import {DEFAULT_LAB_LOCALE,labStrings,normalizeLabLocale} from './lab-i18n.js';
const fallback=[{qbVersion:'4.1.0',webApiVersion:'2.0.0',officialWeiGSupport:false},{qbVersion:'4.1.1',webApiVersion:'2.0.1',officialWeiGSupport:false},{qbVersion:'4.1.2',webApiVersion:'2.0.2',officialWeiGSupport:false},{qbVersion:'4.1.3',webApiVersion:'2.1.0',officialWeiGSupport:false},{qbVersion:'4.1.9.1',webApiVersion:'2.2.1',officialWeiGSupport:true},{qbVersion:'4.2.0',webApiVersion:'2.3.0',officialWeiGSupport:true},{qbVersion:'5.2.3',webApiVersion:'2.15.1',officialWeiGSupport:true}];
const form=document.querySelector('#launch-form'),branchSelect=document.querySelector('#branch'),versionSelect=document.querySelector('#qb-version'),status=document.querySelector('#catalog-status'),facts=document.querySelector('#version-facts');let catalog=fallback;
const LAB_LOCALE_KEYS=['weig.localeBootstrap'],LAB_UI_LOCALE_KEY='weig.lab.locale',query=new URLSearchParams(location.search),selectUi=new Map();let locale=initialLocale();
function parts(v){return String(v).split('.').map(x=>Number.parseInt(x,10)||0)}function compare(a,b){const aa=parts(a.qbVersion),bb=parts(b.qbVersion),n=Math.max(aa.length,bb.length);for(let i=0;i<n;i++){const d=(aa[i]||0)-(bb[i]||0);if(d)return d}return 0}
function initialLocale(){let saved='';try{saved=localStorage.getItem(LAB_UI_LOCALE_KEY)||''}catch{}return normalizeLabLocale(query.get('lang')||saved||navigator.languages?.[0]||navigator.language||DEFAULT_LAB_LOCALE)}
function tr(key,vars={}){let value=String(labStrings(locale)[key]??key);for(const [name,replacement] of Object.entries(vars))value=value.replaceAll(`{${name}}`,String(replacement));return value}
function applyLocale(next){locale=normalizeLabLocale(next);document.documentElement.lang=locale;document.querySelectorAll('[data-i18n]').forEach(node=>{node.textContent=tr(node.dataset.i18n)});document.querySelectorAll('[data-i18n-html]').forEach(node=>{node.innerHTML=tr(node.dataset.i18nHtml)});document.querySelectorAll('[data-lab-locale]').forEach(node=>node.classList.toggle('is-active',node.dataset.labLocale===locale));try{localStorage.setItem(LAB_UI_LOCALE_KEY,locale)}catch{}for(const ui of selectUi.values())ui.refresh();renderCatalogStatus();renderFacts()}
function enhanceSelect(select){select.classList.add('lab-select-native');const host=document.createElement('div');host.className='lab-select';const trigger=document.createElement('button');trigger.type='button';trigger.className='lab-select__trigger';trigger.setAttribute('aria-haspopup','listbox');trigger.setAttribute('aria-expanded','false');const value=document.createElement('span');value.className='lab-select__value';const menu=document.createElement('div');menu.className='lab-select__menu';menu.setAttribute('role','listbox');menu.hidden=true;trigger.append(value);host.append(trigger,menu);select.insertAdjacentElement('afterend',host);
 function close(){host.classList.remove('is-open');menu.hidden=true;trigger.setAttribute('aria-expanded','false')}
 function sync(){const option=select.selectedOptions?.[0];value.textContent=option?.textContent||select.value}
 function refresh(){menu.textContent='';for(const option of select.options){const button=document.createElement('button');button.type='button';button.className='lab-select__option';button.dataset.value=option.value;button.setAttribute('role','option');button.setAttribute('aria-selected',option.selected?'true':'false');button.textContent=option.textContent;button.addEventListener('click',()=>{select.value=option.value;select.dispatchEvent(new Event('change',{bubbles:true}));close()});menu.append(button)}sync()}
 trigger.addEventListener('click',event=>{event.stopPropagation();const open=menu.hidden;for(const item of selectUi.values())item.close();menu.hidden=!open;host.classList.toggle('is-open',open);trigger.setAttribute('aria-expanded',open?'true':'false');if(open)menu.querySelector('[aria-selected="true"]')?.focus()});
 select.addEventListener('change',()=>{refresh()});document.addEventListener('click',close);const api={refresh,close};selectUi.set(select,api);refresh();return api}
function renderCatalogStatus(){status.textContent=catalog===fallback?tr('catalogBootstrap'):tr('catalogReady',{count:catalog.length})}
function renderFacts(){const item=catalog.find(x=>x.qbVersion===versionSelect.value)||catalog.at(-1);if(!item)return;facts.textContent=`qBittorrent ${item.qbVersion} · WebAPI ${item.webApiVersion||'unknown'} · ${item.officialWeiGSupport===false?tr('earlyRange'):tr('officialRange')}${item.tag?` · ${item.tag}`:''}`}
function render(){const requested=query.get('qb');catalog=[...catalog].sort(compare);versionSelect.innerHTML=catalog.map(x=>`<option value="${x.qbVersion}">${x.qbVersion}</option>`).join('');versionSelect.value=catalog.some(x=>x.qbVersion===requested)?requested:(catalog.at(-1)?.qbVersion||'5.2.3');selectUi.get(versionSelect)?.refresh();renderFacts()}
async function loadCatalog(){status.textContent=tr('catalogLoading');try{const response=await fetch('../metadata/qb-releases.json',{cache:'no-store'});if(!response.ok)throw new Error(String(response.status));const data=await response.json();if(!Array.isArray(data)||!data.length)throw new Error('empty catalog');catalog=data}catch{catalog=fallback}render();renderCatalogStatus()}
function resetLabLocaleBootstrap(){for(const key of LAB_LOCALE_KEYS){try{localStorage.removeItem(key)}catch{}}}
function applyQueryDefaults(){const branch=query.get('branch');branchSelect.value=branch==='main'?'main':'dev';for(const [name,id] of [['count','torrent-count'],['scenario','scenario'],['seed','seed'],['clean','clean']]){const value=query.get(name),node=document.getElementById(id);if(value!=null&&node){if(node.tagName==='SELECT'&&![...node.options].some(option=>option.value===value))continue;node.value=value}}}
document.querySelectorAll('[data-lab-locale]').forEach(button=>button.addEventListener('click',()=>applyLocale(button.dataset.labLocale)));
applyQueryDefaults();document.querySelectorAll('select').forEach(enhanceSelect);applyLocale(locale);
versionSelect.addEventListener('change',renderFacts);
form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form),branch=String(data.get('branch')||'dev'),sim=query.get('sim')||crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;resetLabLocaleBootstrap();const params=new URLSearchParams({sim,qb:String(data.get('qb')||'5.2.3'),count:String(data.get('count')||'5000'),scenario:String(data.get('scenario')||'mixed'),seed:String(data.get('seed')||'20260905'),clean:String(data.get('clean')||'0')});const target=new URL(`../${branch}/app/`,location.href);target.search=params.toString();target.hash=location.hash;location.href=target.href});
loadCatalog();
