import { chromium } from 'playwright';
import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url));
const webRoot=path.resolve(here,'../webui/private');
const matrix=JSON.parse(await fs.readFile(path.join(here,'fixtures/qb-compat-matrix.json'),'utf8'));
const host='127.0.0.1',port=8768;
const variants={};
for(const [index,fixture] of matrix.fixtures.entries())variants[`f${index}`]={...fixture,qb:fixture.qbVersion==='master'?'v5.3.0alpha1':fixture.qbVersion.includes('synthetic')?'v6.0.0':`v${fixture.qbVersion}`,api:fixture.webApiVersion.replace('-synthetic','')};
const viewports=[{width:390,height:844,label:'mobile'},{width:1366,height:768,label:'desktop'},{width:1920,height:1080,label:'wide'}];
const torrents=Array.from({length:125},(_,i)=>({hash:(i+1).toString(16).padStart(40,'0'),name:`Fixture Torrent ${String(i+1).padStart(3,'0')}`,size:1048576*(i+1),progress:.45,dlspeed:1000+i,upspeed:200+i,eta:3600,state:'downloading',ratio:.25,tracker:'https://tracker.example/announce',category:'fixture',added_on:100000+i,save_path:'/downloads/fixture'}));
const advancedPrefs={slow_torrent_inactive_timer:60,slow_torrent_dl_rate_threshold:2,slow_torrent_ul_rate_threshold:2,send_buffer_watermark:500,send_buffer_low_watermark:10,send_buffer_watermark_factor:50,socket_backlog_size:30,socket_receive_buffer_size:0,socket_send_buffer_size:0,stop_tracker_timeout:2,upnp_lease_duration:0,torrent_file_size_limit:104857600,save_resume_data_interval:60,disk_cache_ttl:60,checking_memory_use:32,async_io_threads:10,file_pool_size:40,upload_slots_behavior:0,upload_choking_algorithm:1,utp_tcp_mixed_mode:0,torrent_stop_condition:'None',torrent_content_remove_option:'Delete',hostname_cache_ttl:1200};
function assert(ok,msg){if(!ok)throw new Error(msg);}
function writeJson(res,v){res.writeHead(200,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(v));}
function writeText(res,v){res.writeHead(200,{'content-type':'text/plain; charset=utf-8','cache-control':'no-store'});res.end(String(v));}
function handleApi(req,res,name,apiPath,url){const v=variants[name];if(apiPath==='app/version')return writeText(res,v.qb);if(apiPath==='app/webapiVersion')return writeText(res,v.api);if(apiPath==='app/preferences')return writeJson(res,{web_ui_port:8080,web_ui_upnp:false,alternative_webui_enabled:true,alternative_webui_path:'/config/weigg-qb-webui',...advancedPrefs});if(apiPath==='app/buildInfo')return writeJson(res,{});if(apiPath==='transfer/info')return writeJson(res,{dl_info_speed:12345,up_info_speed:6789,connection_status:'connected',dht_nodes:12,total_peer_connections:4});if(apiPath==='sync/maindata')return writeJson(res,{rid:1,full_update:true,torrents:{},categories:{},tags:[],server_state:{connection_status:'connected',dl_info_speed:12345,up_info_speed:6789,dht_nodes:12,total_peer_connections:4}});if(apiPath==='torrents/info'){const hashes=url.searchParams.get('hashes');if(hashes){const set=new Set(hashes.split('|'));return writeJson(res,torrents.filter(t=>set.has(t.hash)));}const limit=Math.max(0,Number(url.searchParams.get('limit')||0)),offset=Math.max(0,Number(url.searchParams.get('offset')||0));return writeJson(res,limit?torrents.slice(offset,offset+limit):torrents.slice(offset));}if(apiPath==='torrents/properties')return writeJson(res,{save_path:'/downloads/fixture',total_size:1048576,total_downloaded:500000,total_uploaded:100000,share_ratio:.2,nb_connections:4,seeds:2,peers:3,addition_date:1788140000,completion_date:-1,created_by:'fixture',pieces_num:20,piece_size:65536});if(apiPath==='torrents/files'||apiPath==='torrents/trackers'||apiPath==='sync/torrentPeers'||apiPath==='torrents/webseeds')return writeJson(res,apiPath==='sync/torrentPeers'?{peers:{}}:[]);if(apiPath==='torrents/categories')return writeJson(res,{});if(apiPath==='torrents/tags')return writeJson(res,[]);if(apiPath==='rss/items')return writeJson(res,{});if(apiPath==='search/plugins')return writeJson(res,[]);if(apiPath==='log/main'||apiPath==='log/peers')return writeJson(res,[]);if(req.method==='POST'){res.writeHead(200,{'cache-control':'no-store'});return res.end('');}return writeJson(res,{});}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon'};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${host}:${port}`),m=url.pathname.match(/^\/(f\d+)(?:\/(.*))?$/);if(!m||!variants[m[1]]){res.writeHead(404);return res.end('not found');}const name=m[1],relative=m[2]||'';if(relative.startsWith('api/v2/'))return handleApi(req,res,name,relative.slice(7),url);if(relative==='weigg-install.json')return writeJson(res,{version:'0.3.6',gitSha:'1234567890abcdef1234567890abcdef12345678',container:'fixture',qbPath:'/config/weigg-qb-webui',hostPath:'/root/qbittorrent/config/weigg-qb-webui',installedAt:'2026-08-31T11:00:00Z',installer:'linux'});const requested=relative||'index.html',file=path.resolve(webRoot,requested);if(!(file===webRoot||file.startsWith(webRoot+path.sep))){res.writeHead(403);return res.end('forbidden');}const body=await fs.readFile(file);res.writeHead(200,{'content-type':mime[path.extname(file).toLowerCase()]||'application/octet-stream','cache-control':'no-store'});res.end(body);}catch(e){res.writeHead(e?.code==='ENOENT'?404:500,{'content-type':'text/plain; charset=utf-8'});res.end(String(e));}});
await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,host,resolve);});

async function openNative(page,id){const root=page.locator(`#${id} + .ui-select`);await root.locator('.ui-select__trigger').click();await page.waitForFunction(()=>{const m=document.querySelector('#weigg-floating-layer .ui-select__menu:not([hidden])');if(!m)return false;const r=m.getBoundingClientRect();return getComputedStyle(m).visibility==='visible'&&r.width>0&&r.height>0&&r.left>=7;},{},{timeout:1500});return page.locator('#weigg-floating-layer .ui-select__menu:not([hidden])');}
async function chooseNative(page,id,value){await openNative(page,id);await page.locator(`#weigg-floating-layer .ui-select__option[data-value="${value}"]`).click();}
async function assertFloatingBounds(page,label){const r=await page.evaluate(()=>{const m=document.querySelector('#weigg-floating-layer .ui-select__menu:not([hidden])');if(!m)return null;const b=m.getBoundingClientRect();return {left:b.left,right:b.right,top:b.top,bottom:b.bottom,width:innerWidth,height:innerHeight,parent:m.parentElement?.id||''};});assert(r,`${label}: floating menu missing`);assert(r.parent==='weigg-floating-layer',`${label}: menu is not portaled`);assert(r.left>=7,`${label}: clipped left ${r.left}`);assert(r.right<=r.width-7,`${label}: clipped right ${r.right}/${r.width}`);assert(r.top>=7,`${label}: clipped top ${r.top}`);assert(r.bottom<=r.height-7,`${label}: clipped bottom ${r.bottom}/${r.height}`);}
async function waitPage(page,n){await page.waitForFunction(x=>new RegExp(`(?:Page|第)\\s*${x}(?:\\s|\\/)`).test(document.querySelector('#page-label')?.textContent||''),n,{timeout:3000});}
async function visibleHash(list){return list.evaluate(node=>{const b=node.getBoundingClientRect(),rows=[...node.querySelectorAll('[data-hash]')],v=rows.find(row=>{const r=row.getBoundingClientRect();return r.top>=b.top+4&&r.bottom<=b.bottom-4;});return (v||rows[0])?.dataset.hash||'';});}
function titleFor(page,hash,mobile){return page.locator(`${mobile?'.torrent-mobile-card':'.torrent-row'}[data-hash="${hash}"] ${mobile?'.mobile-card-title':'.torrent-title'}`);}

const browser=await chromium.launch({headless:true});
try{
  for(const [name,variant] of Object.entries(variants))for(const vp of viewports){
    const context=await browser.newContext({viewport:{width:vp.width,height:vp.height},locale:'en-US',timezoneId:'UTC'}),page=await context.newPage(),errors=[];page.on('console',m=>{if(m.type()==='error'&&!/favicon|Wei\.G\.ico/i.test(m.text()))errors.push(m.text());});page.on('pageerror',e=>errors.push(String(e)));
    await page.goto(`http://${host}:${port}/${name}/#/`,{waitUntil:'networkidle'});await page.waitForSelector('.torrent-title,.torrent-mobile-card');await page.waitForFunction(()=>document.documentElement.dataset.v036==='1');const tag=`${variant.qbVersion}/${vp.label}`;
    const p=await page.evaluate(()=>{const n=document.querySelector('#page-size'),c=n?.nextElementSibling,m=document.querySelector('.brand__mark');return {native:n?.classList.contains('ui-native-select'),custom:c?.classList.contains('ui-select'),ambient:m?.classList.contains('ambient-mark'),orbit:!!m?.querySelector('.ambient-mark__orbit'),sparks:m?.querySelectorAll('.ambient-mark__spark').length||0,scrollWidth:document.documentElement.scrollWidth,innerWidth,timezone:!!document.querySelector('[data-status-timezone]'),compat:document.querySelector('#compat-mode')?.textContent||''};});
    assert(p.native&&p.custom,`${tag}: canonical native-select bridge missing`);assert(p.ambient&&p.orbit&&p.sparks>=4,`${tag}: AmbientMark missing`);assert(p.scrollWidth<=p.innerWidth+1,`${tag}: horizontal overflow`);assert(p.timezone,`${tag}: global timezone missing`);if(variant.role==='forward-major-sentinel')assert(!/unsupported/i.test(p.compat),`${tag}: future major hard-rejected`);assert(await page.evaluate(()=>WeiG.AmbientMark.trigger('.brand__mark','orbit-spark')),`${tag}: ambient deterministic trigger failed`);
    await openNative(page,'page-size');await assertFloatingBounds(page,`${tag}/page-size`);await page.keyboard.press('Escape');await chooseNative(page,'page-size','20');await page.waitForFunction(()=>document.querySelector('#page-size')?.value==='20');await page.locator('#next-btn').click();await waitPage(page,2);
    const list=page.locator('#torrent-list');await list.evaluate(n=>{n.scrollTop=160;});await page.waitForTimeout(80);const before=await list.evaluate(n=>n.scrollTop),hash=await visibleHash(list);assert(hash,`${tag}: no visible row`);const mobile=vp.width<=820;await titleFor(page,hash,mobile).click();await page.waitForFunction(()=>WeiG.Router.route().name==='torrent');await page.waitForSelector('[data-v036-detail-back]');const saved=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('weigg.torrentListContext.v036')||'null'));assert(saved&&Math.abs(Number(saved.scrollTop)-before)<=2,`${tag}: captured scroll ${before} -> ${saved?.scrollTop}`);assert(await page.evaluate(()=>{const t=document.querySelector('.detail-tabs'),b=t?.querySelector('[data-v036-detail-back]');return !!b&&t.firstElementChild===b;}),`${tag}: Back placement wrong`);await page.locator('[data-v036-detail-back]').click();await page.waitForFunction(()=>WeiG.Router.route().name==='home');await waitPage(page,2);await page.waitForTimeout(180);const after=await list.evaluate(n=>n.scrollTop);assert(Math.abs(after-before)<=8,`${tag}: scroll restore ${before} -> ${after}`);await titleFor(page,hash,mobile).click();await page.waitForFunction(()=>WeiG.Router.route().name==='torrent');await page.keyboard.press('Escape');await page.waitForFunction(()=>WeiG.Router.route().name==='home');await waitPage(page,2);
    if(vp.label==='desktop'){
      await page.locator('[data-route="settings"]').first().click();await page.waitForFunction(()=>WeiG.Router.route().name==='settings');await page.waitForFunction(()=>!!WeiG.AdvancedSettingsV036,{},{timeout:2500});await page.locator('#settings-tabs [data-settings-tab="advanced"]').click();await page.waitForSelector('#settings-content [data-setting-key="slow_torrent_inactive_timer"]');
      const a=await page.evaluate(()=>({
        inactive:document.querySelector('[data-setting-key="slow_torrent_inactive_timer"] strong')?.textContent||'',
        dl:document.querySelector('[data-setting-key="slow_torrent_dl_rate_threshold"] strong')?.textContent||'',
        watermark:document.querySelector('[data-setting-key="send_buffer_watermark"] strong')?.textContent||'',
        socket:document.querySelector('[data-setting-key="socket_backlog_size"] strong')?.textContent||'',
        recvTitle:document.querySelector('[data-setting-key="socket_receive_buffer_size"] strong')?.textContent||'',
        recvDescription:document.querySelector('[data-setting-key="socket_receive_buffer_size"] small')?.textContent||'',
        recvValue:document.querySelector('[data-setting-key="socket_receive_buffer_size"] input')?.value||'',
        torrentLimitTitle:document.querySelector('[data-setting-key="torrent_file_size_limit"] strong')?.textContent||'',
        torrentLimitValue:document.querySelector('[data-setting-key="torrent_file_size_limit"] input')?.value||'',
        enums:document.querySelectorAll('[data-setting-key="upload_choking_algorithm"] .ui-select,[data-setting-key="upload_slots_behavior"] .ui-select,[data-setting-key="utp_tcp_mixed_mode"] .ui-select,[data-setting-key="torrent_content_remove_option"] .ui-select').length,
        tz:document.querySelector('.status-timezone .ui-select__value')?.textContent||''
      }));
      assert(/\(s\)/.test(a.inactive),`${tag}: timer unit missing`);assert(/\(KiB\/s\)/.test(a.dl),`${tag}: rate unit missing`);assert(/\(KiB\)/.test(a.watermark),`${tag}: watermark unit missing`);assert(/\(connections\)/.test(a.socket),`${tag}: socket backlog unit missing`);assert(/\(KiB\)/.test(a.recvTitle),`${tag}: socket receive display unit missing: ${a.recvTitle}`);assert(/0 = System default/.test(a.recvDescription),`${tag}: socket receive zero semantic missing`);assert(a.recvValue==='0',`${tag}: socket receive zero conversion changed value`);assert(/\(MiB\)/.test(a.torrentLimitTitle),`${tag}: torrent-file limit display unit missing: ${a.torrentLimitTitle}`);assert(a.torrentLimitValue==='100',`${tag}: 104857600-byte torrent limit must display as 100 MiB, got ${a.torrentLimitValue}`);assert(a.enums===4,`${tag}: Advanced readable enums missing (${a.enums})`);assert(/^UTC[+-]\d{2}:\d{2}\s*·/.test(a.tz),`${tag}: status timezone label invalid: ${a.tz}`);
    }
    assert(errors.length===0,`${tag}: browser errors: ${errors.join(' | ')}`);await context.close();
  }
  const context=await browser.newContext({viewport:{width:1366,height:768},reducedMotion:'reduce'}),page=await context.newPage();await page.goto(`http://${host}:${port}/f8/#/`,{waitUntil:'networkidle'});await page.waitForFunction(()=>document.documentElement.dataset.v036==='1');assert((await page.evaluate(()=>WeiG.AmbientMark.trigger('.brand__mark','orbit-spark')))===false,'Reduced Motion must disable AmbientMark');await context.close();
  console.log(`v0.3.6 representative browser regression passed for ${Object.keys(variants).length} compatibility nodes × ${viewports.length} viewports.`);
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
