import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url));const root=path.resolve(here,'..');const matrix=JSON.parse(fs.readFileSync(path.join(here,'fixtures/qb-compat-matrix.json'),'utf8'));const source=fs.readFileSync(path.join(root,'webui/private/scripts/qb-client.js'),'utf8');
class TestFormData{constructor(){this.entries=[];}append(name,value,filename){this.entries.push({name,value,filename});}}
let activeFixture=null;
function versionAtLeast(actual,required){const a=String(actual).split('.').map(x=>Number.parseInt(x,10)||0),b=String(required).split('.').map(x=>Number.parseInt(x,10)||0),n=Math.max(a.length,b.length);for(let i=0;i<n;i++){if((a[i]||0)>(b[i]||0))return true;if((a[i]||0)<(b[i]||0))return false;}return true;}
function fixtureFacts(fixture){const c=fixture?.capabilities||{},modern=c.startStop===true,legacy=c.pauseResume===true;return{filters:modern?['stopped','running']:legacy?['paused','resumed']:[],actions:modern?{start:'start',stop:'stop'}:legacy?{start:'resume',stop:'pause'}:{}};}
const capabilityRegistry={
  upstreamTorrentFilter(value){const facts=fixtureFacts(activeFixture);if(value==='stopped')return facts.filters.includes('stopped')?'stopped':facts.filters.includes('paused')?'paused':null;if(value==='running')return facts.filters.includes('running')?'running':facts.filters.includes('resumed')?'resumed':null;return value;},
  resolveTorrentAction(kind){return fixtureFacts(activeFixture).actions[kind]||null;},
  resolveTorrentActionDescriptor(kind){const endpoint=this.resolveTorrentAction(kind);return endpoint?{sourceAction:`fixture:${endpoint}`,endpoint,parameters:['hashes'],required:['hashes'],optional:[]}:null;},
  sourceActionDescriptor(action){
    if(action!=='torrentscontroller.h:editTrackerAction'||!activeFixture?.realRelease)return null;
    const modern=versionAtLeast(activeFixture.webApiVersion.replace('-synthetic',''),'2.13.0');
    const parameters=modern?['hash','url','newUrl']:['hash','origUrl','newUrl'];
    return{sourceAction:action,endpoint:'editTracker',parameters,required:parameters.slice(),optional:[]};
  },
  isCertified(){return !!activeFixture?.realRelease;}
};
const sandbox={console,URLSearchParams,FormData:TestFormData,Blob,fetch:async()=>{throw new Error('Unexpected fetch');},window:{WeiG:{CapabilityRegistry:capabilityRegistry,util:{form(obj){const p=new URLSearchParams();for(const [k,v] of Object.entries(obj||{}))if(v!==undefined&&v!==null)p.append(k,String(v));return p.toString();}},I18n:{getLocale:()=> 'en'}}}};sandbox.window.window=sandbox.window;vm.runInNewContext(source,sandbox,{filename:'qb-client.js'});const Client=sandbox.window.WeiG.QBClient;

async function detect(fixture){const c=new Client();c.request=async p=>{if(p==='app/version')return fixture.qbVersion==='master'?'v5.3.0alpha1':fixture.qbVersion.includes('synthetic')?'v6.0.0':`v${fixture.qbVersion}`;if(p==='app/webapiVersion')return fixture.webApiVersion.replace('-synthetic','');throw new Error(`Unexpected detect endpoint ${p}`);};await c.detect();return c;}
function capture(client){const calls=[];client.request=async(path,options={})=>{calls.push({path,options});return null;};return calls;}
function extractLoginClassifier(file){const text=fs.readFileSync(file,'utf8');const match=text.match(/function classifyLogin\(x\)\{[\s\S]*?return'unexpected';\}/);assert.ok(match,`${path.relative(root,file)} must expose login response classifier`);return vm.runInNewContext(`(${match[0]})`);}
for(const rel of ['webui/public/index.html','webui/public/login.html','webui/private/index.html'])assert.ok(fs.statSync(path.join(root,rel)).isFile(),`required Alternate WebUI entry point missing: ${rel}`);
for(const rel of ['webui/public/index.html','webui/public/login.html']){const classify=extractLoginClassifier(path.join(root,rel));assert.equal(classify({status:200,ok:true,text:'Ok.'}),'ok');assert.equal(classify({status:204,ok:true,text:''}),'ok');assert.equal(classify({status:200,ok:true,text:'Fails.'}),'bad');assert.equal(classify({status:401,ok:false,text:'Unauthorized'}),'bad');assert.equal(classify({status:403,ok:false,text:'Forbidden'}),'banned');}

let realCount=0;
for(const fixture of matrix.fixtures){activeFixture=fixture;const c=await detect(fixture),tag=`qB ${fixture.qbVersion} / WebAPI ${fixture.webApiVersion}`;if(fixture.realRelease)realCount++;
  if(/^4\./.test(fixture.qbVersion))assert.equal(c.major,4,`${tag}: major detection`);if(/^5\./.test(fixture.qbVersion)||fixture.qbVersion==='master')assert.equal(c.major,5,`${tag}: major detection`);if(fixture.role==='forward-major-sentinel')assert.equal(c.major,6,`${tag}: future-major detection`);
  assert.deepEqual(Object.keys(c.capabilities),['certified'],`${tag}: QBClient.detect must not own feature/version capability truth`);assert.equal(c.capabilities.certified,false,`${tag}: QBClient.detect must never self-certify`);
  if(fixture.realRelease){const expectedStart=capabilityRegistry.resolveTorrentAction('start'),expectedStop=capabilityRegistry.resolveTorrentAction('stop');assert.ok(expectedStart&&expectedStop,`${tag}: fixture must declare start/stop capability facts`);const actionCalls=capture(c);await c.resume('abc');await c.pause('abc');assert.equal(actionCalls[0].path,`torrents/${expectedStart}`,`${tag}: exact start/resume dispatch`);assert.equal(actionCalls[1].path,`torrents/${expectedStop}`,`${tag}: exact stop/pause dispatch`);const expectedStopped=capabilityRegistry.upstreamTorrentFilter('stopped');assert.ok(expectedStopped,`${tag}: fixture must declare stopped filter fact`);const filterCalls=capture(c);await c.getTorrents({filter:'stopped'});assert.match(filterCalls[0].path,new RegExp(`filter=${expectedStopped}`),`${tag}: stopped/paused HTTP boundary`);const trackerEditUrl=versionAtLeast(fixture.webApiVersion.replace('-synthetic',''),'2.13.0');const editCalls=capture(c);await c.editTracker('hash','https://old.invalid/announce','https://new.invalid/announce');const form=editCalls[0].options.form;if(trackerEditUrl){assert.equal(form.url,'https://old.invalid/announce');assert.equal('origUrl' in form,false);}else{assert.equal(form.origUrl,'https://old.invalid/announce');assert.equal('url' in form,false);}}
}
activeFixture=matrix.fixtures.find(x=>x.realRelease);assert.ok(activeFixture,'matrix must provide one real release for fail-closed contract checks');const contractClient=await detect(activeFixture),contractCalls=capture(contractClient),savedCapabilityRegistry=sandbox.window.WeiG.CapabilityRegistry;sandbox.window.WeiG.CapabilityRegistry=null;await assert.rejects(contractClient.resume('abc'),/compatibility contract is unavailable/i,'start/stop writes must not fall back to a qB major guess when the compatibility owner is missing');await assert.rejects(contractClient.recheck('abc'),/compatibility contract is unavailable/i,'guarded writes must not fall back to a fixed endpoint when the compatibility owner is missing');await assert.rejects(contractClient.getTorrents({filter:'stopped'}),/compatibility contract is unavailable/i,'version-sensitive filters must not fall back to qB major guessing when the compatibility owner is missing');assert.equal(contractCalls.length,0,'missing compatibility owner must produce zero Torrent HTTP requests');sandbox.window.WeiG.CapabilityRegistry=savedCapabilityRegistry;activeFixture=null;
assert.equal(matrix.supportedRange.minimum,'4.1.0','fixture floor must be qB 4.1.0');assert.equal(matrix.fixtures.find(x=>x.qbVersion==='4.6.1')?.webApiVersion,'2.9.3','qB 4.6.1 WebAPI fact must remain 2.9.3');assert.ok(realCount>=20,'representative release gate must cover at least 20 real releases');assert.ok(matrix.releaseGate.length>=22,'release gate must retain broad real + upstream/sentinel coverage');
console.log(`Release compatibility fixture gate passed: ${realCount} representative real-release facts from 4.1.0 plus upstream/sentinel nodes; QBClient detects only version identity, exact action/filter contracts drive transport, and missing compatibility ownership fails closed with zero HTTP.`);
