(function(global){
  'use strict';
  var W=global.WeiG,U=W.util;
  var app={client:new W.QBClient(),filter:'all',page:0,pageSize:50,torrents:[],selected:new Set(),search:'',pollTimer:null,detailHash:'',detailTab:'overview',busy:false,virtual:null};
  var titles={all:'全部种子',downloading:'下载中',seeding:'做种',completed:'已完成',paused:'已暂停',active:'活动',stalled:'停滞',errored:'错误'};
  function setStatus(msg){U.$('status-message').textContent=msg||'';}
  function toggleLoading(on){U.$('list-loading').classList.toggle('is-hidden',!on);if(on)U.$('list-empty').classList.add('is-hidden');}
  function updateSelection(){var has=app.selected.size>0;['resume-btn','pause-btn','delete-btn'].forEach(function(id){U.$(id).disabled=!has;});}
  function normalizeFilter(f){return f==='seeding'?'seeding':f;}
  function filteredTorrents(){if(!app.search)return app.torrents;var q=app.search.toLocaleLowerCase();return app.torrents.filter(function(t){return String(t.name||'').toLocaleLowerCase().includes(q);});}
  function renderList(){var list=U.$('torrent-list'),items=filteredTorrents();list.textContent='';var frag=document.createDocumentFragment();items.forEach(function(t){frag.appendChild(W.Components.torrentRow(t,app.selected.has(t.hash),{select:function(hash,on){if(on)app.selected.add(hash);else app.selected.delete(hash);updateSelection();},open:openDetail}));});list.appendChild(frag);U.$('list-empty').classList.toggle('is-hidden',items.length!==0||app.busy);U.$('page-label').textContent='第 '+(app.page+1)+' 批 · '+app.pageSize+'/批';U.$('prev-btn').disabled=app.page===0||app.busy;U.$('next-btn').disabled=app.torrents.length<app.pageSize||app.busy;var start=app.torrents.length?app.page*app.pageSize+1:0,end=app.page*app.pageSize+app.torrents.length;U.$('page-range').textContent=start+'–'+end;updateSelection();}
  async function loadPage(silent){if(app.busy&&!silent)return;app.busy=true;if(!silent)toggleLoading(true);try{var data=await app.client.getTorrents({filter:normalizeFilter(app.filter),sort:'added_on',reverse:'true',limit:app.pageSize,offset:app.page*app.pageSize});app.torrents=Array.isArray(data)?data:[];var live=new Set(app.torrents.map(function(t){return t.hash;}));Array.from(app.selected).forEach(function(h){if(!live.has(h))app.selected.delete(h);});renderList();U.$('last-refresh').textContent=U.time();setStatus('已加载 '+app.torrents.length+' 个种子');}catch(e){setStatus('读取种子失败');if(!silent)W.toast('读取种子失败：'+e.message,'danger');if(e.status!==403)renderList();}finally{app.busy=false;toggleLoading(false);renderList();}}
  async function loadTransfer(){try{var info=await app.client.getTransferInfo();var dl=info&&((info.dl_info_speed!=null?info.dl_info_speed:info.dl_info_speed)||0),up=info&&((info.up_info_speed!=null?info.up_info_speed:info.up_info_speed)||0);U.$('dl-speed').textContent=U.formatSpeed(dl);U.$('up-speed').textContent=U.formatSpeed(up);U.$('status-dl').textContent=U.formatSpeed(dl);U.$('status-up').textContent=U.formatSpeed(up);U.$('connection-status').textContent=info&&info.connection_status||'Connected';}catch(_e){U.$('connection-status').textContent='异常';}}
  function schedulePoll(){clearTimeout(app.pollTimer);var delay=document.hidden?10000:2000;app.pollTimer=setTimeout(async function(){if(W.Router.route().name==='home')await loadPage(true);await loadTransfer();schedulePoll();},delay);}
  function setFilter(filter){app.filter=filter;app.page=0;app.selected.clear();document.querySelectorAll('.nav-item').forEach(function(el){el.classList.toggle('is-active',el.dataset.filter===filter);});U.$('page-title').textContent=titles[filter]||'种子';closeDrawer();loadPage(false);}
  function setView(name){U.$('list-view').classList.toggle('is-active',name==='home');U.$('detail-view').classList.toggle('is-active',name==='torrent');U.$('back-btn').classList.toggle('is-hidden',name==='home');}
  async function route(){var r=W.Router.route();if(r.name==='torrent'&&r.id){setView('torrent');app.detailHash=decodeURIComponent(r.id);app.detailTab=r.tab||'overview';await loadDetailHeader();await loadDetailTab(app.detailTab);}else{setView('home');if(!app.torrents.length)loadPage(false);}}
  async function openDetail(hash){W.Router.detail(hash,'overview');}
  async function loadDetailHeader(){var t=app.torrents.find(function(x){return x.hash===app.detailHash;});if(!t){try{var a=await app.client.getTorrents({hashes:app.detailHash,limit:1});t=a&&a[0];}catch(_e){}}if(!t){U.$('detail-title').textContent='种子详情';return;}U.$('detail-title').textContent=t.name||'种子详情';var s=W.Components.state(t.state);U.$('detail-state').textContent=s[0];U.$('detail-state').dataset.tone=s[1];var p=U.clamp(U.percent(t.progress),0,100);U.$('detail-progress-bar').style.width=p+'%';U.$('detail-progress-text').textContent=p+'%';}
  function activateTab(tab){document.querySelectorAll('.tab').forEach(function(el){el.classList.toggle('is-active',el.dataset.tab===tab);});app.detailTab=tab;}
  async function loadDetailTab(tab){activateTab(tab);var root=U.$('detail-content');root.textContent='';var loading=document.createElement('div');loading.className='loading-state';loading.innerHTML='<div class="spinner"></div><span>正在加载…</span>';root.appendChild(loading);try{if(tab==='overview')await renderOverview(root);else if(tab==='files')await renderFiles(root);else if(tab==='trackers')await renderTrackers(root);else if(tab==='peers')await renderPeers(root);}catch(e){root.textContent='';var p=document.createElement('p');p.className='muted';p.textContent='加载失败：'+e.message;root.appendChild(p);W.toast('详情加载失败','danger');}}
  async function renderOverview(root){var p=await app.client.properties(app.detailHash);root.textContent='';var grid=document.createElement('div');grid.className='kv-grid';var fields=[['保存路径',p.save_path],['总大小',U.formatBytes(p.total_size)],['已下载',U.formatBytes(p.total_downloaded)],['已上传',U.formatBytes(p.total_uploaded)],['分享率',U.formatRatio(p.share_ratio)],['连接数',p.nb_connections],['Seeds',p.seeds],['Peers',p.peers],['添加时间',p.addition_date?new Date(p.addition_date*1000).toLocaleString():'—'],['完成时间',p.completion_date>0?new Date(p.completion_date*1000).toLocaleString():'—'],['创建者',p.created_by||'—'],['Pieces',p.pieces_num!=null?(p.pieces_num+' × '+U.formatBytes(p.piece_size)):'—']];fields.forEach(function(x){grid.appendChild(W.Components.kv(x[0],x[1]));});root.appendChild(grid);}
  function makeVirtual(root,items,rowHeight,render){root.textContent='';var note=document.createElement('p');note.className='section-note';note.textContent='共 '+items.length+' 项；仅挂载可视区域 DOM。';var box=document.createElement('div');root.append(note,box);app.virtual=new W.VirtualList(box,{rowHeight:rowHeight,overscan:6,renderRow:render});app.virtual.setItems(items);}
  async function renderFiles(root){var items=await app.client.files(app.detailHash);makeVirtual(root,items||[],46,function(f){var row=document.createElement('div');var name=document.createElement('span'),size=document.createElement('span'),progress=document.createElement('span');name.textContent=f.name||'—';size.textContent=U.formatBytes(f.size);progress.textContent=U.percent(f.progress)+'%';row.append(name,size,progress);return row;});}
  async function renderTrackers(root){var items=await app.client.trackers(app.detailHash);makeVirtual(root,items||[],46,function(t){var row=document.createElement('div');var url=document.createElement('span'),status=document.createElement('span'),msg=document.createElement('span');url.textContent=t.url||'—';status.textContent='状态 '+(t.status==null?'—':t.status);msg.textContent=t.msg||'';row.append(url,status,msg);return row;});}
  async function renderPeers(root){var items=await app.client.peers(app.detailHash);makeVirtual(root,items||[],46,function(p){var row=document.createElement('div');var ip=document.createElement('span'),client=document.createElement('span'),speed=document.createElement('span');ip.textContent=(p.ip||p.__key||'—')+(p.port?':'+p.port:'');client.textContent=p.client||'—';speed.textContent='↓ '+U.formatSpeed(p.dl_speed)+' / ↑ '+U.formatSpeed(p.up_speed);row.append(ip,client,speed);return row;});}
  async function action(kind){if(!app.selected.size)return;var hashes=U.hashes(app.selected);try{if(kind==='resume')await app.client.resume(hashes);if(kind==='pause')await app.client.pause(hashes);W.toast(kind==='resume'?'已发送开始命令':'已发送暂停命令');await loadPage(false);}catch(e){W.toast('操作失败：'+e.message,'danger');}}
  function openDelete(){if(!app.selected.size)return;U.$('delete-copy').textContent='将删除 '+app.selected.size+' 个选中的种子。';U.$('delete-files').checked=false;U.$('delete-dialog').showModal();}
  async function confirmDelete(){var hashes=U.hashes(app.selected);if(!hashes)return;var btn=U.$('delete-confirm');btn.disabled=true;try{await app.client.delete(hashes,U.$('delete-files').checked);U.$('delete-dialog').close();app.selected.clear();W.toast('删除命令已发送');await loadPage(false);}catch(e){W.toast('删除失败：'+e.message,'danger');}finally{btn.disabled=false;}}
  function openAdd(){U.$('torrent-urls').value='';U.$('torrent-files').value='';U.$('add-dialog').showModal();setTimeout(function(){U.$('torrent-urls').focus();},50);}
  async function submitAdd(){var urls=U.$('torrent-urls').value,files=U.$('torrent-files').files;if(!urls.trim()&&!files.length){W.toast('请输入 Magnet/URL 或选择 .torrent 文件','danger');return;}var btn=U.$('add-submit');btn.disabled=true;btn.textContent='添加中…';try{var result=await app.client.add(urls,files,U.$('save-path').value);if(result&&String(result).trim()!=='Ok.')throw new Error(String(result));U.$('add-dialog').close();W.toast('种子已添加');app.page=0;await loadPage(false);}catch(e){W.toast('添加失败：'+e.message,'danger');}finally{btn.disabled=false;btn.textContent='添加';}}
  function toggleTheme(){var html=document.documentElement,next=html.dataset.theme==='light'?'dark':'light';html.dataset.theme=next;localStorage.setItem('weigg-theme',next);}
  function openDrawer(){U.$('sidebar').classList.add('is-open');U.$('drawer-scrim').classList.add('is-open');}
  function closeDrawer(){U.$('sidebar').classList.remove('is-open');U.$('drawer-scrim').classList.remove('is-open');}
  function bind(){U.$('filter-nav').addEventListener('click',function(e){var b=e.target.closest('[data-filter]');if(b)setFilter(b.dataset.filter);});U.$('prev-btn').addEventListener('click',function(){if(app.page>0){app.page--;app.selected.clear();loadPage(false);}});U.$('next-btn').addEventListener('click',function(){if(app.torrents.length===app.pageSize){app.page++;app.selected.clear();loadPage(false);}});U.$('refresh-btn').addEventListener('click',function(){loadPage(false);loadTransfer();});U.$('resume-btn').addEventListener('click',function(){action('resume');});U.$('pause-btn').addEventListener('click',function(){action('pause');});U.$('delete-btn').addEventListener('click',openDelete);U.$('delete-confirm').addEventListener('click',confirmDelete);U.$('add-btn').addEventListener('click',openAdd);U.$('empty-add-btn').addEventListener('click',openAdd);U.$('add-submit').addEventListener('click',submitAdd);U.$('back-btn').addEventListener('click',function(){W.Router.back();});U.$('brand-btn').addEventListener('click',W.Router.home.bind(W.Router));U.$('theme-btn').addEventListener('click',toggleTheme);U.$('menu-btn').addEventListener('click',openDrawer);U.$('drawer-scrim').addEventListener('click',closeDrawer);U.$('search-input').addEventListener('input',U.debounce(function(e){app.search=e.target.value.trim();renderList();},120));document.querySelectorAll('.tab').forEach(function(tab){tab.addEventListener('click',function(){W.Router.detail(app.detailHash,tab.dataset.tab);});});U.$('fatal-back').addEventListener('click',function(){W.Router.back();});U.$('fatal-home').addEventListener('click',function(){W.Router.home();U.$('fatal').classList.add('is-hidden');});global.addEventListener('hashchange',route);document.addEventListener('visibilitychange',schedulePoll);global.addEventListener('error',function(e){setStatus('界面出现异常');console.error(e.error||e.message);});}
  async function init(){var saved=localStorage.getItem('weigg-theme');if(saved==='light'||saved==='dark')document.documentElement.dataset.theme=saved;bind();try{await app.client.detect();U.$('qb-version').textContent=app.client.qbVersion;U.$('api-version').textContent=app.client.webApiVersion;U.$('compat-mode').textContent=app.client.capabilities.certified?'已适配':'兼容模式';await Promise.all([loadPage(false),loadTransfer()]);await route();schedulePoll();setStatus('WeiG qB WebUI 已连接');}catch(e){console.error(e);W.fatal(e);}}
  document.addEventListener('DOMContentLoaded',init);
})(window);
