(function(global){
  'use strict';
  var W=global.WeiG,U=W.util,C=W.Components;
  var cfg=W.Config.load();W.Config.apply(cfg);
  var PRIVATE_TRACKER='__weig_private__';
  var app={client:new W.QBClient(),preferences:null,filter:'all',tracker:'',category:'',tag:'',savePath:'',page:0,pageSize:Number(cfg.pageSize)||50,torrents:[],catalog:[],catalogReady:false,catalogBusy:false,catalogError:false,catalogTask:null,hasNext:false,selection:W.Selection,search:'',sort:'added_on',reverse:true,pollTimer:null,detailHash:'',detailTab:'',busy:false,pendingLoad:null,virtual:null,detailVirtual:null,detailProperties:null,detailPropertiesHash:'',columns:W.DataGrid.load(cfg),searchJob:null,searchPoll:null,pageSizeControl:null,facets:{tracker:[],savePath:[],category:[],tag:[]}};
  W.AppState=app;
  var statusMessages={torrent:'',transfer:''};
  function event(name,detail){try{global.dispatchEvent(new CustomEvent(name,{detail:detail||{}}));}catch(_e){}}
  function tr(key,vars){return W.I18n&&W.I18n.t?W.I18n.t(key,vars):String(key||'');}
  function emitLibraryState(reason){event('weig:library-state',{reason:reason||'render',filter:app.filter,tracker:app.tracker,savePath:app.savePath,category:app.category,tag:app.tag,search:app.search,page:app.page,pageSize:app.pageSize,sort:app.sort,reverse:app.reverse,total:totalMatching(),indexing:!app.catalogReady&&!app.catalogError,indexError:app.catalogError});}
  function emitStatusState(status){event('weig:status-state',{connection:status||'—'});}
  function renderStatus(){var node=U.$('status-message');if(node)node.textContent=statusMessages.transfer||statusMessages.torrent||'';}
  function setStatus(source,msg){if(!(source in statusMessages))return;statusMessages[source]=msg||'';renderStatus();}
  function paintText(id,next){var node=U.$(id);if(node&&node.textContent!==next)node.textContent=next;}
  function toggleLoading(on){U.$('list-loading').classList.toggle('is-hidden',!on);if(on)U.$('list-empty').classList.add('is-hidden');}
  function rowHeight(){if(U.isMobile()&&W.MobileAdaptive&&W.MobileAdaptive.mobileRowHeight)return W.MobileAdaptive.mobileRowHeight();if(U.isMobile())return cfg.density==='compact'?76:cfg.density==='comfortable'?92:84;return cfg.density==='compact'?48:cfg.density==='comfortable'?64:56;}
  function resetTorrentScroll(){var list=U.$('torrent-list');if(!list)return;list.__weigVirtualScrollTop=0;list.scrollTop=0;if(list.__weigTorrentVirtual&&list.__weigTorrentVirtual.resetScroll)list.__weigTorrentVirtual.resetScroll();}
  function clearSelection(){if(app.selection)app.selection.clear(true);}
  function privateTrackerSupported(){return !!(W.CapabilityRegistry&&W.CapabilityRegistry.supports&&W.CapabilityRegistry.supports('privateFilter'));}
  function filterMatch(t,state){state=state||app;if(W.TorrentSemantics&&W.TorrentSemantics.matchesStatus&&!W.TorrentSemantics.matchesStatus(t,state.filter||'all',cfg.ptTrackers))return false;if(state.category&&String(t.category||'')!==state.category)return false;if(state.tag){var tags=String(t.tags||'').split(',').map(function(x){return x.trim();});if(tags.indexOf(state.tag)<0)return false;}if(state.tracker){if(state.tracker===PRIVATE_TRACKER){if(!privateTrackerSupported()||!W.TorrentSemantics||!W.TorrentSemantics.isPrivateOrPt||!W.TorrentSemantics.isPrivateOrPt(t,cfg.ptTrackers))return false;}else if(U.normalizeTracker(t.tracker)!==state.tracker)return false;}if(state.savePath&&String(t.save_path||'')!==state.savePath)return false;if(state.search&&String(t.name||'').toLocaleLowerCase().indexOf(String(state.search).toLocaleLowerCase())<0)return false;return true;}
  function sortCatalog(items){var key=app.sort,dir=app.reverse?-1:1;return items.slice().sort(function(a,b){var av=a[key],bv=b[key];if(key==='tracker'){av=U.normalizeTracker(a.tracker);bv=U.normalizeTracker(b.tracker);}if(typeof av==='string'||typeof bv==='string')return String(av||'').localeCompare(String(bv||''))*dir;return ((Number(av)||0)-(Number(bv)||0))*dir;});}
  function matchingCatalog(){return sortCatalog(app.catalog.filter(function(t){return filterMatch(t,app);}));}
  function totalMatching(){return app.catalogReady?app.catalog.filter(function(t){return filterMatch(t,app);}).length:null;}
  function defaultFacetLabel(kind){var key=kind==='tracker'?'tracker.all':kind==='savePath'?'path.all':kind==='category'?'category.all':'tag.all',fallback=kind==='tracker'?tr('tracker.all'):kind==='savePath'?tr('path.all'):kind==='category'?tr('category.all'):tr('tag.all'),value=W.t?W.t(key):'';return value&&value!==key?value:fallback;}
  function facetOptions(kind){var items=app.facets[kind]||[],out=[{value:'',label:defaultFacetLabel(kind)}];if(kind==='tracker'&&privateTrackerSupported())out.push({value:PRIVATE_TRACKER,label:'Private / PT'});items.forEach(function(item){out.push({value:String(item.value),label:item.count==null?String(item.label):String(item.label)+' · '+item.count});});return out;}
  function rebuildCatalogFacets(){var trackers={},paths={},categories={},tags={};app.catalog.forEach(function(t){var tracker=U.normalizeTracker(t.tracker),path=String(t.save_path||'').trim(),category=String(t.category||'').trim();if(tracker)trackers[tracker]=(trackers[tracker]||0)+1;if(path)paths[path]=(paths[path]||0)+1;if(category)categories[category]=(categories[category]||0)+1;String(t.tags||'').split(',').map(function(x){return x.trim();}).filter(Boolean).forEach(function(tag){tags[tag]=(tags[tag]||0)+1;});});app.facets.tracker=Object.keys(trackers).sort().map(function(value){return{value:value,label:U.trackerLabel(value),count:trackers[value]};});app.facets.savePath=Object.keys(paths).sort().map(function(value){return{value:value,label:value,count:paths[value]};});app.facets.category=Object.keys(categories).sort().map(function(value){return{value:value,label:value,count:categories[value]};});app.facets.tag=Object.keys(tags).sort().map(function(value){return{value:value,label:value,count:tags[value]};});}
  function capabilitySupported(id,fallback){return W.CapabilityRegistry&&W.CapabilityRegistry.supports?W.CapabilityRegistry.supports(id):!!fallback;}
  function showCapability(kind){var id=kind==='private'?'privateFilter':kind;if(W.CapabilityRegistry&&W.CapabilityRegistry.open)W.CapabilityRegistry.open(id);}
  function hasInfoParameter(name){var R=W.CapabilityRegistry;return !!(R&&R.hasTorrentInfoParameter&&R.hasTorrentInfoParameter(name));}
  function localStatusFilter(){return !!(W.TorrentSemantics&&W.TorrentSemantics.localFilterRequired&&W.TorrentSemantics.localFilterRequired(app.filter));}
  function localTaxonomyFilter(){return !!((app.category&&!hasInfoParameter('category'))||(app.tag&&!hasInfoParameter('tag')));}
  function needsCatalogFiltering(){return !!(app.tracker||app.search||app.savePath||localStatusFilter()||localTaxonomyFilter());}
  function upstreamTorrentQuery(){return{filter:localStatusFilter()?'all':app.filter,category:app.category&&hasInfoParameter('category')?app.category:'',tag:app.tag&&hasInfoParameter('tag')?app.tag:'',sort:app.sort,reverse:String(app.reverse),limit:app.pageSize+1,offset:app.page*app.pageSize};}
  function mergeNativeFacet(kind,values){var current={},out=[];(app.facets[kind]||[]).forEach(function(item){current[String(item.value)]=item;});(values||[]).forEach(function(value){value=String(value||'').trim();if(value&&!current[value])current[value]={value:value,label:value,count:null};});Object.keys(current).sort().forEach(function(value){out.push(current[value]);});app.facets[kind]=out;}
  function fieldRegistry(){return W.TorrentFieldRegistry||null;}
  function effectiveColumnDefinitions(){var R=fieldRegistry();return R&&R.availableColumnDefinitions?R.availableColumnDefinitions():W.DataGrid.defaults;}
  function applyEffectiveColumns(){var R=fieldRegistry();if(!R||!R.effectiveDesktopColumns)return app.columns;app.columns=R.effectiveDesktopColumns(cfg);renderHead();return app.columns;}
  function saveEffectiveColumns(cols){var R=fieldRegistry();if(R&&R.saveEffectiveDesktopColumns)app.columns=R.saveEffectiveDesktopColumns(cfg,cols);else{app.columns=cols;W.DataGrid.save(cfg,cols);}return app.columns;}
  function refreshColumnCopy(){var defs=effectiveColumnDefinitions(),byKey={};defs.forEach(function(def){byKey[def.key]=def;});app.columns=(app.columns||[]).map(function(column){var def=byKey[column.key]||column;return Object.assign({},def,{width:column.width||def.width,visible:column.visible!==false});});if(!app.columns.length&&defs.length)app.columns=defs.slice(0,7).map(function(def){return Object.assign({},def);});renderHead();renderList();if(W.ColumnConfigurator&&W.ColumnConfigurator.refreshActive)W.ColumnConfigurator.refreshActive();}
  function setSort(sort,dir){var key=String(sort||'').trim();if(!key)return false;app.sort=key;app.reverse=String(dir||'asc').toLowerCase()==='desc';app.page=0;clearSelection();resetTorrentScroll();renderHead();emitLibraryState('sort');loadPage(false);return true;}
  function renderHead(){var head=U.$('torrent-table-head'),template=W.DataGrid.template(app.columns);head.style.gridTemplateColumns=template;W.DataGridHeader.render(head,app.columns,{surfaceId:'torrent-main',label:function(c){return c.label+(app.sort===c.sort?(app.reverse?' ↓':' ↑'):'');},onClick:function(c){if(app.sort===c.sort)setSort(c.sort,app.reverse?'asc':'desc');else setSort(c.sort,'asc');}});W.DataGrid.addResizeHandles(head,app.columns,function(cols,save){app.columns=cols;var t=W.DataGrid.template(cols);head.style.gridTemplateColumns=t;if(app.virtual)app.virtual.render();if(save)saveEffectiveColumns(cols);});W.DataGridHeader.refresh(head,app.columns);}
  function renderPageLabel(total){var host=U.$('page-label'),state=document.createElement('span');host.textContent='';state.className='pager-index-state';if(total==null){var mark=document.createElement('span');if(app.catalogError){mark.className='pager-index-error';mark.textContent='!';mark.setAttribute('aria-label',tr('library.totalUnavailable'));}else{mark.className='pager-index-spinner';mark.setAttribute('aria-hidden','true');}state.appendChild(mark);}var copy=document.createElement('span');copy.className='pager-index-copy';copy.textContent=total==null?tr('library.pageCurrent',{page:app.page+1,size:app.pageSize}):tr('library.page',{page:app.page+1,pages:Math.max(1,Math.ceil(total/app.pageSize)),size:app.pageSize});state.appendChild(copy);host.appendChild(state);}
  function renderList(){var list=U.$('torrent-list'),items=app.torrents;var handlers={open:openDetail,menu:function(hash){app.selection.selectOnly(hash);app.selection.openActions();}},renderRow=function(t){return U.isMobile()?C.mobileTorrentCard(t,app.selection.has(t.hash),handlers,cfg.mobileFields):C.torrentRow(t,app.selection.has(t.hash),handlers,app.columns,W.DataGrid.template(app.columns));},nextHeight=rowHeight(),nextOverscan=U.isMobile()?3:7;if(!app.virtual||app.virtual.el!==list){if(app.virtual&&app.virtual.destroy)app.virtual.destroy();app.virtual=new W.VirtualList(list,{rowHeight:nextHeight,overscan:nextOverscan,renderRow:renderRow});list.__weigTorrentVirtual=app.virtual;}else{app.virtual.renderRow=renderRow;app.virtual.overscan=nextOverscan;if(app.virtual.rowHeight!==nextHeight)app.virtual.setRowHeight(nextHeight);}app.virtual.setItems(items);var empty=items.length===0&&!app.busy;U.$('list-empty').classList.toggle('is-hidden',!empty);var panel=list.closest('.torrent-panel');if(panel)panel.classList.toggle('is-empty',empty);var total=totalMatching();renderPageLabel(total);U.$('prev-btn').disabled=app.page===0||app.busy;U.$('next-btn').disabled=app.busy||(total!=null?(app.page+1)*app.pageSize>=total:!app.hasNext);U.$('status-torrents').textContent='Torrent '+(total==null?'…':total);app.selection.apply();app.selection.sync();emitLibraryState('render-list');}
  async function pageFromCatalog(){var matches=matchingCatalog(),slice=matches.slice(app.page*app.pageSize,(app.page+1)*app.pageSize);app.hasNext=(app.page+1)*app.pageSize<matches.length;if(!slice.length)return [];var hashes=slice.map(function(t){return t.hash;}).join('|');var live=await app.client.getTorrents({hashes:hashes});var map={};(live||[]).forEach(function(t){map[t.hash]=t;});return slice.map(function(t){return Object.assign({},t,map[t.hash]||{});});}
  async function loadPage(silent){if(app.busy){if(!silent)app.pendingLoad=false;return;}app.busy=true;if(!silent)toggleLoading(true);try{var data;if(app.catalogReady&&needsCatalogFiltering())data=await pageFromCatalog();else{var raw=await app.client.getTorrents(upstreamTorrentQuery());raw=Array.isArray(raw)?raw:[];app.hasNext=raw.length>app.pageSize;data=raw.slice(0,app.pageSize);}if(app.pendingLoad!==null)return;app.torrents=Array.isArray(data)?data:[];app.torrents.forEach(function(t){var i=app.catalog.findIndex(function(x){return x.hash===t.hash;});if(i>=0)app.catalog[i]=Object.assign({},app.catalog[i],t);});setStatus('torrent','');}catch(e){setStatus('torrent',tr('library.refreshFailedStatus'));if(!silent)W.toast(tr('library.refreshFailedPrefix')+e.message,'error',{title:tr('library.refreshFailedTitle')});if(e.status===403)location.reload();}finally{var pending=app.pendingLoad;app.pendingLoad=null;app.busy=false;toggleLoading(false);renderList();if(pending!==null)loadPage(pending);}}
  async function loadTransfer(){try{var info=await app.client.getTransferInfo(),downloadSpeed=info&&info.dl_info_speed||0,uploadSpeed=info&&info.up_info_speed||0,status=info&&info.connection_status||'connected';if(W.TransferRuntime&&W.TransferRuntime.ingest)W.TransferRuntime.ingest(info);paintText('status-dl',U.formatSpeed(downloadSpeed));paintText('status-up',U.formatSpeed(uploadSpeed));setStatus('transfer','');emitStatusState(status);}catch(_e){setStatus('transfer',tr('transfer.statusUnavailable'));emitStatusState('error');}}
  async function buildCatalog(){if(app.catalogTask)return app.catalogTask;app.catalogTask=(async function(){app.catalogBusy=true;app.catalogError=false;app.catalogReady=false;U.$('catalog-state').textContent='';renderList();try{var all=[],offset=0,batch=200;while(true){var part=await app.client.getTorrents({sort:'added_on',reverse:'true',limit:batch,offset:offset});part=Array.isArray(part)?part:[];all=all.concat(part);if(part.length<batch)break;offset+=batch;await U.sleep(0);}app.catalog=all;app.catalogReady=true;rebuildCatalogFacets();emitLibraryState('catalog-ready');if(needsCatalogFiltering())await loadPage(false);else renderList();return all;}catch(e){app.catalogError=true;app.catalogReady=false;U.$('catalog-state').textContent='';renderList();emitLibraryState('catalog-error');return null;}finally{app.catalogBusy=false;app.catalogTask=null;}})();return app.catalogTask;}
  async function ensureCatalogForLocalView(){if(needsCatalogFiltering()&&!app.catalogReady){await buildCatalog();return true;}return false;}
  async function setSavePath(value){app.savePath=String(value||'');app.page=0;clearSelection();resetTorrentScroll();emitLibraryState('savepath-filter');if(await ensureCatalogForLocalView())return;loadPage(false);}
  async function loadTaxonomy(){if(app.catalogReady)rebuildCatalogFacets();if(capabilitySupported('categories',app.client.capabilities.categories)){try{var cats=await app.client.categories();mergeNativeFacet('category',cats?Object.keys(cats):[]);}catch(_e){}}if(capabilitySupported('tags',app.client.capabilities.tags)){try{var tags=await app.client.tags();mergeNativeFacet('tag',Array.isArray(tags)?tags:[]);}catch(_e){}}emitLibraryState('taxonomy');}
  function schedulePoll(){clearTimeout(app.pollTimer);var delay=document.hidden?10000:(Number(cfg.refresh)||2000);app.pollTimer=setTimeout(async function(){var r=W.Router.route();if(r.name==='home')await loadPage(true);await loadTransfer();schedulePoll();},delay);}
  function applyRuntimeConfig(key,value){if(!(key in cfg))return false;cfg[key]=value;if(key==='pageSize'){cfg.pageSize=Number(value)||50;app.pageSize=cfg.pageSize;app.page=0;resetTorrentScroll();if(app.pageSizeControl&&app.pageSizeControl.setValue)app.pageSizeControl.setValue(String(app.pageSize));emitLibraryState('page-size');loadPage(false);}else if(key==='refresh'){cfg.refresh=Number(value)||2000;schedulePoll();}else if(key==='density'){renderList();}else if(key==='ptTrackers'){app.page=0;if(app.catalogReady&&needsCatalogFiltering())loadPage(false);else renderList();}return true;}
  async function setFilter(filter){filter=W.TorrentSemantics&&W.TorrentSemantics.canonicalFilter?W.TorrentSemantics.canonicalFilter(filter):String(filter||'all');if(filter==='private')return false;if(W.TorrentSemantics&&W.TorrentSemantics.isSupportedFilter&&!W.TorrentSemantics.isSupportedFilter(filter))return false;app.filter=filter;app.page=0;clearSelection();resetTorrentScroll();U.$$('#filter-nav .nav-item').forEach(function(el){el.classList.toggle('is-active',el.dataset.filter===filter);});closeDrawer();emitLibraryState('filter');if(await ensureCatalogForLocalView())return true;loadPage(false);return true;}
  async function setTax(type,value){var capability=type==='tag'?'tagFacet':'categoryFacet';if(!capabilitySupported(capability,true)){showCapability(capability);return false;}app[type]=String(value||'');app.page=0;clearSelection();resetTorrentScroll();emitLibraryState('taxonomy-filter');if(await ensureCatalogForLocalView())return true;loadPage(false);return true;}
  async function setTracker(value){value=String(value||'');if(value===PRIVATE_TRACKER&&!privateTrackerSupported()){showCapability('private');return false;}app.tracker=value;app.page=0;clearSelection();resetTorrentScroll();emitLibraryState('tracker-filter');if(await ensureCatalogForLocalView())return true;loadPage(false);return true;}
  var LibraryController={state:function(){return{filter:app.filter,tracker:app.tracker,savePath:app.savePath,category:app.category,tag:app.tag,search:app.search,page:app.page,pageSize:app.pageSize,sort:app.sort,reverse:app.reverse};},total:totalMatching,facetOptions:facetOptions,matchesTorrent:function(t,state){return filterMatch(t,state||app);},setFilter:setFilter,setTracker:setTracker,setSavePath:setSavePath,setCategory:function(value){return setTax('category',value);},setTag:function(value){return setTax('tag',value);},setSort:setSort,applyRuntimeConfig:applyRuntimeConfig,showCapability:showCapability};
  W.LibraryController=LibraryController;
  function setView(name){if(name!=='torrent'&&app.detailVirtual){if(app.detailVirtual.destroy)app.detailVirtual.destroy();app.detailVirtual=null;}['list','detail','settings','search','rss','logs'].forEach(function(v){U.$(v+'-view').classList.toggle('is-active',(name==='home'&&v==='list')||(name==='torrent'&&v==='detail')||(name===v));});var active=name==='home'||name==='torrent'?'':name;U.$$('#app-nav [data-route],#mobile-bottom-nav [data-route]').forEach(function(btn){btn.classList.toggle('is-active',(btn.dataset.route||'')===active);});var shell=U.$('app');if(shell)shell.classList.toggle('is-tool-route',name!=='home');U.$('back-btn').classList.toggle('is-hidden',name==='home');closeDrawer();event('weig:route-state',{name:name,scope:name==='home'?'library':'tool'});}
  function detailUi(){var R=W.CapabilityRegistry;return R&&typeof R.torrentDetailUi==='function'?R.torrentDetailUi():null;}
  function detailTabKeys(){var ui=detailUi(),tabs=ui&&ui.tabs||{},raw=Array.isArray(ui&&ui.tabOrder)?ui.tabOrder:Object.keys(tabs);return raw.map(String).filter(function(key,index,list){return tabs[key]&&list.indexOf(key)===index;});}
  function defaultDetailTab(){var keys=detailTabKeys();return keys.length?keys[0]:'';}
  function detailTableSurface(tab){var ui=detailUi(),tables=ui&&ui.tables,key=String(tab||'');return tables&&Array.isArray(tables[key])&&tables[key].length?key:'';}
  async function route(){var r=W.Router.route();if(r.name==='torrent'&&r.id){if(W.CapabilityRegistry&&W.CapabilityRegistry.ensure)await W.CapabilityRegistry.ensure('detail');setView('torrent');var nextDetailHash=decodeURIComponent(r.id);if(app.detailHash!==nextDetailHash){app.detailHash=nextDetailHash;app.detailProperties=null;app.detailPropertiesHash='';}var tabs=detailTabKeys(),requested=String(r.tab||''),tab=requested&&tabs.indexOf(requested)>=0?requested:(tabs[0]||'');if(tab&&requested!==tab){W.Router.detail(app.detailHash,tab);return;}app.detailTab=tab;await loadDetailHeader();await loadDetailTab(app.detailTab);}else if(r.name==='settings'){setView('settings');if(W.SettingsRenderer&&W.SettingsRenderer.open)await W.SettingsRenderer.open();}else if(r.name==='search'){if(!capabilitySupported('search',app.client.capabilities.search)){showCapability('search');W.Router.home();return;}setView('search');}else if(r.name==='rss'){if(!capabilitySupported('rss',app.client.capabilities.rss)){showCapability('rss');W.Router.home();return;}setView('rss');await loadRSS();}else if(r.name==='logs'){if(!capabilitySupported('logs',app.client.capabilities.logs)){showCapability('logs');W.Router.home();return;}setView('logs');if(W.Logs&&W.Logs.activate)W.Logs.activate();}else{setView('home');if(!app.torrents.length)loadPage(false);}}
  function showUnsupported(id,msg){var el=U.$(id);el.innerHTML='';var p=document.createElement('p');p.className='text-description';p.textContent=msg;el.appendChild(p);}
  async function openDetail(hash){var tab=defaultDetailTab();W.Router.detail(hash,tab);}
  async function torrentFor(hash){var t=app.catalog.find(function(x){return x.hash===hash;})||app.torrents.find(function(x){return x.hash===hash;});if(!t){try{var a=await app.client.getTorrents({hashes:hash,limit:1});t=a&&a[0];}catch(_e){}}return t||{hash:hash};}
  function hasDetailField(surface,name){var R=W.CapabilityRegistry;return !!(R&&R.hasTorrentDetailField&&R.hasTorrentDetailField(surface,name));}
  function detailValue(surface,item,name,fallback){if(!hasDetailField(surface,name))return fallback;var value=item&&item[name];return value===undefined||value===null?fallback:value;}
  function detailControl(name){var ui=detailUi(),controls=ui&&ui.controls;return controls&&controls[String(name||'')]||null;}
  function detailOptionLabel(controlName,option){var ref=option&&option.translation||null,fallback=String(ref&&ref.source||option&&option.value||'');return W.QbUiEvidence&&typeof W.QbUiEvidence.text==='function'?W.QbUiEvidence.text('detail.control.'+String(controlName||'')+'.'+String(option&&option.value||''),ref,fallback):fallback;}
  function detailEndpointForAction(action){var R=W.CapabilityRegistry,desc=R&&typeof R.actionDescriptor==='function'?R.actionDescriptor(action):null;if(!desc||!desc.endpoint)return'';var controller=String(action||'').split(':')[0].replace(/controller\.h$/,'');return controller?controller+'/'+String(desc.endpoint):String(desc.endpoint);}
  function derivedFileMenu(){var out=[],renameAction='torrentscontroller.h:renameFileAction',renameEndpoint=detailEndpointForAction(renameAction);if(renameEndpoint&&hasDetailField('files','name')&&writeActionSupported(renameAction))out.push({id:'__weig_file_rename',label:tr('action.renameEllipsis'),sourceAction:renameAction,endpoint:renameEndpoint,availability:{minSelection:1,maxSelection:1},fileKinds:['file'],parameterBindings:{oldPath:'name'},parameterPrompts:{newPath:{mode:'basename-preserve-parent',from:'oldPath'}}});var renameFolderAction='torrentscontroller.h:renameFolderAction',renameFolderEndpoint=detailEndpointForAction(renameFolderAction);if(renameFolderEndpoint&&writeActionSupported(renameFolderAction))out.push({id:'__weig_folder_rename',label:tr('action.renameEllipsis'),sourceAction:renameFolderAction,endpoint:renameFolderEndpoint,availability:{minSelection:1,maxSelection:1},fileKinds:['folder'],parameterBindings:{oldPath:'name'},parameterPrompts:{newPath:{mode:'basename-preserve-parent',from:'oldPath'}}});var priorityAction='torrentscontroller.h:filePrioAction',priorityEndpoint=detailEndpointForAction(priorityAction),control=detailControl('filePriority'),options=Array.isArray(control&&control.options)?control.options:[];if(priorityEndpoint&&writeActionSupported(priorityAction))options.filter(function(option){return Number(option&&option.value)>=0;}).forEach(function(option){out.push({id:'__weig_file_priority_'+String(option.value),label:detailOptionLabel('filePriority',option),sourceAction:priorityAction,endpoint:priorityEndpoint,availability:{minSelection:1,maxSelection:1},fileKinds:['file'],parameterValues:{priority:String(option.value)},requiresNonSeed:true});});out.push({id:'copy-file-path',label:tr('detail.copyFilePath'),localAction:'copy-file-path',availability:{minSelection:1,maxSelection:1},fileKinds:['file']},{id:'copy-containing-folder',label:tr('detail.copyContainingFolderPath'),localAction:'copy-containing-folder',availability:{minSelection:1,maxSelection:1},fileKinds:['file']});return out;}
  function detailMenu(surface){var ui=detailUi(),menus=ui&&ui.contextMenus,items=menus&&menus[String(surface||'')],out=Array.isArray(items)?items.slice():[];if(surface==='files')out=out.concat(derivedFileMenu());return out;}
  function detailMenuLabel(surface,item){var explicit=String(item&&item.label||'');if(explicit)return explicit;var ref=item&&item.translation||null,fallback=String(ref&&ref.source||item&&item.id||'');return W.QbUiEvidence&&typeof W.QbUiEvidence.text==='function'?W.QbUiEvidence.text('detail.menu.'+String(surface||'')+'.'+String(item&&item.id||''),ref,fallback):fallback;}
  function detailMenuAvailable(item,selectionCount,rowValue,rowItem){var availability=item&&item.availability||{},count=Number(selectionCount)||0;if(availability.minSelection!=null&&count<Number(availability.minSelection))return false;if(availability.maxSelection!=null&&count>Number(availability.maxSelection))return false;var kinds=Array.isArray(item&&item.fileKinds)?item.fileKinds:[];if(kinds.length){var kind=String(rowItem&&rowItem.__weigFileKind||'file');if(kinds.indexOf(kind)<0)return false;}var value=String(rowValue||''),prefixes=Array.isArray(availability.excludedPrefixes)?availability.excludedPrefixes:[];if(value&&prefixes.some(function(prefix){return value.startsWith(String(prefix));}))return false;if(item&&item.requiresNonSeed&&rowItem&&rowItem.is_seed===true)return false;return true;}
  function detailColumnValue(surface,item,columnKey,fallback){var columns=W.QbUiEvidence&&W.QbUiEvidence.detailColumns?W.QbUiEvidence.detailColumns(surface):[],column=columns.find(function(candidate){return candidate&&candidate.key===columnKey;}),keys=Array.isArray(column&&column.dataProperties)?column.dataProperties.map(String):[];if(keys.indexOf(columnKey)>=0&&item&&Object.prototype.hasOwnProperty.call(item,columnKey))return item[columnKey];var scalar=keys.filter(function(key){return key!=='endpoints'&&item&&Object.prototype.hasOwnProperty.call(item,key);});return scalar.length===1?item[scalar[0]]:fallback;}
  function writeActionSupported(action){var R=W.CapabilityRegistry;return !!(action&&R&&R.supportsWriteAction&&R.supportsWriteAction(action));}
  function detailActionDescriptor(item){var R=W.CapabilityRegistry,action=item&&item.sourceAction,endpoint=String(item&&item.endpoint||'');if(!action||!endpoint||!writeActionSupported(action)||!R||typeof R.actionDescriptor!=='function')return null;var desc=R.actionDescriptor(action);if(!desc)return null;var expected=String(desc.endpoint||'');if(expected&&endpoint.split('/').pop()!==expected)return null;return desc;}
  function detailLocalAction(surface,item){if(!item||item.sourceAction||item.endpoint)return'';if(item.localAction)return String(item.localAction);var id=String(item.id||'').toLowerCase();return(surface==='trackers'||surface==='peers')&&id.indexOf('copy')===0?'copy-row-address':'';}
  function detailRowAddress(surface,item,index){if(surface==='trackers')return String(detailColumnValue(surface,item,'url','')||'');if(surface==='peers'){var ip=detailColumnValue(surface,item,'ip',item&&item.__key||''),port=detailColumnValue(surface,item,'port','');return ip&&port?String(ip)+':'+String(port):String(ip||'');}if(surface==='files'){var fileId=hasDetailField('files','index')?detailValue('files',item,'index',index):index;return String(fileId==null?'':fileId);}return'';}
  function detailRowParameter(surface,item,index,name,allowRow){name=String(name||'');if(name==='hash'||name==='hashes')return{found:true,value:app.detailHash};if(!allowRow||!item)return{found:false};if(Object.prototype.hasOwnProperty.call(item,name))return{found:true,value:item[name]};if(surface==='trackers'){var url=detailColumnValue(surface,item,'url',''),tier=detailColumnValue(surface,item,'tier',null);if(name==='url'||name==='origUrl'||name==='urls')return url?{found:true,value:url}:{found:false};if(name==='tier'&&tier!==null&&tier!==undefined&&tier!=='')return{found:true,value:tier};}if(surface==='peers'&&name==='peers'){var address=detailRowAddress(surface,item,index);return address?{found:true,value:address}:{found:false};}if(surface==='files'&&(name==='id'||name==='ids')){var id=detailRowAddress(surface,item,index);return id!==''?{found:true,value:id}:{found:false};}return{found:false};}
  function detailBoundParameter(surface,item,index,name,allowRow,menuItem){var values=menuItem&&menuItem.parameterValues||{},bindings=menuItem&&menuItem.parameterBindings||{};if(Object.prototype.hasOwnProperty.call(values,name))return{found:true,value:values[name]};if(allowRow&&item&&Object.prototype.hasOwnProperty.call(bindings,name)){var source=String(bindings[name]||'');if(source==='rowAddress'){var address=detailRowAddress(surface,item,index);return address?{found:true,value:address}:{found:false};}if(Object.prototype.hasOwnProperty.call(item,source))return{found:true,value:item[source]};var projected=detailColumnValue(surface,item,source,undefined);if(projected!==undefined&&projected!==null)return{found:true,value:projected};}return detailRowParameter(surface,item,index,name,allowRow);}
  function detailBasename(value){value=String(value==null?'':value);var at=Math.max(value.lastIndexOf('/'),value.lastIndexOf('\\'));return at>=0?value.slice(at+1):value;}
  function detailPromptDefault(surface,item,index,name,menuItem,form){var rules=menuItem&&menuItem.parameterPrompts||{},rule=rules[name];if(rule&&rule.mode==='basename-preserve-parent'&&form&&Object.prototype.hasOwnProperty.call(form,rule.from))return detailBasename(form[rule.from]);var direct=detailBoundParameter(surface,item,index,name,true,menuItem);if(direct.found)return direct.value;var match=String(name||'').match(/^new(.+)$/);if(match){var base=match[1].replace(/^./,function(ch){return ch.toLowerCase();}),prior=detailBoundParameter(surface,item,index,base,true,menuItem);if(prior.found)return prior.value;}return'';}
  function detailNormalizePrompt(name,value){value=String(value==null?'':value);if(name==='peers'&&/[\r\n]/.test(value))return value.trim().split(/[\r\n]+/).filter(Boolean).join('|');return value;}
  function detailApplyPromptRule(menuItem,name,value,form){var rules=menuItem&&menuItem.parameterPrompts||{},rule=rules[name];if(!rule||rule.mode!=='basename-preserve-parent')return value;var old=String(form&&form[rule.from]||''),at=Math.max(old.lastIndexOf('/'),old.lastIndexOf('\\'));return(at>=0?old.slice(0,at+1):'')+String(value||'').trim();}
  function detailPromptValue(title,name,value,options){return new Promise(function(resolve,reject){var dialog=U.$('prompt-dialog'),input=U.$('prompt-value'),allowed=Array.isArray(options)&&options.length?options.map(String):[];U.$('prompt-title').textContent=title;U.$('prompt-label').textContent=String(name||'Value')+(allowed.length?' ('+allowed.join(' / ')+')':'');input.value=value==null?'':String(value);W.DialogRuntime.open(dialog,{draggable:true,focus:input});setTimeout(function(){input.focus();input.select();},20);var settled=false;function cleanup(){dialog.removeEventListener('close',onClose);U.$('prompt-close').onclick=U.$('prompt-cancel').onclick=function(){W.DialogRuntime.close(dialog);};}function finish(ok,result){if(settled)return;settled=true;cleanup();W.DialogRuntime.close(dialog);if(ok)resolve(result);else reject(new Error(tr('common.actionCancelled')));}function onClose(){if(!settled){settled=true;cleanup();reject(new Error(tr('common.actionCancelled')));}}dialog.addEventListener('close',onClose);U.$('prompt-confirm').onclick=function(){var result=String(input.value||'');if(allowed.length&&allowed.indexOf(result)<0){W.toast(tr('detail.sourceValuePromptPrefix')+allowed.join(', '),'warning',{title:tr('common.invalidValue')});return;}finish(true,result);};U.$('prompt-close').onclick=U.$('prompt-cancel').onclick=function(){finish(false);};});}
  async function detailActionForm(surface,item,index,menuItem,desc){var form={},params=Array.isArray(desc.parameters)?desc.parameters.map(String):[],required=Array.isArray(desc.required)?desc.required.map(String):[],optional=Array.isArray(desc.optional)?desc.optional.map(String):[],options=desc.parameterOptions||{},availability=menuItem&&menuItem.availability||{},selectionBound=!!(item&&Number(availability.minSelection)>=1),rowScoped=!!(selectionBound&&(availability.maxSelection!=null||(Array.isArray(availability.excludedPrefixes)&&availability.excludedPrefixes.length))),promptNames=[];params.forEach(function(name){var isOptional=optional.indexOf(name)>=0,allowRow=isOptional?rowScoped:selectionBound,found=detailBoundParameter(surface,item,index,name,allowRow,menuItem);if(found.found)form[name]=found.value;else if(required.indexOf(name)>=0||Object.prototype.hasOwnProperty.call(options,name)||/^new[A-Z_]/.test(name))promptNames.push(name);});for(var i=0;i<promptNames.length;i++){var name=promptNames[i],raw=await detailPromptValue(detailMenuLabel(surface,menuItem),name,detailPromptDefault(surface,item,index,name,menuItem,form),options[name]);raw=detailNormalizePrompt(name,raw);if(required.indexOf(name)>=0&&!raw)throw new Error(tr('detail.requiredParameterEmptyPrefix')+name);form[name]=detailApplyPromptRule(menuItem,name,raw,form);}for(var j=0;j<required.length;j++)if(!Object.prototype.hasOwnProperty.call(form,required[j]))throw new Error(tr('detail.unsafeParameterPrefix')+required[j]);return form;}
  async function executeDetailAction(surface,item,index,menuItem){var desc=detailActionDescriptor(menuItem);if(!desc)throw new Error(tr('detail.actionDescriptorUnavailable'));var form=await detailActionForm(surface,item,index,menuItem,desc);await app.client.request(String(menuItem.endpoint),{method:'POST',form:form,type:'void'});}
  async function detailProperties(){if(app.detailProperties&&app.detailPropertiesHash===app.detailHash)return app.detailProperties;var p=await app.client.properties(app.detailHash);if(!p||typeof p!=='object'||Array.isArray(p))throw new Error(tr('detail.propertiesUnexpected'));app.detailProperties=p;app.detailPropertiesHash=app.detailHash;return p;}
  async function executeDetailLocalAction(kind,rowValue,rowItem){var value=rowValue;if(kind==='copy-file-path'||kind==='copy-containing-folder'){var properties=await detailProperties(),path=W.QbPath&&W.QbPath.resolveFile?W.QbPath.resolveFile(properties,rowItem):'';value=kind==='copy-containing-folder'&&W.QbPath&&W.QbPath.dirname?W.QbPath.dirname(path):path;}if((kind!=='copy-row-address'&&kind!=='copy-file-path'&&kind!=='copy-containing-folder')||!value)throw new Error(tr('detail.localExecutorUnavailable'));if(!global.navigator||!navigator.clipboard||typeof navigator.clipboard.writeText!=='function')throw new Error(tr('common.clipboardUnavailable'));await navigator.clipboard.writeText(String(value));W.toast(tr('common.copiedMessage'),'success',{title:tr('common.copiedTitle')});}
  function detailActionItems(surface,item,index,selectionCount){var rowValue=detailRowAddress(surface,item,index);return detailMenu(surface).map(function(menuItem){if(!detailMenuAvailable(menuItem,selectionCount,rowValue,item))return null;var localAction=detailLocalAction(surface,menuItem),desc=detailActionDescriptor(menuItem);if(!localAction&&!desc)return null;return{key:menuItem.id,label:detailMenuLabel(surface,menuItem),onSelect:async function(){try{if(localAction){await executeDetailLocalAction(localAction,rowValue,item);return;}await executeDetailAction(surface,item,index,menuItem);await renderDetailTable(U.$('detail-content'),surface);}catch(e){if(e&&/Action cancelled|操作已取消/.test(String(e.message||'')))return;W.toast(e.message,'error',{title:tr('detail.actionFailedTitle')});}}};}).filter(Boolean);}
  function renderDetailUnsupported(root){root.textContent='';var p=document.createElement('p');p.className='text-description';p.textContent=tr('detail.surfaceUnavailable');root.appendChild(p);}
  function requireDetailArray(items,label){if(!Array.isArray(items))throw new Error(label+tr('detail.unexpectedResponseSuffix'));return items;}
  async function loadDetailHeader(){var t=await torrentFor(app.detailHash),fallback=tr('detail.eyebrow');if(!t.name){U.$('detail-title').textContent=fallback;return;}U.$('detail-title').textContent=t.name||fallback;var s=C.state(t.state);U.$('detail-state').textContent=s[0];U.$('detail-state').dataset.tone=s[1];var p=U.clamp(U.percent(t.progress),0,100);U.$('detail-progress-bar').style.width=p+'%';U.$('detail-progress-text').textContent=p+'%';}
  function activateTab(tab){U.$$('.tab').forEach(function(el){var active=el.dataset.tab===tab;el.classList.toggle('is-active',active);el.setAttribute('aria-selected',active?'true':'false');});app.detailTab=tab;}
  async function loadDetailTab(tab){var root=U.$('detail-content'),tabs=detailTabKeys(),surface=detailTableSurface(tab);if(!tab||tabs.indexOf(tab)<0){activateTab('');renderDetailUnsupported(root);return;}activateTab(tab);root.textContent='';var loading=document.createElement('div');loading.className='loading-state';loading.innerHTML='<div class="spinner"></div>';var loadingCopy=document.createElement('span');loadingCopy.textContent=tr('detail.loading');loading.appendChild(loadingCopy);root.appendChild(loading);try{if(tab==='overview')await renderOverview(root);else if(surface)await renderDetailTable(root,surface);else renderDetailUnsupported(root);}catch(e){root.textContent='';var p=document.createElement('p');p.className='text-description';p.textContent=tr('detail.loadFailed',{error:e.message});root.appendChild(p);}}
  async function renderOverview(root){var p=await detailProperties();if(!W.QbUiEvidence||typeof W.QbUiEvidence.renderGeneral!=='function'||!W.QbUiEvidence.renderGeneral(root,p,app.detailHash))throw new Error(tr('detail.generalUnavailable'));}
  function makeVirtual(root,items,rowH,render,extra){if(app.detailVirtual&&app.detailVirtual.destroy)app.detailVirtual.destroy();app.detailVirtual=null;root.textContent='';var note=document.createElement('p');note.className='section-note';note.textContent=tr('detail.virtualSummary',{count:items.length});var box=document.createElement('div');root.append(note,box);var options=Object.assign({rowHeight:rowH,overscan:6,renderRow:render},extra||{});app.detailVirtual=new W.VirtualList(box,options);app.detailVirtual.setItems(items);return box;}
  function detailFilePriorityCell(surface){if(surface!=='files')return null;var control=detailControl('filePriority'),sourceOptions=Array.isArray(control&&control.options)?control.options:[],priorityOptions=sourceOptions.map(function(option){return{value:String(option.value),label:detailOptionLabel('filePriority',option)};}),canWrite=writeActionSupported('torrentscontroller.h:filePrioAction');return function(ctx){if(ctx.column.key!=='priority'||!canWrite||!priorityOptions.length||!hasDetailField('files','priority'))return false;var current=String(detailValue('files',ctx.item,'priority',''));if(!priorityOptions.some(function(option){return option.value===current;}))return false;var fileName=detailValue('files',ctx.item,'name','File'),ctl=C.selectControl({value:current,options:priorityOptions,ariaLabel:fileName+' priority',onChange:function(value){var fileId=hasDetailField('files','index')?detailValue('files',ctx.item,'index',ctx.index):ctx.index;app.client.setFilePriority(app.detailHash,fileId,value).then(function(){W.toast(tr('file.priorityUpdatedMessage'),'success',{title:tr('file.priorityUpdatedTitle')});}).catch(function(e){W.toast(e.message,'error',{title:tr('file.priorityFailedTitle')});});}});ctx.cell.appendChild(ctl);return true;};}
  async function renderDetailTable(root,surface){surface=detailTableSurface(surface);if(!surface||typeof app.client[surface]!=='function'){renderDetailUnsupported(root);return;}if(surface==='files')await detailProperties();var items=requireDetailArray(await app.client[surface](app.detailHash),surface+' API'),cellRenderer=detailFilePriorityCell(surface);makeVirtual(root,items,54,function(item,index){var row=document.createElement('div');row.textContent=detailRowAddress(surface,item,index)||String(index+1);return row;},{detailCellRenderer:cellRenderer,detailContextItems:function(item,_surface,index,selectionCount){var count=selectionCount==null?(item?1:0):selectionCount;return detailActionItems(surface,item,index,count);}});}
  function promptAction(title,label,value,cb){U.$('prompt-title').textContent=title;U.$('prompt-label').textContent=label;U.$('prompt-value').value=value||'';W.DialogRuntime.open(U.$('prompt-dialog'),{draggable:true,focus:U.$('prompt-value')});setTimeout(function(){U.$('prompt-value').focus();},20);U.$('prompt-confirm').onclick=async function(){var v=U.$('prompt-value').value,notice=W.toast('正在提交操作。','info',{title:'正在处理',duration:0});try{await cb(v);W.DialogRuntime.close(U.$('prompt-dialog'));notice.update('操作完成。','success',{title:'操作完成'});}catch(e){notice.update(e.message,'error',{title:'操作失败'});}};}
  function openAdd(){U.$('torrent-urls').value='';U.$('torrent-files').value='';W.DialogRuntime.open(U.$('add-dialog'),{draggable:true,focus:U.$('torrent-urls')});setTimeout(function(){U.$('torrent-urls').focus();},50);}
  async function submitAdd(){var urls=U.$('torrent-urls').value,files=U.$('torrent-files').files;if(!urls.trim()&&!files.length){W.toast(tr('torrent.sourceRequiredMessage'),'warning',{title:tr('torrent.sourceRequiredTitle')});return;}var btn=U.$('add-submit'),notice=W.toast(tr('torrent.submitting'),'info',{title:tr('torrent.addingTitle'),duration:0});btn.disabled=true;btn.textContent='添加中…';try{var result=await app.client.add(urls,files,U.$('save-path').value);if(result&&String(result).trim()!=='Ok.')throw new Error(String(result));W.DialogRuntime.close(U.$('add-dialog'));notice.update(tr('torrent.addedMessage'),'success',{title:tr('torrent.added')});app.page=0;await buildCatalog();await loadPage(false);}catch(e){notice.update(tr('torrent.addFailedPrefix')+e.message,'error',{title:tr('torrent.addFailedTitle')});}finally{btn.disabled=false;btn.textContent='添加';}}
  function closeDrawer(){if(W.HeaderUtilities&&W.HeaderUtilities.setDrawer){W.HeaderUtilities.setDrawer(false);return;}U.$('sidebar').classList.remove('is-open');U.$('drawer-scrim').classList.remove('is-open');}
  function installPageSizeControl(){if(app.pageSizeControl)return app.pageSizeControl;var native=U.$('page-size'),host=U.$('page-size-control');if(!host&&native){host=document.createElement('span');host.id='page-size-control';native.replaceWith(host);}if(!host)return null;app.pageSizeControl=C.selectControl({id:'page-size',value:String(app.pageSize),options:[20,50,100,200].map(function(n){return{value:String(n),label:String(n)};}),ariaLabel:'Torrents per page',onChange:function(value){applyRuntimeConfig('pageSize',value);W.Config.save(cfg);}});host.appendChild(app.pageSizeControl);return app.pageSizeControl;}
  function mainColumnConfiguratorProvider(){return{title:function(){return W.I18n&&W.I18n.t?W.I18n.t('columns.title'):'Columns';},columns:function(){var defs=effectiveColumnDefinitions(),active={};app.columns.forEach(function(column,index){active[column.key]={column:column,index:index};});var visible=app.columns.map(function(column){var def=defs.find(function(item){return item.key===column.key;})||column;return Object.assign({},def,column,{visible:true});}),hidden=defs.filter(function(def){return !active[def.key];}).map(function(def){return Object.assign({},def,{visible:false});});return visible.concat(hidden);},commit:function(next){var defs=effectiveColumnDefinitions(),byKey={};defs.forEach(function(def){byKey[def.key]=def;});var chosen=(next||[]).filter(function(column){return column.visible!==false&&byKey[column.key];}).map(function(column){return Object.assign({},byKey[column.key],{width:column.width||byKey[column.key].width});});if(!chosen.length&&defs.length)chosen=[Object.assign({},defs[0])];saveEffectiveColumns(chosen);renderHead();renderList();},reset:function(){var R=fieldRegistry();if(R&&R.resetDesktopColumns)app.columns=R.resetDesktopColumns(cfg);else{app.columns=W.DataGrid.defaults.slice(0,7).map(function(c){return Object.assign({},c);});W.DataGrid.save(cfg,app.columns);}renderHead();renderList();}};}
  function installMainColumnConfigurator(){if(W.ColumnConfigurator)W.ColumnConfigurator.register('torrent-main',mainColumnConfiguratorProvider());}
  function openColumns(){if(W.ColumnConfigurator)W.ColumnConfigurator.open('torrent-main');}
  async function loadRSS(){if(!capabilitySupported('rss',app.client.capabilities.rss)){showCapability('rss');return false;}if(!W.RSSWorkspace||typeof W.RSSWorkspace.load!=='function')throw new Error(tr('rss.workspaceUnavailable'));return W.RSSWorkspace.load();}
  async function addRSS(){var url=U.$('rss-url').value.trim();if(!url)return;if(!W.RSSWorkspace||typeof W.RSSWorkspace.addFeed!=='function')throw new Error(tr('rss.workspaceUnavailable'));var notice=W.toast(tr('rss.addingMessage'),'info',{title:tr('rss.addingTitle'),duration:0});try{await W.RSSWorkspace.addFeed(url,'');U.$('rss-url').value='';notice.update(tr('rss.addedMessage'),'success',{title:tr('rss.addedTitle')});}catch(e){notice.update(e.message,'error',{title:tr('rss.addFailedTitle')});}}
  async function startSearch(){if(!capabilitySupported('search',app.client.capabilities.search)){showCapability('search');return;}var q=U.$('engine-query').value.trim();if(!q)return;try{var res=await app.client.searchStart(q,'enabled','all');app.searchJob=res&&res.id!=null?res.id:res;pollSearch();}catch(e){W.toast('搜索启动失败：'+e.message,'error',{title:'搜索启动失败'});}}
  async function pollSearch(){clearTimeout(app.searchPoll);if(app.searchJob==null)return;try{var data=await app.client.searchResults(app.searchJob,100,0),results=data&&data.results||[];var root=U.$('search-results');root.textContent='';results.forEach(function(x){var row=document.createElement('div');row.className='tool-row';var a=document.createElement('span');a.textContent=x.fileName||x.fileUrl||'—';var b=document.createElement('span');b.textContent=U.formatBytes(x.fileSize);var c=document.createElement('span');c.textContent='Seeds '+(x.nbSeeders==null?'—':x.nbSeeders);row.append(a,b,c);root.appendChild(row);});var st=await app.client.searchStatus(app.searchJob),status=Array.isArray(st)&&st[0]&&st[0].status;if(status==='Running')app.searchPoll=setTimeout(pollSearch,1200);}catch(e){W.toast('搜索读取失败：'+e.message,'error',{title:'搜索读取失败'});}}
  async function stopSearch(){if(app.searchJob==null)return;try{await app.client.searchStop(app.searchJob);app.searchJob=null;clearTimeout(app.searchPoll);}catch(_e){}}
  function bind(){installPageSizeControl();installMainColumnConfigurator();renderHead();U.$$('#app-nav [data-route],#mobile-bottom-nav [data-route],.sidebar [data-route]').forEach(function(b){b.addEventListener('click',function(){var path=b.dataset.route||'';if(path)W.Router.go(path);else W.Router.home();});});U.$('prev-btn').onclick=function(){if(app.page>0){app.page--;resetTorrentScroll();loadPage(false);}};U.$('next-btn').onclick=function(){app.page++;resetTorrentScroll();loadPage(false);};U.$('resume-btn').onclick=function(){app.selection.dispatch('resume').catch(function(e){W.toast(e.message,'error',{title:'命令发送失败'});});};U.$('pause-btn').onclick=function(){app.selection.dispatch('pause').catch(function(e){W.toast(e.message,'error',{title:'命令发送失败'});});};U.$('more-actions-btn').onclick=app.selection.openActions;U.$('delete-btn').onclick=app.selection.openDelete;U.$('add-btn').onclick=openAdd;U.$('empty-add-btn').onclick=openAdd;U.$('add-submit').onclick=submitAdd;U.$('back-btn').onclick=function(){W.Router.back();};U.$('search-input').addEventListener('input',U.debounce(async function(e){var next=e.target.value.trim();if(next!==app.search){app.search=next;app.page=0;clearSelection();resetTorrentScroll();emitLibraryState('search');}if(await ensureCatalogForLocalView())return;if(app.catalogReady)loadPage(false);else renderList();},180));U.$('actions-close').onclick=function(){W.DialogRuntime.close(U.$('actions-dialog'));};U.$('prompt-close').onclick=U.$('prompt-cancel').onclick=function(){W.DialogRuntime.close(U.$('prompt-dialog'));};U.$('columns-btn').onclick=openColumns;U.$('rss-add-btn').onclick=addRSS;U.$('rss-refresh-btn').onclick=loadRSS;U.$('engine-search-btn').onclick=startSearch;U.$('engine-stop-btn').onclick=stopSearch;U.$('fatal-back').onclick=function(){W.Router.back();};U.$('fatal-home').onclick=function(){W.Router.home();U.$('fatal').classList.add('is-hidden');};global.addEventListener('hashchange',route);document.addEventListener('visibilitychange',schedulePoll);global.addEventListener('resize',U.debounce(function(){renderList();},120));global.addEventListener('weig:qbcopychange',refreshColumnCopy);global.addEventListener('weig:languagechange',refreshColumnCopy);document.addEventListener('keydown',function(e){if(e.key==='Escape'){var open=document.querySelector('dialog[open]');if(open)return;if(W.Router.route().name!=='home')W.Router.back();else{app.selection.clear();renderList();}}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();if(U.isMobile()&&W.HeaderUtilities&&W.HeaderUtilities.setSearchOpen)W.HeaderUtilities.setSearchOpen(true);else U.$('search-input').focus();}if(e.key==='Delete'&&app.selection.count())app.selection.openDelete();});}
  function applyCapabilityUI(){if(W.CapabilityRegistry&&W.CapabilityRegistry.sync)W.CapabilityRegistry.sync();if(W.TorrentFilterView&&W.TorrentFilterView.render)W.TorrentFilterView.render();emitLibraryState('capabilities');}
  async function init(){try{bind();if(W.SessionController&&W.SessionController.ready&&!await W.SessionController.ready())return;app.selection.onCommandComplete=async function(kind){if(['delete','rename','location','category','tags'].indexOf(kind)>=0)await buildCatalog();else await loadPage(false);};await app.client.detect();if(W.SpatialRuntime&&W.SpatialRuntime.capabilitiesReady)await W.SpatialRuntime.capabilitiesReady();if(W.CapabilityRegistry&&W.CapabilityRegistry.bind)await W.CapabilityRegistry.bind(app.client);app.preferences=await app.client.getPreferences();if(W.SettingsState)W.SettingsState.prefs=app.preferences;if(app.preferences&&app.preferences.locale!=null&&W.I18n&&W.I18n.applyLocale)W.I18n.applyLocale(app.preferences.locale);if(W.I18n&&W.I18n.ready)await W.I18n.ready();applyEffectiveColumns();U.$('qb-version').textContent=app.client.qbVersion;U.$('api-version').textContent=app.client.webApiVersion;U.$('compat-mode').textContent=app.client.capabilities.certified?'已适配':'兼容模式';applyCapabilityUI();await Promise.all([loadPage(false),loadTransfer(),loadTaxonomy()]);await route();schedulePoll();setTimeout(buildCatalog,500);}catch(e){console.error(e);W.fatal(e);}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
