(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{};
  var ICON='https://raw.githubusercontent.com/weigefenxiang/WeiG-OpenWrt-AutoBuild/main/site/wrt/Wei.G.ico';
  var random=Math.random,timer=null,marks=new Set(),effects=['orbit','spark','tilt','shine','breathe','orbit-spark'];
  function reduced(){return !!(global.matchMedia&&global.matchMedia('(prefers-reduced-motion: reduce)').matches);}
  function layers(mark){if(!mark.querySelector('.ambient-mark__orbit')){var o=document.createElement('span');o.className='ambient-mark__orbit';o.setAttribute('aria-hidden','true');mark.prepend(o);}if(!mark.querySelector('.ambient-mark__shine')){var sh=document.createElement('span');sh.className='ambient-mark__shine';sh.setAttribute('aria-hidden','true');mark.appendChild(sh);}if(!mark.querySelector('.ambient-mark__sparks')){var ss=document.createElement('span');ss.className='ambient-mark__sparks';ss.setAttribute('aria-hidden','true');['#38d6ff','#7297ff','#816fff','#39d98a','#ffbd5a','#edf2ff'].forEach(function(c,i){var s=document.createElement('i');s.className='ambient-mark__spark';s.style.setProperty('--spark-color',c);s.style.setProperty('--spark-delay',(i*36)+'ms');ss.appendChild(s);});mark.appendChild(ss);}}
  function decorate(mark){if(!mark)return mark;mark.classList.add('ambient-mark');mark.dataset.ambientMarkReady='1';layers(mark);marks.add(mark);return mark;}
  function reset(mark){['is-ambient-orbit','is-ambient-spark','is-ambient-tilt','is-ambient-shine','is-ambient-breathe'].forEach(function(c){mark.classList.remove(c);});}
  function trigger(target,effect){var mark=typeof target==='string'?document.querySelector(target):target;mark=decorate(mark);if(!mark||reduced()||document.hidden)return false;reset(mark);void mark.offsetWidth;effect=effect||effects[Math.floor(random()*effects.length)]||'shine';if(effect==='orbit-spark')mark.classList.add('is-ambient-orbit','is-ambient-spark');else mark.classList.add('is-ambient-'+effect);setTimeout(function(){reset(mark);},2100);return true;}
  function schedule(){clearTimeout(timer);if(document.hidden||reduced()||!marks.size)return;timer=setTimeout(function(){var a=Array.from(marks);if(a.length&&random()>.18)trigger(a[Math.floor(random()*a.length)]);schedule();},8000+Math.round(random()*20000));}
  W.AmbientMark={install:function(target){var nodes=typeof target==='string'?document.querySelectorAll(target):[target];Array.from(nodes||[]).forEach(decorate);schedule();return this;},trigger:trigger,setRandom:function(fn){random=typeof fn==='function'?fn:Math.random;return this;},start:schedule,stop:function(){clearTimeout(timer);timer=null;}};
  function goHome(){if(W.Router&&W.Router.home)W.Router.home();else location.hash='#/';}
  function ensureFavicon(){var favicon=document.querySelector('link[rel~="icon"]');if(!favicon){favicon=document.createElement('link');favicon.rel='icon';document.head.appendChild(favicon);}favicon.href=ICON;return favicon;}
  function ensureImage(mark){if(!mark)return;var img=mark.querySelector('img');if(!img){Array.from(mark.childNodes).forEach(function(n){if(n.nodeType===3)n.remove();});img=document.createElement('img');img.alt='Wei.G';img.decoding='async';img.src=ICON;mark.appendChild(img);}decorate(mark);}
  function homeButton(cls,label,child){var b=document.createElement('button');b.type='button';b.className=cls;b.setAttribute('aria-label',label);b.appendChild(child);b.addEventListener('click',function(){if(child.classList&&child.classList.contains('brand__mark'))trigger(child,random()>.5?'orbit':'shine');goHome();});return b;}
  function normalizeHeader(){if(document.querySelector('.brand-cluster'))return;var old=document.getElementById('brand-btn');if(!old)return;var mark=old.querySelector('.brand__mark')||document.createElement('span');mark.classList.add('brand__mark');ensureImage(mark);var textNode=old.querySelector('.brand__text')||document.createElement('span');textNode.classList.add('brand__text');textNode.textContent='WeiG qB';var cluster=document.createElement('span');cluster.className='brand-cluster';cluster.append(homeButton('brand-mark-home','WeiG qB Home',mark),homeButton('brand-name-home','WeiG qB Home',textNode));old.replaceWith(cluster);W.AmbientMark.install(mark);}
  function cloneMark(size){var src=document.querySelector('.brand__mark'),mark=src?src.cloneNode(true):document.createElement('span');mark.className='brand__mark brand-mark brand-mark--'+(size||'identity');mark.querySelectorAll('.ambient-mark__orbit,.ambient-mark__shine,.ambient-mark__sparks').forEach(function(x){x.remove();});ensureImage(mark);return mark;}
  function createIdentity(){var hero=document.createElement('div');hero.className='about-identity brand-identity';var mark=cloneMark('identity'),mb=homeButton('brand-identity__mark-home','WeiG qB Home',mark);var body=document.createElement('div'),name=document.createElement('button');name.type='button';name.className='brand-identity__name-home';name.textContent='WeiG qB WebUI';name.addEventListener('click',goHome);var p=document.createElement('p');p.textContent='Alternate WebUI for qBittorrent';body.append(name,p);hero.append(mb,body);W.AmbientMark.install(mark);return hero;}
  W.Brand={goHome:goHome,normalizeHeader:normalizeHeader,cloneMark:cloneMark,createIdentity:createIdentity,iconUrl:ICON,ensureFavicon:ensureFavicon};
  function init(){ensureFavicon();setTimeout(normalizeHeader,0);document.addEventListener('visibilitychange',function(){if(document.hidden)W.AmbientMark.stop();else W.AmbientMark.start();});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
