(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{};
  if(W.CapabilityRegistry)return;

  var data=null,client=null,loadTask=null,dialog=null;
  function zh(){return !!(W.I18n&&W.I18n.getLocale&&W.I18n.getLocale()==='zh-CN');}
  function local(value,fallback){if(value&&typeof value==='object')return zh()?(value.zh||value.en||fallback):(value.en||value.zh||fallback);return value||fallback||'';}
  function parts(value){return String(value||'0').replace(/^v/i,'').split(/[+-]/)[0].split('.').map(function(x){var n=parseInt(x,10);return Number.isFinite(n)?n:0;});}
  function compare(a,b){var x=parts(a),y=parts(b),n=Math.max(x.length,y.length);for(var i=0;i<n;i++){var av=x[i]||0,bv=y[i]||0;if(av>bv)return 1;if(av<bv)return-1;}return 0;}
  function matchRange(actual,range){range=range||{};if(range.eq!=null&&compare(actual,range.eq)!==0)return false;if(range.gt!=null&&compare(actual,range.gt)<=0)return false;if(range.gte!=null&&compare(actual,range.gte)<0)return false;if(range.lt!=null&&compare(actual,range.lt)>=0)return false;if(range.lte!=null&&compare(actual,range.lte)>0)return false;return true;}
  function matchRule(rule,env){rule=rule||{};env=env||{};if(Array.isArray(rule.all)&&!rule.all.every(function(x){return matchRule(x,env);} ))return false;if(Array.isArray(rule.any)&&!rule.any.some(function(x){return matchRule(x,env);} ))return false;if(rule.not&&matchRule(rule.not,env))return false;if(rule.qb&&!matchRange(env.qb,rule.qb))return false;if(rule.webApi&&!matchRange(env.webApi,rule.webApi))return false;return true;}
  function asset(path){return W.buildAssetUrl?W.buildAssetUrl(path):path;}
  function load(){if(loadTask)return loadTask;loadTask=fetch(asset('data/capabilities.json'),{credentials:'same-origin',cache:'no-store'}).then(function(res){if(!res.ok)throw new Error('Capability registry HTTP '+res.status);return res.json();}).then(function(next){if(!next||next.schemaVersion!==1||!next.features)throw new Error('Invalid capability registry');data=next;return data;});return loadTask;}
  function env(){return{qb:client&&client.qbVersion||'0',webApi:client&&client.webApiVersion||'0'};}
  function feature(id){return data&&data.features&&data.features[id]||null;}
  function supports(id){var f=feature(id);return !f?true:matchRule(f.rule,env());}
  function formatVersion(v){var raw=String(v==null?'0':v).replace(/^v/i,'').split(/[+-]/)[0],p=raw.split('.');while(p.length<3)p.push('0');return p.join('.');}
  function formatLower(v){return formatVersion(v)+'+';}
  function rangeLabel(range){range=range||{};if(range.eq!=null)return formatVersion(range.eq);if(range.gte!=null&&range.lt!=null)return '≥'+formatVersion(range.gte)+' <'+formatVersion(range.lt);if(range.gte!=null&&range.lte!=null)return formatVersion(range.gte)+'–'+formatVersion(range.lte);if(range.gte!=null)return formatLower(range.gte);if(range.gt!=null)return '>'+formatVersion(range.gt);if(range.lt!=null)return '<'+formatVersion(range.lt);if(range.lte!=null)return '≤'+formatVersion(range.lte);return'';}
  function lowerFromRange(range){range=range||{};if(range.gte!=null)return formatVersion(range.gte);if(range.gt!=null)return formatVersion(range.gt);if(range.eq!=null)return formatVersion(range.eq);return'';}
  function milestoneForWebApi(range){if(!data||!Array.isArray(data.webApiMilestones)||!range)return null;for(var i=0;i<data.webApiMilestones.length;i++){var m=data.webApiMilestones[i];if(matchRange(m.webApi,range))return m;}return null;}
  function requirementFacts(id){var f=feature(id),rule=f&&f.rule||{},p=f&&f.presentation||{},req=p.requirements||{},webApi=req.webApi||lowerFromRange(rule.webApi),qb=req.qb||lowerFromRange(rule.qb),knownQb=req.knownQb||'';if(!knownQb&&webApi){var m=milestoneForWebApi({gte:webApi});if(m)knownQb=m.qb;}if(!knownQb&&qb)knownQb=qb;return{qb:qb||'',webApi:webApi||'',knownQb:knownQb||''};}
  function badgeFor(id){var f=feature(id);if(!f)return'';var p=f.presentation||{},facts=requirementFacts(id),rule=f.rule||{};if(p.badge&&p.badge!=='auto')return String(p.badge);if(facts.qb)return formatLower(facts.qb);if(facts.knownQb)return formatLower(facts.knownQb);if(rule.qb)return rangeLabel(rule.qb);if(rule.webApi){var m=milestoneForWebApi(rule.webApi);return m?formatLower(m.qb):local(p.unknownBadge,zh()?'需升级':'Upgrade');}return local(p.unknownBadge,zh()?'需升级':'Upgrade');}
  function ruleLines(id){var facts=requirementFacts(id),qb=facts.qb?formatLower(facts.qb):'—',webApi=facts.webApi?formatLower(facts.webApi):'—';return[(zh()?'qBittorrent 要求：':'qBittorrent requirement: ')+qb,(zh()?'WebAPI 要求：':'WebAPI requirement: ')+webApi];}
  function affordanceLayout(node){return node&&node.querySelector&&node.querySelector('.ui-select__trigger')?'control':'inline';}
  function clearAffordance(node){if(!node)return;delete node.dataset.capabilityLayout;node.classList.remove('capability-affordance','capability-affordance--control','capability-affordance--inline');}
  function markAffordance(node){var layout=affordanceLayout(node);node.dataset.capabilityLayout=layout;node.classList.add('capability-affordance');node.classList.toggle('capability-affordance--control',layout==='control');node.classList.toggle('capability-affordance--inline',layout==='inline');return layout;}
  function clearBadge(node){if(!node)return;var badges=[];if(node.querySelectorAll)badges=Array.from(node.querySelectorAll('.capability-badge'));badges.forEach(function(child){child.remove();});}
  function badgeHost(node,layout){if(layout==='control'&&node&&node.querySelector){var trigger=node.querySelector('.ui-select__trigger');if(trigger)return trigger;}return node;}
  function ensureDialog(){if(dialog&&dialog.isConnected)return dialog;var d=document.createElement('dialog');d.id='capability-dialog';d.className='dialog surface surface--modal capability-dialog';d.innerHTML='<div class="dialog__head"><div><div class="eyebrow">QBITTORRENT</div><h2 class="capability-dialog__title"></h2></div><button type="button" class="icon-btn capability-dialog__close">×</button></div><div class="dialog__body capability-dialog__body"><p class="capability-dialog__reason"></p><div class="capability-dialog__requirements"></div><div class="capability-dialog__current"></div><p class="text-description capability-dialog__advice"></p></div><div class="dialog__actions"><button type="button" class="btn btn--primary capability-dialog__done"></button></div>';d.querySelector('.capability-dialog__close').onclick=d.querySelector('.capability-dialog__done').onclick=function(){d.close();};document.body.appendChild(d);dialog=d;return d;}
  function open(id){var f=feature(id);if(!f)return null;var d=ensureDialog(),current=env();d.dataset.dialogCapability=id;d.querySelector('.capability-dialog__title').textContent=local(f.copy&&f.copy.title,zh()?'功能不可用':'Feature unavailable');d.querySelector('.capability-dialog__reason').textContent=local(f.copy&&f.copy.reason,zh()?'当前版本不支持此功能。':'This feature is not supported by the current version.');var req=d.querySelector('.capability-dialog__requirements');req.textContent='';ruleLines(id).forEach(function(line){var row=document.createElement('div');row.className='capability-dialog__row';row.textContent=line;req.appendChild(row);});var cur=d.querySelector('.capability-dialog__current');cur.textContent='';[(zh()?'当前 qBittorrent：':'Current qBittorrent: ')+(current.qb||'—'),(zh()?'当前 WebAPI：':'Current WebAPI: ')+(current.webApi||'—')].forEach(function(line){var row=document.createElement('div');row.className='capability-dialog__row';row.textContent=line;cur.appendChild(row);});d.querySelector('.capability-dialog__advice').textContent=zh()?'该功能由当前 qBittorrent / WebAPI 能力决定。升级前请备份 qBittorrent 配置与任务数据。':'Availability is determined by the detected qBittorrent / WebAPI capability. Back up qBittorrent configuration and torrent data before upgrading.';d.querySelector('.capability-dialog__done').textContent=zh()?'知道了':'OK';if(!d.open)d.showModal();return d;}
  function decorate(node,id){if(!node)return;id=id||node.dataset.capability||node.dataset.capabilityId;if(!id)return;node.dataset.capabilityId=id;var f=feature(id);if(!f)return;var supported=supports(id),policy=(f.presentation&&f.presentation.unsupported)||'disable';node.classList.toggle('is-capability-disabled',!supported&&policy==='disable');node.setAttribute('aria-disabled',!supported&&policy==='disable'?'true':'false');delete node.dataset.tooltip;if(!supported&&policy==='hide'){clearBadge(node);clearAffordance(node);node.hidden=true;return;}node.hidden=false;clearBadge(node);if(supported){clearAffordance(node);return;}var layout=markAffordance(node);var badge=document.createElement('span');badge.className='capability-badge';badge.textContent=badgeFor(id);badge.setAttribute('aria-hidden','true');badgeHost(node,layout).appendChild(badge);}
  function sync(){if(!data||!client)return;Object.keys(data.features||{}).forEach(function(id){var f=data.features[id]||{},selectors=Array.isArray(f.selectors)?f.selectors:[];selectors.forEach(function(selector){document.querySelectorAll(selector).forEach(function(node){decorate(node,id);});});});document.querySelectorAll('[data-capability]').forEach(function(node){decorate(node,node.dataset.capability);});}
  function bind(nextClient){client=nextClient||client;return load().then(function(){sync();return api;});}
  function state(id){var f=feature(id);return{id:id,supported:supports(id),badge:badgeFor(id),feature:f,requirements:requirementFacts(id),environment:env()};}
  function intercept(event){var node=event.target&&event.target.closest&&event.target.closest('[data-capability-id]');if(!node||node.getAttribute('aria-disabled')!=='true')return;event.preventDefault();event.stopImmediatePropagation();open(node.dataset.capabilityId);}
  document.addEventListener('click',intercept,true);
  global.addEventListener('weigg:library-state',function(){requestAnimationFrame(sync);});
  global.addEventListener('weigg:languagechange',function(){requestAnimationFrame(sync);if(dialog&&dialog.open&&dialog.dataset.dialogCapability)open(dialog.dataset.dialogCapability);});

  var api={load:load,ready:load,bind:bind,supports:supports,state:state,open:open,sync:sync,decorate:decorate,compareVersions:compare,matchRange:matchRange,matchRule:matchRule,badgeFor:badgeFor,formatVersion:formatVersion,requirementFacts:requirementFacts,ruleLines:ruleLines};
  W.CapabilityRegistry=api;
  W.CapabilityDialog={open:function(value){return typeof value==='string'?open(value):null;},close:function(){if(dialog&&dialog.open)dialog.close();}};
})(window);
