(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{};
  if(W.CapabilityRegistry)return;
  var data=null,client=null,loadTask=null,dialog=null,current=null,domains={},domainTasks={},sourceFactOwners={};
  function tr(key,vars){return W.I18n&&W.I18n.t?W.I18n.t(key,vars):String(key||'');}
  function featureCopy(id,part,fallback){var key='capability.'+String(id||'')+'.'+String(part||''),value=tr(key);return value&&value!==key?value:String(fallback||'');}
  function parts(value){return String(value||'0').replace(/^v/i,'').split(/[+-]/)[0].split('.').map(function(x){var n=parseInt(x,10);return Number.isFinite(n)?n:0;});}
  function prerelease(value){var raw=String(value||'').toLowerCase().replace(/^v/,'').split('+')[0],match=raw.match(/(?:[-._]?)(dev|nightly|alpha|beta|preview|pre|rc)(?:[-._]?(\d+))?$/);if(!match)return{rank:5,number:0};var ranks={dev:0,nightly:0,alpha:1,beta:2,preview:3,pre:3,rc:4};return{rank:ranks[match[1]],number:Number(match[2]||0)};}
  function compare(a,b){var x=parts(a),y=parts(b),n=Math.max(x.length,y.length);for(var i=0;i<n;i++){var av=x[i]||0,bv=y[i]||0;if(av>bv)return 1;if(av<bv)return-1;}var ax=prerelease(a),bx=prerelease(b);return ax.rank!==bx.rank?(ax.rank>bx.rank?1:-1):(ax.number>bx.number?1:ax.number<bx.number?-1:0);}
  function matchRange(actual,range){range=range||{};if(range.eq!=null&&compare(actual,range.eq)!==0)return false;if(range.gt!=null&&compare(actual,range.gt)<=0)return false;if(range.gte!=null&&compare(actual,range.gte)<0)return false;if(range.lt!=null&&compare(actual,range.lt)>=0)return false;if(range.lte!=null&&compare(actual,range.lte)>0)return false;return true;}
  function matchRule(rule,env){rule=rule||{};env=env||{};if(Array.isArray(rule.all)&&!rule.all.every(function(x){return matchRule(x,env);} ))return false;if(Array.isArray(rule.any)&&!rule.any.some(function(x){return matchRule(x,env);} ))return false;if(rule.not&&matchRule(rule.not,env))return false;if(rule.qb&&!matchRange(env.qb,rule.qb))return false;if(rule.webApi&&!matchRange(env.webApi,rule.webApi))return false;return true;}
  function asset(path){return W.buildAssetUrl?W.buildAssetUrl(path):path;}
  function rawVersion(value){return String(value||'0').trim().replace(/^v/i,'');}
  function normalizedVersion(value){return rawVersion(value).split(/[+-]/)[0];}
  function sameSeries(a,b){var x=parts(a),y=parts(b);return(x[0]||0)===(y[0]||0)&&(x[1]||0)===(y[1]||0);}
  function sameMajor(a,b){var x=parts(a),y=parts(b);return(x[0]||0)===(y[0]||0)&&(x[0]||0)>0;}
  function request(path,label,type){var loader=W.RuntimeAssets;if(!loader)return Promise.reject(new Error('RuntimeAssets unavailable for '+label));var options={namespace:'compat',identity:'build'};return(type==='text'?loader.readText(path,options):loader.readJson(path,options)).catch(function(error){throw new Error(label+': '+String(error&&error.message||error));});}
  function fetchJson(path,label){return request(path,label,'json');}
  function identityKey(value){value=value||{};return[String(value.supportFloor||''),String(value.latestAdmittedStable||''),Number(value.releaseCount)||0,String(value.releaseSetSha256||''),String(value.sourceCatalogSha256||'')].join('|');}
  function sameCatalogIdentity(a,b){return !!(a&&b&&identityKey(a)===identityKey(b));}
  function loadSettingsDomain(path){return fetchJson(path,'Settings compatibility manifest').then(function(manifest){if(!manifest||manifest.schemaVersion!==3||manifest.source!=='qb-upstream-preferences-native-surface-runtime'||manifest.encoding!=='deflate-raw-base64-json'||!manifest.payload||!sameCatalogIdentity(manifest.catalogIdentity,data&&data.catalogIdentity))throw new Error('Invalid Settings runtime manifest');var loader=W.RuntimeAssets;if(!loader||typeof loader.decodeDeflateJson!=='function')throw new Error('RuntimeAssets deflate JSON decoder unavailable');var value=loader.decodeDeflateJson(manifest.payload,'Settings runtime payload');if(!value||value.schemaVersion!==manifest.payload.schemaVersion||value.source!==manifest.payload.source||!sameCatalogIdentity(value.catalogIdentity,manifest.catalogIdentity))throw new Error('Settings source-native payload identity mismatch');return value;});}
  function load(){if(loadTask)return loadTask;loadTask=fetchJson('data/capabilities.json','Capability core contract').then(function(next){if(!next||next.schemaVersion!==2||!next.features||!Array.isArray(next.releases)||!next.releases.length||!next.compatFiles||!next.catalogIdentity||!next.domainRelations||next.domainRelations.schemaVersion!==1)throw new Error('Invalid compact capability control plane');next.sourceFacts={};next.sourceActions={};data=next;return data;});return loadTask;}
  function mergeDomain(name,value){if(name==='torrent'||name==='detail'){if(!value||value.schemaVersion!==1||!value.sourceFacts)throw new Error('Invalid '+name+' compatibility contract');data.sourceFacts=Object.assign({},data.sourceFacts,value.sourceFacts);Object.keys(value.sourceFacts).forEach(function(key){sourceFactOwners[key]=name;});}else if(name==='actions'){if(!value||value.schemaVersion!==1||!value.sourceActions)throw new Error('Invalid source action contract');data.sourceActions=value.sourceActions;}else if(name==='settings'){if(!value||value.schemaVersion!==2||value.source!=='qb-upstream-preferences-native-surface-compact'||!value.preferences||!value.descriptors||!Array.isArray(value.releases)||!sameCatalogIdentity(value.catalogIdentity,data.catalogIdentity))throw new Error('Invalid source-native Settings compatibility contract');if(value.releases.length!==(data.releases||[]).length)throw new Error('Settings release-set length mismatch');for(var i=0;i<value.releases.length;i++){var row=value.releases[i],release=data.releases[i];if(!Array.isArray(row)||String(row[0])!==String(release&&release.qbVersion||'')||String(row[1]||'').toLowerCase()!==String(release&&release.sourceSha||'').toLowerCase())throw new Error('Settings exact release identity mismatch');}}domains[name]=value;return value;}
  function ensure(name){name=String(name||'');if(domains[name])return Promise.resolve(domains[name]);if(domainTasks[name])return domainTasks[name];domainTasks[name]=load().then(function(){var path=data&&data.compatFiles&&data.compatFiles[name];if(!path)throw new Error('Unknown compatibility domain '+name);return name==='settings'?loadSettingsDomain(path):fetchJson(path,name+' compatibility contract');}).then(function(value){return mergeDomain(name,value);}).finally(function(){delete domainTasks[name];});return domainTasks[name];}
  function domain(name){return domains[String(name||'')]||null;}
  function env(){return{qb:client&&client.qbVersion||'0',webApi:client&&client.webApiVersion||'0'};}
  function feature(id){return data&&data.features&&data.features[id]||null;}
  function releaseByVersion(qb){var target=normalizedVersion(qb);return(data&&data.releases||[]).find(function(item){return normalizedVersion(item&&item.qbVersion)===target;})||null;}
  function exactRelease(qb){var raw=rawVersion(qb),hit=releaseByVersion(qb);return hit&&raw===normalizedVersion(hit.qbVersion)?hit:null;}
  function inheritedRelease(qb,webApi){var target=rawVersion(qb),api=normalizedVersion(webApi),candidates=(data&&data.releases||[]).filter(function(item){return item&&item.officialWeiGSupport!==false&&sameMajor(item.qbVersion,target)&&compare(item.qbVersion,target)<=0;}).sort(function(a,b){return compare(b.qbVersion,a.qbVersion);}),base=candidates[0]||null;if(!base)return null;if(api&&api!=='0'&&base.webApiVersion&&compare(api,base.webApiVersion)<0)return null;return base;}
  function equivalentRelease(qb,domain){var table=data&&data.domainRelations&&data.domainRelations.specialStable||{},spec=table[normalizedVersion(qb)]||null,baseVersion=spec&&spec.equivalent&&spec.equivalent[String(domain||'')];if(!baseVersion)return null;var exact=releaseByVersion(qb),base=releaseByVersion(baseVersion);if(!exact||!base||base.officialWeiGSupport===false||!sameSeries(exact.qbVersion,base.qbVersion)||compare(base.qbVersion,exact.qbVersion)>0)return null;return base;}
  function resolutionObject(domain,qb,api,catalogHit,base,mode){var fallback=!base,detected=rawVersion(qb),detectedApi=normalizedVersion(api);return{domain:String(domain||'core'),qbVersion:fallback?normalizedVersion(qb):normalizedVersion(base.qbVersion),detectedQbVersion:detected,detectedWebApiVersion:detectedApi,catalogQbVersion:catalogHit?normalizedVersion(catalogHit.qbVersion):'',webApiVersion:fallback?detectedApi:normalizedVersion(base.webApiVersion||api),sourceSha:fallback?'':String(base.sourceSha||''),copyRouteId:!fallback&&String(domain||'')==='copy'?String(base.copyRouteId||''):'',resolvedFrom:fallback?'':normalizedVersion(base.qbVersion),resolutionMode:mode,inherited:mode==='INHERITED',equivalent:mode==='EQUIVALENT',fallback:fallback,officialWeiGSupport:!fallback&&base.officialWeiGSupport!==false,certified:!fallback&&base.officialWeiGSupport!==false&&(mode==='EXACT'||mode==='EQUIVALENT')};}
  function domainResolution(name){name=String(name||'');if(!client||!data)return null;var qb=client.qbVersion||'0',api=client.webApiVersion||'0',hit=exactRelease(qb),base=null,mode='FALLBACK';if(hit){base=equivalentRelease(hit.qbVersion,name)||hit;mode=base===hit?'EXACT':'EQUIVALENT';}else{base=inheritedRelease(qb,api);if(base)mode='INHERITED';}return resolutionObject(name,qb,api,hit,base,mode);}
  function domainResolutions(){var names=Object.keys(data&&data.compatFiles||{}).concat(['locale','copy']),out={};Array.from(new Set(names)).forEach(function(name){out[name]=domainResolution(name);});return out;}
  function resolveRelease(){var qb=client&&client.qbVersion||'0',api=client&&client.webApiVersion||'0',hit=exactRelease(qb),base=hit,mode=hit?'EXACT':'FALLBACK';if(!base){base=inheritedRelease(qb,api);if(base)mode='INHERITED';}current=resolutionObject('core',qb,api,hit,base,mode);return current;}
  function releaseIdentity(){if(!current)return null;return{qbVersion:String(current.qbVersion||''),detectedQbVersion:String(current.detectedQbVersion||''),detectedWebApiVersion:String(current.detectedWebApiVersion||''),catalogQbVersion:String(current.catalogQbVersion||''),webApiVersion:String(current.webApiVersion||''),sourceSha:String(current.sourceSha||''),resolvedFrom:String(current.resolvedFrom||''),fallback:current.fallback===true,officialWeiGSupport:current.officialWeiGSupport!==false,resolutionMode:String(current.resolutionMode||''),inherited:current.inherited===true,equivalent:current.equivalent===true,certified:isCertified()};}
  function changeValue(changes,qb){if(!Array.isArray(changes)||!changes.length)return null;var hit=null;for(var i=0;i<changes.length;i++){if(compare(changes[i].from,qb)<=0)hit=changes[i].value;else break;}return hit;}
  function clone(value){if(Array.isArray(value))return value.map(clone);if(value&&typeof value==='object'){var out={};Object.keys(value).forEach(function(key){out[key]=clone(value[key]);});return out;}return value;}
  function applyMerge(target,patch){if(!patch||typeof patch!=='object'||Array.isArray(patch))return clone(patch);var out=target&&typeof target==='object'&&!Array.isArray(target)?clone(target):{};Object.keys(patch).forEach(function(key){var value=patch[key];if(value===null)delete out[key];else out[key]=applyMerge(out[key],value);});return out;}
  function resolveMerge(spec,qb){var value=null,changes=spec&&spec.changes;if(!Array.isArray(changes))return null;for(var i=0;i<changes.length;i++){var change=changes[i];if(compare(change.from,qb)>0)break;if(Object.prototype.hasOwnProperty.call(change,'value'))value=clone(change.value);else if(Object.prototype.hasOwnProperty.call(change,'patch'))value=applyMerge(value,change.patch);}return value;}
  function resolveKeyed(spec,qb){var order=changeValue(spec&&spec.order,qb);if(!Array.isArray(order)||!spec.items)return[];return order.map(function(key){return changeValue(spec.items[key],qb);}).filter(function(item){return item!=null;}).map(clone);}
  function factDomain(name){name=String(name||'');return name==='webuiLocales'?'locale':String(sourceFactOwners[name]||'torrent');}
  function sourceFact(name){var resolution=domainResolution(factDomain(name));if(!resolution||resolution.fallback||!data||!data.sourceFacts)return null;var spec=data.sourceFacts[name],qb=resolution.qbVersion;if(Array.isArray(spec))return clone(changeValue(spec,qb));if(spec&&spec.mode==='merge')return resolveMerge(spec,qb);if(spec&&spec.mode==='keyed')return resolveKeyed(spec,qb);return null;}
  function webuiLocales(){var items=sourceFact('webuiLocales');return Array.isArray(items)?items.map(function(item){return item&&typeof item==='object'?Object.assign({},item):item;}):[];}
  function hasExactSourceFacts(){var resolution=domainResolution('torrent');return !!(resolution&&resolution.fallback!==true);}
  function canonicalFilter(name){name=String(name||'all');if(name==='paused')return'stopped';if(name==='resumed')return'running';return name;}
  function rawTorrentFilters(){var list=sourceFact('torrentFilters');return Array.isArray(list)?Array.from(new Set(list.map(String))):[];}
  function torrentFilters(){return Array.from(new Set(rawTorrentFilters().map(canonicalFilter)));}
  function torrentVisibleFilters(){var list=sourceFact('torrentVisibleFilters');return Array.isArray(list)?list.filter(function(item){return item&&typeof item==='object'&&item.name;}).map(function(item){return clone(item);}):[];}
  function facetSpecialRows(kind){var value=sourceFact('facetSpecialRows');if(!value||typeof value!=='object'||Array.isArray(value))return kind?{}:{};if(kind){var rows=value[String(kind||'')];return rows&&typeof rows==='object'&&!Array.isArray(rows)?clone(rows):{};}return clone(value);}
  function upstreamTorrentFilter(name){if(!current)return undefined;name=String(name||'all');var list=rawTorrentFilters();if(list.indexOf(name)>=0)return name;if(name==='stopped'&&list.indexOf('paused')>=0)return'paused';if(name==='running'&&list.indexOf('resumed')>=0)return'resumed';return null;}
  function supportsTorrentFilter(name){return upstreamTorrentFilter(name)!==null;}
  function factList(name){var list=sourceFact(name);return Array.isArray(list)?list.map(String):[];}
  function hasTorrentInfoParameter(name){return factList('torrentInfoParameters').indexOf(String(name||''))>=0;}
  function hasTorrentInfoField(name){return factList('torrentInfoFields').indexOf(String(name||''))>=0;}
  function trackerFilters(){var list=sourceFact('trackerFilters');return Array.isArray(list)?list.filter(function(item){return item&&typeof item==='object'&&item.id;}).map(function(item){return clone(item);}):[];}
  function trackerFacetMode(){var mode=sourceFact('trackerFacetMode');return['none','url','hostname'].indexOf(String(mode||''))>=0?String(mode):null;}
  function torrentStates(){return factList('torrentStates');}
  function torrentContextMenu(){var list=sourceFact('torrentContextMenu');return Array.isArray(list)?list.filter(function(item){return item&&typeof item==='object'&&item.id;}).map(function(item){return clone(item);}):[];}
  function statisticsUi(){var value=sourceFact('statisticsUi');return value&&typeof value==='object'&&!Array.isArray(value)&&Array.isArray(value.groups)?clone(value):null;}
  function torrentFieldFacts(){if(!hasExactSourceFacts()||current.officialWeiGSupport===false)return null;var fields=factList('torrentInfoFields'),columns=sourceFact('torrentTableColumns');return{fallback:false,officialWeiGSupport:true,torrentInfoFields:fields,torrentTableColumns:Array.isArray(columns)?columns.map(function(column){return column&&typeof column==='object'?Object.assign({},column):column;}):[]};}
  function torrentDetailUi(){var resolution=domainResolution('detail');if(!resolution||resolution.fallback)return null;var ui=sourceFact('torrentDetailUi');return ui&&typeof ui==='object'&&!Array.isArray(ui)?ui:null;}
  function detailFields(surface){var map={properties:'torrentPropertiesFields',trackers:'torrentTrackerFields',files:'torrentFileFields',webseeds:'torrentWebSeedFields'},key=map[String(surface||'')];return key?factList(key):[];}
  function hasTorrentDetailField(surface,name){return detailFields(surface).indexOf(String(name||''))>=0;}
  function sourceActionValue(action){var resolution=domainResolution('actions');if(!resolution||resolution.fallback||!data||!data.sourceActions)return null;return changeValue(data.sourceActions[String(action||'')],resolution.qbVersion);}
  function hasAction(action){return !!(action&&sourceActionValue(action));}
  function actionDescriptor(action){var key=String(action||''),spec=sourceActionValue(key);if(!spec)return null;var name=(key.split(':')[1]||'').replace(/Action$/,'');return{sourceAction:key,endpoint:name,parameters:Array.isArray(spec.parameters)?spec.parameters.map(String):[],required:Array.isArray(spec.required)?spec.required.map(String):[],optional:Array.isArray(spec.optional)?spec.optional.map(String):[],parameterOptions:spec.parameterOptions&&typeof spec.parameterOptions==='object'?Object.assign({},spec.parameterOptions):{}};}
  function isResolutionCertified(value){return !!(value&&!value.fallback&&value.officialWeiGSupport!==false&&(value.resolutionMode==='EXACT'||value.resolutionMode==='EQUIVALENT')&&value.detectedWebApiVersion&&value.detectedWebApiVersion!=='0'&&normalizedVersion(value.detectedWebApiVersion)===normalizedVersion(value.webApiVersion));}
  function isCertified(domainName){return domainName?isResolutionCertified(domainResolution(domainName)):isResolutionCertified(current);}
  // HTTP method does not define the semantics of the operation. The source
  // action is required in addition to exact inherited WebAPI identity.
  var POST_READ_ACTIONS=Object.freeze({'clientdata/load':'clientdatacontroller.h:loadAction'});
  function inheritedActionProof(){
    if(!domains.actions)return false;
    var release=domainResolution('actions');
    return !!(release&&!release.fallback&&release.resolutionMode==='INHERITED'&&release.sourceSha&&normalizedVersion(release.detectedWebApiVersion)===normalizedVersion(release.webApiVersion));
  }
  function allowsReadOperation(path,method){
    if(String(method||'').toUpperCase()!=='POST')return false;
    var endpoint=String(path||'').replace(/^[/]+/,'').split('?')[0],action=POST_READ_ACTIONS[endpoint];
    if(!action||!inheritedActionProof())return false;
    return !!actionDescriptor(action);
  }
  // Only bounded additive operations inherit; the HTTP verb and WebAPI alone
  // are never sufficient evidence of an unknown version's mutation safety.
  var INHERITED_ADDITIVE_ACTIONS=Object.freeze({'torrents/add':'torrentscontroller.h:addAction'});
  function allowsWriteOperation(path,method,sourceAction,body){
    if(String(method||'').toUpperCase()!=='POST')return false;
    var endpoint=String(path||'').replace(/^[/]+/,'').split('?')[0],action=INHERITED_ADDITIVE_ACTIONS[endpoint];
    if(!action||action!==String(sourceAction||'')||!body||typeof body.keys!=='function'||!inheritedActionProof())return false;
    var desc=actionDescriptor(action),fields=Array.from(body.keys());
    if(!desc||!Array.isArray(desc.parameters)||desc.parameters.indexOf('urls')<0||!fields.length)return false;
    return fields.some(function(key){return key==='urls'||key==='torrents';})&&fields.every(function(key){return key==='torrents'||desc.parameters.indexOf(key)>=0;});
  }
  function hasWriteProvenance(domainName){return isCertified(domainName||'actions');}
  function supportsWriteAction(action){return !!(action&&hasWriteProvenance('actions')&&hasAction(action));}
  function sourceActionDescriptor(action){if(!data||!current)return undefined;if(current.fallback===true)return null;return actionDescriptor(String(action||''));}
  var TORRENT_ACTION_CHOICES={start:[['torrentscontroller.h:startAction','start'],['torrentscontroller.h:resumeAction','resume']],stop:[['torrentscontroller.h:stopAction','stop'],['torrentscontroller.h:pauseAction','pause']],delete:[['torrentscontroller.h:deleteAction','delete']],force:[['torrentscontroller.h:setForceStartAction','setForceStart']],recheck:[['torrentscontroller.h:recheckAction','recheck']],reannounce:[['torrentscontroller.h:reannounceAction','reannounce']],sequential:[['torrentscontroller.h:toggleSequentialDownloadAction','toggleSequentialDownload']],firstlast:[['torrentscontroller.h:toggleFirstLastPiecePrioAction','toggleFirstLastPiecePrio']],autotmm:[['torrentscontroller.h:setAutoManagementAction','setAutoManagement']],superseeding:[['torrentscontroller.h:setSuperSeedingAction','setSuperSeeding']],top:[['torrentscontroller.h:topPrioAction','topPrio']],increase:[['torrentscontroller.h:increasePrioAction','increasePrio']],decrease:[['torrentscontroller.h:decreasePrioAction','decreasePrio']],bottom:[['torrentscontroller.h:bottomPrioAction','bottomPrio']],export:[['torrentscontroller.h:exportAction','export']],rename:[['torrentscontroller.h:renameAction','rename']],location:[['torrentscontroller.h:setLocationAction','setLocation']],category:[['torrentscontroller.h:setCategoryAction','setCategory']],tags:[['torrentscontroller.h:addTagsAction','addTags']],dllimit:[['torrentscontroller.h:setDownloadLimitAction','setDownloadLimit']],uplimit:[['torrentscontroller.h:setUploadLimitAction','setUploadLimit']],addTrackers:[['torrentscontroller.h:addTrackersAction','addTrackers']],removeTrackers:[['torrentscontroller.h:removeTrackersAction','removeTrackers']],editTracker:[['torrentscontroller.h:editTrackerAction','editTracker']]};function actionChoices(kind){return TORRENT_ACTION_CHOICES[String(kind||'')]||[];}function torrentActionSurface(){return Object.keys(TORRENT_ACTION_CHOICES).map(function(kind){var descriptor=resolveTorrentActionDescriptor(kind);return{kind:kind,supported:!!descriptor,descriptor:descriptor};});}function torrentSourceActionInventory(){if(!data||!data.sourceActions)return[];return Object.keys(data.sourceActions).filter(function(key){return key.indexOf('torrentscontroller.h:')===0;}).map(function(key){return actionDescriptor(key);}).filter(Boolean);}
  function resolveTorrentActionDescriptor(kind){kind=String(kind||'');if(!current||!hasWriteProvenance())return null;var choices=actionChoices(kind);for(var i=0;i<choices.length;i++){var desc=actionDescriptor(choices[i][0]);if(desc){desc.endpoint=choices[i][1];desc.kind=kind;return desc;}}return null;}
  function supportsTorrentAction(kind){return !!resolveTorrentActionDescriptor(kind);}
  function sourceTruth(f){var upstream=f&&f.upstream;if(f&&f.writeRequired===true&&!hasWriteProvenance())return false;if(!upstream||!hasExactSourceFacts())return null;if(Array.isArray(upstream.allActions))return upstream.allActions.length>0&&upstream.allActions.every(function(action){return hasAction(String(action));});if(Array.isArray(upstream.anyActions))return upstream.anyActions.some(function(action){return hasAction(String(action));});if(upstream.action)return hasAction(String(upstream.action));if(upstream.actionParameter){var spec=upstream.actionParameter||{},desc=actionDescriptor(String(spec.action||''));return !!(desc&&Array.isArray(desc.parameters)&&desc.parameters.indexOf(String(spec.parameter||''))>=0);}if(upstream.torrentFilter)return supportsTorrentFilter(upstream.torrentFilter);if(upstream.torrentInfoParameter)return hasTorrentInfoParameter(upstream.torrentInfoParameter);if(upstream.torrentInfoField)return hasTorrentInfoField(upstream.torrentInfoField);return null;}
  function supports(id){var f=feature(id);if(!f)return false;var truth=sourceTruth(f);if(truth!==null)return !!truth;if(f.sourceRequired===true)return false;return matchRule(f.rule,env());}
  function formatVersion(v){var raw=String(v==null?'0':v).replace(/^v/i,'').split(/[+-]/)[0],p=raw.split('.');while(p.length<3)p.push('0');return p.join('.');}
  function formatLower(v){return formatVersion(v)+'+';}
  function rangeLabel(range){range=range||{};if(range.eq!=null)return formatVersion(range.eq);if(range.gte!=null&&range.lt!=null)return '≥'+formatVersion(range.gte)+' <'+formatVersion(range.lt);if(range.gte!=null&&range.lte!=null)return formatVersion(range.gte)+'–'+formatVersion(range.lte);if(range.gte!=null)return formatLower(range.gte);if(range.gt!=null)return '>'+formatVersion(range.gt);if(range.lt!=null)return '<'+formatVersion(range.lt);if(range.lte!=null)return '≤'+formatVersion(range.lte);return'';}
  function lowerFromRange(range){range=range||{};if(range.gte!=null)return formatVersion(range.gte);if(range.gt!=null)return formatVersion(range.gt);if(range.eq!=null)return formatVersion(range.eq);return'';}
  function milestoneForWebApi(range){if(!data||!Array.isArray(data.webApiMilestones)||!range)return null;for(var i=0;i<data.webApiMilestones.length;i++){var m=data.webApiMilestones[i];if(matchRange(m.webApi,range))return m;}return null;}
  function requirementFacts(id){var f=feature(id),rule=f&&f.rule||{},p=f&&f.presentation||{},req=p.requirements||{},webApi=req.webApi||lowerFromRange(rule.webApi),qb=req.qb||lowerFromRange(rule.qb),knownQb=req.knownQb||'';if(!knownQb&&webApi){var m=milestoneForWebApi({gte:webApi});if(m)knownQb=m.qb;}if(!knownQb&&qb)knownQb=qb;return{qb:qb||'',webApi:webApi||'',knownQb:knownQb||''};}
  function badgeFor(id){var f=feature(id);if(!f)return'';var p=f.presentation||{},facts=requirementFacts(id),rule=f.rule||{};if(p.badge&&p.badge!=='auto')return String(p.badge);if(facts.qb)return formatLower(facts.qb);if(facts.knownQb)return formatLower(facts.knownQb);if(rule.qb)return rangeLabel(rule.qb);if(rule.webApi){var m=milestoneForWebApi(rule.webApi);return m?formatLower(m.qb):tr('capability.upgrade');}return tr('capability.upgrade');}
  function ruleLines(id){var facts=requirementFacts(id),qb=facts.qb?formatLower(facts.qb):'—',webApi=facts.webApi?formatLower(facts.webApi):'—';return[tr('capability.qbRequirement',{value:qb}),tr('capability.webApiRequirement',{value:webApi})];}
  function affordanceLayout(node){return node&&node.querySelector&&node.querySelector('.ui-select__trigger')?'control':'inline';}
  function clearAffordance(node){if(!node)return;delete node.dataset.capabilityLayout;node.classList.remove('capability-affordance','capability-affordance--control','capability-affordance--inline');}
  function markAffordance(node){var layout=affordanceLayout(node);node.dataset.capabilityLayout=layout;node.classList.add('capability-affordance');node.classList.toggle('capability-affordance--control',layout==='control');node.classList.toggle('capability-affordance--inline',layout==='inline');return layout;}
  function clearBadge(node){if(!node)return;var badges=[];if(node.querySelectorAll)badges=Array.from(node.querySelectorAll('.capability-badge'));badges.forEach(function(child){child.remove();});}
  function badgeHost(node,layout){if(layout==='control'&&node&&node.querySelector){var trigger=node.querySelector('.ui-select__trigger');if(trigger)return trigger;}return node;}
  function ensureDialog(){if(dialog&&dialog.isConnected)return dialog;var d=W.DialogRuntime.create({id:'capability-dialog',className:'dialog surface surface--modal capability-dialog',draggable:true});d.innerHTML='<div class="dialog__head"><div><div class="eyebrow">QBITTORRENT</div><h2 class="capability-dialog__title"></h2></div><button type="button" class="icon-btn capability-dialog__close">×</button></div><div class="dialog__body capability-dialog__body"><p class="capability-dialog__reason"></p><div class="capability-dialog__requirements"></div><div class="capability-dialog__current"></div><p class="text-description capability-dialog__advice"></p></div><div class="dialog__actions"><button type="button" class="btn btn--primary capability-dialog__done"></button></div>';d.querySelector('.capability-dialog__close').onclick=d.querySelector('.capability-dialog__done').onclick=function(){W.DialogRuntime.close(d);};dialog=d;return d;}
  function open(id){var f=feature(id);if(!f)return null;var d=ensureDialog(),currentEnv=env();d.dataset.dialogCapability=id;d.querySelector('.capability-dialog__title').textContent=featureCopy(id,'title',tr('capability.featureUnavailable'));d.querySelector('.capability-dialog__reason').textContent=featureCopy(id,'reason',tr('capability.unsupportedCurrent'));var req=d.querySelector('.capability-dialog__requirements');req.textContent='';ruleLines(id).forEach(function(line){var row=document.createElement('div');row.className='capability-dialog__row';row.textContent=line;req.appendChild(row);});var cur=d.querySelector('.capability-dialog__current');cur.textContent='';[tr('capability.currentQb',{value:currentEnv.qb||'—'}),tr('capability.currentWebApi',{value:currentEnv.webApi||'—'})].forEach(function(line){var row=document.createElement('div');row.className='capability-dialog__row';row.textContent=line;cur.appendChild(row);});d.querySelector('.capability-dialog__advice').textContent=tr('capability.advice');d.querySelector('.capability-dialog__done').textContent=tr('app.ok');W.DialogRuntime.open(d,{draggable:true});return d;}
  function decorate(node,id){if(!node)return;id=id||node.dataset.capability||node.dataset.capabilityId;if(!id)return;node.dataset.capabilityId=id;var f=feature(id);if(!f){node.hidden=true;return;}var supported=supports(id),policy=(f.presentation&&f.presentation.unsupported)||'disable';node.classList.toggle('is-capability-disabled',!supported&&policy==='disable');node.setAttribute('aria-disabled',!supported&&policy==='disable'?'true':'false');delete node.dataset.tooltip;if(!supported&&policy==='hide'){clearBadge(node);clearAffordance(node);node.hidden=true;return;}node.hidden=false;clearBadge(node);if(supported){clearAffordance(node);return;}var layout=markAffordance(node);var badge=document.createElement('span');badge.className='capability-badge';badge.textContent=badgeFor(id);badge.setAttribute('aria-hidden','true');badgeHost(node,layout).appendChild(badge);}
  function syncClientCapabilities(){if(!client||!data||!data.features)return;var caps=client.capabilities=client.capabilities||{},major=parts(client.qbVersion)[0]||0;caps.legacy4=major===4;caps.modern5=major>=5;caps.certified=isCertified();Object.keys(data.features).forEach(function(id){caps[id]=supports(id);});caps.privateFlag=!!caps.privateFilter;}
  function decorateMatching(node){if(!data||!client||!node)return node;Object.keys(data.features||{}).forEach(function(id){var f=data.features[id]||{},selectors=Array.isArray(f.selectors)?f.selectors:[];selectors.forEach(function(selector){try{if(node.matches&&node.matches(selector))decorate(node,id);if(node.querySelectorAll)node.querySelectorAll(selector).forEach(function(hit){decorate(hit,id);});}catch(_e){}});});if(node.matches&&node.matches('[data-capability]'))decorate(node,node.dataset.capability);if(node.querySelectorAll)node.querySelectorAll('[data-capability]').forEach(function(hit){decorate(hit,hit.dataset.capability);});return node;}
  function sync(){if(!data||!client)return;decorateMatching(document);}
  function bind(nextClient){client=nextClient||client;return load().then(function(){resolveRelease();return Promise.all([ensure('torrent'),ensure('actions')]);}).then(function(){var release=releaseIdentity();if(W.SettingsSchema&&typeof W.SettingsSchema.bindRelease==='function')W.SettingsSchema.bindRelease(domainResolution('settings'));syncClientCapabilities();sync();try{global.dispatchEvent(new CustomEvent('weig:capabilities-ready',{detail:{profile:release,release:release}}));}catch(_e){}return api;});}
  function state(id){var f=feature(id);return{id:id,supported:supports(id),badge:badgeFor(id),feature:f,requirements:requirementFacts(id),environment:env()};}
  function intercept(event){var node=event.target&&event.target.closest&&event.target.closest('[data-capability-id]');if(!node||node.getAttribute('aria-disabled')!=='true')return;event.preventDefault();event.stopImmediatePropagation();open(node.dataset.capabilityId);}
  function interceptKey(event){if(['Enter',' ','ArrowDown','ArrowUp'].indexOf(event.key)<0)return;intercept(event);}
  document.addEventListener('click',intercept,true);document.addEventListener('keydown',interceptKey,true);global.addEventListener('weig:library-state',function(){requestAnimationFrame(sync);});global.addEventListener('weig:languagechange',function(){requestAnimationFrame(sync);if(dialog&&dialog.open&&dialog.dataset.dialogCapability)open(dialog.dataset.dialogCapability);});
  var api={load:load,ready:load,ensure:ensure,domain:domain,bind:bind,supports:supports,state:state,open:open,sync:sync,decorate:decorate,decorateMatching:decorateMatching,compareVersions:compare,matchRange:matchRange,matchRule:matchRule,badgeFor:badgeFor,formatVersion:formatVersion,requirementFacts:requirementFacts,ruleLines:ruleLines,releaseIdentity:releaseIdentity,domainResolution:domainResolution,domainResolutions:domainResolutions,webuiLocales:webuiLocales,hasExactSourceFacts:hasExactSourceFacts,torrentFilters:torrentFilters,torrentVisibleFilters:torrentVisibleFilters,facetSpecialRows:facetSpecialRows,supportsTorrentFilter:supportsTorrentFilter,hasTorrentInfoParameter:hasTorrentInfoParameter,hasTorrentInfoField:hasTorrentInfoField,trackerFilters:trackerFilters,trackerFacetMode:trackerFacetMode,torrentStates:torrentStates,torrentContextMenu:torrentContextMenu,statisticsUi:statisticsUi,torrentFieldFacts:torrentFieldFacts,torrentDetailUi:torrentDetailUi,hasTorrentDetailField:hasTorrentDetailField,actionDescriptor:actionDescriptor,hasWriteProvenance:hasWriteProvenance,allowsReadOperation:allowsReadOperation,allowsWriteOperation:allowsWriteOperation,hasAction:hasAction,supportsWriteAction:supportsWriteAction,isCertified:isCertified,sourceActionDescriptor:sourceActionDescriptor,upstreamTorrentFilter:upstreamTorrentFilter,resolveTorrentActionDescriptor:resolveTorrentActionDescriptor,supportsTorrentAction:supportsTorrentAction,torrentActionSurface:torrentActionSurface,torrentSourceActionInventory:torrentSourceActionInventory};
  W.CapabilityRegistry=api;W.CapabilityDialog={open:function(value){return typeof value==='string'?open(value):null;},close:function(){if(dialog)W.DialogRuntime.close(dialog);}};
})(window);
