(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{};
  if(W.CapabilityRegistry)return;
  var data=null,client=null,loadTask=null,dialog=null,current=null,domains={},domainTasks={};
  function zh(){return !!(W.I18n&&W.I18n.getLocale&&W.I18n.getLocale()==='zh-CN');}
  function local(value,fallback){if(value&&typeof value==='object')return zh()?(value.zh||value.en||fallback):(value.en||value.zh||fallback);return value||fallback||'';}
  function parts(value){return String(value||'0').replace(/^v/i,'').split(/[+-]/)[0].split('.').map(function(x){var n=parseInt(x,10);return Number.isFinite(n)?n:0;});}
  function compare(a,b){var x=parts(a),y=parts(b),n=Math.max(x.length,y.length);for(var i=0;i<n;i++){var av=x[i]||0,bv=y[i]||0;if(av>bv)return 1;if(av<bv)return-1;}return 0;}
  function matchRange(actual,range){range=range||{};if(range.eq!=null&&compare(actual,range.eq)!==0)return false;if(range.gt!=null&&compare(actual,range.gt)<=0)return false;if(range.gte!=null&&compare(actual,range.gte)<0)return false;if(range.lt!=null&&compare(actual,range.lt)>=0)return false;if(range.lte!=null&&compare(actual,range.lte)>0)return false;return true;}
  function matchRule(rule,env){rule=rule||{};env=env||{};if(Array.isArray(rule.all)&&!rule.all.every(function(x){return matchRule(x,env);} ))return false;if(Array.isArray(rule.any)&&!rule.any.some(function(x){return matchRule(x,env);} ))return false;if(rule.not&&matchRule(rule.not,env))return false;if(rule.qb&&!matchRange(env.qb,rule.qb))return false;if(rule.webApi&&!matchRange(env.webApi,rule.webApi))return false;return true;}
  function asset(path){return W.buildAssetUrl?W.buildAssetUrl(path):path;}
  function rawVersion(value){return String(value||'0').trim().replace(/^v/i,'');}
  function normalizedVersion(value){return rawVersion(value).split(/[+-]/)[0];}
  function sameSeries(a,b){var x=parts(a),y=parts(b);return(x[0]||0)===(y[0]||0)&&(x[1]||0)===(y[1]||0);}
  function request(path,label,type){return fetch(asset(path),{credentials:'same-origin',cache:'no-store'}).then(function(res){if(!res.ok)throw new Error(label+' HTTP '+res.status);return type==='text'?res.text():res.json();});}
  function fetchJson(path,label){return request(path,label,'json');}
  function load(){if(loadTask)return loadTask;loadTask=fetchJson('data/capabilities.json','Capability core contract').then(function(next){if(!next||next.schemaVersion!==2||!next.features||!Array.isArray(next.releases)||!next.releases.length||!next.compatFiles)throw new Error('Invalid compact capability control plane');next.sourceFacts={};next.sourceActions={};data=next;return data;});return loadTask;}
  function mergeDomain(name,value){if(name==='torrent'||name==='detail'){if(!value||value.schemaVersion!==1||!value.sourceFacts)throw new Error('Invalid '+name+' compatibility contract');data.sourceFacts=Object.assign({},data.sourceFacts,value.sourceFacts);}else if(name==='actions'){if(!value||value.schemaVersion!==1||!value.sourceActions)throw new Error('Invalid source action contract');data.sourceActions=value.sourceActions;}else if(name==='settings'){if(!value||value.schemaVersion!==1||!value.preferences)throw new Error('Invalid Settings compatibility contract');}domains[name]=value;return value;}
  function ensure(name){name=String(name||'');if(domains[name])return Promise.resolve(domains[name]);if(domainTasks[name])return domainTasks[name];domainTasks[name]=load().then(function(){var path=data&&data.compatFiles&&data.compatFiles[name];if(!path)throw new Error('Unknown compatibility domain '+name);return fetchJson(path,name+' compatibility contract');}).then(function(value){return mergeDomain(name,value);}).finally(function(){delete domainTasks[name];});return domainTasks[name];}
  function domain(name){return domains[String(name||'')]||null;}
  function env(){return{qb:client&&client.qbVersion||'0',webApi:client&&client.webApiVersion||'0'};}
  function feature(id){return data&&data.features&&data.features[id]||null;}
  function exactRelease(qb){var target=normalizedVersion(qb);return(data&&data.releases||[]).find(function(item){return normalizedVersion(item&&item.qbVersion)===target;})||null;}
  function inheritedRelease(qb,webApi){var target=normalizedVersion(qb),api=normalizedVersion(webApi),candidates=(data&&data.releases||[]).filter(function(item){return item&&item.officialWeiGSupport!==false&&sameSeries(item.qbVersion,target)&&compare(item.qbVersion,target)<=0;}).sort(function(a,b){return compare(b.qbVersion,a.qbVersion);}),base=candidates[0]||null;if(!base)return null;if(api&&api!=='0'&&base.webApiVersion&&compare(api,base.webApiVersion)<0)return null;return base;}
  function resolveRelease(){var qb=client&&client.qbVersion||'0',api=client&&client.webApiVersion||'0',hit=exactRelease(qb),mode='FALLBACK',base=null;if(hit){base=hit;mode=rawVersion(qb)===normalizedVersion(hit.qbVersion)?'EXACT':'EQUIVALENT';}else{base=inheritedRelease(qb,api);if(base)mode='INHERITED';}if(!base){current={qbVersion:normalizedVersion(qb),detectedQbVersion:rawVersion(qb),webApiVersion:normalizedVersion(api),sourceSha:'',resolvedFrom:'',resolutionMode:'FALLBACK',inherited:false,equivalent:false,fallback:true,officialWeiGSupport:false};return current;}current={qbVersion:normalizedVersion(base.qbVersion),detectedQbVersion:rawVersion(qb),webApiVersion:normalizedVersion(base.webApiVersion||api),sourceSha:String(base.sourceSha||''),resolvedFrom:normalizedVersion(base.qbVersion),resolutionMode:mode,inherited:mode==='INHERITED',equivalent:mode==='EQUIVALENT',fallback:false,officialWeiGSupport:base.officialWeiGSupport!==false};return current;}
  function releaseIdentity(){if(!current)return null;return{qbVersion:String(current.qbVersion||''),detectedQbVersion:String(current.detectedQbVersion||''),webApiVersion:String(current.webApiVersion||''),sourceSha:String(current.sourceSha||''),resolvedFrom:String(current.resolvedFrom||''),fallback:current.fallback===true,officialWeiGSupport:current.officialWeiGSupport!==false,resolutionMode:String(current.resolutionMode||''),inherited:current.inherited===true,equivalent:current.equivalent===true,certified:isCertified()};}
  function changeValue(changes,qb){if(!Array.isArray(changes)||!changes.length)return null;var hit=null;for(var i=0;i<changes.length;i++){if(compare(changes[i].from,qb)<=0)hit=changes[i].value;else break;}return hit;}
  function clone(value){if(Array.isArray(value))return value.map(clone);if(value&&typeof value==='object'){var out={};Object.keys(value).forEach(function(key){out[key]=clone(value[key]);});return out;}return value;}
  function applyMerge(target,patch){if(!patch||typeof patch!=='object'||Array.isArray(patch))return clone(patch);var out=target&&typeof target==='object'&&!Array.isArray(target)?clone(target):{};Object.keys(patch).forEach(function(key){var value=patch[key];if(value===null)delete out[key];else out[key]=applyMerge(out[key],value);});return out;}
  function resolveMerge(spec,qb){var value=null,changes=spec&&spec.changes;if(!Array.isArray(changes))return null;for(var i=0;i<changes.length;i++){var change=changes[i];if(compare(change.from,qb)>0)break;if(Object.prototype.hasOwnProperty.call(change,'value'))value=clone(change.value);else if(Object.prototype.hasOwnProperty.call(change,'patch'))value=applyMerge(value,change.patch);}return value;}
  function resolveKeyed(spec,qb){var order=changeValue(spec&&spec.order,qb);if(!Array.isArray(order)||!spec.items)return[];return order.map(function(key){return changeValue(spec.items[key],qb);}).filter(function(item){return item!=null;}).map(clone);}
  function sourceFact(name){if(!current||current.fallback||!data||!data.sourceFacts)return null;var spec=data.sourceFacts[name];if(Array.isArray(spec))return clone(changeValue(spec,current.qbVersion));if(spec&&spec.mode==='merge')return resolveMerge(spec,current.qbVersion);if(spec&&spec.mode==='keyed')return resolveKeyed(spec,current.qbVersion);return null;}
  function webuiLocales(){var items=sourceFact('webuiLocales');return Array.isArray(items)?items.map(function(item){return item&&typeof item==='object'?Object.assign({},item):item;}):[];}
  function hasExactSourceFacts(){return !!(current&&current.fallback!==true);}
  function canonicalFilter(name){name=String(name||'all');if(name==='paused')return'stopped';if(name==='resumed')return'running';return name;}
  function rawTorrentFilters(){var list=sourceFact('torrentFilters');return Array.isArray(list)?Array.from(new Set(list.map(String))):[];}
  function torrentFilters(){return Array.from(new Set(rawTorrentFilters().map(canonicalFilter)));}
  function upstreamTorrentFilter(name){if(!current)return undefined;name=String(name||'all');var list=rawTorrentFilters();if(list.indexOf(name)>=0)return name;if(name==='stopped'&&list.indexOf('paused')>=0)return'paused';if(name==='running'&&list.indexOf('resumed')>=0)return'resumed';return null;}
  function supportsTorrentFilter(name){return upstreamTorrentFilter(name)!==null;}
  function factList(name){var list=sourceFact(name);return Array.isArray(list)?list.map(String):[];}
  function hasTorrentInfoParameter(name){return factList('torrentInfoParameters').indexOf(String(name||''))>=0;}
  function hasTorrentInfoField(name){return factList('torrentInfoFields').indexOf(String(name||''))>=0;}
  function torrentStates(){return factList('torrentStates');}
  function torrentFieldFacts(){if(!hasExactSourceFacts()||current.officialWeiGSupport===false)return null;var fields=factList('torrentInfoFields'),columns=sourceFact('torrentTableColumns');return{fallback:false,officialWeiGSupport:true,torrentInfoFields:fields,torrentTableColumns:Array.isArray(columns)?columns.map(function(column){return column&&typeof column==='object'?Object.assign({},column):column;}):[]};}
  function torrentDetailUi(){if(!isCertified())return null;var ui=sourceFact('torrentDetailUi');return ui&&typeof ui==='object'&&!Array.isArray(ui)?ui:null;}
  function detailFields(surface){var map={properties:'torrentPropertiesFields',trackers:'torrentTrackerFields',files:'torrentFileFields',webseeds:'torrentWebSeedFields'},key=map[String(surface||'')];return key?factList(key):[];}
  function hasTorrentDetailField(surface,name){return detailFields(surface).indexOf(String(name||''))>=0;}
  function sourceActionValue(action){if(!hasExactSourceFacts()||!data||!data.sourceActions)return null;return changeValue(data.sourceActions[String(action||'')],current.qbVersion);}
  function hasAction(action){return !!(action&&sourceActionValue(action));}
  function actionDescriptor(action){var key=String(action||''),spec=sourceActionValue(key);if(!spec)return null;var name=(key.split(':')[1]||'').replace(/Action$/,'');return{sourceAction:key,endpoint:name,parameters:Array.isArray(spec.parameters)?spec.parameters.map(String):[],required:Array.isArray(spec.required)?spec.required.map(String):[],optional:Array.isArray(spec.optional)?spec.optional.map(String):[],parameterOptions:spec.parameterOptions&&typeof spec.parameterOptions==='object'?Object.assign({},spec.parameterOptions):{}};}
  function hasWriteProvenance(){return isCertified();}
  function supportsWriteAction(action){return !!(action&&hasWriteProvenance()&&hasAction(action));}
  function isCertified(){return !!(current&&!current.fallback&&current.officialWeiGSupport!==false&&(current.resolutionMode==='EXACT'||current.resolutionMode==='EQUIVALENT'));}
  function sourceActionDescriptor(action){if(!data||!current)return undefined;if(current.fallback===true)return null;return actionDescriptor(String(action||''));}
  function actionChoices(kind){var map={start:[['torrentscontroller.h:startAction','start'],['torrentscontroller.h:resumeAction','resume']],stop:[['torrentscontroller.h:stopAction','stop'],['torrentscontroller.h:pauseAction','pause']],delete:[['torrentscontroller.h:deleteAction','delete']],force:[['torrentscontroller.h:setForceStartAction','setForceStart']],recheck:[['torrentscontroller.h:recheckAction','recheck']],reannounce:[['torrentscontroller.h:reannounceAction','reannounce']],sequential:[['torrentscontroller.h:toggleSequentialDownloadAction','toggleSequentialDownload']],firstlast:[['torrentscontroller.h:toggleFirstLastPiecePrioAction','toggleFirstLastPiecePrio']],autotmm:[['torrentscontroller.h:setAutoManagementAction','setAutoManagement']],superseeding:[['torrentscontroller.h:setSuperSeedingAction','setSuperSeeding']],top:[['torrentscontroller.h:topPrioAction','topPrio']],increase:[['torrentscontroller.h:increasePrioAction','increasePrio']],decrease:[['torrentscontroller.h:decreasePrioAction','decreasePrio']],bottom:[['torrentscontroller.h:bottomPrioAction','bottomPrio']],export:[['torrentscontroller.h:exportAction','export']],rename:[['torrentscontroller.h:renameAction','rename']],location:[['torrentscontroller.h:setLocationAction','setLocation']],category:[['torrentscontroller.h:setCategoryAction','setCategory']],tags:[['torrentscontroller.h:addTagsAction','addTags']],dllimit:[['torrentscontroller.h:setDownloadLimitAction','setDownloadLimit']],uplimit:[['torrentscontroller.h:setUploadLimitAction','setUploadLimit']],addTrackers:[['torrentscontroller.h:addTrackersAction','addTrackers']],removeTrackers:[['torrentscontroller.h:removeTrackersAction','removeTrackers']],editTracker:[['torrentscontroller.h:editTrackerAction','editTracker']]};return map[String(kind||'')]||[];}
  function resolveTorrentActionDescriptor(kind){kind=String(kind||'');if(!current||!hasWriteProvenance())return null;var choices=actionChoices(kind);for(var i=0;i<choices.length;i++){var desc=actionDescriptor(choices[i][0]);if(desc){desc.endpoint=choices[i][1];desc.kind=kind;return desc;}}return null;}
  function supportsTorrentAction(kind){return !!resolveTorrentActionDescriptor(kind);}
  function sourceTruth(f){var upstream=f&&f.upstream;if(f&&f.writeRequired===true&&!hasWriteProvenance())return false;if(!upstream||!hasExactSourceFacts())return null;if(Array.isArray(upstream.allActions))return upstream.allActions.length>0&&upstream.allActions.every(function(action){return hasAction(String(action));});if(Array.isArray(upstream.anyActions))return upstream.anyActions.some(function(action){return hasAction(String(action));});if(upstream.action)return hasAction(String(upstream.action));if(upstream.actionParameter){var spec=upstream.actionParameter||{},desc=actionDescriptor(String(spec.action||''));return !!(desc&&Array.isArray(desc.parameters)&&desc.parameters.indexOf(String(spec.parameter||''))>=0);}if(upstream.torrentFilter)return supportsTorrentFilter(upstream.torrentFilter);if(upstream.torrentInfoParameter)return hasTorrentInfoParameter(upstream.torrentInfoParameter);if(upstream.torrentInfoField)return hasTorrentInfoField(upstream.torrentInfoField);return null;}
  function supports(id){var f=feature(id);if(!f)return false;var truth=sourceTruth(f);if(truth!==null)return !!truth;if(f.sourceRequired===true)return false;return matchRule(f.rule,env());}
  function formatVersion(v){var raw=String(v==null?'0':v).replace(/^v/i,'').split(/[+-]/)[0],p=raw.split('.');while(p.length<3)p.push('0');return p.join('.');}
  function formatLower(v){return formatVersion(v)+'+';}
  function rangeLabel(range){range=range||{};if(range.eq!=null)return formatVersion(range.eq);if(range.gte!=null&&range.lt!=null)return '≥'+formatVersion(range.gte)+' <'+formatVersion(range.lt);if(range.gte!=null&&range.lte!=null)return formatVersion(range.gte)+'–'+formatVersion(range.lte);if(range.gte!=null)return formatLower(range.gte);if(range.gt!=null)return '>'+formatVersion(range.gt);if(range.lt!=null)return '<'+formatVersion(range.lt);if(range.lte!=null)return '≤'+formatVersion(range.lte);return'';}
  function lowerFromRange(range){range=range||{};if(range.gte!=null)return formatVersion(range.gte);if(range.gt!=null)return formatVersion(range.gt);if(range.eq!=null)return formatVersion(range.eq);return'';}
  function milestoneForWebApi(range){if(!data||!Array.isArray(data.webApiMilestones)||!range)return null;for(var i=0;i<data.webApiMilestones.length;i++){var m=data.webApiMilestones[i];if(matchRange(m.webApi,range))return m;}return null;}
  function requirementFacts(id){var f=feature(id),rule=f&&f.rule||{},p=f&&f.presentation||{},req=p.requirements||{},webApi=req.webApi||lowerFromRange(rule.webApi),qb=req.qb||lowerFromRange(rule.qb),knownQb=req.knownQb||'';if(!knownQb&&webApi){var m=milestoneForWebApi({gte:webApi});if(m)knownQb=m.qb;}if(!knownQb&&qb)knownQb=qb;return{qb:qb||'',webApi:webApi||'',knownQb:knownQb||''};}
  function badgeFor(id){var f=feature(id);if(!f)return'';var p=f.presentation||{},facts=requirementFacts(id),rule=f.rule||{};if(p.badge&&p.badge!=='auto')return String(p.badge);if(facts.qb)return formatLower(facts.qb);if(facts.knownQb)return formatLower(facts.knownQb);if(rule.qb)return rangeLabel(rule.qb);if(rule.webApi){var m=milestoneForWebApi(rule.webApi);return m?formatLower(m.qb):local(p.unknownBadge,zh()?'需升级':'Upgrade');}return local(p.unknownBadge,zh()?'需升级':'Upgrade');}
  function ruleLines(id){var facts=requirementFacts(id),qb=facts.qb?formatLower(facts.qb):'—',webApi=facts.webApi?formatLower(facts.webApi):'—';return[(zh()?'qBittorrent 要求：':'qBittorrent requirement: ')+qb,(zh()?'WebAPI 要求：':'WebAPI requirement: ')+webApi];}
  function affordanceLayout(node){return node&&node.querySelector&&node.querySelector('.ui-select__trigger')?'control':'inline';}
  function clearAffordance(node){if(!node)return;delete node.dataset.capabilityLayout;node.classList.remove('capability-affordance','capability-affordance--control','capability-affordance--inline');}
  function markAffordance(node){var layout=affordanceLayout(node);node.dataset.capabilityLayout=layout;node.classList.add('capability-affordance');node.classList.toggle('capability-affordance--control',layout==='control');node.classList.toggle('capability-affordance--inline',layout==='inline');return layout;}
  function clearBadge(node){if(!node)return;var badges=[];if(node.querySelectorAll)badges=Array.from(node.querySelectorAll('.capability-badge'));badges.forEach(function(child){child.remove();});}
  function badgeHost(node,layout){if(layout==='control'&&node&&node.querySelector){var trigger=node.querySelector('.ui-select__trigger');if(trigger)return trigger;}return node;}
  function ensureDialog(){if(dialog&&dialog.isConnected)return dialog;var d=document.createElement('dialog');d.id='capability-dialog';d.className='dialog surface surface--modal capability-dialog';d.innerHTML='<div class="dialog__head"><div><div class="eyebrow">QBITTORRENT</div><h2 class="capability-dialog__title"></h2></div><button type="button" class="icon-btn capability-dialog__close">×</button></div><div class="dialog__body capability-dialog__body"><p class="capability-dialog__reason"></p><div class="capability-dialog__requirements"></div><div class="capability-dialog__current"></div><p class="text-description capability-dialog__advice"></p></div><div class="dialog__actions"><button type="button" class="btn btn--primary capability-dialog__done"></button></div>';d.querySelector('.capability-dialog__close').onclick=d.querySelector('.capability-dialog__done').onclick=function(){d.close();};document.body.appendChild(d);dialog=d;return d;}
  function open(id){var f=feature(id);if(!f)return null;var d=ensureDialog(),currentEnv=env();d.dataset.dialogCapability=id;d.querySelector('.capability-dialog__title').textContent=local(f.copy&&f.copy.title,zh()?'功能不可用':'Feature unavailable');d.querySelector('.capability-dialog__reason').textContent=local(f.copy&&f.copy.reason,zh()?'当前版本不支持此功能。':'This feature is not supported by the current version.');var req=d.querySelector('.capability-dialog__requirements');req.textContent='';ruleLines(id).forEach(function(line){var row=document.createElement('div');row.className='capability-dialog__row';row.textContent=line;req.appendChild(row);});var cur=d.querySelector('.capability-dialog__current');cur.textContent='';[(zh()?'当前 qBittorrent：':'Current qBittorrent: ')+(currentEnv.qb||'—'),(zh()?'当前 WebAPI：':'Current WebAPI: ')+(currentEnv.webApi||'—')].forEach(function(line){var row=document.createElement('div');row.className='capability-dialog__row';row.textContent=line;cur.appendChild(row);});d.querySelector('.capability-dialog__advice').textContent=zh()?'该功能由当前 qBittorrent / WebAPI 能力决定。升级前请备份 qBittorrent 配置与任务数据。':'Availability is determined by the detected qBittorrent / WebAPI capability. Back up qBittorrent configuration and torrent data before upgrading.';d.querySelector('.capability-dialog__done').textContent=zh()?'知道了':'OK';if(!d.open)d.showModal();return d;}
  function decorate(node,id){if(!node)return;id=id||node.dataset.capability||node.dataset.capabilityId;if(!id)return;node.dataset.capabilityId=id;var f=feature(id);if(!f){node.hidden=true;return;}var supported=supports(id),policy=(f.presentation&&f.presentation.unsupported)||'disable';node.classList.toggle('is-capability-disabled',!supported&&policy==='disable');node.setAttribute('aria-disabled',!supported&&policy==='disable'?'true':'false');delete node.dataset.tooltip;if(!supported&&policy==='hide'){clearBadge(node);clearAffordance(node);node.hidden=true;return;}node.hidden=false;clearBadge(node);if(supported){clearAffordance(node);return;}var layout=markAffordance(node);var badge=document.createElement('span');badge.className='capability-badge';badge.textContent=badgeFor(id);badge.setAttribute('aria-hidden','true');badgeHost(node,layout).appendChild(badge);}
  function syncClientCapabilities(){if(!client||!data||!data.features)return;var caps=client.capabilities=client.capabilities||{},major=parts(client.qbVersion)[0]||0;caps.legacy4=major===4;caps.modern5=major>=5;caps.certified=isCertified();Object.keys(data.features).forEach(function(id){caps[id]=supports(id);});caps.privateFlag=!!caps.privateFilter;}
  function decorateMatching(node){if(!data||!client||!node)return node;Object.keys(data.features||{}).forEach(function(id){var f=data.features[id]||{},selectors=Array.isArray(f.selectors)?f.selectors:[];selectors.forEach(function(selector){try{if(node.matches&&node.matches(selector))decorate(node,id);if(node.querySelectorAll)node.querySelectorAll(selector).forEach(function(hit){decorate(hit,id);});}catch(_e){}});});if(node.matches&&node.matches('[data-capability]'))decorate(node,node.dataset.capability);if(node.querySelectorAll)node.querySelectorAll('[data-capability]').forEach(function(hit){decorate(hit,hit.dataset.capability);});return node;}
  function sync(){if(!data||!client)return;decorateMatching(document);}
  function bind(nextClient){client=nextClient||client;return load().then(function(){resolveRelease();return Promise.all([ensure('torrent'),ensure('actions')]);}).then(function(){var release=releaseIdentity();if(W.SettingsSchema&&typeof W.SettingsSchema.bindRelease==='function')W.SettingsSchema.bindRelease(release);syncClientCapabilities();sync();try{global.dispatchEvent(new CustomEvent('weigg:capabilities-ready',{detail:{profile:release,release:release}}));}catch(_e){}return api;});}
  function state(id){var f=feature(id);return{id:id,supported:supports(id),badge:badgeFor(id),feature:f,requirements:requirementFacts(id),environment:env()};}
  function intercept(event){var node=event.target&&event.target.closest&&event.target.closest('[data-capability-id]');if(!node||node.getAttribute('aria-disabled')!=='true')return;event.preventDefault();event.stopImmediatePropagation();open(node.dataset.capabilityId);}
  function interceptKey(event){if(['Enter',' ','ArrowDown','ArrowUp'].indexOf(event.key)<0)return;intercept(event);}
  document.addEventListener('click',intercept,true);document.addEventListener('keydown',interceptKey,true);global.addEventListener('weigg:library-state',function(){requestAnimationFrame(sync);});global.addEventListener('weigg:languagechange',function(){requestAnimationFrame(sync);if(dialog&&dialog.open&&dialog.dataset.dialogCapability)open(dialog.dataset.dialogCapability);});
  var api={load:load,ready:load,ensure:ensure,domain:domain,bind:bind,supports:supports,state:state,open:open,sync:sync,decorate:decorate,decorateMatching:decorateMatching,compareVersions:compare,matchRange:matchRange,matchRule:matchRule,badgeFor:badgeFor,formatVersion:formatVersion,requirementFacts:requirementFacts,ruleLines:ruleLines,releaseIdentity:releaseIdentity,webuiLocales:webuiLocales,hasExactSourceFacts:hasExactSourceFacts,torrentFilters:torrentFilters,supportsTorrentFilter:supportsTorrentFilter,hasTorrentInfoParameter:hasTorrentInfoParameter,hasTorrentInfoField:hasTorrentInfoField,torrentStates:torrentStates,torrentFieldFacts:torrentFieldFacts,torrentDetailUi:torrentDetailUi,hasTorrentDetailField:hasTorrentDetailField,actionDescriptor:actionDescriptor,hasWriteProvenance:hasWriteProvenance,hasAction:hasAction,supportsWriteAction:supportsWriteAction,isCertified:isCertified,sourceActionDescriptor:sourceActionDescriptor,upstreamTorrentFilter:upstreamTorrentFilter,resolveTorrentActionDescriptor:resolveTorrentActionDescriptor,supportsTorrentAction:supportsTorrentAction};
  W.CapabilityRegistry=api;W.CapabilityDialog={open:function(value){return typeof value==='string'?open(value):null;},close:function(){if(dialog&&dialog.open)dialog.close();}};
})(window);
