(function(global){
  'use strict';
  var W=global.WeiG,U=W.util,T=W.t||function(k){return k;};
  var states={downloading:['state.downloading','info'],metaDL:['state.metaDL','info'],forcedDL:['state.forcedDL','info'],allocating:['state.allocating','info'],checkingDL:['state.checkingDL','warning'],checkingUP:['state.checkingUP','warning'],checkingResumeData:['state.checkingResumeData','warning'],moving:['state.moving','warning'],uploading:['state.uploading','success'],stalledUP:['state.stalledUP','warning'],forcedUP:['state.forcedUP','success'],queuedUP:['state.queuedUP','muted'],pausedDL:['state.pausedDL','muted'],pausedUP:['state.pausedUP','muted'],stoppedDL:['state.stoppedDL','muted'],stoppedUP:['state.stoppedUP','muted'],queuedDL:['state.queuedDL','muted'],stalledDL:['state.stalledDL','warning'],error:['state.error','danger'],missingFiles:['state.missingFiles','danger'],unknown:['state.unknown','muted']};
  W.Components={};
  W.Components.state=function(code){var s=states[code]||['state.unknown','muted'];return [T(s[0]),s[1]];};
  function statusPill(code){var s=W.Components.state(code),p=document.createElement('span');p.className='status-pill';p.dataset.tone=s[1];p.textContent=s[0];return p;}
  function textCell(text,cls){var e=document.createElement('span');e.className='cell '+(cls||'');e.textContent=text;return e;}
  function progressCell(t){var pc=document.createElement('div');pc.className='progress-cell';var track=document.createElement('div');track.className='progress-track';var fill=document.createElement('div');fill.className='progress-fill';fill.style.width=U.clamp(U.percent(t.progress),0,100)+'%';track.appendChild(fill);pc.append(track,textCell(U.percent(t.progress)+'%','progress-number'));return pc;}
  function nameCell(t,selected,handlers){var name=document.createElement('div');name.className='torrent-name-cell';var check=document.createElement('input');check.type='checkbox';check.className='torrent-select';check.checked=selected;check.setAttribute('aria-label',T('torrent.name')+': '+U.escapeText(t.name));check.addEventListener('change',function(){handlers.select(t.hash,check.checked);});var title=document.createElement('button');title.type='button';title.className='torrent-title';title.textContent=U.escapeText(t.name)||'Untitled torrent';title.title=U.escapeText(t.name);title.addEventListener('click',function(){handlers.open(t.hash);});var more=document.createElement('button');more.type='button';more.className='row-more';more.textContent='›';more.setAttribute('aria-label',T('torrent.details'));more.addEventListener('click',function(){handlers.open(t.hash);});name.append(check,title,more);return name;}
  W.Components.torrentRow=function(t,selected,handlers,columns,template){var row=document.createElement('article');row.className='torrent-row'+(selected?' is-selected':'');row.role='listitem';row.dataset.hash=t.hash;row.style.gridTemplateColumns=template;columns.forEach(function(c){var el;if(c.key==='name')el=nameCell(t,selected,handlers);else if(c.key==='size')el=textCell(U.formatBytes(t.size),'size-cell');else if(c.key==='progress')el=progressCell(t);else if(c.key==='dlspeed')el=textCell(U.formatSpeed(t.dlspeed),'speed-dl');else if(c.key==='upspeed')el=textCell(U.formatSpeed(t.upspeed),'speed-up');else if(c.key==='eta')el=textCell(U.formatEta(t.eta),'eta-cell');else if(c.key==='state'){el=document.createElement('div');el.className='status-cell';el.appendChild(statusPill(t.state));}else if(c.key==='ratio')el=textCell(U.formatRatio(t.ratio),'ratio-cell');else if(c.key==='tracker'){el=textCell(U.trackerLabel(t.tracker),'tracker-cell');el.title=U.normalizeTracker(t.tracker);}else if(c.key==='category')el=textCell(t.category||'—','category-cell');else el=textCell('—');row.appendChild(el);});return row;};
  W.Components.mobileTorrentCard=function(t,selected,handlers,fields){var row=document.createElement('article');row.className='torrent-mobile-card'+(selected?' is-selected':'');row.dataset.hash=t.hash;var top=document.createElement('div');top.className='mobile-card-top';var check=document.createElement('input');check.type='checkbox';check.className='torrent-select';check.checked=selected;check.setAttribute('aria-label',T('torrent.name')+': '+U.escapeText(t.name));check.addEventListener('change',function(){handlers.select(t.hash,check.checked);});var title=document.createElement('button');title.className='mobile-card-title';title.type='button';title.textContent=t.name||'Untitled torrent';title.addEventListener('click',function(){handlers.open(t.hash);});var more=document.createElement('button');more.className='icon-btn mobile-more';more.type='button';more.textContent='⋯';more.setAttribute('aria-label',T('app.more'));more.addEventListener('click',function(){handlers.menu(t.hash);});top.append(check,title,more);row.appendChild(top);if(fields.indexOf('status')>=0||fields.indexOf('progress')>=0){var line=document.createElement('div');line.className='mobile-card-status';if(fields.indexOf('status')>=0)line.appendChild(statusPill(t.state));if(fields.indexOf('progress')>=0){var p=document.createElement('strong');p.textContent=U.percent(t.progress)+'%';line.appendChild(p);}row.appendChild(line);}if(fields.indexOf('progress')>=0)row.appendChild(progressCell(t));var meta=document.createElement('div');meta.className='mobile-card-meta';if(fields.indexOf('dl')>=0)meta.appendChild(textCell('↓ '+U.formatSpeed(t.dlspeed),'speed-dl'));if(fields.indexOf('up')>=0)meta.appendChild(textCell('↑ '+U.formatSpeed(t.upspeed),'speed-up'));if(fields.indexOf('eta')>=0)meta.appendChild(textCell('ETA '+U.formatEta(t.eta)));if(fields.indexOf('size')>=0)meta.appendChild(textCell(U.formatBytes(t.size)));if(fields.indexOf('ratio')>=0)meta.appendChild(textCell('Ratio '+U.formatRatio(t.ratio)));if(fields.indexOf('tracker')>=0)meta.appendChild(textCell(U.trackerLabel(t.tracker)));if(fields.indexOf('category')>=0)meta.appendChild(textCell(t.category||'—'));row.appendChild(meta);return row;};
  W.Components.kv=function(label,value){var el=document.createElement('div');el.className='kv';var a=document.createElement('span'),b=document.createElement('strong');a.textContent=label;b.textContent=value==null?'—':String(value);el.append(a,b);return el;};
  W.Components.sectionTitle=function(text,subtitle){var w=document.createElement('div');w.className='section-heading';var h=document.createElement('h2');h.textContent=text;w.appendChild(h);if(subtitle){var p=document.createElement('p');p.className='text-description';p.textContent=subtitle;w.appendChild(p);}return w;};
  W.Components.preferenceField=function(key,value,onChange,label){var info=W.SettingsSchema?W.SettingsSchema.describe(key):{title:label||key,description:'qBittorrent preference.',kind:'auto',known:false};var row=document.createElement('label');row.className='settings-row setting-card';row.dataset.settingKey=key;row.dataset.settingSearch=(info.title+' '+info.description+' '+key).toLowerCase();var copy=document.createElement('span');copy.className='settings-row__copy';var title=document.createElement('strong');title.textContent=info.title;title.title=info.title;var meta=document.createElement('small');meta.className='text-description';meta.textContent=info.description;copy.append(title,meta);var input;if(typeof value==='boolean'||info.kind==='boolean'){var switchWrap=document.createElement('span');switchWrap.className='switch-control';input=document.createElement('input');input.type='checkbox';input.checked=!!value;input.className='switch-input';var track=document.createElement('span');track.className='switch-track';var thumb=document.createElement('span');thumb.className='switch-thumb';track.appendChild(thumb);switchWrap.append(input,track);input.addEventListener('change',function(){onChange(key,input.checked);});row.append(copy,switchWrap);return row;}input=document.createElement('input');input.type=(typeof value==='number'||info.kind==='number')?'number':'text';input.value=value==null?'':String(value);input.className='field-input';input.autocomplete='off';input.addEventListener('change',function(){onChange(key,U.parseScalar(input.value));});row.append(copy,input);return row;};
  W.Components.readonlySettingField=function(key,titleText,description,value){var row=document.createElement('div');row.className='settings-row setting-card';row.dataset.settingKey=key;row.dataset.settingReadonly='true';row.dataset.settingSearch=(String(titleText||'')+' '+String(description||'')+' '+String(value||'')+' '+key).toLowerCase();var copy=document.createElement('span');copy.className='settings-row__copy';var title=document.createElement('strong');title.textContent=titleText||key;title.title=title.textContent;var meta=document.createElement('small');meta.className='text-description';meta.textContent=description||'';copy.append(title,meta);var input=document.createElement('input');input.type='text';input.className='field-input';input.value=value==null?'—':String(value);input.readOnly=true;input.setAttribute('aria-readonly','true');input.title=input.value;row.append(copy,input);return row;};

  /* UI-SELECT-001: one custom listbox primitive replaces OS-dependent popup styling. */
  var activeSelect=null;
  function normalizeOptions(items){return (items||[]).map(function(item){return typeof item==='string'?{value:item,label:item}:{value:String(item.value),label:String(item.label==null?item.value:item.label)};});}
  function closeSelect(wrapper,restoreFocus){if(!wrapper)return false;var menu=wrapper.querySelector('.ui-select__menu'),trigger=wrapper.querySelector('.ui-select__trigger');if(!menu||menu.hidden)return false;menu.hidden=true;wrapper.classList.remove('is-open');if(trigger)trigger.setAttribute('aria-expanded','false');if(activeSelect===wrapper)activeSelect=null;if(restoreFocus&&trigger)trigger.focus();return true;}
  W.Components.closeSelects=function(restoreFocus){return closeSelect(activeSelect,restoreFocus!==false);};
  W.Components.selectControl=function(opts){
    opts=opts||{};var items=normalizeOptions(opts.options),value=String(opts.value==null?'':opts.value),wrapper=document.createElement('div');wrapper.className='ui-select'+(opts.className?' '+opts.className:'');if(opts.id)wrapper.id=opts.id;wrapper.dataset.uiSelect='1';
    var trigger=document.createElement('button');trigger.type='button';trigger.className='ui-select__trigger';trigger.setAttribute('aria-haspopup','listbox');trigger.setAttribute('aria-expanded','false');if(opts.ariaLabel)trigger.setAttribute('aria-label',opts.ariaLabel);
    var copy=document.createElement('span');copy.className='ui-select__value';var chevron=document.createElement('span');chevron.className='ui-select__chevron';chevron.setAttribute('aria-hidden','true');chevron.textContent='▾';trigger.append(copy,chevron);
    var menu=document.createElement('div');menu.className='ui-select__menu surface surface--floating';menu.setAttribute('role','listbox');menu.hidden=true;var search=null,list=document.createElement('div');list.className='ui-select__options';menu.appendChild(list);wrapper.append(trigger,menu);
    var filteredItems=items.slice(),activeIndex=-1;
    function currentLabel(){var hit=items.find(function(x){return x.value===value;});return hit?hit.label:(opts.placeholder||value||'—');}
    function syncCopy(){copy.textContent=currentLabel();trigger.title=currentLabel();trigger.disabled=!!opts.disabled;}
    function renderOptions(query){var q=String(query||'').trim().toLocaleLowerCase();filteredItems=items.filter(function(x){return !q||x.label.toLocaleLowerCase().indexOf(q)>=0||x.value.toLocaleLowerCase().indexOf(q)>=0;});list.textContent='';filteredItems.forEach(function(item,index){var b=document.createElement('button');b.type='button';b.className='ui-select__option';b.setAttribute('role','option');b.dataset.value=item.value;b.setAttribute('aria-selected',item.value===value?'true':'false');b.classList.toggle('is-selected',item.value===value);b.textContent=item.label;b.addEventListener('click',function(){setValue(item.value,true);closeSelect(wrapper,true);});list.appendChild(b);if(item.value===value)activeIndex=index;});if(activeIndex<0&&filteredItems.length)activeIndex=0;}
    function ensureSearch(){if(!opts.searchable||search)return;if(items.length<(opts.searchThreshold||14))return;search=document.createElement('input');search.type='search';search.className='ui-select__search';search.autocomplete='off';search.placeholder=opts.searchPlaceholder||'Search…';search.setAttribute('aria-label',search.placeholder);search.addEventListener('input',function(){activeIndex=0;renderOptions(search.value);});search.addEventListener('keydown',onMenuKey);menu.insertBefore(search,list);}
    function focusIndex(index){var buttons=Array.from(list.querySelectorAll('.ui-select__option'));if(!buttons.length)return;activeIndex=Math.max(0,Math.min(buttons.length-1,index));buttons[activeIndex].focus();}
    function onMenuKey(e){if(e.key==='Escape'){e.preventDefault();closeSelect(wrapper,true);return;}if(e.key==='ArrowDown'){e.preventDefault();focusIndex(activeIndex+1);return;}if(e.key==='ArrowUp'){e.preventDefault();focusIndex(activeIndex-1);return;}if(e.key==='Home'){e.preventDefault();focusIndex(0);return;}if(e.key==='End'){e.preventDefault();focusIndex(filteredItems.length-1);}}
    function open(){if(trigger.disabled)return;if(activeSelect&&activeSelect!==wrapper)closeSelect(activeSelect,false);ensureSearch();renderOptions(search&&search.value);menu.hidden=false;wrapper.classList.add('is-open');trigger.setAttribute('aria-expanded','true');activeSelect=wrapper;requestAnimationFrame(function(){if(search)search.focus();else focusIndex(Math.max(0,activeIndex));});}
    function setValue(next,notify){value=String(next==null?'':next);syncCopy();renderOptions(search&&search.value);if(notify&&typeof opts.onChange==='function')opts.onChange(value);}
    trigger.addEventListener('click',function(e){e.stopPropagation();menu.hidden?open():closeSelect(wrapper,false);});
    trigger.addEventListener('keydown',function(e){if(e.key==='ArrowDown'||e.key==='ArrowUp'||e.key==='Enter'||e.key===' '){e.preventDefault();open();}else if(e.key==='Escape')closeSelect(wrapper,false);});
    menu.addEventListener('keydown',onMenuKey);menu.addEventListener('click',function(e){e.stopPropagation();});
    wrapper.setValue=function(next){setValue(next,false);};wrapper.getValue=function(){return value;};wrapper.setOptions=function(next){items=normalizeOptions(next);renderOptions(search&&search.value);syncCopy();};wrapper.setDisabled=function(disabled){opts.disabled=!!disabled;syncCopy();};
    renderOptions('');syncCopy();return wrapper;
  };
  W.Components.filterChip=function(label,active){var b=document.createElement('button');b.type='button';b.className='ui-chip';b.classList.toggle('is-active',!!active);b.setAttribute('aria-pressed',active?'true':'false');b.textContent=label;return b;};
  W.Components.checkControl=function(label,checked,onChange){var wrap=document.createElement('label');wrap.className='ui-check';var input=document.createElement('input');input.type='checkbox';input.checked=!!checked;var mark=document.createElement('span');mark.className='ui-check__mark';mark.setAttribute('aria-hidden','true');var copy=document.createElement('span');copy.className='ui-check__label';copy.textContent=label;wrap.append(input,mark,copy);input.addEventListener('change',function(){if(onChange)onChange(input.checked);});wrap.input=input;return wrap;};
  W.Components.upgradeNativeSelect=function(select){
    if(!select||select.dataset.uiSelectUpgraded==='1'||select.closest('.ui-select'))return null;select.dataset.uiSelectUpgraded='1';var options=function(){return Array.from(select.options||[]).map(function(o){return {value:o.value,label:o.textContent};});};var custom=W.Components.selectControl({value:select.value,options:options(),ariaLabel:select.getAttribute('aria-label')||select.name||select.id||'Select',searchable:(select.options||[]).length>18,onChange:function(next){select.value=next;select.dispatchEvent(new Event('input',{bubbles:true}));select.dispatchEvent(new Event('change',{bubbles:true}));}});custom.classList.add('ui-select--native');select.classList.add('ui-native-select');select.tabIndex=-1;select.setAttribute('aria-hidden','true');select.insertAdjacentElement('afterend',custom);select.addEventListener('change',function(){custom.setValue(select.value);});new MutationObserver(function(){custom.setOptions(options());custom.setValue(select.value);custom.setDisabled(select.disabled);}).observe(select,{childList:true,subtree:true,attributes:true,attributeFilter:['disabled']});custom.setDisabled(select.disabled);return custom;
  };
  W.Components.upgradeNativeSelects=function(root){Array.from((root||document).querySelectorAll('select:not([data-ui-select-upgraded="1"])')).forEach(W.Components.upgradeNativeSelect);};
  document.addEventListener('click',function(){W.Components.closeSelects(false);});

  /* TIME-001: display timezone is a browser concern, never a qB preference. */
  var TZ_KEY='weigg.timeZone';
  var COMMON_ZONES=['UTC','Asia/Shanghai','Asia/Singapore','Asia/Tokyo','Europe/London','Europe/Berlin','America/New_York','America/Los_Angeles','Australia/Sydney'];
  W.Time={
    getZone:function(){return localStorage.getItem(TZ_KEY)||'system';},
    setZone:function(zone){zone=String(zone||'system');localStorage.setItem(TZ_KEY,zone);global.dispatchEvent(new CustomEvent('weigg:timezonechange',{detail:{timeZone:zone}}));},
    zones:function(){var zones=[];try{if(Intl.supportedValuesOf)zones=Intl.supportedValuesOf('timeZone');}catch(_e){}var seen=new Set(),out=[{value:'system',label:'System / Browser'}];COMMON_ZONES.concat(zones).forEach(function(zone){if(seen.has(zone))return;seen.add(zone);out.push({value:zone,label:zone});});return out;},
    format:function(value,options){var n=Number(value),ms=n>=1e12?n:n*1000;if(!Number.isFinite(ms)||ms<=0)return '';var locale=W.I18n&&W.I18n.getLocale?W.I18n.getLocale():undefined,zone=this.getZone(),fmt=Object.assign({year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false},options||{});if(zone!=='system')fmt.timeZone=zone;try{return new Intl.DateTimeFormat(locale,fmt).format(new Date(ms));}catch(_e){delete fmt.timeZone;return new Intl.DateTimeFormat(locale,fmt).format(new Date(ms));}}
  };

  /* BUILD-001: HTML carries one deployment Git SHA. Every lazy asset reuses it. */
  var buildToken=null;
  function currentBuildToken(){if(buildToken)return buildToken;var meta=document.querySelector('meta[name="weigg-build-sha"]'),raw=String(meta&&meta.content||'').trim();buildToken=/^[0-9a-f]{7,40}$/i.test(raw)?raw:'dev';return buildToken;}
  function buildAssetUrl(src){var sep=src.indexOf('?')>=0?'&':'?';return src+sep+'v='+encodeURIComponent(currentBuildToken());}
  W.buildAssetUrl=buildAssetUrl;

  /* Stable filenames keep old Alternate-WebUI roots compatible. Asset identity is
   * the deployment Git SHA, never a hand-maintained product-version query. */
  (function loadRuntimeLayers(){
    function css(href,key){if(document.querySelector('link[data-weigg-layer="'+key+'"]'))return;var link=document.createElement('link');link.rel='stylesheet';link.href=buildAssetUrl(href);link.dataset.weiggLayer=key;document.head.appendChild(link);}
    function asyncScript(src,key){if(document.querySelector('script[data-weigg-layer="'+key+'"]'))return;var script=document.createElement('script');script.src=buildAssetUrl(src);script.async=true;script.dataset.weiggLayer=key;document.head.appendChild(script);}
    function loadV030(){if(document.querySelector('script[data-weigg-layer="runtime-030"]'))return;var script=document.createElement('script');script.src=buildAssetUrl('scripts/v030.js');script.async=false;script.dataset.weiggLayer='runtime-030';document.head.appendChild(script);}
    function loadV036(){if(document.querySelector('script[data-weigg-layer="runtime-036"]'))return;var script=document.createElement('script');script.src=buildAssetUrl('scripts/v036.js');script.async=false;script.dataset.weiggLayer='runtime-036';document.head.appendChild(script);}
    css('css/v022.css','spatial-022');
    css('css/v030.css','runtime-030');
    css('css/v036.css','runtime-036');
    asyncScript('scripts/spatial-v022.js','spatial-022');
    if(W.V030I18n)loadV030();
    else if(!document.querySelector('script[data-weigg-layer="i18n-030"]')){var i18=document.createElement('script');i18.src=buildAssetUrl('scripts/i18n-v030.js');i18.async=false;i18.dataset.weiggLayer='i18n-030';i18.onload=loadV030;document.head.appendChild(i18);}
    else{var existing=document.querySelector('script[data-weigg-layer="i18n-030"]');existing.addEventListener('load',loadV030,{once:true});}
    if(W.V036I18n)loadV036();
    else if(!document.querySelector('script[data-weigg-layer="i18n-036"]')){var i36=document.createElement('script');i36.src=buildAssetUrl('scripts/i18n-v036.js');i36.async=false;i36.dataset.weiggLayer='i18n-036';i36.onload=loadV036;document.head.appendChild(i36);}
    else{var existing36=document.querySelector('script[data-weigg-layer="i18n-036"]');existing36.addEventListener('load',loadV036,{once:true});}
  })();
})(window);
