(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{},U=W.util,T=W.t||function(k){return k;};
  var states={downloading:['state.downloading','info'],metaDL:['state.metaDL','info'],forcedDL:['state.forcedDL','info'],allocating:['state.allocating','info'],checkingDL:['state.checkingDL','warning'],checkingUP:['state.checkingUP','warning'],checkingResumeData:['state.checkingResumeData','warning'],moving:['state.moving','warning'],uploading:['state.uploading','success'],stalledUP:['state.stalledUP','warning'],forcedUP:['state.forcedUP','success'],queuedUP:['state.queuedUP','muted'],pausedDL:['state.pausedDL','muted'],pausedUP:['state.pausedUP','muted'],stoppedDL:['state.stoppedDL','muted'],stoppedUP:['state.stoppedUP','muted'],queuedDL:['state.queuedDL','muted'],stalledDL:['state.stalledDL','warning'],error:['state.error','danger'],missingFiles:['state.missingFiles','danger'],unknown:['state.unknown','muted']};
  var C=W.Components={};
  C.state=function(code){var s=states[code]||['state.unknown','muted'];return[T(s[0]),s[1]];};
  function textCell(text,cls){var e=document.createElement('span');e.className='cell '+(cls||'');e.textContent=text;return e;}
  function statusPill(code){var s=C.state(code),p=document.createElement('span');p.className='status-pill';p.dataset.tone=s[1];p.textContent=s[0];return p;}
  function progressCell(t){var p=document.createElement('div');p.className='progress-cell';var track=document.createElement('div');track.className='progress-track';var fill=document.createElement('div');fill.className='progress-fill';fill.style.width=U.clamp(U.percent(t.progress),0,100)+'%';track.appendChild(fill);p.append(track,textCell(U.percent(t.progress)+'%','progress-number'));return p;}
  function nameCell(t,selected,handlers){var name=document.createElement('div');name.className='torrent-name-cell';var check=document.createElement('input');check.type='checkbox';check.className='torrent-select';check.checked=selected;check.setAttribute('aria-label',T('torrent.name')+': '+U.escapeText(t.name));check.addEventListener('change',function(){handlers.select(t.hash,check.checked);});var title=document.createElement('button');title.type='button';title.className='torrent-title';title.textContent=U.escapeText(t.name)||'Untitled torrent';title.title=U.escapeText(t.name);title.addEventListener('click',function(){handlers.open(t.hash);});var more=document.createElement('button');more.type='button';more.className='row-more';more.textContent='›';more.setAttribute('aria-label',T('torrent.details'));more.addEventListener('click',function(){handlers.open(t.hash);});name.append(check,title,more);return name;}
  C.torrentRow=function(t,selected,handlers,columns,template){var row=document.createElement('article');row.className='torrent-row'+(selected?' is-selected':'');row.role='listitem';row.dataset.hash=t.hash;row.style.gridTemplateColumns=template;columns.forEach(function(c){var el;if(c.key==='name')el=nameCell(t,selected,handlers);else if(c.key==='size')el=textCell(U.formatBytes(t.size),'size-cell');else if(c.key==='progress')el=progressCell(t);else if(c.key==='dlspeed')el=textCell(U.formatSpeed(t.dlspeed),'speed-dl');else if(c.key==='upspeed')el=textCell(U.formatSpeed(t.upspeed),'speed-up');else if(c.key==='eta')el=textCell(U.formatEta(t.eta),'eta-cell');else if(c.key==='state'){el=document.createElement('div');el.className='status-cell';el.appendChild(statusPill(t.state));}else if(c.key==='ratio')el=textCell(U.formatRatio(t.ratio),'ratio-cell');else if(c.key==='tracker'){el=textCell(U.trackerLabel(t.tracker),'tracker-cell');el.title=U.normalizeTracker(t.tracker);}else if(c.key==='category')el=textCell(t.category||'—','category-cell');else el=textCell('—');row.appendChild(el);});return row;};
  C.mobileTorrentCard=function(t,selected,handlers,fields){var row=document.createElement('article');row.className='torrent-mobile-card'+(selected?' is-selected':'');row.dataset.hash=t.hash;var top=document.createElement('div');top.className='mobile-card-top';var check=document.createElement('input');check.type='checkbox';check.className='torrent-select';check.checked=selected;check.setAttribute('aria-label',T('torrent.name')+': '+U.escapeText(t.name));check.addEventListener('change',function(){handlers.select(t.hash,check.checked);});var title=document.createElement('button');title.className='mobile-card-title';title.type='button';title.textContent=t.name||'Untitled torrent';title.addEventListener('click',function(){handlers.open(t.hash);});var more=document.createElement('button');more.className='icon-btn mobile-more';more.type='button';more.textContent='⋯';more.setAttribute('aria-label',T('app.more'));more.addEventListener('click',function(){handlers.menu(t.hash);});top.append(check,title,more);row.appendChild(top);fields=fields||[];if(fields.indexOf('status')>=0||fields.indexOf('progress')>=0){var line=document.createElement('div');line.className='mobile-card-status';if(fields.indexOf('status')>=0)line.appendChild(statusPill(t.state));if(fields.indexOf('progress')>=0){var pc=document.createElement('strong');pc.textContent=U.percent(t.progress)+'%';line.appendChild(pc);}row.appendChild(line);}if(fields.indexOf('progress')>=0)row.appendChild(progressCell(t));var meta=document.createElement('div');meta.className='mobile-card-meta';if(fields.indexOf('dl')>=0)meta.appendChild(textCell('↓ '+U.formatSpeed(t.dlspeed),'speed-dl'));if(fields.indexOf('up')>=0)meta.appendChild(textCell('↑ '+U.formatSpeed(t.upspeed),'speed-up'));if(fields.indexOf('eta')>=0)meta.appendChild(textCell('ETA '+U.formatEta(t.eta)));if(fields.indexOf('size')>=0)meta.appendChild(textCell(U.formatBytes(t.size)));if(fields.indexOf('ratio')>=0)meta.appendChild(textCell('Ratio '+U.formatRatio(t.ratio)));if(fields.indexOf('tracker')>=0)meta.appendChild(textCell(U.trackerLabel(t.tracker)));if(fields.indexOf('category')>=0)meta.appendChild(textCell(t.category||'—'));row.appendChild(meta);return row;};
  C.kv=function(label,value){var el=document.createElement('div');el.className='kv';var a=document.createElement('span'),b=document.createElement('strong');a.textContent=label;b.textContent=value==null?'—':String(value);el.append(a,b);return el;};
  C.sectionTitle=function(text,subtitle){var w=document.createElement('div');w.className='section-heading';var h=document.createElement('h2');h.textContent=text;w.appendChild(h);if(subtitle){var p=document.createElement('p');p.className='text-description';p.textContent=subtitle;w.appendChild(p);}return w;};
  C.preferenceField=function(key,value,onChange,label){var info=W.SettingsSchema?W.SettingsSchema.describe(key):{title:label||key,description:'qBittorrent preference.',kind:'auto'};var row=document.createElement('label');row.className='settings-row setting-card';row.dataset.settingKey=key;row.dataset.settingSearch=(info.title+' '+info.description+' '+key).toLowerCase();var copy=document.createElement('span');copy.className='settings-row__copy';var title=document.createElement('strong');title.textContent=info.title;title.title=info.title;var meta=document.createElement('small');meta.className='text-description';meta.textContent=info.description;copy.append(title,meta);var input;if(typeof value==='boolean'||info.kind==='boolean'){var sw=document.createElement('span');sw.className='switch-control';input=document.createElement('input');input.type='checkbox';input.checked=!!value;input.className='switch-input';var track=document.createElement('span');track.className='switch-track';var thumb=document.createElement('span');thumb.className='switch-thumb';track.appendChild(thumb);sw.append(input,track);input.addEventListener('change',function(){onChange(key,input.checked);});row.append(copy,sw);return row;}input=document.createElement('input');input.type=(typeof value==='number'||info.kind==='number')?'number':'text';input.value=value==null?'':String(value);input.className='field-input';input.autocomplete='off';input.addEventListener('change',function(){onChange(key,U.parseScalar(input.value));});row.append(copy,input);return row;};
  C.readonlySettingField=function(key,titleText,description,value){var row=document.createElement('div');row.className='settings-row setting-card';row.dataset.settingKey=key;row.dataset.settingReadonly='true';var copy=document.createElement('span');copy.className='settings-row__copy';var title=document.createElement('strong');title.textContent=titleText||key;var meta=document.createElement('small');meta.className='text-description';meta.textContent=description||'';copy.append(title,meta);var input=document.createElement('input');input.type='text';input.className='field-input';input.value=value==null?'—':String(value);input.readOnly=true;row.append(copy,input);return row;};
  var activeSelect=null;
  function normalizeOptions(items){return(items||[]).map(function(item){return typeof item==='string'?{value:item,label:item}:{value:String(item.value),label:String(item.label==null?item.value:item.label)};});}
  function closeSelect(wrapper,restoreFocus){if(!wrapper)return false;var menu=wrapper.querySelector('.ui-select__menu'),trigger=wrapper.querySelector('.ui-select__trigger');if(!menu||menu.hidden)return false;menu.hidden=true;wrapper.classList.remove('is-open');if(trigger)trigger.setAttribute('aria-expanded','false');if(activeSelect===wrapper)activeSelect=null;if(restoreFocus&&trigger)trigger.focus();return true;}
  C.closeSelects=function(restoreFocus){return closeSelect(activeSelect,restoreFocus!==false);};
  C.selectControl=function(opts){opts=opts||{};var items=normalizeOptions(opts.options),value=String(opts.value==null?'':opts.value),wrapper=document.createElement('div');wrapper.className='ui-select'+(opts.className?' '+opts.className:'');if(opts.id)wrapper.id=opts.id;wrapper.dataset.uiSelect='1';var trigger=document.createElement('button');trigger.type='button';trigger.className='ui-select__trigger';trigger.setAttribute('aria-haspopup','listbox');trigger.setAttribute('aria-expanded','false');if(opts.ariaLabel)trigger.setAttribute('aria-label',opts.ariaLabel);var copy=document.createElement('span');copy.className='ui-select__value';var chevron=document.createElement('span');chevron.className='ui-select__chevron';chevron.setAttribute('aria-hidden','true');chevron.textContent='▾';trigger.append(copy,chevron);var menu=document.createElement('div');menu.className='ui-select__menu surface surface--floating';menu.setAttribute('role','listbox');menu.hidden=true;var list=document.createElement('div');list.className='ui-select__options';menu.appendChild(list);wrapper.append(trigger,menu);function current(){var hit=items.find(function(x){return x.value===value;});return hit?hit.label:(opts.placeholder||value||'—');}function render(){list.textContent='';items.forEach(function(item){var b=document.createElement('button');b.type='button';b.className='ui-select__option';b.dataset.value=item.value;b.textContent=item.label;b.setAttribute('role','option');b.setAttribute('aria-selected',item.value===value?'true':'false');b.addEventListener('click',function(){setValue(item.value,true);closeSelect(wrapper,true);});list.appendChild(b);});}function sync(){copy.textContent=current();trigger.title=current();trigger.disabled=!!opts.disabled;}function setValue(next,notify){value=String(next==null?'':next);sync();render();if(notify&&typeof opts.onChange==='function')opts.onChange(value);}trigger.addEventListener('click',function(e){e.stopPropagation();if(activeSelect&&activeSelect!==wrapper)closeSelect(activeSelect,false);menu.hidden=false;wrapper.classList.add('is-open');trigger.setAttribute('aria-expanded','true');activeSelect=wrapper;});wrapper.setValue=function(v){setValue(v,false);};wrapper.getValue=function(){return value;};wrapper.setOptions=function(next){items=normalizeOptions(next);render();sync();};wrapper.setDisabled=function(v){opts.disabled=!!v;sync();};render();sync();return wrapper;};
  C.filterChip=function(label,active){var b=document.createElement('button');b.type='button';b.className='ui-chip';b.classList.toggle('is-active',!!active);b.setAttribute('aria-pressed',active?'true':'false');b.textContent=label;return b;};
  C.checkControl=function(label,checked,onChange){var wrap=document.createElement('label');wrap.className='ui-check';var input=document.createElement('input');input.type='checkbox';input.checked=!!checked;var mark=document.createElement('span');mark.className='ui-check__mark';var copy=document.createElement('span');copy.className='ui-check__label';copy.textContent=label;wrap.append(input,mark,copy);input.addEventListener('change',function(){if(onChange)onChange(input.checked);});wrap.input=input;return wrap;};
  C.upgradeNativeSelect=function(select){if(!select||select.dataset.uiSelectUpgraded==='1'||select.closest('.ui-select')||select.closest('.mobile-filter-control'))return null;select.dataset.uiSelectUpgraded='1';var options=function(){return Array.from(select.options||[]).map(function(o){return{value:o.value,label:o.textContent};});};var custom=C.selectControl({value:select.value,options:options(),ariaLabel:select.getAttribute('aria-label')||select.name||select.id||'Select',searchable:(select.options||[]).length>18,onChange:function(next){select.value=next;select.dispatchEvent(new Event('input',{bubbles:true}));select.dispatchEvent(new Event('change',{bubbles:true}));}});custom.classList.add('ui-select--native');select.classList.add('ui-native-select');select.tabIndex=-1;select.setAttribute('aria-hidden','true');select.insertAdjacentElement('afterend',custom);select.addEventListener('change',function(){custom.setValue(select.value);});new MutationObserver(function(){custom.setOptions(options());custom.setValue(select.value);custom.setDisabled(select.disabled);}).observe(select,{childList:true,subtree:true,attributes:true,attributeFilter:['disabled']});custom.setDisabled(select.disabled);return custom;};
  C.upgradeNativeSelects=function(root){Array.from((root||document).querySelectorAll('select:not([data-ui-select-upgraded="1"])')).forEach(C.upgradeNativeSelect);};
  document.addEventListener('click',function(){C.closeSelects(false);});
  var buildToken=null;
  function currentBuildToken(){if(buildToken)return buildToken;var meta=document.querySelector('meta[name="weigg-build-sha"]'),raw=String(meta&&meta.content||'').trim();buildToken=/^[0-9a-f]{7,40}$/i.test(raw)?raw:'dev';return buildToken;}
  W.buildAssetUrl=function(src){var sep=src.indexOf('?')>=0?'&':'?';return src+sep+'v='+encodeURIComponent(currentBuildToken());};
  function observeNativeSelects(){C.upgradeNativeSelects(document);if(document.documentElement.dataset.selectObserver==='1')return;document.documentElement.dataset.selectObserver='1';new MutationObserver(function(records){records.forEach(function(record){Array.from(record.addedNodes||[]).forEach(function(node){if(!node||node.nodeType!==1)return;if(node.matches&&node.matches('select'))C.upgradeNativeSelect(node);C.upgradeNativeSelects(node);});});}).observe(document.body,{childList:true,subtree:true});}
  function init(){observeNativeSelects();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
