(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{},U=W.util,T=W.t||function(k){return k;};
  var states={downloading:['state.downloading','download'],metaDL:['state.metaDL','download'],forcedDL:['state.forcedDL','download'],allocating:['state.allocating','checking'],checkingDL:['state.checkingDL','checking'],checkingUP:['state.checkingUP','checking'],checkingResumeData:['state.checkingResumeData','checking'],moving:['state.moving','checking'],uploading:['state.uploading','seed'],stalledUP:['state.stalledUP','stalled-up'],forcedUP:['state.forcedUP','seed'],queuedUP:['state.queuedUP','queued'],pausedDL:['state.pausedDL','stopped'],pausedUP:['state.pausedUP','stopped'],stoppedDL:['state.stoppedDL','stopped'],stoppedUP:['state.stoppedUP','stopped'],queuedDL:['state.queuedDL','queued'],stalledDL:['state.stalledDL','stalled-down'],error:['state.error','danger'],missingFiles:['state.missingFiles','danger'],unknown:['state.unknown','muted']};
  var progressStates={downloading:['download',true],metaDL:['download',true],forcedDL:['download',true],uploading:['seed',true],forcedUP:['seed',true],allocating:['checking',true],checkingDL:['checking',true],checkingUP:['checking',true],checkingResumeData:['checking',true],moving:['checking',true],queuedDL:['queued',false],queuedUP:['queued',false],stalledDL:['stalled',false],stalledUP:['stalled',false],pausedDL:['paused',false],stoppedDL:['paused',false],pausedUP:['complete',false],stoppedUP:['complete',false],error:['error',false],missingFiles:['error',false]};
  var C=W.Components={};
  C.state=function(code){var s=states[code]||['state.unknown','muted'];return[T(s[0]),s[1]];};
  function textCell(text,cls){var e=document.createElement('span');e.className='cell '+(cls||'');e.textContent=text;return e;}
  function statusPill(code){var s=C.state(code),p=document.createElement('span');p.className='status-pill';p.dataset.tone=s[1];p.textContent=s[0];return p;}
  function progressVisual(t){var code=String(t&&t.state||''),percent=U.clamp(U.percent(t&&t.progress),0,100),meta=progressStates[code];if(meta)return{state:meta[0],active:meta[1],percent:percent};if(percent>=100)return{state:'complete',active:false,percent:percent};return{state:'idle',active:false,percent:percent};}
  function paintProgress(track,fill,t){var visual=progressVisual(t);if(track){track.dataset.progressState=visual.state;track.dataset.progressActive=visual.active?'true':'false';}if(fill){fill.dataset.progressState=visual.state;fill.dataset.progressActive=visual.active?'true':'false';fill.style.width=visual.percent+'%';}return visual;}
  function buildProgressTrack(t){var track=document.createElement('div');track.className='progress-track';var fill=document.createElement('div');fill.className='progress-fill';var visual=paintProgress(track,fill,t);track.appendChild(fill);return{track:track,visual:visual};}
  function progressCell(t){var p=document.createElement('div');p.className='progress-cell';var built=buildProgressTrack(t);p.dataset.progressState=built.visual.state;p.append(built.track,textCell(built.visual.percent+'%','progress-number'));return p;}
  function selectionHit(t,selected){var hit=document.createElement('label');hit.className='torrent-select-hit';hit.setAttribute('aria-label',T('torrent.name')+': '+U.escapeText(t.name));var check=document.createElement('input');check.type='checkbox';check.className='torrent-select';check.checked=selected;check.setAttribute('aria-label',T('torrent.name')+': '+U.escapeText(t.name));hit.appendChild(check);return hit;}
  function privacyBadge(t){if(!W.TorrentSemantics||!W.TorrentSemantics.classify)return null;var cfg=W.Config&&W.Config.load?W.Config.load():{},c=W.TorrentSemantics.classify(t,cfg.ptTrackers||[]);if(c.kind==='PUBLIC'||c.kind==='UNKNOWN')return null;var b=document.createElement('span');b.className='torrent-privacy-badge';b.dataset.privacyKind=c.kind;b.textContent=c.kind==='PRIVATE_PT'?'PRIVATE · PT':c.kind;return b;}
  function nameCell(t,selected,handlers){var name=document.createElement('div');name.className='torrent-name-cell';var titleLine=document.createElement('span');titleLine.className='torrent-title-line';var title=document.createElement('button');title.type='button';title.className='torrent-title';title.textContent=U.escapeText(t.name)||'Untitled torrent';title.title=U.escapeText(t.name);title.addEventListener('click',function(){handlers.open(t.hash);});titleLine.appendChild(title);var badge=privacyBadge(t);if(badge)titleLine.appendChild(badge);var more=document.createElement('button');more.type='button';more.className='row-more';more.textContent='›';more.setAttribute('aria-label',T('torrent.details'));more.addEventListener('click',function(){handlers.open(t.hash);});name.append(selectionHit(t,selected),titleLine,more);return name;}
  function registryCell(t,key){var registry=W.TorrentFieldRegistry,f=registry&&registry.get&&registry.get(key);if(!f)return null;var cell=textCell(f.format?f.format(t):'—','registry-cell registry-cell--'+f.key);cell.title=cell.textContent;return cell;}
  C.torrentRow=function(t,selected,handlers,columns,template){var row=document.createElement('article');row.className='torrent-row'+(selected?' is-selected':'');row.role='listitem';row.dataset.hash=t.hash;row.style.gridTemplateColumns=template;columns.forEach(function(c){var el;if(c.key==='name')el=nameCell(t,selected,handlers);else if(c.key==='size')el=textCell(U.formatBytes(t.size),'size-cell');else if(c.key==='progress')el=progressCell(t);else if(c.key==='dlspeed')el=textCell(U.formatSpeed(t.dlspeed),'speed-dl');else if(c.key==='upspeed')el=textCell(U.formatSpeed(t.upspeed),'speed-up');else if(c.key==='eta')el=textCell(U.formatEta(t.eta),'eta-cell');else if(c.key==='state'){el=document.createElement('div');el.className='status-cell';el.appendChild(statusPill(t.state));}else if(c.key==='ratio')el=textCell(U.formatRatio(t.ratio),'ratio-cell');else if(c.key==='tracker'){el=textCell(U.trackerLabel(t.tracker),'tracker-cell');el.title=U.normalizeTracker(t.tracker);}else if(c.key==='category')el=textCell(t.category||'—','category-cell');else el=registryCell(t,c.key)||textCell('—');row.appendChild(el);});return row;};
  function mobileFieldKeys(fields){var registry=W.TorrentFieldRegistry;if(registry&&registry.mobileFields)return registry.mobileFields();var out=[];(fields||[]).forEach(function(k){var key=k==='status'?'state':k==='dl'?'dlspeed':k==='up'?'upspeed':k;if(key!=='name'&&out.indexOf(key)<0)out.push(key);});return out.length?out:['state','progress','dlspeed','upspeed','eta','size'];}
  function fallbackMetric(t,key){if(key==='state')return C.state(t.state)[0];if(key==='progress')return U.percent(t.progress)+'%';if(key==='dlspeed')return'↓ '+U.formatSpeed(t.dlspeed);if(key==='upspeed')return'↑ '+U.formatSpeed(t.upspeed);if(key==='eta')return'ETA '+U.formatEta(t.eta);if(key==='size')return U.formatBytes(t.size);if(key==='ratio')return'R '+U.formatRatio(t.ratio);if(key==='tracker')return U.trackerLabel(t.tracker);if(key==='category')return t.category||'—';return'—';}
  function mobileMetric(t,key){var registry=W.TorrentFieldRegistry,f=registry&&registry.get&&registry.get(key),span=document.createElement('span');span.className='mobile-metric mobile-metric--'+key;span.dataset.mobileField=key;span.textContent=f&&f.format?f.format(t):fallbackMetric(t,key);span.title=span.textContent;return span;}
  C.mobileTorrentCard=function(t,selected,handlers,fields){var row=document.createElement('article');row.className='torrent-mobile-card torrent-mobile-card--two-line'+(selected?' is-selected':'');row.role='listitem';row.dataset.hash=t.hash;var top=document.createElement('div');top.className='mobile-card-top mobile-card-top--single';var titleLine=document.createElement('span');titleLine.className='torrent-title-line';var title=document.createElement('button');title.className='mobile-card-title';title.type='button';title.textContent=t.name||'Untitled torrent';title.title=title.textContent;title.addEventListener('click',function(){handlers.open(t.hash);});titleLine.appendChild(title);var badge=privacyBadge(t);if(badge)titleLine.appendChild(badge);var more=document.createElement('button');more.className='icon-btn mobile-more';more.type='button';more.textContent='⋯';more.setAttribute('aria-label',T('app.more'));more.addEventListener('click',function(){handlers.menu(t.hash);});top.append(selectionHit(t,selected),titleLine,more);row.appendChild(top);var keys=mobileFieldKeys(fields),rail=document.createElement('div');rail.className='mobile-card-meta mobile-card-meta--rail';keys.forEach(function(key){rail.appendChild(mobileMetric(t,key));});var overflow=document.createElement('button');overflow.type='button';overflow.className='mobile-metric-more';overflow.hidden=true;overflow.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();handlers.open(t.hash);});rail.appendChild(overflow);row.appendChild(rail);if(keys.indexOf('progress')>=0){var progress=buildProgressTrack(t).track;progress.classList.add('progress-track--mobile-edge');row.appendChild(progress);}return row;};
  C.progressVisual=progressVisual;
  C.progressTrack=function(t){return buildProgressTrack(t).track;};
  C.paintProgress=paintProgress;
  C.selectionHit=selectionHit;
  C.privacyBadge=privacyBadge;
  C.kv=function(label,value){var el=document.createElement('div');el.className='kv';var a=document.createElement('span'),b=document.createElement('strong');a.textContent=label;b.textContent=value==null?'—':String(value);el.append(a,b);return el;};
  C.sectionTitle=function(text,subtitle){var w=document.createElement('div');w.className='section-heading';var h=document.createElement('h2');h.textContent=text;w.appendChild(h);if(subtitle){var p=document.createElement('p');p.className='text-description';p.textContent=subtitle;w.appendChild(p);}return w;};
  C.filterChip=function(label,active){var b=document.createElement('button');b.type='button';b.className='ui-chip';b.classList.toggle('is-active',!!active);b.setAttribute('aria-pressed',active?'true':'false');b.textContent=label;return b;};
  C.checkControl=function(label,checked,onChange){var wrap=document.createElement('label');wrap.className='ui-check';var input=document.createElement('input');input.type='checkbox';input.checked=!!checked;var mark=document.createElement('span');mark.className='ui-check__mark';var copy=document.createElement('span');copy.className='ui-check__label';copy.textContent=label;wrap.append(input,mark,copy);input.addEventListener('change',function(){if(onChange)onChange(input.checked);});wrap.input=input;return wrap;};
  var buildToken=null;
  function currentBuildToken(){if(buildToken)return buildToken;var meta=document.querySelector('meta[name="weigg-build-sha"]'),raw=String(meta&&meta.content||'').trim();buildToken=/^[0-9a-f]{7,40}$/i.test(raw)?raw:'dev';return buildToken;}
  W.buildAssetUrl=function(src){var sep=src.indexOf('?')>=0?'&':'?';return src+sep+'v='+encodeURIComponent(currentBuildToken());};
})(window);
