(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{}, U=W.util={}, T=W.t||function(k){return k;};
  U.$=function(id){return document.getElementById(id);};
  U.$$=function(sel,root){return Array.prototype.slice.call((root||document).querySelectorAll(sel));};
  U.clamp=function(v,min,max){return Math.min(max,Math.max(min,v));};
  U.escapeText=function(v){return v==null?'':String(v);};
  U.sleep=function(ms){return new Promise(function(resolve){setTimeout(resolve,ms);});};
  U.formatBytes=function(value){var n=Number(value)||0;if(n<1024)return n+' B';var units=['KiB','MiB','GiB','TiB','PiB'],i=-1;do{n/=1024;i++;}while(n>=1024&&i<units.length-1);return (n>=100?n.toFixed(0):n>=10?n.toFixed(1):n.toFixed(2))+' '+units[i];};
  U.formatSpeed=function(value){return U.formatBytes(value)+'/s';};
  U.formatEta=function(value){var s=Number(value);if(!isFinite(s)||s<0||s>=8640000)return '∞';if(s===0)return '0s';var d=Math.floor(s/86400);s%=86400;var h=Math.floor(s/3600);s%=3600;var m=Math.floor(s/60);if(d)return d+'d '+h+'h';if(h)return h+'h '+m+'m';if(m)return m+'m';return Math.floor(s)+'s';};
  U.formatRatio=function(v){var n=Number(v);return isFinite(n)&&n>=0?n.toFixed(2):'—';};
  U.percent=function(v){return Math.round((Number(v)||0)*1000)/10;};
  U.form=function(obj){var p=new URLSearchParams();Object.keys(obj||{}).forEach(function(k){if(obj[k]!==undefined&&obj[k]!==null)p.append(k,String(obj[k]));});return p.toString();};
  U.debounce=function(fn,wait){var t;return function(){var a=arguments,c=this;clearTimeout(t);t=setTimeout(function(){fn.apply(c,a);},wait);};};
  U.time=function(){return new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});};
  U.hashes=function(set){return Array.from(set).join('|');};
  U.isMobile=function(){return matchMedia('(max-width: 820px)').matches;};
  U.safeJSON=function(value,fallback){try{return JSON.parse(value);}catch(_e){return fallback;}};
  U.parseScalar=function(value){var s=String(value).trim();if(s==='true')return true;if(s==='false')return false;if(s==='null')return null;if(s!==''&&!isNaN(Number(s)))return Number(s);try{return JSON.parse(s);}catch(_e){return value;}};
  U.normalizeTracker=function(raw){var value=String(raw||'').trim();if(!value)return '';try{var url=new URL(value);var port=url.port&&url.port!==((url.protocol==='https:')?'443':(url.protocol==='http:'?'80':''))?':'+url.port:'';return url.protocol+'//'+url.hostname+port+(url.pathname||'/');}catch(_e){return value.split('?')[0].split('#')[0];}};
  U.trackerLabel=function(raw){var value=U.normalizeTracker(raw);if(!value)return T('tracker.none');try{var u=new URL(value),h=u.hostname.replace(/^tracker\./i,'');return h.split('.')[0].replace(/[-_]+/g,' ').replace(/\b\w/g,function(c){return c.toUpperCase();})||u.hostname;}catch(_e){return value;}};
  var CONFIG_KEY=(W.StorageKeys&&W.StorageKeys.config)||'weig.preferences';
  W.Config={key:CONFIG_KEY,defaults:{theme:'dark',fontSize:'large',density:'standard',pageSize:50,refresh:2000,starfield:'subtle',motion:'system',mobileFields:['status','progress','dl','up','eta','size'],ptTrackers:[],columns:null},load:function(){var saved=U.safeJSON(localStorage.getItem(this.key),{})||{},out={};Object.keys(this.defaults).forEach(function(k){out[k]=saved[k]===undefined?W.Config.defaults[k]:saved[k];});return out;},save:function(obj){var value=Object.assign({schemaVersion:1},obj||{});localStorage.setItem(this.key,JSON.stringify(value));},apply:function(cfg){var h=document.documentElement;h.dataset.fontSize=cfg.fontSize;h.dataset.density=cfg.density;h.dataset.starfield=cfg.starfield;h.dataset.motion=cfg.motion;if(W.Theme&&W.Theme.applyConfig)W.Theme.applyConfig(cfg);}};
  W.fatal=function(error){var box=U.$('fatal'),msg=U.$('fatal-message');if(msg)msg.textContent=(error&&error.message)||T('fatal.unknown');if(box)box.classList.remove('is-hidden');};
  W.QbPath={
    separator:function(value){value=String(value||'');return /^[A-Za-z]:[\\/]/.test(value)||/^\\\\/.test(value)||value.indexOf('\\')>=0?'\\':'/';},
    join:function(base,relative){base=String(base||'');relative=String(relative||'');if(!base)return relative;if(!relative)return base;var sep=this.separator(base),tail=base.replace(/[\\/]+$/,''),part=relative.replace(/^[\\/]+/,'').replace(/[\\/]+/g,sep);if(!tail){if(sep==='/'&&base.indexOf('/')===0)return '/'+part;return part;}return tail+sep+part;},
    dirname:function(value){value=String(value||'');if(!value)return'';var end=value.length;while(end>1&&/[\\/]/.test(value.charAt(end-1)))end--;var trimmed=value.slice(0,end),at=Math.max(trimmed.lastIndexOf('/'),trimmed.lastIndexOf('\\'));if(at<0)return'';if(at===0)return trimmed.charAt(0);if(at===2&&/^[A-Za-z]:/.test(trimmed))return trimmed.slice(0,3);return trimmed.slice(0,at);},
    resolveFile:function(properties,file){var base=properties&&properties.save_path,name=file&&file.name;if(base==null||name==null)return'';return this.join(base,name);}
  };
  W.Router={route:function(){var raw=(location.hash||'#/').replace(/^#/,'');var parts=raw.split('/').filter(Boolean);return {name:parts[0]||'home',id:parts[1]||'',tab:parts[2]||''};},go:function(path){location.hash='#/'+String(path||'').replace(/^\/+/, '');},home:function(){location.hash='#/';},detail:function(hash,tab){location.hash='#/torrent/'+encodeURIComponent(hash)+(tab?'/'+tab:'');},back:function(){var r=this.route();if(r.name!=='home'&&history.length>1)history.back();else this.home();}};

  function frame(fn){var raf=global.requestAnimationFrame||function(cb){return global.setTimeout(cb,16);};return raf(fn);}
  function cancelFrame(id){var cancel=global.cancelAnimationFrame||global.clearTimeout;if(id&&cancel)cancel(id);}
  W.DataViewport=function(container,options){
    options=options||{};this.el=container;this.rowHeight=options.rowHeight||52;this.overscan=options.overscan||6;this.renderRow=options.renderRow;this.createRow=typeof options.createRow==='function'?options.createRow:this.renderRow;this.updateRow=typeof options.updateRow==='function'?options.updateRow:null;this.releaseRow=typeof options.releaseRow==='function'?options.releaseRow:null;this.recycler=!!this.updateRow;this.variableHeight=!!options.variableHeight;this.itemKey=typeof options.itemKey==='function'?options.itemKey:function(_item,index){return index;};this.itemSignature=typeof options.itemSignature==='function'?options.itemSignature:null;this.heightMap=new Map();this.offsets=[0];this.items=[];this._signatureCache=[];this._rowPool=[];this._cachedHeaderHeight=0;this.spacer=document.createElement('div');this.spacer.className='data-viewport__spacer';this.el.classList.add('data-viewport');
    var remembered=Number(this.el.__weigDataViewportScrollTop)||0,rememberedLeft=Number(this.el.__weigDataViewportScrollLeft)||0;
    if(this.el.__weigDataViewportScrollHandler)this.el.removeEventListener('scroll',this.el.__weigDataViewportScrollHandler);
    cancelFrame(this.el.__weigDataViewportScrollFrame);this.el.__weigDataViewportScrollFrame=0;
    if(this.el.__weigDataViewportScrollIdleTimer)global.clearTimeout(this.el.__weigDataViewportScrollIdleTimer);this.el.__weigDataViewportScrollIdleTimer=0;
    this.staticHead=options.staticHead||null;
    this.el.textContent='';
    if(this.staticHead){this.staticHead.classList.add('data-viewport__head');this.el.appendChild(this.staticHead);}
    this.el.appendChild(this.spacer);this.el.__weigDataViewportScrollTop=remembered;this.el.__weigDataViewportScrollLeft=rememberedLeft;this._rendering=false;this._lastRange='';this._lastScrollTop=remembered;this._lastScrollLeft=rememberedLeft;this._scrolling=false;this._hasPendingItems=false;this._pendingItems=null;this._pendingPreserve=undefined;this._pendingUiCommit=null;this._renderedRows=new Map();this.onScroll=typeof options.onScroll==='function'?options.onScroll:null;this._metrics={renders:0,created:0,reused:0,updated:0,removed:0,measured:0,lastRenderMs:0,maxRenderMs:0,totalRenderMs:0,poolPeak:0};
    var self=this;
    this.el.__weigDataViewportScrollHandler=function(){
      if(!self.spacer.isConnected||self.spacer.parentNode!==self.el)return;
      var top=self.el.scrollTop,left=self.el.scrollLeft,vertical=Math.abs(top-self._lastScrollTop)>.5,horizontal=Math.abs(left-self._lastScrollLeft)>.5;
      if(vertical||horizontal){self._scrolling=true;self.el.classList.add('is-scroll-interacting');if(self.el.__weigDataViewportScrollIdleTimer)global.clearTimeout(self.el.__weigDataViewportScrollIdleTimer);self.el.__weigDataViewportScrollIdleTimer=global.setTimeout(function(){self.el.__weigDataViewportScrollIdleTimer=0;if(!self.spacer.isConnected||self.spacer.parentNode!==self.el)return;self._scrolling=false;self.el.classList.remove('is-scroll-interacting');self._flushPendingItems();self._normalizeRenderedRows();self._flushPendingUiCommit();},120);}
      self.el.__weigDataViewportScrollTop=top;self.el.__weigDataViewportScrollLeft=left;self._lastScrollTop=top;self._lastScrollLeft=left;
      if(typeof self.onScroll==='function')self.onScroll({top:top,left:left,vertical:vertical,horizontal:horizontal});
      if(!vertical||self._rendering||self.el.__weigDataViewportScrollFrame)return;
      self.el.__weigDataViewportScrollFrame=frame(function(){self.el.__weigDataViewportScrollFrame=0;if(!self.spacer.isConnected||self.spacer.parentNode!==self.el)return;self.render(false);});
    };
    this.el.addEventListener('scroll',this.el.__weigDataViewportScrollHandler,{passive:true});this._rebuildOffsets();
  };
  W.DataViewport.prototype._key=function(item,index){try{return this.itemKey(item,index);}catch(_e){return index;}};
  W.DataViewport.prototype._computeSignature=function(item,index){if(!this.itemSignature)return{valid:false,value:null};try{return{valid:true,value:this.itemSignature(item,index)};}catch(_e){return{valid:false,value:null};}};
  W.DataViewport.prototype._precomputeSignatures=function(){this._signatureCache=[];if(!this.itemSignature)return;for(var i=0;i<this.items.length;i++)this._signatureCache[i]=this._computeSignature(this.items[i],i);};
  W.DataViewport.prototype._signature=function(item,index){return this._signatureCache[index]||this._computeSignature(item,index);};
  W.DataViewport.prototype._headerHeight=function(refresh){if(!this.staticHead||this.staticHead.offsetParent===null){this._cachedHeaderHeight=0;return 0;}if(refresh||!this._cachedHeaderHeight)this._cachedHeaderHeight=Math.max(0,Number(this.staticHead.offsetHeight)||0);return this._cachedHeaderHeight;};
  W.DataViewport.prototype.refreshGeometry=function(){this._cachedHeaderHeight=0;this._lastRange='';this.render(true);};
  W.DataViewport.prototype._rebuildOffsets=function(){if(!this.variableHeight){this.offsets=[0,this.items.length*this.rowHeight];this.spacer.style.height=(this.items.length*this.rowHeight)+'px';return;}var offsets=new Array(this.items.length+1);offsets[0]=0;for(var i=0;i<this.items.length;i++){var key=this._key(this.items[i],i),height=Number(this.heightMap.get(key))||this.rowHeight;offsets[i+1]=offsets[i]+Math.max(this.rowHeight,height);}this.offsets=offsets;this.spacer.style.height=(offsets[offsets.length-1]||0)+'px';};
  W.DataViewport.prototype._totalHeight=function(){return this.variableHeight?(this.offsets[this.offsets.length-1]||0):this.items.length*this.rowHeight;};
  W.DataViewport.prototype._indexAtOffset=function(offset){if(!this.variableHeight)return Math.max(0,Math.min(this.items.length-1,Math.floor(offset/this.rowHeight)));var lo=0,hi=this.items.length;while(lo<hi){var mid=(lo+hi)>>1;if((this.offsets[mid+1]||0)<=offset)lo=mid+1;else hi=mid;}return Math.max(0,Math.min(this.items.length-1,lo));};
  W.DataViewport.prototype._range=function(){var visible=!!(this.el.isConnected&&this.el.clientHeight>0&&this.el.getClientRects().length),headH=this._headerHeight(),h=visible?Math.max(1,this.el.clientHeight-headH):420,remembered=Number(this.el.__weigDataViewportScrollTop)||0,top=Math.max(0,(visible?this.el.scrollTop:remembered)-headH),start,end;if(this.variableHeight&&this.items.length){start=Math.max(0,this._indexAtOffset(top)-this.overscan);end=Math.min(this.items.length,this._indexAtOffset(top+h)+this.overscan+1);}else{start=Math.max(0,Math.floor(top/this.rowHeight)-this.overscan);end=Math.min(this.items.length,Math.ceil((top+h)/this.rowHeight)+this.overscan);}return{visible:visible,start:start,end:end,top:top,height:h,key:start+':'+end};};
  W.DataViewport.prototype.invalidateItemHeight=function(key){if(!this.variableHeight)return;this.heightMap.delete(key);this._rebuildOffsets();this._lastRange='';this.render(true);};
  W.DataViewport.prototype.resetHeights=function(){if(!this.variableHeight)return;this.heightMap.clear();this._rebuildOffsets();this._lastRange='';this.render(true);};
  W.DataViewport.prototype.setRowHeight=function(h){this.rowHeight=h||this.rowHeight;if(this.variableHeight)this.heightMap.clear();this._rebuildOffsets();this._lastRange='';this.render(true);};
  W.DataViewport.prototype.resetScroll=function(){this.el.__weigDataViewportScrollTop=0;this._lastScrollTop=0;this.el.scrollTop=0;this._lastRange='';this.render(true);};
  W.DataViewport.prototype._applyItems=function(items,preserve){this.items=items||[];this._precomputeSignatures();if(this.variableHeight&&this.heightMap.size){var live=new Set();for(var i=0;i<this.items.length;i++)live.add(this._key(this.items[i],i));Array.from(this.heightMap.keys()).forEach(function(key){if(!live.has(key))this.heightMap.delete(key);},this);}this._rebuildOffsets();var keep=preserve!==false,clientH=this.el.clientHeight||0,saved=keep?(Number(this.el.__weigDataViewportScrollTop)||0):0,max=Math.max(0,this._totalHeight()+this._headerHeight()-clientH);saved=Math.min(saved,max);this.el.__weigDataViewportScrollTop=saved;this._lastScrollTop=saved;if(clientH>0)this.el.scrollTop=saved;this._lastRange='';this.render(true);};
  W.DataViewport.prototype._flushPendingItems=function(){if(!this._hasPendingItems)return;var items=this._pendingItems,preserve=this._pendingPreserve;this._hasPendingItems=false;this._pendingItems=null;this._pendingPreserve=undefined;this._applyItems(items,preserve);};
  W.DataViewport.prototype._normalizeRenderedRows=function(){if(this.recycler)return;var self=this;Array.from(this._renderedRows.values()).sort(function(a,b){return a.index-b.index;}).forEach(function(entry){if(entry&&entry.node&&entry.node.parentNode===self.spacer)self.spacer.appendChild(entry.node);});};
  W.DataViewport.prototype.setItems=function(items,preserve){if(this._scrolling){this._pendingItems=items||[];this._pendingPreserve=preserve;this._hasPendingItems=true;return;}this._applyItems(items,preserve);};
  W.DataViewport.prototype.isInteracting=function(){return !!this._scrolling;};
  W.DataViewport.prototype.resetPool=function(){for(var i=0;i<this._rowPool.length;i++){var slot=this._rowPool[i],row=slot&&slot.node;if(this.releaseRow&&row)try{this.releaseRow(row,slot);}catch(_e){}if(row&&row.parentNode===this.spacer){row.remove();this._metrics.removed++;}}this._rowPool=[];this._renderedRows.clear();this._lastRange='';};
  W.DataViewport.prototype._flushPendingUiCommit=function(){var commit=this._pendingUiCommit;this._pendingUiCommit=null;if(typeof commit==='function')commit();};
  W.DataViewport.prototype.commitWhenIdle=function(commit){if(typeof commit!=='function')return true;if(this._scrolling){this._pendingUiCommit=commit;return false;}commit();return true;};
  W.DataViewport.prototype.destroy=function(){if(this.el.__weigDataViewportScrollHandler)this.el.removeEventListener('scroll',this.el.__weigDataViewportScrollHandler);if(this.el.__weigDataViewportScrollFrame)cancelFrame(this.el.__weigDataViewportScrollFrame);if(this.el.__weigDataViewportScrollIdleTimer)global.clearTimeout(this.el.__weigDataViewportScrollIdleTimer);this.el.__weigDataViewportScrollHandler=null;this.el.__weigDataViewportScrollFrame=0;this.el.__weigDataViewportScrollIdleTimer=0;this.el.classList.remove('is-scroll-interacting');this._scrolling=false;this._hasPendingItems=false;this._pendingItems=null;this._pendingPreserve=undefined;this._pendingUiCommit=null;this._signatureCache=[];this._rowPool=[];this._renderedRows.clear();};
  W.DataViewport.prototype.metrics=function(){return Object.assign({},this._metrics,{visible:this._renderedRows.size,poolSize:this._rowPool.length});};
  W.DataViewport.prototype.resetMetrics=function(){this._metrics={renders:0,created:0,reused:0,updated:0,removed:0,measured:0,lastRenderMs:0,maxRenderMs:0,totalRenderMs:0,poolPeak:this._rowPool.length};return this.metrics();};
  W.DataViewport.prototype._finishRenderMetrics=function(started){if(started){var elapsed=Math.max(0,global.performance.now()-started);this._metrics.lastRenderMs=elapsed;this._metrics.totalRenderMs+=elapsed;this._metrics.maxRenderMs=Math.max(this._metrics.maxRenderMs,elapsed);}this._rendering=false;};
  W.DataViewport.prototype._renderRecycler=function(force){
    if(force===undefined)force=true;if(force)this._headerHeight(true);var range=this._range();if(!force&&range.key===this._lastRange)return;
    var started=global.performance&&typeof global.performance.now==='function'?global.performance.now():0;this._rendering=true;this._lastRange=range.key;this._metrics.renders++;
    var count=Math.max(0,range.end-range.start),capacity=count;if(!this.variableHeight&&this.items.length){capacity=Math.min(this.items.length,Math.max(count,Math.ceil(range.height/this.rowHeight)+(this.overscan*2)+1));}
    var templateRoot=this.el.closest&&this.el.closest('.torrent-panel'),gridTemplate=templateRoot&&templateRoot.style.getPropertyValue('--weig-grid-template')?'var(--weig-grid-template)':'',nextRows=new Map(),dirty=false,rendered=this.variableHeight?[]:null,j;
    while(this._rowPool.length<capacity){var slotIndex=this._rowPool.length,newIndex=Math.min(this.items.length-1,range.start+Math.min(slotIndex,Math.max(0,count-1))),newItem=this.items[newIndex],newKey=this._key(newItem,newIndex),newSig=this._signature(newItem,newIndex),row=this.createRow(newItem,newIndex);row.classList.add('data-viewport__row');row.hidden=false;if(row.parentNode!==this.spacer)this.spacer.appendChild(row);this._rowPool.push({node:row,index:newIndex,key:newKey,signature:newSig.value,signatureValid:newSig.valid,bound:true,justCreated:true});this._metrics.created++;this._metrics.poolPeak=Math.max(this._metrics.poolPeak,this._rowPool.length);}
    var targets=[],slotByKey=new Map(),used=new Set(),free=[];
    for(j=0;j<this._rowPool.length;j++){var existing=this._rowPool[j];if(existing.bound&&!slotByKey.has(existing.key))slotByKey.set(existing.key,existing);}
    for(j=0;j<count;j++){var index=range.start+j,item=this.items[index],key=this._key(item,index),sig=this._signature(item,index),slot=slotByKey.get(key);if(slot&&used.has(slot))slot=null;targets.push({index:index,item:item,key:key,sig:sig,slot:slot||null});if(slot)used.add(slot);}
    for(j=0;j<this._rowPool.length;j++)if(!used.has(this._rowPool[j]))free.push(this._rowPool[j]);
    var freeIndex=0;
    for(j=0;j<targets.length;j++){var target=targets[j];if(!target.slot){target.slot=free[freeIndex++];used.add(target.slot);}}
    for(j=0;j<targets.length;j++){var targetRow=targets[j],slot=targetRow.slot,node=slot.node,index=targetRow.index,item=targetRow.item,key=targetRow.key,sig=targetRow.sig,fresh=!!slot.justCreated;if(node.hidden)node.hidden=false;if(node.getAttribute&&node.getAttribute('aria-hidden')!==null)node.removeAttribute('aria-hidden');var changed=!slot.bound||slot.index!==index||slot.key!==key||(sig.valid?(!slot.signatureValid||slot.signature!==sig.value):!!force);if(!fresh){this._metrics.reused++;if(changed){if(this.releaseRow&&slot.bound&&slot.key!==key)try{this.releaseRow(node,slot);}catch(_e){}this.updateRow(node,item,index,{key:slot.key,index:slot.index,signature:slot.signature});this._metrics.updated++;}}slot.justCreated=false;slot.bound=true;slot.index=index;slot.key=key;slot.signature=sig.value;slot.signatureValid=sig.valid;var y=this.variableHeight?(this.offsets[index]||0):(index*this.rowHeight),height=this.variableHeight?'auto':this.rowHeight+'px',transform='translateY('+y+'px)';if(node.style.height!==height)node.style.height=height;if(this.variableHeight&&node.style.minHeight!==this.rowHeight+'px')node.style.minHeight=this.rowHeight+'px';if(node.style.transform!==transform)node.style.transform=transform;if(gridTemplate&&node.classList.contains('torrent-row')&&node.style.gridTemplateColumns!==gridTemplate)node.style.gridTemplateColumns=gridTemplate;nextRows.set(key,{node:node,index:index,signature:sig.value,signatureValid:sig.valid});if(rendered)rendered.push([node,index]);if(this.variableHeight&&range.visible&&(fresh||changed||force||!this.heightMap.has(key))){this._metrics.measured++;var measured=Math.max(this.rowHeight,Math.ceil(node.getBoundingClientRect().height)),known=this.heightMap.has(key)?Number(this.heightMap.get(key)):this.rowHeight;this.heightMap.set(key,measured);if(Math.abs(measured-known)>1)dirty=true;}}
    for(j=0;j<this._rowPool.length;j++){var unused=this._rowPool[j];if(used.has(unused))continue;var hidden=unused.node;if(unused.bound&&this.releaseRow)try{this.releaseRow(hidden,unused);}catch(_e){}unused.bound=false;unused.index=-1;unused.key=null;unused.signature=null;unused.signatureValid=false;unused.justCreated=false;if(!hidden.hidden)hidden.hidden=true;if(!hidden.getAttribute||hidden.getAttribute('aria-hidden')!=='true')hidden.setAttribute('aria-hidden','true');}
    this._renderedRows=nextRows;if(dirty&&rendered){this._rebuildOffsets();for(var r=0;r<rendered.length;r++){var corrected='translateY('+(this.offsets[rendered[r][1]]||0)+'px)';if(rendered[r][0].style.transform!==corrected)rendered[r][0].style.transform=corrected;}}if(this.el.dataset.rendered!==String(count))this.el.dataset.rendered=String(count);if(range.visible){this.el.__weigDataViewportScrollTop=this.el.scrollTop;this.el.__weigDataViewportScrollLeft=this.el.scrollLeft;this._lastScrollTop=this.el.scrollTop;this._lastScrollLeft=this.el.scrollLeft;}this._finishRenderMetrics(started);
  };
  W.DataViewport.prototype.render=function(force){
    if(W.DataGrid&&W.DataGrid._suppressVirtualRender)return;if(this.recycler)return this._renderRecycler(force);if(force===undefined)force=true;if(force)this._headerHeight(true);var range=this._range();if(!force&&range.key===this._lastRange)return;var started=global.performance&&typeof global.performance.now==='function'?global.performance.now():0;this._rendering=true;this._lastRange=range.key;this._metrics.renders++;var previous=this._renderedRows,next=new Map(),rendered=[],dirty=false,templateRoot=this.el.closest&&this.el.closest('.torrent-panel');
    for(var i=range.start;i<range.end;i++){var item=this.items[i],key=this._key(item,i),sig=this._signature(item,i),entry=previous.get(key),canReuse=!!(entry&&entry.node&&entry.node.parentNode===this.spacer&&((sig.valid&&entry.signatureValid&&entry.signature===sig.value)||(!sig.valid&&!force))),row;if(canReuse){row=entry.node;this._metrics.reused++;}else{row=this.renderRow(item,i);row.classList.add('data-viewport__row');this._metrics.created++;}var y=this.variableHeight?(this.offsets[i]||0):(i*this.rowHeight);row.style.height=this.variableHeight?'auto':this.rowHeight+'px';if(this.variableHeight)row.style.minHeight=this.rowHeight+'px';row.style.transform='translateY('+y+'px)';if(templateRoot&&row.classList.contains('torrent-row')&&templateRoot.style.getPropertyValue('--weig-grid-template'))row.style.gridTemplateColumns='var(--weig-grid-template)';if(row.parentNode!==this.spacer)this.spacer.appendChild(row);next.set(key,{node:row,index:i,signature:sig.value,signatureValid:sig.valid});rendered.push([row,i]);if(this.variableHeight&&range.visible&&(!canReuse||force||!this.heightMap.has(key))){this._metrics.measured++;var measured=Math.max(this.rowHeight,Math.ceil(row.getBoundingClientRect().height)),known=this.heightMap.has(key)?Number(this.heightMap.get(key)):this.rowHeight;this.heightMap.set(key,measured);if(Math.abs(measured-known)>1)dirty=true;}}
    previous.forEach(function(entry,key){var replacement=next.get(key);if(replacement&&replacement.node===entry.node)return;var row=entry&&entry.node;if(row&&row.parentNode===this.spacer){if(typeof row.remove==='function')row.remove();else if(this.spacer.removeChild)this.spacer.removeChild(row);this._metrics.removed++;}},this);this._renderedRows=next;if(dirty){this._rebuildOffsets();for(var r=0;r<rendered.length;r++)rendered[r][0].style.transform='translateY('+(this.offsets[rendered[r][1]]||0)+'px';}this.el.dataset.rendered=String(Math.max(0,range.end-range.start));if(range.visible){this.el.__weigDataViewportScrollTop=this.el.scrollTop;this.el.__weigDataViewportScrollLeft=this.el.scrollLeft;this._lastScrollTop=this.el.scrollTop;this._lastScrollLeft=this.el.scrollLeft;}this._finishRenderMetrics(started);
  };

  var GRID_MIN_WIDTH=24,GRID_HEADER_ELLIPSIS='…',gridMeasureCanvas=null;
  function gridHeaderText(column){return String(column&&((column.label!==undefined&&column.label!==null)?column.label:(column.caption!==undefined&&column.caption!==null)?column.caption:column.key)||'');}
  function gridGraphemes(value){var text=String(value||'');if(!text)return[];try{if(global.Intl&&Intl.Segmenter){var segmenter=new Intl.Segmenter(undefined,{granularity:'grapheme'});return Array.from(segmenter.segment(text),function(item){return item.segment;});}}catch(_e){}return Array.from(text);}
  function gridMeasureNodeText(node,text){if(!gridMeasureCanvas)gridMeasureCanvas=document.createElement('canvas');var ctx=gridMeasureCanvas.getContext&&gridMeasureCanvas.getContext('2d');if(!ctx)return String(text||'').length*8;var style=node&&global.getComputedStyle?global.getComputedStyle(node):null;if(style)ctx.font=[style.fontStyle,style.fontVariant,style.fontWeight,style.fontSize,style.fontFamily].filter(Boolean).join(' ');return ctx.measureText(String(text||'')).width;}
  function gridPx(style,name){var value=style?parseFloat(style[name]):0;return Number.isFinite(value)?value:0;}
  function gridHeaderInsets(cell,label){var cs=cell&&global.getComputedStyle?global.getComputedStyle(cell):null,ls=label&&global.getComputedStyle?global.getComputedStyle(label):null;return gridPx(cs,'paddingLeft')+gridPx(cs,'paddingRight')+gridPx(ls,'paddingLeft')+gridPx(ls,'paddingRight');}
  function gridColumnAlign(column){var requested=String(column&&column.align||'').toLowerCase();if(requested==='start'||requested==='center'||requested==='end'||requested==='stretch')return requested;var key=String(column&&column.key||'').toLowerCase();if(key==='state_icon'||key==='checked')return'center';if(key==='progress')return'stretch';return'start';}
  function gridColumnHardMin(column,cell){var explicit=Number(column&&column.hardMin);if(Number.isFinite(explicit)&&explicit>0)return Math.max(GRID_MIN_WIDTH,explicit);if(!cell)return Math.max(GRID_MIN_WIDTH,Number(column&&column.__weigHeaderHardMin)||0);var label=cell.querySelector&&cell.querySelector('.grid-head-label'),full=label&&label.dataset?String(label.dataset.fullLabel||''):gridHeaderText(column),parts=gridGraphemes(full),minimum=GRID_MIN_WIDTH;if(parts.length&&label){minimum=Math.max(GRID_MIN_WIDTH,Math.ceil(gridMeasureNodeText(label,parts[0])+gridHeaderInsets(cell,label)+1));}column.__weigHeaderHardMin=minimum;return minimum;}
  function gridFitHeaderCell(cell,column){if(!cell)return'';var label=cell.querySelector&&cell.querySelector('.grid-head-label');if(!label)return'';var full=String(label.dataset.fullLabel!==undefined?label.dataset.fullLabel:gridHeaderText(column)),parts=gridGraphemes(full);cell.setAttribute('aria-label',full);if(!parts.length){label.textContent='';return'';}var style=global.getComputedStyle?global.getComputedStyle(label):null,available=Math.max(0,label.clientWidth-gridPx(style,'paddingLeft')-gridPx(style,'paddingRight'));if(!available){label.textContent=parts[0];return parts[0];}if(gridMeasureNodeText(label,full)<=available){label.textContent=full;return full;}for(var count=parts.length-1;count>=1;count--){var candidate=parts.slice(0,count).join('')+GRID_HEADER_ELLIPSIS;if(gridMeasureNodeText(label,candidate)<=available){label.textContent=candidate;return candidate;}}label.textContent=parts[0];return parts[0];}
  function gridCreateHeaderCell(column,options){options=options||{};var cell=document.createElement('span');cell.className='grid-head-cell';cell.dataset.key=String(column&&column.key||'');cell.dataset.align=gridColumnAlign(column);var label=document.createElement('span');label.className='grid-head-label';var full=String(options.label?options.label(column):gridHeaderText(column));label.dataset.fullLabel=full;label.textContent=full;cell.appendChild(label);cell.setAttribute('aria-label',full);if(options.onClick)cell.addEventListener('click',function(e){if(e.target&&e.target.closest&&e.target.closest('.col-resize'))return;options.onClick(column,e,cell);});if(options.surfaceId)cell.addEventListener('contextmenu',function(e){e.preventDefault();e.stopPropagation();if(W.ColumnConfigurator)W.ColumnConfigurator.open(options.surfaceId);});return cell;}
  function gridRefreshHeader(head,columns){if(!head)return columns||[];var byKey={};(columns||[]).forEach(function(column){byKey[String(column.key||'')]=column;});Array.from(head.querySelectorAll('.grid-head-cell')).forEach(function(cell){var column=byKey[String(cell.dataset.key||'')];if(!column)return;gridColumnHardMin(column,cell);gridFitHeaderCell(cell,column);});return columns||[];}
  function gridRenderHeader(head,columns,options){if(!head)return[];head.textContent='';(columns||[]).forEach(function(column){head.appendChild(gridCreateHeaderCell(column,options));});gridRefreshHeader(head,columns);return columns||[];}
  function gridBindHeader(head,columns,onChange,options){
    options=options||{};var root=options.root||head.closest('.shared-table__viewport')||head.closest('.torrent-panel')||head.parentElement,cssVar=options.cssVar||((head.classList.contains('shared-table__head'))?'--weig-detail-grid-template':'--weig-grid-template'),rowSelector=options.rowSelector||(head.classList.contains('shared-table__head')?'.shared-table__row':'.torrent-row'),viewport=options.viewport||((head.parentElement&&head.parentElement.scrollWidth>head.parentElement.clientWidth)?head.parentElement:root);
    function setTemplate(){var template=W.DataGrid.template(columns);if(root)root.style.setProperty(cssVar,template);head.style.gridTemplateColumns=root?'var('+cssVar+')':template;gridRefreshHeader(head,columns);return template;}
    function bindRows(){if(!root)return;Array.from(root.querySelectorAll(rowSelector)).forEach(function(row){row.style.gridTemplateColumns='var('+cssVar+')';});}
    function notify(reason){W.DataGrid._suppressVirtualRender=true;try{if(onChange)onChange(columns,true,reason);}finally{W.DataGrid._suppressVirtualRender=false;}}
    function clearDrop(){Array.from(head.querySelectorAll('.grid-head-cell')).forEach(function(cell){cell.style.boxShadow='';cell.style.opacity='';cell.classList.remove('is-column-dragging');});}
    function reorderRows(oldKeys){if(!root)return;Array.from(root.querySelectorAll(rowSelector)).forEach(function(row){var children=Array.from(row.children),byKey={};oldKeys.forEach(function(key,index){if(children[index])byKey[key]=children[index];});columns.forEach(function(column){if(byKey[column.key])row.appendChild(byKey[column.key]);});});}
    function commitReorder(sourceKey,targetKey,before){var oldKeys=columns.map(function(column){return column.key;}),si=columns.findIndex(function(column){return column.key===sourceKey;}),ti=columns.findIndex(function(column){return column.key===targetKey;});if(si<0||ti<0||si===ti)return false;var moved=columns.splice(si,1)[0];ti=columns.findIndex(function(column){return column.key===targetKey;});columns.splice(before?ti:ti+1,0,moved);columns.forEach(function(column){var node=Array.from(head.querySelectorAll('.grid-head-cell')).find(function(cell){return cell.dataset.key===column.key;});if(node)head.appendChild(node);});reorderRows(oldKeys);setTemplate();notify('reorder');return true;}
    function autoScroll(pointerX){if(!viewport||viewport.scrollWidth<=viewport.clientWidth)return;var rect=viewport.getBoundingClientRect(),edge=Math.min(48,Math.max(26,rect.width*.08));if(pointerX<rect.left+edge)viewport.scrollLeft=Math.max(0,viewport.scrollLeft-18);else if(pointerX>rect.right-edge)viewport.scrollLeft=Math.min(viewport.scrollWidth-viewport.clientWidth,viewport.scrollLeft+18);}
    if(head.__weigGridResizeObserver&&head.__weigGridResizeObserver.disconnect)head.__weigGridResizeObserver.disconnect();if(global.ResizeObserver){head.__weigGridResizeObserver=new ResizeObserver(function(){gridRefreshHeader(head,columns);});head.__weigGridResizeObserver.observe(head);}
    setTemplate();bindRows();
    Array.from(head.querySelectorAll('.grid-head-cell')).forEach(function(cell){
      var handle=document.createElement('span');handle.className='col-resize';handle.setAttribute('aria-hidden','true');cell.appendChild(handle);
      handle.addEventListener('pointerdown',function(e){e.preventDefault();e.stopPropagation();var key=cell.dataset.key,current=columns.find(function(column){return column.key===key;}),startX=e.clientX,startW=current&&current.width||100,pointerId=e.pointerId;bindRows();if(handle.setPointerCapture)try{handle.setPointerCapture(pointerId);}catch(_e){}function move(ev){if(ev.pointerId!==pointerId)return;var active=columns.find(function(column){return column.key===key;});if(!active)return;active.width=Math.max(gridColumnHardMin(active,cell),startW+(ev.clientX-startX));setTemplate();}function up(ev){if(ev.pointerId!==pointerId)return;if(handle.hasPointerCapture&&handle.hasPointerCapture(pointerId))try{handle.releasePointerCapture(pointerId);}catch(_e){}global.removeEventListener('pointermove',move,true);global.removeEventListener('pointerup',up,true);global.removeEventListener('pointercancel',up,true);gridRefreshHeader(head,columns);notify('resize');}global.addEventListener('pointermove',move,true);global.addEventListener('pointerup',up,true);global.addEventListener('pointercancel',up,true);});
      var drag=null,longPress=0;
      cell.addEventListener('click',function(e){if(cell.__weigSuppressSort){cell.__weigSuppressSort=false;e.preventDefault();e.stopImmediatePropagation();}},true);
      cell.addEventListener('pointerdown',function(e){if((e.pointerType!=='touch'&&e.button!==0)||(e.target&&e.target.closest&&e.target.closest('.col-resize')))return;drag={id:e.pointerId,key:cell.dataset.key,startX:e.clientX,startY:e.clientY,active:false,armed:e.pointerType!=='touch',target:null,before:true};if(drag.armed&&cell.setPointerCapture)cell.setPointerCapture(e.pointerId);if(e.pointerType==='touch'){clearTimeout(longPress);longPress=setTimeout(function(){if(!drag||drag.id!==e.pointerId)return;drag.armed=true;drag.active=true;cell.classList.add('is-column-dragging');if(cell.setPointerCapture)try{cell.setPointerCapture(e.pointerId);}catch(_e){}},280);}});
      cell.addEventListener('pointermove',function(e){if(!drag||drag.id!==e.pointerId)return;var distance=Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY);if(!drag.armed){if(distance>8){clearTimeout(longPress);drag=null;}return;}if(!drag.active){if(distance<7)return;drag.active=true;cell.classList.add('is-column-dragging');}e.preventDefault();autoScroll(e.clientX);clearDrop();cell.style.opacity='.56';cell.classList.add('is-column-dragging');var hit=document.elementFromPoint(e.clientX,e.clientY),target=hit&&hit.closest&&hit.closest('.grid-head-cell');if(!target||target.parentElement!==head||target===cell){drag.target=null;return;}drag.target=target.dataset.key;drag.before=e.clientX<target.getBoundingClientRect().left+target.getBoundingClientRect().width/2;target.style.boxShadow=drag.before?'inset 2px 0 var(--accent-primary)':'inset -2px 0 var(--accent-primary)';});
      function finish(e){clearTimeout(longPress);if(!drag||drag.id!==e.pointerId)return;var state=drag;drag=null;if(cell.hasPointerCapture&&cell.hasPointerCapture(e.pointerId))cell.releasePointerCapture(e.pointerId);clearDrop();if(state.active){cell.__weigSuppressSort=true;if(state.target)commitReorder(state.key,state.target,state.before);}}
      cell.addEventListener('pointerup',finish);cell.addEventListener('pointercancel',finish);
    });
    gridRefreshHeader(head,columns);return columns;
  }
  W.DataGridHeader={graphemes:gridGraphemes,createCell:gridCreateHeaderCell,render:gridRenderHeader,refresh:gridRefreshHeader,fit:gridFitHeaderCell,hardMin:gridColumnHardMin,bind:gridBindHeader};
  W.ColumnInteraction={attach:gridBindHeader};
  W.DataGrid={defaults:[],align:gridColumnAlign,_suppressVirtualRender:false,hardMin:gridColumnHardMin,load:function(cfg){var saved=cfg.columns;if(!Array.isArray(saved)||!saved.length)return this.defaults.slice(0,7).map(function(c){return Object.assign({},c);});var all={};this.defaults.forEach(function(c){all[c.key]=c;});return saved.filter(function(c){return all[c.key];}).map(function(c){return Object.assign({},all[c.key],c);});},save:function(cfg,cols){cfg.columns=cols.map(function(c){return {key:c.key,width:c.width};});W.Config.save(cfg);},template:function(cols){return cols.map(function(c){return Math.max(gridColumnHardMin(c),c.width||100)+'px';}).join(' ');},addResizeHandles:gridBindHeader};
})(window);
