(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{};
  if(W.DialogRuntime)return;
  var openDialogs=new Set(),dragState=null;
  function node(target){return typeof target==='string'?document.getElementById(target):target;}
  function mobile(){return !!(global.matchMedia&&global.matchMedia('(max-width:820px)').matches);}
  function viewport(){var v=global.visualViewport;return{left:v?v.offsetLeft:0,top:v?v.offsetTop:0,width:v?v.width:document.documentElement.clientWidth,height:v?v.height:document.documentElement.clientHeight};}
  function options(dialog,next){dialog.__weigDialogOptions=Object.assign({draggable:true,backdropClose:true,escapeClose:true,removeOnClose:false},dialog.__weigDialogOptions||{},next||{});if(dialog&&dialog.dataset)dialog.dataset.dialogDraggable=dialog.__weigDialogOptions.draggable===false?'0':'1';return dialog.__weigDialogOptions;}
  function syncViewportBudget(dialog){if(!dialog||!dialog.style)return null;var v=viewport(),height=Math.max(1,Number(v.height)||1),width=Math.max(1,Number(v.width)||1);dialog.style.setProperty('--dialog-visual-viewport-height',height+'px');dialog.style.setProperty('--dialog-visual-viewport-width',width+'px');return{height:height,width:width};}
  function reset(dialog){if(!dialog)return;dialog.style.removeProperty('left');dialog.style.removeProperty('top');dialog.style.removeProperty('margin');dialog.style.removeProperty('position');dialog.dataset.dialogDragged='0';}
  function guardOpener(dialog){if(!dialog||dialog.__weigDialogOpenerGuard)return;var opener=dialog.__weigDialogOpener;if(!opener||!opener.isConnected||!('inert' in opener))return;var wasInert=!!opener.inert;dialog.__weigDialogOpenerGuard={opener:opener,wasInert:wasInert};if(!wasInert)opener.inert=true;}
  function restoreOpener(dialog){if(!dialog)return;var guard=dialog.__weigDialogOpenerGuard;dialog.__weigDialogOpenerGuard=null;var opener=dialog.__weigDialogOpener;dialog.__weigDialogOpener=null;if(guard&&guard.opener===opener&&!guard.wasInert&&opener&&opener.isConnected)opener.inert=false;if(opener&&opener.isConnected&&(!guard||!guard.wasInert)&&typeof opener.focus==='function')try{opener.focus({preventScroll:true});}catch(_e){try{opener.focus();}catch(_e2){}}}
  function captureOpenerScroll(opener){var out=[],seen=new Set(),current=opener&&opener.parentElement;while(current){if(!seen.has(current)&&(current.scrollTop||current.scrollLeft||current.scrollHeight>current.clientHeight+1||current.scrollWidth>current.clientWidth+1)){seen.add(current);out.push({node:current,top:current.scrollTop,left:current.scrollLeft});}current=current.parentElement;}var scrolling=document.scrollingElement;if(scrolling&&!seen.has(scrolling)){out.push({node:scrolling,top:scrolling.scrollTop,left:scrolling.scrollLeft});}return out;}
  function restoreOpenerScroll(dialog){var snapshot=dialog&&dialog.__weigDialogScrollSnapshot;dialog.__weigDialogScrollSnapshot=null;if(!snapshot||!snapshot.length)return;var restore=function(){snapshot.forEach(function(entry){var target=entry&&entry.node;if(!target||!target.isConnected)return;target.scrollTop=entry.top;target.scrollLeft=entry.left;});};restore();if(typeof global.queueMicrotask==='function')global.queueMicrotask(restore);else Promise.resolve().then(restore);if(typeof global.requestAnimationFrame==='function')global.requestAnimationFrame(restore);}
  function clamp(dialog,left,top){if(!dialog||!dialog.open)return null;if(mobile()){reset(dialog);return null;}var v=viewport(),pad=8,rect=dialog.getBoundingClientRect(),width=Math.min(rect.width,Math.max(1,v.width-pad*2)),height=Math.min(rect.height,Math.max(1,v.height-pad*2)),x=Math.min(Math.max(v.left+pad,Number(left)),v.left+v.width-pad-width),y=Math.min(Math.max(v.top+pad,Number(top)),v.top+v.height-pad-height);dialog.style.position='fixed';dialog.style.margin='0';dialog.style.left=Math.round(x)+'px';dialog.style.top=Math.round(y)+'px';dialog.dataset.dialogDragged='1';return{x:x,y:y};}
  function stopDrag(){if(!dragState)return;var state=dragState;dragState=null;global.removeEventListener('pointermove',state.move,true);global.removeEventListener('pointerup',state.finish,true);global.removeEventListener('pointercancel',state.finish,true);}
  function startDrag(dialog,event){var opts=options(dialog);if(!opts.draggable||mobile()||event.button!==0||!event.target||!event.target.closest)return;if(event.target.closest('button,input,textarea,select,a,[role="button"],[contenteditable="true"]'))return;var explicit=event.target.closest('[data-dialog-drag-handle]'),head=event.target.closest('.dialog__head,.workspace__header');if(!head||!dialog.contains(head)||(!explicit&&event.target!==head)||(explicit&&!dialog.contains(explicit)))return;event.preventDefault();var rect=dialog.getBoundingClientRect(),pointerId=event.pointerId,dx=event.clientX-rect.left,dy=event.clientY-rect.top;stopDrag();function move(e){if(e.pointerId!==pointerId)return;e.preventDefault();clamp(dialog,e.clientX-dx,e.clientY-dy);}function finish(e){if(e.pointerId!==pointerId)return;stopDrag();}dragState={dialog:dialog,move:move,finish:finish};global.addEventListener('pointermove',move,true);global.addEventListener('pointerup',finish,true);global.addEventListener('pointercancel',finish,true);}
  function adopt(target,next){var dialog=node(target);if(!dialog||String(dialog.tagName||'').toLowerCase()!=='dialog')return null;options(dialog,next);dialog.dataset.dialogRuntime='1';if(dialog.__weigDialogRuntimeBound)return dialog;dialog.__weigDialogRuntimeBound=true;
    dialog.addEventListener('pointerdown',function(event){startDrag(dialog,event);});
    dialog.addEventListener('submit',function(event){var form=event&&event.target;if(!form||String(form.method||'').toLowerCase()!=='dialog')return;guardOpener(dialog);if(W.SurfaceTransition&&W.SurfaceTransition.capture)dialog.__weigSurfaceCloseSnapshot=W.SurfaceTransition.capture(dialog);});
    dialog.addEventListener('cancel',function(event){if(event.target!==dialog)return;var opts=options(dialog);if(opts.escapeClose===false){event.preventDefault();return;}event.preventDefault();close(dialog,'escape');});
    dialog.addEventListener('click',function(event){var opts=options(dialog);if(event.target!==dialog||opts.backdropClose===false||!mobile())return;close(dialog,'backdrop');});
    dialog.addEventListener('dblclick',function(event){var opts=options(dialog);if(event.target!==dialog||opts.backdropClose===false||mobile()||event.button!==0)return;close(dialog,'backdrop');});
    dialog.addEventListener('close',function(){openDialogs.delete(dialog);stopDrag();var snapshot=dialog.__weigSurfaceCloseSnapshot;dialog.__weigSurfaceCloseSnapshot=null;reset(dialog);restoreOpener(dialog);restoreOpenerScroll(dialog);if(options(dialog).removeOnClose===true&&dialog.isConnected)dialog.remove();if(snapshot&&W.SurfaceTransition&&W.SurfaceTransition.exitSnapshot)W.SurfaceTransition.exitSnapshot(snapshot,'dialog');});
    return dialog;
  }
  function create(opts){opts=opts||{};var dialog=opts.id&&document.getElementById(opts.id);if(!dialog){dialog=document.createElement('dialog');if(opts.id)dialog.id=opts.id;if(opts.className)dialog.className=opts.className;document.body.appendChild(dialog);}else if(opts.className&&!dialog.className)dialog.className=opts.className;return adopt(dialog,opts);}
  function open(target,next){var dialog=adopt(target,next);if(!dialog)return null;options(dialog,next);syncViewportBudget(dialog);if(W.LayoutRuntime&&typeof W.LayoutRuntime.normalizeDialogs==='function')W.LayoutRuntime.normalizeDialogs(dialog);var wasOpen=dialog.open;if(!wasOpen){dialog.__weigDialogOpener=document.activeElement;dialog.__weigDialogScrollSnapshot=captureOpenerScroll(dialog.__weigDialogOpener);dialog.showModal();}openDialogs.add(dialog);if(mobile())reset(dialog);else if(dialog.dataset.dialogDragged==='1'){var r=dialog.getBoundingClientRect();clamp(dialog,r.left,r.top);}if(!wasOpen&&W.SurfaceTransition&&W.SurfaceTransition.enter)W.SurfaceTransition.enter(dialog,'dialog');var focus=next&&next.focus;if(focus){requestAnimationFrame(function(){var item=typeof focus==='string'?dialog.querySelector(focus):focus;if(item&&typeof item.focus==='function')item.focus();});}return dialog;}
  function close(target,reason){var dialog=node(target);if(!dialog)return false;if(dialog.open){guardOpener(dialog);if(W.SurfaceTransition&&W.SurfaceTransition.capture)dialog.__weigSurfaceCloseSnapshot=W.SurfaceTransition.capture(dialog);dialog.close(reason||'');}else if(options(dialog).removeOnClose===true&&dialog.isConnected)dialog.remove();return true;}
  function remove(target){var dialog=node(target);if(!dialog)return false;options(dialog,{removeOnClose:false});if(dialog.open){guardOpener(dialog);if(W.SurfaceTransition&&W.SurfaceTransition.capture)dialog.__weigSurfaceCloseSnapshot=W.SurfaceTransition.capture(dialog);dialog.close();}openDialogs.delete(dialog);dialog.remove();return true;}
  function normalizeOpen(){openDialogs.forEach(function(dialog){if(!dialog.open){openDialogs.delete(dialog);return;}syncViewportBudget(dialog);if(mobile())reset(dialog);else if(dialog.dataset.dialogDragged==='1'){var r=dialog.getBoundingClientRect();clamp(dialog,r.left,r.top);}});}
  global.addEventListener('resize',normalizeOpen,{passive:true});if(global.visualViewport){global.visualViewport.addEventListener('resize',normalizeOpen,{passive:true});global.visualViewport.addEventListener('scroll',normalizeOpen,{passive:true});}
  W.DialogRuntime={create:create,adopt:adopt,open:open,close:close,remove:remove,clamp:clamp,reset:reset,active:function(){return Array.from(openDialogs).filter(function(dialog){return dialog.open;});}};
})(window);
