(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{};
  if(W.DialogRuntime)return;
  var openDialogs=new Set(),dragState=null;
  function node(target){return typeof target==='string'?document.getElementById(target):target;}
  function mobile(){return !!(global.matchMedia&&global.matchMedia('(max-width:820px)').matches);}
  function viewport(){var v=global.visualViewport;return{left:v?v.offsetLeft:0,top:v?v.offsetTop:0,width:v?v.width:document.documentElement.clientWidth,height:v?v.height:document.documentElement.clientHeight};}
  function options(dialog,next){dialog.__weigDialogOptions=Object.assign({draggable:false,backdropClose:true,escapeClose:true,removeOnClose:false},dialog.__weigDialogOptions||{},next||{});return dialog.__weigDialogOptions;}
  function reset(dialog){if(!dialog)return;dialog.style.removeProperty('left');dialog.style.removeProperty('top');dialog.style.removeProperty('margin');dialog.style.removeProperty('position');dialog.dataset.dialogDragged='0';}
  function clamp(dialog,left,top){if(!dialog||!dialog.open)return null;if(mobile()){reset(dialog);return null;}var v=viewport(),pad=8,rect=dialog.getBoundingClientRect(),width=Math.min(rect.width,Math.max(1,v.width-pad*2)),height=Math.min(rect.height,Math.max(1,v.height-pad*2)),x=Math.min(Math.max(v.left+pad,Number(left)),v.left+v.width-pad-width),y=Math.min(Math.max(v.top+pad,Number(top)),v.top+v.height-pad-height);dialog.style.position='fixed';dialog.style.margin='0';dialog.style.left=Math.round(x)+'px';dialog.style.top=Math.round(y)+'px';dialog.dataset.dialogDragged='1';return{x:x,y:y};}
  function stopDrag(){if(!dragState)return;var state=dragState;dragState=null;global.removeEventListener('pointermove',state.move,true);global.removeEventListener('pointerup',state.finish,true);global.removeEventListener('pointercancel',state.finish,true);}
  function startDrag(dialog,event){var opts=options(dialog);if(!opts.draggable||mobile()||event.button!==0)return;var head=event.target&&event.target.closest&&event.target.closest('.dialog__head,.workspace__header');if(!head||!dialog.contains(head)||event.target.closest('button,input,textarea,select,a,[role="button"]'))return;event.preventDefault();var rect=dialog.getBoundingClientRect(),pointerId=event.pointerId,dx=event.clientX-rect.left,dy=event.clientY-rect.top;stopDrag();function move(e){if(e.pointerId!==pointerId)return;e.preventDefault();clamp(dialog,e.clientX-dx,e.clientY-dy);}function finish(e){if(e.pointerId!==pointerId)return;stopDrag();}dragState={dialog:dialog,move:move,finish:finish};global.addEventListener('pointermove',move,true);global.addEventListener('pointerup',finish,true);global.addEventListener('pointercancel',finish,true);}
  function adopt(target,next){var dialog=node(target);if(!dialog||String(dialog.tagName||'').toLowerCase()!=='dialog')return null;options(dialog,next);dialog.dataset.dialogRuntime='1';if(dialog.__weigDialogRuntimeBound)return dialog;dialog.__weigDialogRuntimeBound=true;
    dialog.addEventListener('pointerdown',function(event){startDrag(dialog,event);});
    dialog.addEventListener('cancel',function(event){var opts=options(dialog);if(opts.escapeClose===false){event.preventDefault();return;}event.preventDefault();close(dialog,'escape');});
    dialog.addEventListener('dblclick',function(event){var opts=options(dialog);if(event.target!==dialog||opts.backdropClose===false)return;close(dialog,'backdrop');});
    dialog.addEventListener('close',function(){openDialogs.delete(dialog);stopDrag();reset(dialog);var opener=dialog.__weigDialogOpener;dialog.__weigDialogOpener=null;if(options(dialog).removeOnClose===true&&dialog.isConnected)dialog.remove();if(opener&&opener.isConnected&&typeof opener.focus==='function')try{opener.focus();}catch(_e){}});
    return dialog;
  }
  function create(opts){opts=opts||{};var dialog=opts.id&&document.getElementById(opts.id);if(!dialog){dialog=document.createElement('dialog');if(opts.id)dialog.id=opts.id;if(opts.className)dialog.className=opts.className;document.body.appendChild(dialog);}else if(opts.className&&!dialog.className)dialog.className=opts.className;return adopt(dialog,opts);}
  function open(target,next){var dialog=adopt(target,next);if(!dialog)return null;options(dialog,next);if(W.LayoutRuntime&&typeof W.LayoutRuntime.normalizeDialogs==='function')W.LayoutRuntime.normalizeDialogs(dialog);if(!dialog.open){dialog.__weigDialogOpener=document.activeElement;dialog.showModal();}openDialogs.add(dialog);if(mobile())reset(dialog);else if(dialog.dataset.dialogDragged==='1'){var r=dialog.getBoundingClientRect();clamp(dialog,r.left,r.top);}var focus=next&&next.focus;if(focus){requestAnimationFrame(function(){var item=typeof focus==='string'?dialog.querySelector(focus):focus;if(item&&typeof item.focus==='function')item.focus();});}return dialog;}
  function close(target,reason){var dialog=node(target);if(!dialog)return false;if(dialog.open)dialog.close(reason||'');else if(options(dialog).removeOnClose===true&&dialog.isConnected)dialog.remove();return true;}
  function remove(target){var dialog=node(target);if(!dialog)return false;options(dialog,{removeOnClose:false});if(dialog.open)dialog.close();openDialogs.delete(dialog);dialog.remove();return true;}
  function normalizeOpen(){openDialogs.forEach(function(dialog){if(!dialog.open){openDialogs.delete(dialog);return;}if(mobile())reset(dialog);else if(dialog.dataset.dialogDragged==='1'){var r=dialog.getBoundingClientRect();clamp(dialog,r.left,r.top);}});}
  global.addEventListener('resize',normalizeOpen,{passive:true});if(global.visualViewport){global.visualViewport.addEventListener('resize',normalizeOpen,{passive:true});global.visualViewport.addEventListener('scroll',normalizeOpen,{passive:true});}
  W.DialogRuntime={create:create,adopt:adopt,open:open,close:close,remove:remove,clamp:clamp,reset:reset,active:function(){return Array.from(openDialogs).filter(function(dialog){return dialog.open;});}};
})(window);
