(function(global){
  'use strict';
  var W=global.WeiG,C=W&&W.Components;
  if(!W||!C||C.__floatingSelect)return;C.__floatingSelect=true;
  var root=null,active=null,contextMenu=null,preview=null,previewPersistent=false,previewTimer=0,measureCanvas=null;
  function layer(){if(root&&root.isConnected)return root;root=document.getElementById('weig-floating-layer');if(!root){root=document.createElement('div');root.id='weig-floating-layer';root.className='weig-floating-layer';root.setAttribute('aria-live','off');document.body.appendChild(root);}return root;}
  function modalLayer(owner){var dialog=owner&&owner.closest?owner.closest('dialog[open]'):null;if(!dialog)return null;var host=null;for(var i=0;i<dialog.children.length;i++){var child=dialog.children[i];if(child&&child.classList&&child.classList.contains('weig-floating-layer')&&child.dataset.uiModalLayer==='1'){host=child;break;}}if(!host){host=document.createElement('div');host.className='weig-floating-layer weig-floating-layer--dialog';host.dataset.uiModalLayer='1';host.setAttribute('aria-live','off');dialog.appendChild(host);}return host;}
  function selectLayer(owner){return modalLayer(owner)||layer();}
  function normalizeOptions(input){return (input||[]).map(function(x){return typeof x==='string'?{value:x,label:x,disabled:false}:{value:String(x.value),label:String(x.label==null?x.value:x.label),disabled:x.disabled===true};});}
  function decorateCapability(node){if(W.CapabilityRegistry&&W.CapabilityRegistry.decorateMatching)W.CapabilityRegistry.decorateMatching(node);return node;}
  function nativeControl(opts,items,value){var w=document.createElement('span'),select=document.createElement('select');w.className='ui-select ui-select--native'+(opts.className?' '+opts.className:'');w.dataset.uiSelect='1';w.dataset.uiSelectMode='native';if(opts.id)w.id=opts.id;select.className='ui-select__native';if(opts.ariaLabel)select.setAttribute('aria-label',opts.ariaLabel);w.appendChild(select);function render(){select.textContent='';items.forEach(function(item){var option=document.createElement('option');option.value=item.value;option.textContent=item.label;option.disabled=!!item.disabled;select.appendChild(option);});select.value=value;select.disabled=!!opts.disabled;}function setValue(next,notify){value=String(next==null?'':next);select.value=value;if(notify&&typeof opts.onChange==='function')opts.onChange(value);}select.addEventListener('mousedown',function(e){if(typeof opts.onOpen==='function'&&opts.onOpen(value,w)===false){e.preventDefault();e.stopPropagation();}});select.addEventListener('change',function(){setValue(select.value,true);});w.setValue=function(v){setValue(v,false);};w.getValue=function(){return value;};w.setOptions=function(next){items=normalizeOptions(next);render();};w.setDisabled=function(v){opts.disabled=!!v;render();};render();return decorateCapability(w);}
  function viewport(){var v=global.visualViewport;return{left:v?v.offsetLeft:0,top:v?v.offsetTop:0,width:v?v.width:document.documentElement.clientWidth,height:v?v.height:document.documentElement.clientHeight};}
  function pointRect(x,y){x=Number(x)||0;y=Number(y)||0;return{left:x,right:x,top:y,bottom:y,width:0,height:0};}function measureText(text,node){if(!measureCanvas)measureCanvas=document.createElement('canvas');var ctx=measureCanvas.getContext&&measureCanvas.getContext('2d'),style=node&&global.getComputedStyle?global.getComputedStyle(node):null;if(!ctx)return String(text||'').length*8;if(style)ctx.font=[style.fontStyle,style.fontVariant,style.fontWeight,style.fontSize,style.fontFamily].filter(Boolean).join(' ');return ctx.measureText(String(text||'')).width;}function cssPx(style,name){var value=style?parseFloat(style[name]):0;return Number.isFinite(value)?value:0;}function horizontalBox(style){return cssPx(style,'paddingLeft')+cssPx(style,'paddingRight')+cssPx(style,'borderLeftWidth')+cssPx(style,'borderRightWidth');}function pseudoWidth(option,style){if(!global.getComputedStyle)return 0;var before=global.getComputedStyle(option,'::before'),content=before&&String(before.content||'');if(!before||content==='none'||content==='normal'||content==='""')return 0;var width=cssPx(before,'width');if(!width||!Number.isFinite(width)){content=content.replace(/^['"]|['"]$/g,'');width=measureText(content,option);}return width+cssPx(before,'marginLeft')+cssPx(before,'marginRight')+cssPx(style,'columnGap');}function intrinsicMenuWidth(menu){if(menu.__uiIntrinsicWidth>0)return menu.__uiIntrinsicWidth;var list=menu.querySelector('.ui-select__options'),menuStyle=global.getComputedStyle?global.getComputedStyle(menu):null,listStyle=list&&global.getComputedStyle?global.getComputedStyle(list):null,gutter=list?Math.max(0,(list.offsetWidth||0)-(list.clientWidth||0)):0,outer=horizontalBox(menuStyle)+horizontalBox(listStyle)+gutter,natural=0;Array.from(menu.querySelectorAll('.ui-select__option')).forEach(function(option){var label=option.querySelector('.ui-select__option-label'),optionStyle=global.getComputedStyle?global.getComputedStyle(option):null,text=label?Math.ceil(measureText(label.textContent,label)):0;natural=Math.max(natural,text+horizontalBox(optionStyle)+pseudoWidth(option,optionStyle));});menu.__uiIntrinsicWidth=Math.ceil(natural+outer);return menu.__uiIntrinsicWidth;}
  function boundaryRect(owner){var v=viewport(),base={left:v.left,top:v.top,right:v.left+v.width,bottom:v.top+v.height,width:v.width,height:v.height},dialog=owner&&owner.closest?owner.closest('dialog[open]'):null;if(!dialog)return base;var r=dialog.getBoundingClientRect(),left=Math.max(base.left,r.left),top=Math.max(base.top,r.top),right=Math.min(base.right,r.right),bottom=Math.min(base.bottom,r.bottom);if(right<=left||bottom<=top)return base;return{left:left,top:top,right:right,bottom:bottom,width:right-left,height:bottom-top};}
  function setViewportPosition(menu,left,top){var host=menu&&menu.parentElement,modal=!!(host&&host.dataset&&host.dataset.uiModalLayer==='1');if(modal){var origin=host.getBoundingClientRect();menu.style.left=(left-origin.left)+'px';menu.style.top=(top-origin.top)+'px';}else{menu.style.left=left+'px';menu.style.top=top+'px';}return menu.getBoundingClientRect();}
  function placeBounded(menu,anchor,opts){opts=opts||{};if(!menu||menu.hidden)return null;var v=viewport(),boundary=opts.boundary||{left:v.left,top:v.top,right:v.left+v.width,bottom:v.top+v.height,width:v.width,height:v.height},pad=opts.pad==null?8:Number(opts.pad),gap=opts.gap==null?7:Number(opts.gap),leftBound=Math.max(v.left,Number(boundary.left)),topBound=Math.max(v.top,Number(boundary.top)),rightBound=Math.min(v.left+v.width,Number(boundary.right)),bottomBound=Math.min(v.top+v.height,Number(boundary.bottom)),innerW=Math.max(1,rightBound-leftBound-pad*2),innerH=Math.max(1,bottomBound-topBound-pad*2),minW=Math.min(Math.max(1,Number(opts.minWidth)||160),innerW),maxW=Math.max(minW,innerW);menu.style.visibility='hidden';menu.style.left='0px';menu.style.top='0px';menu.style.maxHeight='';if(opts.width!=null){var requested=Math.min(maxW,Math.max(minW,Number(opts.width)||minW))+'px';menu.style.width=requested;menu.style.inlineSize=requested;}var measuredW=menu.offsetWidth||Number(opts.width)||minW,desiredW=Math.min(maxW,Math.max(minW,measuredW)),naturalH=menu.scrollHeight||menu.offsetHeight||120,heightCap=Math.max(1,Math.min(innerH,Math.max(96,Math.floor(v.height*(v.width<=820?.84:.68))))),desiredH=Math.min(naturalH,heightCap),spaces={bottom:Math.max(0,bottomBound-pad-anchor.bottom-gap),top:Math.max(0,anchor.top-gap-(topBound+pad)),right:Math.max(0,rightBound-pad-anchor.right-gap),left:Math.max(0,anchor.left-gap-(leftBound+pad))},order=Array.isArray(opts.placements)&&opts.placements.length?opts.placements:(opts.preferDown===false?['top','bottom','right','left']:['bottom','top','right','left']),placement='';function full(side){return side==='bottom'||side==='top'?spaces[side]>=desiredH:spaces[side]>=desiredW;}for(var i=0;i<order.length;i++){if(full(order[i])){placement=order[i];break;}}if(!placement){placement=order[0]||'bottom';var best=-1;order.forEach(function(side){var score=(side==='bottom'||side==='top')?Math.min(spaces[side],desiredH)*desiredW:Math.min(spaces[side],desiredW)*desiredH;if(score>best){best=score;placement=side;}});}var width=desiredW,maxH=heightCap;if(placement==='left'||placement==='right')width=Math.max(1,Math.min(desiredW,spaces[placement]));else maxH=Math.max(1,Math.min(heightCap,spaces[placement]));menu.style.width=width+'px';menu.style.inlineSize=width+'px';menu.style.maxHeight=maxH+'px';var h=Math.min(menu.offsetHeight||naturalH,maxH),left,top;if(placement==='right'){left=anchor.right+gap;top=anchor.top;}else if(placement==='left'){left=anchor.left-gap-width;top=anchor.top;}else{left=anchor.left;top=placement==='bottom'?anchor.bottom+gap:anchor.top-gap-h;}left=Math.min(Math.max(leftBound+pad,left),rightBound-pad-width);top=Math.min(Math.max(topBound+pad,top),bottomBound-pad-h);setViewportPosition(menu,left,top);menu.style.visibility='visible';menu.dataset.placement=placement;return{left:left,top:top,width:width,height:h,maxHeight:maxH,placement:placement,boundary:boundary};}
  function place(w){if(!w||!w.__uiMenu||w.__uiMenu.hidden)return;var t=w.__uiTrigger,m=w.__uiMenu,r=t.getBoundingClientRect(),v=viewport(),boundary=boundaryRect(w),pad=8,viewportMax=Math.max(160,v.width-pad*2),desktopMax=v.width>820?Math.max(160,Math.floor(v.width*.5)):viewportMax,boundaryMax=Math.max(1,boundary.width-pad*2),maxW=Math.min(viewportMax,desktopMax,boundaryMax),scrollNode=m.querySelector('.ui-select__options'),savedScroll=scrollNode?scrollNode.scrollTop:0,natural=intrinsicMenuWidth(m),desired=Math.max(r.width,w.__preferredWidth||160,natural),width=Math.min(maxW,desired);placeBounded(m,r,{width:width,minWidth:Math.min(160,boundaryMax),pad:pad,gap:7,preferDown:true,boundary:boundary,placements:['bottom','top','right','left']});if(scrollNode&&savedScroll>0){var maxScroll=Math.max(0,scrollNode.scrollHeight-scrollNode.clientHeight);scrollNode.scrollTop=Math.min(savedScroll,maxScroll);}}
  function close(w,focus){if(!w||!w.__uiMenu||w.__uiMenu.hidden)return false;w.__uiMenu.hidden=true;w.__uiMenu.remove();w.classList.remove('is-open');w.__uiTrigger.setAttribute('aria-expanded','false');if(active===w)active=null;if(focus)w.__uiTrigger.focus();return true;}
  function closeContextMenu(){if(!contextMenu)return false;var menu=contextMenu;contextMenu=null;menu.remove();return true;}
  function cancelPreviewTimer(){if(previewTimer){clearTimeout(previewTimer);previewTimer=0;}}
  function closePreview(force){cancelPreviewTimer();if(!preview)return false;if(previewPersistent&&!force)return false;var node=preview;preview=null;previewPersistent=false;node.remove();return true;}
  function previewOverflowing(option){var label=option&&option.querySelector?option.querySelector('.ui-select__option-label'):null;return !!(label&&label.scrollWidth>label.clientWidth+1);}
  function showTextPreview(anchor,text,persistent,force){cancelPreviewTimer();text=String(text||'');if(!anchor||!anchor.isConnected||!text){if(!persistent)closePreview(false);return false;}if(!force&&!(anchor.scrollWidth>anchor.clientWidth+1)){if(!persistent)closePreview(false);return false;}if(preview)preview.remove();var node=document.createElement('div'),v=viewport(),cap=Math.max(120,Math.min(v.width-16,v.width>820?Math.floor(v.width*.5):Math.floor(v.width*.88))),desired=Math.ceil(measureText(text,anchor))+28,width=Math.max(120,Math.min(cap,desired));node.className='ui-floating-preview surface surface--floating';node.textContent=text;node.dataset.persistent=persistent?'1':'0';node.setAttribute('role','note');node.tabIndex=0;node.addEventListener('mouseenter',cancelPreviewTimer);node.addEventListener('mouseleave',function(){if(!previewPersistent){previewTimer=setTimeout(function(){closePreview(false);},120);}});node.addEventListener('click',function(e){e.stopPropagation();});node.addEventListener('contextmenu',function(e){e.stopPropagation();});layer().appendChild(node);preview=node;previewPersistent=!!persistent;placeBounded(node,anchor.getBoundingClientRect(),{width:width,minWidth:Math.min(120,width),pad:8,gap:6,preferDown:true});if(previewPersistent)node.focus({preventScroll:true});return true;}
  function showPreview(option,persistent){cancelPreviewTimer();if(!option||!option.isConnected||!previewOverflowing(option)){if(!persistent)closePreview(false);return false;}var label=option.querySelector('.ui-select__option-label'),text=String(option.dataset.fullLabel||label.textContent||'');return showTextPreview(option,text,persistent,true);}
  function schedulePreviewClose(){cancelPreviewTimer();if(previewPersistent)return;previewTimer=setTimeout(function(){closePreview(false);},120);}
  function placeContextMenu(menu,x,y){var r=pointRect(x,y),width=Math.max(160,menu.offsetWidth||180);return placeBounded(menu,r,{width:width,minWidth:160,pad:8,gap:4,preferDown:true});}
  function internalMenuScroll(e){return !!((active&&active.__uiMenu&&e&&e.target&&active.__uiMenu.contains(e.target))||(contextMenu&&e&&e.target&&contextMenu.contains(e.target)));}
  C.closeSelects=function(focus){var closed=close(active,focus!==false);return closeContextMenu()||closed;};
  C.closeContextMenu=closeContextMenu;
  C.showTextPreview=function(anchor,text,opts){opts=opts||{};return showTextPreview(anchor,text,opts.persistent!==false,opts.force===true);};
  C.closeTextPreview=function(){return closePreview(true);};
  C.openContextMenu=function(opts){opts=opts||{};var items=(opts.items||[]).filter(function(item){return item&&item.hidden!==true;});if(!items.length)return false;if(active)close(active,false);closeContextMenu();var menu=document.createElement('div');menu.className='ui-select__menu ui-context-menu surface surface--floating';menu.setAttribute('role','menu');var list=document.createElement('div');list.className='ui-select__options';items.forEach(function(item){var button=document.createElement('button');button.type='button';button.className='ui-select__option';button.setAttribute('role','menuitem');button.textContent=String(item.label||item.key||'');button.disabled=!!item.disabled;button.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();if(button.disabled)return;closeContextMenu();if(typeof item.onSelect==='function')item.onSelect(item);});list.appendChild(button);});menu.appendChild(list);layer().appendChild(menu);contextMenu=menu;requestAnimationFrame(function(){if(contextMenu===menu){placeContextMenu(menu,opts.x,opts.y);var first=menu.querySelector('.ui-select__option:not(:disabled)');if(first)first.focus();}});return true;};
  C.selectControl=function(opts){
    opts=opts||{};var items=normalizeOptions(opts.options),value=String(opts.value==null?'':opts.value);if(opts.native===true)return nativeControl(opts,items,value);var w=document.createElement('div');w.className='ui-select ui-select--intrinsic'+(opts.stretch?' ui-select--stretch':'')+(opts.className?' '+opts.className:'');w.dataset.uiSelect='1';w.dataset.uiSelectMode='floating';w.dataset.uiSelectTrigger=opts.triggerMode==='prefix'?'prefix':'value';if(opts.id)w.id=opts.id;
    var t=document.createElement('button');t.type='button';t.className='ui-select__trigger';t.setAttribute('aria-haspopup','listbox');t.setAttribute('aria-expanded','false');if(opts.ariaLabel)t.setAttribute('aria-label',opts.ariaLabel);
    var prefix=document.createElement('span');prefix.className='ui-select__prefix'+(opts.prefixClassName?' '+opts.prefixClassName:'');if(opts.prefixNode&&opts.prefixNode.nodeType)prefix.appendChild(opts.prefixNode);else prefix.textContent=opts.prefix||'';prefix.hidden=!(opts.prefixNode||opts.prefix);var prefixOnly=opts.triggerMode==='prefix',val=null,ch=null;t.appendChild(prefix);if(!prefixOnly){val=document.createElement('span');val.className='ui-select__value';ch=document.createElement('span');ch.className='ui-select__chevron';ch.setAttribute('aria-hidden','true');ch.textContent='▾';t.append(val,ch);}w.appendChild(t);
    var m=document.createElement('div');m.className='ui-select__menu surface surface--floating';m.setAttribute('role','listbox');m.hidden=true;var search=null,list=document.createElement('div');list.className='ui-select__options';m.appendChild(list);w.__uiMenu=m;w.__uiTrigger=t;w.__preferredWidth=opts.width||160;var filtered=[],index=-1,itemsSignature=optionSignature(items);
    function optionSignature(next){return next.map(function(item){return item.value+'\u0000'+item.label+'\u0000'+(item.disabled?'1':'0');}).join('\u0001');}function current(){var h=items.find(function(x){return x.value===value;});if(h)return h.label;if(typeof opts.formatValue==='function')return String(opts.formatValue(value));return opts.placeholder||value||'—';}
    function sync(){if(val)val.textContent=current();t.removeAttribute('title');if(opts.nativeTitle===true&&!opts.ariaLabel)t.setAttribute('aria-label',(opts.prefix?opts.prefix+' ':'')+current());t.disabled=!!opts.disabled;}
    function syncIntrinsic(){m.__uiIntrinsicWidth=0;if(!opts.width)w.__preferredWidth=160;}
    function syncSelection(){index=-1;Array.from(list.querySelectorAll('.ui-select__option')).forEach(function(button,i){var selected=button.dataset.value===value;button.setAttribute('aria-selected',selected?'true':'false');if(selected)index=i;});if(index<0&&filtered.length)index=0;}function render(q,preserveScroll){q=String(q||'').trim().toLocaleLowerCase();var saved=preserveScroll?list.scrollTop:0;filtered=items.filter(function(x){return !q||x.label.toLocaleLowerCase().includes(q)||x.value.toLocaleLowerCase().includes(q);});if(preview&&!previewPersistent)closePreview(true);list.textContent='';index=-1;filtered.forEach(function(item,i){var b=document.createElement('button'),label=document.createElement('span');b.type='button';b.className='ui-select__option';b.setAttribute('role','option');b.dataset.value=item.value;b.dataset.fullLabel=item.label;b.setAttribute('aria-selected',item.value===value?'true':'false');b.disabled=!!item.disabled;b.setAttribute('aria-disabled',b.disabled?'true':'false');label.className='ui-select__option-label';label.textContent=item.label;b.appendChild(label);b.addEventListener('mouseenter',function(){showPreview(b,false);});b.addEventListener('mouseleave',schedulePreviewClose);b.addEventListener('contextmenu',function(event){event.preventDefault();event.stopPropagation();showPreview(b,true);close(w,false);});b.onclick=function(){if(b.disabled)return;setValue(item.value,true);close(w,true);closePreview(true);};list.appendChild(b);if(item.value===value)index=i;});m.__uiIntrinsicWidth=0;if(index<0&&filtered.length)index=0;if(preserveScroll)list.scrollTop=Math.min(saved,Math.max(0,list.scrollHeight-list.clientHeight));}
    function numericSearchSpec(){var spec=opts.numericSearch;return spec&&typeof spec==='object'?spec:null;}function numericInputSpec(){var spec=opts.numericInput;return spec&&typeof spec==='object'?spec:null;}function numericMaxLength(spec){var max=Math.max(Math.abs(Number(spec&&spec.min)||0),Math.abs(Number(spec&&spec.max)||0));return Math.max(1,String(Math.floor(max)).length);}function cleanNumericInput(spec){var raw=String(search&&search.value||'').replace(/\D/g,'').slice(0,numericMaxLength(spec));if(search&&search.value!==raw)search.value=raw;return raw;}function commitNumericSearch(){var spec=numericSearchSpec();if(!spec||!search)return false;var raw=String(search.value||'').replace(/\D/g,'').slice(0,Math.max(1,Number(spec.pad)||2));if(!raw)return false;var number=Number(raw),min=Number(spec.min),max=Number(spec.max);if(!Number.isInteger(number)||!Number.isFinite(min)||!Number.isFinite(max)||number<min||number>max){search.setAttribute('aria-invalid','true');search.select();return false;}var next=String(number).padStart(Math.max(1,Number(spec.pad)||2),'0');if(!items.some(function(item){return item.value===next;})){search.setAttribute('aria-invalid','true');return false;}search.removeAttribute('aria-invalid');setValue(next,true);close(w,true);return true;}function commitNumericInput(){var spec=numericInputSpec();if(!spec||!search)return false;var raw=cleanNumericInput(spec),number=Number(raw),min=Number(spec.min),max=Number(spec.max);if(!raw||!Number.isInteger(number)||!Number.isFinite(min)||!Number.isFinite(max)||number<min||number>max){search.setAttribute('aria-invalid','true');search.select();return false;}search.removeAttribute('aria-invalid');setValue(String(number),true);close(w,true);return true;}function ensureSearch(){var numeric=numericSearchSpec(),numericInput=numericInputSpec(),numericSpec=numericInput||numeric;if(search||(!numericSpec&&!opts.searchable)||(!numericSpec&&items.length<(opts.searchThreshold||14)))return;search=document.createElement('input');search.type=numericSpec?'text':'search';search.className='ui-select__search'+(numericInput?' ui-select__numeric-input':'');search.placeholder=opts.searchPlaceholder||'Search…';search.setAttribute('aria-label',search.placeholder);if(numericSpec){search.inputMode='numeric';search.autocomplete='off';search.spellcheck=false;search.maxLength=numericInput?numericMaxLength(numericInput):Math.max(1,Number(numeric.pad)||2);w.dataset.uiSelectNumeric=numericInput?'input':'search';search.addEventListener('keydown',function(event){if(event.key==='Enter'){event.preventDefault();event.stopPropagation();if(numericInput)commitNumericInput();else commitNumericSearch();}});}search.oninput=function(){if(numericSpec){cleanNumericInput(numericSpec);search.removeAttribute('aria-invalid');if(numericInput){render('',true);place(w);return;}}render(search.value);place(w);};m.insertBefore(search,list);}
    function focusIndex(i){var bs=Array.from(list.querySelectorAll('.ui-select__option'));if(!bs.length)return;index=Math.max(0,Math.min(bs.length-1,i));bs[index].focus();bs[index].scrollIntoView({block:'nearest'});}
    function keys(e){if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close(w,true);}else if(e.key==='ArrowDown'){e.preventDefault();focusIndex(index+1);}else if(e.key==='ArrowUp'){e.preventDefault();focusIndex(index-1);}else if(e.key==='Home'){e.preventDefault();focusIndex(0);}else if(e.key==='End'){e.preventDefault();focusIndex(filtered.length-1);}}
    function open(){if(t.disabled)return;if(typeof opts.onOpen==='function'&&opts.onOpen(value,w)===false)return;if(active&&active!==w)close(active,false);closeContextMenu();ensureSearch();var numericInput=numericInputSpec();if(search&&numericSearchSpec()){search.value='';search.removeAttribute('aria-invalid');}if(search&&numericInput){search.value=typeof numericInput.inputValue==='function'?String(numericInput.inputValue(value)||''):(/^\d+$/.test(value)?value:'');search.removeAttribute('aria-invalid');}render(search&&(numericInput?'':search.value));selectLayer(w).appendChild(m);m.hidden=false;w.classList.add('is-open');t.setAttribute('aria-expanded','true');active=w;place(w);if(search)search.focus({preventScroll:true});else focusIndex(Math.max(0,index));requestAnimationFrame(function(){if(active!==w||m.hidden)return;place(w);});}
    function setValue(next,notify){next=String(next==null?'':next);var changed=value!==next;value=next;sync();syncSelection();if(changed&&notify&&typeof opts.onChange==='function')opts.onChange(value);}
    t.onclick=function(e){e.stopPropagation();m.hidden?open():close(w,false);};t.onkeydown=function(e){if(['ArrowDown','ArrowUp','Enter',' '].includes(e.key)){e.preventDefault();open();}else keys(e);};m.onkeydown=keys;m.onclick=function(e){e.stopPropagation();};
    w.setValue=function(v){setValue(v,false);};w.getValue=function(){return value;};w.setOptions=function(next){var normalized=normalizeOptions(next),nextSignature=optionSignature(normalized);if(nextSignature===itemsSignature){sync();syncSelection();return false;}items=normalized;itemsSignature=nextSignature;syncIntrinsic();render(search&&(numericInputSpec()?'':search.value),!m.hidden);sync();if(!m.hidden)place(w);return true;};w.setDisabled=function(v){opts.disabled=!!v;sync();};w.__uiClose=function(f){return close(w,f);};render('');sync();return decorateCapability(w);
  };
  C.comboControl=function(opts){
    opts=opts||{};var items=normalizeOptions(opts.options),multiple=!!opts.multiple,value=String(opts.value==null?'':opts.value),disabled=!!opts.disabled,w=document.createElement('div');w.className='ui-select ui-select--intrinsic ui-combo'+(opts.stretch?' ui-select--stretch':'')+(opts.className?' '+opts.className:'');w.dataset.uiSelect='1';w.dataset.uiSelectMode='floating-combo';if(opts.id)w.id=opts.id;
    var t=document.createElement('div');t.className='ui-select__trigger ui-combo__trigger';t.tabIndex=-1;t.setAttribute('role','combobox');t.setAttribute('aria-haspopup','listbox');t.setAttribute('aria-expanded','false');if(opts.ariaLabel)t.setAttribute('aria-label',opts.ariaLabel);var input=document.createElement('input');input.type='text';input.className='ui-combo__input';input.autocomplete='off';input.spellcheck=false;if(opts.placeholder)input.placeholder=opts.placeholder;if(opts.ariaLabel)input.setAttribute('aria-label',opts.ariaLabel);var ch=document.createElement('span');ch.className='ui-select__chevron';ch.setAttribute('aria-hidden','true');ch.textContent='▾';t.append(input,ch);w.appendChild(t);
    var m=document.createElement('div');m.className='ui-select__menu surface surface--floating';m.setAttribute('role','listbox');m.setAttribute('aria-multiselectable',multiple?'true':'false');m.hidden=true;var list=document.createElement('div');list.className='ui-select__options';m.appendChild(list);w.__uiMenu=m;w.__uiTrigger=t;w.__preferredWidth=opts.width||180;var filtered=[],index=-1,itemsSignature='';
    function signature(next){return next.map(function(item){return item.value+'\u0000'+item.label;}).join('\u0001');}itemsSignature=signature(items);
    function values(){if(!multiple)return value?[value]:[];var out=[];String(value||'').split(',').forEach(function(part){part=part.trim();if(part&&out.indexOf(part)<0)out.push(part);});return out;}
    function query(){if(!multiple)return input.value.trim();var parts=input.value.split(',');return String(parts[parts.length-1]||'').trim();}
    function selected(item){return values().indexOf(item.value)>=0;}
    function sync(){input.value=value;t.classList.toggle('is-disabled',disabled);t.setAttribute('aria-disabled',disabled?'true':'false');input.disabled=disabled;}
    function setValue(next,notify){next=String(next==null?'':next);var changed=value!==next;value=next;input.value=value;render('',true);if(changed&&notify&&typeof opts.onChange==='function')opts.onChange(value);}
    function choose(item){if(multiple){var current=values(),at=current.indexOf(item.value),q=query(),last=current.length-1;if(at>=0&&(!q||q===item.value))current.splice(at,1);else if(q&&last>=0&&current[last]===q){current[last]=item.value;current=current.filter(function(value,index,list){return list.indexOf(value)===index;});}else if(at<0)current.push(item.value);setValue(current.join(', '),true);render('',true);input.focus({preventScroll:true});}else{setValue(item.value,true);close(w,true);}}
    function render(q,preserveScroll){q=String(q||'').trim().toLocaleLowerCase();var saved=preserveScroll?list.scrollTop:0;filtered=items.filter(function(item){return !q||item.label.toLocaleLowerCase().includes(q)||item.value.toLocaleLowerCase().includes(q);});list.textContent='';index=-1;filtered.forEach(function(item,i){var b=document.createElement('button'),label=document.createElement('span'),isSelected=selected(item);b.type='button';b.className='ui-select__option';b.setAttribute('role','option');b.dataset.value=item.value;b.dataset.fullLabel=item.label;b.setAttribute('aria-selected',isSelected?'true':'false');label.className='ui-select__option-label';label.textContent=item.label;b.appendChild(label);b.addEventListener('mouseenter',function(){showPreview(b,false);});b.addEventListener('mouseleave',schedulePreviewClose);b.onclick=function(e){e.preventDefault();e.stopPropagation();choose(item);};list.appendChild(b);if(isSelected&&index<0)index=i;});m.__uiIntrinsicWidth=0;if(index<0&&filtered.length)index=0;if(preserveScroll)list.scrollTop=Math.min(saved,Math.max(0,list.scrollHeight-list.clientHeight));}
    function focusIndex(i){var bs=Array.from(list.querySelectorAll('.ui-select__option'));if(!bs.length)return;index=Math.max(0,Math.min(bs.length-1,i));bs[index].focus();bs[index].scrollIntoView({block:'nearest'});}
    function open(showAll){if(disabled)return;if(active&&active!==w)close(active,false);closeContextMenu();render(showAll?'':query());selectLayer(w).appendChild(m);m.hidden=false;w.classList.add('is-open');t.setAttribute('aria-expanded','true');active=w;place(w);requestAnimationFrame(function(){if(active===w&&!m.hidden)place(w);});}
    input.addEventListener('focus',function(){open(true);});input.addEventListener('click',function(e){e.stopPropagation();open(true);});input.addEventListener('input',function(){value=input.value;open(false);render(query(),true);place(w);if(typeof opts.onInput==='function')opts.onInput(value);if(typeof opts.onChange==='function'&&!multiple)opts.onChange(value);});input.addEventListener('keydown',function(e){if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close(w,true);}else if(e.key==='ArrowDown'){e.preventDefault();open(false);focusIndex(index+1);}else if(e.key==='ArrowUp'){e.preventDefault();open(false);focusIndex(index-1);}else if(e.key==='Enter'&&filtered[index]){e.preventDefault();choose(filtered[index]);}});
    t.addEventListener('click',function(e){if(e.target===input)return;e.stopPropagation();if(m.hidden){open(true);input.focus({preventScroll:true});}else close(w,false);});m.addEventListener('keydown',function(e){if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close(w,true);}else if(e.key==='ArrowDown'){e.preventDefault();focusIndex(index+1);}else if(e.key==='ArrowUp'){e.preventDefault();focusIndex(index-1);}else if(e.key==='Enter'&&filtered[index]){e.preventDefault();choose(filtered[index]);}});m.onclick=function(e){e.stopPropagation();};
    w.getValue=function(){return String(input.value==null?'':input.value).trim();};w.setValue=function(next){setValue(next,false);};w.setOptions=function(next){var normalized=normalizeOptions(next),nextSignature=signature(normalized);if(nextSignature===itemsSignature)return false;items=normalized;itemsSignature=nextSignature;render('',true);if(!m.hidden)place(w);return true;};w.setDisabled=function(next){disabled=!!next;sync();if(disabled&&active===w)close(w,false);};w.__uiClose=function(f){return close(w,f);};render('');sync();return decorateCapability(w);
  };
  C.timeControl=function(opts){
    opts=opts||{};
    function pad(value){return String(value).padStart(2,'0');}
    function parse(value){var match=String(value||'').match(/^(\d{2}):(\d{2})$/),hour=match?Number(match[1]):0,minute=match?Number(match[2]):0;if(!Number.isInteger(hour)||hour<0||hour>23)hour=0;if(!Number.isInteger(minute)||minute<0||minute>59)minute=0;return[pad(hour),pad(minute)];}
    function timeOptions(max){var out=[];for(var i=0;i<=max;i++){var value=pad(i);out.push({value:value,label:value});}return out;}
    var state=parse(opts.value),disabled=!!opts.disabled,readOnly=!!opts.readOnly,picker=null,w=document.createElement('span');w.className='ui-time-control'+(opts.className?' '+opts.className:'');w.dataset.uiTimeControl='1';w.dataset.controlKind='time';if(opts.ariaLabel)w.setAttribute('aria-label',opts.ariaLabel);
    function makePart(index,max,className,label){return C.selectControl({value:state[index],options:timeOptions(max),ariaLabel:label,className:'ui-time-control__select '+className,searchable:true,searchThreshold:1,searchPlaceholder:max===23?'00–23':'00–59',numericSearch:{min:0,max:max,pad:2},onChange:function(next){var number=Number(next);if(!Number.isInteger(number)||number<0||number>max)return;var value=pad(number),changed=state[index]!==value;state[index]=value;syncVisual();if(changed)emit();}});}
    var hour=makePart(0,23,'ui-time-control__hour',(opts.ariaLabel?opts.ariaLabel+' HH':'HH')),sep=document.createElement('span');sep.className='ui-time-control__separator';sep.textContent=':';sep.setAttribute('aria-hidden','true');var minute=makePart(1,59,'ui-time-control__minute',(opts.ariaLabel?opts.ariaLabel+' mm':'mm')),trigger=document.createElement('button');trigger.type='button';trigger.className='ui-time-control__clock-trigger';trigger.setAttribute('aria-label',opts.ariaLabel||'HH:mm');trigger.addEventListener('click',openPicker);w.append(hour,sep,minute,trigger);
    function value(){return state.join(':');}
    function syncVisual(){hour.setValue(state[0]);minute.setValue(state[1]);trigger.textContent=value();}
    function emit(){syncVisual();if(typeof opts.onChange==='function')opts.onChange(value());}
    function copy(key,fallback){return W.t?W.t(key):fallback;}
    function closePicker(apply){if(!picker)return;var dialog=picker,draft=dialog.__timeDraft;if(apply&&draft){var changed=state[0]!==draft[0]||state[1]!==draft[1];state=[draft[0],draft[1]];syncVisual();if(changed)emit();}picker=null;W.DialogRuntime.close(dialog,apply?'confirm':'cancel');}
    function openPicker(){if(disabled||readOnly||!W.DialogRuntime)return;C.closeSelects(false);if(picker)closePicker(false);var existing=document.querySelector('dialog.ui-time-picker');if(existing)W.DialogRuntime.remove(existing);var draft=[state[0],state[1]],mode='hour',dialog=W.DialogRuntime.create({className:'ui-time-picker',removeOnClose:true,backdropClose:true,escapeClose:true});dialog.__timeDraft=draft;dialog.setAttribute('aria-label',opts.ariaLabel||'HH:mm');var surface=document.createElement('div');surface.className='ui-time-picker__surface';var display=document.createElement('div');display.className='ui-time-picker__display';var hourTab=document.createElement('button');hourTab.type='button';hourTab.className='ui-time-picker__display-part';hourTab.dataset.timeMode='hour';hourTab.setAttribute('aria-label',(opts.ariaLabel?opts.ariaLabel+' HH':'HH'));var displaySep=document.createElement('span');displaySep.className='ui-time-picker__display-separator';displaySep.textContent=':';var minuteTab=document.createElement('button');minuteTab.type='button';minuteTab.className='ui-time-picker__display-part';minuteTab.dataset.timeMode='minute';minuteTab.setAttribute('aria-label',(opts.ariaLabel?opts.ariaLabel+' mm':'mm'));display.append(hourTab,displaySep,minuteTab);var face=document.createElement('div');face.className='ui-time-picker__face';face.setAttribute('role','group');var hand=document.createElement('span');hand.className='ui-time-picker__hand';var dot=document.createElement('span');dot.className='ui-time-picker__center';var ring=document.createElement('div');ring.className='ui-time-picker__ring';face.append(hand,dot,ring);var footer=document.createElement('div');footer.className='ui-time-picker__footer';var cancel=document.createElement('button');cancel.type='button';cancel.className='btn btn--ghost';cancel.textContent=copy('app.cancel','Cancel');cancel.dataset.timePickerCancel='1';var ok=document.createElement('button');ok.type='button';ok.className='btn';ok.textContent=copy('app.confirm','Confirm');ok.dataset.timePickerOk='1';footer.append(cancel,ok);surface.append(display,face,footer);dialog.appendChild(surface);picker=dialog;dialog.addEventListener('close',function(){if(picker===dialog)picker=null;},{once:true});
      function position(node,angle,radius){var radians=(angle-90)*Math.PI/180;node.style.left=(50+Math.cos(radians)*radius)+'%';node.style.top=(50+Math.sin(radians)*radius)+'%';}
      var renderedMode='';function option(value,label,angle,radius){var button=document.createElement('button');button.type='button';button.className='ui-time-picker__face-option';button.dataset.timeValue=String(value);button.textContent=label;position(button,angle,radius);button.addEventListener('click',function(event){event.stopPropagation();if(mode==='hour'){draft[0]=pad(value);mode='minute';}else draft[1]=pad(value);render();});ring.appendChild(button);}
      function syncDialSelection(){Array.from(ring.querySelectorAll('.ui-time-picker__face-option')).forEach(function(button){var selected=Number(mode==='hour'?draft[0]:draft[1])===Number(button.dataset.timeValue);button.classList.toggle('is-selected',selected);});}
      function syncDialHand(){if(mode==='hour'){var hourNumber=Number(draft[0]),innerRing=hourNumber===0||hourNumber>12;hand.style.setProperty('--time-hand-angle',((hourNumber%12)*30)+'deg');hand.style.setProperty('--time-hand-length',(innerRing?'27%':'42%'));}else{hand.style.setProperty('--time-hand-angle',(Number(draft[1])*6)+'deg');hand.style.setProperty('--time-hand-length','42%');}}
      function rebuildRing(){ring.textContent='';if(mode==='hour'){for(var h=1;h<=12;h++)option(h,pad(h),h%12*30,42);option(0,'00',0,27);for(var inner=13;inner<=23;inner++)option(inner,pad(inner),(inner-12)*30,27);}else{for(var m=0;m<60;m+=5)option(m,pad(m),m*6,42);}renderedMode=mode;ring.classList.remove('is-entering');void ring.offsetWidth;ring.classList.add('is-entering');}
      function render(){dialog.dataset.timeMode=mode;hourTab.textContent=draft[0];minuteTab.textContent=draft[1];hourTab.classList.toggle('is-active',mode==='hour');minuteTab.classList.toggle('is-active',mode==='minute');if(renderedMode!==mode)rebuildRing();syncDialSelection();syncDialHand();}
      function chooseFromPoint(event){if(event.target.closest('.ui-time-picker__face-option'))return;var rect=face.getBoundingClientRect(),x=event.clientX-(rect.left+rect.width/2),y=event.clientY-(rect.top+rect.height/2),radius=Math.sqrt(x*x+y*y),angle=(Math.atan2(y,x)*180/Math.PI+90+360)%360;if(mode==='hour'){var step=Math.round(angle/30)%12,innerRing=radius<rect.width*.35,next=innerRing?(step===0?0:12+step):(step===0?12:step);draft[0]=pad(next);mode='minute';}else draft[1]=pad(Math.round(angle/6)%60);render();}
      hourTab.addEventListener('click',function(){mode='hour';render();});minuteTab.addEventListener('click',function(){mode='minute';render();});face.addEventListener('pointerdown',chooseFromPoint);cancel.addEventListener('click',function(){closePicker(false);});ok.addEventListener('click',function(){closePicker(true);});render();W.DialogRuntime.open(dialog,{draggable:false,backdropClose:true,escapeClose:true,removeOnClose:true,focus:hourTab});
    }
    function syncLock(){var locked=disabled||readOnly;hour.setDisabled(locked);minute.setDisabled(locked);trigger.disabled=locked;if(locked&&picker)closePicker(false);if(disabled)w.setAttribute('aria-disabled','true');else w.removeAttribute('aria-disabled');if(readOnly)w.setAttribute('aria-readonly','true');else w.removeAttribute('aria-readonly');}
    w.getValue=value;w.setValue=function(next){state=parse(next);syncVisual();};w.setDisabled=function(next){disabled=!!next;syncLock();};w.setReadOnly=function(next){readOnly=!!next;syncLock();};syncVisual();syncLock();return decorateCapability(w);
  };
  document.addEventListener('pointerdown',function(e){if(previewPersistent&&preview&&e&&e.target&&!preview.contains(e.target))closePreview(true);},true);document.addEventListener('click',function(){C.closeSelects(false);closePreview(true);});document.addEventListener('keydown',function(e){if(e.key==='Escape'){closeContextMenu();closePreview(true);}});global.addEventListener('resize',function(){if(contextMenu)closeContextMenu();else place(active);},{passive:true});global.addEventListener('scroll',function(e){if(internalMenuScroll(e))return;if(contextMenu)closeContextMenu();else place(active);},true);if(global.visualViewport){visualViewport.addEventListener('resize',function(){if(contextMenu)closeContextMenu();else place(active);});visualViewport.addEventListener('scroll',function(){if(contextMenu)closeContextMenu();else place(active);});}
})(window);
