(function(global){
  'use strict';
  var W=global.WeiG,C=W&&W.Components;
  if(!W||!C||C.__floatingSelect)return;C.__floatingSelect=true;
  var root=null,active=null,contextMenu=null;
  function layer(){if(root&&root.isConnected)return root;root=document.getElementById('weig-floating-layer');if(!root){root=document.createElement('div');root.id='weig-floating-layer';root.className='weig-floating-layer';root.setAttribute('aria-live','off');document.body.appendChild(root);}return root;}
  function modalLayer(owner){var dialog=owner&&owner.closest?owner.closest('dialog[open]'):null;if(!dialog)return null;var host=null;for(var i=0;i<dialog.children.length;i++){var child=dialog.children[i];if(child&&child.classList&&child.classList.contains('weig-floating-layer')&&child.dataset.uiModalLayer==='1'){host=child;break;}}if(!host){host=document.createElement('div');host.className='weig-floating-layer weig-floating-layer--dialog';host.dataset.uiModalLayer='1';host.setAttribute('aria-live','off');dialog.appendChild(host);}return host;}
  function selectLayer(owner){return modalLayer(owner)||layer();}
  function normalizeOptions(input){return (input||[]).map(function(x){return typeof x==='string'?{value:x,label:x}:{value:String(x.value),label:String(x.label==null?x.value:x.label)};});}
  function decorateCapability(node){if(W.CapabilityRegistry&&W.CapabilityRegistry.decorateMatching)W.CapabilityRegistry.decorateMatching(node);return node;}
  function nativeControl(opts,items,value){var w=document.createElement('span'),select=document.createElement('select');w.className='ui-select ui-select--native'+(opts.className?' '+opts.className:'');w.dataset.uiSelect='1';w.dataset.uiSelectMode='native';if(opts.id)w.id=opts.id;select.className='ui-select__native';if(opts.ariaLabel)select.setAttribute('aria-label',opts.ariaLabel);w.appendChild(select);function render(){select.textContent='';items.forEach(function(item){var option=document.createElement('option');option.value=item.value;option.textContent=item.label;select.appendChild(option);});select.value=value;select.disabled=!!opts.disabled;}function setValue(next,notify){value=String(next==null?'':next);select.value=value;if(notify&&typeof opts.onChange==='function')opts.onChange(value);}select.addEventListener('mousedown',function(e){if(typeof opts.onOpen==='function'&&opts.onOpen(value,w)===false){e.preventDefault();e.stopPropagation();}});select.addEventListener('change',function(){setValue(select.value,true);});w.setValue=function(v){setValue(v,false);};w.getValue=function(){return value;};w.setOptions=function(next){items=normalizeOptions(next);render();};w.setDisabled=function(v){opts.disabled=!!v;render();};render();return decorateCapability(w);}
  function viewport(){var v=global.visualViewport;return{left:v?v.offsetLeft:0,top:v?v.offsetTop:0,width:v?v.width:document.documentElement.clientWidth,height:v?v.height:document.documentElement.clientHeight};}
  function pointRect(x,y){x=Number(x)||0;y=Number(y)||0;return{left:x,right:x,top:y,bottom:y,width:0,height:0};}
  function placeBounded(menu,anchor,opts){opts=opts||{};if(!menu||menu.hidden)return null;var v=viewport(),pad=opts.pad==null?8:Number(opts.pad),gap=opts.gap==null?7:Number(opts.gap),minW=Math.min(Math.max(1,Number(opts.minWidth)||160),Math.max(1,v.width-pad*2)),maxW=Math.max(minW,v.width-pad*2);menu.style.visibility='hidden';menu.style.left='0px';menu.style.top='0px';menu.style.maxHeight='';if(opts.width!=null){var requested=Math.min(maxW,Math.max(minW,Number(opts.width)||minW))+'px';menu.style.width=requested;menu.style.inlineSize=requested;}var measuredW=menu.offsetWidth||Number(opts.width)||minW,width=Math.min(maxW,Math.max(minW,measuredW)),natural=menu.scrollHeight||menu.offsetHeight||120,down=v.top+v.height-anchor.bottom-gap-pad,up=anchor.top-v.top-gap-pad,viewportCap=Math.max(96,Math.floor(v.height*(v.width<=820?.84:.68))),preferDown=opts.preferDown!==false,useDown=preferDown?(down>=Math.min(natural,viewportCap)||down>=up):(up<Math.min(natural,viewportCap)&&down>up),available=Math.max(0,useDown?down:up),maxH=Math.max(72,Math.min(viewportCap,Math.max(72,available))),finalWidth=width+'px';menu.style.width=finalWidth;menu.style.inlineSize=finalWidth;menu.style.maxHeight=maxH+'px';var h=Math.min(menu.offsetHeight||natural,maxH),left=Math.min(Math.max(v.left+pad,anchor.left),v.left+v.width-pad-width),top=useDown?anchor.bottom+gap:anchor.top-gap-h;top=Math.min(Math.max(v.top+pad,top),v.top+v.height-pad-h);menu.style.left=Math.round(left)+'px';menu.style.top=Math.round(top)+'px';menu.style.visibility='visible';menu.dataset.placement=useDown?'bottom':'top';return{left:left,top:top,width:width,height:h,maxHeight:maxH,placement:menu.dataset.placement};}
  function place(w){if(!w||!w.__uiMenu||w.__uiMenu.hidden)return;var t=w.__uiTrigger,m=w.__uiMenu,r=t.getBoundingClientRect(),v=viewport(),pad=8,maxW=Math.max(160,v.width-pad*2);m.dataset.wrap='0';m.style.width='max-content';m.style.inlineSize='max-content';var natural=0;Array.from(m.querySelectorAll('.ui-select__option')).forEach(function(option){natural=Math.max(natural,option.scrollWidth+20);});var desired=Math.max(r.width,w.__preferredWidth||220,natural),wrap=desired>maxW,width=Math.min(maxW,desired);m.dataset.wrap=wrap?'1':'0';m.style.width='';m.style.inlineSize='';placeBounded(m,r,{width:width,minWidth:160,pad:pad,gap:7,preferDown:true});}
  function close(w,focus){if(!w||!w.__uiMenu||w.__uiMenu.hidden)return false;w.__uiMenu.hidden=true;w.__uiMenu.remove();w.classList.remove('is-open');w.__uiTrigger.setAttribute('aria-expanded','false');if(active===w)active=null;if(focus)w.__uiTrigger.focus();return true;}
  function closeContextMenu(){if(!contextMenu)return false;var menu=contextMenu;contextMenu=null;menu.remove();return true;}
  function placeContextMenu(menu,x,y){var r=pointRect(x,y),width=Math.max(160,menu.offsetWidth||180);return placeBounded(menu,r,{width:width,minWidth:160,pad:8,gap:4,preferDown:true});}
  function internalMenuScroll(e){return !!((active&&active.__uiMenu&&e&&e.target&&active.__uiMenu.contains(e.target))||(contextMenu&&e&&e.target&&contextMenu.contains(e.target)));}
  C.closeSelects=function(focus){var closed=close(active,focus!==false);return closeContextMenu()||closed;};
  C.closeContextMenu=closeContextMenu;
  C.openContextMenu=function(opts){opts=opts||{};var items=(opts.items||[]).filter(function(item){return item&&item.hidden!==true;});if(!items.length)return false;if(active)close(active,false);closeContextMenu();var menu=document.createElement('div');menu.className='ui-select__menu ui-context-menu surface surface--floating';menu.setAttribute('role','menu');var list=document.createElement('div');list.className='ui-select__options';items.forEach(function(item){var button=document.createElement('button');button.type='button';button.className='ui-select__option';button.setAttribute('role','menuitem');button.textContent=String(item.label||item.key||'');button.disabled=!!item.disabled;button.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();if(button.disabled)return;closeContextMenu();if(typeof item.onSelect==='function')item.onSelect(item);});list.appendChild(button);});menu.appendChild(list);layer().appendChild(menu);contextMenu=menu;requestAnimationFrame(function(){if(contextMenu===menu){placeContextMenu(menu,opts.x,opts.y);var first=menu.querySelector('.ui-select__option:not(:disabled)');if(first)first.focus();}});return true;};
  C.selectControl=function(opts){
    opts=opts||{};var items=normalizeOptions(opts.options),value=String(opts.value==null?'':opts.value);if(opts.native===true)return nativeControl(opts,items,value);var w=document.createElement('div'),maxLabel=0;items.forEach(function(x){maxLabel=Math.max(maxLabel,String(x.label||x.value||'').length);});w.className='ui-select ui-select--intrinsic'+(opts.className?' '+opts.className:'');w.dataset.uiSelect='1';w.dataset.uiSelectMode='floating';w.dataset.uiSelectTrigger=opts.triggerMode==='prefix'?'prefix':'value';w.style.setProperty('--select-menu-ch',String(Math.min(42,Math.max(8,maxLabel+3))));if(opts.id)w.id=opts.id;
    var t=document.createElement('button');t.type='button';t.className='ui-select__trigger';t.setAttribute('aria-haspopup','listbox');t.setAttribute('aria-expanded','false');if(opts.ariaLabel)t.setAttribute('aria-label',opts.ariaLabel);
    var prefix=document.createElement('span');prefix.className='ui-select__prefix'+(opts.prefixClassName?' '+opts.prefixClassName:'');if(opts.prefixNode&&opts.prefixNode.nodeType)prefix.appendChild(opts.prefixNode);else prefix.textContent=opts.prefix||'';prefix.hidden=!(opts.prefixNode||opts.prefix);var prefixOnly=opts.triggerMode==='prefix',val=null,ch=null;t.appendChild(prefix);if(!prefixOnly){val=document.createElement('span');val.className='ui-select__value';ch=document.createElement('span');ch.className='ui-select__chevron';ch.setAttribute('aria-hidden','true');ch.textContent='▾';t.append(val,ch);}w.appendChild(t);
    var m=document.createElement('div');m.className='ui-select__menu surface surface--floating';m.setAttribute('role','listbox');m.hidden=true;var search=null,list=document.createElement('div');list.className='ui-select__options';m.appendChild(list);w.__uiMenu=m;w.__uiTrigger=t;w.__preferredWidth=opts.width||Math.max(116,maxLabel*8+34);var filtered=[],index=-1;
    function current(){var h=items.find(function(x){return x.value===value;});return h?h.label:(opts.placeholder||value||'—');}
    function sync(){if(val)val.textContent=current();t.removeAttribute('title');if(opts.nativeTitle===true&&!opts.ariaLabel)t.setAttribute('aria-label',(opts.prefix?opts.prefix+' ':'')+current());t.disabled=!!opts.disabled;}
    function syncIntrinsic(){maxLabel=0;items.forEach(function(x){maxLabel=Math.max(maxLabel,String(x.label||x.value||'').length);});w.style.setProperty('--select-menu-ch',String(Math.min(42,Math.max(8,maxLabel+3))));if(!opts.width)w.__preferredWidth=Math.max(116,maxLabel*8+34);}
    function render(q){q=String(q||'').trim().toLocaleLowerCase();filtered=items.filter(function(x){return !q||x.label.toLocaleLowerCase().includes(q)||x.value.toLocaleLowerCase().includes(q);});list.textContent='';index=-1;filtered.forEach(function(item,i){var b=document.createElement('button');b.type='button';b.className='ui-select__option';b.setAttribute('role','option');b.dataset.value=item.value;b.setAttribute('aria-selected',item.value===value?'true':'false');b.textContent=item.label;b.onclick=function(){setValue(item.value,true);close(w,true);};list.appendChild(b);if(item.value===value)index=i;});if(index<0&&filtered.length)index=0;}
    function ensureSearch(){if(search||!opts.searchable||items.length<(opts.searchThreshold||14))return;search=document.createElement('input');search.type='search';search.className='ui-select__search';search.placeholder=opts.searchPlaceholder||'Search…';search.setAttribute('aria-label',search.placeholder);search.oninput=function(){render(search.value);place(w);};m.insertBefore(search,list);}
    function focusIndex(i){var bs=Array.from(list.querySelectorAll('.ui-select__option'));if(!bs.length)return;index=Math.max(0,Math.min(bs.length-1,i));bs[index].focus();bs[index].scrollIntoView({block:'nearest'});}
    function keys(e){if(e.key==='Escape'){e.preventDefault();close(w,true);}else if(e.key==='ArrowDown'){e.preventDefault();focusIndex(index+1);}else if(e.key==='ArrowUp'){e.preventDefault();focusIndex(index-1);}else if(e.key==='Home'){e.preventDefault();focusIndex(0);}else if(e.key==='End'){e.preventDefault();focusIndex(filtered.length-1);}}
    function open(){if(t.disabled)return;if(typeof opts.onOpen==='function'&&opts.onOpen(value,w)===false)return;if(active&&active!==w)close(active,false);closeContextMenu();ensureSearch();render(search&&search.value);selectLayer(w).appendChild(m);m.hidden=false;w.classList.add('is-open');t.setAttribute('aria-expanded','true');active=w;place(w);requestAnimationFrame(function(){if(active!==w||m.hidden)return;place(w);if(search)search.focus();else focusIndex(Math.max(0,index));});}
    function setValue(next,notify){value=String(next==null?'':next);sync();render(search&&search.value);if(notify&&typeof opts.onChange==='function')opts.onChange(value);}
    t.onclick=function(e){e.stopPropagation();m.hidden?open():close(w,false);};t.onkeydown=function(e){if(['ArrowDown','ArrowUp','Enter',' '].includes(e.key)){e.preventDefault();open();}else keys(e);};m.onkeydown=keys;m.onclick=function(e){e.stopPropagation();};
    w.setValue=function(v){setValue(v,false);};w.getValue=function(){return value;};w.setOptions=function(next){items=normalizeOptions(next);syncIntrinsic();render(search&&search.value);sync();};w.setDisabled=function(v){opts.disabled=!!v;sync();};w.__uiClose=function(f){return close(w,f);};render('');sync();return decorateCapability(w);
  };
  C.timeControl=function(opts){
    opts=opts||{};
    function pad(value){return String(value).padStart(2,'0');}
    function parse(value){var match=String(value||'').match(/^(\d{2}):(\d{2})$/),hour=match?Number(match[1]):0,minute=match?Number(match[2]):0;if(!Number.isInteger(hour)||hour<0||hour>23)hour=0;if(!Number.isInteger(minute)||minute<0||minute>59)minute=0;return[pad(hour),pad(minute)];}
    var state=parse(opts.value),disabled=!!opts.disabled,readOnly=!!opts.readOnly,picker=null,w=document.createElement('span');w.className='ui-time-control'+(opts.className?' '+opts.className:'');w.dataset.uiTimeControl='1';w.dataset.controlKind='time';if(opts.ariaLabel)w.setAttribute('aria-label',opts.ariaLabel);
    function makePart(index,max,className,label){var input=document.createElement('input');input.type='text';input.inputMode='numeric';input.autocomplete='off';input.spellcheck=false;input.maxLength=2;input.className='ui-time-control__part '+className;input.setAttribute('aria-label',label);input.value=state[index];function commit(notify){var raw=String(input.value||'').replace(/\D/g,'').slice(0,2);if(!raw){input.value=state[index];return;}var number=Number(raw);if(!Number.isFinite(number))number=Number(state[index]);number=Math.max(0,Math.min(max,number));var next=pad(number),changed=state[index]!==next;state[index]=next;syncVisual();if(notify&&changed)emit();}input.addEventListener('input',function(){var raw=String(input.value||'').replace(/\D/g,'').slice(0,2);if(input.value!==raw)input.value=raw;if(raw.length===2&&Number(raw)<=max)commit(true);});input.addEventListener('blur',function(){commit(true);});input.addEventListener('keydown',function(event){if(event.key==='Enter'){event.preventDefault();commit(true);input.blur();return;}if(event.key==='ArrowUp'||event.key==='ArrowDown'){event.preventDefault();var delta=event.key==='ArrowUp'?1:-1,next=(Number(state[index])+delta+(max+1))%(max+1);state[index]=pad(next);syncVisual();emit();}});return input;}
    var hour=makePart(0,23,'ui-time-control__hour',(opts.ariaLabel?opts.ariaLabel+' HH':'HH')),sep=document.createElement('span');sep.className='ui-time-control__separator';sep.textContent=':';sep.setAttribute('aria-hidden','true');var minute=makePart(1,59,'ui-time-control__minute',(opts.ariaLabel?opts.ariaLabel+' mm':'mm')),trigger=document.createElement('button');trigger.type='button';trigger.className='ui-time-control__clock-trigger';trigger.setAttribute('aria-label',opts.ariaLabel||'Time');trigger.addEventListener('click',openPicker);w.append(hour,sep,minute,trigger);
    function value(){return state.join(':');}
    function syncVisual(){hour.value=state[0];minute.value=state[1];trigger.textContent=value();}
    function emit(){syncVisual();if(typeof opts.onChange==='function')opts.onChange(value());}
    function pickerCopy(en,zh){var lang=String(document.documentElement.lang||navigator.language||'').toLowerCase();return lang.indexOf('zh')===0?zh:en;}
    function closePicker(apply){if(!picker)return;var overlay=picker,draft=overlay.__timeDraft;if(apply&&draft){var changed=state[0]!==draft[0]||state[1]!==draft[1];state=[draft[0],draft[1]];syncVisual();if(changed)emit();}document.removeEventListener('keydown',overlay.__timeEscape,true);overlay.remove();picker=null;if(trigger.isConnected)trigger.focus();}
    function openPicker(){if(disabled||readOnly)return;if(picker)closePicker(false);var existing=document.querySelector('.ui-time-picker');if(existing)existing.remove();var draft=[state[0],state[1]],mode='hour',overlay=document.createElement('div');overlay.className='ui-time-picker';overlay.setAttribute('role','presentation');overlay.__timeDraft=draft;var dialog=document.createElement('div');dialog.className='ui-time-picker__dialog';dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');dialog.setAttribute('aria-label',pickerCopy('Select time','选择时间'));var display=document.createElement('div');display.className='ui-time-picker__display';var hourTab=document.createElement('button');hourTab.type='button';hourTab.className='ui-time-picker__display-part';hourTab.dataset.timeMode='hour';hourTab.setAttribute('aria-label',pickerCopy('Choose hour','选择小时'));var displaySep=document.createElement('span');displaySep.className='ui-time-picker__display-separator';displaySep.textContent=':';var minuteTab=document.createElement('button');minuteTab.type='button';minuteTab.className='ui-time-picker__display-part';minuteTab.dataset.timeMode='minute';minuteTab.setAttribute('aria-label',pickerCopy('Choose minute','选择分钟'));display.append(hourTab,displaySep,minuteTab);var face=document.createElement('div');face.className='ui-time-picker__face';face.setAttribute('role','group');var footer=document.createElement('div');footer.className='ui-time-picker__footer';var cancel=document.createElement('button');cancel.type='button';cancel.className='btn btn--ghost';cancel.textContent=pickerCopy('Cancel','取消');cancel.dataset.timePickerCancel='1';var ok=document.createElement('button');ok.type='button';ok.className='btn';ok.textContent=pickerCopy('OK','确定');ok.dataset.timePickerOk='1';footer.append(cancel,ok);dialog.append(display,face,footer);overlay.appendChild(dialog);document.body.appendChild(overlay);picker=overlay;
      function position(node,angle,radius){var radians=(angle-90)*Math.PI/180;node.style.left=(50+Math.cos(radians)*radius)+'%';node.style.top=(50+Math.sin(radians)*radius)+'%';}
      function option(value,label,angle,radius){var button=document.createElement('button');button.type='button';button.className='ui-time-picker__face-option';button.dataset.timeValue=String(value);button.textContent=label;position(button,angle,radius);var selected=mode==='hour'?Number(draft[0])===value:Number(draft[1])===value;button.classList.toggle('is-selected',selected);button.addEventListener('click',function(event){event.stopPropagation();if(mode==='hour'){draft[0]=pad(value);mode='minute';}else draft[1]=pad(value);render();});face.appendChild(button);}
      function render(){overlay.dataset.timeMode=mode;hourTab.textContent=draft[0];minuteTab.textContent=draft[1];hourTab.classList.toggle('is-active',mode==='hour');minuteTab.classList.toggle('is-active',mode==='minute');face.textContent='';var hand=document.createElement('span');hand.className='ui-time-picker__hand';var dot=document.createElement('span');dot.className='ui-time-picker__center';face.append(hand,dot);if(mode==='hour'){for(var h=1;h<=12;h++)option(h,pad(h),h%12*30,42);option(0,'00',0,27);for(var inner=13;inner<=23;inner++)option(inner,pad(inner),(inner-12)*30,27);var hourNumber=Number(draft[0]),innerRing=hourNumber===0||hourNumber>12;hand.style.setProperty('--time-hand-angle',((hourNumber%12)*30)+'deg');hand.style.setProperty('--time-hand-length',(innerRing?'27%':'42%'));}else{for(var m=0;m<60;m+=5)option(m,pad(m),m*6,42);hand.style.setProperty('--time-hand-angle',(Number(draft[1])*6)+'deg');hand.style.setProperty('--time-hand-length','42%');}}
      function chooseFromPoint(event){if(event.target.closest('.ui-time-picker__face-option'))return;var rect=face.getBoundingClientRect(),x=event.clientX-(rect.left+rect.width/2),y=event.clientY-(rect.top+rect.height/2),radius=Math.sqrt(x*x+y*y),angle=(Math.atan2(y,x)*180/Math.PI+90+360)%360;if(mode==='hour'){var step=Math.round(angle/30)%12,innerRing=radius<rect.width*.35,next=innerRing?(step===0?0:12+step):(step===0?12:step);draft[0]=pad(next);mode='minute';}else draft[1]=pad(Math.round(angle/6)%60);render();}
      hourTab.addEventListener('click',function(){mode='hour';render();});minuteTab.addEventListener('click',function(){mode='minute';render();});face.addEventListener('pointerdown',chooseFromPoint);cancel.addEventListener('click',function(){closePicker(false);});ok.addEventListener('click',function(){closePicker(true);});overlay.addEventListener('click',function(event){if(event.target===overlay)closePicker(false);});overlay.__timeEscape=function(event){if(event.key==='Escape'){event.preventDefault();closePicker(false);}};document.addEventListener('keydown',overlay.__timeEscape,true);render();requestAnimationFrame(function(){hourTab.focus();});
    }
    function syncLock(){var locked=disabled||readOnly;hour.disabled=disabled;minute.disabled=disabled;hour.readOnly=readOnly;minute.readOnly=readOnly;trigger.disabled=locked;if(locked&&picker)closePicker(false);if(disabled)w.setAttribute('aria-disabled','true');else w.removeAttribute('aria-disabled');if(readOnly)w.setAttribute('aria-readonly','true');else w.removeAttribute('aria-readonly');}
    w.getValue=value;w.setValue=function(next){state=parse(next);syncVisual();};w.setDisabled=function(next){disabled=!!next;syncLock();};w.setReadOnly=function(next){readOnly=!!next;syncLock();};syncVisual();syncLock();return decorateCapability(w);
  };
  document.addEventListener('click',function(){C.closeSelects(false);});document.addEventListener('keydown',function(e){if(e.key==='Escape')closeContextMenu();});global.addEventListener('resize',function(){if(contextMenu)closeContextMenu();else place(active);},{passive:true});global.addEventListener('scroll',function(e){if(internalMenuScroll(e))return;if(contextMenu)closeContextMenu();else place(active);},true);if(global.visualViewport){visualViewport.addEventListener('resize',function(){if(contextMenu)closeContextMenu();else place(active);});visualViewport.addEventListener('scroll',function(){if(contextMenu)closeContextMenu();else place(active);});}
})(window);
