(function(global){
  'use strict';
  var W=global.WeiG,C=W&&W.Components;
  if(!W||!C||C.__floatingSelect)return;C.__floatingSelect=true;
  var root=null,active=null;
  function layer(){if(root&&root.isConnected)return root;root=document.getElementById('weigg-floating-layer');if(!root){root=document.createElement('div');root.id='weigg-floating-layer';root.className='weigg-floating-layer';root.setAttribute('aria-live','off');document.body.appendChild(root);}return root;}
  function normalizeOptions(input){return (input||[]).map(function(x){return typeof x==='string'?{value:x,label:x}:{value:String(x.value),label:String(x.label==null?x.value:x.label)};});}
  function nativeControl(opts,items,value){var w=document.createElement('span'),select=document.createElement('select');w.className='ui-select ui-select--native'+(opts.className?' '+opts.className:'');w.dataset.uiSelect='1';w.dataset.uiSelectMode='native';if(opts.id)w.id=opts.id;select.className='ui-select__native';if(opts.ariaLabel)select.setAttribute('aria-label',opts.ariaLabel);w.appendChild(select);function render(){select.textContent='';items.forEach(function(item){var option=document.createElement('option');option.value=item.value;option.textContent=item.label;select.appendChild(option);});select.value=value;select.disabled=!!opts.disabled;}function setValue(next,notify){value=String(next==null?'':next);select.value=value;if(notify&&typeof opts.onChange==='function')opts.onChange(value);}select.addEventListener('mousedown',function(e){if(typeof opts.onOpen==='function'&&opts.onOpen(value,w)===false){e.preventDefault();e.stopPropagation();}});select.addEventListener('change',function(){setValue(select.value,true);});w.setValue=function(v){setValue(v,false);};w.getValue=function(){return value;};w.setOptions=function(next){items=normalizeOptions(next);render();};w.setDisabled=function(v){opts.disabled=!!v;render();};render();return w;}
  function viewport(){var v=global.visualViewport;return{left:v?v.offsetLeft:0,top:v?v.offsetTop:0,width:v?v.width:document.documentElement.clientWidth,height:v?v.height:document.documentElement.clientHeight};}
  function place(w){if(!w||!w.__uiMenu||w.__uiMenu.hidden)return;var t=w.__uiTrigger,m=w.__uiMenu,r=t.getBoundingClientRect(),v=viewport(),pad=8,gap=7,maxW=Math.max(160,v.width-pad*2);m.style.visibility='hidden';m.style.left='0px';m.style.top='0px';m.style.width=Math.min(maxW,Math.max(r.width,Math.min(360,w.__preferredWidth||220)))+'px';m.style.maxHeight='';var width=Math.min(maxW,Math.max(r.width,m.offsetWidth||220)),natural=m.offsetHeight||240,down=v.top+v.height-r.bottom-gap-pad,up=r.top-v.top-gap-pad,useDown=down>=Math.min(natural,280)||down>=up,maxH=Math.max(120,useDown?down:up);m.style.width=width+'px';m.style.maxHeight=Math.min(maxH,Math.floor(v.height*.68))+'px';var h=Math.min(m.offsetHeight||natural,Math.min(maxH,Math.floor(v.height*.68))),left=Math.min(Math.max(v.left+pad,r.left),v.left+v.width-pad-width),top=useDown?r.bottom+gap:Math.max(v.top+pad,r.top-gap-h);m.style.left=Math.round(left)+'px';m.style.top=Math.round(top)+'px';m.style.visibility='visible';m.dataset.placement=useDown?'bottom':'top';}
  function close(w,focus){if(!w||!w.__uiMenu||w.__uiMenu.hidden)return false;w.__uiMenu.hidden=true;w.__uiMenu.remove();w.classList.remove('is-open');w.__uiTrigger.setAttribute('aria-expanded','false');if(active===w)active=null;if(focus)w.__uiTrigger.focus();return true;}
  function internalMenuScroll(e){return !!(active&&active.__uiMenu&&e&&e.target&&active.__uiMenu.contains(e.target));}
  C.closeSelects=function(focus){return close(active,focus!==false);};
  C.selectControl=function(opts){
    opts=opts||{};var items=normalizeOptions(opts.options),value=String(opts.value==null?'':opts.value);if(opts.native===true)return nativeControl(opts,items,value);var w=document.createElement('div'),maxLabel=0;items.forEach(function(x){maxLabel=Math.max(maxLabel,String(x.label||x.value||'').length);});w.className='ui-select ui-select--intrinsic'+(opts.className?' '+opts.className:'');w.dataset.uiSelect='1';w.dataset.uiSelectMode='floating';w.style.setProperty('--select-menu-ch',String(Math.min(42,Math.max(8,maxLabel+3))));if(opts.id)w.id=opts.id;
    var t=document.createElement('button');t.type='button';t.className='ui-select__trigger';t.setAttribute('aria-haspopup','listbox');t.setAttribute('aria-expanded','false');if(opts.ariaLabel)t.setAttribute('aria-label',opts.ariaLabel);
    var prefix=document.createElement('span');prefix.className='ui-select__prefix';prefix.textContent=opts.prefix||'';prefix.hidden=!opts.prefix;var val=document.createElement('span');val.className='ui-select__value';var ch=document.createElement('span');ch.className='ui-select__chevron';ch.setAttribute('aria-hidden','true');ch.textContent='▾';t.append(prefix,val,ch);w.appendChild(t);
    var m=document.createElement('div');m.className='ui-select__menu surface surface--floating';m.setAttribute('role','listbox');m.hidden=true;var search=null,list=document.createElement('div');list.className='ui-select__options';m.appendChild(list);w.__uiMenu=m;w.__uiTrigger=t;w.__preferredWidth=opts.width||Math.min(360,Math.max(116,maxLabel*8+34));var filtered=[],index=-1;
    function current(){var h=items.find(function(x){return x.value===value;});return h?h.label:(opts.placeholder||value||'—');}
    function sync(){val.textContent=current();t.title=(opts.prefix?opts.prefix+' ':'')+current();t.disabled=!!opts.disabled;}
    function syncIntrinsic(){maxLabel=0;items.forEach(function(x){maxLabel=Math.max(maxLabel,String(x.label||x.value||'').length);});w.style.setProperty('--select-menu-ch',String(Math.min(42,Math.max(8,maxLabel+3))));if(!opts.width)w.__preferredWidth=Math.min(360,Math.max(116,maxLabel*8+34));}
    function render(q){q=String(q||'').trim().toLocaleLowerCase();filtered=items.filter(function(x){return !q||x.label.toLocaleLowerCase().includes(q)||x.value.toLocaleLowerCase().includes(q);});list.textContent='';index=-1;filtered.forEach(function(item,i){var b=document.createElement('button');b.type='button';b.className='ui-select__option';b.setAttribute('role','option');b.dataset.value=item.value;b.setAttribute('aria-selected',item.value===value?'true':'false');b.textContent=item.label;b.onclick=function(){setValue(item.value,true);close(w,true);};list.appendChild(b);if(item.value===value)index=i;});if(index<0&&filtered.length)index=0;}
    function ensureSearch(){if(search||!opts.searchable||items.length<(opts.searchThreshold||14))return;search=document.createElement('input');search.type='search';search.className='ui-select__search';search.placeholder=opts.searchPlaceholder||'Search…';search.setAttribute('aria-label',search.placeholder);search.oninput=function(){render(search.value);place(w);};m.insertBefore(search,list);}
    function focusIndex(i){var bs=Array.from(list.querySelectorAll('.ui-select__option'));if(!bs.length)return;index=Math.max(0,Math.min(bs.length-1,i));bs[index].focus();}
    function keys(e){if(e.key==='Escape'){e.preventDefault();close(w,true);}else if(e.key==='ArrowDown'){e.preventDefault();focusIndex(index+1);}else if(e.key==='ArrowUp'){e.preventDefault();focusIndex(index-1);}else if(e.key==='Home'){e.preventDefault();focusIndex(0);}else if(e.key==='End'){e.preventDefault();focusIndex(filtered.length-1);}}
    function open(){if(t.disabled)return;if(typeof opts.onOpen==='function'&&opts.onOpen(value,w)===false)return;if(active&&active!==w)close(active,false);ensureSearch();render(search&&search.value);layer().appendChild(m);m.hidden=false;w.classList.add('is-open');t.setAttribute('aria-expanded','true');active=w;requestAnimationFrame(function(){place(w);if(search)search.focus();else focusIndex(Math.max(0,index));});}
    function setValue(next,notify){value=String(next==null?'':next);sync();render(search&&search.value);if(notify&&typeof opts.onChange==='function')opts.onChange(value);}
    t.onclick=function(e){e.stopPropagation();m.hidden?open():close(w,false);};t.onkeydown=function(e){if(['ArrowDown','ArrowUp','Enter',' '].includes(e.key)){e.preventDefault();open();}else keys(e);};m.onkeydown=keys;m.onclick=function(e){e.stopPropagation();};
    w.setValue=function(v){setValue(v,false);};w.getValue=function(){return value;};w.setOptions=function(next){items=normalizeOptions(next);syncIntrinsic();render(search&&search.value);sync();};w.setDisabled=function(v){opts.disabled=!!v;sync();};w.__uiClose=function(f){return close(w,f);};render('');sync();return w;
  };
  document.addEventListener('click',function(){C.closeSelects(false);});global.addEventListener('resize',function(){place(active);},{passive:true});global.addEventListener('scroll',function(e){if(internalMenuScroll(e))return;place(active);},true);if(global.visualViewport){visualViewport.addEventListener('resize',function(){place(active);});visualViewport.addEventListener('scroll',function(){place(active);});}
})(window);
