(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{};
  var EN={
    'app.skip':'Skip to torrent list','app.back':'Back','app.home':'Home','app.reload':'Reload','app.refresh':'Refresh','app.theme':'Toggle theme','app.menu':'Open navigation','app.close':'Close','app.cancel':'Cancel','app.confirm':'Confirm','app.done':'Done','app.reset':'Reset','app.more':'More','app.loading':'Loading…','app.connected':'WeiG qB WebUI connected','app.compatible':'Adapted','app.compatMode':'Compatibility mode','app.detecting':'Detecting…',
    'nav.torrents':'Torrents','nav.search':'Search','nav.rss':'RSS','nav.logs':'Logs','nav.settings':'Settings','nav.more':'More',
    'sidebar.torrents':'TORRENTS','sidebar.trackers':'TRACKERS','sidebar.savePath':'SAVE PATH','sidebar.categories':'CATEGORIES','sidebar.tags':'TAGS','sidebar.connection':'CONNECTION',
    'tracker.all':'All Trackers','tracker.none':'No Tracker','tracker.indexing':'Building Tracker index…','path.all':'All Paths','category.all':'All Categories','tag.all':'All Tags',
    'library.eyebrow':'LIBRARY','library.all':'All Torrents','library.count':'{count} torrents','library.empty':'No torrents match','library.emptyDesc':'Adjust the filters or add a new torrent.','library.add':'Add Torrent','library.pageSize':'Per page','library.columns':'Columns','library.prev':'Previous','library.next':'Next','library.page':'Page {page} / {pages} · {size} per page','library.range':'{start}–{end} / {total}','library.refreshed':'Refreshed','library.readFailed':'Failed to load torrents: {error}',
    'search.torrents':'Search torrents…','search.settings':'Search settings…','search.logs':'Search logs…','search.rss':'Search RSS…','search.engine':'Search engine…','search.title':'Search Engine','search.description':'Search through qBittorrent Search API.','search.query':'Search query','search.start':'Search','search.stop':'Stop','search.unsupported':'This WebAPI does not support Search API.','search.failed':'Search failed: {error}',
    'rss.title':'RSS','rss.feedUrl':'RSS Feed URL','rss.add':'Add Feed','rss.refresh':'Refresh','rss.empty':'No RSS feeds yet.','rss.unsupported':'This WebAPI does not support RSS.','rss.failed':'RSS failed: {error}',
    'logs.title':'Logs','logs.unsupported':'This WebAPI does not provide the log endpoint.','logs.failed':'Failed to load logs: {error}',
    'logs.ui.normal':'Normal','logs.ui.info':'Info','logs.ui.warning':'Warning','logs.ui.critical':'Critical','logs.ui.unknown':'Unknown','logs.ui.follow':'Follow latest','logs.ui.compact':'Compact','logs.ui.auto':'Auto','logs.ui.max':'Max','logs.ui.refresh':'Refresh','logs.ui.log':'Log','logs.ui.time':'Time','logs.ui.level':'Level','logs.ui.empty':'No logs match the current filters.','logs.ui.showing':'Showing {shown} / {total} · newest first','logs.ui.stream':'incremental log stream','logs.ui.unsupported':'This qBittorrent instance does not expose the log API.','logs.ui.failed':'Failed to read logs: {error}','logs.ui.timeZone':'Time zone','logs.ui.timeZoneSearch':'Search time zones…',
    'stats.download':'Download Speed','stats.upload':'Upload Speed','stats.network':'Network','stats.torrent':'Torrents','stats.globalDownload':'Global download rate','stats.globalUpload':'Global upload rate','stats.connection':'Connection status','stats.firewalled':'Firewalled','stats.connected':'Connected','stats.disconnected':'Disconnected','stats.error':'Error','stats.dhtPeers':'DHT {dht} · Peers {peers}',
    'torrent.start':'Start','torrent.pause':'Pause','torrent.stop':'Stop','torrent.delete':'Delete','torrent.deleteData':'Also delete downloaded files','torrent.deleteSelected':'Delete {count} selected torrents?','torrent.actions':'Torrent Actions','torrent.forceStart':'Force Start','torrent.recheck':'Force Recheck','torrent.reannounce':'Reannounce','torrent.sequential':'Sequential Download','torrent.firstLast':'First/Last Piece Priority','torrent.autoTmm':'Automatic Torrent Management','torrent.top':'Move to Top','torrent.bottom':'Move to Bottom','torrent.rename':'Rename','torrent.location':'Set Location','torrent.category':'Set Category','torrent.addTags':'Add Tags','torrent.downloadLimit':'Download Limit (KiB/s)','torrent.uploadLimit':'Upload Limit (KiB/s)','torrent.details':'View Details','torrent.commandSent':'Command sent','torrent.actionFailed':'Action failed: {error}','torrent.added':'Torrent added','torrent.addFailed':'Failed to add torrent: {error}','torrent.name':'Name','torrent.size':'Size','torrent.progress':'Progress','torrent.download':'Download','torrent.upload':'Upload','torrent.eta':'ETA','torrent.status':'Status','torrent.ratio':'Ratio','torrent.tracker':'Tracker','torrent.categoryColumn':'Category',
    
    'detail.eyebrow':'TORRENT DETAIL','detail.overview':'Overview','detail.files':'Files','detail.trackers':'Trackers','detail.peers':'Peers','detail.webseeds':'HTTP Sources','detail.loading':'Loading…','detail.title':'Torrent Details','detail.savePath':'Save path','detail.totalSize':'Total size','detail.downloaded':'Downloaded','detail.uploaded':'Uploaded','detail.shareRatio':'Share ratio','detail.connections':'Connections','detail.seeds':'Seeds','detail.peersCount':'Peers','detail.addedOn':'Added on','detail.completedOn':'Completed on','detail.createdBy':'Created by','detail.pieces':'Pieces','detail.noWebseeds':'This torrent has no Web Seed / HTTP Source.','file.skip':'Skip','file.normal':'Normal','file.high':'High','file.maximum':'Maximum','file.updated':'File priority updated','tracker.add':'Add Tracker','tracker.remove':'Remove','tracker.edit':'Edit','peer.ban':'Ban Peer','peer.banned':'Peer banned',
    'settings.eyebrow':'SETTINGS','settings.title':'Settings','settings.save':'Save','settings.search':'Search settings…','settings.currentOnly':'Only preferences returned by this qBittorrent instance are shown.','settings.none':'This version does not return settings in this group.','settings.readFailed':'Failed to load settings: {error}','settings.saved':'qBittorrent settings saved','settings.noChanges':'No qBittorrent setting changes to save','settings.saveFailed':'Failed to save settings: {error}','settings.interface':'Interface','settings.interfaceDesc':'Typography, density, language, pagination and visual behavior use shared design tokens.','settings.performance':'Performance','settings.performanceDesc':'Developer and rendering diagnostics live here instead of the main torrent view.','settings.language':'Language','settings.languageDesc':'This is the qBittorrent interface language. Both language controls share the same preference.','settings.theme':'Appearance','settings.fontSize':'Font size','settings.density':'Interface density','settings.starfield':'Starfield','settings.motion':'Motion','settings.pageSize':'Torrents per page','settings.refresh':'Refresh interval','settings.ptRules':'4.x PT tracker rules','settings.ptRulesDesc':'qBittorrent 4.x has no precise private flag. Match tracker hostnames here, comma-separated.','settings.global':'Global interface setting','settings.theme.system':'System','settings.theme.dark':'Dark','settings.theme.light':'Light','settings.size.standard':'Standard','settings.size.large':'Large (+2px)','settings.size.xlarge':'Extra large (+3px)','settings.density.compact':'Compact','settings.density.standard':'Standard','settings.density.comfortable':'Comfortable','settings.off':'Off','settings.subtle':'Subtle','settings.full':'Full','settings.reduced':'Reduced','settings.seconds':'{n} seconds','settings.cache':'Library cache','settings.pageData':'Current page data','settings.dom':'Current DOM','settings.apiPage':'API page size','settings.refreshInterval':'Refresh interval','settings.trackerIndex':'Tracker index','settings.complete':'Complete','settings.building':'Building',
    'columns.title':'Columns','columns.reset':'Restore defaults','columns.done':'Done',
    'dialog.add.eyebrow':'ADD TORRENT','dialog.add.or':'or','dialog.add.savePath':'Save path (optional)','dialog.delete.eyebrow':'DANGER','dialog.delete.title':'Delete Torrent','dialog.delete.confirm':'Confirm Delete','dialog.action.eyebrow':'ACTION','dialog.action.title':'Action','dialog.action.value':'Value','selection.newCategory':'New category…','selection.resetCategory':'Reset','selection.removeAllTags':'Remove all','selection.categoryName':'Category name','selection.categorySavePath':'Save path','selection.categoryDownloadPath':'Download path','selection.categoryDownloadPathEnabled':'Use download path',
    'fatal.title':'WebUI cannot continue','fatal.unknown':'An unknown error occurred.','status.refresh':'Refresh {time}',
    'language.en':'English','language.zh-CN':'简体中文','language.zh-TW':'繁體中文','language.zh-HK':'香港正體字','language.ja':'日本語','language.ko':'한국어'
  };
  var ZH={
    'app.skip':'跳到种子列表','app.back':'返回','app.home':'首页','app.reload':'重载','app.refresh':'刷新','app.theme':'切换主题','app.menu':'打开导航','app.close':'关闭','app.cancel':'取消','app.confirm':'确认','app.done':'完成','app.reset':'恢复默认','app.more':'更多','app.loading':'正在加载…','app.connected':'WeiG qB WebUI 已连接','app.compatible':'已适配','app.compatMode':'兼容模式','app.detecting':'检测中…',
    'nav.torrents':'种子','nav.search':'搜索','nav.rss':'RSS','nav.logs':'日志','nav.settings':'设置','nav.more':'更多',
    'sidebar.torrents':'种子','sidebar.trackers':'Tracker','sidebar.savePath':'保存路径','sidebar.categories':'分类','sidebar.tags':'标签','sidebar.connection':'连接',
    'tracker.all':'全部 Tracker','tracker.none':'无 Tracker','tracker.indexing':'正在建立 Tracker 索引…','path.all':'全部路径','category.all':'全部分类','tag.all':'全部标签',
    'library.eyebrow':'资源库','library.all':'全部种子','library.count':'共 {count} 个 Torrent','library.empty':'没有符合条件的种子','library.emptyDesc':'调整筛选条件，或添加新的 Torrent。','library.add':'添加种子','library.pageSize':'每页','library.columns':'列设置','library.prev':'上一页','library.next':'下一页','library.page':'第 {page} / {pages} 页 · 每页 {size}','library.range':'{start}–{end} / {total}','library.refreshed':'已刷新','library.readFailed':'读取种子失败：{error}',
    'search.torrents':'搜索种子…','search.settings':'搜索设置…','search.logs':'搜索日志…','search.rss':'搜索 RSS…','search.engine':'搜索引擎…','search.title':'搜索引擎','search.description':'使用 qBittorrent Search API 搜索。','search.query':'搜索关键词','search.start':'搜索','search.stop':'停止','search.unsupported':'当前 WebAPI 不支持 Search API。','search.failed':'搜索失败：{error}',
    'rss.feedUrl':'RSS Feed URL','rss.add':'添加 Feed','rss.refresh':'刷新','rss.empty':'还没有 RSS Feed。','rss.unsupported':'当前 WebAPI 不支持 RSS。','rss.failed':'RSS 读取失败：{error}',
    'logs.title':'日志','logs.unsupported':'当前 WebAPI 不提供日志接口。','logs.failed':'日志读取失败：{error}',
    'logs.ui.normal':'普通','logs.ui.info':'信息','logs.ui.warning':'警告','logs.ui.critical':'严重','logs.ui.unknown':'未知','logs.ui.follow':'跟随最新','logs.ui.compact':'紧凑','logs.ui.auto':'自动','logs.ui.max':'最大','logs.ui.refresh':'刷新','logs.ui.log':'日志','logs.ui.time':'时间','logs.ui.level':'级别','logs.ui.empty':'没有符合当前条件的日志。','logs.ui.showing':'显示 {shown} / {total} · 最新在最上方','logs.ui.stream':'增量日志流','logs.ui.unsupported':'当前 qBittorrent 实例不提供日志 API。','logs.ui.failed':'日志读取失败：{error}','logs.ui.timeZone':'时区','logs.ui.timeZoneSearch':'搜索时区…',
    'stats.download':'下载速度','stats.upload':'上传速度','stats.network':'网络','stats.torrent':'种子','stats.globalDownload':'全局实时下载','stats.globalUpload':'全局实时上传','stats.connection':'连接状态','stats.firewalled':'防火墙限制','stats.connected':'已连接','stats.disconnected':'已断开','stats.error':'异常','stats.dhtPeers':'DHT {dht} · Peers {peers}',
    'torrent.start':'开始','torrent.pause':'暂停','torrent.stop':'停止','torrent.delete':'删除','torrent.deleteData':'同时删除下载的数据文件','torrent.deleteSelected':'确定删除选中的 {count} 个种子吗？','torrent.actions':'更多操作','torrent.forceStart':'强制开始','torrent.recheck':'重新校验','torrent.reannounce':'重新汇报','torrent.sequential':'顺序下载','torrent.firstLast':'首尾块优先','torrent.autoTmm':'自动 Torrent 管理','torrent.top':'队列置顶','torrent.bottom':'队列置底','torrent.rename':'重命名','torrent.location':'移动位置','torrent.category':'设置分类','torrent.addTags':'添加 Tags','torrent.downloadLimit':'下载限速 (KiB/s)','torrent.uploadLimit':'上传限速 (KiB/s)','torrent.details':'查看详情','torrent.commandSent':'命令已发送','torrent.actionFailed':'操作失败：{error}','torrent.added':'种子已添加','torrent.addFailed':'添加失败：{error}','torrent.name':'名称','torrent.size':'大小','torrent.progress':'进度','torrent.download':'下载','torrent.upload':'上传','torrent.status':'状态','torrent.categoryColumn':'分类',
    
    'detail.eyebrow':'种子详情','detail.overview':'概览','detail.files':'文件','detail.trackers':'Trackers','detail.peers':'Peers','detail.webseeds':'HTTP 来源','detail.loading':'正在加载…','detail.title':'种子详情','detail.savePath':'保存路径','detail.totalSize':'总大小','detail.downloaded':'已下载','detail.uploaded':'已上传','detail.shareRatio':'分享率','detail.connections':'连接数','detail.seeds':'Seeds','detail.peersCount':'Peers','detail.addedOn':'添加时间','detail.completedOn':'完成时间','detail.createdBy':'创建者','detail.pieces':'分块','detail.noWebseeds':'当前种子没有 Web Seed / HTTP Source。','file.skip':'跳过','file.normal':'正常','file.high':'高','file.maximum':'最高','file.updated':'文件优先级已更新','tracker.add':'添加 Tracker','tracker.remove':'删除','tracker.edit':'编辑','peer.ban':'封禁 Peer','peer.banned':'Peer 已封禁',
    'settings.eyebrow':'设置','settings.title':'设置','settings.save':'保存','settings.search':'搜索设置…','settings.currentOnly':'只显示当前 qBittorrent 实际返回的 Preferences。','settings.none':'当前版本没有返回这一组设置。','settings.readFailed':'读取设置失败：{error}','settings.saved':'qBittorrent 设置已保存','settings.noChanges':'没有需要保存的 qB 设置','settings.saveFailed':'保存失败：{error}','settings.interface':'界面','settings.interfaceDesc':'字体、密度、语言、分页和视觉行为统一使用设计 Token。','settings.performance':'性能','settings.performanceDesc':'开发和渲染诊断信息放在这里，不占主界面。','settings.language':'语言','settings.languageDesc':'这里直接修改 qBittorrent 的界面语言；两个语言入口共享同一个 preference。','settings.theme':'外观','settings.fontSize':'字体大小','settings.density':'界面密度','settings.starfield':'星空','settings.motion':'动画','settings.pageSize':'每页 Torrent','settings.refresh':'刷新频率','settings.ptRules':'4.x PT Tracker 规则','settings.ptRulesDesc':'qBittorrent 4.x 没有精确 Private 字段；这里按 Tracker 域名识别，使用逗号分隔。','settings.global':'统一全局设置','settings.theme.system':'跟随系统','settings.theme.dark':'深色','settings.theme.light':'浅色','settings.size.standard':'标准','settings.size.large':'大（+2px）','settings.size.xlarge':'特大（+3px）','settings.density.compact':'紧凑','settings.density.standard':'标准','settings.density.comfortable':'宽松','settings.off':'关闭','settings.subtle':'柔和','settings.full':'完整','settings.reduced':'减少','settings.seconds':'{n} 秒','settings.cache':'全库缓存','settings.pageData':'当前页数据','settings.dom':'当前 DOM','settings.apiPage':'API 每页','settings.refreshInterval':'刷新间隔','settings.trackerIndex':'Tracker 索引','settings.complete':'完成','settings.building':'构建中',
    'columns.title':'列设置','columns.reset':'恢复默认','columns.done':'完成','dialog.add.or':'或','dialog.add.savePath':'保存路径（可选）','dialog.delete.title':'删除种子','dialog.delete.confirm':'确认删除','dialog.action.title':'操作','dialog.action.value':'值','selection.newCategory':'新分类…','selection.resetCategory':'重置','selection.removeAllTags':'删除全部','selection.categoryName':'分类名称','selection.categorySavePath':'保存路径','selection.categoryDownloadPath':'下载路径','selection.categoryDownloadPathEnabled':'使用下载路径','fatal.title':'WebUI 无法继续加载','fatal.unknown':'发生未知错误。','status.refresh':'刷新 {time}'
  };
  var SUPPORTED_LOCALES=["en","zh-CN","zh-TW","zh-HK","ja","ko","de","fr","es","pt","ru"];
  var dicts={en:EN},weigLocaleTasks={};
  function validWeiGOverlay(data,target){return !!(data&&data.schemaVersion===1&&data.source==='WeiG-runtime-locale-overlay'&&data.locale===target&&data.messages&&typeof data.messages==='object'&&!Array.isArray(data.messages));}
  function loadWeiGLocale(target){
    target=String(target||'en');if(target==='en'||dicts[target])return Promise.resolve(dicts[target]||EN);
    if(SUPPORTED_LOCALES.indexOf(target)<0)return Promise.resolve(EN);
    if(weigLocaleTasks[target])return weigLocaleTasks[target];
    var loader=W.RuntimeAssets;if(!loader||typeof loader.readJson!=='function')return Promise.reject(new Error('WeiG locale runtime asset loader unavailable'));
    var task=loader.readJson('data/weig-i18n/'+target+'.json',{namespace:'weig-i18n',identity:target}).then(function(data){
      if(!validWeiGOverlay(data,target))throw new Error('WeiG locale overlay identity mismatch: '+target);
      dicts[target]=Object.assign({},EN,data.messages);return dicts[target];
    }).finally(function(){delete weigLocaleTasks[target];});
    weigLocaleTasks[target]=task;return task;
  }
  var qbLocale='en',locale='en',localeOptions=[],localeTask=null,localeTaskKey='',localeResolvedKey='',localeGeneration=0,localeRevision=0,localeProviderStatus='IDLE',localeInventory={classification:'UNAVAILABLE',selectedOwner:'current-only',sourceCount:0,runtimeCount:0,missing:[],extra:[],domain:null},qbCopyData=null,qbCopyTask=null,qbCopyLocale=null,localeApplied=false,reloadScheduled=false;
  function canonicalQbTag(value){var raw=String(value||'').trim().replace(/@(?:latin|latn)$/i,'-Latn').replace(/_/g,'-');if(!raw)return'';try{if(Intl.getCanonicalLocales)raw=Intl.getCanonicalLocales(raw)[0]||raw;}catch(_e){}return raw;}
  function qbLocaleParts(value){var tag=canonicalQbTag(value);if(!tag)return null;try{var loc=new Intl.Locale(tag),max=loc.maximize?loc.maximize():loc;return{tag:tag,language:String(loc.language||'').toLowerCase(),script:String(loc.script||max.script||''),region:String(loc.region||max.region||'').toUpperCase(),explicitScript:!!loc.script,explicitRegion:!!loc.region};}catch(_e){}var bits=tag.split('-');return{tag:tag,language:String(bits[0]||'').toLowerCase(),script:'',region:'',explicitScript:false,explicitRegion:false};}
  function localeOptionValues(items){var out=[],seen={};(items||[]).forEach(function(item){var value=String(typeof item==='string'?item:item&&item.value||'').trim();if(value&&!seen[value]){seen[value]=true;out.push(value);}});return out;}
  function exactLocaleOption(value,items){var target=canonicalQbTag(value).toLowerCase();if(!target)return null;var values=localeOptionValues(items);for(var i=0;i<values.length;i++)if(canonicalQbTag(values[i]).toLowerCase()===target)return values[i];return null;}
  function sameQbLocale(a,b){var x=canonicalQbTag(a),y=canonicalQbTag(b);return !!x&&!!y&&x.toLowerCase()===y.toLowerCase();}
  function hasExactLocale(value,items){return exactLocaleOption(value,items||localeOptions)!==null;}
  function matchBrowserLocale(languages,items){var values=localeOptionValues(items||localeOptions);if(!values.length)return null;var parsed=values.map(function(value){return{value:value,parts:qbLocaleParts(value)};}).filter(function(x){return x.parts&&x.parts.language;});var wanted=Array.isArray(languages)?languages:[languages];for(var i=0;i<wanted.length;i++){var bp=qbLocaleParts(wanted[i]);if(!bp||!bp.language)continue;var exact=exactLocaleOption(bp.tag,values);if(exact)return exact;var same=parsed.filter(function(x){return x.parts.language===bp.language;});if(!same.length)continue;if(bp.language==='zh'){var targets=[];if(bp.script==='Hans'||bp.region==='CN'||bp.region==='SG')targets=['zh-CN','zh'];else if(bp.region==='HK'||bp.region==='MO')targets=['zh-HK','zh-TW','zh'];else if(bp.script==='Hant'||bp.region==='TW')targets=['zh-TW','zh'];for(var z=0;z<targets.length;z++){var zh=exactLocaleOption(targets[z],values);if(zh)return zh;}}var generic=same.find(function(x){return !x.parts.explicitRegion&&!x.parts.explicitScript&&canonicalQbTag(x.value).indexOf('-')<0;});if(generic)return generic.value;if(bp.explicitScript){var scriptHits=same.filter(function(x){return x.parts.script===bp.script;});if(scriptHits.length===1)return scriptHits[0].value;}if(bp.explicitRegion){var regionHits=same.filter(function(x){return x.parts.region===bp.region;});if(regionHits.length===1)return regionHits[0].value;}if(same.length===1)return same[0].value;}return null;}
  function normalize(tag){var raw=canonicalQbTag(tag||'en')||'en',lower=raw.toLowerCase();if(lower==='zh'||lower==='zh-cn'||lower==='zh-sg'||lower.indexOf('zh-hans')===0)return'zh-CN';if(lower==='zh-hk'||lower==='zh-mo'||lower.indexOf('zh-hant-hk')===0||lower.indexOf('zh-hant-mo')===0)return'zh-HK';if(lower==='zh-tw'||lower.indexOf('zh-hant')===0)return'zh-TW';if(lower.indexOf('ja')===0)return'ja';if(lower.indexOf('ko')===0)return'ko';if(lower.indexOf('de')===0)return'de';if(lower.indexOf('fr')===0)return'fr';if(lower.indexOf('es')===0)return'es';if(lower.indexOf('pt')===0)return'pt';if(lower.indexOf('ru')===0)return'ru';if(lower.indexOf('en')===0)return'en';return raw||'en';}
  function format(value,vars){return String(value).replace(/\{([^}]+)\}/g,function(_,key){return vars&&vars[key]!==undefined?vars[key]:'{'+key+'}';});}
  function t(key,vars){var d=dicts[locale]||EN;return format(d[key]!==undefined?d[key]:(EN[key]!==undefined?EN[key]:key),vars);}
  function applyQbOwned(root){root=root||document;Array.prototype.forEach.call(root.querySelectorAll('[data-qb-owned-text]'),function(el){var key=String(el.dataset.qbOwnedText||''),fallback=String(el.dataset.qbOwnedFallback||el.textContent||'');if(key)el.textContent=qbText(key,fallback);});}
  function apply(root){root=root||document;document.documentElement.lang=locale;Array.prototype.forEach.call(root.querySelectorAll('[data-i18n]'),function(el){el.textContent=t(el.dataset.i18n);});Array.prototype.forEach.call(root.querySelectorAll('[data-i18n-placeholder]'),function(el){el.setAttribute('placeholder',t(el.dataset.i18nPlaceholder));});Array.prototype.forEach.call(root.querySelectorAll('[data-i18n-aria]'),function(el){el.setAttribute('aria-label',t(el.dataset.i18nAria));});Array.prototype.forEach.call(root.querySelectorAll('[data-i18n-title]'),function(el){el.removeAttribute('title');el.setAttribute('aria-label',t(el.dataset.i18nTitle));});applyQbOwned(root);}
  function resetQbCopy(){qbCopyData=null;qbCopyTask=null;qbCopyLocale=null;}
  function applyLocale(value,options){options=options||{};var raw=String(value||'en').trim()||'en',next=normalize(raw),wasApplied=localeApplied,changed=raw!==qbLocale||next!==locale,committed=options.commit===true;qbLocale=raw;locale=next;localeApplied=true;if(changed)resetQbCopy();var paint=function(){apply(document);if(changed)global.dispatchEvent(new CustomEvent('weig:languagechange',{detail:{locale:locale,qbLocale:qbLocale,transient:options.reload===false}}));};if(next==='en'||dicts[next])paint();else loadWeiGLocale(next).then(function(){if(locale===next)paint();}).catch(function(error){try{console.error('[WeiG i18n] locale shard load failed',next,error);}catch(_e){}});if((changed||committed)&&wasApplied&&options.reload!==false&&!reloadScheduled){reloadScheduled=true;setTimeout(function(){global.location.reload();},0);}return locale;}
  function nativeLabel(code){var raw=String(code||'').trim(),tag=canonicalQbTag(raw);try{var loc=new Intl.Locale(tag),language=loc.language,display=new Intl.DisplayNames([tag],{type:'language'}),name=display.of(language);if(!name)return raw;if(language==='zh'){var expanded=loc.maximize?loc.maximize():loc,script=expanded.script?new Intl.DisplayNames([tag],{type:'script'}).of(expanded.script):'';return name+(script?' · '+script:'')+' ('+raw+')';}return name+' ('+raw+')';}catch(_e){}return raw;}
  function normalizeOptions(items){var out=[],seen={},counts={};(items||[]).forEach(function(item){var value=String(item&&item.value||'').trim();if(!value||seen[value])return;seen[value]=true;var label=String(item&&item.label||nativeLabel(value)||value).trim();out.push({value:value,label:label});counts[label]=(counts[label]||0)+1;});out.forEach(function(item){if(counts[item.label]>1)item.label=nativeLabel(item.value)||item.value;});return out;}
  function localeSelect(html){var source=String(html||''),match=source.match(/<select\b[^>]*\bid=["']locale_select["'][^>]*>([\s\S]*?)<\/select>/i)||source.match(/<select\b[^>]*\bid=["']weig-qb-locale-options["'][^>]*>([\s\S]*?)<\/select>/i);return match?match[1]:null;}
  function parseLocaleBody(body){var out=[];for(var match of String(body||'').matchAll(/<option\b[^>]*\bvalue=["']([^"']+)["'][^>]*>([\s\S]*?)<\/option>/gi)){var label=String(match[2]||'').replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').trim();out.push({value:match[1],label:label});}return normalizeOptions(out);}
  function parseLocaleOptions(html){var body=localeSelect(html);return body===null||body.indexOf('${LANGUAGE_OPTIONS}')>=0?[]:parseLocaleBody(body);}
  function profileLocaleOptions(){var R=W.CapabilityRegistry,items=R&&typeof R.webuiLocales==='function'?R.webuiLocales():[];return normalizeOptions(items.map(function(item){return typeof item==='string'?{value:item,label:null}:item;}));}
  function localeKey(value){return canonicalQbTag(value).toLocaleLowerCase();}
  function localeDiff(source,runtime){var sourceKeys=new Map((source||[]).map(function(item){return[localeKey(item.value),item.value];})),runtimeKeys=new Map((runtime||[]).map(function(item){return[localeKey(item.value),item.value];})),missing=[],extra=[];sourceKeys.forEach(function(value,key){if(key&&!runtimeKeys.has(key))missing.push(value);});runtimeKeys.forEach(function(value,key){if(key&&!sourceKeys.has(key))extra.push(value);});return{missing:missing,extra:extra};}
  function localeDomain(){var R=W.CapabilityRegistry;return R&&typeof R.domainResolution==='function'?R.domainResolution('locale'):null;}
  function classifyLocaleProbe(html,baseline){baseline=normalizeOptions(baseline||[]);var body=localeSelect(html);if(body===null)return{classification:'UNAVAILABLE',options:[],missing:baseline.map(function(item){return item.value;}),extra:[]};if(body.indexOf('${LANGUAGE_OPTIONS}')>=0)return{classification:'TEMPLATE_UNRESOLVED',options:[],missing:baseline.map(function(item){return item.value;}),extra:[]};var options=parseLocaleBody(body),diff=localeDiff(baseline,options),complete=options.length>1&&(baseline.length===0||diff.missing.length===0);return{classification:complete?'COMPLETE_NATIVE_SET':'PARTIAL_OR_INVALID',options:options,missing:diff.missing,extra:diff.extra};}
  function setLocaleInventory(result,baseline,selectedOwner){localeInventory={classification:String(result&&result.classification||'UNAVAILABLE'),selectedOwner:String(selectedOwner||'source'),sourceCount:(baseline||[]).length,runtimeCount:result&&Array.isArray(result.options)?result.options.length:0,missing:result&&Array.isArray(result.missing)?result.missing.slice():[],extra:result&&Array.isArray(result.extra)?result.extra.slice():[],domain:localeDomain()};return localeInventory;}
  function localeInventoryEvidence(){return JSON.parse(JSON.stringify(localeInventory));}
  function localeOptionsIdentity(items){return normalizeOptions(items||[]).map(function(item){return String(item.value)+'\u0000'+String(item.label);}).join('\u0001');}
  function localeBaselineKey(baseline){var domain=localeDomain()||{};return[String(domain.detectedQbVersion||''),String(domain.qbVersion||''),String(domain.sourceSha||''),String(domain.resolutionMode||''),localeOptionsIdentity(baseline)].join('\u0002');}
  function settingOptionsState(key){if(String(key||'')!=='locale')return null;return{key:'locale',status:localeProviderStatus,ready:localeProviderStatus==='READY',revision:localeRevision,options:localeOptions.slice(),inventory:localeInventoryEvidence()};}
  function settingOptions(key){if(String(key||'')!=='locale'||!localeOptions.length)return null;return localeOptions.slice();}
  function setLocaleOptions(items,status){var previous=localeOptionsIdentity(localeOptions),previousStatus=localeProviderStatus,next=normalizeOptions(items);if(qbLocale&&!hasExactLocale(qbLocale,next))next.unshift({value:qbLocale,label:nativeLabel(qbLocale)||qbLocale});localeOptions=next;localeProviderStatus=String(status||'READY');api.supported=localeOptions.map(function(item){return item.value;});if(previous!==localeOptionsIdentity(localeOptions)||previousStatus!==localeProviderStatus){localeRevision++;try{global.dispatchEvent(new CustomEvent('weig:setting-optionschange',{detail:{key:'locale',revision:localeRevision,status:localeProviderStatus}}));}catch(_e){}}return localeOptions.slice();}
  function loadLocaleOptions(){var baseline=profileLocaleOptions(),key=localeBaselineKey(baseline);if(localeResolvedKey===key&&localeOptions.length)return Promise.resolve(localeOptions.slice());if(localeTask&&localeTaskKey===key)return localeTask;var generation=++localeGeneration;localeTaskKey=key;localeProviderStatus=baseline.length?'LOADING':'WAITING_SOURCE';localeTask=fetch('views/preferences.html?weig_locale_probe=1',{credentials:'same-origin',cache:'no-store'}).then(function(res){if(!res.ok)throw new Error('qB locale probe HTTP '+res.status);return res.text();}).then(function(html){if(generation!==localeGeneration)return localeOptions.slice();var result=classifyLocaleProbe(html,baseline),useRuntime=result.classification==='COMPLETE_NATIVE_SET',selected=useRuntime?result.options:baseline,owner=useRuntime?'runtime-complete':(baseline.length?'source-baseline':'current-only'),status=(baseline.length||useRuntime)?'READY':'WAITING_SOURCE';setLocaleInventory(result,baseline,owner);localeResolvedKey=key;return setLocaleOptions(selected,status);}).catch(function(){if(generation!==localeGeneration)return localeOptions.slice();var result={classification:'UNAVAILABLE',options:[],missing:baseline.map(function(item){return item.value;}),extra:[]},status=baseline.length?'READY':'WAITING_SOURCE';setLocaleInventory(result,baseline,baseline.length?'source-baseline':'current-only');localeResolvedKey=key;return setLocaleOptions(baseline,status);}).finally(function(){if(generation===localeGeneration)localeTask=null;});return localeTask;}
  function asset(path){return W.buildAssetUrl?W.buildAssetUrl(path):path;}
  function currentProfile(){var R=W.CapabilityRegistry;return R&&typeof R.domainResolution==='function'?R.domainResolution('copy'):null;}
  function decodeField(value){try{return decodeURIComponent(String(value||''));}catch(_e){return String(value||'');}}
  function routeLocale(list){if(!Array.isArray(list))return null;for(var i=0;i<list.length;i++)if(sameQbLocale(list[i],qbLocale))return list[i];var wanted=normalize(qbLocale);for(var j=0;j<list.length;j++)if(normalize(list[j])===wanted)return list[j];return null;}
  function resolveFallbackSet(data,id){
    if(!data||data.schemaVersion!==1||!id)return{};var sets={},defMap=data.sets||{},values=data.values||{};
    function tokens(setId,trail){if(!setId)return[];if(sets[setId])return sets[setId].slice();var def=defMap[setId];if(!def)return null;trail=trail||{};if(trail[setId])return null;trail[setId]=true;var base=def.parent?tokens(def.parent,trail):[];if(base===null)return null;var active={};for(var i=0;i<base.length;i++)active[base[i]]=true;for(var j=0;j<(def.remove||[]).length;j++)delete active[def.remove[j]];for(var k=0;k<(def.add||[]).length;k++)active[def.add[k]]=true;delete trail[setId];var out=Object.keys(active).sort(function(a,b){return parseInt(a,36)-parseInt(b,36);});sets[setId]=out;return out.slice();}
    var list=tokens(id,{});if(list===null)return null;var out={};for(var i=0;i<list.length;i++){var item=values[list[i]];if(!item||!item.ref||typeof item.value!=='string')return null;if(out[item.ref]!==undefined&&out[item.ref]!==item.value)return null;out[item.ref]=item.value;}return out;
  }
  function parseOwnedCopyBinding(text,profile,fallbackData){
    var source=String(text||''),refs={},binding={preferences:{},ui:{}},match,bindingMatch=source.match(/^@@BINDING\t(b[0-9a-f]{20})\s*$/m);
    if(!profile||!bindingMatch||bindingMatch[1]!==profile.bindingId)return null;
    var refRe=/^@@REF\t([0-9a-f]{24})\t([^\t\r\n]*)\t([^\t\r\n]*)\r?\n([\s\S]*?)\r?\n@@END\s*$/gm;
    while((match=refRe.exec(source))){var raw=String(match[4]||'').trim();refs[match[1]]={context:decodeField(match[2]),source:decodeField(match[3]),text:raw&&raw.indexOf('QBT_'+'TR(')<0?raw:null};}
    var prefRe=/^@@PREF\t([^\t\r\n]*)\t([^\t\r\n]*)\t([0-9a-f]{24})\t([0-9a-f]{24}|-)\s*$/gm;
    while((match=prefRe.exec(source)))binding.preferences[decodeField(match[1])]={controlId:decodeField(match[2])||null,title:match[3],description:match[4]==='-'?null:match[4]};
    var uiRe=/^@@UI\t([^\t\r\n]*)\t([0-9a-f]{24})\s*$/gm;
    while((match=uiRe.exec(source)))binding.ui[decodeField(match[1])]=match[2];
    var nativeLocale=routeLocale(profile.nativeLocales),fallbackLocale=nativeLocale?null:routeLocale(profile.fallbackLocales),mode=nativeLocale?'native':(fallbackLocale?'fallback':null);if(!mode)return null;
    var fallbackSet={};if(mode==='fallback'){var setId=profile.fallbackSets&&profile.fallbackSets[fallbackLocale];if(setId){fallbackSet=resolveFallbackSet(fallbackData,setId);if(fallbackSet===null)return null;}}
    function resolve(id){var ref=refs[id];if(!ref)return null;if(mode==='fallback')return String(fallbackSet[id]!==undefined?fallbackSet[id]:ref.source);return ref.text===null?null:String(ref.text);}
    var preferences={},ui={},resolvedRefs={},addRefs={},unresolved=false;
    Object.keys(refs).forEach(function(id){var value=resolve(id),ref=refs[id];if(value!==null)resolvedRefs[ref.context+'\u0000'+ref.source]=value;});
    Object.keys(binding.preferences).forEach(function(key){var entry=binding.preferences[key],title=resolve(entry.title),description=entry.description?resolve(entry.description):'';if(title===null||description===null){unresolved=true;return;}preferences[key]={title:title,description:description||'',controlId:entry.controlId||null};});
    Object.keys(binding.ui).forEach(function(key){var ref=refs[binding.ui[key]],value=resolve(binding.ui[key]);if(value===null){unresolved=true;return;}ui[key]=value;if(key.indexOf('add.copy.')===0&&ref)addRefs[ref.context+'\u0000'+ref.source]=true;});
    if(mode==='native'&&unresolved)return null;
    return{schemaVersion:3,source:mode==='native'?'qb-native-QBT_TR+official-QM':'qb-exact-official-fallback-shard',sourceSha:profile.sourceSha,qbVersion:profile.qbVersion,locale:qbLocale,mode:mode,preferences:preferences,ui:ui,resolvedRefs:resolvedRefs,addRefs:addRefs};
  }
  function loadQbOwnedCopy(){
    var current=currentProfile();if(!current||current.fallback)return Promise.resolve(null);var expectedSha=String(current.sourceSha||''),expectedVersion=String(current.qbVersion||''),loader=W.RuntimeAssets;if(!/^[0-9a-f]{40}$/.test(expectedSha)||!expectedVersion||!loader)return Promise.resolve(null);
    if(qbCopyData&&qbCopyData.sourceSha===expectedSha&&qbCopyData.qbVersion===expectedVersion&&qbCopyLocale===qbLocale)return Promise.resolve(qbCopyData);if(qbCopyTask)return qbCopyTask;qbCopyLocale=qbLocale;
    var profilePath='data/qb-copy-profiles/'+expectedSha+'.json',profileIdentity=expectedSha+'@'+expectedVersion;
    qbCopyTask=loader.readJson(profilePath,{namespace:'qb-copy-profile',identity:profileIdentity}).then(function(profile){
      if(!profile||profile.schemaVersion!==1||profile.source!=='qB-source-context-runtime-copy-profile'||String(profile.sourceSha)!==expectedSha||String(profile.qbVersion)!==expectedVersion||!/^b[0-9a-f]{20}$/.test(String(profile.bindingId||'')))throw new Error('qB-owned copy profile identity mismatch');
      var nativeLocale=routeLocale(profile.nativeLocales),fallbackLocale=nativeLocale?null:routeLocale(profile.fallbackLocales);if(!nativeLocale&&!fallbackLocale)throw new Error('qB-owned copy locale route unavailable');
      var route=nativeLocale||fallbackLocale,bindingTask=loader.readText('data/qb-copy-bindings/'+profile.bindingId+'.txt',{namespace:'qb-copy-binding',identity:expectedSha+'@'+route}),fallbackTask=Promise.resolve(null),setId=fallbackLocale&&profile.fallbackSets&&profile.fallbackSets[fallbackLocale];
      if(fallbackLocale&&setId){var major=expectedVersion.split('.')[0];fallbackTask=loader.readJson('data/qb-copy-fallback/'+major+'/'+fallbackLocale+'.json',{namespace:'qb-copy-fallback',identity:major+'@'+fallbackLocale});}
      return Promise.all([bindingTask,fallbackTask]).then(function(parts){var value=parseOwnedCopyBinding(parts[0],profile,parts[1]);if(!value)throw new Error('qB-owned copy shard is unresolved');return value;});
    }).then(function(value){qbCopyData=value;applyQbOwned(document);try{global.dispatchEvent(new CustomEvent('weig:qbcopychange',{detail:{locale:qbLocale,qbVersion:expectedVersion,sourceSha:expectedSha}}));}catch(_e){}return value;}).catch(function(){qbCopyData=null;return null;}).finally(function(){qbCopyTask=null;});return qbCopyTask;
  }
  function resolvedQbCopy(){var current=currentProfile();if(!qbCopyData||!current||current.fallback||qbCopyLocale!==qbLocale)return null;if(String(qbCopyData.qbVersion)!==String(current.qbVersion)||String(qbCopyData.sourceSha)!==String(current.sourceSha))return null;return qbCopyData;}
  function qbSetting(key){var data=resolvedQbCopy(),entry=data&&data.preferences&&data.preferences[key];if(!entry)return null;return{title:entry.title,description:entry.description||'',source:data.source,controlId:entry.controlId||null};}
  function qbOwnedText(){var data=resolvedQbCopy();return data&&data.ui?Object.assign({},data.ui):{};}
  function qbSourceText(ref,fallback){var data=resolvedQbCopy(),context=ref&&String(ref.context||''),source=ref&&String(ref.source||'');if(!context||!source)return String(fallback||source||'');var value=data&&data.resolvedRefs?data.resolvedRefs[context+'\u0000'+source]:undefined;return String(value!==undefined&&value!==null?value:(fallback||source));}
  function qbAddSourceHas(ref){var data=resolvedQbCopy(),context=ref&&String(ref.context||''),source=ref&&String(ref.source||'');return !!(context&&source&&data&&data.addRefs&&data.addRefs[context+'\u0000'+source]);}
  function qbText(key,fallback){var values=qbOwnedText(),value=values[key];return String(value!==undefined&&value!==null&&value!==''?value:(fallback||''));}
  var ADD_SOURCE_FIELDS={
    'add-auto-tmm':[['autoTMM'],[['Torrent Management Mode:','AddNewTorrentDialog']]],
    'save-path':[['savepath'],[['Save files to location:','AddNewTorrentDialog'],['Save files to location:','HttpServer']]],
    'add-use-download-path':[['useDownloadPath'],[['Use another path for incomplete torrent','AddNewTorrentDialog']]],
    'add-download-path':[['downloadPath'],[['Save path:','AddNewTorrentDialog']]],
    'add-rename':[['rename'],[['Rename torrent','AddNewTorrentDialog'],['Rename torrent','HttpServer']]],
    'add-category':[['category'],[['Category:','AddNewTorrentDialog']]],
    'add-tags':[['tags'],[['Tags:','AddNewTorrentDialog']]],
    'add-cookie':[['cookie'],[['Cookie:','HttpServer']]],
    'add-start':[['stopped','paused'],[['Start torrent','AddNewTorrentDialog']]],
    'add-queue-top':[['addToTopOfQueue'],[['Add to top of queue','AddNewTorrentDialog']]],
    'add-stop-condition':[['stopCondition'],[['Stop condition:','AddNewTorrentDialog']]],
    'add-skip-check':[['skip_checking'],[['Skip hash check','AddNewTorrentDialog']]],
    'add-sequential':[['sequentialDownload'],[['Download in sequential order','AddNewTorrentDialog'],['Download in sequential order','TransferListWidget']]],
    'add-first-last':[['firstLastPiecePrio'],[['Download first and last pieces first','AddNewTorrentDialog'],['Download first and last pieces first','TransferListWidget']]],
    'add-content-layout':[['contentLayout','root_folder'],[['Content layout:','AddNewTorrentDialog'],['Create subfolder','AddNewTorrentDialog']]],
    'add-dl-limit':[['dlLimit'],[['Limit download rate','AddNewTorrentDialog'],['Limit download rate','HttpServer']]],
    'add-up-limit':[['upLimit'],[['Limit upload rate','AddNewTorrentDialog'],['Limit upload rate','HttpServer']]],
    'add-ratio-limit':[['ratioLimit'],[['ratio','UpDownRatioDialog']]],
    'add-seeding-time':[['seedingTimeLimit'],[['total minutes','UpDownRatioDialog']]],
    'add-inactive-seeding-time':[['inactiveSeedingTimeLimit'],[['inactive minutes','UpDownRatioDialog']]],
    'add-share-action':[['shareLimitAction'],[['Action when the limit is reached','UpDownRatioDialog']]]
  };
  function addFieldRef(refs){for(var i=0;i<(refs||[]).length;i++){var pair=refs[i],ref={source:String(pair[0]||''),context:String(pair[1]||'')};if(qbAddSourceHas(ref))return ref;}return null;}
  function qbAddSourceField(id,fallback){var spec=ADD_SOURCE_FIELDS[String(id||'')];if(!spec)return null;var ref=addFieldRef(spec[1]);return{parameters:spec[0].slice(),ref:ref,visible:!!ref,text:ref?qbSourceText(ref,fallback||ref.source):String(fallback||'')};}
  function qbAddSourceCopy(refs,fallback){var ref=addFieldRef(refs);return{ref:ref,visible:!!ref,text:ref?qbSourceText(ref,fallback||ref.source):String(fallback||'')};}
  function qbAddSourceGroup(key,fallback){var refs={save:[['Save at','AddNewTorrentDialog']],settings:[['Torrent settings','AddNewTorrentDialog']]}[String(key||'')]||[];return qbAddSourceCopy(refs,fallback);}
  function loadQbOwnedText(){return loadQbOwnedCopy().then(function(){return qbOwnedText();});}
  function ready(){return Promise.all([loadWeiGLocale(locale),loadLocaleOptions(),loadQbOwnedCopy()]).then(function(){apply(document);return api;});}
  var api={t:t,apply:apply,applyQbOwned:applyQbOwned,applyLocale:applyLocale,getLocale:function(){return locale;},getQbLocale:function(){return qbLocale;},normalize:normalize,canonicalQbTag:canonicalQbTag,sameQbLocale:sameQbLocale,hasExactLocale:hasExactLocale,matchBrowserLocale:matchBrowserLocale,parseLocaleOptions:parseLocaleOptions,parseOwnedCopyBinding:parseOwnedCopyBinding,loadLocaleOptions:loadLocaleOptions,localeOptions:function(){return localeOptions.slice();},settingOptions:settingOptions,settingOptionsState:settingOptionsState,localeInventoryEvidence:localeInventoryEvidence,loadQbOwnedCopy:loadQbOwnedCopy,loadQbOwnedText:loadQbOwnedText,qbOwnedText:qbOwnedText,qbSetting:qbSetting,qbSourceText:qbSourceText,qbAddSourceHas:qbAddSourceHas,qbAddSourceField:qbAddSourceField,qbAddSourceCopy:qbAddSourceCopy,qbAddSourceGroup:qbAddSourceGroup,qbText:qbText,ready:ready,supported:SUPPORTED_LOCALES.slice(),english:EN,loadWeiGLocale:loadWeiGLocale};
  W.I18n=api;W.t=t;
})(window);
