(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{};
  var EN={
    'app.skip':'Skip to torrent list','app.back':'Back','app.home':'Home','app.reload':'Reload','app.refresh':'Refresh','app.theme':'Toggle theme','app.menu':'Open navigation','app.close':'Close','app.cancel':'Cancel','app.confirm':'Confirm','app.done':'Done','app.reset':'Reset','app.more':'More','app.loading':'Loading…','app.connected':'WeiG qB WebUI connected','app.compatible':'Adapted','app.compatMode':'Compatibility mode','app.detecting':'Detecting…',
    'nav.torrents':'Torrents','nav.search':'Search','nav.rss':'RSS','nav.logs':'Logs','nav.settings':'Settings','nav.more':'More',
    'sidebar.torrents':'TORRENTS','sidebar.trackers':'TRACKERS','sidebar.savePath':'SAVE PATH','sidebar.categories':'CATEGORIES','sidebar.tags':'TAGS','sidebar.connection':'CONNECTION',
    'filter.all':'All','filter.downloading':'Downloading','filter.seeding':'Seeding','filter.completed':'Completed','filter.paused':'Paused','filter.active':'Active','filter.stalled':'Stalled','filter.error':'Error','filter.private':'Private / PT',
    'tracker.all':'All Trackers','tracker.none':'No Tracker','tracker.indexing':'Building Tracker index…','path.all':'All Paths','category.all':'All Categories','tag.all':'All Tags',
    'library.eyebrow':'LIBRARY','library.all':'All Torrents','library.count':'{count} torrents','library.empty':'No torrents match','library.emptyDesc':'Adjust the filters or add a new torrent.','library.add':'Add Torrent','library.pageSize':'Per page','library.columns':'Columns','library.prev':'Previous','library.next':'Next','library.page':'Page {page} / {pages} · {size} per page','library.range':'{start}–{end} / {total}','library.refreshing':'Refreshing torrents…','library.refreshed':'Refreshed','library.readFailed':'Failed to load torrents: {error}',
    'search.torrents':'Search torrents…','search.settings':'Search settings…','search.logs':'Search logs…','search.rss':'Search RSS…','search.engine':'Search engine…','search.title':'Search Engine','search.description':'Search through qBittorrent Search API.','search.query':'Search query','search.start':'Search','search.stop':'Stop','search.unsupported':'This WebAPI does not support Search API.','search.failed':'Search failed: {error}',
    'rss.title':'RSS','rss.description':'Feeds, articles and compatible RSS actions.','rss.feedUrl':'RSS Feed URL','rss.add':'Add Feed','rss.refresh':'Refresh','rss.empty':'No RSS feeds yet.','rss.unsupported':'This WebAPI does not support RSS.','rss.failed':'Failed to load RSS: {error}',
    'logs.title':'Logs','logs.description':'qBittorrent execution log. Large lists remain windowed.','logs.unsupported':'This WebAPI does not provide the log endpoint.','logs.failed':'Failed to load logs: {error}',
    'stats.download':'Download Speed','stats.upload':'Upload Speed','stats.network':'Network','stats.torrent':'Torrents','stats.globalDownload':'Global download rate','stats.globalUpload':'Global upload rate','stats.connection':'Connection status','stats.firewalled':'Firewalled','stats.connected':'Connected','stats.disconnected':'Disconnected','stats.error':'Error','stats.dhtPeers':'DHT {dht} · Peers {peers}',
    'torrent.start':'Start','torrent.pause':'Pause','torrent.stop':'Stop','torrent.delete':'Delete','torrent.deleteData':'Also delete downloaded files','torrent.deleteSelected':'Delete {count} selected torrents?','torrent.actions':'Torrent Actions','torrent.forceStart':'Force Start','torrent.recheck':'Force Recheck','torrent.reannounce':'Reannounce','torrent.sequential':'Sequential Download','torrent.firstLast':'First/Last Piece Priority','torrent.autoTmm':'Automatic Torrent Management','torrent.top':'Move to Top','torrent.bottom':'Move to Bottom','torrent.rename':'Rename','torrent.location':'Set Location','torrent.category':'Set Category','torrent.addTags':'Add Tags','torrent.downloadLimit':'Download Limit (KiB/s)','torrent.uploadLimit':'Upload Limit (KiB/s)','torrent.details':'View Details','torrent.commandSent':'Command sent','torrent.actionFailed':'Action failed: {error}','torrent.added':'Torrent added','torrent.addFailed':'Failed to add torrent: {error}','torrent.name':'Name','torrent.size':'Size','torrent.progress':'Progress','torrent.download':'Download','torrent.upload':'Upload','torrent.eta':'ETA','torrent.status':'Status','torrent.ratio':'Ratio','torrent.tracker':'Tracker','torrent.categoryColumn':'Category',
    'state.downloading':'Downloading','state.metaDL':'Downloading metadata','state.forcedDL':'Forced downloading','state.allocating':'Allocating','state.checkingDL':'Checking','state.checkingUP':'Checking','state.checkingResumeData':'Checking resume data','state.moving':'Moving','state.uploading':'Seeding','state.stalledUP':'Stalled seeding','state.forcedUP':'Forced seeding','state.queuedUP':'Queued seeding','state.pausedDL':'Paused','state.pausedUP':'Paused','state.stoppedDL':'Stopped','state.stoppedUP':'Stopped','state.queuedDL':'Queued download','state.stalledDL':'Stalled download','state.error':'Error','state.missingFiles':'Missing files','state.unknown':'Unknown',
    'detail.eyebrow':'TORRENT DETAIL','detail.overview':'Overview','detail.files':'Files','detail.trackers':'Trackers','detail.peers':'Peers','detail.webseeds':'HTTP Sources','detail.loading':'Loading…','detail.title':'Torrent Details','detail.savePath':'Save path','detail.totalSize':'Total size','detail.downloaded':'Downloaded','detail.uploaded':'Uploaded','detail.shareRatio':'Share ratio','detail.connections':'Connections','detail.seeds':'Seeds','detail.peersCount':'Peers','detail.addedOn':'Added on','detail.completedOn':'Completed on','detail.createdBy':'Created by','detail.pieces':'Pieces','detail.noWebseeds':'This torrent has no Web Seed / HTTP Source.','file.skip':'Skip','file.normal':'Normal','file.high':'High','file.maximum':'Maximum','file.updated':'File priority updated','tracker.add':'Add Tracker','tracker.remove':'Remove','tracker.edit':'Edit','tracker.status':'Status {status} · Seeds {seeds}','peer.ban':'Ban Peer','peer.banned':'Peer banned',
    'settings.eyebrow':'SETTINGS','settings.title':'Settings','settings.description':'Interface preferences and qBittorrent settings supported by this instance.','settings.save':'Save','settings.search':'Search settings…','settings.weigg':'WeiG WebUI','settings.downloads':'Downloads','settings.connection':'Connection','settings.speed':'Speed','settings.bittorrent':'BitTorrent','settings.webui':'Web UI','settings.advanced':'Advanced','settings.currentOnly':'Only preferences returned by this qBittorrent instance are shown.','settings.none':'This version does not return settings in this group.','settings.readFailed':'Failed to load settings: {error}','settings.saved':'qBittorrent settings saved','settings.noChanges':'No qBittorrent setting changes to save','settings.saveFailed':'Failed to save settings: {error}','settings.interface':'Interface','settings.interfaceDesc':'Typography, density, language, pagination and visual behavior use shared design tokens.','settings.performance':'Performance','settings.performanceDesc':'Developer and rendering diagnostics live here instead of the main torrent view.','settings.language':'Language','settings.languageDesc':'Automatic follows the browser; unsupported locales fall back to English.','settings.autoLanguage':'Automatic (Browser)','settings.theme':'Appearance','settings.fontSize':'Font size','settings.density':'Interface density','settings.starfield':'Starfield','settings.motion':'Motion','settings.pageSize':'Torrents per page','settings.refresh':'Refresh interval','settings.ptRules':'4.x PT tracker rules','settings.ptRulesDesc':'qBittorrent 4.x has no precise private flag. Match tracker hostnames here, comma-separated.','settings.global':'Global interface setting','settings.theme.system':'System','settings.theme.dark':'Dark','settings.theme.light':'Light','settings.size.standard':'Standard','settings.size.large':'Large (+2px)','settings.size.xlarge':'Extra large (+3px)','settings.density.compact':'Compact','settings.density.standard':'Standard','settings.density.comfortable':'Comfortable','settings.off':'Off','settings.subtle':'Subtle','settings.full':'Full','settings.reduced':'Reduced','settings.seconds':'{n} seconds','settings.cache':'Library cache','settings.pageData':'Current page data','settings.dom':'Current DOM','settings.apiPage':'API page size','settings.refreshInterval':'Refresh interval','settings.trackerIndex':'Tracker index','settings.complete':'Complete','settings.building':'Building',
    'columns.title':'Columns','columns.reset':'Restore defaults','columns.done':'Done',
    'dialog.add.eyebrow':'ADD TORRENT','dialog.add.title':'Add Torrent','dialog.add.urls':'Magnet / URL','dialog.add.or':'or','dialog.add.files':'Choose .torrent files','dialog.add.multi':'Multiple files allowed','dialog.add.savePath':'Save path (optional)','dialog.delete.eyebrow':'DANGER','dialog.delete.title':'Delete Torrent','dialog.delete.confirm':'Confirm Delete','dialog.action.eyebrow':'ACTION','dialog.action.title':'Action','dialog.action.value':'Value',
    'fatal.title':'WebUI cannot continue','fatal.unknown':'An unknown error occurred.','status.refresh':'Refresh {time}',
    'language.en':'English','language.zh-CN':'简体中文','language.zh-TW':'繁體中文','language.ja':'日本語','language.ko':'한국어'
  };
  var ZH={
    'app.skip':'跳到种子列表','app.back':'返回','app.home':'首页','app.reload':'重载','app.refresh':'刷新','app.theme':'切换主题','app.menu':'打开导航','app.close':'关闭','app.cancel':'取消','app.confirm':'确认','app.done':'完成','app.reset':'恢复默认','app.more':'更多','app.loading':'正在加载…','app.connected':'WeiG qB WebUI 已连接','app.compatible':'已适配','app.compatMode':'兼容模式','app.detecting':'检测中…',
    'nav.torrents':'种子','nav.search':'搜索','nav.rss':'RSS','nav.logs':'日志','nav.settings':'设置','nav.more':'更多',
    'sidebar.torrents':'种子','sidebar.trackers':'Tracker','sidebar.savePath':'保存路径','sidebar.categories':'分类','sidebar.tags':'标签','sidebar.connection':'连接',
    'filter.all':'全部','filter.downloading':'下载中','filter.seeding':'做种','filter.completed':'已完成','filter.paused':'已暂停','filter.active':'活动','filter.stalled':'停滞','filter.error':'错误','filter.private':'私有 / PT',
    'tracker.all':'全部 Tracker','tracker.none':'无 Tracker','tracker.indexing':'正在建立 Tracker 索引…','path.all':'全部路径','category.all':'全部分类','tag.all':'全部标签',
    'library.eyebrow':'资源库','library.all':'全部种子','library.count':'共 {count} 个 Torrent','library.empty':'没有符合条件的种子','library.emptyDesc':'调整筛选条件，或添加新的 Torrent。','library.add':'添加种子','library.pageSize':'每页','library.columns':'列设置','library.prev':'上一页','library.next':'下一页','library.page':'第 {page} / {pages} 页 · 每页 {size}','library.range':'{start}–{end} / {total}','library.refreshing':'正在刷新种子…','library.refreshed':'已刷新','library.readFailed':'读取种子失败：{error}',
    'search.torrents':'搜索种子…','search.settings':'搜索设置…','search.logs':'搜索日志…','search.rss':'搜索 RSS…','search.engine':'搜索引擎…','search.title':'搜索引擎','search.description':'使用 qBittorrent Search API 搜索。','search.query':'搜索关键词','search.start':'搜索','search.stop':'停止','search.unsupported':'当前 WebAPI 不支持 Search API。','search.failed':'搜索失败：{error}',
    'rss.description':'Feed、文章与兼容的 RSS 操作。','rss.feedUrl':'RSS Feed URL','rss.add':'添加 Feed','rss.refresh':'刷新','rss.empty':'还没有 RSS Feed。','rss.unsupported':'当前 WebAPI 不支持 RSS。','rss.failed':'RSS 读取失败：{error}',
    'logs.title':'日志','logs.description':'qBittorrent 执行日志；大列表保持窗口化。','logs.unsupported':'当前 WebAPI 不提供日志接口。','logs.failed':'日志读取失败：{error}',
    'stats.download':'下载速度','stats.upload':'上传速度','stats.network':'网络','stats.torrent':'种子','stats.globalDownload':'全局实时下载','stats.globalUpload':'全局实时上传','stats.connection':'连接状态','stats.firewalled':'防火墙限制','stats.connected':'已连接','stats.disconnected':'已断开','stats.error':'异常','stats.dhtPeers':'DHT {dht} · Peers {peers}',
    'torrent.start':'开始','torrent.pause':'暂停','torrent.stop':'停止','torrent.delete':'删除','torrent.deleteData':'同时删除下载的数据文件','torrent.deleteSelected':'确定删除选中的 {count} 个种子吗？','torrent.actions':'更多操作','torrent.forceStart':'强制开始','torrent.recheck':'重新校验','torrent.reannounce':'重新汇报','torrent.sequential':'顺序下载','torrent.firstLast':'首尾块优先','torrent.autoTmm':'自动 Torrent 管理','torrent.top':'队列置顶','torrent.bottom':'队列置底','torrent.rename':'重命名','torrent.location':'移动位置','torrent.category':'设置分类','torrent.addTags':'添加 Tags','torrent.downloadLimit':'下载限速 (KiB/s)','torrent.uploadLimit':'上传限速 (KiB/s)','torrent.details':'查看详情','torrent.commandSent':'命令已发送','torrent.actionFailed':'操作失败：{error}','torrent.added':'种子已添加','torrent.addFailed':'添加失败：{error}','torrent.name':'名称','torrent.size':'大小','torrent.progress':'进度','torrent.download':'下载','torrent.upload':'上传','torrent.status':'状态','torrent.categoryColumn':'分类',
    'state.downloading':'下载中','state.metaDL':'下载元数据','state.forcedDL':'强制下载','state.allocating':'分配空间','state.checkingDL':'检查中','state.checkingUP':'检查中','state.checkingResumeData':'检查恢复数据','state.moving':'移动中','state.uploading':'做种','state.stalledUP':'做种停滞','state.forcedUP':'强制作种','state.queuedUP':'做种排队','state.pausedDL':'已暂停','state.pausedUP':'已暂停','state.stoppedDL':'已停止','state.stoppedUP':'已停止','state.queuedDL':'下载排队','state.stalledDL':'下载停滞','state.error':'错误','state.missingFiles':'文件缺失','state.unknown':'未知',
    'detail.eyebrow':'种子详情','detail.overview':'概览','detail.files':'文件','detail.trackers':'Trackers','detail.peers':'Peers','detail.webseeds':'HTTP 来源','detail.loading':'正在加载…','detail.title':'种子详情','detail.savePath':'保存路径','detail.totalSize':'总大小','detail.downloaded':'已下载','detail.uploaded':'已上传','detail.shareRatio':'分享率','detail.connections':'连接数','detail.seeds':'Seeds','detail.peersCount':'Peers','detail.addedOn':'添加时间','detail.completedOn':'完成时间','detail.createdBy':'创建者','detail.pieces':'分块','detail.noWebseeds':'当前种子没有 Web Seed / HTTP Source。','file.skip':'跳过','file.normal':'正常','file.high':'高','file.maximum':'最高','file.updated':'文件优先级已更新','tracker.add':'添加 Tracker','tracker.remove':'删除','tracker.edit':'编辑','tracker.status':'状态 {status} · Seeds {seeds}','peer.ban':'封禁 Peer','peer.banned':'Peer 已封禁',
    'settings.eyebrow':'设置','settings.title':'设置','settings.description':'界面设置与当前 qBittorrent 实际支持的 Preferences。','settings.save':'保存','settings.search':'搜索设置…','settings.weigg':'WeiG WebUI','settings.downloads':'下载','settings.connection':'连接','settings.speed':'速度','settings.bittorrent':'BitTorrent','settings.webui':'Web UI','settings.advanced':'高级','settings.currentOnly':'只显示当前 qBittorrent 实际返回的 Preferences。','settings.none':'当前版本没有返回这一组设置。','settings.readFailed':'读取设置失败：{error}','settings.saved':'qBittorrent 设置已保存','settings.noChanges':'没有需要保存的 qB 设置','settings.saveFailed':'保存失败：{error}','settings.interface':'界面','settings.interfaceDesc':'字体、密度、语言、分页和视觉行为统一使用设计 Token。','settings.performance':'性能','settings.performanceDesc':'开发和渲染诊断信息放在这里，不占主界面。','settings.language':'语言','settings.languageDesc':'自动跟随浏览器；不支持的语言自动回退英文。','settings.autoLanguage':'自动（浏览器）','settings.theme':'外观','settings.fontSize':'字体大小','settings.density':'界面密度','settings.starfield':'星空','settings.motion':'动画','settings.pageSize':'每页 Torrent','settings.refresh':'刷新频率','settings.ptRules':'4.x PT Tracker 规则','settings.ptRulesDesc':'qBittorrent 4.x 没有精确 Private 字段；这里按 Tracker 域名识别，使用逗号分隔。','settings.global':'统一全局设置','settings.theme.system':'跟随系统','settings.theme.dark':'深色','settings.theme.light':'浅色','settings.size.standard':'标准','settings.size.large':'大（+2px）','settings.size.xlarge':'特大（+3px）','settings.density.compact':'紧凑','settings.density.standard':'标准','settings.density.comfortable':'宽松','settings.off':'关闭','settings.subtle':'柔和','settings.full':'完整','settings.reduced':'减少','settings.seconds':'{n} 秒','settings.cache':'全库缓存','settings.pageData':'当前页数据','settings.dom':'当前 DOM','settings.apiPage':'API 每页','settings.refreshInterval':'刷新间隔','settings.trackerIndex':'Tracker 索引','settings.complete':'完成','settings.building':'构建中',
    'columns.title':'列设置','columns.reset':'恢复默认','columns.done':'完成','dialog.add.title':'添加种子','dialog.add.urls':'Magnet / URL','dialog.add.or':'或','dialog.add.files':'选择 .torrent 文件','dialog.add.multi':'可多选','dialog.add.savePath':'保存路径（可选）','dialog.delete.title':'删除种子','dialog.delete.confirm':'确认删除','dialog.action.title':'操作','dialog.action.value':'值','fatal.title':'WebUI 无法继续加载','fatal.unknown':'发生未知错误。','status.refresh':'刷新 {time}'
  };
  var ZHT={'nav.torrents':'Torrent','nav.search':'搜尋','nav.logs':'日誌','nav.settings':'設定','filter.all':'全部','filter.downloading':'下載中','filter.seeding':'做種','filter.completed':'已完成','filter.paused':'已暫停','filter.active':'活動','filter.stalled':'停滯','filter.error':'錯誤','filter.private':'私有 / PT','library.all':'全部 Torrent','library.count':'共 {count} 個 Torrent','library.add':'新增 Torrent','library.pageSize':'每頁','library.columns':'欄位','settings.title':'設定','settings.description':'介面設定與目前 qBittorrent 支援的 Preferences。','settings.save':'儲存','settings.language':'語言','settings.autoLanguage':'自動（瀏覽器）','settings.downloads':'下載','settings.connection':'連線','settings.speed':'速度','settings.advanced':'進階','search.torrents':'搜尋 Torrent…','search.settings':'搜尋設定…'};
  var JA={'nav.torrents':'Torrent','nav.search':'検索','nav.logs':'ログ','nav.settings':'設定','filter.all':'すべて','filter.downloading':'ダウンロード中','filter.seeding':'シード中','filter.completed':'完了','filter.paused':'一時停止','filter.active':'アクティブ','filter.error':'エラー','library.all':'すべてのTorrent','library.add':'Torrentを追加','settings.title':'設定','settings.save':'保存','settings.language':'言語','settings.autoLanguage':'自動（ブラウザー）','search.torrents':'Torrentを検索…','search.settings':'設定を検索…'};
  var KO={'nav.torrents':'토렌트','nav.search':'검색','nav.logs':'로그','nav.settings':'설정','filter.all':'전체','filter.downloading':'다운로드 중','filter.seeding':'시딩','filter.completed':'완료','filter.paused':'일시정지','filter.active':'활성','filter.error':'오류','library.all':'모든 토렌트','library.add':'토렌트 추가','settings.title':'설정','settings.save':'저장','settings.language':'언어','settings.autoLanguage':'자동 (브라우저)','search.torrents':'토렌트 검색…','search.settings':'설정 검색…'};
  var dicts={'en':EN,'zh-CN':Object.assign({},EN,ZH),'zh-TW':Object.assign({},EN,ZHT),'ja':Object.assign({},EN,JA),'ko':Object.assign({},EN,KO)};
  function normalize(tag){tag=String(tag||'').replace('_','-').toLowerCase();if(tag==='zh-tw'||tag==='zh-hk'||tag==='zh-mo'||tag.indexOf('zh-hant')===0)return 'zh-TW';if(tag==='zh-cn'||tag==='zh-sg'||tag.indexOf('zh-hans')===0||tag==='zh')return 'zh-CN';if(tag.indexOf('ja')===0)return 'ja';if(tag.indexOf('ko')===0)return 'ko';if(tag.indexOf('en')===0)return 'en';return '';}
  function browserLocale(){var list=(navigator.languages&&navigator.languages.length?navigator.languages:[navigator.language||'en']);for(var i=0;i<list.length;i++){var x=normalize(list[i]);if(x)return x;}return 'en';}
  var saved=localStorage.getItem('weigg-language')||'auto';var locale=saved==='auto'?browserLocale():(normalize(saved)||'en');
  function format(text,vars){return String(text).replace(/\{([^}]+)\}/g,function(_,k){return vars&&vars[k]!==undefined?vars[k]:'{'+k+'}';});}
  function t(key,vars){var d=dicts[locale]||EN;return format(d[key]!==undefined?d[key]:(EN[key]!==undefined?EN[key]:key),vars);}
  function setLocale(value){var v=value==='auto'?'auto':(normalize(value)||'en');localStorage.setItem('weigg-language',v);saved=v;locale=v==='auto'?browserLocale():v;document.documentElement.lang=locale;apply(document);global.dispatchEvent(new CustomEvent('weigg:languagechange',{detail:{locale:locale,setting:v}}));return locale;}
  function apply(root){root=root||document;document.documentElement.lang=locale;Array.prototype.forEach.call(root.querySelectorAll('[data-i18n]'),function(el){el.textContent=t(el.dataset.i18n);});Array.prototype.forEach.call(root.querySelectorAll('[data-i18n-placeholder]'),function(el){el.setAttribute('placeholder',t(el.dataset.i18nPlaceholder));});Array.prototype.forEach.call(root.querySelectorAll('[data-i18n-aria]'),function(el){el.setAttribute('aria-label',t(el.dataset.i18nAria));});Array.prototype.forEach.call(root.querySelectorAll('[data-i18n-title]'),function(el){el.setAttribute('title',t(el.dataset.i18nTitle));});}
  W.I18n={t:t,apply:apply,setLocale:setLocale,getLocale:function(){return locale;},getSetting:function(){return saved;},supported:['en','zh-CN','zh-TW','ja','ko'],browserLocale:browserLocale,english:EN};W.t=t;
})(window);
