(function(global){
  'use strict';
  var W=global.WeiG,U=W&&W.util;
  if(!W||!U||W.V037Layout)return;
  var initialized=false,Grid={widths:{}},originalTemplate=W.DataGrid&&W.DataGrid.template;
  function isMobile(){return !!(global.matchMedia&&global.matchMedia('(max-width: 820px)').matches);}
  function gridColumnsFromDom(){return Array.from(document.querySelectorAll('#torrent-table-head .grid-head-cell')).map(function(cell){var key=cell.dataset.key,def=(W.DataGrid.defaults||[]).find(function(x){return x.key===key;})||{},width=Grid.widths[key]||Math.round(cell.getBoundingClientRect().width)||def.width||100;return {key:key,width:width,min:def.min||60};});}
  function applyGridWidths(cols){if(!cols||!cols.length)return;cols.forEach(function(c){Grid.widths[c.key]=c.width;});var template=cols.map(function(c){return Math.max(c.min||60,Grid.widths[c.key]||c.width||100)+'px';}).join(' '),view=document.getElementById('list-view');if(view)view.style.setProperty('--weigg-grid-template',template);}
  function installHandle(handle,index,cols,onDone){handle.addEventListener('pointerdown',function(e){e.preventDefault();e.stopPropagation();var startX=e.clientX,startW=Grid.widths[cols[index].key]||cols[index].width||100,pending=null,raf=0;handle.setPointerCapture(e.pointerId);function flush(){raf=0;if(pending==null)return;cols[index].width=Math.max(cols[index].min||60,startW+pending);Grid.widths[cols[index].key]=cols[index].width;applyGridWidths(cols);pending=null;}function move(ev){pending=ev.clientX-startX;if(!raf)raf=requestAnimationFrame(flush);}function up(ev){if(raf){cancelAnimationFrame(raf);flush();}try{handle.releasePointerCapture(ev.pointerId);}catch(_e){}handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',up);handle.removeEventListener('pointercancel',up);if(onDone)onDone(cols);}handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',up);handle.addEventListener('pointercancel',up);});}
  function installGridResizeOnCurrent(){var head=document.getElementById('torrent-table-head');if(!head||isMobile())return;var cols=gridColumnsFromDom();if(!cols.length)return;applyGridWidths(cols);Array.from(head.querySelectorAll('.col-resize')).forEach(function(old,index){if(old.dataset.v037Resize==='1')return;var clone=old.cloneNode(true);clone.dataset.v037Resize='1';old.replaceWith(clone);installHandle(clone,index,cols,function(next){var cfg=W.Config.load(),saveCols=next.map(function(c){var def=(W.DataGrid.defaults||[]).find(function(x){return x.key===c.key;})||{};return Object.assign({},def,c);});W.DataGrid.save(cfg,saveCols);if(head)head.style.gridTemplateColumns=W.DataGrid.template(saveCols);var list=document.getElementById('torrent-list'),instance=list&&list.__weiggTorrentVirtual;if(instance)instance.render();});});}
  function overrideGrid(){if(!W.DataGrid||!originalTemplate)return;W.DataGrid.template=function(cols){var next=(cols||[]).map(function(c){var copy=Object.assign({},c);if(Grid.widths[c.key])copy.width=Grid.widths[c.key];return copy;});return originalTemplate.call(this,next);};W.DataGrid.addResizeHandles=function(head,cols,onChange){U.$$('.col-resize',head).forEach(function(x){x.remove();});applyGridWidths(cols);U.$$('.grid-head-cell',head).forEach(function(cell,index){var h=document.createElement('span');h.className='col-resize';h.dataset.v037Resize='1';h.setAttribute('aria-hidden','true');cell.appendChild(h);installHandle(h,index,cols,function(next){if(onChange)onChange(next,true);});});};}

  function normalizeDialog(dialog){if(!dialog||dialog.dataset.adaptiveDialog==='1')return;dialog.dataset.adaptiveDialog='1';var root=dialog.querySelector(':scope > form')||dialog,head=root.querySelector(':scope > .dialog__head'),actions=root.querySelector(':scope > .dialog__actions'),body=root.querySelector(':scope > .dialog__body');if(!body){body=document.createElement('div');body.className='dialog__body';var nodes=Array.from(root.childNodes).filter(function(n){return n!==head&&n!==actions;});nodes.forEach(function(n){body.appendChild(n);});if(head)head.insertAdjacentElement('afterend',body);else root.insertBefore(body,actions||root.firstChild);}}
  function normalizeDialogs(){Array.from(document.querySelectorAll('dialog.dialog')).forEach(normalizeDialog);}
  function syncBottomNav(){Array.from(document.querySelectorAll('#mobile-bottom-nav .mobile-bottom-nav__item')).forEach(function(item){item.classList.add('v037-nav-horizontal');});}
  function normalizeMobileDrawer(){var filters=document.getElementById('filter-nav'),settings=document.querySelector('.v037-mobile-settings-nav');if(filters&&settings&&settings.previousElementSibling!==filters)filters.insertAdjacentElement('afterend',settings);}
  function installDrawerReveal(){var menu=document.getElementById('menu-btn');if(!menu||menu.dataset.v037DrawerReveal==='1')return;menu.dataset.v037DrawerReveal='1';menu.addEventListener('click',function(){requestAnimationFrame(function(){normalizeMobileDrawer();var route=W.Router&&W.Router.route&&W.Router.route(),settings=document.querySelector('.v037-mobile-settings-nav');if(route&&route.name==='settings'&&settings)settings.scrollIntoView({block:'nearest'});});});}
  function init(){if(initialized)return;initialized=true;overrideGrid();installGridResizeOnCurrent();normalizeDialogs();syncBottomNav();normalizeMobileDrawer();installDrawerReveal();new MutationObserver(function(records){var needsDialog=false,needsGrid=false,needsDrawer=false;records.forEach(function(r){Array.from(r.addedNodes||[]).forEach(function(n){if(n.nodeType!==1)return;if((n.matches&&n.matches('dialog.dialog'))||(n.querySelector&&n.querySelector('dialog.dialog')))needsDialog=true;if(n.id==='torrent-table-head'||(n.querySelector&&n.querySelector('#torrent-table-head')))needsGrid=true;if((n.matches&&n.matches('.v037-mobile-settings-nav'))||(n.querySelector&&n.querySelector('.v037-mobile-settings-nav')))needsDrawer=true;});});if(needsDialog)normalizeDialogs();if(needsGrid)requestAnimationFrame(installGridResizeOnCurrent);if(needsDrawer)requestAnimationFrame(normalizeMobileDrawer);}).observe(document.body,{childList:true,subtree:true});global.addEventListener('resize',U.debounce(function(){installGridResizeOnCurrent();normalizeMobileDrawer();},80));}
  W.V037Layout={init:init,installGridResize:installGridResizeOnCurrent,normalizeDialogs:normalizeDialogs,normalizeMobileDrawer:normalizeMobileDrawer,widths:Grid.widths};
})(window);
