(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{};
  function int(value,fallback){var n=Number(value);return Number.isSafeInteger(n)&&n>=0?n:fallback;}
  function delay(ms){return new Promise(function(resolve){global.setTimeout(resolve,Math.max(0,Number(ms)||0));});}function idle(){return new Promise(function(resolve){if(typeof global.requestIdleCallback==='function')global.requestIdleCallback(function(){resolve();},{timeout:180});else global.setTimeout(resolve,36);});}
  function normalizedQuery(query){var out={};Object.keys(query||{}).sort().forEach(function(key){if(key==='limit'||key==='offset'||key==='hashes')return;var value=query[key];if(value===undefined||value===null||value==='')return;out[key]=String(value);});return out;}
  function signature(query,pageSize){var normalized=normalizedQuery(query),keys=Object.keys(normalized);return String(pageSize)+'|'+keys.map(function(key){return encodeURIComponent(key)+'='+encodeURIComponent(normalized[key]);}).join('&');}
  function totalSignature(query){var normalized=normalizedQuery(query);delete normalized.sort;delete normalized.reverse;var keys=Object.keys(normalized);return'q|'+keys.map(function(key){return encodeURIComponent(key)+'='+encodeURIComponent(normalized[key]);}).join('&');}
  function totalProbeQuery(query){var out=normalizedQuery(query);delete out.sort;delete out.reverse;out.sort='added_on';out.reverse='true';return out;}
  function prefetchRadius(pageSize,rowBudget){pageSize=int(pageSize,0);rowBudget=int(rowBudget,600);if(pageSize<=0||pageSize>=500)return 0;return Math.max(0,Math.min(3,Math.floor(rowBudget/(pageSize*2))));}
  function pageCount(total,pageSize){total=Math.max(0,int(total,0));pageSize=Math.max(1,int(pageSize,1));return Math.max(1,Math.ceil(total/pageSize));}
  function create(client,options){
    options=options||{};if(!client||typeof client.getTorrents!=='function')throw new Error('LibraryDataRuntime requires QBClient.getTorrents');
    var cache=new Map(),pageInflight=new Map(),pageGeneration=0,totalCache=new Map(),totalInflight=new Map(),totalGeneration=0,totalDemand=0,totalTraffic=0,tick=0,prefetchGeneration=0,prefetchDemand=0,pageTraffic=0,lastPageTrafficAt=0,catalogTask=null,catalogPriority='background',cacheRows=0,mainDataRid=0,mainData={torrents:{},trackers:{}};
    var maxCacheRows=Math.max(200,int(options.pageCacheRows,900)),ttl=Math.max(1000,int(options.pageTtlMs,10000)),totalTtl=Math.max(1000,int(options.totalTtlMs,300000)),rowBudget=Math.max(100,int(options.prefetchRowBudget,600)),catalogBatch=Math.max(50,int(options.catalogBatchSize,200)),totalProbeBudget=Math.max(8,int(options.totalProbeBudget,48)),backgroundQuietMs=Math.max(0,int(options.backgroundQuietMs,120)),interactionActive=typeof options.interactionActive==='function'?options.interactionActive:function(){return false;};
    function userInteracting(){try{return !!interactionActive();}catch(_e){return false;}}
    function cacheKey(query,page,pageSize){return signature(query,pageSize)+'|p='+String(page);}
    function cacheAllowed(pageSize){return int(pageSize,0)>0&&int(pageSize,0)<500;}
    function drop(key){var entry=cache.get(key);if(!entry)return;cacheRows-=entry.items.length;cache.delete(key);}
    function trim(){if(cacheRows<=maxCacheRows)return;Array.from(cache.entries()).sort(function(a,b){return a[1].used-b[1].used;}).forEach(function(pair){if(cacheRows>maxCacheRows)drop(pair[0]);});}
    function rememberPage(query,page,pageSize,value){if(!cacheAllowed(pageSize)||!value)return value;var key=cacheKey(query,page,pageSize),prior=cache.get(key);if(prior)cacheRows-=prior.items.length;var entry={items:Array.isArray(value.items)?value.items.slice():[],hasNext:!!value.hasNext,time:Date.now(),used:++tick};cache.set(key,entry);cacheRows+=entry.items.length;trim();return entry;}
    function cachedPage(query,page,pageSize){if(!cacheAllowed(pageSize))return null;var key=cacheKey(query,page,pageSize),entry=cache.get(key);if(!entry)return null;if(Date.now()-entry.time>ttl){drop(key);return null;}entry.used=++tick;return{items:entry.items.slice(),hasNext:entry.hasNext,cached:true};}
    async function fetchPage(query,page,pageSize,opts){page=Math.max(0,int(page,0));pageSize=Math.max(1,int(pageSize,50));opts=opts||{};var key=cacheKey(query,page,pageSize),existing=pageInflight.get(key);if(existing)return existing;var generation=pageGeneration,next=Object.assign({},normalizedQuery(query),{limit:pageSize+1,offset:page*pageSize}),task=(async function(){pageTraffic++;lastPageTrafficAt=Date.now();try{var raw=await client.getTorrents(next);raw=Array.isArray(raw)?raw:[];var value={items:raw.slice(0,pageSize),hasNext:raw.length>pageSize,cached:false};if(opts.remember!==false&&generation===pageGeneration)rememberPage(query,page,pageSize,value);return value;}finally{pageTraffic=Math.max(0,pageTraffic-1);lastPageTrafficAt=Date.now();}})();pageInflight.set(key,task);try{return await task;}finally{if(pageInflight.get(key)===task)pageInflight.delete(key);}}
    function totalKey(query){return totalSignature(query);}
    function totalSnapshot(query){var entry=totalCache.get(totalKey(query));if(!entry)return null;var age=Math.max(0,Date.now()-Number(entry.time||0));return{value:entry.value,time:entry.time,ageMs:age,fresh:age<=totalTtl};}function cachedTotal(query){var snapshot=totalSnapshot(query);return snapshot&&snapshot.fresh?snapshot.value:null;}function peekTotal(query){var snapshot=totalSnapshot(query);return snapshot?snapshot.value:null;}
    function rememberTotal(query,value,generation){value=Number(value);if(generation!==totalGeneration||!Number.isSafeInteger(value)||value<0)return null;totalCache.set(totalKey(query),{value:value,time:Date.now()});return value;}function seedTotal(query,value){return rememberTotal(query,value,totalGeneration);}
    async function waitTotalTurn(generation){while(generation===totalGeneration&&(userInteracting()||pageTraffic>0))await delay(16);return generation===totalGeneration;}
    async function totalProbe(query,offset,generation,counter){if(counter&&++counter.count>totalProbeBudget)return{budgetExceeded:true,exists:false,hash:''};if(!await waitTotalTurn(generation))return null;totalTraffic++;try{var next=Object.assign({},totalProbeQuery(query),{limit:1,offset:Math.max(0,int(offset,0))}),raw=await client.getTorrents(next);if(generation!==totalGeneration)return null;raw=Array.isArray(raw)?raw:[];var item=raw[0]||null;return{budgetExceeded:false,exists:!!item,hash:item&&item.hash!=null?String(item.hash):''};}finally{totalTraffic=Math.max(0,totalTraffic-1);}}
    function fetchTotal(query,page,pageSize,visibleCount,hasNext){page=Math.max(0,int(page,0));pageSize=Math.max(1,int(pageSize,50));visibleCount=Math.max(0,int(visibleCount,0));var cached=cachedTotal(query);if(cached!==null)return Promise.resolve(cached);var key=totalKey(query),existing=totalInflight.get(key);if(existing)return existing;var generation=totalGeneration;totalDemand++;var task=(async function(){try{var base=page*pageSize;if(!hasNext&&(visibleCount>0||page===0))return rememberTotal(query,base+visibleCount,generation);var counter={count:0},first=await totalProbe(query,0,generation,counter);if(first===null||first.budgetExceeded)return null;if(!first.exists)return rememberTotal(query,0,generation);var firstHash=first.hash,probeExists=async function(offset){var probe=await totalProbe(query,offset,generation,counter);if(probe===null||probe.budgetExceeded)return null;if(!probe.exists)return false;if(offset>0&&firstHash&&probe.hash===firstHash)return false;return true;},low=-1,high=-1;if(visibleCount>0)low=base+visibleCount-1;if(hasNext)low=Math.max(low,(page+1)*pageSize);if(low<0){low=0;high=Math.max(1,base);}if(high<0)high=Math.max(low+1,(page+2)*pageSize-1);if(high<=low)high=low+1;var exists;while(true){exists=await probeExists(high);if(exists===null)return null;if(!exists)break;low=high;high=Math.max(low+1,(low+1)*2-1);}while(low+1<high){var mid=Math.floor((low+high)/2);exists=await probeExists(mid);if(exists===null)return null;if(exists)low=mid;else high=mid;}return rememberTotal(query,low+1,generation);}finally{totalDemand=Math.max(0,totalDemand-1);}})();totalInflight.set(key,task);task.finally(function(){if(totalInflight.get(key)===task)totalInflight.delete(key);}).catch(function(){});return task;}
    function cancelPrefetch(){prefetchGeneration++;return prefetchGeneration;}
    function clearPages(){pageGeneration++;cancelPrefetch();pageInflight.clear();cache.clear();cacheRows=0;}
    function markTotalsStale(){totalGeneration++;totalInflight.clear();totalCache.forEach(function(entry){entry.time=0;});return totalCache.size;}function clearTotals(){totalGeneration++;totalInflight.clear();totalCache.clear();}
    function schedulePrefetch(query,currentPage,pageSize,currentHasNext){var radius=prefetchRadius(pageSize,rowBudget),generation=cancelPrefetch();if(!radius||global.document&&global.document.hidden||userInteracting()||totalDemand>0)return Promise.resolve(false);prefetchDemand++;var task=(async function(){var forward=!!currentHasNext;for(var distance=1;distance<=radius;distance++){if(generation!==prefetchGeneration||userInteracting()||totalDemand>0)return false;var back=currentPage-distance;if(back>=0&&!cachedPage(query,back,pageSize)){await idle();if(generation!==prefetchGeneration||userInteracting()||totalDemand>0)return false;await fetchPage(query,back,pageSize,{remember:true});}if(generation!==prefetchGeneration||userInteracting()||totalDemand>0)return false;if(forward){var nextPage=currentPage+distance,cached=cachedPage(query,nextPage,pageSize);if(!cached){await idle();if(generation!==prefetchGeneration||userInteracting()||totalDemand>0)return false;cached=await fetchPage(query,nextPage,pageSize,{remember:true});}forward=!!cached.hasNext;}}return true;})();task.finally(function(){prefetchDemand=Math.max(0,prefetchDemand-1);}).catch(function(){});return task;}
    function promoteCatalog(){catalogPriority='foreground';}
    async function waitCatalogTurn(){while(userInteracting())await delay(24);while(catalogPriority==='background'){var quietFor=Date.now()-lastPageTrafficAt;if(userInteracting()){await delay(24);continue;}if(pageTraffic>0||totalDemand>0||totalTraffic>0||prefetchDemand>0||quietFor<backgroundQuietMs){await delay(Math.max(8,Math.min(48,backgroundQuietMs-quietFor>0?backgroundQuietMs-quietFor:16)));continue;}await idle();if(userInteracting())continue;if(pageTraffic===0&&totalDemand===0&&totalTraffic===0&&prefetchDemand===0&&(Date.now()-lastPageTrafficAt)>=backgroundQuietMs)return true;}return true;}
    function scanCatalog(opts){opts=opts||{};if(catalogTask){if(opts.priority==='foreground')promoteCatalog();return catalogTask;}catalogPriority=opts.priority==='background'?'background':'foreground';var batch=Math.max(50,int(opts.batchSize,catalogBatch));catalogTask=(async function(){var all=[],offset=0;while(true){await waitCatalogTurn();var part=await client.getTorrents({sort:'added_on',reverse:'true',limit:batch,offset:offset});part=Array.isArray(part)?part:[];all=all.concat(part);if(typeof opts.onBatch==='function')opts.onBatch(part.slice(),all.length);if(part.length<batch)break;offset+=batch;if(catalogPriority!=='background')await Promise.resolve();}return all;})();catalogTask.finally(function(){catalogTask=null;catalogPriority='background';}).catch(function(){});return catalogTask;}
    async function syncMainData(){if(typeof client.getMainData!=='function')throw new Error('LibraryDataRuntime requires QBClient.getMainData for sync');var response=await client.getMainData(mainDataRid);if(!response||typeof response!=='object'||Array.isArray(response))throw new Error('sync/maindata returned an invalid response');var full=response.full_update===true||mainDataRid===0,removed=Array.isArray(response.torrents_removed)?response.torrents_removed.map(String):[],removedTrackers=Array.isArray(response.trackers_removed)?response.trackers_removed.map(String):[];if(full)mainData={torrents:{},trackers:{}};var torrentPatch=response.torrents&&typeof response.torrents==='object'&&!Array.isArray(response.torrents)?response.torrents:{};Object.keys(torrentPatch).forEach(function(hash){var prior=mainData.torrents[hash]&&typeof mainData.torrents[hash]==='object'?mainData.torrents[hash]:{};mainData.torrents[hash]=Object.assign({},prior,torrentPatch[hash],{hash:String(hash)});});removed.forEach(function(hash){delete mainData.torrents[hash];});var trackerPatch=response.trackers&&typeof response.trackers==='object'&&!Array.isArray(response.trackers)?response.trackers:{};Object.keys(trackerPatch).forEach(function(key){mainData.trackers[key]=Array.isArray(trackerPatch[key])?trackerPatch[key].map(String):[];});removedTrackers.forEach(function(key){delete mainData.trackers[key];});var rid=Number(response.rid);if(Number.isSafeInteger(rid)&&rid>0)mainDataRid=rid;return{rid:mainDataRid,fullUpdate:full,torrents:mainData.torrents,trackers:mainData.trackers,removedTorrents:removed,removedTrackers:removedTrackers};}
    function stats(){return{cacheEntries:cache.size,cacheRows:cacheRows,inflightPages:pageInflight.size,pageTraffic:pageTraffic,totalCacheEntries:totalCache.size,totalTtlMs:totalTtl,totalInflight:totalInflight.size,totalTraffic:totalTraffic,totalDemand:totalDemand,prefetchDemand:prefetchDemand,prefetchRadius:function(pageSize){return prefetchRadius(pageSize,rowBudget);},catalogBusy:!!catalogTask,catalogPriority:catalogPriority,interactionActive:userInteracting(),mainDataRid:mainDataRid};}
    return{signature:signature,totalSignature:totalSignature,cachedPage:cachedPage,fetchPage:fetchPage,rememberPage:rememberPage,cachedTotal:cachedTotal,peekTotal:peekTotal,totalSnapshot:totalSnapshot,rememberTotal:seedTotal,fetchTotal:fetchTotal,schedulePrefetch:schedulePrefetch,cancelPrefetch:cancelPrefetch,clearPages:clearPages,markTotalsStale:markTotalsStale,clearTotals:clearTotals,scanCatalog:scanCatalog,promoteCatalog:promoteCatalog,syncMainData:syncMainData,stats:stats};
  }
  W.LibraryDataRuntime={create:create,prefetchRadius:function(pageSize,rowBudget){return prefetchRadius(pageSize,rowBudget==null?600:rowBudget);},pageCount:pageCount,signature:signature,totalSignature:totalSignature};
})(window);
