(function(global){
  'use strict';
  var W=global.WeiG,U=W&&W.util,C=W&&W.Components;
  if(!W||!U||!W.QBClient||!W.DataViewport||!C||!W.PageSizePolicy)return;

  var pageSizePolicy=W.PageSizePolicy,state={items:[],lastId:-1,types:new Set([1,2,4,8]),query:'',follow:true,page:0,pageSize:W.PageSizePolicy.defaultValue,pager:null,pageSizeControl:null,viewport:null,timer:null,loading:false,active:false,root:null,sizeMode:localStorage.getItem((W.StorageKeys&&W.StorageKeys.logsSizeMode)||'weig.logs.sizeMode')||'auto',programmaticScroll:false,expandedId:null};
  var MAX_ITEMS=5000;
  function tr(key,vars,fallback){var I=W.I18n,value=I&&I.t?I.t(key,vars):key;return value===key?(fallback||key):value;}
  function onLogsRoute(){return W.Router&&W.Router.route&&W.Router.route().name==='logs';}
  function typeLabel(type){return type===1?tr('logs.ui.normal',null,'Normal'):type===2?tr('logs.ui.info',null,'Info'):type===4?tr('logs.ui.warning',null,'Warning'):type===8?tr('logs.ui.critical',null,'Critical'):tr('logs.ui.unknown',null,'Unknown');}
  function typeTone(type){return type===8?'danger':type===4?'warning':type===2?'info':'normal';}
  function itemId(x){return Number(x&&x.id);}
  function rowKey(x){return String(itemId(x));}
  function baseRowHeight(){return U.isMobile&&U.isMobile()?72:54;}
  function timestampMs(x){var v=Number(x&&x.timestamp);if(!Number.isFinite(v)||v<=0)return 0;return v>=1e12?v:v*1000;}
  function formatTime(x){var ms=timestampMs(x);if(!ms)return '';return W.Time&&W.Time.format?W.Time.format(ms):new Date(ms).toLocaleString();}
  function filtered(){var q=state.query.trim().toLocaleLowerCase();return state.items.filter(function(x){return state.types.has(Number(x.type))&&(!q||String(x.message||'').toLocaleLowerCase().indexOf(q)>=0);});}function pageCount(total){return Math.max(1,Math.ceil(Math.max(0,Number(total)||0)/state.pageSize));}function setPage(next){var total=filtered().length,pages=pageCount(total),target=Math.max(0,Math.min(pages-1,Number(next)||0));if(target===state.page){renderRows(true,0);return;}state.page=target;state.expandedId=null;if(state.page>0&&state.follow){state.follow=false;syncFollowControl();}renderRows(true,0);}function pageLabel(pages){if(U.isMobile&&U.isMobile())return String(state.page+1)+' / '+pages;return tr('library.page',{page:state.page+1,pages:pages,size:state.pageSize},'Page '+(state.page+1)+' / '+pages+' · '+state.pageSize+' per page');}
  function stopPoll(){clearTimeout(state.timer);state.timer=null;}
  function schedulePoll(){stopPoll();if(!state.active||!onLogsRoute())return;var cfg=W.Config&&W.Config.load?W.Config.load():{};var delay=document.hidden?10000:Math.max(1500,Number(cfg.refresh)||2500);state.timer=setTimeout(fetchIncremental,delay);}

  function makeButton(label,cls){var b=document.createElement('button');b.type='button';b.className=cls||'btn btn--ghost';b.textContent=label;return b;}
  function applySizeMode(){var view=U.$('logs-view');if(!view)return;['auto','compact','max'].forEach(function(m){view.classList.toggle('logs-size-'+m,state.sizeMode===m);});localStorage.setItem((W.StorageKeys&&W.StorageKeys.logsSizeMode)||'weig.logs.sizeMode',state.sizeMode);var sel=U.$('logs-size-mode');if(sel&&sel.setValue)sel.setValue(state.sizeMode);}
  function syncFollowControl(){var wrap=state.root&&state.root.querySelector('[data-logs-follow]');if(wrap&&wrap.input)wrap.input.checked=state.follow;}
  function toggleExpanded(row){if(!row)return;var id=Number(row.dataset.logId);if(!Number.isFinite(id))return;state.expandedId=state.expandedId===id?null:id;if(state.viewport&&state.viewport.resetHeights)state.viewport.resetHeights();else if(state.viewport&&state.viewport.render)state.viewport.render();requestAnimationFrame(function(){var next=state.root&&state.root.querySelector('.logs-row[data-log-id="'+id+'"]');if(next)next.focus({preventScroll:true});});}

  function buildShell(root){
    root.textContent='';root.dataset.weigLogsReady='1';
    var shell=document.createElement('div');shell.className='logs-shell';shell.dataset.weigLogShell='1';
    var toolbar=document.createElement('div');toolbar.className='logs-toolbar grid-toolbar';
    var filters=document.createElement('div');filters.className='logs-filters';
    [1,2,4,8].forEach(function(type){var b=C.filterChip(typeLabel(type),state.types.has(type));b.dataset.logType=String(type);b.dataset.tone=typeTone(type);filters.appendChild(b);});
    var follow=C.checkControl(tr('logs.ui.follow',null,'Follow latest'),state.follow,function(checked){state.follow=checked;if(state.follow)scrollLatest();});follow.dataset.logsFollow='1';follow.dataset.shortLabel=tr('logs.latestShort',null,'Latest');follow.classList.add('logs-follow');filters.appendChild(follow);
    var actions=document.createElement('div');actions.className='logs-actions';
    var size=C.selectControl({id:'logs-size-mode',value:state.sizeMode,options:[{value:'compact',label:tr('logs.ui.compact',null,'Compact')},{value:'auto',label:tr('logs.ui.auto',null,'Auto')},{value:'max',label:tr('logs.ui.max',null,'Max')}],ariaLabel:tr('logs.ui.auto',null,'Auto'),onChange:function(value){state.sizeMode=value;applySizeMode();setTimeout(function(){if(state.viewport&&state.viewport.resetHeights)state.viewport.resetHeights();else if(state.viewport&&state.viewport.render)state.viewport.render();},40);}});size.classList.add('logs-size-mode');
    var refresh=makeButton('↻ '+tr('logs.ui.refresh',null,'Refresh'),'btn btn--ghost logs-refresh');
    actions.append(size,refresh);toolbar.append(filters,actions);
    state.pager=C.pagerControl({prevLabel:tr('library.prev',null,'Previous'),nextLabel:tr('library.next',null,'Next'),meta:true,onPrev:function(){setPage(state.page-1);},onNext:function(){setPage(state.page+1);}});state.pager.root.classList.add('logs-pager');var pageSizeWrap=document.createElement('label');pageSizeWrap.className='logs-page-size';var pageSizeCopy=document.createElement('span');pageSizeCopy.textContent=tr('library.pageSize',null,'Per page');state.pageSizeControl=C.selectControl({id:'logs-page-size',value:String(state.pageSize),options:pageSizePolicy.options(),ariaLabel:tr('library.pageSize',null,'Per page'),searchPlaceholder:pageSizePolicy.min+'–'+pageSizePolicy.max,numericInput:{min:pageSizePolicy.min,max:pageSizePolicy.max},formatValue:function(value){return String(value);},onChange:function(value){var next=pageSizePolicy.parse(value);if(next==null)return;state.pageSize=next;state.page=0;state.expandedId=null;renderRows(true,0);}});pageSizeWrap.append(pageSizeCopy,state.pageSizeControl);state.pager.root.insertBefore(pageSizeWrap,state.pager.nav);

    var panel=document.createElement('section');panel.className='logs-panel surface surface--panel surface--scroll';
    var head=document.createElement('div');head.className='logs-head';head.innerHTML='<span>'+tr('logs.ui.log',null,'Log')+'</span><span>'+tr('logs.ui.time',null,'Time')+'</span><span>'+tr('logs.ui.level',null,'Level')+'</span>';
    var list=document.createElement('div');list.className='logs-list';list.setAttribute('role','list');
    var empty=document.createElement('div');empty.className='logs-empty is-hidden';empty.textContent=tr('logs.ui.empty',null,'No logs match the current filters.');
    panel.append(head,list,empty,state.pager.root);shell.append(toolbar,panel);root.appendChild(shell);state.root=root;

    filters.addEventListener('click',function(e){var b=e.target.closest('[data-log-type]');if(!b)return;var type=Number(b.dataset.logType);if(state.types.has(type))state.types.delete(type);else state.types.add(type);state.page=0;b.classList.toggle('is-active',state.types.has(type));b.setAttribute('aria-pressed',state.types.has(type)?'true':'false');renderRows(true,0);});
    list.addEventListener('click',function(e){var row=e.target.closest('.logs-row[data-log-id]');if(row)toggleExpanded(row);});
    list.addEventListener('keydown',function(e){if(e.key!=='Enter'&&e.key!==' ')return;var row=e.target.closest('.logs-row[data-log-id]');if(!row)return;e.preventDefault();toggleExpanded(row);});
    list.addEventListener('scroll',function(){if(state.programmaticScroll||!state.follow)return;if(list.scrollTop>40){state.follow=false;syncFollowControl();}},{passive:true});
    refresh.addEventListener('click',function(){fetchInitial(true);});applySizeMode();
  }

  function renderRows(reset,added){var root=U.$('logs-content');if(!root)return;if(!root.querySelector('[data-weig-log-shell]'))buildShell(root);var list=root.querySelector('.logs-list'),empty=root.querySelector('.logs-empty');if(!list)return;var all=filtered(),pages=pageCount(all.length);state.page=Math.max(0,Math.min(state.page,pages-1));var start=state.page*state.pageSize,items=all.slice(start,start+state.pageSize),previousTop=list.scrollTop;if(!state.viewport||state.viewport.el!==list){state.viewport=new W.DataViewport(list,{rowHeight:baseRowHeight(),overscan:8,variableHeight:true,itemKey:rowKey,renderRow:function(x){var id=itemId(x),tone=typeTone(Number(x.type)),expanded=state.expandedId===id,row=document.createElement('div');row.className='logs-row'+(expanded?' is-expanded':'');row.dataset.tone=tone;row.setAttribute('role','listitem');row.dataset.logId=String(id);row.tabIndex=0;row.setAttribute('aria-expanded',expanded?'true':'false');var msg=document.createElement('span');msg.className='logs-message';msg.textContent=x.message||'';var ts=document.createElement('time');ts.className='logs-time';ts.dateTime=timestampMs(x)?new Date(timestampMs(x)).toISOString():'';ts.textContent=formatTime(x);var level=document.createElement('span');level.className='logs-level status-pill';level.dataset.tone=tone;level.textContent=typeLabel(Number(x.type));row.append(msg,ts,level);return row;}});}state.viewport.setItems(items);if(reset&&state.viewport.resetScroll)state.viewport.resetScroll();else if(!state.follow&&added>0&&previousTop>0){var keep=previousTop+added*baseRowHeight();list.__weigDataViewportScrollTop=keep;list.scrollTop=keep;state.viewport.render();}empty.classList.toggle('is-hidden',all.length!==0);if(state.pager)state.pager.update({prevDisabled:state.page===0,nextDisabled:state.page>=pages-1,label:pageLabel(pages),meta:tr('logs.ui.showing',{shown:items.length,total:all.length},'Showing '+items.length+' / '+all.length+' filtered · '+state.items.length+' retained')});if(state.follow&&state.page===0)scrollLatest();}

  function scrollLatest(){if(state.page!==0){state.page=0;renderRows(true,0);return;}var list=state.root&&state.root.querySelector('.logs-list');if(!list)return;state.programmaticScroll=true;requestAnimationFrame(function(){list.__weigDataViewportScrollTop=0;list.scrollTop=0;if(state.viewport&&state.viewport.render)state.viewport.render();requestAnimationFrame(function(){state.programmaticScroll=false;});});}
  function merge(items,replace){items=Array.isArray(items)?items:[];if(replace)state.items=[];var known=new Set(state.items.map(function(x){return itemId(x);})),added=0;items.forEach(function(x){var id=itemId(x);if(Number.isFinite(id)&&known.has(id))return;state.items.push(x);added++;if(Number.isFinite(id))known.add(id);});state.items.sort(function(a,b){var ai=itemId(a),bi=itemId(b);if(Number.isFinite(ai)&&Number.isFinite(bi))return bi-ai;return timestampMs(b)-timestampMs(a);});if(state.items.length>MAX_ITEMS)state.items=state.items.slice(0,MAX_ITEMS);var ids=state.items.map(itemId).filter(Number.isFinite);state.lastId=ids.length?Math.max.apply(Math,ids):-1;return added;}

  async function ensureClient(){var app=W.AppState;if(app&&app.client)return app.client;throw new Error('qBittorrent client is not ready.');}
  async function fetchInitial(){if(state.loading)return;if(W.CapabilityRegistry&&!W.CapabilityRegistry.supports('logs')){W.CapabilityRegistry.open('logs');return;}state.loading=true;try{var client=await ensureClient(),items=await client.logs(-1);merge(items,true);renderRows(false,0);if(state.follow)scrollLatest();}catch(e){showError(e);}finally{state.loading=false;schedulePoll();}}
  async function fetchIncremental(){if(state.loading||!state.active||!onLogsRoute()){schedulePoll();return;}state.loading=true;try{var client=await ensureClient(),items=await client.logs(state.lastId);if(Array.isArray(items)&&items.length){var added=merge(items,false);renderRows(false,added);}}catch(_e){}finally{state.loading=false;schedulePoll();}}
  function showError(e){var root=U.$('logs-content');if(!root)return;root.innerHTML='<div class="logs-message-state">'+tr('logs.ui.failed',{error:String(e&&e.message||e)},'Failed to read logs: '+String(e&&e.message||e))+'</div>';}
  function setQuery(q){state.query=String(q||'');state.page=0;if(state.active&&onLogsRoute())renderRows(true,0);}

  function activate(){if(!onLogsRoute()){state.active=false;stopPoll();return;}state.active=true;var root=U.$('logs-content');if(!root)return;if(!root.querySelector('[data-weig-log-shell]')){state.viewport=null;buildShell(root);}fetchInitial();}
  function rebuildShell(){if(!onLogsRoute())return;var root=U.$('logs-content');if(!root)return;state.viewport=null;buildShell(root);renderRows(false,0);}
  function init(){global.addEventListener('weig:route-state',function(e){if(e.detail&&e.detail.name!=='logs'){state.active=false;stopPoll();}});document.addEventListener('visibilitychange',function(){if(state.active)schedulePoll();});global.addEventListener('resize',U.debounce(function(){if(state.active&&state.viewport&&state.viewport.setRowHeight)state.viewport.setRowHeight(baseRowHeight());},120));global.addEventListener('weig:languagechange',rebuildShell);global.addEventListener('weig:timezonechange',function(){if(state.active)renderRows(false,0);});global.addEventListener('weig:timeformatrefresh',function(){if(state.active)renderRows(false,0);});if(onLogsRoute())activate();}
  W.Logs={setQuery:setQuery,query:function(){return state.query;},refresh:fetchInitial,activate:activate};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})(window);
