(function(global){
  'use strict';
  var W=global.WeiG,U=W&&W.util;
  if(!W||!U||W.PolishRuntime)return;

  var initialized=false,tooltipNode=null,observer=null,statusGuard=false;
  function zh(){return !!(W.I18n&&W.I18n.getLocale&&W.I18n.getLocale()==='zh-CN');}
  function label(en,cn){return zh()?cn:en;}

  function normalizeStatusMessage(){var node=document.getElementById('status-message');if(!node)return;var text=String(node.textContent||'').trim();if(/^(已刷新|refreshed|refresh complete)$/i.test(text))node.textContent='';}
  function connectionState(text){text=String(text||'').toLocaleLowerCase();if(/disconnect|offline|异常|断开|未连接|error/.test(text))return'disconnected';if(/firewall|limited|受限|防火墙/.test(text))return'limited';return'connected';}
  function syncConnectionIndicator(){var node=document.getElementById('status-connection');if(!node||statusGuard)return;var raw=String(node.textContent||'').trim(),copy=raw.replace(/^●\s*/,'').trim()||'—';statusGuard=true;node.classList.add('connection-indicator');node.dataset.connectionState=connectionState(copy);if(copy!==raw)node.textContent=copy;statusGuard=false;}
  function pulseConnection(){var node=document.getElementById('status-connection');if(!node)return;node.classList.remove('is-refresh-pulse');void node.offsetWidth;node.classList.add('is-refresh-pulse');setTimeout(function(){node.classList.remove('is-refresh-pulse');},620);}

  function tooltipText(target){if(!target)return'';var id=target.id;if(id==='refresh-btn')return label('Refresh data','刷新数据');if(id==='theme-btn')return label('Toggle theme','切换主题');if(/logout/i.test(id)||target.dataset.action==='logout')return label('Log out','注销');return target.dataset.tooltip||target.getAttribute('aria-label')||target.title||'';}
  function ensureTooltip(){if(tooltipNode)return tooltipNode;tooltipNode=document.createElement('div');tooltipNode.id='polish-tooltip';tooltipNode.className='tooltip polish-tooltip';tooltipNode.setAttribute('role','tooltip');document.body.appendChild(tooltipNode);return tooltipNode;}
  function positionTooltip(target){var tip=ensureTooltip(),r=target.getBoundingClientRect(),box=tip.getBoundingClientRect(),left=Math.min(innerWidth-box.width-8,Math.max(8,r.left+(r.width-box.width)/2)),top=r.bottom+8;if(top+box.height>innerHeight-8)top=Math.max(8,r.top-box.height-8);tip.style.left=Math.round(left)+'px';tip.style.top=Math.round(top)+'px';}
  function showTooltip(target){var text=tooltipText(target);if(!text)return;var tip=ensureTooltip();tip.textContent=text;tip.classList.add('is-visible');tip.dataset.for=target.id||'';requestAnimationFrame(function(){positionTooltip(target);});}
  function hideTooltip(){if(tooltipNode)tooltipNode.classList.remove('is-visible');}
  function installTooltips(){if(document.documentElement.dataset.polishTooltips==='1')return;document.documentElement.dataset.polishTooltips='1';['refresh-btn','theme-btn'].forEach(function(id){var node=document.getElementById(id);if(node){node.dataset.polishTooltip='1';if(node.title)node.removeAttribute('title');}});document.addEventListener('mouseover',function(e){var t=e.target&&e.target.closest&&e.target.closest('.icon-btn[data-polish-tooltip],#refresh-btn,#theme-btn,[data-action="logout"]');if(t)showTooltip(t);});document.addEventListener('mouseout',function(e){var t=e.target&&e.target.closest&&e.target.closest('.icon-btn[data-polish-tooltip],#refresh-btn,#theme-btn,[data-action="logout"]');if(t)hideTooltip();});document.addEventListener('focusin',function(e){var t=e.target&&e.target.closest&&e.target.closest('.icon-btn[data-polish-tooltip],#refresh-btn,#theme-btn,[data-action="logout"]');if(t)showTooltip(t);});document.addEventListener('focusout',function(e){var t=e.target&&e.target.closest&&e.target.closest('.icon-btn[data-polish-tooltip],#refresh-btn,#theme-btn,[data-action="logout"]');if(t)hideTooltip();});}

  function compactAbout(){var group=document.querySelector('#settings-content .about-surface');if(!group)return;var grid=group.querySelector(':scope > .about-facts-grid');if(!grid){grid=document.createElement('div');grid.className='about-facts-grid';var legal=group.querySelector(':scope > .about-legal');group.insertBefore(grid,legal||null);}Array.from(group.querySelectorAll(':scope > .about-row')).forEach(function(row){row.classList.add('about-fact');grid.appendChild(row);});}
  function actionTone(text){text=String(text||'').toLocaleLowerCase();if(/删除|delete/.test(text))return'danger';if(/限速|limit/.test(text))return'rate';if(/校验|汇报|recheck|reannounce/.test(text))return'verify';if(/队列|顺序|首尾|自动|queue|sequential|first|auto/.test(text))return'queue';if(/移动|分类|标签|tag|location|category/.test(text))return'organize';if(/开始|暂停|停止|强制|start|pause|stop|force/.test(text))return'run';return'neutral';}
  function decorateActionSheet(){var dialog=document.getElementById('actions-dialog');if(!dialog)return;dialog.classList.add('action-sheet-polish');var grid=dialog.querySelector('.action-grid');if(!grid)return;Array.from(grid.querySelectorAll('button.btn')).forEach(function(button){button.dataset.actionTone=actionTone(button.textContent);});}

  function observe(){if(observer)return;observer=new MutationObserver(function(records){var needsAbout=false,needsActions=false,needsStatus=false,needsConnection=false;records.forEach(function(record){var target=record.target;if(target&&target.id==='status-message')needsStatus=true;if(target&&target.id==='status-connection')needsConnection=true;Array.from(record.addedNodes||[]).forEach(function(node){if(!node||node.nodeType!==1)return;if((node.matches&&node.matches('.about-surface,.about-row'))||(node.querySelector&&node.querySelector('.about-surface,.about-row')))needsAbout=true;if(node.id==='actions-dialog'||(node.querySelector&&node.querySelector('#actions-dialog')))needsActions=true;});});if(needsAbout)requestAnimationFrame(compactAbout);if(needsActions)requestAnimationFrame(decorateActionSheet);if(needsStatus)normalizeStatusMessage();if(needsConnection)syncConnectionIndicator();});observer.observe(document.body,{childList:true,subtree:true,characterData:true});var refresh=document.getElementById('last-refresh');if(refresh)new MutationObserver(function(){pulseConnection();}).observe(refresh,{childList:true,subtree:true,characterData:true});}

  function init(){if(initialized)return;initialized=true;normalizeStatusMessage();syncConnectionIndicator();installTooltips();compactAbout();decorateActionSheet();observe();setTimeout(function(){compactAbout();decorateActionSheet();syncConnectionIndicator();},700);global.addEventListener('weigg:languagechange',function(){installTooltips();compactAbout();decorateActionSheet();syncConnectionIndicator();});}

  W.PolishRuntime={init:init,compactAbout:compactAbout,decorateActionSheet:decorateActionSheet,syncConnectionIndicator:syncConnectionIndicator};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
