(function(global){
  'use strict';
  var W=global.WeiG,U=W&&W.util;
  if(!W||!U||W.PolishRuntime)return;

  var initialized=false,tooltipNode=null,activeTarget=null;
  function zh(){return !!(W.I18n&&W.I18n.getLocale&&W.I18n.getLocale()==='zh-CN');}
  function label(en,cn){return zh()?cn:en;}
  function viewport(){var v=global.visualViewport;return{left:v?v.offsetLeft:0,top:v?v.offsetTop:0,width:v?v.width:document.documentElement.clientWidth,height:v?v.height:document.documentElement.clientHeight};}
  function bindHeaderTooltip(target,text){if(!target)return target;target.dataset.headerTooltip=String(text||'');target.removeAttribute('title');return target;}
  function headerText(target){if(!target)return'';if(target.dataset&&target.dataset.headerTooltip)return target.dataset.headerTooltip;var id=target.id||'',host=target.closest&&target.closest('#theme-btn,#github-link,#blog-link,#logout-btn');if(host&&host!==target)id=host.id||id;if(id==='theme-btn'||id==='theme-utility-btn'||id==='theme-control')return W.Theme&&W.Theme.title?W.Theme.title():label('Theme','主题');if(id==='github-link')return'GitHub';if(id==='blog-link')return label('WeiG Share Blog','WeiG Share 博客');if(id==='logout-btn')return label('Log out','注销');return'';}
  function ensureTooltip(){if(tooltipNode&&tooltipNode.isConnected)return tooltipNode;tooltipNode=document.createElement('div');tooltipNode.id='polish-tooltip';tooltipNode.className='tooltip polish-tooltip';tooltipNode.setAttribute('role','tooltip');tooltipNode.setAttribute('aria-hidden','true');document.body.appendChild(tooltipNode);return tooltipNode;}
  function stripLegacy(root){if(!root)return;var nodes=[];if(root.nodeType===1&&(root.hasAttribute('title')||root.hasAttribute('data-tooltip')))nodes.push(root);if(root.querySelectorAll)nodes=nodes.concat(Array.from(root.querySelectorAll('[title],[data-tooltip]')));nodes.forEach(function(node){node.removeAttribute('title');node.removeAttribute('data-tooltip');});}
  function scrubChain(node){var current=node&&node.nodeType===1?node:node&&node.parentElement;for(var i=0;current&&current!==document.documentElement&&i<10;i++,current=current.parentElement){current.removeAttribute('title');current.removeAttribute('data-tooltip');}}
  function triggerFrom(event){var raw=event.target&&event.target.closest&&event.target.closest('[data-header-tooltip],#theme-btn,#github-link,#blog-link,#logout-btn');if(!raw)return null;if(raw.id==='theme-btn'){var trigger=raw.querySelector('.ui-select__trigger');if(trigger)return trigger;}return raw;}
  function positionTooltip(target){var tip=ensureTooltip(),v=viewport(),pad=10,gap=8,r=target.getBoundingClientRect(),right=v.left+v.width,bottom=v.top+v.height,maxWidth=Math.max(80,v.width-pad*2);tip.style.visibility='hidden';tip.style.left='0px';tip.style.top='0px';tip.style.width='max-content';tip.style.maxWidth=Math.min(320,maxWidth)+'px';tip.style.maxHeight='';tip.style.overflow='visible';var box=tip.getBoundingClientRect(),w=Math.min(box.width,maxWidth),h=box.height;if(box.width>maxWidth){tip.style.width=maxWidth+'px';box=tip.getBoundingClientRect();w=box.width;h=box.height;}var downSpace=bottom-pad-r.bottom-gap,upSpace=r.top-gap-(v.top+pad),placement='bottom';if(downSpace<h&&upSpace>=h)placement='top';else if(downSpace<h&&upSpace<h)placement=upSpace>downSpace?'top':'bottom';var sideSpace=Math.max(24,placement==='bottom'?downSpace:upSpace);if(h>sideSpace){tip.style.maxHeight=Math.floor(sideSpace)+'px';tip.style.overflow='auto';box=tip.getBoundingClientRect();h=Math.min(box.height,sideSpace);}var left=r.left+r.width/2-w/2;left=Math.min(right-pad-w,Math.max(v.left+pad,left));var top=placement==='bottom'?r.bottom+gap:r.top-gap-h;top=Math.min(bottom-pad-h,Math.max(v.top+pad,top));tip.style.left=Math.round(left)+'px';tip.style.top=Math.round(top)+'px';tip.style.visibility='visible';tip.dataset.placement=placement;return{placement:placement,left:left,top:top,width:w,height:h};}
  function showTooltip(target){if(!target)return;var text=headerText(target);if(!text)return;bindHeaderTooltip(target,text);var tip=ensureTooltip();tip.textContent=text;tip.classList.add('is-visible');tip.setAttribute('aria-hidden','false');tip.dataset.for=target.id||((target.closest&&target.closest('[id]'))||{}).id||'';activeTarget=target;requestAnimationFrame(function(){if(activeTarget===target&&target.isConnected)positionTooltip(target);});}
  function hideTooltip(target){if(target&&activeTarget&&target!==activeTarget&&!(target.contains&&target.contains(activeTarget)))return;if(tooltipNode){tooltipNode.classList.remove('is-visible');tooltipNode.setAttribute('aria-hidden','true');}activeTarget=null;}
  function refreshActive(){if(!activeTarget||!activeTarget.isConnected)return;var text=headerText(activeTarget);if(text&&tooltipNode)tooltipNode.textContent=text;requestAnimationFrame(function(){if(activeTarget)positionTooltip(activeTarget);});}
  function installTooltips(){if(document.documentElement.dataset.polishTooltips==='header-only')return;document.documentElement.dataset.polishTooltips='header-only';stripLegacy(document);document.addEventListener('mouseover',function(e){scrubChain(e.target);var t=triggerFrom(e);if(t)showTooltip(t);},true);document.addEventListener('mouseout',function(e){var t=triggerFrom(e);if(!t)return;var next=e.relatedTarget;if(next&&t.contains&&t.contains(next))return;hideTooltip(t);},true);document.addEventListener('focusin',function(e){scrubChain(e.target);var t=triggerFrom(e);if(t)showTooltip(t);},true);document.addEventListener('focusout',function(e){var t=triggerFrom(e);if(t)hideTooltip(t);},true);global.addEventListener('resize',refreshActive,{passive:true});global.addEventListener('scroll',refreshActive,true);if(global.visualViewport){visualViewport.addEventListener('resize',refreshActive,{passive:true});visualViewport.addEventListener('scroll',refreshActive,{passive:true});}['weigg:library-state','weigg:settings-render','weigg:route-state','weigg:status-state','weigg:maindata'].forEach(function(name){global.addEventListener(name,function(){requestAnimationFrame(function(){stripLegacy(document);});});});global.addEventListener('weigg:languagechange',function(){requestAnimationFrame(function(){stripLegacy(document);refreshActive();});});}

  function init(){if(initialized)return;initialized=true;installTooltips();}
  W.PolishRuntime={init:init,bindHeaderTooltip:bindHeaderTooltip,positionTooltip:positionTooltip,stripLegacyHoverMetadata:stripLegacy,hideTooltip:hideTooltip};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
