(function(global){
  'use strict';
  var W=global.WeiG, U=W.util;
  function ApiError(message,status,path){this.name='ApiError';this.message=message;this.status=status||0;this.path=path||'';}ApiError.prototype=Object.create(Error.prototype);
  function versionParts(v){return String(v||'0').replace(/^v/i,'').split('.').map(function(x){return parseInt(x,10)||0;});}
  function tr(key,vars){return W.I18n&&W.I18n.t?W.I18n.t(key,vars):String(key||'');}
  function contractUnavailable(path){return new ApiError(tr('api.contractUnavailable'),400,path);}
  function sourceActionDescriptor(action){var R=W.CapabilityRegistry;if(!R||typeof R.sourceActionDescriptor!=='function')return undefined;return R.sourceActionDescriptor(action);}
  function requireSourceAction(action,path){var desc=sourceActionDescriptor(action);if(desc===undefined)throw contractUnavailable(path);if(desc===null)throw new ApiError(tr('api.actionUnproven'),400,path);return desc;}
  function normalizeTorrentAddResult(result){
    if(result===null||result===undefined)return 'Ok.';
    var data=result,text='';
    if(typeof result==='string'){
      text=result.trim();
      if(!text)return 'Ok.';
      if(text==='Ok.'||text==='Fails.')return text;
      try{data=JSON.parse(text);}catch(_e){return text;}
    }
    if(data&&typeof data==='object'){
      var hasCounts=('success_count' in data)||('pending_count' in data)||('failure_count' in data);
      if(hasCounts){
        var accepted=(Number(data.success_count)||0)+(Number(data.pending_count)||0);
        if(accepted>0)return 'Ok.';
        try{return JSON.stringify(data);}catch(_e2){return tr('api.torrentRejected');}
      }
      try{return JSON.stringify(data);}catch(_e3){return String(data);}
    }
    return String(result);
  }
  function normalizeLogItems(items){return (Array.isArray(items)?items:[]).map(function(item){var x=Object.assign({},item),ts=Number(x.timestamp);if(Number.isFinite(ts)&&ts>=1e12)x.timestamp=Math.floor(ts/1000);return x;});}
  function normalizeCategories(items,path){if(Array.isArray(items)){var out={};items.forEach(function(item){var name=String(item||'').trim();if(name)out[name]={name:name,savePath:''};});return out;}if(items&&typeof items==='object')return items;throw new ApiError(tr('api.categoriesUnexpected'),200,path||'torrents/categories');}
  function Client(){this.qbVersion='0.0.0';this.webApiVersion='0.0.0';this.major=0;this.capabilities={};}
  Client.prototype.request=async function(path,options){options=options||{};var method=String(options.method||'GET').toUpperCase(),R=W.CapabilityRegistry;if(method==='POST'&&!/^auth\//.test(String(path||''))&&(!R||typeof R.isCertified!=='function'||!R.isCertified()))throw new ApiError(tr('api.writeBlocked'),400,path);var init={method:method,credentials:'same-origin',headers:options.headers||{}};if(options.form){init.headers['Content-Type']='application/x-www-form-urlencoded; charset=UTF-8';init.body=U.form(options.form);}else if(options.json!==undefined){init.headers['Content-Type']='application/json; charset=UTF-8';init.body=JSON.stringify(options.json);}else if(options.body){init.body=options.body;}var res=await fetch('api/v2/'+path.replace(/^\//,''),init);if(res.status===403){throw new ApiError(tr('api.sessionExpired'),403,path);}if(!res.ok){var txt='';try{txt=await res.text();}catch(_e){}throw new ApiError(txt||('HTTP '+res.status),res.status,path);}if(options.type==='text')return res.text();if(options.type==='blob')return res.blob();if(options.type==='void')return null;var text=await res.text();if(!text)return null;try{return JSON.parse(text);}catch(e){throw new ApiError(tr('api.parseFailed'),res.status,path);}};
  Client.prototype.detect=async function(){var results=await Promise.all([this.request('app/version',{type:'text'}),this.request('app/webapiVersion',{type:'text'}).catch(function(){return '2.0';})]);this.qbVersion=(results[0]||'0').trim();this.webApiVersion=(results[1]||'0').trim();this.major=versionParts(this.qbVersion)[0]||0;this.capabilities={certified:false};return this;};
  Client.prototype.getTorrents=function(opts){opts=opts||{};var q=new URLSearchParams(),R=W.CapabilityRegistry,next=Object.assign({},opts);if(next.filter!==undefined&&next.filter!==null&&next.filter!==''){if(!R||typeof R.upstreamTorrentFilter!=='function')return Promise.reject(contractUnavailable('torrents/info'));var mapped=R.upstreamTorrentFilter(next.filter);if(mapped===undefined)return Promise.reject(contractUnavailable('torrents/info'));if(mapped===null)return Promise.reject(new ApiError(tr('api.filterUnsupported'),400,'torrents/info'));next.filter=mapped;}['filter','category','tag','sort','reverse','limit','offset','hashes'].forEach(function(k){if(next[k]===undefined||next[k]===null||next[k]==='')return;q.set(k,String(next[k]));});return this.request('torrents/info?'+q.toString());};
  Client.prototype.getTransferInfo=function(){return this.request('transfer/info');};
  Client.prototype.getMainData=function(rid){return this.request('sync/maindata?rid='+(rid==null?0:encodeURIComponent(rid)));};
  Client.prototype.getAltSpeedMode=async function(){var v=await this.request('transfer/speedLimitsMode',{type:'text'});return String(v).trim()==='1';};
  Client.prototype.toggleAltSpeedMode=function(){requireSourceAction('transfercontroller.h:toggleSpeedLimitsModeAction','transfer/toggleSpeedLimitsMode');return this.request('transfer/toggleSpeedLimitsMode',{method:'POST',type:'void'});};
  Client.prototype.getGlobalDownloadLimit=async function(){var v=await this.request('transfer/downloadLimit',{type:'text'});return Number(String(v).trim())||0;};
  Client.prototype.setGlobalDownloadLimit=function(limit){requireSourceAction('transfercontroller.h:setDownloadLimitAction','transfer/setDownloadLimit');return this.request('transfer/setDownloadLimit',{method:'POST',form:{limit:Math.max(0,Math.round(Number(limit)||0))},type:'void'});};
  Client.prototype.getGlobalUploadLimit=async function(){var v=await this.request('transfer/uploadLimit',{type:'text'});return Number(String(v).trim())||0;};
  Client.prototype.setGlobalUploadLimit=function(limit){requireSourceAction('transfercontroller.h:setUploadLimitAction','transfer/setUploadLimit');return this.request('transfer/setUploadLimit',{method:'POST',form:{limit:Math.max(0,Math.round(Number(limit)||0))},type:'void'});};
  Client.prototype.settingsDynamicOptions=async function(provider,dependency){provider=provider||{};if(provider.kind!=='api-options')throw new ApiError(tr('api.settingsOptionProviderUnproven'),400,'settings/options');var endpoint=String(provider.endpoint||'').trim();if(!/^[A-Za-z0-9_-]+\/[A-Za-z0-9_-]+$/.test(endpoint))throw new ApiError(tr('api.settingsOptionEndpointInvalid'),400,'settings/options');var path=endpoint,queryParam=provider.queryParam==null?'':String(provider.queryParam).trim();if(queryParam){if(!/^[A-Za-z0-9_.-]+$/.test(queryParam))throw new ApiError(tr('api.settingsOptionQueryInvalid'),400,endpoint);var query=new URLSearchParams();query.set(queryParam,dependency==null?'':String(dependency));path+='?'+query.toString();}var data=await this.request(path),shape=String(provider.responseShape||'');if(shape==='string-array'){if(!Array.isArray(data)||data.some(function(value){return value===null||value===undefined||typeof value==='object';}))throw new ApiError(tr('api.settingsOptionUnexpected'),200,endpoint);return data.map(function(value){value=String(value);return{value:value,label:value};});}if(shape==='object-array'){var valueField=String(provider.valueField||''),labelField=String(provider.labelField||'');if(!valueField||!labelField||!Array.isArray(data))throw new ApiError(tr('api.settingsOptionUnexpected'),200,endpoint);return data.map(function(item){if(!item||typeof item!=='object'||Array.isArray(item)||!Object.prototype.hasOwnProperty.call(item,valueField)||!Object.prototype.hasOwnProperty.call(item,labelField))throw new ApiError(tr('api.settingsOptionUnexpected'),200,endpoint);return{value:String(item[valueField]==null?'':item[valueField]),label:String(item[labelField]==null?item[valueField]:item[labelField])};});}throw new ApiError(tr('api.settingsOptionShapeUnsupported'),400,endpoint);};
  Client.prototype.getPreferences=async function(){requireSourceAction('appcontroller.h:preferencesAction','app/preferences');return this.request('app/preferences');};
  Client.prototype.setPreferences=async function(prefs){requireSourceAction('appcontroller.h:setPreferencesAction','app/setPreferences');return this.request('app/setPreferences',{method:'POST',form:{json:JSON.stringify(prefs||{})},type:'void'});};
  Client.prototype.getAltSpeedLimits=async function(){var prefs=await this.getPreferences();return{down:Math.max(0,Math.round((Number(prefs&&prefs.alt_dl_limit)||0)*1024)),up:Math.max(0,Math.round((Number(prefs&&prefs.alt_up_limit)||0)*1024))};};
  Client.prototype.setAltSpeedLimits=function(down,up){return this.setPreferences({alt_dl_limit:Math.max(0,Math.round((Number(down)||0)/1024)),alt_up_limit:Math.max(0,Math.round((Number(up)||0)/1024))});};
  Client.prototype.getBuildInfo=function(){requireSourceAction('appcontroller.h:buildInfoAction','app/buildInfo');return this.request('app/buildInfo');};
  Client.prototype.getCookies=function(){requireSourceAction('appcontroller.h:cookiesAction','app/cookies');return this.request('app/cookies');};
  Client.prototype.setCookies=function(cookies){requireSourceAction('appcontroller.h:setCookiesAction','app/setCookies');return this.request('app/setCookies',{method:'POST',form:{cookies:JSON.stringify(Array.isArray(cookies)?cookies:[])},type:'void'});};
  Client.prototype.torrentCreatorAdd=function(params){requireSourceAction('torrentcreatorcontroller.h:addTaskAction','torrentcreator/addTask');return this.request('torrentcreator/addTask',{method:'POST',form:params||{}});};
  Client.prototype.torrentCreatorStatus=function(taskID){requireSourceAction('torrentcreatorcontroller.h:statusAction','torrentcreator/status');return this.request('torrentcreator/status'+(taskID?'?taskID='+encodeURIComponent(taskID):''));};
  Client.prototype.torrentCreatorDelete=function(taskID){requireSourceAction('torrentcreatorcontroller.h:deleteTaskAction','torrentcreator/deleteTask');return this.request('torrentcreator/deleteTask',{method:'POST',form:{taskID:taskID},type:'void'});};
  Client.prototype.torrentCreatorFile=function(taskID){requireSourceAction('torrentcreatorcontroller.h:torrentFileAction','torrentcreator/torrentFile');return this.request('torrentcreator/torrentFile?taskID='+encodeURIComponent(taskID),{type:'blob'});};
  Client.prototype._guardedTorrentAction=function(kind,form){var R=W.CapabilityRegistry;if(!R||typeof R.resolveTorrentActionDescriptor!=='function')return Promise.reject(contractUnavailable('torrents/'+kind));var desc=R.resolveTorrentActionDescriptor(kind);if(desc===undefined)return Promise.reject(contractUnavailable('torrents/'+kind));if(!desc||!desc.endpoint)return Promise.reject(new ApiError(tr('api.torrentActionUnsupported'),400,'torrents/'+kind));return this.request('torrents/'+desc.endpoint,{method:'POST',form:form||{},type:'void'});};
  Client.prototype.resume=function(hashes){return this._guardedTorrentAction('start',{hashes:hashes});};
  Client.prototype.pause=function(hashes){return this._guardedTorrentAction('stop',{hashes:hashes});};
  Client.prototype.delete=function(hashes,deleteFiles){return this._guardedTorrentAction('delete',{hashes:hashes,deleteFiles:!!deleteFiles});};
  Client.prototype.recheck=function(hashes){return this._guardedTorrentAction('recheck',{hashes:hashes});};
  Client.prototype.reannounce=function(hashes){return this._guardedTorrentAction('reannounce',{hashes:hashes});};
  Client.prototype.forceStart=function(hashes,value){return this._guardedTorrentAction('force',{hashes:hashes,value:!!value});};
  Client.prototype.setAutoManagement=function(hashes,enable){return this._guardedTorrentAction('autotmm',{hashes:hashes,enable:!!enable});};
  Client.prototype.toggleSequential=function(hashes){return this._guardedTorrentAction('sequential',{hashes:hashes});};
  Client.prototype.toggleFirstLast=function(hashes){return this._guardedTorrentAction('firstlast',{hashes:hashes});};
  Client.prototype.topPriority=function(hashes){return this._guardedTorrentAction('top',{hashes:hashes});};
  Client.prototype.bottomPriority=function(hashes){return this._guardedTorrentAction('bottom',{hashes:hashes});};
  Client.prototype.setLocation=function(hashes,location){return this._guardedTorrentAction('location',{hashes:hashes,location:location});};
  Client.prototype.setCategory=function(hashes,category){requireSourceAction('torrentscontroller.h:setCategoryAction','torrents/setCategory');return this.request('torrents/setCategory',{method:'POST',form:{hashes:hashes,category:category},type:'void'});};
  Client.prototype.addTags=function(hashes,tags){requireSourceAction('torrentscontroller.h:addTagsAction','torrents/addTags');return this.request('torrents/addTags',{method:'POST',form:{hashes:hashes,tags:tags},type:'void'});};
  Client.prototype.removeTags=function(hashes,tags){requireSourceAction('torrentscontroller.h:removeTagsAction','torrents/removeTags');return this.request('torrents/removeTags',{method:'POST',form:{hashes:hashes,tags:tags},type:'void'});};
  Client.prototype.renameTorrent=function(hash,name){return this._guardedTorrentAction('rename',{hash:hash,name:name});};
  Client.prototype.setDownloadLimit=function(hashes,limit){return this._guardedTorrentAction('dllimit',{hashes:hashes,limit:limit});};
  Client.prototype.setUploadLimit=function(hashes,limit){return this._guardedTorrentAction('uplimit',{hashes:hashes,limit:limit});};
  Client.prototype.add=async function(urls,files,savepath,extra){var desc=requireSourceAction('torrentscontroller.h:addAction','torrents/add'),allowed=new Set(Array.isArray(desc.parameters)?desc.parameters:[]),fd=new FormData();function append(name,value){if(value===''||value==null)return;if(!allowed.has(name))throw new ApiError(tr('api.actionUnproven')+': '+name,400,'torrents/add');fd.append(name,String(value));}if(urls&&urls.trim())append('urls',urls.trim());if(savepath&&savepath.trim())append('savepath',savepath.trim());Object.keys(extra||{}).forEach(function(k){append(k,extra[k]);});Array.from(files||[]).forEach(function(file){fd.append('torrents',file,file.name);});var result=await this.request('torrents/add',{method:'POST',body:fd,type:'text'});return normalizeTorrentAddResult(result);};
  Client.prototype.properties=function(hash){requireSourceAction('torrentscontroller.h:propertiesAction','torrents/properties');return this.request('torrents/properties?hash='+encodeURIComponent(hash));};
  Client.prototype.files=function(hash){requireSourceAction('torrentscontroller.h:filesAction','torrents/files');return this.request('torrents/files?hash='+encodeURIComponent(hash));};
  Client.prototype.setFilePriority=function(hash,ids,priority){requireSourceAction('torrentscontroller.h:filePrioAction','torrents/filePrio');return this.request('torrents/filePrio',{method:'POST',form:{hash:hash,id:ids,priority:priority},type:'void'});};
  Client.prototype.trackers=function(hash){requireSourceAction('torrentscontroller.h:trackersAction','torrents/trackers');return this.request('torrents/trackers?hash='+encodeURIComponent(hash));};
  Client.prototype.addTrackers=function(hash,urls){requireSourceAction('torrentscontroller.h:addTrackersAction','torrents/addTrackers');return this.request('torrents/addTrackers',{method:'POST',form:{hash:hash,urls:urls},type:'void'});};
  Client.prototype.removeTrackers=function(hash,urls){return this._guardedTorrentAction('removeTrackers',{hash:hash,urls:urls});};
  Client.prototype.editTracker=async function(hash,origUrl,newUrl){var desc=requireSourceAction('torrentscontroller.h:editTrackerAction','torrents/editTracker'),form={};if(desc!==undefined){var parameters=Array.isArray(desc.parameters)?desc.parameters:[],required=Array.isArray(desc.required)?desc.required:[];if(parameters.indexOf('hash')<0)throw new ApiError(tr('api.editTrackerHashMissing'),400,'torrents/editTracker');form.hash=hash;if(parameters.indexOf('origUrl')>=0)form.origUrl=origUrl;else if(parameters.indexOf('url')>=0)form.url=origUrl;else throw new ApiError(tr('api.editTrackerUrlMissing'),400,'torrents/editTracker');if(parameters.indexOf('newUrl')>=0)form.newUrl=newUrl;else throw new ApiError(tr('api.editTrackerEditUnproven'),400,'torrents/editTracker');for(var i=0;i<required.length;i++)if(!Object.prototype.hasOwnProperty.call(form,required[i]))throw new ApiError(tr('api.editTrackerParameterUnsupported'),400,'torrents/editTracker');return this.request('torrents/'+(desc.endpoint||'editTracker'),{method:'POST',form:form,type:'void'});}form={hash:hash,newUrl:newUrl};if(this.capabilities.trackerEditUrl===true)form.url=origUrl;else form.origUrl=origUrl;return this.request('torrents/editTracker',{method:'POST',form:form,type:'void'});};
  Client.prototype.webseeds=function(hash){requireSourceAction('torrentscontroller.h:webseedsAction','torrents/webseeds');return this.request('torrents/webseeds?hash='+encodeURIComponent(hash));};
  Client.prototype.peers=async function(hash){requireSourceAction('synccontroller.h:torrentPeersAction','sync/torrentPeers');var data=await this.request('sync/torrentPeers?rid=0&hash='+encodeURIComponent(hash));if(!data||typeof data!=='object'||Array.isArray(data)||!data.peers||typeof data.peers!=='object'||Array.isArray(data.peers))throw new ApiError(tr('api.peersUnexpected'),200,'sync/torrentPeers');var peers=data.peers;return Object.keys(peers).map(function(k){var p=peers[k]||{};p.__key=k;return p;});};
  Client.prototype.banPeers=function(peers){requireSourceAction('transfercontroller.h:banPeersAction','transfer/banPeers');return this.request('transfer/banPeers',{method:'POST',form:{peers:peers},type:'void'});};
  Client.prototype.categories=async function(){var direct=sourceActionDescriptor('torrentscontroller.h:categoriesAction');if(direct!==null&&direct!==undefined)return normalizeCategories(await this.request('torrents/categories'),'torrents/categories');var sync=sourceActionDescriptor('synccontroller.h:maindataAction');if(sync!==null&&sync!==undefined){var data=await this.request('sync/maindata?rid=0');return normalizeCategories(data&&data.categories,'sync/maindata');}if(direct===undefined||sync===undefined)throw contractUnavailable('torrents/categories');requireSourceAction('torrentscontroller.h:categoriesAction','torrents/categories');return {};};
  Client.prototype.tags=function(){requireSourceAction('torrentscontroller.h:tagsAction','torrents/tags');return this.request('torrents/tags');};
  Client.prototype.createCategory=function(category,savePath){requireSourceAction('torrentscontroller.h:createCategoryAction','torrents/createCategory');return this.request('torrents/createCategory',{method:'POST',form:{category:category,savePath:savePath||''},type:'void'});};
  Client.prototype.removeCategories=function(categories){requireSourceAction('torrentscontroller.h:removeCategoriesAction','torrents/removeCategories');return this.request('torrents/removeCategories',{method:'POST',form:{categories:categories},type:'void'});};
  Client.prototype.createTags=function(tags){requireSourceAction('torrentscontroller.h:createTagsAction','torrents/createTags');return this.request('torrents/createTags',{method:'POST',form:{tags:tags},type:'void'});};
  Client.prototype.deleteTags=function(tags){requireSourceAction('torrentscontroller.h:deleteTagsAction','torrents/deleteTags');return this.request('torrents/deleteTags',{method:'POST',form:{tags:tags},type:'void'});};
  Client.prototype.logs=async function(lastId){requireSourceAction('logcontroller.h:mainAction','log/main');var q='normal=true&info=true&warning=true&critical=true&last_known_id='+(lastId==null?-1:lastId);return normalizeLogItems(await this.request('log/main?'+q));};
  Client.prototype.peerLogs=async function(lastId){requireSourceAction('logcontroller.h:peersAction','log/peers');return normalizeLogItems(await this.request('log/peers?last_known_id='+(lastId==null?-1:lastId)));};
  Client.prototype.rssItems=function(withData){requireSourceAction('rsscontroller.h:itemsAction','rss/items');return this.request('rss/items?withData='+(withData?'true':'false'));};
  Client.prototype.rssAddFeed=function(url,path){requireSourceAction('rsscontroller.h:addFeedAction','rss/addFeed');return this.request('rss/addFeed',{method:'POST',form:{url:url,path:path||''},type:'void'});};
  Client.prototype.rssRemoveItem=function(path){requireSourceAction('rsscontroller.h:removeItemAction','rss/removeItem');return this.request('rss/removeItem',{method:'POST',form:{path:path},type:'void'});};
  Client.prototype.rssRefreshItem=function(itemPath){requireSourceAction('rsscontroller.h:refreshItemAction','rss/refreshItem');return this.request('rss/refreshItem',{method:'POST',form:{itemPath:itemPath},type:'void'});};
  Client.prototype.rssRules=function(){requireSourceAction('rsscontroller.h:rulesAction','rss/rules');return this.request('rss/rules');};
  Client.prototype.rssSetRule=function(ruleName,ruleDef){requireSourceAction('rsscontroller.h:setRuleAction','rss/setRule');return this.request('rss/setRule',{method:'POST',form:{ruleName:String(ruleName||''),ruleDef:JSON.stringify(ruleDef||{})},type:'void'});};
  Client.prototype.rssRenameRule=function(ruleName,newRuleName){requireSourceAction('rsscontroller.h:renameRuleAction','rss/renameRule');return this.request('rss/renameRule',{method:'POST',form:{ruleName:String(ruleName||''),newRuleName:String(newRuleName||'')},type:'void'});};
  Client.prototype.rssRemoveRule=function(ruleName){requireSourceAction('rsscontroller.h:removeRuleAction','rss/removeRule');return this.request('rss/removeRule',{method:'POST',form:{ruleName:String(ruleName||'')},type:'void'});};
  Client.prototype.rssMatchingArticles=function(ruleName){requireSourceAction('rsscontroller.h:matchingArticlesAction','rss/matchingArticles');return this.request('rss/matchingArticles?ruleName='+encodeURIComponent(String(ruleName||'')));};
  Client.prototype.rssMarkAsRead=function(itemPath,articleId){requireSourceAction('rsscontroller.h:markAsReadAction','rss/markAsRead');var form={itemPath:String(itemPath||'')};if(articleId!==undefined&&articleId!==null)form.articleId=String(articleId);return this.request('rss/markAsRead',{method:'POST',form:form,type:'void'});};
  Client.prototype.searchPlugins=function(){requireSourceAction('searchcontroller.h:pluginsAction','search/plugins');return this.request('search/plugins');};
  Client.prototype.searchStart=function(pattern,plugins,category){requireSourceAction('searchcontroller.h:startAction','search/start');return this.request('search/start',{method:'POST',form:{pattern:pattern,plugins:plugins||'enabled',category:category||'all'}});};
  Client.prototype.searchStatus=function(id){requireSourceAction('searchcontroller.h:statusAction','search/status');return this.request('search/status'+(id!=null?'?id='+encodeURIComponent(id):''));};
  Client.prototype.searchResults=function(id,limit,offset){requireSourceAction('searchcontroller.h:resultsAction','search/results');return this.request('search/results?id='+encodeURIComponent(id)+'&limit='+(limit||50)+'&offset='+(offset||0));};
  Client.prototype.searchStop=function(id){requireSourceAction('searchcontroller.h:stopAction','search/stop');return this.request('search/stop',{method:'POST',form:{id:id},type:'void'});};
  Client.prototype.logout=function(){return this.request('auth/logout',{method:'POST',type:'void'});};
  W.ApiError=ApiError;W.QBClient=Client;
})(window);
