(function(global){
  'use strict';
  var W=global.WeiG, U=W.util;
  function ApiError(message,status,path){this.name='ApiError';this.message=message;this.status=status||0;this.path=path||'';}ApiError.prototype=Object.create(Error.prototype);
  function versionParts(v){return String(v||'0').replace(/^v/i,'').split('.').map(function(x){return parseInt(x,10)||0;});}
  function atLeast(actual,required){var a=versionParts(actual),b=versionParts(required),n=Math.max(a.length,b.length);for(var i=0;i<n;i++){var av=a[i]||0,bv=b[i]||0;if(av>bv)return true;if(av<bv)return false;}return true;}
  function localeText(en,zh){return W.I18n&&W.I18n.getLocale&&W.I18n.getLocale()==='zh-CN'?zh:en;}
  function sourceActionDescriptor(action){var R=W.ReleaseProfile,profile=R&&R.current&&R.current();if(!R||!profile)return undefined;if(profile.fallback===true)return null;if(typeof R.actionDescriptor==='function')return R.actionDescriptor(action);if(typeof R.hasAction==='function'&&R.hasAction(action))return{sourceAction:action,parameters:[],required:[],optional:[]};return null;}
  function requireSourceAction(action,path){var desc=sourceActionDescriptor(action);if(desc===null)throw new ApiError(localeText('This API action is not source-proven for the current qBittorrent release.','当前 qBittorrent 版本未由源码证明支持此 API 操作。'),400,path);return desc;}
  function normalizeTorrentAddResult(result){
    if(result===null||result===undefined)return 'Ok.';
    var data=result,text='';
    if(typeof result==='string'){
      text=result.trim();
      if(!text)return 'Ok.';
      if(text==='Ok.'||text==='Fails.')return text;
      try{data=JSON.parse(text);}catch(_e){return text;}
    }
    if(data&&typeof data==='object'){
      var hasCounts=('success_count' in data)||('pending_count' in data)||('failure_count' in data);
      if(hasCounts){
        var accepted=(Number(data.success_count)||0)+(Number(data.pending_count)||0);
        if(accepted>0)return 'Ok.';
        try{return JSON.stringify(data);}catch(_e2){return localeText('qBittorrent did not accept the torrent.','qBittorrent 未接受该种子。');}
      }
      try{return JSON.stringify(data);}catch(_e3){return String(data);}
    }
    return String(result);
  }
  function normalizeLogItems(items){return (Array.isArray(items)?items:[]).map(function(item){var x=Object.assign({},item),ts=Number(x.timestamp);if(Number.isFinite(ts)&&ts>=1e12)x.timestamp=Math.floor(ts/1000);return x;});}
  function Client(){this.qbVersion='0.0.0';this.webApiVersion='0.0.0';this.major=0;this.capabilities={};}
  Client.prototype.request=async function(path,options){options=options||{};var init={method:options.method||'GET',credentials:'same-origin',headers:options.headers||{}};if(options.form){init.headers['Content-Type']='application/x-www-form-urlencoded; charset=UTF-8';init.body=U.form(options.form);}else if(options.json!==undefined){init.headers['Content-Type']='application/json; charset=UTF-8';init.body=JSON.stringify(options.json);}else if(options.body){init.body=options.body;}var res=await fetch('api/v2/'+path.replace(/^\//,''),init);if(res.status===403){throw new ApiError(localeText('Session expired. Please sign in again.','会话已失效，请重新登录。'),403,path);}if(!res.ok){var txt='';try{txt=await res.text();}catch(_e){}throw new ApiError(txt||('HTTP '+res.status),res.status,path);}if(options.type==='text')return res.text();if(options.type==='blob')return res.blob();if(options.type==='void')return null;var text=await res.text();if(!text)return null;try{return JSON.parse(text);}catch(e){throw new ApiError(localeText('The API returned data that could not be parsed.','API 返回了无法解析的数据。'),res.status,path);}};
  Client.prototype.detect=async function(){var results=await Promise.all([this.request('app/version',{type:'text'}),this.request('app/webapiVersion',{type:'text'}).catch(function(){return '2.0';})]);this.qbVersion=(results[0]||'0').trim();this.webApiVersion=(results[1]||'0').trim();this.major=versionParts(this.qbVersion)[0]||0;var v=this.webApiVersion;this.capabilities={legacy4:this.major===4,modern5:this.major>=5,certified:false,rss:atLeast(v,'2.1.0'),search:atLeast(v,'2.1.1'),trackerEdit:atLeast(v,'2.2.0'),rssRefresh:atLeast(v,'2.2.1'),tags:atLeast(v,'2.3.0'),peerBan:atLeast(v,'2.3.0'),buildInfo:atLeast(v,'2.3.0'),renameFile:atLeast(v,'2.4.0'),stalledFilter:atLeast(v,'2.4.1'),contentPath:atLeast(v,'2.6.1'),addTags:atLeast(v,'2.6.2'),renameFolder:atLeast(v,'2.8.0'),fileIndexes:atLeast(v,'2.8.2'),tagFilter:atLeast(v,'2.8.3'),privateFlag:this.major>=5,logs:atLeast(this.qbVersion,'4.1.0'),globalSpeedLimits:true,altSpeedLimits:true,mainData:true,sessionStats:true,torrentCreator:this.major>=5&&atLeast(v,'2.11.0'),cookies:atLeast(v,'2.11.3'),trackerEditUrl:atLeast(v,'2.13.0'),structuredTorrentAdd:atLeast(v,'2.14.0'),webseeds:true,categories:true,preferences:true};if(this.qbVersion.replace(/^v/i,'')==='4.3.3')this.capabilities.renameFolder=true;return this;};
  Client.prototype.applyCapabilityRegistry=function(registry){var R=W.ReleaseProfile,self=this,map={privateFilter:'privateFlag',tags:'tags',stalledFilter:'stalledFilter',rss:'rss',search:'search',logs:'logs',peerBan:'peerBan'};this.capabilities.certified=!!(R&&R.isCertified&&R.isCertified());if(registry&&typeof registry.supports==='function')Object.keys(map).forEach(function(id){self.capabilities[map[id]]=!!registry.supports(id);});return this;};
  Client.prototype.getTorrents=function(opts){opts=opts||{};var q=new URLSearchParams(),self=this,R=W.ReleaseProfile,next=Object.assign({},opts);if(next.filter!==undefined&&next.filter!==null&&next.filter!==''){var mapped=R&&R.upstreamTorrentFilter?R.upstreamTorrentFilter(next.filter):null;if(mapped!==null)next.filter=mapped;else if(R&&R.upstreamTorrentFilter)return Promise.reject(new ApiError(localeText('This torrent filter is not supported by the current qBittorrent release.','当前 qBittorrent 版本不支持此 Torrent 筛选。'),400,'torrents/info'));else if(next.filter==='paused'&&self.major>=5)next.filter='stopped';else if(next.filter==='stopped'&&self.major===4)next.filter='paused';}['filter','category','tag','sort','reverse','limit','offset','hashes'].forEach(function(k){if(next[k]===undefined||next[k]===null||next[k]==='')return;q.set(k,String(next[k]));});return this.request('torrents/info?'+q.toString());};
  Client.prototype.getTransferInfo=function(){return this.request('transfer/info');};
  Client.prototype.getMainData=function(rid){return this.request('sync/maindata?rid='+(rid==null?0:encodeURIComponent(rid)));};
  Client.prototype.getAltSpeedMode=async function(){var v=await this.request('transfer/speedLimitsMode',{type:'text'});return String(v).trim()==='1';};
  Client.prototype.toggleAltSpeedMode=function(){requireSourceAction('transfercontroller.h:toggleSpeedLimitsModeAction','transfer/toggleSpeedLimitsMode');return this.request('transfer/toggleSpeedLimitsMode',{method:'POST',type:'void'});};
  Client.prototype.getGlobalDownloadLimit=async function(){var v=await this.request('transfer/downloadLimit',{type:'text'});return Number(String(v).trim())||0;};
  Client.prototype.setGlobalDownloadLimit=function(limit){requireSourceAction('transfercontroller.h:setDownloadLimitAction','transfer/setDownloadLimit');return this.request('transfer/setDownloadLimit',{method:'POST',form:{limit:Math.max(0,Math.round(Number(limit)||0))},type:'void'});};
  Client.prototype.getGlobalUploadLimit=async function(){var v=await this.request('transfer/uploadLimit',{type:'text'});return Number(String(v).trim())||0;};
  Client.prototype.setGlobalUploadLimit=function(limit){requireSourceAction('transfercontroller.h:setUploadLimitAction','transfer/setUploadLimit');return this.request('transfer/setUploadLimit',{method:'POST',form:{limit:Math.max(0,Math.round(Number(limit)||0))},type:'void'});};
  Client.prototype.getPreferences=async function(){requireSourceAction('appcontroller.h:preferencesAction','app/preferences');return this.request('app/preferences');};
  Client.prototype.setPreferences=async function(prefs){requireSourceAction('appcontroller.h:setPreferencesAction','app/setPreferences');return this.request('app/setPreferences',{method:'POST',form:{json:JSON.stringify(prefs||{})},type:'void'});};
  Client.prototype.getAltSpeedLimits=async function(){var prefs=await this.getPreferences();return{down:Math.max(0,Math.round((Number(prefs&&prefs.alt_dl_limit)||0)*1024)),up:Math.max(0,Math.round((Number(prefs&&prefs.alt_up_limit)||0)*1024))};};
  Client.prototype.setAltSpeedLimits=function(down,up){return this.setPreferences({alt_dl_limit:Math.max(0,Math.round((Number(down)||0)/1024)),alt_up_limit:Math.max(0,Math.round((Number(up)||0)/1024))});};
  Client.prototype.getBuildInfo=function(){requireSourceAction('appcontroller.h:buildInfoAction','app/buildInfo');return this.request('app/buildInfo');};
  Client.prototype.getCookies=function(){requireSourceAction('appcontroller.h:cookiesAction','app/cookies');return this.request('app/cookies');};
  Client.prototype.setCookies=function(cookies){requireSourceAction('appcontroller.h:setCookiesAction','app/setCookies');return this.request('app/setCookies',{method:'POST',form:{cookies:JSON.stringify(Array.isArray(cookies)?cookies:[])},type:'void'});};
  Client.prototype.torrentCreatorAdd=function(params){requireSourceAction('torrentcreatorcontroller.h:addTaskAction','torrentcreator/addTask');return this.request('torrentcreator/addTask',{method:'POST',form:params||{}});};
  Client.prototype.torrentCreatorStatus=function(taskID){requireSourceAction('torrentcreatorcontroller.h:statusAction','torrentcreator/status');return this.request('torrentcreator/status'+(taskID?'?taskID='+encodeURIComponent(taskID):''));};
  Client.prototype.torrentCreatorDelete=function(taskID){requireSourceAction('torrentcreatorcontroller.h:deleteTaskAction','torrentcreator/deleteTask');return this.request('torrentcreator/deleteTask',{method:'POST',form:{taskID:taskID},type:'void'});};
  Client.prototype.torrentCreatorFile=function(taskID){requireSourceAction('torrentcreatorcontroller.h:torrentFileAction','torrentcreator/torrentFile');return this.request('torrentcreator/torrentFile?taskID='+encodeURIComponent(taskID),{type:'blob'});};
  Client.prototype._torrentAction=function(hashes,kind){var R=W.ReleaseProfile,action=R&&R.resolveTorrentAction?R.resolveTorrentAction(kind):null;if(!action){if(!R||!R.resolveTorrentAction)action=kind==='start'?(this.major>=5?'start':'resume'):(this.major>=5?'stop':'pause');else return Promise.reject(new ApiError(localeText('This torrent action is not supported by the current qBittorrent release.','当前 qBittorrent 版本不支持此 Torrent 操作。'),400,'torrents/'+kind));}return this.request('torrents/'+action,{method:'POST',form:{hashes:hashes},type:'void'});};
  Client.prototype._guardedTorrentAction=function(kind,fallbackEndpoint,form){var R=W.ReleaseProfile,desc=R&&R.resolveTorrentActionDescriptor?R.resolveTorrentActionDescriptor(kind):null;if(R&&R.resolveTorrentActionDescriptor&&!desc)return Promise.reject(new ApiError(localeText('This torrent action is not supported by the current qBittorrent release.','当前 qBittorrent 版本不支持此 Torrent 操作。'),400,'torrents/'+kind));return this.request('torrents/'+(desc&&desc.endpoint||fallbackEndpoint),{method:'POST',form:form||{},type:'void'});};
  Client.prototype.resume=function(hashes){return this._torrentAction(hashes,'start');};
  Client.prototype.pause=function(hashes){return this._torrentAction(hashes,'stop');};
  Client.prototype.delete=function(hashes,deleteFiles){return this._guardedTorrentAction('delete','delete',{hashes:hashes,deleteFiles:!!deleteFiles});};
  Client.prototype.recheck=function(hashes){return this._guardedTorrentAction('recheck','recheck',{hashes:hashes});};
  Client.prototype.reannounce=function(hashes){return this._guardedTorrentAction('reannounce','reannounce',{hashes:hashes});};
  Client.prototype.forceStart=function(hashes,value){return this._guardedTorrentAction('force','setForceStart',{hashes:hashes,value:!!value});};
  Client.prototype.setAutoManagement=function(hashes,enable){return this._guardedTorrentAction('autotmm','setAutoManagement',{hashes:hashes,enable:!!enable});};
  Client.prototype.toggleSequential=function(hashes){return this._guardedTorrentAction('sequential','toggleSequentialDownload',{hashes:hashes});};
  Client.prototype.toggleFirstLast=function(hashes){return this._guardedTorrentAction('firstlast','toggleFirstLastPiecePrio',{hashes:hashes});};
  Client.prototype.topPriority=function(hashes){return this._guardedTorrentAction('top','topPrio',{hashes:hashes});};
  Client.prototype.bottomPriority=function(hashes){return this._guardedTorrentAction('bottom','bottomPrio',{hashes:hashes});};
  Client.prototype.setLocation=function(hashes,location){return this._guardedTorrentAction('location','setLocation',{hashes:hashes,location:location});};
  Client.prototype.setCategory=function(hashes,category){requireSourceAction('torrentscontroller.h:setCategoryAction','torrents/setCategory');return this.request('torrents/setCategory',{method:'POST',form:{hashes:hashes,category:category},type:'void'});};
  Client.prototype.addTags=function(hashes,tags){requireSourceAction('torrentscontroller.h:addTagsAction','torrents/addTags');return this.request('torrents/addTags',{method:'POST',form:{hashes:hashes,tags:tags},type:'void'});};
  Client.prototype.removeTags=function(hashes,tags){requireSourceAction('torrentscontroller.h:removeTagsAction','torrents/removeTags');return this.request('torrents/removeTags',{method:'POST',form:{hashes:hashes,tags:tags},type:'void'});};
  Client.prototype.renameTorrent=function(hash,name){return this._guardedTorrentAction('rename','rename',{hash:hash,name:name});};
  Client.prototype.setDownloadLimit=function(hashes,limit){return this._guardedTorrentAction('dllimit','setDownloadLimit',{hashes:hashes,limit:limit});};
  Client.prototype.setUploadLimit=function(hashes,limit){return this._guardedTorrentAction('uplimit','setUploadLimit',{hashes:hashes,limit:limit});};
  Client.prototype.add=async function(urls,files,savepath,extra){requireSourceAction('torrentscontroller.h:addAction','torrents/add');var fd=new FormData();if(urls&&urls.trim())fd.append('urls',urls.trim());if(savepath&&savepath.trim())fd.append('savepath',savepath.trim());Object.keys(extra||{}).forEach(function(k){if(extra[k]!==''&&extra[k]!=null)fd.append(k,String(extra[k]));});Array.from(files||[]).forEach(function(file){fd.append('torrents',file,file.name);});var result=await this.request('torrents/add',{method:'POST',body:fd,type:'text'});return normalizeTorrentAddResult(result);};
  Client.prototype.properties=function(hash){requireSourceAction('torrentscontroller.h:propertiesAction','torrents/properties');return this.request('torrents/properties?hash='+encodeURIComponent(hash));};
  Client.prototype.files=function(hash){requireSourceAction('torrentscontroller.h:filesAction','torrents/files');return this.request('torrents/files?hash='+encodeURIComponent(hash));};
  Client.prototype.setFilePriority=function(hash,ids,priority){requireSourceAction('torrentscontroller.h:filePrioAction','torrents/filePrio');return this.request('torrents/filePrio',{method:'POST',form:{hash:hash,id:ids,priority:priority},type:'void'});};
  Client.prototype.trackers=function(hash){requireSourceAction('torrentscontroller.h:trackersAction','torrents/trackers');return this.request('torrents/trackers?hash='+encodeURIComponent(hash));};
  Client.prototype.addTrackers=function(hash,urls){requireSourceAction('torrentscontroller.h:addTrackersAction','torrents/addTrackers');return this.request('torrents/addTrackers',{method:'POST',form:{hash:hash,urls:urls},type:'void'});};
  Client.prototype.removeTrackers=function(hash,urls){return this._guardedTorrentAction('removeTrackers','removeTrackers',{hash:hash,urls:urls});};
  Client.prototype.editTracker=async function(hash,origUrl,newUrl){var desc=requireSourceAction('torrentscontroller.h:editTrackerAction','torrents/editTracker'),form={};if(desc!==undefined){var parameters=Array.isArray(desc.parameters)?desc.parameters:[],required=Array.isArray(desc.required)?desc.required:[];if(parameters.indexOf('hash')<0)throw new ApiError(localeText('The current editTracker source contract does not expose the hash parameter.','当前 editTracker 源码契约未声明 hash 参数。'),400,'torrents/editTracker');form.hash=hash;if(parameters.indexOf('origUrl')>=0)form.origUrl=origUrl;else if(parameters.indexOf('url')>=0)form.url=origUrl;else throw new ApiError(localeText('The current editTracker source contract does not expose a supported tracker URL parameter.','当前 editTracker 源码契约未声明可支持的 Tracker URL 参数。'),400,'torrents/editTracker');if(parameters.indexOf('newUrl')>=0)form.newUrl=newUrl;else throw new ApiError(localeText('The current editTracker source contract cannot prove URL editing.','当前 editTracker 源码契约无法证明支持 URL 编辑。'),400,'torrents/editTracker');for(var i=0;i<required.length;i++)if(!Object.prototype.hasOwnProperty.call(form,required[i]))throw new ApiError(localeText('The current editTracker source contract requires a parameter this client cannot provide.','当前 editTracker 源码契约要求客户端无法安全提供的参数。'),400,'torrents/editTracker');return this.request('torrents/'+(desc.endpoint||'editTracker'),{method:'POST',form:form,type:'void'});}form={hash:hash,newUrl:newUrl};if(this.capabilities.trackerEditUrl===true||atLeast(this.webApiVersion,'2.13.0'))form.url=origUrl;else form.origUrl=origUrl;return this.request('torrents/editTracker',{method:'POST',form:form,type:'void'});};
  Client.prototype.webseeds=function(hash){requireSourceAction('torrentscontroller.h:webseedsAction','torrents/webseeds');return this.request('torrents/webseeds?hash='+encodeURIComponent(hash));};
  Client.prototype.peers=async function(hash){requireSourceAction('synccontroller.h:torrentPeersAction','sync/torrentPeers');var data=await this.request('sync/torrentPeers?rid=0&hash='+encodeURIComponent(hash));if(!data||typeof data!=='object'||Array.isArray(data)||!data.peers||typeof data.peers!=='object'||Array.isArray(data.peers))throw new ApiError(localeText('The Torrent Peers API returned an unexpected response.','Torrent Peers API 返回了异常响应。'),200,'sync/torrentPeers');var peers=data.peers;return Object.keys(peers).map(function(k){var p=peers[k]||{};p.__key=k;return p;});};
  Client.prototype.banPeers=function(peers){requireSourceAction('transfercontroller.h:banPeersAction','transfer/banPeers');return this.request('transfer/banPeers',{method:'POST',form:{peers:peers},type:'void'});};
  Client.prototype.categories=function(){requireSourceAction('torrentscontroller.h:categoriesAction','torrents/categories');return this.request('torrents/categories');};
  Client.prototype.tags=function(){requireSourceAction('torrentscontroller.h:tagsAction','torrents/tags');return this.request('torrents/tags');};
  Client.prototype.createCategory=function(category,savePath){requireSourceAction('torrentscontroller.h:createCategoryAction','torrents/createCategory');return this.request('torrents/createCategory',{method:'POST',form:{category:category,savePath:savePath||''},type:'void'});};
  Client.prototype.removeCategories=function(categories){requireSourceAction('torrentscontroller.h:removeCategoriesAction','torrents/removeCategories');return this.request('torrents/removeCategories',{method:'POST',form:{categories:categories},type:'void'});};
  Client.prototype.createTags=function(tags){requireSourceAction('torrentscontroller.h:createTagsAction','torrents/createTags');return this.request('torrents/createTags',{method:'POST',form:{tags:tags},type:'void'});};
  Client.prototype.deleteTags=function(tags){requireSourceAction('torrentscontroller.h:deleteTagsAction','torrents/deleteTags');return this.request('torrents/deleteTags',{method:'POST',form:{tags:tags},type:'void'});};
  Client.prototype.logs=async function(lastId){requireSourceAction('logcontroller.h:mainAction','log/main');var q='normal=true&info=true&warning=true&critical=true&last_known_id='+(lastId==null?-1:lastId);return normalizeLogItems(await this.request('log/main?'+q));};
  Client.prototype.peerLogs=async function(lastId){requireSourceAction('logcontroller.h:peersAction','log/peers');return normalizeLogItems(await this.request('log/peers?last_known_id='+(lastId==null?-1:lastId)));};
  Client.prototype.rssItems=function(withData){requireSourceAction('rsscontroller.h:itemsAction','rss/items');return this.request('rss/items?withData='+(withData?'true':'false'));};
  Client.prototype.rssAddFeed=function(url,path){requireSourceAction('rsscontroller.h:addFeedAction','rss/addFeed');return this.request('rss/addFeed',{method:'POST',form:{url:url,path:path||''},type:'void'});};
  Client.prototype.rssRemoveItem=function(path){requireSourceAction('rsscontroller.h:removeItemAction','rss/removeItem');return this.request('rss/removeItem',{method:'POST',form:{path:path},type:'void'});};
  Client.prototype.rssRefreshItem=function(itemPath){requireSourceAction('rsscontroller.h:refreshItemAction','rss/refreshItem');return this.request('rss/refreshItem',{method:'POST',form:{itemPath:itemPath},type:'void'});};
  Client.prototype.rssRules=function(){requireSourceAction('rsscontroller.h:rulesAction','rss/rules');return this.request('rss/rules');};
  Client.prototype.searchPlugins=function(){requireSourceAction('searchcontroller.h:pluginsAction','search/plugins');return this.request('search/plugins');};
  Client.prototype.searchStart=function(pattern,plugins,category){requireSourceAction('searchcontroller.h:startAction','search/start');return this.request('search/start',{method:'POST',form:{pattern:pattern,plugins:plugins||'enabled',category:category||'all'}});};
  Client.prototype.searchStatus=function(id){requireSourceAction('searchcontroller.h:statusAction','search/status');return this.request('search/status'+(id!=null?'?id='+encodeURIComponent(id):''));};
  Client.prototype.searchResults=function(id,limit,offset){requireSourceAction('searchcontroller.h:resultsAction','search/results');return this.request('search/results?id='+encodeURIComponent(id)+'&limit='+(limit||50)+'&offset='+(offset||0));};
  Client.prototype.searchStop=function(id){requireSourceAction('searchcontroller.h:stopAction','search/stop');return this.request('search/stop',{method:'POST',form:{id:id},type:'void'});};
  Client.prototype.logout=function(){return this.request('auth/logout',{method:'POST',type:'void'});};
  W.ApiError=ApiError;W.QBClient=Client;W.versionAtLeast=atLeast;
})(window);
