(function(global){
  'use strict';
  var W=global.WeiG,C=W&&W.Components;
  if(!W||!C)return;
  function tr(key,fallback,vars){return W.RuntimeI18n&&W.RuntimeI18n.t?W.RuntimeI18n.t(key,vars):fallback;}
  function baseT(key,fallback){var value=W.t?W.t(key):key;return value&&value!==key?value:fallback;}
  function isMobile(){return !!(global.matchMedia&&global.matchMedia('(max-width: 820px)').matches);}

  var baseState=C.state;
  var toneByState={downloading:'download',metaDL:'download',forcedDL:'download',uploading:'seed',forcedUP:'seed',stalledDL:'stalled-down',stalledUP:'stalled-up',pausedDL:'stopped',pausedUP:'stopped',stoppedDL:'stopped',stoppedUP:'stopped',queuedDL:'queued',queuedUP:'queued',checkingDL:'checking',checkingUP:'checking',checkingResumeData:'checking',allocating:'checking',moving:'checking'};
  C.state=function(code){var result=baseState(code),tone=toneByState[String(code||'')];return tone?[result[0],tone]:result;};

  var pageContracts=[['list-view','torrent-list','data'],['detail-view','detail-content','scroll'],['settings-view','settings-content','scroll'],['search-view','search-results','tool'],['rss-view','rss-content','tool'],['logs-view','logs-content','tool']];
  function installPageContracts(){pageContracts.forEach(function(spec){var view=document.getElementById(spec[0]),owner=document.getElementById(spec[1]);if(!view||!owner)return;view.dataset.pageLayout=spec[2];owner.dataset.primaryScroll='1';});}
  function primaryScrollOwners(view){return view?Array.from(view.querySelectorAll('[data-primary-scroll="1"]')):[];}

  var BaseVirtualList=W.VirtualList;
  function mobileRowHeight(){var density=document.documentElement.dataset.density||'standard';if(global.innerHeight<=680)return 104;if(density==='compact')return 102;if(density==='comfortable')return 126;return 114;}
  W.VirtualList=function(container,options){var opts=Object.assign({},options||{});if(container&&container.id==='torrent-list'&&isMobile())opts.rowHeight=mobileRowHeight();var instance=new BaseVirtualList(container,opts);if(container&&container.id==='torrent-list')container.__weiggTorrentVirtual=instance;return instance;};
  W.VirtualList.prototype=BaseVirtualList.prototype;Object.setPrototypeOf(W.VirtualList,BaseVirtualList);
  function syncTorrentRowHeight(){var list=document.getElementById('torrent-list'),instance=list&&list.__weiggTorrentVirtual;if(!instance)return;var next=isMobile()?mobileRowHeight():(document.documentElement.dataset.density==='compact'?48:document.documentElement.dataset.density==='comfortable'?64:56);if(instance.rowHeight!==next)instance.setRowHeight(next);}

  function compactMetricText(value){var s=String(value==null?'':value);s=s.replace(/^([↓↑])\s+/, '$1');s=s.replace(/(\d+\.\d*?[1-9])0+(?=\s*(?:[KMGTPE]?i?B|B)(?:\/s)?\b)/g,'$1');s=s.replace(/(\d+)\.0+(?=\s*(?:[KMGTPE]?i?B|B)(?:\/s)?\b)/g,'$1');s=s.replace(/(\d+(?:\.\d+)?)\s+(?=(?:[KMGTPE]?i?B|B)(?:\/s)?\b)/g,'$1');s=s.replace(/(\d+[dhms])\s+(?=\d)/g,'$1');return s;}
  function compactMetaCells(cells){cells.forEach(function(cell){if(cell.dataset.mobileFullText===undefined)cell.dataset.mobileFullText=cell.textContent||'';var full=cell.dataset.mobileFullText,compact=compactMetricText(full);cell.textContent=compact;cell.title=full;});}
  function fitMobileMeta(meta){if(!meta||!isMobile())return;var cells=Array.from(meta.querySelectorAll('.mobile-metric,.cell'));if(!cells.length)return;compactMetaCells(cells);meta.classList.remove('is-tight','is-ultra-tight');meta.style.removeProperty('--mobile-meta-gap');meta.style.removeProperty('--mobile-meta-font');if(meta.scrollWidth<=meta.clientWidth+1)return;meta.classList.add('is-tight');meta.style.setProperty('--mobile-meta-gap','3px');meta.style.setProperty('--mobile-meta-font','9px');if(meta.scrollWidth<=meta.clientWidth+1)return;meta.classList.add('is-ultra-tight');meta.style.setProperty('--mobile-meta-gap','2px');meta.style.setProperty('--mobile-meta-font','8px');}
  function fitVisibleMobileMeta(root){Array.from((root||document).querySelectorAll('.mobile-card-meta')).forEach(fitMobileMeta);}

  var commandBar=null,commandCount=null,filterControl=null;
  function filterOptions(){var nav=document.getElementById('filter-nav');if(!nav)return[];return Array.from(nav.querySelectorAll('[data-filter]')).filter(function(btn){return !btn.hidden;}).map(function(btn){return{value:btn.dataset.filter||'all',label:String(btn.textContent||'').replace(/\s·\s\d+$/,'').trim()||baseT('filter.all','All')};});}
  function currentFilter(){var state=W.LibraryController&&W.LibraryController.state?W.LibraryController.state():null;if(state)return state.filter||'all';var active=document.querySelector('#filter-nav [data-filter].is-active');return active?active.dataset.filter||'all':'all';}
  function countText(){var total=W.LibraryController&&W.LibraryController.total?W.LibraryController.total():null;return'Torrent '+(total==null?'…':total);}
  function syncFilterControl(){if(!filterControl||typeof filterControl.setOptions!=='function'||typeof filterControl.setValue!=='function')return;filterControl.setOptions(filterOptions());filterControl.setValue(currentFilter());}
  function syncCommandLocale(){if(commandCount)commandCount.textContent=countText();syncFilterControl();}
  function installCompactCommandBar(){if(commandBar)return commandBar;var slot=document.getElementById('mobile-command-slot'),toolbar=document.getElementById('torrent-selection-toolbar');if(!slot||!toolbar)return null;commandBar=document.createElement('div');commandBar.id='mobile-command-bar';commandBar.className='mobile-command-bar';var filterHost=document.createElement('div');filterHost.className='mobile-filter-control';filterControl=C.selectControl({options:filterOptions(),value:currentFilter(),ariaLabel:tr('v036.mobile.filter','Torrent filter'),onChange:function(value){if(W.LibraryController&&W.LibraryController.setFilter)W.LibraryController.setFilter(value);requestAnimationFrame(syncFilterControl);}});filterHost.appendChild(filterControl);commandCount=document.createElement('span');commandCount.className='mobile-command-count';commandCount.textContent=countText();commandBar.append(filterHost,commandCount);slot.appendChild(commandBar);return commandBar;}
  function mountCommandBar(){var toolbar=document.getElementById('torrent-selection-toolbar'),desktopSlot=document.getElementById('torrent-action-slot'),bar=commandBar||installCompactCommandBar();if(!toolbar||!desktopSlot||!bar)return;if(isMobile()){if(toolbar.parentElement!==bar)bar.appendChild(toolbar);}else if(toolbar.parentElement!==desktopSlot)desktopSlot.appendChild(toolbar);}
  function fitCommandBar(){if(!commandBar||!isMobile())return;commandBar.classList.remove('is-tight','is-ultra-tight');if(commandBar.scrollWidth<=commandBar.clientWidth+1)return;commandBar.classList.add('is-tight');if(commandBar.scrollWidth<=commandBar.clientWidth+1)return;commandBar.classList.add('is-ultra-tight');}

  var focusRegistry=[];
  function setDataViewportFocus(entry,on){if(!entry||!entry.owner||!entry.viewport)return;if(on===entry.active)return;if(on)entry.scrollTop=entry.viewport.scrollTop;entry.active=!!on;entry.owner.classList.toggle('is-data-focus',entry.active);entry.owner.dataset.dataFocus=entry.active?'1':'0';if(entry.button){entry.button.textContent=entry.active?'⤡':'⤢';entry.button.setAttribute('aria-pressed',entry.active?'true':'false');var text=entry.active?tr('v036.mobile.focus.collapse','Restore layout'):tr('v036.mobile.focus.expand','Expand list');entry.button.title=text;entry.button.setAttribute('aria-label',text);}requestAnimationFrame(function(){entry.viewport.scrollTop=entry.scrollTop||0;entry.viewport.__weiggVirtualScrollTop=entry.viewport.scrollTop;if(entry.viewport.__weiggTorrentVirtual)entry.viewport.__weiggTorrentVirtual.render();fitVisibleMobileMeta(entry.viewport);});}
  function registerDataViewport(options){options=options||{};var owner=typeof options.owner==='string'?document.querySelector(options.owner):options.owner,viewport=typeof options.viewport==='string'?document.querySelector(options.viewport):options.viewport,toolbar=typeof options.toolbar==='string'?document.querySelector(options.toolbar):options.toolbar;if(!owner||!viewport||!toolbar)return null;var existing=focusRegistry.find(function(item){return item.owner===owner&&item.viewport===viewport;});if(existing)return existing;var button=document.createElement('button');button.type='button';button.className='btn btn--ghost data-viewport-focus';button.dataset.dataViewportFocus='1';button.textContent='⤢';button.setAttribute('aria-pressed','false');var entry={owner:owner,viewport:viewport,toolbar:toolbar,button:button,active:null,scrollTop:0};button.addEventListener('click',function(){setDataViewportFocus(entry,!entry.active);});toolbar.appendChild(button);focusRegistry.push(entry);setDataViewportFocus(entry,false);return entry;}
  function installTorrentFocus(){registerDataViewport({owner:'#list-view',viewport:'#torrent-list',toolbar:'#torrent-focus-slot'});}

  var lastFree=null;
  function trimFixed(value,decimals){return Number(value).toFixed(decimals).replace(/\.0+$/,'').replace(/(\.\d*?[1-9])0+$/,'$1');}
  function formatFreeSpace(bytes){var n=Number(bytes);if(!Number.isFinite(n)||n<0)return'—';if(n<1024)return Math.round(n)+' B';var units=[['TiB',1099511627776],['GiB',1073741824],['MiB',1048576],['KiB',1024]];for(var i=0;i<units.length;i++)if(n>=units[i][1]){var value=n/units[i][1],decimals=value<10?2:(value<100?1:0);return trimFixed(value,decimals)+' '+units[i][0];}return Math.round(n)+' B';}
  function localizeStorage(node){if(!node)return;var label=node.querySelector('.status-storage__label'),value=node.querySelector('strong'),shown=value?value.textContent:'—';if(label)label.textContent=tr('v036.storage.free','Free');var bytes=(lastFree!=null&&Number.isFinite(Number(lastFree)))?Math.round(Number(lastFree)).toLocaleString():'—';node.title=tr('v036.storage.tooltip','Free space on the filesystem containing qBittorrent’s default save path: {value} ({bytes} bytes)',{value:shown,bytes:bytes});}
  function installStorageStatus(){var bar=document.querySelector('.statusbar');if(!bar)return null;var node=document.getElementById('status-free-space');if(!node){node=document.createElement('span');node.id='status-free-space';node.className='status-storage';node.dataset.tone='neutral';var icon=document.createElement('span');icon.className='status-storage__icon';icon.textContent='◫';icon.setAttribute('aria-hidden','true');var label=document.createElement('span');label.className='status-storage__label';var value=document.createElement('strong');value.textContent='—';node.append(icon,label,value);var message=document.getElementById('status-message');bar.insertBefore(node,message||null);}localizeStorage(node);return node;}
  function paintStorage(bytes){var node=installStorageStatus();if(!node)return;lastFree=Number(bytes);node.hidden=false;var strong=node.querySelector('strong');var next=formatFreeSpace(lastFree);if(strong&&strong.textContent!==next)strong.textContent=next;localizeStorage(node);}
  function refreshStorage(){var snap=W.TransferRuntime&&W.TransferRuntime.snapshot?W.TransferRuntime.snapshot():{};if(snap.freeSpace!=null&&Number.isFinite(Number(snap.freeSpace)))paintStorage(snap.freeSpace);else{var node=installStorageStatus();if(node&&lastFree==null)node.hidden=true;}}

  function syncResponsiveSystem(){installPageContracts();installCompactCommandBar();mountCommandBar();syncFilterControl();installTorrentFocus();syncTorrentRowHeight();fitVisibleMobileMeta();fitCommandBar();if(commandCount)commandCount.textContent=countText();if(W.SpatialRuntime&&W.SpatialRuntime.mountForViewport)W.SpatialRuntime.mountForViewport();}
  function init(){syncResponsiveSystem();installStorageStatus();refreshStorage();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
  document.addEventListener('visibilitychange',function(){if(!document.hidden){syncResponsiveSystem();refreshStorage();}});
  global.addEventListener('resize',function(){requestAnimationFrame(syncResponsiveSystem);},{passive:true});
  global.addEventListener('weigg:library-state',function(){requestAnimationFrame(syncResponsiveSystem);});
  global.addEventListener('weigg:maindata',function(event){var state=event.detail&&event.detail.serverState||{},free=state.free_space_on_disk;if(free!=null&&Number.isFinite(Number(free)))paintStorage(free);else refreshStorage();});
  global.addEventListener('weigg:languagechange',function(){localizeStorage(document.getElementById('status-free-space'));syncCommandLocale();focusRegistry.forEach(function(entry){if(entry.button){var text=entry.active?tr('v036.mobile.focus.collapse','Restore layout'):tr('v036.mobile.focus.expand','Expand list');entry.button.title=text;entry.button.setAttribute('aria-label',text);}});if(W.SpatialRuntime&&W.SpatialRuntime.syncFacets)W.SpatialRuntime.syncFacets();});

  W.MobileAdaptive={formatFreeSpace:formatFreeSpace,mobileRowHeight:mobileRowHeight,fitMobileMeta:fitMobileMeta,refreshStorage:refreshStorage,installPageContracts:installPageContracts,primaryScrollOwners:primaryScrollOwners,fitCommandBar:fitCommandBar,registerDataViewport:registerDataViewport,setDataViewportFocus:setDataViewportFocus};
})(window);
