(function(global){
  'use strict';
  var W=global.WeiG,C=W&&W.Components;
  if(!W||!C)return;
  function tr(key,vars){return W.I18n&&W.I18n.t?W.I18n.t(key,vars):String(key||'');}
  function trList(keys){return (keys||[]).map(function(key){return tr(key);});}
  function isMobile(){return !!(global.matchMedia&&global.matchMedia('(max-width: 820px)').matches);}

  var pageContracts=[['list-view','torrent-list','data'],['detail-view','detail-content','scroll'],['settings-view','settings-content','scroll'],['search-view','search-results','tool'],['rss-view','rss-content','tool'],['logs-view','logs-content','tool']];
  function installPageContracts(){pageContracts.forEach(function(spec){var view=document.getElementById(spec[0]),owner=document.getElementById(spec[1]);if(!view||!owner)return;view.dataset.pageLayout=spec[2];owner.dataset.primaryScroll='1';});}
  function primaryScrollOwners(view){return view?Array.from(view.querySelectorAll('[data-primary-scroll="1"]')):[];}

  function mobileRowHeight(){var density=document.documentElement.dataset.density||'standard';if(global.innerHeight<=680)return 94;if(density==='compact')return 94;if(density==='comfortable')return 104;return 98;}
  function desktopRowHeight(){var density=document.documentElement.dataset.density||'standard';return density==='compact'?48:density==='comfortable'?64:56;}
  function syncTorrentRowHeight(){var list=document.getElementById('torrent-list'),instance=list&&list.__weigTorrentVirtual;if(!instance||!instance.setRowHeight)return;var next=isMobile()?mobileRowHeight():desktopRowHeight();if(instance.rowHeight!==next)instance.setRowHeight(next);}

  function compactMetricText(value){var s=String(value==null?'':value);s=s.replace(/^([↓↑])\s+/, '$1');s=s.replace(/(\d+\.\d*?[1-9])0+(?=\s*(?:[KMGTPE]?i?B|B)(?:\/s)?\b)/g,'$1');s=s.replace(/(\d+)\.0+(?=\s*(?:[KMGTPE]?i?B|B)(?:\/s)?\b)/g,'$1');s=s.replace(/(\d+(?:\.\d+)?)\s+(?=(?:[KMGTPE]?i?B|B)(?:\/s)?\b)/g,'$1');s=s.replace(/(\d+[dhms])\s+(?=\d)/g,'$1');return s;}
  function compactMetaCells(cells){cells.forEach(function(cell){if(cell.dataset.mobileFullText===undefined)cell.dataset.mobileFullText=cell.textContent||'';var full=cell.dataset.mobileFullText,compact=compactMetricText(full);cell.textContent=compact;cell.removeAttribute('title');cell.setAttribute('aria-label',full);});}
  function fitMobileMeta(meta){if(!meta||!isMobile())return;var cells=Array.from(meta.querySelectorAll('.mobile-metric,.cell'));if(!cells.length)return;compactMetaCells(cells);meta.classList.remove('is-tight','is-ultra-tight');meta.style.removeProperty('--mobile-meta-gap');meta.style.removeProperty('--mobile-meta-font');if(meta.scrollWidth<=meta.clientWidth+1)return;meta.classList.add('is-tight');meta.style.setProperty('--mobile-meta-gap','4px');meta.style.setProperty('--mobile-meta-font','10px');if(meta.scrollWidth<=meta.clientWidth+1)return;meta.classList.add('is-ultra-tight');meta.style.setProperty('--mobile-meta-gap','3px');meta.style.setProperty('--mobile-meta-font','9px');}
  function fitVisibleMobileMeta(root){Array.from((root||document).querySelectorAll('.mobile-card-meta')).forEach(fitMobileMeta);}

  var detailTitleTimer=null,lastDetailTitleRoute='';
  function detailTitleNode(){return document.getElementById('detail-title');}
  function setDetailTitleExpanded(node,on){if(!node)return;node.classList.toggle('is-expanded',!!on);node.setAttribute('aria-expanded',on?'true':'false');}
  function copyText(value){value=String(value||'');if(!value)return Promise.reject(new Error('empty'));if(navigator.clipboard&&typeof navigator.clipboard.writeText==='function')return navigator.clipboard.writeText(value);return new Promise(function(resolve,reject){var area=document.createElement('textarea');area.value=value;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';area.style.pointerEvents='none';document.body.appendChild(area);area.select();try{if(document.execCommand&&document.execCommand('copy'))resolve();else reject(new Error('copy unavailable'));}catch(e){reject(e);}finally{area.remove();}});}
  function copyDetailTitle(){var node=detailTitleNode(),value=node&&String(node.textContent||'').trim();if(!value)return;copyText(value).then(function(){if(W.toast)W.toast(tr('responsive.copyTorrentMessage'),'success',{title:tr('common.copiedTitle')});}).catch(function(){if(W.toast)W.toast(tr('responsive.copyTorrentFailed'),'error',{title:tr('common.copyFailedTitle')});});}
  function installDetailTitleInteraction(){var node=detailTitleNode();if(!node||node.dataset.detailTitleAction==='copy-expand')return;node.dataset.detailTitleAction='copy-expand';node.tabIndex=0;node.setAttribute('role','button');node.setAttribute('aria-expanded','false');node.addEventListener('click',function(event){if(!isMobile()||event.detail>1)return;clearTimeout(detailTitleTimer);detailTitleTimer=setTimeout(function(){detailTitleTimer=null;copyDetailTitle();},260);});node.addEventListener('dblclick',function(event){if(!isMobile())return;event.preventDefault();clearTimeout(detailTitleTimer);detailTitleTimer=null;setDetailTitleExpanded(node,!node.classList.contains('is-expanded'));});node.addEventListener('keydown',function(event){if(!isMobile())return;if(event.key==='Enter'){event.preventDefault();copyDetailTitle();}else if(event.key===' '){event.preventDefault();setDetailTitleExpanded(node,!node.classList.contains('is-expanded'));}});}
  function syncDetailTitleContract(){installDetailTitleInteraction();var r=W.Router&&W.Router.route?W.Router.route():{name:'home',id:''},key=r.name==='torrent'?String(r.id||''):'';if(key!==lastDetailTitleRoute){clearTimeout(detailTitleTimer);detailTitleTimer=null;setDetailTitleExpanded(detailTitleNode(),false);lastDetailTitleRoute=key;}}

  function mountSelectionToolbar(){var toolbar=document.getElementById('torrent-selection-toolbar'),desktopSlot=document.getElementById('torrent-action-slot'),mobileSlot=document.getElementById('mobile-pager-actions-slot');if(!toolbar||!desktopSlot||!mobileSlot)return;if(isMobile()){if(toolbar.parentElement!==mobileSlot)mobileSlot.appendChild(toolbar);}else if(toolbar.parentElement!==desktopSlot)desktopSlot.appendChild(toolbar);}
  function syncPagerCopy(){if(!isMobile()||!W.LibraryController)return;var host=document.getElementById('page-label'),copy=host&&host.querySelector('.pager-index-copy');if(!copy)return;var state=W.LibraryController.state?W.LibraryController.state():null;if(!state)return;var page=Number(state.page||0)+1,size=Number(state.pageSize||50),total=W.LibraryController.total?W.LibraryController.total():null;if(total==null){copy.textContent=String(page);return;}var pages=Math.max(1,Math.ceil(Number(total||0)/size));copy.textContent=page+' / '+pages;}

  function ensureDrawerTelemetry(){
    var sidebar=document.getElementById('sidebar');if(!sidebar)return null;var host=document.getElementById('mobile-drawer-telemetry');if(host)return host;
    host=document.createElement('section');host.id='mobile-drawer-telemetry';host.className='sidebar__section mobile-drawer-telemetry mobile-only';
    var primary=document.createElement('div');primary.className='mobile-drawer-telemetry__row mobile-drawer-telemetry__row--primary';primary.dataset.drawerStatusRow='primary';
    var transfer=document.createElement('div');transfer.className='mobile-drawer-telemetry__row mobile-drawer-telemetry__row--transfer';transfer.dataset.drawerStatusRow='transfer';
    var chart=document.createElement('div');chart.id='mobile-drawer-transfer-chart';chart.className='mobile-drawer-transfer-chart';
    host.append(chart,transfer,primary);sidebar.appendChild(host);return host;
  }
  function moveNode(node,target){if(node&&target&&node.parentElement!==target)target.appendChild(node);}
  function mountStatusTelemetry(){
    var bar=document.querySelector('.statusbar');if(!bar)return;var torrents=document.getElementById('status-torrents'),storage=document.getElementById('status-free-space'),capsule=document.getElementById('transfer-capsule'),connection=document.getElementById('status-connection'),message=document.getElementById('status-message');
    if(isMobile()){
      var host=ensureDrawerTelemetry(),primary=host&&host.querySelector('[data-drawer-status-row="primary"]'),transfer=host&&host.querySelector('[data-drawer-status-row="transfer"]'),chart=host&&host.querySelector('#mobile-drawer-transfer-chart');
      moveNode(torrents,primary);moveNode(storage,primary);moveNode(capsule,transfer);moveNode(connection,transfer);if(W.Transfer&&W.Transfer.mountCompactChart&&chart)W.Transfer.mountCompactChart(chart);return;
    }
    [torrents,storage,capsule,connection,message].forEach(function(node){moveNode(node,bar);});
  }

  var lastFree=null,lastConnection='unknown',connectionDialog=null;
  function trimFixed(value,decimals){return Number(value).toFixed(decimals).replace(/\.0+$/,'').replace(/(\.\d*?[1-9])0+$/,'$1');}
  function formatFreeSpace(bytes){var n=Number(bytes);if(!Number.isFinite(n)||n<0)return'—';if(n<1024)return Math.round(n)+' B';var units=[['TiB',1099511627776],['GiB',1073741824],['MiB',1048576],['KiB',1024]];for(var i=0;i<units.length;i++)if(n>=units[i][1]){var value=n/units[i][1],decimals=value<10?2:(value<100?1:0);return trimFixed(value,decimals)+' '+units[i][0];}return Math.round(n)+' B';}
  function localizeStorage(node){if(!node)return;var label=node.querySelector('.status-storage__label'),value=node.querySelector('strong'),shown=value?value.textContent:'—';if(label)label.textContent=tr('status.storage.free');var bytes=(lastFree!=null&&Number.isFinite(Number(lastFree)))?Math.round(Number(lastFree)).toLocaleString():'—',description=tr('status.storage.tooltip',{value:shown,bytes:bytes});node.removeAttribute('title');node.setAttribute('aria-label',description);}
  function installStorageStatus(){var bar=document.querySelector('.statusbar');if(!bar)return null;var node=document.getElementById('status-free-space');if(!node){node=document.createElement('span');node.id='status-free-space';node.className='status-storage';node.dataset.tone='neutral';var icon=document.createElement('span');icon.className='status-storage__icon';icon.textContent='◫';icon.setAttribute('aria-hidden','true');var label=document.createElement('span');label.className='status-storage__label';var value=document.createElement('strong');value.textContent='—';node.append(icon,label,value);var connection=document.getElementById('status-connection'),message=document.getElementById('status-message');bar.insertBefore(node,connection||message||null);}localizeStorage(node);return node;}
  function paintStorage(bytes){var node=installStorageStatus();if(!node)return;lastFree=Number(bytes);node.hidden=false;var strong=node.querySelector('strong');var next=formatFreeSpace(lastFree);if(strong&&strong.textContent!==next)strong.textContent=next;localizeStorage(node);mountStatusTelemetry();}
  function refreshStorage(){var snap=W.TransferRuntime&&W.TransferRuntime.snapshot?W.TransferRuntime.snapshot():{};if(snap.freeSpace!=null&&Number.isFinite(Number(snap.freeSpace)))paintStorage(snap.freeSpace);else{var node=installStorageStatus();if(node&&lastFree==null)node.hidden=true;}}
  function normalizeConnection(status){var value=String(status||'unknown').toLowerCase();return value==='connected'||value==='firewalled'||value==='disconnected'||value==='error'?value:'unknown';}
  function connectionLabel(status){if(status==='connected')return tr('stats.connected');if(status==='firewalled')return tr('connection.networkLimited');if(status==='disconnected')return tr('stats.disconnected');if(status==='error')return tr('connection.unavailable');return'—';}
  function connectionReason(status){if(status==='connected')return tr('connection.reason.connected');if(status==='firewalled')return tr('connection.reason.firewalled');if(status==='disconnected')return tr('connection.reason.disconnected');if(status==='error')return tr('connection.reason.error');return tr('connection.reason.unknown');}
  function connectionSteps(status){if(status==='firewalled')return trList(['connection.step.firewalled.1','connection.step.firewalled.2','connection.step.firewalled.3','connection.step.firewalled.4','connection.step.firewalled.5']);if(status==='disconnected')return trList(['connection.step.disconnected.1','connection.step.disconnected.2','connection.step.disconnected.3']);if(status==='error')return trList(['connection.step.error.1','connection.step.error.2','connection.step.error.3']);return trList(['connection.step.default.1','connection.step.default.2','connection.step.default.3']);}
  function ensureConnectionDialog(){if(connectionDialog&&connectionDialog.isConnected)return connectionDialog;var d=W.DialogRuntime.create({id:'connection-dialog',className:'dialog surface surface--modal connection-dialog',draggable:true});d.innerHTML='<div class="dialog__head"><div><div class="eyebrow">CONNECTION</div><h2 class="connection-dialog__title"></h2></div><button type="button" class="icon-btn connection-dialog__close">×</button></div><div class="dialog__body connection-dialog__body"><div class="connection-dialog__summary"><span class="connection-dialog__dot" aria-hidden="true"></span><strong class="connection-dialog__state"></strong></div><p class="connection-dialog__reason"></p><div class="connection-dialog__environment"></div><div><h3 class="connection-dialog__help-title"></h3><ol class="connection-dialog__steps"></ol></div></div><div class="dialog__actions"><button type="button" class="btn btn--primary connection-dialog__done"></button></div>';d.querySelector('.connection-dialog__close').onclick=d.querySelector('.connection-dialog__done').onclick=function(){W.DialogRuntime.close(d);};connectionDialog=d;return d;}
  function networkSnapshotText(){var snap=W.TransferRuntime&&W.TransferRuntime.snapshot?W.TransferRuntime.snapshot():{};return tr('connection.networkSnapshot',{dht:snap.dhtNodes==null?'—':snap.dhtNodes,peers:snap.peers==null?'—':snap.peers});}
  function openConnectionDialog(){var d=ensureConnectionDialog(),status=lastConnection,label=connectionLabel(status),client=W.AppState&&W.AppState.client;d.dataset.connection=status;d.querySelector('.connection-dialog__title').textContent=tr('connection.title');d.querySelector('.connection-dialog__state').textContent=label;d.querySelector('.connection-dialog__reason').textContent=connectionReason(status);var env=d.querySelector('.connection-dialog__environment');env.textContent='';[tr('connection.environment.qb',{value:client&&client.qbVersion||'—'}),tr('connection.environment.webapi',{value:client&&client.webApiVersion||'—'}),tr('connection.environment.network',{value:networkSnapshotText()})].forEach(function(line){var row=document.createElement('div');row.className='connection-dialog__row';row.textContent=line;env.appendChild(row);});d.querySelector('.connection-dialog__help-title').textContent=tr('connection.troubleshooting');var steps=d.querySelector('.connection-dialog__steps');steps.textContent='';connectionSteps(status).forEach(function(step){var li=document.createElement('li');li.textContent=step;steps.appendChild(li);});d.querySelector('.connection-dialog__done').textContent=tr('app.close');W.DialogRuntime.open(d,{draggable:true});return d;}
  function installConnectionTrigger(){var footer=document.getElementById('status-connection');if(!footer||footer.dataset.connectionTrigger==='1')return footer;footer.dataset.connectionTrigger='1';footer.setAttribute('role','button');footer.tabIndex=0;footer.addEventListener('click',openConnectionDialog);footer.addEventListener('keydown',function(event){if(event.key==='Enter'||event.key===' '){event.preventDefault();openConnectionDialog();}});return footer;}
  function paintConnection(status){lastConnection=normalizeConnection(status);var label=connectionLabel(lastConnection),footer=installConnectionTrigger(),footerLabel=document.getElementById('status-connection-label');if(footer){footer.dataset.connection=lastConnection;footer.removeAttribute('data-tooltip');footer.setAttribute('aria-label',label+' — '+connectionReason(lastConnection));}if(footerLabel&&footerLabel.textContent!==label)footerLabel.textContent=label;mountStatusTelemetry();}

  function syncResponsiveSystem(){installPageContracts();mountSelectionToolbar();syncTorrentRowHeight();fitVisibleMobileMeta();syncPagerCopy();syncDetailTitleContract();mountStatusTelemetry();}
  function init(){installStorageStatus();refreshStorage();installConnectionTrigger();paintConnection(lastConnection);syncResponsiveSystem();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
  document.addEventListener('visibilitychange',function(){if(!document.hidden){syncResponsiveSystem();refreshStorage();}});
  global.addEventListener('resize',function(){requestAnimationFrame(syncResponsiveSystem);},{passive:true});
  global.addEventListener('weig:route-state',function(){syncDetailTitleContract();});
  global.addEventListener('weig:library-state',function(){requestAnimationFrame(syncResponsiveSystem);});
  global.addEventListener('weig:transfer',function(){requestAnimationFrame(mountStatusTelemetry);});
  global.addEventListener('weig:status-state',function(event){paintConnection(event.detail&&event.detail.connection||'unknown');});
  global.addEventListener('weig:maindata',function(event){var state=event.detail&&event.detail.serverState||{},free=state.free_space_on_disk;if(free!=null&&Number.isFinite(Number(free)))paintStorage(free);else refreshStorage();if(connectionDialog&&connectionDialog.open)requestAnimationFrame(openConnectionDialog);});
  global.addEventListener('weig:languagechange',function(){localizeStorage(document.getElementById('status-free-space'));paintConnection(lastConnection);syncPagerCopy();mountStatusTelemetry();if(connectionDialog&&connectionDialog.open)openConnectionDialog();});

  W.MobileAdaptive={formatFreeSpace:formatFreeSpace,mobileRowHeight:mobileRowHeight,fitMobileMeta:fitMobileMeta,refreshStorage:refreshStorage,paintConnection:paintConnection,openConnectionDialog:openConnectionDialog,installPageContracts:installPageContracts,primaryScrollOwners:primaryScrollOwners,mountSelectionToolbar:mountSelectionToolbar,mountStatusTelemetry:mountStatusTelemetry,syncPagerCopy:syncPagerCopy,installDetailTitleInteraction:installDetailTitleInteraction};
})(window);
