(function(global){
  'use strict';
  var W=global.WeiG,C=W&&W.Components;
  if(!W||!C)return;
  function tr(key,fallback,vars){return W.RuntimeI18n&&W.RuntimeI18n.t?W.RuntimeI18n.t(key,vars):fallback;}
  function localized(en,cn){return W.I18n&&W.I18n.getLocale&&W.I18n.getLocale()==='zh-CN'?cn:en;}
  function isMobile(){return !!(global.matchMedia&&global.matchMedia('(max-width: 820px)').matches);}

  var pageContracts=[['list-view','torrent-list','data'],['detail-view','detail-content','scroll'],['settings-view','settings-content','scroll'],['search-view','search-results','tool'],['rss-view','rss-content','tool'],['logs-view','logs-content','tool']];
  function installPageContracts(){pageContracts.forEach(function(spec){var view=document.getElementById(spec[0]),owner=document.getElementById(spec[1]);if(!view||!owner)return;view.dataset.pageLayout=spec[2];owner.dataset.primaryScroll='1';});}
  function primaryScrollOwners(view){return view?Array.from(view.querySelectorAll('[data-primary-scroll="1"]')):[];}

  function mobileRowHeight(){var density=document.documentElement.dataset.density||'standard';if(global.innerHeight<=680)return 82;if(density==='compact')return 76;if(density==='comfortable')return 92;return 84;}
  function desktopRowHeight(){var density=document.documentElement.dataset.density||'standard';return density==='compact'?48:density==='comfortable'?64:56;}
  function syncTorrentRowHeight(){var list=document.getElementById('torrent-list'),instance=list&&list.__weiggTorrentVirtual;if(!instance||!instance.setRowHeight)return;var next=isMobile()?mobileRowHeight():desktopRowHeight();if(instance.rowHeight!==next)instance.setRowHeight(next);}

  function compactMetricText(value){var s=String(value==null?'':value);s=s.replace(/^([↓↑])\s+/, '$1');s=s.replace(/(\d+\.\d*?[1-9])0+(?=\s*(?:[KMGTPE]?i?B|B)(?:\/s)?\b)/g,'$1');s=s.replace(/(\d+)\.0+(?=\s*(?:[KMGTPE]?i?B|B)(?:\/s)?\b)/g,'$1');s=s.replace(/(\d+(?:\.\d+)?)\s+(?=(?:[KMGTPE]?i?B|B)(?:\/s)?\b)/g,'$1');s=s.replace(/(\d+[dhms])\s+(?=\d)/g,'$1');return s;}
  function compactMetaCells(cells){cells.forEach(function(cell){if(cell.dataset.mobileFullText===undefined)cell.dataset.mobileFullText=cell.textContent||'';var full=cell.dataset.mobileFullText,compact=compactMetricText(full);cell.textContent=compact;cell.title=full;});}
  function fitMobileMeta(meta){if(!meta||!isMobile())return;var cells=Array.from(meta.querySelectorAll('.mobile-metric,.cell'));if(!cells.length)return;compactMetaCells(cells);meta.classList.remove('is-tight','is-ultra-tight');meta.style.removeProperty('--mobile-meta-gap');meta.style.removeProperty('--mobile-meta-font');if(meta.scrollWidth<=meta.clientWidth+1)return;meta.classList.add('is-tight');meta.style.setProperty('--mobile-meta-gap','4px');meta.style.setProperty('--mobile-meta-font','10px');if(meta.scrollWidth<=meta.clientWidth+1)return;meta.classList.add('is-ultra-tight');meta.style.setProperty('--mobile-meta-gap','3px');meta.style.setProperty('--mobile-meta-font','9px');}
  function fitVisibleMobileMeta(root){Array.from((root||document).querySelectorAll('.mobile-card-meta')).forEach(fitMobileMeta);}

  function mountSelectionToolbar(){var toolbar=document.getElementById('torrent-selection-toolbar'),desktopSlot=document.getElementById('torrent-action-slot'),mobileSlot=document.getElementById('mobile-pager-actions-slot');if(!toolbar||!desktopSlot||!mobileSlot)return;if(isMobile()){if(toolbar.parentElement!==mobileSlot)mobileSlot.appendChild(toolbar);}else if(toolbar.parentElement!==desktopSlot)desktopSlot.appendChild(toolbar);}

  var lastFree=null,lastConnection='unknown',connectionDialog=null;
  function trimFixed(value,decimals){return Number(value).toFixed(decimals).replace(/\.0+$/,'').replace(/(\.\d*?[1-9])0+$/,'$1');}
  function formatFreeSpace(bytes){var n=Number(bytes);if(!Number.isFinite(n)||n<0)return'—';if(n<1024)return Math.round(n)+' B';var units=[['TiB',1099511627776],['GiB',1073741824],['MiB',1048576],['KiB',1024]];for(var i=0;i<units.length;i++)if(n>=units[i][1]){var value=n/units[i][1],decimals=value<10?2:(value<100?1:0);return trimFixed(value,decimals)+' '+units[i][0];}return Math.round(n)+' B';}
  function localizeStorage(node){if(!node)return;var label=node.querySelector('.status-storage__label'),value=node.querySelector('strong'),shown=value?value.textContent:'—';if(label)label.textContent=tr('v036.storage.free','Free');var bytes=(lastFree!=null&&Number.isFinite(Number(lastFree)))?Math.round(Number(lastFree)).toLocaleString():'—';node.title=tr('v036.storage.tooltip','Free space on the filesystem containing qBittorrent’s default save path: {value} ({bytes} bytes)',{value:shown,bytes:bytes});}
  function installStorageStatus(){var bar=document.querySelector('.statusbar');if(!bar)return null;var node=document.getElementById('status-free-space');if(!node){node=document.createElement('span');node.id='status-free-space';node.className='status-storage';node.dataset.tone='neutral';var icon=document.createElement('span');icon.className='status-storage__icon';icon.textContent='◫';icon.setAttribute('aria-hidden','true');var label=document.createElement('span');label.className='status-storage__label';var value=document.createElement('strong');value.textContent='—';node.append(icon,label,value);var connection=document.getElementById('status-connection'),message=document.getElementById('status-message');bar.insertBefore(node,connection||message||null);}localizeStorage(node);return node;}
  function paintStorage(bytes){var node=installStorageStatus();if(!node)return;lastFree=Number(bytes);node.hidden=false;var strong=node.querySelector('strong');var next=formatFreeSpace(lastFree);if(strong&&strong.textContent!==next)strong.textContent=next;localizeStorage(node);}
  function refreshStorage(){var snap=W.TransferRuntime&&W.TransferRuntime.snapshot?W.TransferRuntime.snapshot():{};if(snap.freeSpace!=null&&Number.isFinite(Number(snap.freeSpace)))paintStorage(snap.freeSpace);else{var node=installStorageStatus();if(node&&lastFree==null)node.hidden=true;}}
  function normalizeConnection(status){var value=String(status||'unknown').toLowerCase();return value==='connected'||value==='firewalled'||value==='disconnected'||value==='error'?value:'unknown';}
  function connectionLabel(status){if(status==='connected')return localized('Connected','已连接');if(status==='firewalled')return localized('Network limited','网络受限');if(status==='disconnected')return localized('Disconnected','未连接');if(status==='error')return localized('Unavailable','异常');return'—';}
  function connectionReason(status){if(status==='connected')return localized('qBittorrent currently reports a normal network connection.','qBittorrent 当前报告网络连接正常。');if(status==='firewalled')return localized('qBittorrent reports limited connectivity; incoming peer connections may be unreachable.','qBittorrent 报告连接受限，入站 Peer 连接可能不可达。');if(status==='disconnected')return localized('qBittorrent currently reports no active network connection.','qBittorrent 当前未建立有效网络连接。');if(status==='error')return localized('WeiG WebUI cannot obtain a reliable connection status right now.','WeiG WebUI 暂时无法取得可靠的连接状态。');return localized('Connection state has not been detected yet.','尚未检测到连接状态。');}
  function connectionSteps(status){if(status==='firewalled')return localized(['Check the qBittorrent listening port.','Check router UPnP / NAT-PMP or manual port forwarding.','Check host, Docker and VPS firewall rules.','If using a VPN, confirm that it supports inbound port forwarding.','Check whether the WAN connection is behind CGNAT.'],['检查 qBittorrent 监听端口。','检查路由器 UPnP / NAT-PMP 或手动端口转发。','检查系统、Docker 与 VPS 防火墙规则。','如使用 VPN，确认 VPN 支持入站端口转发。','检查 WAN 是否处于 CGNAT。']);if(status==='disconnected')return localized(['Check the host network connection.','Check VPN / proxy network interfaces.','Check Docker networking and qBittorrent network-interface settings.'],['检查主机网络连接。','检查 VPN / 代理网络接口。','检查 Docker 网络与 qBittorrent 网络接口设置。']);if(status==='error')return localized(['Refresh the page once.','Check qBittorrent WebAPI availability.','Check browser Network requests and qBittorrent / Docker logs.'],['刷新一次页面。','检查 qBittorrent WebAPI 是否可用。','检查浏览器 Network 请求以及 qBittorrent / Docker 日志。']);return localized(['If transfer is still abnormal, check the listening port and firewall.','Check Tracker, DHT and PeX status for the affected torrent.','Check VPN / proxy routing if peers cannot connect.'],['如传输仍异常，检查监听端口与防火墙。','检查相关 Torrent 的 Tracker、DHT 与 PeX 状态。','如 Peer 无法连接，检查 VPN / 代理路由。']);}
  function ensureConnectionDialog(){if(connectionDialog&&connectionDialog.isConnected)return connectionDialog;var d=document.createElement('dialog');d.id='connection-dialog';d.className='dialog surface surface--modal connection-dialog';d.innerHTML='<div class="dialog__head"><div><div class="eyebrow">CONNECTION</div><h2 class="connection-dialog__title"></h2></div><button type="button" class="icon-btn connection-dialog__close">×</button></div><div class="dialog__body connection-dialog__body"><div class="connection-dialog__summary"><span class="connection-dialog__dot" aria-hidden="true"></span><strong class="connection-dialog__state"></strong></div><p class="connection-dialog__reason"></p><div class="connection-dialog__environment"></div><div><h3 class="connection-dialog__help-title"></h3><ol class="connection-dialog__steps"></ol></div></div><div class="dialog__actions"><button type="button" class="btn btn--primary connection-dialog__done"></button></div>';d.querySelector('.connection-dialog__close').onclick=d.querySelector('.connection-dialog__done').onclick=function(){d.close();};document.body.appendChild(d);connectionDialog=d;return d;}
  function networkSnapshotText(){var snap=W.TransferRuntime&&W.TransferRuntime.snapshot?W.TransferRuntime.snapshot():{};return'DHT '+(snap.dhtNodes==null?'—':snap.dhtNodes)+' · Peers '+(snap.peers==null?'—':snap.peers);}
  function openConnectionDialog(){var d=ensureConnectionDialog(),status=lastConnection,label=connectionLabel(status),client=W.AppState&&W.AppState.client;d.dataset.connection=status;d.querySelector('.connection-dialog__title').textContent=localized('Network connection status','网络连接状态');d.querySelector('.connection-dialog__state').textContent=label;d.querySelector('.connection-dialog__reason').textContent=connectionReason(status);var env=d.querySelector('.connection-dialog__environment');env.textContent='';[(localized('qBittorrent: ','qBittorrent：')+(client&&client.qbVersion||'—')),(localized('WebAPI: ','WebAPI：')+(client&&client.webApiVersion||'—')),(localized('Network: ','网络：')+networkSnapshotText())].forEach(function(line){var row=document.createElement('div');row.className='connection-dialog__row';row.textContent=line;env.appendChild(row);});d.querySelector('.connection-dialog__help-title').textContent=localized('Troubleshooting','排查建议');var steps=d.querySelector('.connection-dialog__steps');steps.textContent='';connectionSteps(status).forEach(function(step){var li=document.createElement('li');li.textContent=step;steps.appendChild(li);});d.querySelector('.connection-dialog__done').textContent=localized('Close','关闭');if(!d.open)d.showModal();return d;}
  function installConnectionTrigger(){var footer=document.getElementById('status-connection');if(!footer||footer.dataset.connectionTrigger==='1')return footer;footer.dataset.connectionTrigger='1';footer.setAttribute('role','button');footer.tabIndex=0;footer.addEventListener('click',openConnectionDialog);footer.addEventListener('keydown',function(event){if(event.key==='Enter'||event.key===' '){event.preventDefault();openConnectionDialog();}});return footer;}
  function paintConnection(status){lastConnection=normalizeConnection(status);var label=connectionLabel(lastConnection),footer=installConnectionTrigger(),footerLabel=document.getElementById('status-connection-label');if(footer){footer.dataset.connection=lastConnection;footer.dataset.tooltip=connectionReason(lastConnection);footer.setAttribute('aria-label',label+' — '+connectionReason(lastConnection));}if(footerLabel&&footerLabel.textContent!==label)footerLabel.textContent=label;}

  function syncResponsiveSystem(){installPageContracts();mountSelectionToolbar();syncTorrentRowHeight();fitVisibleMobileMeta();}
  function init(){syncResponsiveSystem();installStorageStatus();refreshStorage();installConnectionTrigger();paintConnection(lastConnection);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
  document.addEventListener('visibilitychange',function(){if(!document.hidden){syncResponsiveSystem();refreshStorage();}});
  global.addEventListener('resize',function(){requestAnimationFrame(syncResponsiveSystem);},{passive:true});
  global.addEventListener('weigg:library-state',function(){requestAnimationFrame(syncResponsiveSystem);});
  global.addEventListener('weigg:status-state',function(event){paintConnection(event.detail&&event.detail.connection||'unknown');});
  global.addEventListener('weigg:maindata',function(event){var state=event.detail&&event.detail.serverState||{},free=state.free_space_on_disk;if(free!=null&&Number.isFinite(Number(free)))paintStorage(free);else refreshStorage();if(connectionDialog&&connectionDialog.open)requestAnimationFrame(openConnectionDialog);});
  global.addEventListener('weigg:languagechange',function(){localizeStorage(document.getElementById('status-free-space'));paintConnection(lastConnection);if(connectionDialog&&connectionDialog.open)openConnectionDialog();});

  W.MobileAdaptive={formatFreeSpace:formatFreeSpace,mobileRowHeight:mobileRowHeight,fitMobileMeta:fitMobileMeta,refreshStorage:refreshStorage,paintConnection:paintConnection,openConnectionDialog:openConnectionDialog,installPageContracts:installPageContracts,primaryScrollOwners:primaryScrollOwners,mountSelectionToolbar:mountSelectionToolbar};
})(window);
