(function(global){
  'use strict';
  var W=global.WeiG;
  if(!W||!W.QBClient||W.RSSRules)return;
  var R=W.CapabilityRegistry,own=Object.prototype.hasOwnProperty;
  function zh(){return !!(W.I18n&&W.I18n.getLocale&&W.I18n.getLocale()==='zh-CN');}
  function text(en,cn){return zh()?cn:en;}
  function qb(key,en,cn){var fallback=text(en,cn);return W.I18n&&W.I18n.qbText?W.I18n.qbText(key,fallback):fallback;}
  function hasAction(name){return !!(R&&typeof R.hasAction==='function'&&R.hasAction(name));}
  function canWrite(name){return !!(R&&typeof R.supportsWriteAction==='function'&&R.supportsWriteAction(name));}
  var state={rules:{},selected:'',draft:null,matching:{},busy:false,root:null,list:null,editor:null,status:null,matchingRoot:null};
  function clone(value){try{return structuredClone(value);}catch(_e){return JSON.parse(JSON.stringify(value));}}
  function button(copy,kind){var el=document.createElement('button');el.type='button';el.className='btn '+(kind||'btn--ghost');el.textContent=copy;return el;}
  function input(type,value){var el=document.createElement('input');el.type=type||'text';el.className='field-input';if(type==='checkbox')el.checked=!!value;else el.value=value==null?'':String(value);return el;}
  function select(value,options){var el=document.createElement('select');el.className='field-input';(options||[]).forEach(function(item){var op=document.createElement('option');op.value=String(item.value);op.textContent=item.label;el.appendChild(op);});el.value=value==null?'':String(value);return el;}
  function field(labelText,control){var label=document.createElement('label');label.className=control.type==='checkbox'?'check-row':'field';var span=document.createElement('span');span.textContent=labelText;label.appendChild(control);if(control.type==='checkbox')label.appendChild(span);else label.insertBefore(span,control);return label;}
  function ownKey(obj,key){return !!obj&&own.call(obj,key);}
  function pathIn(rule,key){var tp=rule&&rule.torrentParams&&typeof rule.torrentParams==='object'?rule.torrentParams:null;var map={
    category:ownKey(rule,'assignedCategory')?['rule','assignedCategory']:ownKey(tp,'category')?['tp','category']:null,
    tags:ownKey(tp,'tags')?['tp','tags']:null,
    savePath:ownKey(rule,'savePath')?['rule','savePath']:ownKey(tp,'save_path')?['tp','save_path']:null,
    layout:ownKey(rule,'torrentContentLayout')?['rule','torrentContentLayout']:ownKey(tp,'content_layout')?['tp','content_layout']:null,
    stopped:ownKey(tp,'stopped')?['tp','stopped']:ownKey(rule,'addStopped')?['rule','addStopped']:ownKey(rule,'addPaused')?['rule','addPaused']:ownKey(tp,'paused')?['tp','paused']:null,
    subfolder:ownKey(rule,'createSubfolder')?['rule','createSubfolder']:null
  };return map[key]||null;}
  function readPath(rule,path){if(!path)return undefined;var obj=path[0]==='tp'?rule.torrentParams:rule;return obj?obj[path[1]]:undefined;}
  function writePath(rule,path,value){if(!path)return;var obj=path[0]==='tp'?(rule.torrentParams||(rule.torrentParams={})):rule;obj[path[1]]=value;}
  function triState(value){return value===null||value===undefined?'default':value?'always':'never';}
  function triValue(value){return value==='default'?null:value==='always';}
  function layoutState(value){return value===null||value===undefined||value===''?'Default':String(value);}
  function setStatus(message,error){if(!state.status)return;state.status.textContent=message||'';state.status.classList.toggle('danger-text',!!error);}
  function emptyDraft(){return{enabled:true,mustContain:'',mustNotContain:'',useRegex:false,episodeFilter:'',affectedFeeds:[],ignoreDays:0,smartFilter:false};}
  function currentClient(){return W.AppState&&W.AppState.client;}
  async function selectRule(name){state.selected=name;state.draft=clone(state.rules[name]||{});state.matching={};render();await loadMatchingArticles();}
  function renderList(){if(!state.list)return;state.list.textContent='';var names=Object.keys(state.rules||{}).sort(function(a,b){return a.localeCompare(b);});if(!names.length){var empty=document.createElement('p');empty.className='text-description';empty.textContent=text('No download rules.','暂无下载规则。');state.list.appendChild(empty);return;}names.forEach(function(name){var row=button(name,'btn--ghost');row.classList.toggle('is-active',name===state.selected);row.addEventListener('click',function(){selectRule(name);});state.list.appendChild(row);});}
  function renderMatchingArticles(){var root=state.matchingRoot;if(!root)return;root.textContent='';if(!state.selected||!hasAction('rsscontroller.h:matchingArticlesAction'))return;var title=document.createElement('h3');title.textContent=qb('rss.rule.matchingArticles','Matching RSS Articles','匹配的 RSS 文章');root.appendChild(title);var feeds=Object.keys(state.matching||{});if(!feeds.length){var empty=document.createElement('p');empty.className='text-description';empty.textContent=text('No matching articles.','没有匹配的文章。');root.appendChild(empty);return;}feeds.forEach(function(feed){var block=document.createElement('div');block.className='rss-rule-matches';var name=document.createElement('strong');name.textContent=feed;block.appendChild(name);var list=document.createElement('ul');(Array.isArray(state.matching[feed])?state.matching[feed]:[]).forEach(function(article){var li=document.createElement('li');li.textContent=String(article);list.appendChild(li);});block.appendChild(list);root.appendChild(block);});}
  async function loadMatchingArticles(){var client=currentClient();if(!client||!state.selected||!hasAction('rsscontroller.h:matchingArticlesAction')){state.matching={};renderMatchingArticles();return;}try{var data=await client.rssMatchingArticles(state.selected);state.matching=data&&typeof data==='object'&&!Array.isArray(data)?data:{};renderMatchingArticles();}catch(error){state.matching={};renderMatchingArticles();setStatus(text('Failed to load matching articles: ','读取匹配文章失败：')+(error&&error.message||error),true);}}
  function appendControl(form,name,labelText,control){control.dataset.rssRuleField=name;form.appendChild(field(labelText,control));return control;}
  function renderEditor(){var root=state.editor;if(!root)return;root.textContent='';state.matchingRoot=null;if(!state.draft){var p=document.createElement('p');p.className='text-description';p.textContent=text('Select a rule or create a new one.','选择一个规则或新建规则。');root.appendChild(p);return;}var rule=state.draft,form=document.createElement('div');form.className='settings-grid';
    appendControl(form,'name',text('Rule name','规则名称'),input('text',state.selected||text('New rule','新规则')));
    appendControl(form,'enabled',qb('rss.rule.enabled','Enabled','启用'),input('checkbox',rule.enabled!==false));
    appendControl(form,'mustContain',qb('rss.rule.mustContain','Must Contain:','必须包含：'),input('text',rule.mustContain||''));
    appendControl(form,'mustNotContain',qb('rss.rule.mustNotContain','Must Not Contain:','必须不含：'),input('text',rule.mustNotContain||''));
    appendControl(form,'useRegex',qb('rss.rule.useRegex','Use Regular Expressions','使用正则表达式'),input('checkbox',!!rule.useRegex));
    if(ownKey(rule,'episodeFilter'))appendControl(form,'episodeFilter',qb('rss.rule.episodeFilter','Episode Filter:','剧集过滤器：'),input('text',rule.episodeFilter||''));
    if(ownKey(rule,'smartFilter'))appendControl(form,'smartFilter',qb('rss.rule.smartFilter','Use Smart Episode Filter','使用智能剧集过滤器'),input('checkbox',!!rule.smartFilter));
    if(ownKey(rule,'ignoreDays')){var days=input('number',Number(rule.ignoreDays)||0);days.min='0';appendControl(form,'ignoreDays',qb('rss.rule.ignoreDays','Ignore Subsequent Matches for (0 to Disable)','忽略后续匹配（0 表示禁用）'),days);}
    if(Array.isArray(rule.affectedFeeds)){var feeds=document.createElement('textarea');feeds.className='field-input';feeds.rows=4;feeds.value=rule.affectedFeeds.join('\n');appendControl(form,'affectedFeeds',qb('rss.rule.affectedFeeds','Apply Rule to Feeds:','应用规则到订阅源：'),feeds);}
    var categoryPath=pathIn(rule,'category');if(categoryPath)appendControl(form,'category',qb('rss.rule.category','Assign Category:','分配分类：'),input('text',readPath(rule,categoryPath)||''));
    var tagsPath=pathIn(rule,'tags');if(tagsPath)appendControl(form,'tags',qb('rss.rule.tags','Add Tags:','添加标签：'),input('text',Array.isArray(readPath(rule,tagsPath))?readPath(rule,tagsPath).join(', '):readPath(rule,tagsPath)||''));
    var savePath=pathIn(rule,'savePath');if(savePath)appendControl(form,'savePath',qb('rss.rule.savePath','Save to:','保存到：'),input('text',readPath(rule,savePath)||''));
    var stoppedPath=pathIn(rule,'stopped');if(stoppedPath)appendControl(form,'stopped',qb('rss.rule.stopped',ownKey(rule,'addPaused')?'Add Paused:':'Add Stopped:','添加时停止：'),select(triState(readPath(rule,stoppedPath)),[{value:'default',label:qb('rss.rule.global','Use global settings','使用全局设置')},{value:'always',label:qb('rss.rule.always','Always','总是')},{value:'never',label:qb('rss.rule.never','Never','从不')}]));
    var layoutPath=pathIn(rule,'layout');if(layoutPath)appendControl(form,'layout',qb('rss.rule.contentLayout','Torrent content layout:','Torrent 内容布局：'),select(layoutState(readPath(rule,layoutPath)),[{value:'Default',label:qb('rss.rule.global','Use global settings','使用全局设置')},{value:'Original',label:qb('rss.rule.layout.original','Original','原始')},{value:'Subfolder',label:qb('rss.rule.layout.subfolder','Create subfolder','创建子文件夹')},{value:'NoSubfolder',label:qb('rss.rule.layout.noSubfolder',"Don't create subfolder",'不创建子文件夹')}]));
    var subfolderPath=pathIn(rule,'subfolder');if(subfolderPath&&!layoutPath)appendControl(form,'subfolder',qb('rss.rule.subfolder','Create Subfolder:','创建子文件夹：'),select(triState(readPath(rule,subfolderPath)),[{value:'default',label:qb('rss.rule.global','Use global settings','使用全局设置')},{value:'always',label:qb('rss.rule.always','Always','总是')},{value:'never',label:qb('rss.rule.never','Never','从不')}]));
    root.appendChild(form);
    var actions=document.createElement('div');actions.className='dialog__actions';var saveBtn=button(qb('rss.rule.save','Save','保存'),'btn--primary');saveBtn.disabled=!canWrite('rsscontroller.h:setRuleAction');saveBtn.addEventListener('click',saveRule);actions.appendChild(saveBtn);if(state.selected){var del=button(text('Delete','删除'),'btn--danger-ghost');del.disabled=!canWrite('rsscontroller.h:removeRuleAction');del.addEventListener('click',removeRule);actions.appendChild(del);}root.appendChild(actions);
    if(ownKey(rule,'lastMatch')&&rule.lastMatch){var last=document.createElement('p');last.className='text-description';last.textContent=qb('rss.rule.lastMatch','Last Match: ','上次匹配：')+String(rule.lastMatch);root.appendChild(last);}
    state.matchingRoot=document.createElement('section');state.matchingRoot.className='rss-matching-articles';root.appendChild(state.matchingRoot);renderMatchingArticles();}
  function collect(){var root=state.editor,rule=clone(state.draft||emptyDraft()),get=function(name){return root.querySelector('[data-rss-rule-field="'+name+'"]');};var name=String(get('name')&&get('name').value||'').trim();rule.enabled=!!(get('enabled')&&get('enabled').checked);rule.mustContain=String(get('mustContain')&&get('mustContain').value||'');rule.mustNotContain=String(get('mustNotContain')&&get('mustNotContain').value||'');rule.useRegex=!!(get('useRegex')&&get('useRegex').checked);if(ownKey(rule,'episodeFilter')&&get('episodeFilter'))rule.episodeFilter=String(get('episodeFilter').value||'');if(ownKey(rule,'smartFilter')&&get('smartFilter'))rule.smartFilter=!!get('smartFilter').checked;if(ownKey(rule,'ignoreDays')&&get('ignoreDays'))rule.ignoreDays=Math.max(0,Number(get('ignoreDays').value)||0);if(Array.isArray(rule.affectedFeeds)&&get('affectedFeeds'))rule.affectedFeeds=String(get('affectedFeeds').value||'').split(/\r?\n/).map(function(x){return x.trim();}).filter(Boolean);
    var categoryPath=pathIn(rule,'category');if(categoryPath&&get('category'))writePath(rule,categoryPath,String(get('category').value||''));var tagsPath=pathIn(rule,'tags');if(tagsPath&&get('tags')){var raw=String(get('tags').value||'');writePath(rule,tagsPath,Array.isArray(readPath(rule,tagsPath))?raw.split(',').map(function(x){return x.trim();}).filter(Boolean):raw);}var savePath=pathIn(rule,'savePath');if(savePath&&get('savePath'))writePath(rule,savePath,String(get('savePath').value||''));var stoppedPath=pathIn(rule,'stopped');if(stoppedPath&&get('stopped'))writePath(rule,stoppedPath,triValue(get('stopped').value));var layoutPath=pathIn(rule,'layout');if(layoutPath&&get('layout'))writePath(rule,layoutPath,get('layout').value==='Default'?null:String(get('layout').value));var subfolderPath=pathIn(rule,'subfolder');if(subfolderPath&&get('subfolder'))writePath(rule,subfolderPath,triValue(get('subfolder').value));return{name:name,rule:rule};}
  async function saveRule(){if(state.busy)return;var client=currentClient(),value=collect();if(!client||!value.name)return setStatus(text('Rule name is required.','必须填写规则名称。'),true);if(!canWrite('rsscontroller.h:setRuleAction'))return setStatus(text('This RSS rule write is not source-proven for the current qBittorrent release.','当前 qBittorrent 版本没有源码证明支持 RSS 规则写入。'),true);state.busy=true;setStatus(text('Saving rule…','正在保存规则…'));try{if(state.selected&&state.selected!==value.name){if(!canWrite('rsscontroller.h:renameRuleAction'))throw new Error(text('This qBittorrent release cannot safely rename RSS rules.','当前 qBittorrent 版本无法安全重命名 RSS 规则。'));await client.rssRenameRule(state.selected,value.name);}await client.rssSetRule(value.name,value.rule);state.selected=value.name;await loadRules();await loadMatchingArticles();setStatus(text('RSS rule saved.','RSS 规则已保存。'));}catch(error){setStatus(text('Failed to save RSS rule: ','保存 RSS 规则失败：')+(error&&error.message||error),true);}finally{state.busy=false;}}
  async function removeRule(){if(state.busy||!state.selected)return;var client=currentClient();if(!client||!canWrite('rsscontroller.h:removeRuleAction'))return;state.busy=true;setStatus(text('Removing rule…','正在删除规则…'));try{await client.rssRemoveRule(state.selected);state.selected='';state.draft=null;state.matching={};await loadRules();setStatus(text('RSS rule removed.','RSS 规则已删除。'));}catch(error){setStatus(text('Failed to remove RSS rule: ','删除 RSS 规则失败：')+(error&&error.message||error),true);}finally{state.busy=false;}}
  function render(){renderList();renderEditor();}
  async function loadRules(){var client=currentClient();if(!state.root||!client||!hasAction('rsscontroller.h:rulesAction'))return;try{var rules=await client.rssRules();state.rules=rules&&typeof rules==='object'&&!Array.isArray(rules)?rules:{};if(state.selected&&ownKey(state.rules,state.selected))state.draft=clone(state.rules[state.selected]);else if(state.selected){state.selected='';state.draft=null;state.matching={};}render();}catch(error){setStatus(text('Failed to load RSS rules: ','读取 RSS 规则失败：')+(error&&error.message||error),true);}}
  function install(){var view=document.getElementById('rss-view');if(!view||document.getElementById('rss-rules-panel'))return;var panel=document.createElement('div');panel.id='rss-rules-panel';panel.className='tool-page surface surface--panel';var head=document.createElement('div');head.className='workspace__header';var title=document.createElement('h2');title.textContent=qb('rss.downloader.title','RSS Downloader','RSS 下载器');head.appendChild(title);var actions=document.createElement('div');actions.className='inline-form';var add=button(text('New rule','新建规则'),'btn--primary');add.disabled=!canWrite('rsscontroller.h:setRuleAction');add.addEventListener('click',function(){state.selected='';state.draft=emptyDraft();state.matching={};render();});var refresh=button(text('Refresh rules','刷新规则'),'btn--ghost');refresh.addEventListener('click',loadRules);actions.appendChild(add);actions.appendChild(refresh);head.appendChild(actions);panel.appendChild(head);var layout=document.createElement('div');layout.className='settings-layout';state.list=document.createElement('nav');state.list.id='rss-rules-list';state.list.className='settings-tabs';state.editor=document.createElement('div');state.editor.id='rss-rule-editor';state.editor.className='settings-content';layout.appendChild(state.list);layout.appendChild(state.editor);panel.appendChild(layout);state.status=document.createElement('p');state.status.className='text-description';panel.appendChild(state.status);var existing=view.querySelector('.tool-page');if(existing&&existing.parentNode)existing.parentNode.insertBefore(panel,existing.nextSibling);else view.appendChild(panel);state.root=panel;if(!hasAction('rsscontroller.h:rulesAction')){panel.hidden=true;return;}loadRules();}
  function refresh(){if(!state.root)install();else if(location.hash.replace(/^#\/?/,'').split('/')[0]==='rss')loadRules();}
  W.RSSRules={install:install,refresh:refresh,loadRules:loadRules,loadMatchingArticles:loadMatchingArticles,state:function(){return{selected:state.selected,rules:Object.keys(state.rules||{}),matching:clone(state.matching||{})};}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
  global.addEventListener('hashchange',refresh);global.addEventListener('weigg:languagechange',function(){if(state.root){state.root.remove();state.root=null;state.list=null;state.editor=null;state.status=null;state.matchingRoot=null;install();}});
})(window);
