(function(global){
  'use strict';
  var W=global.WeiG;
  if(!W||!W.QBClient||W.RSSRules)return;
  var R=W.CapabilityRegistry,own=Object.prototype.hasOwnProperty;
  function zh(){return !!(W.I18n&&W.I18n.getLocale&&W.I18n.getLocale()==='zh-CN');}
  function text(en,cn){return zh()?cn:en;}
  function qb(key,en,cn){var fallback=text(en,cn);return W.I18n&&W.I18n.qbText?W.I18n.qbText(key,fallback):fallback;}
  function hasAction(name){return !!(R&&typeof R.hasAction==='function'&&R.hasAction(name));}
  function canWrite(name){return !!(R&&typeof R.supportsWriteAction==='function'&&R.supportsWriteAction(name));}
  var state={rules:{},selected:'',draft:null,matching:{},busy:false,root:null,list:null,editor:null,status:null,matchingRoot:null};
  function clone(value){try{return structuredClone(value);}catch(_e){return JSON.parse(JSON.stringify(value));}}
  function button(copy,kind){var el=document.createElement('button');el.type='button';el.className='btn '+(kind||'btn--ghost');el.textContent=copy;return el;}
  function input(type,value){var el=document.createElement('input');el.type=type||'text';el.className='field-input';if(type==='checkbox')el.checked=!!value;else el.value=value==null?'':String(value);return el;}
  function field(labelText,control){var label=document.createElement('label');label.className=control.type==='checkbox'?'check-row':'field';var span=document.createElement('span');span.textContent=labelText;label.appendChild(control);if(control.type==='checkbox')label.appendChild(span);else label.insertBefore(span,control);return label;}
  function ownKey(obj,key){return !!obj&&own.call(obj,key);}
  function shape(rule){var tp=rule&&rule.torrentParams&&typeof rule.torrentParams==='object'?rule.torrentParams:null;return{
    category:ownKey(rule,'assignedCategory')?['rule','assignedCategory']:ownKey(tp,'category')?['tp','category']:null,
    tags:ownKey(tp,'tags')?['tp','tags']:null,
    savePath:ownKey(rule,'savePath')?['rule','savePath']:ownKey(tp,'save_path')?['tp','save_path']:null,
    layout:ownKey(rule,'torrentContentLayout')?['rule','torrentContentLayout']:ownKey(tp,'content_layout')?['tp','content_layout']:null,
    paused:ownKey(rule,'addStopped')?['rule','addStopped']:ownKey(rule,'addPaused')?['rule','addPaused']:ownKey(tp,'paused')?['tp','paused']:null
  };}
  function readPath(rule,path){if(!path)return undefined;var obj=path[0]==='tp'?rule.torrentParams:rule;return obj?obj[path[1]]:undefined;}
  function writePath(rule,path,value){if(!path)return;var obj=path[0]==='tp'?(rule.torrentParams||(rule.torrentParams={})):rule;obj[path[1]]=value;}
  function setStatus(message,error){if(!state.status)return;state.status.textContent=message||'';state.status.classList.toggle('danger-text',!!error);}
  function emptyDraft(){return{enabled:true,mustContain:'',mustNotContain:'',useRegex:false,episodeFilter:'',affectedFeeds:[],ignoreDays:0,smartFilter:false};}
  function currentClient(){return W.AppState&&W.AppState.client;}
  async function selectRule(name){state.selected=name;state.draft=clone(state.rules[name]||{});state.matching={};render();await loadMatchingArticles();}
  function renderList(){if(!state.list)return;state.list.textContent='';var names=Object.keys(state.rules||{}).sort(function(a,b){return a.localeCompare(b);});if(!names.length){var empty=document.createElement('p');empty.className='text-description';empty.textContent=text('No download rules.','暂无下载规则。');state.list.appendChild(empty);return;}names.forEach(function(name){var row=button(name,'btn--ghost');row.classList.toggle('is-active',name===state.selected);row.addEventListener('click',function(){selectRule(name);});state.list.appendChild(row);});}
  function renderMatchingArticles(){var root=state.matchingRoot;if(!root)return;root.textContent='';if(!state.selected||!hasAction('rsscontroller.h:matchingArticlesAction'))return;var title=document.createElement('h3');title.textContent=qb('rss.rule.matchingArticles','Matching articles','匹配的文章');root.appendChild(title);var feeds=Object.keys(state.matching||{});if(!feeds.length){var empty=document.createElement('p');empty.className='text-description';empty.textContent=text('No matching articles.','没有匹配的文章。');root.appendChild(empty);return;}feeds.forEach(function(feed){var block=document.createElement('div');block.className='rss-rule-matches';var name=document.createElement('strong');name.textContent=feed;block.appendChild(name);var list=document.createElement('ul');(Array.isArray(state.matching[feed])?state.matching[feed]:[]).forEach(function(article){var li=document.createElement('li');li.textContent=String(article);list.appendChild(li);});block.appendChild(list);root.appendChild(block);});}
  async function loadMatchingArticles(){var client=currentClient();if(!client||!state.selected||!hasAction('rsscontroller.h:matchingArticlesAction')){state.matching={};renderMatchingArticles();return;}try{var data=await client.rssMatchingArticles(state.selected);state.matching=data&&typeof data==='object'&&!Array.isArray(data)?data:{};renderMatchingArticles();}catch(error){state.matching={};renderMatchingArticles();setStatus(text('Failed to load matching articles: ','读取匹配文章失败：')+(error&&error.message||error),true);}}
  function renderEditor(){var root=state.editor;if(!root)return;root.textContent='';state.matchingRoot=null;if(!state.draft){var p=document.createElement('p');p.className='text-description';p.textContent=text('Select a rule or create a new one.','选择一个规则或新建规则。');root.appendChild(p);return;}var rule=state.draft,s=shape(rule),form=document.createElement('div');form.className='settings-grid';
    var name=input('text',state.selected||text('New rule','新规则'));name.dataset.rssRuleField='name';form.appendChild(field(text('Rule name','规则名称'),name));
    var enabled=input('checkbox',rule.enabled!==false);enabled.dataset.rssRuleField='enabled';form.appendChild(field(qb('rss.rule.enabled','Enabled','启用'),enabled));
    var must=input('text',rule.mustContain||'');must.dataset.rssRuleField='mustContain';form.appendChild(field(qb('rss.rule.mustContain','Must contain','必须包含'),must));
    var mustNot=input('text',rule.mustNotContain||'');mustNot.dataset.rssRuleField='mustNotContain';form.appendChild(field(qb('rss.rule.mustNotContain','Must not contain','必须不含'),mustNot));
    var regex=input('checkbox',!!rule.useRegex);regex.dataset.rssRuleField='useRegex';form.appendChild(field(qb('rss.rule.useRegex','Use regular expressions','使用正则表达式'),regex));
    if(ownKey(rule,'episodeFilter')){var ep=input('text',rule.episodeFilter||'');ep.dataset.rssRuleField='episodeFilter';form.appendChild(field(qb('rss.rule.episodeFilter','Episode filter','剧集过滤器'),ep));}
    if(ownKey(rule,'ignoreDays')){var days=input('number',Number(rule.ignoreDays)||0);days.min='0';days.dataset.rssRuleField='ignoreDays';form.appendChild(field(qb('rss.rule.ignoreDays','Ignore matches for days','忽略匹配天数'),days));}
    if(Array.isArray(rule.affectedFeeds)){var feeds=document.createElement('textarea');feeds.className='field-input';feeds.rows=4;feeds.value=rule.affectedFeeds.join('\n');feeds.dataset.rssRuleField='affectedFeeds';form.appendChild(field(qb('rss.rule.affectedFeeds','Apply rule to feeds','应用到订阅源'),feeds));}
    if(s.category){var category=input('text',readPath(rule,s.category)||'');category.dataset.rssRuleField='category';form.appendChild(field(qb('rss.rule.category','Category','分类'),category));}
    if(s.tags){var tags=input('text',Array.isArray(readPath(rule,s.tags))?readPath(rule,s.tags).join(', '):readPath(rule,s.tags)||'');tags.dataset.rssRuleField='tags';form.appendChild(field(qb('rss.rule.tags','Tags','标签'),tags));}
    if(s.savePath){var save=input('text',readPath(rule,s.savePath)||'');save.dataset.rssRuleField='savePath';form.appendChild(field(qb('rss.rule.savePath','Save to','保存到'),save));}
    if(s.layout){var layout=input('text',readPath(rule,s.layout)||'');layout.dataset.rssRuleField='layout';form.appendChild(field(qb('rss.rule.contentLayout','Content layout','内容布局'),layout));}
    if(s.paused){var paused=input('checkbox',!!readPath(rule,s.paused));paused.dataset.rssRuleField='paused';form.appendChild(field(qb('rss.rule.startPaused','Start paused/stopped','以暂停/停止状态添加'),paused));}
    root.appendChild(form);
    var actions=document.createElement('div');actions.className='dialog__actions';var saveBtn=button(text('Save','保存'),'btn--primary');saveBtn.disabled=!canWrite('rsscontroller.h:setRuleAction');saveBtn.addEventListener('click',saveRule);actions.appendChild(saveBtn);if(state.selected){var del=button(text('Delete','删除'),'btn--danger-ghost');del.disabled=!canWrite('rsscontroller.h:removeRuleAction');del.addEventListener('click',removeRule);actions.appendChild(del);}root.appendChild(actions);
    if(ownKey(rule,'lastMatch')&&rule.lastMatch){var last=document.createElement('p');last.className='text-description';last.textContent=text('Last match: ','上次匹配：')+String(rule.lastMatch);root.appendChild(last);}
    state.matchingRoot=document.createElement('section');state.matchingRoot.className='rss-matching-articles';root.appendChild(state.matchingRoot);renderMatchingArticles();}
  function collect(){var root=state.editor,rule=clone(state.draft||emptyDraft()),s=shape(rule),get=function(name){return root.querySelector('[data-rss-rule-field="'+name+'"]');};var name=String(get('name')&&get('name').value||'').trim();rule.enabled=!!(get('enabled')&&get('enabled').checked);rule.mustContain=String(get('mustContain')&&get('mustContain').value||'');rule.mustNotContain=String(get('mustNotContain')&&get('mustNotContain').value||'');rule.useRegex=!!(get('useRegex')&&get('useRegex').checked);if(ownKey(rule,'episodeFilter')&&get('episodeFilter'))rule.episodeFilter=String(get('episodeFilter').value||'');if(ownKey(rule,'ignoreDays')&&get('ignoreDays'))rule.ignoreDays=Math.max(0,Number(get('ignoreDays').value)||0);if(Array.isArray(rule.affectedFeeds)&&get('affectedFeeds'))rule.affectedFeeds=String(get('affectedFeeds').value||'').split(/\r?\n/).map(function(x){return x.trim();}).filter(Boolean);if(s.category&&get('category'))writePath(rule,s.category,String(get('category').value||''));if(s.tags&&get('tags')){var raw=String(get('tags').value||'');writePath(rule,s.tags,Array.isArray(readPath(rule,s.tags))?raw.split(',').map(function(x){return x.trim();}).filter(Boolean):raw);}if(s.savePath&&get('savePath'))writePath(rule,s.savePath,String(get('savePath').value||''));if(s.layout&&get('layout'))writePath(rule,s.layout,String(get('layout').value||''));if(s.paused&&get('paused'))writePath(rule,s.paused,!!get('paused').checked);return{name:name,rule:rule};}
  async function saveRule(){if(state.busy)return;var client=currentClient(),value=collect();if(!client||!value.name)return setStatus(text('Rule name is required.','必须填写规则名称。'),true);if(!canWrite('rsscontroller.h:setRuleAction'))return setStatus(text('This RSS rule write is not source-proven for the current qBittorrent release.','当前 qBittorrent 版本没有源码证明支持 RSS 规则写入。'),true);state.busy=true;setStatus(text('Saving rule…','正在保存规则…'));try{if(state.selected&&state.selected!==value.name){if(!canWrite('rsscontroller.h:renameRuleAction'))throw new Error(text('This qBittorrent release cannot safely rename RSS rules.','当前 qBittorrent 版本无法安全重命名 RSS 规则。'));await client.rssRenameRule(state.selected,value.name);}await client.rssSetRule(value.name,value.rule);state.selected=value.name;await loadRules();await loadMatchingArticles();setStatus(text('RSS rule saved.','RSS 规则已保存。'));}catch(error){setStatus(text('Failed to save RSS rule: ','保存 RSS 规则失败：')+(error&&error.message||error),true);}finally{state.busy=false;}}
  async function removeRule(){if(state.busy||!state.selected)return;var client=currentClient();if(!client||!canWrite('rsscontroller.h:removeRuleAction'))return;state.busy=true;setStatus(text('Removing rule…','正在删除规则…'));try{await client.rssRemoveRule(state.selected);state.selected='';state.draft=null;state.matching={};await loadRules();setStatus(text('RSS rule removed.','RSS 规则已删除。'));}catch(error){setStatus(text('Failed to remove RSS rule: ','删除 RSS 规则失败：')+(error&&error.message||error),true);}finally{state.busy=false;}}
  function render(){renderList();renderEditor();}
  async function loadRules(){var client=currentClient();if(!state.root||!client||!hasAction('rsscontroller.h:rulesAction'))return;try{var rules=await client.rssRules();state.rules=rules&&typeof rules==='object'&&!Array.isArray(rules)?rules:{};if(state.selected&&ownKey(state.rules,state.selected))state.draft=clone(state.rules[state.selected]);else if(state.selected){state.selected='';state.draft=null;state.matching={};}render();}catch(error){setStatus(text('Failed to load RSS rules: ','读取 RSS 规则失败：')+(error&&error.message||error),true);}}
  function install(){var view=document.getElementById('rss-view');if(!view||document.getElementById('rss-rules-panel'))return;var panel=document.createElement('div');panel.id='rss-rules-panel';panel.className='tool-page surface surface--panel';var head=document.createElement('div');head.className='workspace__header';var title=document.createElement('h2');title.textContent=qb('rss.downloader.title','RSS Downloader','RSS 下载器');head.appendChild(title);var actions=document.createElement('div');actions.className='inline-form';var add=button(text('New rule','新建规则'),'btn--primary');add.disabled=!canWrite('rsscontroller.h:setRuleAction');add.addEventListener('click',function(){state.selected='';state.draft=emptyDraft();state.matching={};render();});var refresh=button(text('Refresh rules','刷新规则'),'btn--ghost');refresh.addEventListener('click',loadRules);actions.appendChild(add);actions.appendChild(refresh);head.appendChild(actions);panel.appendChild(head);var layout=document.createElement('div');layout.className='settings-layout';state.list=document.createElement('nav');state.list.id='rss-rules-list';state.list.className='settings-tabs';state.editor=document.createElement('div');state.editor.id='rss-rule-editor';state.editor.className='settings-content';layout.appendChild(state.list);layout.appendChild(state.editor);panel.appendChild(layout);state.status=document.createElement('p');state.status.className='text-description';panel.appendChild(state.status);var existing=view.querySelector('.tool-page');if(existing&&existing.parentNode)existing.parentNode.insertBefore(panel,existing.nextSibling);else view.appendChild(panel);state.root=panel;if(!hasAction('rsscontroller.h:rulesAction')){panel.hidden=true;return;}loadRules();}
  function refresh(){if(!state.root)install();else if(location.hash.replace(/^#\/?/,'').split('/')[0]==='rss')loadRules();}
  W.RSSRules={install:install,refresh:refresh,loadRules:loadRules,loadMatchingArticles:loadMatchingArticles,state:function(){return{selected:state.selected,rules:Object.keys(state.rules||{}),matching:clone(state.matching||{})};}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
  global.addEventListener('hashchange',refresh);global.addEventListener('weigg:languagechange',function(){if(state.root){state.root.remove();state.root=null;state.list=null;state.editor=null;state.status=null;state.matchingRoot=null;install();}});
})(window);
