(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{};
  if(W.RuntimeAssets)return;
  var SCHEMA=2,DB_NAME='weig-runtime-assets',STORE='assets',memory=new Map(),inflight=new Map(),scriptInflight=new Map(),scriptLoaded=new Set(),dbTask=null,upstreamAssetBuilder=typeof W.buildAssetUrl==='function'?W.buildAssetUrl:null;
  function buildId(){var meta=global.document&&document.querySelector&&document.querySelector('meta[name="weig-build-sha"]'),value=meta&&meta.getAttribute('content');value=String(value||'dev').trim()||'dev';return value;}
  var BUILD=buildId();
  function namespace(options){return String(options&&options.namespace||'runtime').trim()||'runtime';}
  function identity(options){return String(options&&options.identity||'global').trim()||'global';}
  function cacheKey(path,options,kind){return[SCHEMA,BUILD,namespace(options),identity(options),String(kind||'text'),String(path||'')].join('\u0001');}
  function assetUrl(path){if(upstreamAssetBuilder)return upstreamAssetBuilder(path);var url=new URL(String(path||''),global.location.href);if(BUILD&&BUILD.indexOf('__WEIG_')!==0)url.searchParams.set('v',BUILD);return url.href;}
  function openDb(){if(dbTask)return dbTask;if(!global.indexedDB)return Promise.resolve(null);dbTask=new Promise(function(resolve){var request;try{request=global.indexedDB.open(DB_NAME,SCHEMA);}catch(_e){resolve(null);return;}request.onupgradeneeded=function(){var db=request.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'key'});};request.onsuccess=function(){resolve(request.result);};request.onerror=function(){resolve(null);};request.onblocked=function(){resolve(null);};});return dbTask;}
  function transaction(mode,run){return openDb().then(function(db){if(!db)return null;return new Promise(function(resolve){var tx,store,req;try{tx=db.transaction(STORE,mode);store=tx.objectStore(STORE);req=run(store);}catch(_e){resolve(null);return;}if(!req){resolve(null);return;}req.onsuccess=function(){resolve(req.result===undefined?null:req.result);};req.onerror=function(){resolve(null);};});});}
  function readStored(key){return transaction('readonly',function(store){return store.get(key);});}
  function writeStored(record){return transaction('readwrite',function(store){return store.put(record);});}
  function deleteStored(key){return transaction('readwrite',function(store){return store.delete(key);});}
  function fetchText(path){return global.fetch(assetUrl(path),{credentials:'same-origin',cache:'no-store'}).then(function(res){if(!res.ok)throw new Error('Runtime asset '+path+' HTTP '+res.status);return res.text();});}
  function fetchBytes(path){return global.fetch(assetUrl(path),{credentials:'same-origin',cache:'no-store'}).then(function(res){if(!res.ok)throw new Error('Runtime asset '+path+' HTTP '+res.status);return res.arrayBuffer();}).then(function(value){return new Uint8Array(value);});}
  function storedValue(record,kind){if(!record||record.schemaVersion!==SCHEMA||record.build!==BUILD||record.kind!==kind)return null;if(kind==='text')return typeof record.value==='string'?record.value:null;var value=record.value;if(value instanceof Uint8Array)return value;if(value&&value.buffer instanceof ArrayBuffer)return new Uint8Array(value.buffer,value.byteOffset||0,value.byteLength);if(value instanceof ArrayBuffer)return new Uint8Array(value);return null;}
  function readAsset(path,options,kind){path=String(path||'');kind=kind==='bytes'?'bytes':'text';var key=cacheKey(path,options,kind);if(memory.has(key))return Promise.resolve(memory.get(key));if(inflight.has(key))return inflight.get(key);var task=readStored(key).then(function(record){var stored=storedValue(record,kind);if(stored!==null){memory.set(key,stored);return stored;}var fetcher=kind==='bytes'?fetchBytes:fetchText;return fetcher(path).then(function(value){memory.set(key,value);writeStored({key:key,schemaVersion:SCHEMA,build:BUILD,namespace:namespace(options),identity:identity(options),kind:kind,path:path,value:value,savedAt:Date.now()});return value;});}).finally(function(){inflight.delete(key);});inflight.set(key,task);return task;}
  function readText(path,options){return readAsset(path,options,'text');}
  function readBytes(path,options){return readAsset(path,options,'bytes');}
  function readJson(path,options){return readText(path,options).then(function(text){try{return JSON.parse(text);}catch(error){throw new Error('Runtime asset '+path+' JSON parse failed: '+error.message);}});}
  function base64Bytes(value){var text=String(value||'').replace(/\s+/g,''),raw=global.atob(text),out=new Uint8Array(raw.length);for(var i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i)&255;return out;}
  function crc32Value(bytes){var crc=0xffffffff;for(var i=0;i<bytes.length;i++){crc^=bytes[i];for(var j=0;j<8;j++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return(crc^0xffffffff)>>>0;}
  function crc32(bytes){return('00000000'+crc32Value(bytes).toString(16)).slice(-8);}
  function sha256(bytes){
    var K=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2],H=[0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19],len=bytes.length,bitHi=Math.floor(len/0x20000000),bitLo=(len<<3)>>>0,total=((len+9+63)>>6)<<6,msg=new Uint8Array(total);msg.set(bytes);msg[len]=0x80;var p=total-8;msg[p]=(bitHi>>>24)&255;msg[p+1]=(bitHi>>>16)&255;msg[p+2]=(bitHi>>>8)&255;msg[p+3]=bitHi&255;msg[p+4]=(bitLo>>>24)&255;msg[p+5]=(bitLo>>>16)&255;msg[p+6]=(bitLo>>>8)&255;msg[p+7]=bitLo&255;var w=new Uint32Array(64);for(var off=0;off<total;off+=64){for(var i=0;i<16;i++){var j=off+i*4;w[i]=((msg[j]<<24)|(msg[j+1]<<16)|(msg[j+2]<<8)|msg[j+3])>>>0;}for(i=16;i<64;i++){var a=w[i-15],b=w[i-2],s0=((a>>>7)|(a<<25))^((a>>>18)|(a<<14))^(a>>>3),s1=((b>>>17)|(b<<15))^((b>>>19)|(b<<13))^(b>>>10);w[i]=(w[i-16]+s0+w[i-7]+s1)>>>0;}var A=H[0],B=H[1],C=H[2],D=H[3],E=H[4],F=H[5],G=H[6],HH=H[7];for(i=0;i<64;i++){var S1=((E>>>6)|(E<<26))^((E>>>11)|(E<<21))^((E>>>25)|(E<<7)),ch=(E&F)^((~E)&G),t1=(HH+S1+ch+K[i]+w[i])>>>0,S0=((A>>>2)|(A<<30))^((A>>>13)|(A<<19))^((A>>>22)|(A<<10)),maj=(A&B)^(A&C)^(B&C),t2=(S0+maj)>>>0;HH=G;G=F;F=E;E=(D+t1)>>>0;D=C;C=B;B=A;A=(t1+t2)>>>0;}H[0]=(H[0]+A)>>>0;H[1]=(H[1]+B)>>>0;H[2]=(H[2]+C)>>>0;H[3]=(H[3]+D)>>>0;H[4]=(H[4]+E)>>>0;H[5]=(H[5]+F)>>>0;H[6]=(H[6]+G)>>>0;H[7]=(H[7]+HH)>>>0;}return H.map(function(x){return('00000000'+x.toString(16)).slice(-8);}).join('');
  }
  function inflateRaw(input,outputLength){
    var bytes=input instanceof Uint8Array?input:new Uint8Array(input),pos=0,bitbuf=0,bitcnt=0,out=new Uint8Array(outputLength||Math.max(1024,bytes.length*8)),op=0;
    function need(n){while(bitcnt<n){if(pos>=bytes.length)throw new Error('Deflate input truncated');bitbuf|=bytes[pos++]<<bitcnt;bitcnt+=8;}}
    function bits(n){need(n);var v=bitbuf&((1<<n)-1);bitbuf>>>=n;bitcnt-=n;return v;}
    function align(){bitbuf=0;bitcnt=0;}function rev(code,len){var r=0;for(var i=0;i<len;i++){r=(r<<1)|(code&1);code>>>=1;}return r;}
    function table(lengths){var max=0,count=[],next=[],map=new Map();for(var i=0;i<lengths.length;i++){var l=lengths[i]|0;if(l){count[l]=(count[l]||0)+1;if(l>max)max=l;}}var code=0;for(var b=1;b<=max;b++){code=(code+(count[b-1]||0))<<1;next[b]=code;}for(var s=0;s<lengths.length;s++){var len=lengths[s]|0;if(!len)continue;map.set((len<<16)|rev(next[len]++,len),s);}return{max:max,map:map};}
    function symbol(t){var code=0;for(var len=1;len<=t.max;len++){code|=bits(1)<<(len-1);var hit=t.map.get((len<<16)|code);if(hit!==undefined)return hit;}throw new Error('Invalid deflate Huffman code');}
    function ensureOut(n){if(op+n<=out.length)return;var next=new Uint8Array(Math.max(op+n,out.length*2));next.set(out);out=next;}
    var LB=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258],LE=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0],DB=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577],DE=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13];
    function fixed(){var l=new Array(288).fill(0),d=new Array(32).fill(5);for(var i=0;i<=143;i++)l[i]=8;for(i=144;i<=255;i++)l[i]=9;for(i=256;i<=279;i++)l[i]=7;for(i=280;i<=287;i++)l[i]=8;return[table(l),table(d)];}
    function dynamic(){var hlit=bits(5)+257,hdist=bits(5)+1,hclen=bits(4)+4,order=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15],cl=new Array(19).fill(0);for(var i=0;i<hclen;i++)cl[order[i]]=bits(3);var ct=table(cl),lens=[];while(lens.length<hlit+hdist){var s=symbol(ct);if(s<=15)lens.push(s);else if(s===16){if(!lens.length)throw new Error('Invalid deflate repeat');var n=bits(2)+3,v=lens[lens.length-1];while(n--)lens.push(v);}else if(s===17){var n0=bits(3)+3;while(n0--)lens.push(0);}else if(s===18){var n1=bits(7)+11;while(n1--)lens.push(0);}else throw new Error('Invalid code-length symbol');}return[table(lens.slice(0,hlit)),table(lens.slice(hlit,hlit+hdist))];}
    var last=0;while(!last){last=bits(1);var type=bits(2);if(type===0){align();if(pos+4>bytes.length)throw new Error('Stored deflate block truncated');var stored=bytes[pos]|(bytes[pos+1]<<8),nlen=bytes[pos+2]|(bytes[pos+3]<<8);pos+=4;if(((stored^0xffff)&0xffff)!==nlen)throw new Error('Stored deflate length mismatch');ensureOut(stored);out.set(bytes.subarray(pos,pos+stored),op);op+=stored;pos+=stored;continue;}if(type===3)throw new Error('Reserved deflate block');var pair=type===1?fixed():dynamic(),lt=pair[0],dt=pair[1];for(;;){var sym=symbol(lt);if(sym<256){ensureOut(1);out[op++]=sym;continue;}if(sym===256)break;var li=sym-257;if(li<0||li>=LB.length)throw new Error('Invalid deflate length symbol');var length=LB[li]+(LE[li]?bits(LE[li]):0),ds=symbol(dt);if(ds<0||ds>=DB.length)throw new Error('Invalid deflate distance symbol');var dist=DB[ds]+(DE[ds]?bits(DE[ds]):0);if(dist<=0||dist>op)throw new Error('Invalid deflate distance');ensureOut(length);for(var k=0;k<length;k++){out[op]=out[op-dist];op++;}}}
    if(outputLength!=null&&op!==outputLength)throw new Error('Deflate output length mismatch');return out.subarray(0,op);
  }
  function decodeUtf8(bytes,label){var Decoder=global.TextDecoder||(typeof TextDecoder!=='undefined'?TextDecoder:null);if(!Decoder)throw new Error((label||'Runtime asset')+' TextDecoder unavailable');return new Decoder('utf-8',{fatal:true}).decode(bytes);}
  function decodeDeflateJson(payload,label){label=String(label||'Runtime deflate JSON');if(!payload||typeof payload!=='object')throw new Error(label+' descriptor missing');var encoded=String(payload.base64||'').replace(/\s+/g,'');if(encoded.length!==Number(payload.base64Chars))throw new Error(label+' base64 length mismatch');var compressed=base64Bytes(encoded);if(compressed.length!==Number(payload.compressedBytes)||sha256(compressed)!==String(payload.compressedSha256||'').toLowerCase())throw new Error(label+' compressed payload mismatch');var raw=inflateRaw(compressed,Number(payload.bytes));if(crc32(raw)!==String(payload.crc32||'').toLowerCase()||sha256(raw)!==String(payload.sha256||'').toLowerCase())throw new Error(label+' payload checksum mismatch');try{return JSON.parse(decodeUtf8(raw,label));}catch(error){throw new Error(label+' JSON parse failed: '+error.message);}}
  function le32(bytes,offset){return(bytes[offset]|(bytes[offset+1]<<8)|(bytes[offset+2]<<16)|(bytes[offset+3]<<24))>>>0;}
  function gunzip(bytes,label){label=String(label||'Runtime gzip');if(!(bytes instanceof Uint8Array))bytes=new Uint8Array(bytes||0);if(bytes.length<18||bytes[0]!==0x1f||bytes[1]!==0x8b||bytes[2]!==8)throw new Error(label+' header invalid');var flags=bytes[3];if(flags&0xe0)throw new Error(label+' reserved flags set');var pos=10,end=bytes.length-8;if(flags&4){if(pos+2>end)throw new Error(label+' extra header truncated');var extra=bytes[pos]|(bytes[pos+1]<<8);pos+=2+extra;}function skipZ(){while(pos<end&&bytes[pos]!==0)pos++;if(pos>=end)throw new Error(label+' text header truncated');pos++;}if(flags&8)skipZ();if(flags&16)skipZ();if(flags&2)pos+=2;if(pos>end)throw new Error(label+' header truncated');var expectedSize=le32(bytes,bytes.length-4),raw=inflateRaw(bytes.subarray(pos,end),expectedSize),expectedCrc=le32(bytes,bytes.length-8);if(crc32Value(raw)!==expectedCrc)throw new Error(label+' CRC32 mismatch');return raw;}
  function readGzipJson(path,options){return readBytes(path,options).then(function(bytes){var raw=gunzip(bytes,'Runtime asset '+path);try{return JSON.parse(decodeUtf8(raw,'Runtime asset '+path));}catch(error){throw new Error('Runtime asset '+path+' gzip JSON parse failed: '+error.message);}});}
  function loadScript(path,options){path=String(path||'');var key=[BUILD,namespace(options),identity(options),path].join('\u0001');if(scriptLoaded.has(key))return Promise.resolve(path);if(scriptInflight.has(key))return scriptInflight.get(key);var task=new Promise(function(resolve,reject){var node=global.document&&document.createElement?document.createElement('script'):null;if(!node){reject(new Error('Runtime script document unavailable: '+path));return;}node.async=false;node.src=assetUrl(path);node.dataset.weigRuntimeModule=path;node.onload=function(){scriptLoaded.add(key);resolve(path);};node.onerror=function(){try{node.remove();}catch(_e){}reject(new Error('Runtime script '+path+' failed'));};document.head.appendChild(node);}).finally(function(){scriptInflight.delete(key);});scriptInflight.set(key,task);return task;}
  function invalidate(path,options){var key=cacheKey(path,options);memory.delete(key);inflight.delete(key);return deleteStored(key);}
  function clearMemory(){memory.clear();inflight.clear();}
  W.buildAssetUrl=W.buildAssetUrl||assetUrl;
  W.RuntimeAssets=Object.freeze({schemaVersion:SCHEMA,build:BUILD,url:assetUrl,key:cacheKey,readText:readText,readBytes:readBytes,readJson:readJson,readGzipJson:readGzipJson,decodeDeflateJson:decodeDeflateJson,loadScript:loadScript,invalidate:invalidate,clearMemory:clearMemory});
})(window);
