(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{},C=W.Components,U=W.util;
  if(!C||!U||W.Selection)return;

  var initialized=false,selectionControl=null,selectionCount=null,rangeAnchor='';
  function isMobile(){return !!(global.matchMedia&&global.matchMedia('(max-width: 820px)').matches);}
  function zh(){return !!(W.I18n&&W.I18n.getLocale&&W.I18n.getLocale()==='zh-CN');}
  function label(en,cn){return zh()?cn:en;}
  function notify(message,tone){if(W.toast)W.toast(message,tone||'info');}
  function getClient(){var app=W.AppState;if(app&&app.client)return Promise.resolve(app.client);return Promise.reject(new Error(label('qBittorrent client is not ready.','qBittorrent 客户端尚未就绪。')));}

  function pageHashes(){var list=document.getElementById('torrent-list'),instance=list&&list.__weiggTorrentVirtual,items=instance&&Array.isArray(instance.items)?instance.items:null;if(items)return items.map(function(t){return t&&t.hash;}).filter(Boolean);return Array.from(document.querySelectorAll('#torrent-list [data-hash]')).map(function(row){return row.dataset.hash;}).filter(Boolean);}
  function matchingCount(){var total=W.LibraryController&&W.LibraryController.total?W.LibraryController.total():null;return Number.isFinite(Number(total))?Number(total):'…';}
  function currentQuery(){var state=W.LibraryController&&W.LibraryController.state?W.LibraryController.state():W.AppState||{};return{filter:state.filter||'all',tracker:state.tracker||'',savePath:state.savePath||'',category:state.category||'',tag:state.tag||'',search:String((document.getElementById('search-input')||{}).value||'').trim().toLocaleLowerCase()};}
  function matchesQuery(t,q){var filter=q.filter,state=String(t.state||'');if(filter==='downloading'&&!(/DL|downloading|metaDL|stalledDL|queuedDL|forcedDL/i.test(state)&&Number(t.progress)<1))return false;if(filter==='seeding'&&!(/UP|uploading|stalledUP|queuedUP|forcedUP/i.test(state)||Number(t.progress)>=1))return false;if(filter==='completed'&&Number(t.progress)<1)return false;if(filter==='paused'&&!/paused|stopped/i.test(state))return false;if(filter==='active'&&!((Number(t.dlspeed)||0)+(Number(t.upspeed)||0)>0))return false;if(filter==='stalled'&&!/stalled/i.test(state))return false;if(filter==='errored'&&!/error|missing/i.test(state))return false;if(filter==='private'&&!(W.TorrentSemantics&&W.TorrentSemantics.isPrivateOrPt&&W.TorrentSemantics.isPrivateOrPt(t,(W.Config.load().ptTrackers||[]))))return false;if(q.category&&String(t.category||'')!==q.category)return false;if(q.tag&&String(t.tags||'').split(',').map(function(x){return x.trim();}).indexOf(q.tag)<0)return false;if(q.tracker&&U.normalizeTracker(t.tracker)!==q.tracker)return false;if(q.savePath&&String(t.save_path||'')!==q.savePath)return false;if(q.search&&String(t.name||'').toLocaleLowerCase().indexOf(q.search)<0)return false;return true;}

  var selected=new Set();
  var Selection={selected:selected,busy:false,count:function(){return selected.size;},has:function(hash){return selected.has(hash);},hashes:function(){return Array.from(selected);},hashString:function(){return Array.from(selected).join('|');},clear:function(silent){selected.clear();rangeAnchor='';apply();if(!silent)syncUi();},selectOnly:function(hash){selected.clear();if(hash)selected.add(hash);rangeAnchor=hash||'';apply();syncUi();},toggle:function(hash,on){if(!hash)return;if(on===undefined)on=!selected.has(hash);if(on)selected.add(hash);else selected.delete(hash);rangeAnchor=hash;apply();syncUi();},selectPage:function(){pageHashes().forEach(function(hash){selected.add(hash);});apply();syncUi();},invertPage:function(){pageHashes().forEach(function(hash){selected.has(hash)?selected.delete(hash):selected.add(hash);});apply();syncUi();},selectRange:function(hash){var hashes=pageHashes(),to=hashes.indexOf(hash),from=hashes.indexOf(rangeAnchor);if(to<0)return;if(from<0){Selection.selectOnly(hash);return;}var lo=Math.min(from,to),hi=Math.max(from,to);for(var i=lo;i<=hi;i++)selected.add(hashes[i]);rangeAnchor=hash;apply();syncUi();},apply:apply,sync:syncUi,selectAllMatching:selectAllMatching,invertAllMatching:invertAllMatching,dispatch:dispatch,openActions:openActions,openDelete:openDelete,init:init};
  W.Selection=Selection;

  function apply(){Array.from(document.querySelectorAll('#torrent-list [data-hash]')).forEach(function(row){var on=selected.has(row.dataset.hash),box=row.querySelector('.torrent-select');if(box)box.checked=on;row.classList.toggle('is-selected',on);row.classList.toggle('selection-range-anchor',!!rangeAnchor&&row.dataset.hash===rangeAnchor);});syncToolbar();}
  function syncToolbar(){var has=selected.size>0;['resume-btn','pause-btn','delete-btn','more-actions-btn'].forEach(function(id){var button=document.getElementById(id);if(button)button.disabled=!has;});}
  function selectionOptions(){return[{value:'',label:label('Select','选择')},{value:'page',label:label('Select page','选择当前页')},{value:'invert-page',label:label('Invert page','反选当前页')},{value:'all',label:label('Select all matching ({n})','选择全部匹配（{n}）').replace('{n}',matchingCount())},{value:'invert-all',label:label('Invert all matching','反选全部匹配')},{value:'clear',label:label('Clear selection','清除选择')}];}
  function syncUi(){if(selectionCount)selectionCount.textContent=Selection.busy?label('Loading…','加载中…'):label('{n} selected','已选择 {n}').replace('{n}',selected.size);if(selectionControl&&selectionControl.setOptions){selectionControl.setOptions(selectionOptions());selectionControl.setValue('');}syncToolbar();}
  function installSelectionControl(){if(document.getElementById('selection-control'))return;var host=document.querySelector('#list-view .grid-toolbar>div:first-child');if(!host)return;var wrap=document.createElement('span');wrap.id='selection-control';wrap.className='selection-control';selectionControl=C.selectControl({id:'selection-action',value:'',options:selectionOptions(),ariaLabel:label('Selection actions','选择操作'),onChange:function(action){if(action==='page')Selection.selectPage();else if(action==='invert-page')Selection.invertPage();else if(action==='all')selectAllMatching().catch(showError);else if(action==='invert-all')invertAllMatching().catch(showError);else if(action==='clear')Selection.clear();if(selectionControl)selectionControl.setValue('');}});selectionCount=document.createElement('span');selectionCount.id='selection-count';selectionCount.className='selection-count';wrap.append(selectionControl,selectionCount);host.insertBefore(wrap,host.firstChild);syncUi();}

  async function allMatchingHashes(){Selection.busy=true;syncUi();try{var qb=await getClient(),all=[],offset=0,batch=200,query=currentQuery();while(true){var part=await qb.getTorrents({sort:'added_on',reverse:'true',limit:batch,offset:offset});part=Array.isArray(part)?part:[];all=all.concat(part);if(part.length<batch)break;offset+=batch;if(offset>100000)break;}return all.filter(function(t){return matchesQuery(t,query);}).map(function(t){return t.hash;}).filter(Boolean);}finally{Selection.busy=false;syncUi();}}
  async function selectAllMatching(){var hashes=await allMatchingHashes();selected.clear();hashes.forEach(function(hash){selected.add(hash);});apply();syncUi();}
  async function invertAllMatching(){var hashes=await allMatchingHashes();hashes.forEach(function(hash){selected.has(hash)?selected.delete(hash):selected.add(hash);});apply();syncUi();}

  function chunks(items,size){var out=[];for(var i=0;i<items.length;i+=size)out.push(items.slice(i,i+size));return out;}
  async function dispatch(kind,value){var hashes=Array.from(selected);if(!hashes.length)return;if(kind==='tags'&&W.CapabilityRegistry&&!W.CapabilityRegistry.supports('tags')){W.CapabilityRegistry.open('tags');return;}if(kind==='details'){if(hashes.length===1&&W.Router)W.Router.detail(hashes[0],'overview');return;}if(kind==='rename'&&hashes.length!==1)throw new Error(label('Rename supports one torrent at a time.','重命名一次只能操作一个种子。'));var qb=await getClient(),groups=chunks(hashes,200);for(var i=0;i<groups.length;i++){var joined=groups[i].join('|');if(kind==='resume')await qb.resume(joined);else if(kind==='pause')await qb.pause(joined);else if(kind==='force')await qb.forceStart(joined,true);else if(kind==='recheck')await qb.recheck(joined);else if(kind==='reannounce')await qb.reannounce(joined);else if(kind==='sequential')await qb.toggleSequential(joined);else if(kind==='firstlast')await qb.toggleFirstLast(joined);else if(kind==='autotmm')await qb.setAutoManagement(joined,true);else if(kind==='top')await qb.topPriority(joined);else if(kind==='bottom')await qb.bottomPriority(joined);else if(kind==='rename')await qb.renameTorrent(groups[i][0],value);else if(kind==='location')await qb.setLocation(joined,value);else if(kind==='category')await qb.setCategory(joined,value);else if(kind==='tags')await qb.addTags(joined,value);else if(kind==='dllimit')await qb.setDownloadLimit(joined,Math.max(0,Number(value)||0)*1024);else if(kind==='uplimit')await qb.setUploadLimit(joined,Math.max(0,Number(value)||0)*1024);else if(kind==='delete')await qb.delete(joined,!!value);}if(kind==='delete')Selection.clear(true);notify(label('Command sent','命令已发送'),'info');if(typeof Selection.onCommandComplete==='function')await Selection.onCommandComplete(kind);}
  function showError(error){notify((error&&error.message)||String(error),'error');}

  var ActionRegistry=[{kind:'resume',en:'Start',cn:'开始'},{kind:'pause',en:'Pause / stop',cn:'暂停 / 停止'},{kind:'force',en:'Force start',cn:'强制开始'},{kind:'recheck',en:'Recheck',cn:'重新校验'},{kind:'reannounce',en:'Reannounce',cn:'重新汇报'},{kind:'sequential',en:'Sequential download',cn:'顺序下载'},{kind:'firstlast',en:'First / last piece priority',cn:'首尾块优先'},{kind:'autotmm',en:'Automatic management',cn:'自动管理'},{kind:'top',en:'Queue top',cn:'队列置顶'},{kind:'bottom',en:'Queue bottom',cn:'队列置底'},{kind:'rename',en:'Rename',cn:'重命名',prompt:true,single:true},{kind:'location',en:'Location',cn:'移动位置',prompt:true},{kind:'category',en:'Category',cn:'设置分类',prompt:true},{kind:'tags',en:'Tags',cn:'添加 Tags',prompt:true,capability:'tags'},{kind:'dllimit',en:'Download limit',cn:'下载限速',prompt:true,hint:'KiB/s'},{kind:'uplimit',en:'Upload limit',cn:'上传限速',prompt:true,hint:'KiB/s'},{kind:'details',en:'View details',cn:'查看详情',single:true}];
  Selection.actions=ActionRegistry;
  function actionTone(kind){if(kind==='delete')return'danger';if(kind==='dllimit'||kind==='uplimit')return'rate';if(kind==='recheck'||kind==='reannounce')return'verify';if(['top','bottom','sequential','firstlast','autotmm'].indexOf(kind)>=0)return'queue';if(['location','category','tags','rename'].indexOf(kind)>=0)return'organize';if(['resume','pause','force'].indexOf(kind)>=0)return'run';return'neutral';}
  function promptValue(def){var dialog=document.getElementById('prompt-dialog'),title=document.getElementById('prompt-title'),fieldLabel=document.getElementById('prompt-label'),input=document.getElementById('prompt-value'),confirm=document.getElementById('prompt-confirm');if(!dialog||!input||!confirm)return;title.textContent=label(def.en,def.cn);fieldLabel.textContent=def.hint||label('Value','值');input.value='';confirm.onclick=async function(){var value=input.value;dialog.close();try{await dispatch(def.kind,value);}catch(error){showError(error);}};dialog.showModal();setTimeout(function(){input.focus();},20);}
  function openActions(){if(!selected.size)return;var dialog=document.getElementById('actions-dialog'),grid=document.getElementById('actions-grid');if(!dialog||!grid)return;grid.textContent='';ActionRegistry.forEach(function(def){if(def.single&&selected.size!==1)return;var button=document.createElement('button');button.type='button';button.className='btn btn--ghost';button.dataset.torrentAction=def.kind;button.dataset.actionTone=actionTone(def.kind);button.textContent=label(def.en,def.cn);if(def.capability)button.dataset.capability=def.capability;button.onclick=function(){dialog.close();if(def.prompt)promptValue(def);else dispatch(def.kind).catch(showError);};grid.appendChild(button);if(def.capability&&W.CapabilityRegistry&&W.CapabilityRegistry.decorate)W.CapabilityRegistry.decorate(button,def.capability);});var del=document.createElement('button');del.type='button';del.className='btn btn--danger-ghost';del.dataset.torrentAction='delete';del.dataset.actionTone='danger';del.textContent=label('Delete','删除');del.onclick=function(){dialog.close();openDelete();};grid.appendChild(del);dialog.showModal();}
  function openDelete(){if(!selected.size)return;var dialog=document.getElementById('delete-dialog'),copy=document.getElementById('delete-copy'),files=document.getElementById('delete-files'),confirm=document.getElementById('delete-confirm');if(!dialog||!confirm)return;if(copy)copy.textContent=label('Delete {n} selected torrent(s).','将删除 {n} 个选中的种子。').replace('{n}',selected.size);if(files)files.checked=false;confirm.onclick=async function(){confirm.disabled=true;try{await dispatch('delete',!!(files&&files.checked));dialog.close();}catch(error){showError(error);}finally{confirm.disabled=false;}};dialog.showModal();}

  function isRowInteractive(target){return !!(target&&target.closest&&target.closest('button,a,[role=button],.torrent-select-hit,.torrent-select'));}
  function installActionHandlers(){
    document.addEventListener('click',function(e){var row=e.target&&e.target.closest&&e.target.closest('#torrent-list [data-hash]');if(!row||isRowInteractive(e.target))return;e.preventDefault();if(e.shiftKey)Selection.selectRange(row.dataset.hash);else if(e.ctrlKey||e.metaKey)Selection.toggle(row.dataset.hash);else Selection.selectOnly(row.dataset.hash);rangeAnchor=row.dataset.hash;},true);
    document.addEventListener('change',function(e){var box=e.target&&e.target.closest&&e.target.closest('.torrent-select');if(!box)return;var row=box.closest('[data-hash]');if(row)Selection.toggle(row.dataset.hash,box.checked);},true);
    document.addEventListener('contextmenu',function(e){if(isMobile())return;var row=e.target&&e.target.closest&&e.target.closest('#torrent-list [data-hash]');if(!row)return;e.preventDefault();if(!selected.has(row.dataset.hash))Selection.selectOnly(row.dataset.hash);openActions();});
    var longTimer=null,longRow=null,startX=0,startY=0;document.addEventListener('pointerdown',function(e){if(!isMobile()||e.pointerType==='mouse')return;var row=e.target&&e.target.closest&&e.target.closest('#torrent-list [data-hash]');if(!row||isRowInteractive(e.target))return;longRow=row;startX=e.clientX;startY=e.clientY;clearTimeout(longTimer);longTimer=setTimeout(function(){if(!longRow)return;Selection.selectOnly(longRow.dataset.hash);openActions();longRow=null;},525);},{passive:true});document.addEventListener('pointermove',function(e){if(!longRow)return;if(Math.hypot(e.clientX-startX,e.clientY-startY)>10){clearTimeout(longTimer);longRow=null;}},{passive:true});document.addEventListener('pointerup',function(){clearTimeout(longTimer);longRow=null;},{passive:true});document.addEventListener('pointercancel',function(){clearTimeout(longTimer);longRow=null;},{passive:true});
    document.addEventListener('keydown',function(e){var tag=e.target&&e.target.tagName&&e.target.tagName.toLowerCase();if(tag==='input'||tag==='textarea'||tag==='select'||e.target&&e.target.isContentEditable)return;if((e.ctrlKey||e.metaKey)&&String(e.key).toLowerCase()==='a'&&W.Router&&W.Router.route&&W.Router.route().name==='home'){e.preventDefault();Selection.selectPage();return;}if(e.key==='Escape'&&selected.size&&!document.querySelector('dialog[open]'))Selection.clear();},true);
  }
  function init(){if(initialized)return;initialized=true;installSelectionControl();installActionHandlers();apply();syncUi();global.addEventListener('weigg:languagechange',syncUi);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
