(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{},C=W.Components,U=W.util;
  if(!C||!U||W.Selection)return;
  var initialized=false,selectionControl=null,selectionCount=null,rangeAnchor='';
  function isMobile(){return !!(global.matchMedia&&global.matchMedia('(max-width: 820px)').matches);}
  function zh(){return !!(W.I18n&&W.I18n.getLocale&&W.I18n.getLocale()==='zh-CN');}
  function label(en,cn){return zh()?cn:en;}
  function notify(message,tone){if(W.toast)W.toast(message,tone||'info');}
  function getClient(){var app=W.AppState;if(app&&app.client)return Promise.resolve(app.client);return Promise.reject(new Error(label('qBittorrent client is not ready.','qBittorrent 客户端尚未就绪。')));}
  function pageHashes(){var list=document.getElementById('torrent-list'),instance=list&&list.__weigTorrentVirtual,items=instance&&Array.isArray(instance.items)?instance.items:null;if(items)return items.map(function(t){return t&&t.hash;}).filter(Boolean);return Array.from(document.querySelectorAll('#torrent-list [data-hash]')).map(function(row){return row.dataset.hash;}).filter(Boolean);}
  function matchingCount(){var total=W.LibraryController&&W.LibraryController.total?W.LibraryController.total():null;return Number.isFinite(Number(total))?Number(total):'…';}
  function currentQuery(){var state=W.LibraryController&&W.LibraryController.state?W.LibraryController.state():W.AppState||{};return{filter:state.filter||'all',tracker:state.tracker||'',savePath:state.savePath||'',category:state.category||'',tag:state.tag||'',search:String((document.getElementById('search-input')||{}).value||'').trim().toLocaleLowerCase()};}
  function matchesQuery(t,q){return !!(W.LibraryController&&W.LibraryController.matchesTorrent&&W.LibraryController.matchesTorrent(t,q));}
  function releaseActionKind(kind){var map={resume:'start',pause:'stop',force:'force',recheck:'recheck',reannounce:'reannounce',sequential:'sequential',firstlast:'firstlast',autotmm:'autotmm',superseeding:'superseeding',top:'top',increase:'increase',decrease:'decrease',bottom:'bottom',rename:'rename',location:'location',category:'category',tags:'tags',dllimit:'dllimit',uplimit:'uplimit',export:'export',delete:'delete'};return map[String(kind||'')]||null;}
  function actionSupported(kind){var semantic=releaseActionKind(kind),R=W.CapabilityRegistry;if(kind==='copyname')return !R||typeof R.hasTorrentInfoField!=='function'||R.hasTorrentInfoField('name');if(kind==='copyhash')return true;if(kind==='copymagnet')return !R||typeof R.hasTorrentInfoField!=='function'||R.hasTorrentInfoField('magnet_uri');if(kind==='export')return !!(R&&typeof R.isCertified==='function'&&R.isCertified()&&typeof R.hasAction==='function'&&R.hasAction('torrentscontroller.h:exportAction'));if(kind==='superseeding'&&R&&typeof R.hasTorrentInfoField==='function'&&!R.hasTorrentInfoField('super_seeding'))return false;if(!semantic)return true;if(!R||typeof R.supportsTorrentAction!=='function')return true;return R.supportsTorrentAction(semantic);}
  function sourceWriteSupported(action){var R=W.CapabilityRegistry;return !!(R&&R.supportsWriteAction&&R.supportsWriteAction(action));}
  function unsupportedActionError(kind){return new Error(label('This action is not supported by the current qBittorrent release.','当前 qBittorrent 版本不支持此操作。')+' ['+String(kind||'')+']');}
  var selected=new Set();
  var Selection={selected:selected,busy:false,count:function(){return selected.size;},has:function(hash){return selected.has(hash);},hashes:function(){return Array.from(selected);},hashString:function(){return Array.from(selected).join('|');},clear:function(silent){selected.clear();rangeAnchor='';apply();if(!silent)syncUi();},selectOnly:function(hash){selected.clear();if(hash)selected.add(hash);rangeAnchor=hash||'';apply();syncUi();},toggle:function(hash,on){if(!hash)return;if(on===undefined)on=!selected.has(hash);if(on)selected.add(hash);else selected.delete(hash);rangeAnchor=hash;apply();syncUi();},selectPage:function(){pageHashes().forEach(function(hash){selected.add(hash);});apply();syncUi();},invertPage:function(){pageHashes().forEach(function(hash){selected.has(hash)?selected.delete(hash):selected.add(hash);});apply();syncUi();},selectRange:function(hash){var hashes=pageHashes(),to=hashes.indexOf(hash),from=hashes.indexOf(rangeAnchor);if(to<0)return;if(from<0){Selection.selectOnly(hash);return;}var lo=Math.min(from,to),hi=Math.max(from,to);for(var i=lo;i<=hi;i++)selected.add(hashes[i]);rangeAnchor=hash;apply();syncUi();},apply:apply,sync:syncUi,selectAllMatching:selectAllMatching,invertAllMatching:invertAllMatching,dispatch:dispatch,openActions:openActions,openDelete:openDelete,actionSupported:actionSupported,init:init};
  W.Selection=Selection;
  function apply(){Array.from(document.querySelectorAll('#torrent-list [data-hash]')).forEach(function(row){var on=selected.has(row.dataset.hash),box=row.querySelector('.torrent-select');if(box)box.checked=on;row.classList.toggle('is-selected',on);row.classList.toggle('selection-range-anchor',!!rangeAnchor&&row.dataset.hash===rangeAnchor);});syncToolbar();}
  function syncToolbar(){var has=selected.size>0,actions={'resume-btn':'resume','pause-btn':'pause','delete-btn':'delete'};Object.keys(actions).forEach(function(id){var button=document.getElementById(id);if(button)button.disabled=!has||!actionSupported(actions[id]);});var more=document.getElementById('more-actions-btn');if(more)more.disabled=!has;}
  function selectionOptions(){return[{value:'',label:label('Select','选择')},{value:'page',label:label('Select page','选择当前页')},{value:'invert-page',label:label('Invert page','反选当前页')},{value:'all',label:label('Select all matching ({n})','选择全部匹配（{n}）').replace('{n}',matchingCount())},{value:'invert-all',label:label('Invert all matching','反选全部匹配')},{value:'clear',label:label('Clear selection','清除选择')}];}
  function syncUi(){if(selectionCount)selectionCount.textContent=Selection.busy?label('Loading…','加载中…'):label('{n} selected','已选择 {n}').replace('{n}',selected.size);if(selectionControl&&selectionControl.setOptions){selectionControl.setOptions(selectionOptions());selectionControl.setValue('');}syncToolbar();}
  function installSelectionControl(){if(document.getElementById('selection-control'))return;var host=document.querySelector('#list-view .grid-toolbar>div:first-child');if(!host)return;var wrap=document.createElement('span');wrap.id='selection-control';wrap.className='selection-control';selectionControl=C.selectControl({id:'selection-action',value:'',options:selectionOptions(),ariaLabel:label('Selection actions','选择操作'),onChange:function(action){if(action==='page')Selection.selectPage();else if(action==='invert-page')Selection.invertPage();else if(action==='all')selectAllMatching().catch(showError);else if(action==='invert-all')invertAllMatching().catch(showError);else if(action==='clear')Selection.clear();if(selectionControl)selectionControl.setValue('');}});selectionCount=document.createElement('span');selectionCount.id='selection-count';selectionCount.className='selection-count';wrap.append(selectionControl,selectionCount);host.insertBefore(wrap,host.firstChild);syncUi();}
  async function allMatchingHashes(){Selection.busy=true;syncUi();try{var qb=await getClient(),all=[],offset=0,batch=200,query=currentQuery();while(true){var part=await qb.getTorrents({sort:'added_on',reverse:'true',limit:batch,offset:offset});part=Array.isArray(part)?part:[];all=all.concat(part);if(part.length<batch)break;offset+=batch;if(offset>100000)break;}return all.filter(function(t){return matchesQuery(t,query);}).map(function(t){return t.hash;}).filter(Boolean);}finally{Selection.busy=false;syncUi();}}
  async function selectAllMatching(){var hashes=await allMatchingHashes();selected.clear();hashes.forEach(function(hash){selected.add(hash);});apply();syncUi();}
  async function invertAllMatching(){var hashes=await allMatchingHashes();hashes.forEach(function(hash){selected.has(hash)?selected.delete(hash):selected.add(hash);});apply();syncUi();}
  function chunks(items,size){var out=[];for(var i=0;i<items.length;i+=size)out.push(items.slice(i,i+size));return out;}
  async function clipboardWrite(text){text=String(text||'');if(!text)return;if(navigator.clipboard&&navigator.clipboard.writeText)return navigator.clipboard.writeText(text);var area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();try{document.execCommand('copy');}finally{area.remove();}}
  async function selectedTorrents(qb,hashes){var rows=await qb.getTorrents({hashes:hashes.join('|')});return Array.isArray(rows)?rows:[];}
  function safeFileName(value){return String(value||'torrent').replace(/[\\/:*?"<>|]+/g,'_').replace(/[. ]+$/,'')||'torrent';}
  async function exportSelected(qb,hashes){var rows=await selectedTorrents(qb,hashes),names={};rows.forEach(function(row){if(row&&row.hash)names[row.hash]=row.name;});for(var i=0;i<hashes.length;i++){var hash=hashes[i],blob=await qb.request('torrents/export?hash='+encodeURIComponent(hash),{type:'blob'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=safeFileName(names[hash]||hash)+'.torrent';a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(function(u){URL.revokeObjectURL(u);},1000,url);}}
  async function dispatch(kind,value){var hashes=Array.from(selected);if(!hashes.length)return;if(!actionSupported(kind))throw unsupportedActionError(kind);if(kind==='tags'&&W.CapabilityRegistry&&!W.CapabilityRegistry.supports('addTags')){W.CapabilityRegistry.open('addTags');return;}if(kind==='details'){if(hashes.length===1&&W.Router)W.Router.detail(hashes[0],'overview');return;}if(kind==='rename'&&hashes.length!==1)throw new Error(label('Rename supports one torrent at a time.','重命名一次只能操作一个种子。'));var qb=await getClient();if(kind==='copyhash'){await clipboardWrite(hashes.join('\n'));notify(label('Copied','已复制'),'success');return;}if(kind==='copyname'||kind==='copymagnet'){var rows=await selectedTorrents(qb,hashes),key=kind==='copyname'?'name':'magnet_uri',text=rows.map(function(row){return row&&row[key];}).filter(Boolean).join('\n');await clipboardWrite(text);notify(label('Copied','已复制'),'success');return;}if(kind==='export'){await exportSelected(qb,hashes);notify(label('Torrent export started','已开始导出 .torrent'),'success');return;}if(kind==='superseeding'){var live=await selectedTorrents(qb,hashes),enable=!live.length||!live.every(function(row){return row&&row.super_seeding===true;});await qb._guardedTorrentAction('superseeding','setSuperSeeding',{hashes:hashes.join('|'),value:enable});notify(label('Command sent','命令已发送'),'info');if(typeof Selection.onCommandComplete==='function')await Selection.onCommandComplete(kind);return;}var groups=chunks(hashes,200);for(var i=0;i<groups.length;i++){var joined=groups[i].join('|');if(kind==='resume')await qb.resume(joined);else if(kind==='pause')await qb.pause(joined);else if(kind==='force')await qb.forceStart(joined,true);else if(kind==='recheck')await qb.recheck(joined);else if(kind==='reannounce')await qb.reannounce(joined);else if(kind==='sequential')await qb.toggleSequential(joined);else if(kind==='firstlast')await qb.toggleFirstLast(joined);else if(kind==='autotmm')await qb.setAutoManagement(joined,true);else if(kind==='top')await qb.topPriority(joined);else if(kind==='increase')await qb._guardedTorrentAction('increase','increasePrio',{hashes:joined});else if(kind==='decrease')await qb._guardedTorrentAction('decrease','decreasePrio',{hashes:joined});else if(kind==='bottom')await qb.bottomPriority(joined);else if(kind==='rename')await qb.renameTorrent(groups[i][0],value);else if(kind==='location')await qb.setLocation(joined,value);else if(kind==='category')await qb.setCategory(joined,value);else if(kind==='tags')await qb.addTags(joined,value);else if(kind==='dllimit')await qb.setDownloadLimit(joined,Math.max(0,Number(value)||0)*1024);else if(kind==='uplimit')await qb.setUploadLimit(joined,Math.max(0,Number(value)||0)*1024);else if(kind==='delete')await qb.delete(joined,!!value);}if(kind==='delete')Selection.clear(true);notify(label('Command sent','命令已发送'),'info');if(typeof Selection.onCommandComplete==='function')await Selection.onCommandComplete(kind);}
  async function setTagMembership(tag,remove){var hashes=Array.from(selected);if(!hashes.length)return;if(remove&&!sourceWriteSupported('torrentscontroller.h:removeTagsAction'))throw unsupportedActionError('removeTags');var qb=await getClient(),groups=chunks(hashes,200);for(var i=0;i<groups.length;i++){var joined=groups[i].join('|');if(remove)await qb.removeTags(joined,tag);else await qb.addTags(joined,tag);}notify(remove?label('Tag removed','已移除标签'):label('Tag added','已添加标签'),'info');if(typeof Selection.onCommandComplete==='function')await Selection.onCommandComplete('tags');}
  function showError(error){notify((error&&error.message)||String(error),'error');}
  var TorrentActionDefinitions=[{kind:'resume',en:'Start',cn:'开始'},{kind:'pause',en:'Pause / stop',cn:'暂停 / 停止'},{kind:'force',en:'Force start',cn:'强制开始'},{kind:'recheck',en:'Recheck',cn:'重新校验'},{kind:'reannounce',en:'Reannounce',cn:'重新汇报'},{kind:'sequential',en:'Sequential download',cn:'顺序下载'},{kind:'firstlast',en:'First / last piece priority',cn:'首尾块优先'},{kind:'autotmm',en:'Automatic management',cn:'自动管理'},{kind:'superseeding',en:'Super seeding mode',cn:'超级做种模式'},{kind:'top',en:'Queue top',cn:'队列置顶'},{kind:'increase',en:'Move queue up',cn:'队列上移'},{kind:'decrease',en:'Move queue down',cn:'队列下移'},{kind:'bottom',en:'Queue bottom',cn:'队列置底'},{kind:'rename',en:'Rename',cn:'重命名',prompt:true,single:true},{kind:'location',en:'Location',cn:'移动位置',prompt:true},{kind:'category',en:'Category',cn:'设置分类',prompt:true},{kind:'tags',en:'Tags',cn:'添加 Tags',prompt:true,capability:'addTags'},{kind:'dllimit',en:'Download limit',cn:'下载限速',prompt:true,hint:'KiB/s'},{kind:'uplimit',en:'Upload limit',cn:'上传限速',prompt:true,hint:'KiB/s'},{kind:'copyname',en:'Copy name',cn:'复制名称'},{kind:'copyhash',en:'Copy hash',cn:'复制哈希'},{kind:'copymagnet',en:'Copy magnet link',cn:'复制磁力链接'},{kind:'export',en:'Export .torrent',cn:'导出 .torrent'},{kind:'details',en:'View details',cn:'查看详情',single:true}];
  Selection.actions=TorrentActionDefinitions;
  function actionTone(kind){if(kind==='delete')return'danger';if(kind==='dllimit'||kind==='uplimit')return'rate';if(kind==='recheck'||kind==='reannounce')return'verify';if(['top','increase','decrease','bottom','sequential','firstlast','autotmm','superseeding'].indexOf(kind)>=0)return'queue';if(['location','category','tags','rename','copyname','copyhash','copymagnet','export'].indexOf(kind)>=0)return'organize';if(['resume','pause','force'].indexOf(kind)>=0)return'run';return'neutral';}
  function actionDefinition(kind){return TorrentActionDefinitions.find(function(def){return def.kind===kind;})||null;}
  function promptValue(def){var dialog=document.getElementById('prompt-dialog'),title=document.getElementById('prompt-title'),fieldLabel=document.getElementById('prompt-label'),input=document.getElementById('prompt-value'),confirm=document.getElementById('prompt-confirm');if(!dialog||!input||!confirm)return;title.textContent=label(def.en,def.cn);fieldLabel.textContent=def.hint||label('Value','值');input.value='';confirm.onclick=async function(){var value=input.value;W.DialogRuntime.close(dialog);try{await dispatch(def.kind,value);}catch(error){showError(error);}};W.DialogRuntime.open(dialog,{draggable:true});setTimeout(function(){input.focus();},20);}
  function actionLeaf(kind){var def=actionDefinition(kind);if(!def)return null;if(def.single&&selected.size!==1)return null;if(!actionSupported(def.kind))return null;return{kind:def.kind,label:label(def.en,def.cn),tone:actionTone(def.kind),capability:def.capability||'',run:function(){if(def.prompt)promptValue(def);else dispatch(def.kind).catch(showError);}};}
  function actionGroup(id,en,cn,children,tone){children=(children||[]).filter(Boolean);return children.length?{kind:id,label:label(en,cn),tone:tone||'organize',children:children}:null;}
  function tagList(row){return String(row&&row.tags||'').split(',').map(function(value){return value.trim();}).filter(Boolean);}
  async function buildActionTree(){var qb=await getClient(),hashes=Array.from(selected),rows=[],categories={},tags=[];try{rows=await selectedTorrents(qb,hashes);}catch(_e){}if(actionSupported('category')&&typeof qb.categories==='function'){try{categories=await qb.categories()||{};}catch(_e2){categories={};}}if(actionSupported('tags')&&typeof qb.tags==='function'){try{tags=await qb.tags()||[];}catch(_e3){tags=[];}}var categoryItems=[],tagItems=[],queueItems=[],copyItems=[];if(actionSupported('category')){categoryItems.push({kind:'category-none',label:label('No category','无分类'),tone:'organize',run:function(){dispatch('category','').catch(showError);}});Object.keys(categories||{}).sort().forEach(function(category){categoryItems.push({kind:'category:'+category,label:category,tone:'organize',run:function(){dispatch('category',category).catch(showError);}});});}if(actionSupported('tags')){var canRemove=sourceWriteSupported('torrentscontroller.h:removeTagsAction');(Array.isArray(tags)?tags:[]).map(String).filter(Boolean).sort().forEach(function(tag){var allActive=rows.length>0&&rows.every(function(row){return tagList(row).indexOf(tag)>=0;});tagItems.push({kind:'tag:'+tag,label:(allActive?'✓ ':'')+tag,tone:'organize',run:function(){setTagMembership(tag,allActive&&canRemove).catch(showError);}});});var tagDef=actionDefinition('tags');if(tagDef)tagItems.push({kind:'tag-add',label:label('Add Tags…','添加标签…'),tone:'organize',capability:tagDef.capability||'',run:function(){promptValue(tagDef);}});}['top','increase','decrease','bottom'].forEach(function(kind){var leaf=actionLeaf(kind);if(leaf)queueItems.push(leaf);});['copyname','copyhash','copymagnet'].forEach(function(kind){var leaf=actionLeaf(kind);if(leaf)copyItems.push(leaf);});var root=[];['resume','pause','force','recheck','reannounce','rename','location'].forEach(function(kind){var leaf=actionLeaf(kind);if(leaf)root.push(leaf);});var categoryGroup=actionGroup('group-category','Category','分类',categoryItems,'organize'),tagGroup=actionGroup('group-tags','Tags','标签',tagItems,'organize');if(categoryGroup)root.push(categoryGroup);if(tagGroup)root.push(tagGroup);['sequential','firstlast','autotmm','superseeding'].forEach(function(kind){var leaf=actionLeaf(kind);if(leaf)root.push(leaf);});var queueGroup=actionGroup('group-queue','Queue','队列',queueItems,'queue');if(queueGroup)root.push(queueGroup);['dllimit','uplimit'].forEach(function(kind){var leaf=actionLeaf(kind);if(leaf)root.push(leaf);});var copyGroup=actionGroup('group-copy','Copy','复制',copyItems,'organize');if(copyGroup)root.push(copyGroup);['export','details'].forEach(function(kind){var leaf=actionLeaf(kind);if(leaf)root.push(leaf);});if(actionSupported('delete'))root.push({kind:'delete',label:label('Delete','删除'),tone:'danger',danger:true,run:openDelete});return root;}
  function renderActionLevel(dialog,grid,items,backItems){grid.textContent='';if(backItems){var back=document.createElement('button');back.type='button';back.className='btn btn--ghost';back.dataset.torrentAction='back';back.textContent=label('← Back','← 返回');back.onclick=function(){renderActionLevel(dialog,grid,backItems,null);};grid.appendChild(back);}items.forEach(function(item){var button=document.createElement('button');button.type='button';button.className=item.danger?'btn btn--danger-ghost':'btn btn--ghost';button.dataset.torrentAction=item.kind||'';button.dataset.actionTone=item.tone||'neutral';button.textContent=item.label+(item.children?' ›':'');if(item.capability)button.dataset.capability=item.capability;button.onclick=function(){if(item.children){renderActionLevel(dialog,grid,item.children,items);return;}W.DialogRuntime.close(dialog);if(item.run)item.run();};grid.appendChild(button);if(item.capability&&W.CapabilityRegistry&&W.CapabilityRegistry.decorate)W.CapabilityRegistry.decorate(button,item.capability);});}
  async function openActions(){if(!selected.size)return;var dialog=document.getElementById('actions-dialog'),grid=document.getElementById('actions-grid');if(!dialog||!grid)return;grid.textContent='';var loading=document.createElement('span');loading.className='text-description';loading.textContent=label('Loading actions…','正在加载操作…');grid.appendChild(loading);if(!dialog.open)W.DialogRuntime.open(dialog,{draggable:true});try{var items=await buildActionTree();if(!selected.size){W.DialogRuntime.close(dialog);return;}renderActionLevel(dialog,grid,items,null);}catch(error){showError(error);grid.textContent='';var failed=document.createElement('span');failed.className='text-description';failed.textContent=label('Actions unavailable.','操作暂不可用。');grid.appendChild(failed);}}
  function openDelete(){if(!selected.size)return;if(!actionSupported('delete')){showError(unsupportedActionError('delete'));return;}var dialog=document.getElementById('delete-dialog'),copy=document.getElementById('delete-copy'),files=document.getElementById('delete-files'),confirm=document.getElementById('delete-confirm');if(!dialog||!confirm)return;if(copy)copy.textContent=label('Delete {n} selected torrent(s).','将删除 {n} 个选中的种子。').replace('{n}',selected.size);if(files)files.checked=false;confirm.onclick=async function(){confirm.disabled=true;try{await dispatch('delete',!!(files&&files.checked));W.DialogRuntime.close(dialog);}catch(error){showError(error);}finally{confirm.disabled=false;}};W.DialogRuntime.open(dialog,{draggable:true});}
  function isRowInteractive(target){return !!(target&&target.closest&&target.closest('button,a,[role=button],.torrent-select-hit,.torrent-select'));}
  function installActionHandlers(){document.addEventListener('click',function(e){var row=e.target&&e.target.closest&&e.target.closest('#torrent-list [data-hash]');if(!row||isRowInteractive(e.target))return;e.preventDefault();if(e.shiftKey)Selection.selectRange(row.dataset.hash);else if(e.ctrlKey||e.metaKey)Selection.toggle(row.dataset.hash);else Selection.selectOnly(row.dataset.hash);rangeAnchor=row.dataset.hash;},true);document.addEventListener('change',function(e){var box=e.target&&e.target.closest&&e.target.closest('.torrent-select');if(!box)return;var row=box.closest('[data-hash]');if(row)Selection.toggle(row.dataset.hash,box.checked);},true);document.addEventListener('contextmenu',function(e){if(isMobile())return;var row=e.target&&e.target.closest&&e.target.closest('#torrent-list [data-hash]');if(!row)return;e.preventDefault();if(!selected.has(row.dataset.hash))Selection.selectOnly(row.dataset.hash);openActions();});var longTimer=null,longRow=null,startX=0,startY=0;document.addEventListener('pointerdown',function(e){if(!isMobile()||e.pointerType==='mouse')return;var row=e.target&&e.target.closest&&e.target.closest('#torrent-list [data-hash]');if(!row||isRowInteractive(e.target))return;longRow=row;startX=e.clientX;startY=e.clientY;clearTimeout(longTimer);longTimer=setTimeout(function(){if(!longRow)return;Selection.selectOnly(longRow.dataset.hash);openActions();longRow=null;},525);},{passive:true});document.addEventListener('pointermove',function(e){if(!longRow)return;if(Math.hypot(e.clientX-startX,e.clientY-startY)>10){clearTimeout(longTimer);longRow=null;}},{passive:true});document.addEventListener('pointerup',function(){clearTimeout(longTimer);longRow=null;},{passive:true});document.addEventListener('pointercancel',function(){clearTimeout(longTimer);longRow=null;},{passive:true});document.addEventListener('keydown',function(e){var tag=e.target&&e.target.tagName&&e.target.tagName.toLowerCase();if(tag==='input'||tag==='textarea'||tag==='select'||e.target&&e.target.isContentEditable)return;if((e.ctrlKey||e.metaKey)&&String(e.key).toLowerCase()==='a'&&W.Router&&W.Router.route&&W.Router.route().name==='home'){e.preventDefault();Selection.selectPage();return;}if(e.key==='Escape'&&selected.size&&!document.querySelector('dialog[open]'))Selection.clear();},true);}
  function init(){if(initialized)return;initialized=true;installSelectionControl();installActionHandlers();apply();syncUi();global.addEventListener('weig:languagechange',syncUi);global.addEventListener('weig:capabilities-ready',syncUi);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
