(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{},compat=null,compatTask=null,boundRelease=null,expandedCache=null;
  var PREF_FIELDS=['tab','sectionId','order','titleRef','descriptionRef','controlId','semantic','attributes','options','unitRef','staticDisabled','gates','projection'];
  var DESC_FIELDS=['getterPresent','setterPresent','readType','writeType','typeAgreement','writable'];
  function own(obj,key){return Object.prototype.hasOwnProperty.call(obj||{},key);}
  function clone(value){if(Array.isArray(value))return value.map(clone);if(value&&typeof value==='object'){var out={};Object.keys(value).forEach(function(key){out[key]=clone(value[key]);});return out;}return value;}
  function versionParts(value){return String(value||'0').replace(/^v/i,'').split(/[+-]/)[0].split('.').map(function(x){var n=parseInt(x,10);return Number.isFinite(n)?n:0;});}
  function compareVersion(a,b){var x=versionParts(a),y=versionParts(b),n=Math.max(x.length,y.length);for(var i=0;i<n;i++){var av=x[i]||0,bv=y[i]||0;if(av>bv)return 1;if(av<bv)return-1;}return 0;}
  function changeValue(rows){if(!boundRelease||!Array.isArray(rows))return null;var value=null;for(var i=0;i<rows.length;i++){if(compareVersion(rows[i].from,boundRelease.qbVersion)<=0)value=rows[i].value;else break;}return clone(value);}
  function rowObject(fields,row){var out={};if(!Array.isArray(row))return out;for(var i=0;i<fields.length;i++)out[fields[i]]=clone(row[i]);return out;}
  function humanize(key){return String(key||'').replace(/[_-]+/g,' ').replace(/\b[a-z]/g,function(c){return c.toUpperCase();}).replace(/\bUi\b/g,'UI').replace(/\bRss\b/g,'RSS').replace(/\bSsl\b/g,'SSL');}
  function ref(id){if(!compat||!Number.isInteger(id)||id<0||!Array.isArray(compat.refs)||!Array.isArray(compat.refs[id]))return null;return{context:String(compat.refs[id][0]||''),source:String(compat.refs[id][1]||'')};}
  function refText(id,fallback){var value=ref(id);return value&&value.source?value.source:String(fallback||'');}
  function optionValue(raw){if(!Array.isArray(raw))return{value:'',label:'',labelRef:null};var label=raw[1],labelRef=null,text='';if(Array.isArray(label)&&label[0]==='r'){labelRef=ref(label[1]);text=labelRef&&labelRef.source?labelRef.source:String(raw[0]??'');}else if(Array.isArray(label)&&label[0]==='l')text=String(label[1]??raw[0]);else text=String(raw[0]??'');return{value:raw[0],label:text,labelRef:labelRef};}
  function releaseRow(){if(!compat||!boundRelease||!Array.isArray(compat.releases))return null;var version=String(boundRelease.qbVersion||''),sha=String(boundRelease.sourceSha||'').toLowerCase();for(var i=0;i<compat.releases.length;i++){var row=compat.releases[i];if(Array.isArray(row)&&String(row[0])===version&&String(row[1]||'').toLowerCase()===sha)return row;}return null;}
  function identityReady(){return !!(boundRelease&&boundRelease.fallback!==true&&releaseRow());}
  function loadCompatibility(){if(compat)return Promise.resolve(compat);if(compatTask)return compatTask;var R=W.CapabilityRegistry;if(!R||typeof R.ensure!=='function')return Promise.reject(new Error('CapabilityRegistry Settings domain loader is unavailable'));compatTask=R.ensure('settings').then(function(next){if(!next||next.schemaVersion!==2||next.source!=='qb-upstream-preferences-native-surface-compact'||!next.preferences||!next.descriptors||!Array.isArray(next.tabs)||!Array.isArray(next.releases))throw new Error('Invalid source-native Settings compatibility contract');compat=next;expandedCache=null;return compat;}).finally(function(){compatTask=null;});return compatTask;}
  function decodePreference(key){var row=changeValue(compat&&compat.preferences&&compat.preferences[key]);if(!row)return null;var item=rowObject(PREF_FIELDS,row),descriptorRow=changeValue(compat&&compat.descriptors&&compat.descriptors[key]),descriptor=descriptorRow?rowObject(DESC_FIELDS,descriptorRow):null;item.key=key;item.title=ref(item.titleRef);item.description=ref(item.descriptionRef);item.unit=ref(item.unitRef);item.options=item.options===0||!Array.isArray(item.options)?[]:item.options.map(optionValue);item.attributes=item.attributes===0||!item.attributes?{}:item.attributes;item.gates=item.gates===0||!Array.isArray(item.gates)?[]:item.gates.map(function(gate){return{controlId:String(gate&&gate[0]||''),preferenceKey:String(gate&&gate[1]||'')};});item.projection=item.projection===0?null:item.projection;item.staticDisabled=item.staticDisabled===1;item.descriptor=descriptor;return item;}
  function expanded(){if(!compat||!identityReady())return{tabs:[],byTab:{},preferences:{}};var cacheKey=String(boundRelease.qbVersion)+'@'+String(boundRelease.sourceSha);if(expandedCache&&expandedCache.key===cacheKey)return expandedCache.value;var tabRows=changeValue(compat.tabs)||[],tabs=[],byTab={},preferences={};tabRows.forEach(function(row,index){if(!Array.isArray(row)||!row[0])return;var id=String(row[0]),tab={id:id,nativeId:String(row[1]||''),title:ref(row[2]),order:index,sections:[]};var sectionRows=changeValue(compat.sections&&compat.sections[id])||[];tab.sections=sectionRows.map(function(section,sectionIndex){return{id:String(section&&section[0]||id+':'+sectionIndex),title:ref(section&&section[1]),order:sectionIndex,keys:[]};});tabs.push(tab);byTab[id]=tab;});Object.keys(compat.preferences||{}).forEach(function(key){var item=decodePreference(key);if(!item||!byTab[item.tab])return;preferences[key]=item;var section=byTab[item.tab].sections.find(function(value){return value.id===item.sectionId;});if(section)section.keys.push(key);});tabs.forEach(function(tab){tab.sections.forEach(function(section){section.keys.sort(function(a,b){return(preferences[a]&&preferences[a].order||0)-(preferences[b]&&preferences[b].order||0);});});});var value={tabs:tabs,byTab:byTab,preferences:preferences};expandedCache={key:cacheKey,value:value};return value;}
  function nativeSurfaces(){return expanded().tabs.map(function(tab){return tab.id;});}
  function tabTitle(tab){var value=expanded().byTab[String(tab||'')];return value&&value.title&&value.title.source?value.title.source:humanize(tab);}
  function tabTitleRef(tab){var value=expanded().byTab[String(tab||'')];return value?clone(value.title):null;}
  function dependencySatisfied(item,state){if(!item||!item.gates||!item.gates.length)return true;state=state||{};return item.gates.every(function(gate){return !!(gate.preferenceKey&&own(state,gate.preferenceKey)&&state[gate.preferenceKey]);});}
  function sourceActionWritable(){var R=W.CapabilityRegistry;return !!(R&&typeof R.supportsWriteAction==='function'&&R.supportsWriteAction('appcontroller.h:setPreferencesAction'));}
  function typeMatches(value,type){if(type==='boolean')return typeof value==='boolean';if(type==='number')return typeof value==='number'&&Number.isFinite(value);if(type==='string')return typeof value==='string';return false;}
  function writeSafe(item,value,prefs,state){var descriptor=item&&item.descriptor,projection=item&&item.projection;if(!identityReady()||!boundRelease||boundRelease.certified!==true||!sourceActionWritable()||!prefs||!own(prefs,item.key)||item.staticDisabled||!dependencySatisfied(item,state||prefs)||!descriptor||descriptor.setterPresent!==true||descriptor.writable!==true||descriptor.typeAgreement!=='EXACT'||!descriptor.writeType||!projection||projection.safeWrite!==true)return false;return typeMatches(value,descriptor.writeType);}
  function semanticKind(item,value){var semantic=String(item&&item.semantic||'');if(semantic==='checkbox')return'boolean';if(semantic==='number')return'number';if(semantic==='password')return'password';if(semantic==='textarea')return'textarea';if(semantic==='structured')return'structured';if(semantic==='select')return'select';if(semantic==='text')return'text';if(value!==null&&typeof value==='object')return'structured';return typeof value==='boolean'?'boolean':typeof value==='number'?'number':'text';}
  function coerceWrite(value,type){if(type==='string')return String(value==null?'':value);if(type==='boolean')return value===true||value==='true'||value===1||value==='1';if(type==='number'){var number=Number(value);return Number.isFinite(number)?number:value;}return value;}
  function toDisplay(key,raw){var item=expanded().preferences[String(key||'')],projection=item&&item.projection;if(!projection)return raw;var n=Number(raw);if(projection.kind==='scale'&&Number.isFinite(n)&&Number(projection.scale)>0)return n/Number(projection.scale);if(projection.kind==='unproven'&&Number.isFinite(n)&&Number.isFinite(Number(projection.readFactor)))return n*Number(projection.readFactor);if(projection.kind==='switch-map'){var hit=(projection.values||[]).find(function(row){return String(row&&row[0])===String(raw);});return hit?hit[1]:projection.defaultValue;}return raw;}
  function toRaw(key,value){var item=expanded().preferences[String(key||'')],projection=item&&item.projection,descriptor=item&&item.descriptor,raw=value;if(projection&&projection.kind==='scale'&&Number(projection.scale)>0){var n=Number(value);raw=Number.isFinite(n)?n*Number(projection.scale):value;}else if(projection&&projection.kind==='identity')raw=value;else if(projection&&projection.kind==='unproven'&&projection.safeWrite===true&&projection.writeIdentity===true)raw=value;return descriptor?coerceWrite(raw,descriptor.writeType):raw;}
  function describeValue(key,value,prefs,state){var item=expanded().preferences[String(key||'')];if(!item)return{key:String(key||''),title:humanize(key),description:'',kind:value!==null&&typeof value==='object'?'structured':typeof value,source:'unmapped',editable:false,structured:value!==null&&typeof value==='object',meta:{},descriptor:null,projection:null,gates:[]};var kind=semanticKind(item,value),display=toDisplay(key,value),rawCandidate=toRaw(key,display),meta={attributes:clone(item.attributes||{}),enum:clone(item.options||[]),unit:item.unit&&item.unit.source||'',unitRef:clone(item.unit),controlId:item.controlId||'',semantic:item.semantic||''};return{key:item.key,title:item.title&&item.title.source||humanize(key),description:item.description&&item.description.source||'',kind:kind,source:'native',editable:kind!=='structured'&&writeSafe(item,rawCandidate,prefs||{},state||prefs||{}),structured:kind==='structured',meta:meta,span:'1',descriptor:clone(item.descriptor),projection:clone(item.projection),gates:clone(item.gates||[]),dependencySatisfied:dependencySatisfied(item,state||prefs||{}),sourceRefs:{title:clone(item.title),description:clone(item.description),unit:clone(item.unit)}};}
  function group(tab,prefs){var data=expanded(),entry=data.byTab[String(tab||'')];if(!entry)return[];prefs=prefs||{};return entry.sections.map(function(section){var keys=section.keys.filter(function(key){return own(prefs,key);});return{id:section.id,title:section.title&&section.title.source||'',sourceRef:clone(section.title),keys:keys};}).filter(function(section){return section.keys.length;});}
  function keysFor(tab,prefs){return group(tab,prefs).flatMap(function(section){return section.keys;});}
  function bindRelease(release){boundRelease=release?clone(release):null;expandedCache=null;return api;}
  function isWritable(key,value,prefs,state){var item=expanded().preferences[String(key||'')];return !!(item&&writeSafe(item,value,prefs||{},state||prefs||{}));}
  function writableDraft(draft,prefs){draft=draft||{};prefs=prefs||{};var state=Object.assign({},prefs,draft),out={};Object.keys(draft).forEach(function(key){if(isWritable(key,draft[key],prefs,state))out[key]=draft[key];});return out;}
  function sourcePreference(key){var item=expanded().preferences[String(key||'')];return item?clone(item):null;}
  var api={nativeSurfaces:nativeSurfaces,tabTitle:tabTitle,tabTitleRef:tabTitleRef,describeValue:describeValue,toDisplay:toDisplay,toRaw:toRaw,group:group,keysFor:keysFor,humanize:humanize,bindRelease:bindRelease,loadCompatibility:loadCompatibility,isWritable:isWritable,writableDraft:writableDraft,sourcePreference:sourcePreference};
  W.SettingsSchema=api;
})(window);
