(function(global){
  'use strict';
  var W=global.WeiG,C=W&&W.Components,U=W&&W.util;
  if(!W||!C||!U||W.V037Settings)return;
  var VERSION='0.3.7',T=function(k,v){return W.V037Text?W.V037Text.t(k,v):k;};
  var STANDARD_META={
    listen_port:{unit:'port'},max_connec:{unit:'connections',minusOne:'Unlimited'},max_connec_per_torrent:{unit:'connections',minusOne:'Unlimited'},max_uploads:{unit:'slots',minusOne:'Unlimited'},max_uploads_per_torrent:{unit:'slots',minusOne:'Unlimited'},proxy_port:{unit:'port'},
    dl_limit:{unit:'KiB/s',scale:1024,zero:'Unlimited'},up_limit:{unit:'KiB/s',scale:1024,zero:'Unlimited'},alt_dl_limit:{unit:'KiB/s',scale:1024,zero:'Unlimited'},alt_up_limit:{unit:'KiB/s',scale:1024,zero:'Unlimited'},
    max_active_downloads:{unit:'torrents',minusOne:'Unlimited'},max_active_uploads:{unit:'torrents',minusOne:'Unlimited'},max_active_torrents:{unit:'torrents',minusOne:'Unlimited'},max_ratio:{unit:'ratio'},max_seeding_time:{unit:'min'},
    web_ui_port:{unit:'port'},web_ui_max_auth_fail_count:{unit:'attempts'},web_ui_ban_duration:{unit:'s'}
  };
  function specialText(value){var map={Unlimited:'unlimited',Disabled:'disabled','System default':'systemDefault','Permanent lease':'permanent'};return T(map[value]||value);}
  function titleUnit(title,unit){title=String(title||'').replace(/\s+\((?:B|KiB|MiB|GiB|TiB|PiB|s|ms|min|%|port|connections|connections\/s|threads|files|requests|KiB\/s|slots|torrents|attempts|ratio)\)$/,'');return unit?title+' ('+unit+')':title;}
  function displayValue(meta,raw){if(!meta||!meta.scale)return raw;var n=Number(raw);return Number.isFinite(n)?n/meta.scale:raw;}
  function rawValue(meta,value){if(!meta||!meta.scale)return U.parseScalar(value);var n=Number(value);return Number.isFinite(n)?Math.round(n*meta.scale):value;}

  var helpPopover=null,helpOwner=null,helpHideTimer=null;
  function ensureHelpPopover(){if(helpPopover)return helpPopover;helpPopover=document.createElement('div');helpPopover.id='setting-help-popover';helpPopover.className='setting-help-popover surface surface--floating';helpPopover.hidden=true;helpPopover.setAttribute('role','tooltip');var portal=document.getElementById('weigg-floating-layer');if(!portal){portal=document.createElement('div');portal.id='weigg-floating-layer';portal.className='weigg-floating-layer';portal.setAttribute('aria-live','off');document.body.appendChild(portal);}portal.appendChild(helpPopover);helpPopover.addEventListener('mouseenter',function(){clearTimeout(helpHideTimer);});helpPopover.addEventListener('mouseleave',scheduleHelpHide);return helpPopover;}
  function scheduleHelpHide(){clearTimeout(helpHideTimer);helpHideTimer=setTimeout(hideHelp,120);}
  function hideHelp(){if(helpPopover)helpPopover.hidden=true;if(helpOwner)helpOwner.setAttribute('aria-expanded','false');helpOwner=null;}
  function positionHelp(owner){var pop=ensureHelpPopover(),r=owner.getBoundingClientRect(),pr=pop.getBoundingClientRect(),vv=global.visualViewport,v={left:vv?vv.offsetLeft:0,top:vv?vv.offsetTop:0,width:vv?vv.width:document.documentElement.clientWidth,height:vv?vv.height:document.documentElement.clientHeight},left=Math.max(v.left+8,Math.min(v.left+v.width-pr.width-8,r.left+r.width/2-pr.width/2)),top=r.bottom+8;if(top+pr.height>v.top+v.height-8)top=Math.max(v.top+8,r.top-pr.height-8);pop.style.left=Math.round(left)+'px';pop.style.top=Math.round(top)+'px';}
  function showHelp(owner,data){
    clearTimeout(helpHideTimer);var pop=ensureHelpPopover();pop.textContent='';
    function line(cls,label,value){if(!value)return;var row=document.createElement('div');row.className=cls;var a=document.createElement('span');a.textContent=label;var b=document.createElement('strong');b.textContent=value;row.append(a,b);pop.appendChild(row);}
    if(data.translation)line('setting-help__translation',T('source'),data.translation+' · '+(data.translationSource==='qBittorrent official'?T('official'):T('weigg')));
    if(data.purpose)line('setting-help__purpose',T('purpose'),data.purpose);if(data.unit)line('setting-help__unit',T('unit'),data.unit);if(data.special&&data.special.length)line('setting-help__special',T('special'),data.special.join(' · '));if(!pop.children.length)return;
    if(helpOwner&&helpOwner!==owner)helpOwner.setAttribute('aria-expanded','false');helpOwner=owner;owner.setAttribute('aria-expanded','true');pop.hidden=false;positionHelp(owner);
  }
  function attachSettingHelp(row,key,meta,localizedBefore,descriptionBefore){
    var copy=row&&row.querySelector('.settings-row__copy'),strong=copy&&copy.querySelector('strong');if(!copy||!strong)return;
    var adv=W.AdvancedSettingsV036&&W.AdvancedSettingsV036.meta&&W.AdvancedSettingsV036.meta[key],official=W.SettingsOfficialV037,loc=W.V037Text&&W.V037Text.locale?W.V037Text.locale():'en',entry=official&&official.entries&&official.entries[key],english=entry&&entry.source?entry.source.replace(/\s*\[[^\]]+\]\s*:?\s*$/,'').replace(/:\s*$/,''):(W.SettingsSchema&&W.SettingsSchema.humanize?W.SettingsSchema.humanize(key):key),help=null;
    if(adv&&loc!=='en'){
      var resolved=official&&official.label?official.label(key,english):{text:english,source:'english'};strong.textContent=titleUnit(resolved.text,(adv&&adv.unit)||'');strong.title=strong.textContent;help=official&&official.help?official.help(key,english):null;
      if(!help&&localizedBefore&&localizedBefore!==english)help={translation:localizedBefore,translationSource:'WeiG explanation',purpose:descriptionBefore||'',sourceText:english};
      if(!help)help={translation:localizedBefore&&localizedBefore!==english?localizedBefore:english,translationSource:'WeiG explanation',purpose:descriptionBefore||'',sourceText:english};
    }
    var special=[];if(meta&&meta.zero)special.push('0 = '+specialText(meta.zero));if(meta&&meta.minusOne)special.push('-1 = '+specialText(meta.minusOne));if(adv&&adv.zero)special.push('0 = '+specialText(adv.zero));var unit=(adv&&adv.unit)||(meta&&meta.unit)||'';
    if(!help&&(special.length||unit))help={translation:'',translationSource:'',purpose:descriptionBefore||'',sourceText:english};if(!help)return;help.unit=unit;help.special=special;
    var titleLine=copy.querySelector('.setting-title-line');if(!titleLine){titleLine=document.createElement('span');titleLine.className='setting-title-line';copy.insertBefore(titleLine,strong);titleLine.appendChild(strong);}
    var button=titleLine.querySelector('.setting-help-button');if(!button){button=document.createElement('button');button.type='button';button.className='setting-help-button';button.textContent='ⓘ';button.setAttribute('aria-haspopup','true');button.setAttribute('aria-expanded','false');titleLine.appendChild(button);}
    button.__weiggHelp=help;button.onmouseenter=function(){showHelp(button,button.__weiggHelp);};button.onmouseleave=scheduleHelpHide;button.onfocus=function(){showHelp(button,button.__weiggHelp);};button.onblur=scheduleHelpHide;button.onclick=function(e){e.preventDefault();e.stopPropagation();if(helpPopover&&!helpPopover.hidden&&helpOwner===button)hideHelp();else showHelp(button,button.__weiggHelp);};
  }

  var basePreference=C.preferenceField;
  C.preferenceField=function(key,value,onChange,label){
    var std=STANDARD_META[key],adv=W.AdvancedSettingsV036&&W.AdvancedSettingsV036.meta&&W.AdvancedSettingsV036.meta[key],infoBefore=W.SettingsSchema&&W.SettingsSchema.describe?W.SettingsSchema.describe(key):null,row;
    if(std&&!adv)row=basePreference.call(this,key,displayValue(std,value),function(k,v){onChange(k,rawValue(std,v));},label);else row=basePreference.apply(this,arguments);
    var strong=row&&row.querySelector('.settings-row__copy strong'),small=row&&row.querySelector('.settings-row__copy small'),localizedBefore=strong&&strong.textContent||infoBefore&&infoBefore.title||key,descriptionBefore=small&&small.textContent||infoBefore&&infoBefore.description||'';
    if(std&&!adv&&strong){strong.textContent=titleUnit(strong.textContent,std.unit);strong.title=strong.textContent;}
    if(std&&small){var extras=[];if(std.zero)extras.push('0 = '+specialText(std.zero));if(std.minusOne)extras.push('-1 = '+specialText(std.minusOne));if(extras.length&&!extras.every(function(x){return small.textContent.indexOf(x)>=0;}))small.textContent=(small.textContent||'')+(small.textContent?' · ':'')+extras.join(' · ');}
    attachSettingHelp(row,key,std,localizedBefore,descriptionBefore);return row;
  };
  W.PreferenceSchemaV037={standard:STANDARD_META,displayValue:displayValue,rawValue:rawValue};

  var aboutButton=null,mobileSettingsSection=null,mobileSystemSection=null,systemTimer=null,initialized=false;
  function buildAboutCard(label,value,href){var card=document.createElement('div');card.className='about-kv setting-card';var copy=document.createElement('span');copy.className='settings-row__copy';var strong=document.createElement('strong');strong.textContent=label;var small=document.createElement('small');small.className='text-description';small.textContent=value;copy.append(strong,small);card.appendChild(copy);if(href){var a=document.createElement('a');a.className='btn btn--ghost about-link';a.href=href;a.target='_blank';a.rel='noopener noreferrer';a.textContent='↗';a.setAttribute('aria-label',label);card.appendChild(a);}return card;}
  function renderAbout(){var root=document.getElementById('settings-content');if(!root)return;root.textContent='';Array.from(document.querySelectorAll('#settings-tabs [data-settings-tab]')).forEach(function(b){b.classList.toggle('is-active',b.dataset.settingsTab==='about');});var save=document.getElementById('save-settings-btn');if(save)save.hidden=true;var group=document.createElement('div');group.className='settings-group about-grid';group.appendChild(C.sectionTitle('WeiG qB WebUI','WeiG / WeiG Share · Open-source Alternate WebUI for qBittorrent.'));var sha=(document.querySelector('meta[name="weigg-build-sha"]')||{}).content||'—';group.append(buildAboutCard(T('version'),VERSION),buildAboutCard(T('build'),sha),buildAboutCard(T('qb'),(document.getElementById('qb-version')||{}).textContent||'—'),buildAboutCard(T('api'),(document.getElementById('api-version')||{}).textContent||'—'),buildAboutCard(T('github'),'weigefenxiang/WeiG-qB-WebUI','https://github.com/weigefenxiang/WeiG-qB-WebUI'),buildAboutCard(T('blog'),'WeiG Share','https://www.weigshare.com/'),buildAboutCard(T('license'),'GNU GPL-3.0','https://github.com/weigefenxiang/WeiG-qB-WebUI/blob/main/LICENSE'));var legal=document.createElement('p');legal.className='text-description about-legal';legal.textContent='Copyright © 2026 Wei.G / WeiG Share. This program is free software under GNU GPL-3.0 and comes without warranty.';group.appendChild(legal);root.appendChild(group);}
  function syncMobileSettingsNav(){if(!mobileSettingsSection)return;var active=document.querySelector('#settings-tabs [data-settings-tab].is-active');Array.from(mobileSettingsSection.querySelectorAll('[data-mobile-settings-tab]')).forEach(function(b){b.classList.toggle('is-active',active&&b.dataset.mobileSettingsTab===active.dataset.settingsTab);});}
  function ensureAbout(){if(aboutButton)return;var tabs=document.getElementById('settings-tabs'),group=tabs&&tabs.querySelector('.settings-nav-group:last-child');if(!tabs||!group)return;aboutButton=document.createElement('button');aboutButton.type='button';aboutButton.className='nav-item';aboutButton.dataset.settingsTab='about';aboutButton.textContent=T('about');group.appendChild(aboutButton);tabs.addEventListener('click',function(e){var b=e.target.closest('[data-settings-tab]');if(!b)return;if(b.dataset.settingsTab==='about'){e.preventDefault();e.stopImmediatePropagation();renderAbout();syncMobileSettingsNav();}else{var save=document.getElementById('save-settings-btn');if(save)save.hidden=false;setTimeout(syncMobileSettingsNav,0);}},true);}
  function installMobileSettingsDrawer(){
    ensureAbout();if(mobileSettingsSection)return;var sidebar=document.getElementById('sidebar'),first=sidebar&&sidebar.querySelector('.sidebar__section');if(!sidebar||!first)return;
    mobileSettingsSection=document.createElement('div');mobileSettingsSection.className='sidebar__section v037-mobile-settings-nav';var title=document.createElement('div');title.className='eyebrow';title.textContent=T('settings');var nav=document.createElement('nav');nav.className='nav-list';
    Array.from(document.querySelectorAll('#settings-tabs [data-settings-tab]')).forEach(function(original){var b=document.createElement('button');b.type='button';b.className='nav-item';b.dataset.mobileSettingsTab=original.dataset.settingsTab;b.textContent=original.textContent;b.onclick=function(){original.click();W.Router.go('settings');var close=document.getElementById('drawer-scrim');if(close)close.click();};nav.appendChild(b);});mobileSettingsSection.append(title,nav);first.insertAdjacentElement('afterend',mobileSettingsSection);syncMobileSettingsNav();
    mobileSystemSection=document.createElement('div');mobileSystemSection.className='sidebar__section v037-mobile-system';var st=document.createElement('div');st.className='eyebrow';st.textContent=T('system');var body=document.createElement('div');body.className='v037-system-meta';mobileSystemSection.append(st,body);sidebar.appendChild(mobileSystemSection);
    function refresh(){body.textContent='';function add(k,v){if(!v)return;var row=document.createElement('div');row.className='meta-line';var a=document.createElement('span');a.textContent=k;var b=document.createElement('strong');b.textContent=v;row.append(a,b);body.appendChild(row);}add(T('qb'),(document.getElementById('qb-version')||{}).textContent);add(T('api'),(document.getElementById('api-version')||{}).textContent);var storage=document.querySelector('.status-storage'),zone=document.querySelector('[data-status-timezone]'),conn=document.getElementById('status-connection');add('Storage',storage&&storage.textContent.trim());add('Time',zone&&zone.textContent.trim());add('Network',conn&&conn.textContent.trim());}
    refresh();clearInterval(systemTimer);systemTimer=setInterval(refresh,5000);
  }
  function init(){if(initialized)return;initialized=true;ensureAbout();installMobileSettingsDrawer();global.addEventListener('resize',U.debounce(function(){if(helpOwner&&helpPopover&&!helpPopover.hidden)positionHelp(helpOwner);},80));global.addEventListener('weigg:languagechange',function(){hideHelp();if(aboutButton)aboutButton.textContent=T('about');if(mobileSettingsSection){mobileSettingsSection.remove();mobileSettingsSection=null;}if(mobileSystemSection){mobileSystemSection.remove();mobileSystemSection=null;}installMobileSettingsDrawer();var active=document.querySelector('#settings-tabs [data-settings-tab="about"].is-active');if(active)renderAbout();});}
  W.V037Settings={init:init,renderAbout:renderAbout,hideHelp:hideHelp,meta:STANDARD_META};
})(window);
