(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{},U=W.util||{};
  if(W.TorrentFieldRegistry)return;
  var MODES={NATIVE:'NATIVE',NORMALIZED:'NORMALIZED',DERIVED:'DERIVED',READ_ONLY:'READ_ONLY',UNAVAILABLE:'UNAVAILABLE',UNKNOWN:'UNKNOWN'};
  var DEFAULT_MOBILE=['state','progress','size','dlspeed','upspeed','eta'];
  var DEFAULT_DESKTOP=['name','size','progress','dlspeed','upspeed','eta','state'];
  var LAYOUT_VERSION=2,COLUMN_MIN_WIDTH=24;
  function formatTime(value){var n=Number(value);if(!Number.isFinite(n)||n<=0)return'—';var ms=n<1e12?n*1000:n;try{return W.Time&&W.Time.format?W.Time.format(ms,{dateStyle:'short',timeStyle:'short'}):new Date(ms).toLocaleString();}catch(_e){return new Date(ms).toLocaleString();}}
  function formatDuration(value){var s=Math.max(0,Number(value)||0),d=Math.floor(s/86400);s%=86400;var h=Math.floor(s/3600);s%=3600;var m=Math.floor(s/60);s=Math.floor(s%60);if(d)return d+'d '+h+'h';if(h)return h+'h '+m+'m';if(m)return m+'m '+s+'s';return s+'s';}
  var FIELDS=[
    {key:'name',sort:'name',en:'Name',zh:'名称',short:'Name',width:420,min:220},
    {key:'size',sort:'size',en:'Size',zh:'大小',short:'Size',width:105,min:80,format:function(t){return U.formatBytes(t.size);}},
    {key:'progress',sort:'progress',en:'Progress',zh:'进度',short:'%',width:220,min:145,format:function(t){return U.percent(t.progress)+'%';}},
    {key:'dlspeed',sort:'dlspeed',en:'Download',zh:'下载',short:'↓',width:110,min:86,configAliases:['dl'],format:function(t){return '↓ '+U.formatSpeed(t.dlspeed);}},
    {key:'upspeed',sort:'upspeed',en:'Upload',zh:'上传',short:'↑',width:110,min:86,configAliases:['up'],format:function(t){return '↑ '+U.formatSpeed(t.upspeed);}},
    {key:'eta',sort:'eta',en:'ETA',zh:'ETA',short:'ETA',width:90,min:70,format:function(t){return 'ETA '+U.formatEta(t.eta);}},
    {key:'state',sort:'state',en:'Status',zh:'状态',short:'State',width:125,min:96,configAliases:['status'],format:function(t){var C=W.Components,s=C&&C.state?C.state(t.state):null;return s?s[0]:String(t.state||'—');}},
    {key:'ratio',sort:'ratio',en:'Ratio',zh:'比率',short:'R',width:90,min:70,format:function(t){return U.formatRatio(t.ratio);}},
    {key:'tracker',sort:'tracker',en:'Tracker',zh:'Tracker',short:'Tracker',width:165,min:110,format:function(t){return U.trackerLabel(t.tracker);}},
    {key:'category',sort:'category',en:'Category',zh:'分类',short:'Cat',width:130,min:90,format:function(t){return t.category||'—';}},
    {key:'tags',sort:'tags',en:'Tags',zh:'标签',short:'Tags',width:150,min:100,format:function(t){return t.tags||'—';}},
    {key:'num_seeds',sort:'num_seeds',en:'Seeds',zh:'做种数',short:'S',width:90,min:68,format:function(t){return Number.isFinite(Number(t.num_seeds))?String(Number(t.num_seeds)):'—';}},
    {key:'num_leechs',sort:'num_leechs',en:'Peers',zh:'用户',short:'P',width:90,min:68,format:function(t){return Number.isFinite(Number(t.num_leechs))?String(Number(t.num_leechs)):'—';}},
    {key:'save_path',sort:'save_path',en:'Save path',zh:'保存路径',short:'Path',width:220,min:130,format:function(t){return t.save_path||'—';}},
    {key:'added_on',sort:'added_on',en:'Added',zh:'添加于',short:'Added',width:160,min:115,format:function(t){return formatTime(t.added_on);}},
    {key:'completion_on',sort:'completion_on',en:'Completed',zh:'完成于',short:'Done',width:160,min:115,format:function(t){return formatTime(t.completion_on);}},
    {key:'priority',sort:'priority',en:'Priority',zh:'优先级',short:'Prio',width:92,min:70,format:function(t){var n=Number(t.priority);return Number.isFinite(n)?String(n):'—';}}
  ];
  var FIELD_MAP={};FIELDS.forEach(function(f){FIELD_MAP[f.key]=f;(f.configAliases||[]).forEach(function(alias){FIELD_MAP[alias]=f;});});
  var NATIVE_ZH={
    priority:'#',name:'名称',selected_size:'选定大小',size:'总大小',progress:'进度',status:'状态',state:'状态',state_icon:'状态图标',num_seeds:'做种数',num_leechs:'用户',dlspeed:'下载速度',upspeed:'上传速度',eta:'剩余时间',ratio:'比率',category:'分类',tags:'标签',added_on:'添加于',completion_on:'完成于',tracker:'Tracker',dl_limit:'下载限制',up_limit:'上传限制',downloaded:'已下载',uploaded:'已上传',downloaded_session:'本次会话下载',uploaded_session:'本次会话上传',amount_left:'剩余',time_active:'活动时间',save_path:'保存路径',download_path:'保存路径不完整',completed:'已完成',ratio_limit:'比率限制',seen_complete:'最后完整可见',last_activity:'最近活动',availability:'可用性',infohash_v1:'信息哈希值 v1',infohash_v2:'信息哈希值 v2',popularity:'流行度'
  };
  var NATIVE_CAPTION_ZH={'Name':'名称','Selected Size':'选定大小','Total Size':'总大小','Size':'大小','Progress':'进度','Status':'状态','Seeds':'做种数','Peers':'用户','Down Speed':'下载速度','Up Speed':'上传速度','ETA':'剩余时间','Ratio':'比率','Category':'分类','Tags':'标签','Added On':'添加于','Completed On':'完成于','Tracker':'Tracker','Down Limit':'下载限制','Up Limit':'上传限制','Downloaded':'已下载','Uploaded':'已上传','Session Download':'本次会话下载','Session Upload':'本次会话上传','Amount Left':'剩余','Time Active':'活动时间','Save Path':'保存路径','Completed':'已完成','Ratio Limit':'比率限制','Last Seen Complete':'最后完整可见','Last Activity':'最近活动','Availability':'可用性','Incomplete Save Path':'保存路径不完整','Info Hash v1':'信息哈希值 v1','Info Hash v2':'信息哈希值 v2','Popularity':'流行度'};
  function canonical(key){var f=FIELD_MAP[String(key||'')];return f&&f.key||null;}
  function isZh(){return !!(W.I18n&&W.I18n.getLocale&&W.I18n.getLocale()==='zh-CN');}
  function label(field){field=typeof field==='string'?FIELD_MAP[field]:field;if(!field)return'';return isZh()?(field.zh||field.en||field.key):(field.en||field.zh||field.key);}
  function profileFields(profile){return profile&&Array.isArray(profile.torrentInfoFields)?profile.torrentInfoFields.map(String):null;}
  function currentProfile(){return W.CapabilityRegistry&&W.CapabilityRegistry.torrentFieldFacts?W.CapabilityRegistry.torrentFieldFacts():null;}
  function certifiedProfile(profile){return !!(profile&&profile.fallback!==true&&profile.officialWeiGSupport!==false&&Array.isArray(profile.torrentInfoFields));}
  function sourceColumns(profile){if(!certifiedProfile(profile)||!Array.isArray(profile.torrentTableColumns)||!profile.torrentTableColumns.length)return null;var seen={},out=[];profile.torrentTableColumns.forEach(function(raw){raw=raw||{};var key=String(raw.key||'').trim();if(!key||seen[key])return;seen[key]=true;out.push({key:key,caption:String(raw.caption||''),defaultWidth:Number.isFinite(Number(raw.defaultWidth))?Number(raw.defaultWidth):100,defaultVisible:raw.defaultVisible!==false,translation:raw.translation||null,dataProperties:Array.isArray(raw.dataProperties)?raw.dataProperties.map(String).filter(Boolean):[key]});});return out.length?out:null;}
  function normalizeSpec(spec){if(typeof spec==='string')spec={key:spec};spec=spec||{};return{key:String(spec.key||''),source:String(spec.source||spec.key||''),sourceAliases:Array.isArray(spec.sourceAliases)?spec.sourceAliases.map(String):[],derivedFrom:Array.isArray(spec.derivedFrom)?spec.derivedFrom.map(String):[]};}
  function resolveProvenance(spec,profile){var s=normalizeSpec(spec),p=profile===undefined?currentProfile():profile,fields=profileFields(p);if(!s.key)return{field:s.key,mode:MODES.UNKNOWN};if(!p||p.fallback===true||p.officialWeiGSupport===false||!fields)return{field:s.key,mode:MODES.UNKNOWN};if(s.source&&fields.indexOf(s.source)>=0)return{field:s.key,mode:MODES.NATIVE,sourceField:s.source};for(var i=0;i<s.sourceAliases.length;i++)if(fields.indexOf(s.sourceAliases[i])>=0)return{field:s.key,mode:MODES.NORMALIZED,sourceField:s.sourceAliases[i]};if(s.derivedFrom.length&&s.derivedFrom.every(function(key){return fields.indexOf(key)>=0;}))return{field:s.key,mode:MODES.DERIVED,derivedFrom:s.derivedFrom.slice()};return{field:s.key,mode:MODES.UNAVAILABLE};}
  function provenance(key,profile){var f=FIELD_MAP[String(key||'')];if(!f)return{field:String(key||''),mode:MODES.UNKNOWN};return resolveProvenance(f,profile);}
  function isAvailable(key,profile){var mode=provenance(key,profile).mode;return mode===MODES.NATIVE||mode===MODES.NORMALIZED||mode===MODES.DERIVED||mode===MODES.READ_ONLY;}
  function effectiveFields(profile){var p=profile===undefined?currentProfile():profile;if(!p)return FIELDS.slice();return FIELDS.filter(function(f){return isAvailable(f.key,p);});}
  function savedMobileFields(){var cfg=W.Config&&W.Config.load?W.Config.load():{},raw=Array.isArray(cfg.mobileFields)?cfg.mobileFields:[],out=[];raw.forEach(function(k){var c=canonical(k);if(c&&c!=='name'&&out.indexOf(c)<0)out.push(c);});return out.length?out:DEFAULT_MOBILE.slice();}
  function effectiveMobileFields(profile){var saved=savedMobileFields(),p=profile===undefined?currentProfile():profile;if(!p)return saved;return saved.filter(function(key){return isAvailable(key,p);});}
  function saveRawMobileFields(fields){var cfg=W.Config.load(),out=[];(fields||[]).forEach(function(k){var c=canonical(k);if(c&&c!=='name'&&out.indexOf(c)<0)out.push(c);});cfg.mobileFields=out;W.Config.save(cfg);return out;}
  function saveEffectiveMobileFields(fields,profile){var p=profile===undefined?currentProfile():profile,previous=savedMobileFields(),hidden=p?previous.filter(function(key){return !isAvailable(key,p);}):[],next=[];(fields||[]).concat(hidden).forEach(function(k){var c=canonical(k);if(c&&c!=='name'&&next.indexOf(c)<0)next.push(c);});return saveRawMobileFields(next);}
  function column(field){field=typeof field==='string'?FIELD_MAP[field]:field;if(!field)return null;return{key:field.key,label:label(field),width:field.width,min:COLUMN_MIN_WIDTH,sort:field.sort};}
  function normalizeColumnPreferences(raw){var out=[],seen={};(raw||[]).forEach(function(item){item=typeof item==='string'?{key:item}:item||{};var key=String(item.key||'');var c=canonical(key)||key;if(!c||seen[c])return;seen[c]=true;var pref={key:c};if(Number.isFinite(Number(item.width)))pref.width=Number(item.width);if(typeof item.visible==='boolean')pref.visible=item.visible;if(Number(item.layoutVersion)===LAYOUT_VERSION)pref.layoutVersion=LAYOUT_VERSION;out.push(pref);});return out;}
  function normalizeNativePreferences(raw){var out=[],seen={};(raw||[]).forEach(function(item){item=typeof item==='string'?{key:item}:item||{};var key=String(item.key||'');if(!key||seen[key])return;seen[key]=true;var pref={key:key};if(Number.isFinite(Number(item.width)))pref.width=Number(item.width);if(typeof item.visible==='boolean')pref.visible=item.visible;if(Number(item.layoutVersion)===LAYOUT_VERSION)pref.layoutVersion=LAYOUT_VERSION;out.push(pref);});return out;}
  function serializeNativeColumns(cols){var out=[],seen={};(cols||[]).forEach(function(item){item=item||{};var key=String(item.key||'');if(!key||seen[key])return;seen[key]=true;var pref={key:key};if(Number.isFinite(Number(item.width)))pref.width=Number(item.width);out.push(pref);});return out;}
  function defaultDesktopPreferences(){return DEFAULT_DESKTOP.map(function(key){return{key:key};});}
  function savedDesktopColumns(cfg){cfg=cfg||{};var raw=Array.isArray(cfg.columns)&&cfg.columns.length?cfg.columns:defaultDesktopPreferences();return normalizeColumnPreferences(raw);}
  function decorateColumnPreference(pref){var def=FIELD_MAP[pref&&pref.key],out=column(def);if(!out)return null;if(Number.isFinite(Number(pref.width)))out.width=Number(pref.width);return out;}
  function legacyEffectiveDesktopColumns(cfg,profile){var p=profile===undefined?currentProfile():profile,saved=savedDesktopColumns(cfg),out=saved.filter(function(pref){return !p||isAvailable(pref.key,p);}).map(decorateColumnPreference).filter(Boolean);if(out.length||p)return out;return saved.map(decorateColumnPreference).filter(Boolean);}
  function legacyKeyForColumn(col,columns){if(FIELD_MAP[col.key])return canonical(col.key)||col.key;var prop=(col.dataProperties||[])[0];if(prop&&FIELD_MAP[prop])return canonical(prop)||prop;return null;}
  function nativeKeyForLegacy(key,columns){var exact=columns.find(function(col){return col.key===key;});if(exact)return exact.key;var candidates=columns.filter(function(col){return (col.dataProperties||[])[0]===key;});var preferred=candidates.find(function(col){return !/_icon$/i.test(col.key)&&String(col.caption||'').trim();});return (preferred||candidates[0]||{}).key||null;}
  function isLayoutV2(raw){return Array.isArray(raw)&&raw.some(function(item){return item&&Number(item.layoutVersion)===LAYOUT_VERSION&&typeof item.visible==='boolean';});}
  function nativeLabel(col){var source=String(col&&col.translation&&col.translation.source||col&&col.caption||'').trim(),fallback=source||String(col&&col.key||'');if(!isZh())return fallback;if(NATIVE_ZH[col.key])return NATIVE_ZH[col.key];if(NATIVE_CAPTION_ZH[source])return NATIVE_CAPTION_ZH[source];return fallback;}
  function nativeMin(){return COLUMN_MIN_WIDTH;}
  function nativeSort(col,profile){var direct=FIELD_MAP[col.key];if(direct&&direct.sort)return direct.sort;var props=col.dataProperties||[];for(var i=0;i<props.length;i++){var semantic=FIELD_MAP[props[i]];if(semantic&&semantic.sort)return semantic.sort;}return null;}
  function nativeDefinition(col,pref,profile){var width=pref&&Number.isFinite(Number(pref.width))?Number(pref.width):Number(col.defaultWidth)||100;return{key:col.key,label:nativeLabel(col),width:width,min:nativeMin(col),sort:nativeSort(col,profile),native:true,defaultVisible:col.defaultVisible!==false,dataProperties:(col.dataProperties||[]).slice()};}
  function insertNewNativeKeys(nativeKeys,savedCurrent){var out=savedCurrent.slice();nativeKeys.forEach(function(key,index){if(out.indexOf(key)>=0)return;var inserted=false;for(var n=index+1;n<nativeKeys.length;n++){var next=out.indexOf(nativeKeys[n]);if(next>=0){out.splice(next,0,key);inserted=true;break;}}if(inserted)return;for(var p=index-1;p>=0;p--){var prev=out.indexOf(nativeKeys[p]);if(prev>=0){out.splice(prev+1,0,key);inserted=true;break;}}if(!inserted)out.push(key);});return out;}
  function migrateLegacyLayout(cfg,profile,columns){var raw=cfg&&Array.isArray(cfg.columns)?cfg.columns:null;if(!raw||!raw.length)return columns.map(function(col){return{key:col.key,width:Number(col.defaultWidth)||100,visible:col.defaultVisible!==false,layoutVersion:LAYOUT_VERSION};});var old=normalizeColumnPreferences(raw),activeLegacy=old.map(function(pref){return pref.key;}),widthByLegacy={};old.forEach(function(pref){if(Number.isFinite(Number(pref.width)))widthByLegacy[pref.key]=Number(pref.width);});var order=columns.map(function(col){return col.key;}),activeSlots=[];columns.forEach(function(col,index){var legacy=legacyKeyForColumn(col,columns);if(legacy&&activeLegacy.indexOf(legacy)>=0)activeSlots.push(index);});var orderedMapped=[];activeLegacy.forEach(function(key){var nativeKey=nativeKeyForLegacy(key,columns);if(nativeKey&&orderedMapped.indexOf(nativeKey)<0)orderedMapped.push(nativeKey);});activeSlots.forEach(function(slot,index){if(orderedMapped[index])order[slot]=orderedMapped[index];});var byKey={};columns.forEach(function(col){byKey[col.key]=col;});return order.map(function(key){var col=byKey[key],legacy=legacyKeyForColumn(col,columns),visible=legacy?activeLegacy.indexOf(legacy)>=0:col.defaultVisible!==false,width=legacy&&Number.isFinite(widthByLegacy[legacy])?widthByLegacy[legacy]:Number(col.defaultWidth)||100;return{key:key,width:width,visible:visible,layoutVersion:LAYOUT_VERSION};});}
  function nativeLayout(cfg,profile){var columns=sourceColumns(profile);if(!columns)return null;cfg=cfg||{};var raw=Array.isArray(cfg.columns)?cfg.columns:[];if(!isLayoutV2(raw))return migrateLegacyLayout(cfg,profile,columns);var normalized=normalizeNativePreferences(raw),currentKeys=columns.map(function(col){return col.key;}),currentSet=new Set(currentKeys),savedCurrent=normalized.map(function(pref){return pref.key;}).filter(function(key){return currentSet.has(key);}),order=insertNewNativeKeys(currentKeys,savedCurrent),prefByKey={};normalized.forEach(function(pref){prefByKey[pref.key]=pref;});var colByKey={};columns.forEach(function(col){colByKey[col.key]=col;});var current=order.map(function(key){var col=colByKey[key],pref=prefByKey[key]||{};return{key:key,width:Number.isFinite(Number(pref.width))?Number(pref.width):Number(col.defaultWidth)||100,visible:typeof pref.visible==='boolean'?pref.visible:col.defaultVisible!==false,layoutVersion:LAYOUT_VERSION};});var stale=normalized.filter(function(pref){return !currentSet.has(pref.key);}).map(function(pref){return{key:pref.key,width:pref.width,visible:pref.visible!==false,layoutVersion:LAYOUT_VERSION};});return current.concat(stale);}
  function currentNativeLayout(cfg,profile){var layout=nativeLayout(cfg,profile),columns=sourceColumns(profile);if(!layout||!columns)return null;var current=new Set(columns.map(function(col){return col.key;}));return layout.filter(function(pref){return current.has(pref.key);});}
  function effectiveDesktopColumns(cfg,profile){var p=profile===undefined?currentProfile():profile,columns=sourceColumns(p),layout=currentNativeLayout(cfg,p);if(columns&&layout){var byKey={};columns.forEach(function(col){byKey[col.key]=col;});return layout.filter(function(pref){return pref.visible!==false&&byKey[pref.key];}).map(function(pref){return nativeDefinition(byKey[pref.key],pref,p);});}return legacyEffectiveDesktopColumns(cfg,p);}
  function availableColumnDefinitions(profile){var p=profile===undefined?currentProfile():profile,columns=sourceColumns(p);if(columns){var cfg=W.Config&&W.Config.load?W.Config.load():{},layout=currentNativeLayout(cfg,p)||[],byKey={};columns.forEach(function(col){byKey[col.key]=col;});return layout.map(function(pref){return nativeDefinition(byKey[pref.key],pref,p);}).filter(Boolean);}return effectiveFields(p).map(column).filter(Boolean);}
  function serializeLegacyColumns(cols){return normalizeColumnPreferences((cols||[]).map(function(c){return{key:c&&c.key,width:c&&c.width};}));}
  function saveNativeLayout(cfg,layout){cfg=cfg||{};cfg.columns=(layout||[]).map(function(pref){var item={key:String(pref.key||''),visible:pref.visible!==false,layoutVersion:LAYOUT_VERSION};if(Number.isFinite(Number(pref.width)))item.width=Number(pref.width);return item;}).filter(function(item){return item.key;});if(W.Config&&W.Config.save)W.Config.save(cfg);return cfg.columns;}
  function saveRawDesktopColumns(cfg,cols){cfg=cfg||{};cfg.columns=serializeLegacyColumns(cols);if(W.Config&&W.Config.save)W.Config.save(cfg);return cfg.columns;}
  function sameKeySet(a,b){if(a.length!==b.length)return false;var set=new Set(a);return b.every(function(key){return set.has(key);});}
  function saveEffectiveDesktopColumns(cfg,cols,profile){var p=profile===undefined?currentProfile():profile,columns=sourceColumns(p),layout=nativeLayout(cfg,p);if(columns&&layout){var currentKeys=new Set(columns.map(function(col){return col.key;})),currentLayout=layout.filter(function(pref){return currentKeys.has(pref.key);}),stale=layout.filter(function(pref){return !currentKeys.has(pref.key);}),incoming=serializeNativeColumns(cols).filter(function(pref){return currentKeys.has(pref.key);}),incomingKeys=incoming.map(function(pref){return pref.key;}),oldVisible=currentLayout.filter(function(pref){return pref.visible!==false;}).map(function(pref){return pref.key;}),byKey={};currentLayout.forEach(function(pref){byKey[pref.key]=Object.assign({},pref);});incoming.forEach(function(pref){if(byKey[pref.key]&&Number.isFinite(Number(pref.width)))byKey[pref.key].width=Number(pref.width);});var incomingSet=new Set(incomingKeys);currentLayout.forEach(function(pref){byKey[pref.key].visible=incomingSet.has(pref.key);});var order=currentLayout.map(function(pref){return pref.key;});if(sameKeySet(oldVisible,incomingKeys)){var queue=incomingKeys.slice();order=order.map(function(key){return byKey[key].visible?queue.shift():key;});}var next=order.map(function(key){return byKey[key];}).concat(stale);saveNativeLayout(cfg,next);return effectiveDesktopColumns(cfg,p);}var previous=savedDesktopColumns(cfg),effective=serializeLegacyColumns(cols),queue=effective.slice(),next=[];previous.forEach(function(pref){if(p&&!isAvailable(pref.key,p)){next.push(pref);return;}if(queue.length)next.push(queue.shift());});next=next.concat(queue);saveRawDesktopColumns(cfg,next);return legacyEffectiveDesktopColumns(cfg,p);}
  function resetDesktopColumns(cfg,profile){var p=profile===undefined?currentProfile():profile,columns=sourceColumns(p);if(columns){var layout=columns.map(function(col){return{key:col.key,width:Number(col.defaultWidth)||100,visible:col.defaultVisible!==false,layoutVersion:LAYOUT_VERSION};});saveNativeLayout(cfg,layout);return effectiveDesktopColumns(cfg,p);}saveRawDesktopColumns(cfg,defaultDesktopPreferences());return legacyEffectiveDesktopColumns(cfg,p);}
  function genericNativeFormat(col){var key=col.key,source=(col.dataProperties||[])[0]||key;return function(t){var value=t&&t[source];if(value==null&&source!==key)value=t&&t[key];if(value==null)return'—';if(source==='state'||key==='status'||/_state$/.test(key)){var C=W.Components,s=C&&C.state?C.state(value):null;return s?s[0]:String(value||'—');}if(/^(selected_size|size|total_size|downloaded|uploaded|downloaded_session|uploaded_session|amount_left|completed)$/.test(source))return U.formatBytes(value);if(/^(dlspeed|upspeed|dl_limit|up_limit)$/.test(source))return U.formatSpeed(value);if(source==='progress')return U.percent(value)+'%';if(source==='eta')return U.formatEta(value);if(source==='time_active'||source==='seeding_time')return formatDuration(value);if(/^(added_on|completion_on|seen_complete|last_activity)$/.test(source))return formatTime(value);if(/^(ratio|ratio_limit|availability)$/.test(source))return U.formatRatio(value);if(source==='tracker')return U.trackerLabel(value);if(Array.isArray(value))return value.join(', ')||'—';if(typeof value==='boolean')return value?'✓':'—';return String(value||value===0?value:'—');};}
  function nativeField(key,profile){var p=profile===undefined?currentProfile():profile,columns=sourceColumns(p),col=columns&&columns.find(function(item){return item.key===key;});if(!col)return null;var known=FIELD_MAP[key];if(known)return known;var prop=(col.dataProperties||[])[0],semantic=FIELD_MAP[prop];if(semantic)return Object.assign({},semantic,{key:key,sort:nativeSort(col,p),format:semantic.format});return{key:key,sort:nativeSort(col,p),en:col.caption||key,zh:NATIVE_ZH[key]||col.caption||key,width:Number(col.defaultWidth)||100,min:nativeMin(col),format:genericNativeFormat(col)};}
  function syncDataGrid(){if(!W.DataGrid)return[];W.DataGrid.defaults=FIELDS.map(column);return W.DataGrid.defaults;}

  var api={modes:MODES,fields:FIELDS,get:function(key){return FIELD_MAP[String(key||'')]||nativeField(String(key||''));},canonical:canonical,label:label,column:column,syncDataGrid:syncDataGrid,resolveProvenance:resolveProvenance,provenance:provenance,isAvailable:isAvailable,effectiveFields:effectiveFields,savedMobileFields:savedMobileFields,mobileFields:effectiveMobileFields,effectiveMobileFields:effectiveMobileFields,saveMobileFields:saveRawMobileFields,saveEffectiveMobileFields:saveEffectiveMobileFields,savedDesktopColumns:savedDesktopColumns,effectiveDesktopColumns:effectiveDesktopColumns,availableColumnDefinitions:availableColumnDefinitions,saveRawDesktopColumns:saveRawDesktopColumns,saveEffectiveDesktopColumns:saveEffectiveDesktopColumns,resetDesktopColumns:resetDesktopColumns,sourceColumns:sourceColumns,nativeLayout:nativeLayout,layoutVersion:LAYOUT_VERSION,columnMinWidth:COLUMN_MIN_WIDTH};
  W.TorrentFieldRegistry=api;
  syncDataGrid();
})(window);
