(function(global){
  'use strict';
  var W=global.WeiG,C=W&&W.Components,U=W&&W.util,R=W&&W.TorrentFieldRegistry;
  if(!W||!C||!U||!R||W.UiSystem)return;
  var initialized=false,rssQuery='',FIELDS=R.fields||[];
  function mobile(){return !!(global.matchMedia&&global.matchMedia('(max-width:820px)').matches);}
  function zh(){return !!(W.I18n&&W.I18n.getLocale&&W.I18n.getLocale()==='zh-CN');}
  function label(en,cn){return zh()?cn:en;}
  function fieldLabel(f){return R.label(f);}
  function mobileFields(){return R.effectiveMobileFields?R.effectiveMobileFields():R.mobileFields();}
  function saveMobileFields(fields){return R.saveEffectiveMobileFields?R.saveEffectiveMobileFields(fields):R.saveMobileFields(fields);}
  function availableFields(){return R.effectiveFields?R.effectiveFields():FIELDS;}
  function relabelDataGrid(){if(R.syncDataGrid)R.syncDataGrid();}

  function columnTemplate(columns){return W.DataGrid&&W.DataGrid.template?W.DataGrid.template(columns):(columns||[]).map(function(column){return Math.max(Number(column.min)||24,Number(column.width)||140)+'px';}).join(' ');}
  function installSharedColumnInteraction(){if(!W.DataGridHeader||!W.DataGridHeader.bind)return;W.ColumnInteraction={attach:W.DataGridHeader.bind};W.DataGrid.addResizeHandles=W.DataGridHeader.bind;}
  installSharedColumnInteraction();

  function detailSurfaceId(surface){var map={files:'torrent-content',trackers:'torrent-trackers',peers:'torrent-peers',webseeds:'torrent-webseeds'};return map[String(surface||'')]||'';}
  function detailConfiguratorProvider(ctx){return{title:function(){return label('Columns','列设置');},columns:function(){return (ctx.resolved||[]).map(function(column){return Object.assign({},column,{visible:column.visible!==false,label:column.label||column.caption||column.key});});},commit:function(next){ctx.resolved=(next||[]).map(function(column){return Object.assign({},column);});W.SharedColumns.commit(ctx.tableId,ctx.source,ctx.resolved);ctx.apply(true);},reset:function(){W.SharedColumns.reset(ctx.tableId);ctx.resolved=W.SharedColumns.resolve(ctx.tableId,ctx.source);ctx.apply(true);}};}
  function registerDetailConfigurator(ctx){var id=detailSurfaceId(ctx&&ctx.surface);if(id&&W.ColumnConfigurator)W.ColumnConfigurator.register(id,detailConfiguratorProvider(ctx));return id;}
  function openDetailColumns(ctx){var id=registerDetailConfigurator(ctx);if(id&&W.ColumnConfigurator)W.ColumnConfigurator.open(id);}


  function renderPeerCountryFlag(cell,code,countryText){var iso=String(code||'').trim().toLowerCase();if(!/^[a-z]{2}$/.test(iso))return false;cell.textContent='';cell.classList.add('peer-country-cell');var icon=document.createElement('span');icon.className='flag '+iso+' peer-country-flag';icon.setAttribute('aria-hidden','true');var fallback=document.createElement('span');fallback.className='peer-country-code';fallback.textContent=iso.toUpperCase();fallback.setAttribute('aria-hidden','true');cell.append(icon,fallback);if(countryText&&countryText!=='—'){var name=document.createElement('span');name.textContent=countryText;cell.appendChild(name);}cell.setAttribute('aria-label',countryText&&countryText!=='—'?countryText:iso.toUpperCase());return true;}
  function detailSurface(tab){tab=String(tab||'');return['files','trackers','peers','webseeds'].indexOf(tab)>=0?tab:'';}
  function detailWidth(column){var key=String(column&&column.key||'').toLowerCase();if(/name|path|url|client|message|host/.test(key))return 240;if(/ip|country|connection/.test(key))return 170;if(/status|flags|priority/.test(key))return 125;if(/progress|speed|size|download|upload|peer|seed|leech|port/.test(key))return 110;return 135;}
  function sourceColumnKeys(column){return Array.isArray(column&&column.dataProperties)?column.dataProperties.map(String):[];}
  function detailValueSource(surface,column){var key=String(column&&column.key||''),keys=sourceColumnKeys(column);if(surface==='files'&&(key==='checked'||key==='remaining'))return'derived';if(key&&keys.indexOf(key)>=0)return'response';var scalar=keys.filter(function(name){return name!=='endpoints';});return scalar.length===1?'projection':'derived';}
  function detailSourceColumns(surface){var columns=W.QbUiEvidence&&W.QbUiEvidence.detailColumns?W.QbUiEvidence.detailColumns(surface):[];return columns.map(function(column){var out=Object.assign({},column);out.min=24;out.defaultWidth=Number(out.defaultWidth)||detailWidth(out);out.defaultVisible=out.defaultVisible!==false;out.valueSource=out.valueSource||detailValueSource(surface,out);return out;});}
  function owns(item,key){return !!(item&&Object.prototype.hasOwnProperty.call(item,key));}
  function derivedDetailValue(surface,item,column){var key=String(column&&column.key||''),keys=sourceColumnKeys(column);if(surface==='files'&&key==='checked'&&keys.length===1&&keys[0]==='priority'&&owns(item,'priority')){var priority=Number(item.priority);return{key:key,value:Number.isFinite(priority)?priority!==0:null,format:'checkbox'};}if(surface==='files'&&key==='remaining'&&keys.indexOf('size')>=0&&keys.indexOf('progress')>=0&&owns(item,'size')&&owns(item,'progress')){var size=Number(item.size),progress=Number(item.progress),priorityValue=(keys.indexOf('priority')>=0&&owns(item,'priority'))?Number(item.priority):null;if(Number.isFinite(size)&&Number.isFinite(progress)){var ratio=progress>1?progress/100:progress;ratio=Math.max(0,Math.min(1,ratio));return{key:key,value:(priorityValue===0)?0:Math.max(0,size*(1-ratio)),format:'bytes'};}}return{key:key,value:null,derived:true};}
  function projectedDetailValue(item,column){var key=String(column&&column.key||''),keys=sourceColumnKeys(column).filter(function(name){return name!=='endpoints';}),owned=keys.filter(function(name){return owns(item,name);});if(owned.length!==1)return{key:key,value:null,projected:true};return{key:key,sourceKey:owned[0],value:item[owned[0]],projected:true};}
  function propertyValue(surface,item,column){var key=String(column&&column.key||''),keys=sourceColumnKeys(column),valueSource=column&&column.valueSource||detailValueSource(surface,column);if(valueSource==='derived')return derivedDetailValue(surface,item,column);if(valueSource==='projection')return projectedDetailValue(item,column);if(keys.indexOf(key)<0||!owns(item,key))return{key:key,value:null};return{key:key,value:item[key]};}
  function formatDetailValue(surface,item,column){var found=propertyValue(surface,item,column),key=String(column&&column.key||found.key||'').toLowerCase(),value=found.value;if(value===undefined||value===null||value==='')return'—';if(found.format==='bytes')return U.formatBytes(Number(value));if(typeof value==='boolean')return value?label('Yes','是'):label('No','否');if(Array.isArray(value))return value.join(', ');if(surface==='trackers'){if(/^(?:peers|seeds|leeches|downloaded)$/.test(key)&&Number.isFinite(Number(value)))return Number(value)<0?'N/A':String(Number(value));if(/^(?:nextannounce|minannounce)$/.test(key)&&Number.isFinite(Number(value)))return U.formatEta(Number(value));return String(value);}if(/progress|availability/.test(key)&&Number.isFinite(Number(value))){var n=Number(value);return U.percent(n<=1?n:n/100)+'%';}if(/(?:^|_)(?:dl|up)_?speed$|speed/.test(key)&&Number.isFinite(Number(value)))return U.formatSpeed(Number(value));if(/size|remaining|downloaded|uploaded|amount_left|piece_size|completed/.test(key)&&Number.isFinite(Number(value)))return U.formatBytes(Number(value));if(/(?:^|_)(?:added_on|completion_on|addition_date|completion_date|last_activity|seen_complete)$/.test(key)&&Number(value)>0)return new Date(Number(value)*1000).toLocaleString();if(typeof value==='number'&&!Number.isFinite(value))return'—';return String(value);}
  function filePath(item,index){var raw=String(item&&item.name||'').replace(/\\/g,'/').replace(/^\/+|\/+$/g,'');return raw||('File '+(index+1));}
  function fileTreeBuild(items,state){
    var root={path:'',name:'',depth:-1,entries:[],size:0,done:0,priorities:[]},folders={'':root};
    function folder(path,depth){if(folders[path])return folders[path];var parts=path.split('/'),name=parts.pop(),parentPath=parts.join('/'),parent=folder(parentPath,depth-1),node={path:path,name:name,depth:depth,entries:[],size:0,done:0,priorities:[],parentPath:parentPath};folders[path]=node;parent.entries.push(node);return node;}
    (items||[]).forEach(function(source,index){var path=filePath(source,index),parts=path.split('/').filter(function(part){return part!=='.unwanted';}),base=parts.pop()||('File '+(index+1)),parentPath=parts.join('/'),parent=parentPath?folder(parentPath,parts.length-1):root,item=Object.assign({},source,{__weiggFileKind:'file',__weiggSourceIndex:index,__weiggPath:path,__weiggBaseName:base,__weiggDepth:parts.length,__weiggParentPath:parentPath}),size=Math.max(0,Number(source&&source.size)||0),progress=Number(source&&source.progress),priority=Number(source&&source.priority);if(!Number.isFinite(progress))progress=0;if(progress>1)progress/=100;progress=Math.max(0,Math.min(1,progress));item.__weiggDone=size*progress;parent.entries.push(item);for(var node=parent;node;node=node.parentPath!==undefined?folders[node.parentPath]:null){node.size+=size;node.done+=item.__weiggDone;if(Number.isFinite(priority))node.priorities.push(priority);if(node===root)break;}});
    Object.keys(folders).forEach(function(path){if(!path)return;var node=folders[path];if(!state.expanded.has(path))state.expanded.set(path,node.depth===0);});
    function folderPriority(node){if(!node.priorities.length)return 1;var first=node.priorities[0];return node.priorities.every(function(value){return value===first;})?first:-1;}
    function flattenNode(node,out){node.entries.forEach(function(entry){if(entry&&entry.__weiggFileKind==='file'){out.push(entry);return;}var child=entry,open=state.expanded.get(child.path)!==false,folderItem={__weiggFileKind:'folder',__weiggPath:child.path,__weiggBaseName:child.name,__weiggDepth:child.depth,__weiggParentPath:child.parentPath,name:child.path,size:child.size,progress:child.size?child.done/child.size:0,priority:folderPriority(child),__weiggExpanded:open};out.push(folderItem);if(open)flattenNode(child,out);});}
    var flat=[];flattenNode(root,flat);state.folders=folders;state.flat=flat;return flat;
  }
  function fileTreeKey(item,index){return item&&item.__weiggFileKind==='folder'?'folder:'+item.__weiggPath:item&&item.__weiggFileKind==='file'?'file:'+String(item.__weiggSourceIndex)+':'+item.__weiggPath:String(index);}
  function fileTreeVisibleAnchor(ctx){var instance=ctx&&ctx.instance,state=ctx&&ctx.fileTree;if(!instance||!state||!instance.items.length)return null;var head=instance._headerHeight?instance._headerHeight():0,top=Math.max(0,instance.el.scrollTop-head),index=instance._indexAtOffset?instance._indexAtOffset(top):Math.floor(top/instance.rowHeight),item=instance.items[Math.max(0,index)];return item?{key:fileTreeKey(item,index),offset:top-(index*instance.rowHeight)}:null;}
  function fileTreeScrollToKey(ctx,key,offset){var instance=ctx&&ctx.instance;if(!instance||!key)return false;var index=instance.items.findIndex(function(item,i){return fileTreeKey(item,i)===key;});if(index<0)return false;var head=instance._headerHeight?instance._headerHeight():0,top=head+index*instance.rowHeight+Math.max(0,Number(offset)||0);instance.el.__weiggVirtualScrollTop=top;instance.el.scrollTop=top;instance._lastScrollTop=top;instance._lastRange='';instance.render(true);return true;}
  function fileTreeToggle(ctx,item){var state=ctx.fileTree,path=item&&item.__weiggPath,instance=ctx.instance;if(!state||!path||!instance)return;var folderKey='folder:'+path,before=instance.items.findIndex(function(candidate,i){return fileTreeKey(candidate,i)===folderKey;}),headH=instance._headerHeight?instance._headerHeight():0,rowTop=before>=0?(instance.variableHeight?(instance.offsets[before]||0):before*instance.rowHeight):0,viewportY=headH+rowTop-instance.el.scrollTop,open=state.expanded.get(path)!==false;state.expanded.set(path,!open);state.baseSetItems(fileTreeBuild(state.raw,state),true);var after=instance.items.findIndex(function(candidate,i){return fileTreeKey(candidate,i)===folderKey;});if(after>=0){var nextTop=instance.variableHeight?(instance.offsets[after]||0):after*instance.rowHeight,target=Math.max(0,headH+nextTop-viewportY);instance.el.scrollTop=target;instance.el.__weiggVirtualScrollTop=target;instance._lastScrollTop=target;instance.render(true);}fileTreeUpdateSticky(ctx);}
  function renderFileTreeName(cell,item,ctx){var folder=item&&item.__weiggFileKind==='folder',wrap=document.createElement('span');wrap.className='detail-file-name';wrap.style.setProperty('--file-depth',String(Math.max(0,Number(item&&item.__weiggDepth)||0)));if(folder){var toggle=document.createElement('button');toggle.type='button';toggle.className='detail-file-toggle';toggle.setAttribute('aria-expanded',item.__weiggExpanded?'true':'false');toggle.setAttribute('aria-label',item.__weiggExpanded?label('Collapse folder','收起文件夹'):label('Expand folder','展开文件夹'));toggle.textContent=item.__weiggExpanded?'⌄':'›';toggle.onclick=function(e){e.preventDefault();e.stopPropagation();fileTreeToggle(ctx,item);};wrap.appendChild(toggle);}else{var spacer=document.createElement('span');spacer.className='detail-file-toggle';spacer.setAttribute('aria-hidden','true');wrap.appendChild(spacer);}var icon=document.createElement('span');icon.className='detail-file-icon';icon.setAttribute('aria-hidden','true');icon.textContent=folder?'📁':'▧';var text=document.createElement('span');text.className='detail-file-label';text.textContent=String(item&&item.__weiggBaseName||item&&item.name||'—');wrap.append(icon,text);cell.textContent='';cell.appendChild(wrap);cell.setAttribute('aria-label',String(item&&item.name||text.textContent));return true;}
  function fileTreeStickyRow(ctx,item){var row=document.createElement('div');row.className='shared-table__sticky-folder';row.style.gridTemplateColumns='var(--weigg-detail-grid-template)';ctx.visible.forEach(function(column){var cell=document.createElement('span');cell.dataset.columnKey=column.key;if(column.key==='name')renderFileTreeName(cell,item,ctx);row.appendChild(cell);});return row;}
  function fileTreeUpdateSticky(ctx){var state=ctx&&ctx.fileTree,instance=ctx&&ctx.instance;if(!state||!instance||!state.sticky)return;var anchor=fileTreeVisibleAnchor(ctx),item=null;if(anchor){var current=instance.items.find(function(candidate,i){return fileTreeKey(candidate,i)===anchor.key;}),parent=current&&current.__weiggParentPath;if(parent){var folderIndex=instance.items.findIndex(function(candidate){return candidate&&candidate.__weiggFileKind==='folder'&&candidate.__weiggPath===parent;}),visibleIndex=instance.items.indexOf(current);if(folderIndex>=0&&visibleIndex>folderIndex)item=instance.items[folderIndex];}}state.sticky.hidden=!item;state.sticky.textContent='';if(item){var fresh=fileTreeStickyRow(ctx,item);while(fresh.firstChild)state.sticky.appendChild(fresh.firstChild);}}
  function installFileTree(ctx,instance){if(!ctx||ctx.surface!=='files'||!instance||instance.__weiggFileTree)return;instance.__weiggFileTree=true;var state=ctx.fileTree={expanded:new Map(),folders:{},flat:[],raw:[],sticky:document.createElement('div')},baseSetItems=instance.setItems.bind(instance);state.baseSetItems=baseSetItems;state.sticky.className='shared-table__sticky-folder';state.sticky.hidden=true;instance.el.insertBefore(state.sticky,instance.spacer);instance.itemKey=fileTreeKey;instance.setItems=function(items,preserve){state.raw=Array.isArray(items)?items:[];return baseSetItems(fileTreeBuild(state.raw,state),preserve);};instance.el.addEventListener('scroll',function(){fileTreeUpdateSticky(ctx);},{passive:true});}
  function detailContextItems(surface,item,ctx,index,selectionCount){if(!ctx||typeof ctx.contextItems!=='function')return[];var items=ctx.contextItems(item,surface,index,selectionCount);return Array.isArray(items)?items.filter(function(action){return action&&String(action.label||'').trim()&&typeof action.onSelect==='function';}):[];}
  function selectDetailRow(row,ctx){if(!row||!ctx||!ctx.container)return;Array.from(ctx.container.querySelectorAll('.shared-table__row.is-selected')).forEach(function(node){node.classList.remove('is-selected');});row.classList.add('is-selected');}
  function attachDetailContextMenu(row,surface,item,index,ctx){if(!C.openContextMenu)return;row.addEventListener('click',function(){selectDetailRow(row,ctx);});var items=detailContextItems(surface,item,ctx,index,1);if(!items.length)return;row.dataset.contextMenu='true';row.addEventListener('contextmenu',function(e){selectDetailRow(row,ctx);e.preventDefault();e.stopPropagation();C.openContextMenu({x:e.clientX,y:e.clientY,items:items});});}
  function attachDetailViewportContextMenu(ctx){if(!C.openContextMenu||!ctx||!ctx.container||ctx.container.__weiggDetailContextMenu)return;ctx.container.__weiggDetailContextMenu=true;ctx.container.addEventListener('contextmenu',function(e){var row=e.target&&e.target.closest&&e.target.closest('.shared-table__row');if(row)return;var items=detailContextItems(ctx.surface,null,ctx,-1,0);if(!items.length)return;e.preventDefault();e.stopPropagation();C.openContextMenu({x:e.clientX,y:e.clientY,items:items});});}
  function mergeVisibleOrder(all,visible){var queue=visible.slice();return all.map(function(column){return column.visible===false?column:queue.shift();}).filter(Boolean);}
  function detailRow(item,index,ctx){var row=document.createElement('div'),folder=ctx.surface==='files'&&item&&item.__weiggFileKind==='folder',sourceIndex=ctx.surface==='files'&&item&&Number.isFinite(Number(item.__weiggSourceIndex))?Number(item.__weiggSourceIndex):index;row.className='shared-table__row';row.style.gridTemplateColumns='var(--weigg-detail-grid-template)';if(ctx.surface==='files'&&item&&item.__weiggFileKind)row.dataset.fileKind=item.__weiggFileKind;ctx.visible.forEach(function(column){var cell=document.createElement('span');cell.dataset.columnKey=column.key;var found=propertyValue(ctx.surface,item,column),handled=false,isUrl=found.key==='url'||column.key==='url';if(ctx.surface==='files'&&column.key==='name'&&item&&item.__weiggFileKind)handled=renderFileTreeName(cell,item,ctx);else if(!folder&&typeof ctx.cellRenderer==='function'){try{handled=ctx.cellRenderer({cell:cell,item:item,index:sourceIndex,column:column,found:found,surface:ctx.surface})===true;}catch(error){console.error('[WeiG detail cell]',error);}}if(!handled){if(folder&&(column.key==='checked'||column.key==='priority'))cell.textContent='';else if(ctx.surface==='files'&&column.key==='checked'&&found.format==='checkbox'){if(found.value===null)cell.textContent='—';else{var checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=!!found.value;checkbox.tabIndex=-1;checkbox.style.pointerEvents='none';checkbox.setAttribute('aria-hidden','true');cell.appendChild(checkbox);}}else{cell.textContent=formatDetailValue(ctx.surface,item,column);if(isUrl){cell.setAttribute('aria-label',cell.textContent);cell.style.whiteSpace='nowrap';cell.style.overflow='hidden';cell.style.textOverflow='ellipsis';}}}if(ctx.surface==='peers'&&column.key==='country'){var keys=sourceColumnKeys(column),codeKey=keys.find(function(name){return name==='country_code';}),flag=codeKey&&owns(item,codeKey)&&U.countryFlag?U.countryFlag(item[codeKey]):'',countryText=cell.textContent;if(flag)renderPeerCountryFlag(cell,item[codeKey],countryText);}row.appendChild(cell);});attachDetailContextMenu(row,ctx.surface,item,sourceIndex,ctx);return row;}
  function ensureDetailToolbar(ctx){var root=ctx.container.parentElement;if(!root)return;var toolbar=root.querySelector(':scope > .inline-form')||root.querySelector(':scope > .shared-table__toolbar');if(toolbar)toolbar.classList.add('shared-table__toolbar');else{toolbar=document.createElement('div');toolbar.className='shared-table__toolbar';root.insertBefore(toolbar,root.firstChild||ctx.container);}toolbar.dataset.detailSurface=ctx.surface;var button=toolbar.querySelector('[data-detail-columns]');if(!button){button=document.createElement('button');button.type='button';button.className='btn btn--ghost shared-table__columns-button';button.dataset.detailColumns=ctx.surface;button.textContent=label('Columns','列设置');button.onclick=function(){openDetailColumns(ctx);};toolbar.appendChild(button);}else button.onclick=function(){openDetailColumns(ctx);};var note=root.querySelector(':scope > .section-note');if(note&&note.parentElement===root){note.classList.add('shared-table__toolbar-note');toolbar.appendChild(note);}ctx.toolbar=toolbar;}
  function applyDetailColumns(ctx,rebuild){ctx.visible=ctx.resolved.filter(function(column){return column.visible!==false;});if(!ctx.visible.length&&ctx.resolved.length){ctx.resolved[0].visible=true;ctx.visible=[ctx.resolved[0]];}ctx.container.style.setProperty('--weigg-detail-grid-template',columnTemplate(ctx.visible));W.DataGridHeader.render(ctx.head,ctx.visible,{surfaceId:detailSurfaceId(ctx.surface),label:function(column){return column.label||column.caption||column.key;}});W.DataGrid.addResizeHandles(ctx.head,ctx.visible,function(visible,_save,reason){if(reason==='reorder')ctx.resolved=mergeVisibleOrder(ctx.resolved,visible);W.SharedColumns.commit(ctx.tableId,ctx.source,ctx.resolved);},{root:ctx.container,viewport:ctx.container,rowSelector:'.shared-table__row',cssVar:'--weigg-detail-grid-template'});W.DataGridHeader.refresh(ctx.head,ctx.visible);if(ctx.fileTree&&ctx.fileTree.sticky)ctx.fileTree.sticky.style.gridTemplateColumns='var(--weigg-detail-grid-template)';if(rebuild&&ctx.instance){ctx.instance._lastRange='';ctx.instance.render(true);fileTreeUpdateSticky(ctx);}}
  function prepareDetailVirtual(container,options){var app=W.AppState,surface=app&&detailSurface(app.detailTab);if(!surface||!container||!container.closest||!container.closest('#detail-content')||!W.QbUiEvidence||!W.SharedColumns)return null;var source=detailSourceColumns(surface);if(!source.length)return null;var tableId='torrent-detail-'+surface,resolved=W.SharedColumns.resolve(tableId,source),head=document.createElement('div'),ctx={surface:surface,tableId:tableId,source:source,resolved:resolved,visible:[],head:head,container:container,instance:null,contextItems:options&&options.detailContextItems,cellRenderer:options&&options.detailCellRenderer};ctx.apply=function(rebuild){applyDetailColumns(ctx,rebuild);};registerDetailConfigurator(ctx);head.className='shared-table__head';container.classList.add('shared-table__viewport');var next=Object.assign({},options||{});next.staticHead=head;next.renderRow=function(item,index){return detailRow(item,index,ctx);};applyDetailColumns(ctx,false);return{ctx:ctx,options:next};}
  function installDetailVirtualAdapter(){var Base=W.VirtualList;if(!Base||Base.__weiggSharedDetailAdapter)return;function SharedVirtualList(container,options){var prepared=prepareDetailVirtual(container,options),instance=new Base(container,prepared?prepared.options:options);if(prepared){prepared.ctx.instance=instance;if(prepared.ctx.surface==='files')installFileTree(prepared.ctx,instance);attachDetailViewportContextMenu(prepared.ctx);ensureDetailToolbar(prepared.ctx);applyDetailColumns(prepared.ctx,false);instance.__weiggSharedDetail=prepared.ctx;}return instance;}SharedVirtualList.prototype=Base.prototype;Object.keys(Base).forEach(function(key){SharedVirtualList[key]=Base[key];});SharedVirtualList.__weiggSharedDetailAdapter=true;W.VirtualList=SharedVirtualList;}
  installDetailVirtualAdapter();

  function detailTabKeys(){var ui=W.QbUiEvidence&&W.QbUiEvidence.detailUi&&W.QbUiEvidence.detailUi(),tabs=ui&&ui.tabs||{},raw=Array.isArray(ui&&ui.tabOrder)?ui.tabOrder:Object.keys(tabs);return raw.map(String).filter(function(key,index,list){return tabs[key]&&list.indexOf(key)===index;});}
  function syncDetailTabLabels(){if(!W.QbUiEvidence||!W.QbUiEvidence.detailUi||!W.QbUiEvidence.detailUi())return;var host=document.getElementById('detail-tabs')||document.querySelector('.detail-tabs'),keys=detailTabKeys();if(host&&keys.length){var route=W.Router&&W.Router.route?W.Router.route():{},active=route.name==='torrent'?(route.tab||keys[0]):(W.AppState&&W.AppState.detailTab)||keys[0];if(route.name==='torrent'&&route.tab&&keys.indexOf(route.tab)<0){var hash=W.AppState&&W.AppState.detailHash||decodeURIComponent(route.id||'');if(hash&&W.Router&&W.Router.detail){W.Router.detail(hash,keys[0]);return;}}host.textContent='';keys.forEach(function(key){var tab=document.createElement('button'),value=W.QbUiEvidence.detailTab(key);tab.type='button';tab.className='tab';tab.dataset.tab=key;tab.setAttribute('role','tab');tab.setAttribute('aria-selected',active===key?'true':'false');tab.classList.toggle('is-active',active===key);tab.textContent=value&&value!==key?value:key;tab.onclick=function(){var hash=W.AppState&&W.AppState.detailHash||decodeURIComponent(route.id||'');if(hash&&W.Router&&W.Router.detail)W.Router.detail(hash,key);};host.appendChild(tab);});}if(W.ColumnConfigurator&&W.ColumnConfigurator.refreshActive)W.ColumnConfigurator.refreshActive();}

  function fitRail(row){if(!row||!row.isConnected)return;var rail=row.querySelector('.mobile-card-meta--rail');if(!rail)return;var metricHost=rail.querySelector('.mobile-card-metrics'),metrics=Array.from(rail.querySelectorAll('.mobile-metric')),more=rail.querySelector('.mobile-metric-more');if(!metricHost||!more)return;metrics.forEach(function(x){x.hidden=false;});more.hidden=true;more.textContent='';var hidden=0;for(var i=metrics.length-1;i>=0&&metricHost.scrollWidth>metricHost.clientWidth;i--){metrics[i].hidden=true;hidden++;more.hidden=false;more.textContent='+'+hidden;}while(hidden&&metricHost.scrollWidth>metricHost.clientWidth){var visible=metrics.filter(function(x){return !x.hidden;});if(visible.length<=1)break;visible[visible.length-1].hidden=true;hidden++;more.textContent='+'+hidden;}row.dataset.hiddenMetrics=String(hidden);}
  function enforceMobileHeight(){if(!mobile())return;Array.from(document.querySelectorAll('.torrent-mobile-card--two-line')).forEach(fitRail);}


  function applyRSSQuery(root){root=root||document.getElementById('rss-content');if(!root)return;var q=rssQuery.trim().toLocaleLowerCase();Array.from(root.querySelectorAll('.tool-row')).forEach(function(row){row.hidden=!!q&&String(row.textContent||'').toLocaleLowerCase().indexOf(q)<0;});}
  function setRSSQuery(value){rssQuery=String(value||'');applyRSSQuery();}
  function clearRSSQuery(){if(!rssQuery)return;rssQuery='';applyRSSQuery();var input=document.getElementById('search-input');if(input&&W.Router&&W.Router.route&&W.Router.route().name==='rss')input.value='';}
  W.RSS={setQuery:setRSSQuery,query:function(){return rssQuery;},apply:applyRSSQuery};

  var columnDialog=null,columnButton=null,sortControl=null,rssDialog=null,rssOpenButton=null;
  function refreshList(){var app=W.AppState;if(app&&app.virtual&&app.virtual.render)app.virtual.render();setTimeout(enforceMobileHeight,30);}
  function columnSummary(){return mobileFields().length;}
  function ensureColumnDialog(){if(columnDialog)return columnDialog;columnDialog=W.DialogRuntime.create({id:'mobile-columns-dialog',className:'dialog surface surface--modal mobile-field-dialog',draggable:true});columnDialog.innerHTML='<div class="dialog__head"><div><div class="eyebrow">MOBILE VIEW</div><h2>'+label('Visible fields','显示字段')+'</h2></div><button type="button" class="icon-btn mobile-fields-close">×</button></div><div class="dialog__body"><div class="mobile-field-list"></div></div><div class="dialog__actions"><button type="button" class="btn btn--ghost mobile-fields-reset">'+label('Defaults','默认')+'</button><button type="button" class="btn btn--primary mobile-fields-done">'+label('Done','完成')+'</button></div>';columnDialog.querySelector('.mobile-fields-close').onclick=columnDialog.querySelector('.mobile-fields-done').onclick=function(){W.DialogRuntime.close(columnDialog);};columnDialog.querySelector('.mobile-fields-reset').onclick=function(){saveMobileFields(['state','progress','size','dlspeed','upspeed','eta']);renderColumnDialog();refreshList();};return columnDialog;}
  function renderColumnDialog(){var d=ensureColumnDialog(),root=d.querySelector('.mobile-field-list'),active=mobileFields();root.textContent='';availableFields().filter(function(f){return f.key!=='name';}).forEach(function(f){var row=document.createElement('div');row.className='mobile-field-row';var ck=document.createElement('input');ck.type='checkbox';ck.checked=active.indexOf(f.key)>=0;var text=document.createElement('span');text.textContent=fieldLabel(f);var controls=document.createElement('span');controls.className='mobile-field-order';var up=document.createElement('button');up.type='button';up.className='btn btn--ghost';up.textContent='↑';var down=document.createElement('button');down.type='button';down.className='btn btn--ghost';down.textContent='↓';function save(next){saveMobileFields(next);if(columnButton)columnButton.textContent=label('Columns ','列 ')+columnSummary();refreshList();renderColumnDialog();}ck.onchange=function(){var next=mobileFields(),i=next.indexOf(f.key);if(ck.checked&&i<0)next.push(f.key);if(!ck.checked&&i>=0)next.splice(i,1);save(next);};function move(dir){var next=mobileFields(),i=next.indexOf(f.key);if(i<0)return;var j=Math.max(0,Math.min(next.length-1,i+dir));if(i===j)return;var tmp=next[i];next[i]=next[j];next[j]=tmp;save(next);}up.onclick=function(){move(-1);};down.onclick=function(){move(1);};controls.append(up,down);row.append(ck,text,controls);root.appendChild(row);});}
  function sortOptions(){var out=[{value:'',label:label('Sort','排序')}];availableFields().forEach(function(f){out.push({value:f.key+':asc',label:fieldLabel(f)+' ↑'},{value:f.key+':desc',label:fieldLabel(f)+' ↓'});});return out;}
  function currentSortValue(){var state=W.LibraryController&&W.LibraryController.state?W.LibraryController.state():null;if(!state||!state.sort)return'';return state.sort+':' + (state.reverse?'desc':'asc');}
  function applySort(value){var parts=String(value||'').split(':'),key=parts[0],dir=parts[1]||'asc',f=R.get(key);if(!f||!R.isAvailable(f.key)||!W.LibraryController||!W.LibraryController.setSort)return Promise.resolve(false);return Promise.resolve(W.LibraryController.setSort(f.sort||f.key,dir));}
  function syncSortControl(){if(!sortControl)return;sortControl.setOptions(sortOptions());sortControl.setValue(currentSortValue());}
  function syncFieldControls(){if(columnButton)columnButton.textContent=label('Columns ','列 ')+columnSummary();syncSortControl();if(columnDialog&&columnDialog.open)renderColumnDialog();refreshList();}

  function syncRSSCopy(){var url=document.getElementById('rss-url'),add=document.getElementById('rss-add-btn'),title=rssDialog&&rssDialog.querySelector('.rss-add-dialog__title'),field=rssDialog&&rssDialog.querySelector('.rss-add-dialog__field-label'),cancel=rssDialog&&rssDialog.querySelector('.rss-add-dialog__cancel'),close=rssDialog&&rssDialog.querySelector('.rss-add-dialog__close');if(rssOpenButton)rssOpenButton.textContent=label('Add Feed','添加 Feed');if(add)add.textContent=label('Add','添加');if(title)title.textContent=label('Add RSS Feed','添加 RSS Feed');if(field)field.textContent=label('RSS Feed URL','RSS Feed URL');if(cancel)cancel.textContent=label('Cancel','取消');if(close)close.setAttribute('aria-label',label('Close','关闭'));if(url){url.placeholder=label('RSS Feed URL','RSS Feed URL');url.setAttribute('aria-label',label('RSS Feed URL','RSS Feed URL'));}}
  function installRSSControls(){if(document.getElementById('rss-add-open-btn'))return;var view=document.getElementById('rss-view'),header=view&&view.querySelector('.workspace__header'),form=view&&view.querySelector('.inline-form'),url=document.getElementById('rss-url'),add=document.getElementById('rss-add-btn'),refresh=document.getElementById('rss-refresh-btn');if(!view||!header||!form||!url||!add||!refresh)return;
    var actions=document.createElement('div');actions.className='rss-header-actions';rssOpenButton=document.createElement('button');rssOpenButton.id='rss-add-open-btn';rssOpenButton.type='button';rssOpenButton.className='btn btn--primary';rssOpenButton.addEventListener('click',function(){if(!rssDialog)return;W.DialogRuntime.open(rssDialog,{draggable:true,focus:url});setTimeout(function(){url.focus();},20);});refresh.addEventListener('click',clearRSSQuery);actions.append(rssOpenButton,refresh);header.appendChild(actions);
    rssDialog=W.DialogRuntime.create({id:'rss-add-dialog',className:'dialog surface surface--modal rss-add-dialog',draggable:true});rssDialog.setAttribute('aria-labelledby','rss-add-dialog-title');var head=document.createElement('div');head.className='dialog__head';var headCopy=document.createElement('div');var eyebrow=document.createElement('div');eyebrow.className='eyebrow';eyebrow.textContent='RSS';var title=document.createElement('h2');title.id='rss-add-dialog-title';title.className='rss-add-dialog__title';headCopy.append(eyebrow,title);var close=document.createElement('button');close.type='button';close.className='icon-btn rss-add-dialog__close';close.textContent='×';close.onclick=function(){W.DialogRuntime.close(rssDialog);};head.append(headCopy,close);var body=document.createElement('div');body.className='dialog__body';var field=document.createElement('label');field.className='field rss-add-dialog__field';var fieldLabel=document.createElement('span');fieldLabel.className='rss-add-dialog__field-label';url.type='url';url.autocomplete='url';field.append(fieldLabel,url);body.appendChild(field);var dialogActions=document.createElement('div');dialogActions.className='dialog__actions';var cancel=document.createElement('button');cancel.type='button';cancel.className='btn btn--ghost rss-add-dialog__cancel';cancel.onclick=function(){W.DialogRuntime.close(rssDialog);};add.type='button';add.addEventListener('click',function(){if(url.value.trim()){clearRSSQuery();W.DialogRuntime.close(rssDialog);}});dialogActions.append(cancel,add);rssDialog.append(head,body,dialogActions);form.remove();syncRSSCopy();}

  function installMobileControls(){if(document.getElementById('mobile-view-controls'))return;var host=document.querySelector('#list-view .grid-toolbar>div:first-child');if(!host)return;var wrap=document.createElement('span');wrap.id='mobile-view-controls';wrap.className='mobile-view-controls';columnButton=document.createElement('button');columnButton.type='button';columnButton.className='btn btn--ghost mobile-columns-button';columnButton.textContent=label('Columns ','列 ')+columnSummary();columnButton.onclick=function(){renderColumnDialog();W.DialogRuntime.open(ensureColumnDialog(),{draggable:true});};sortControl=C.selectControl({value:'',options:sortOptions(),className:'mobile-sort-control',ariaLabel:label('Torrent sort','种子排序'),searchable:true,searchThreshold:20,onChange:function(value){if(value)applySort(value).catch(function(e){console.error('[WeiG mobile sort]',e);});}});wrap.append(columnButton,sortControl);var pageHost=document.getElementById('page-size-control');if(pageHost&&pageHost.nextSibling)host.insertBefore(wrap,pageHost.nextSibling);else host.appendChild(wrap);syncSortControl();}
  function init(){if(initialized)return;initialized=true;installRSSControls();installMobileControls();setTimeout(function(){installRSSControls();installMobileControls();syncDetailTabLabels();if(mobile()){refreshList();enforceMobileHeight();}syncSortControl();},650);global.addEventListener('resize',U.debounce(function(){enforceMobileHeight();},80));global.addEventListener('weigg:library-state',function(){enforceMobileHeight();syncSortControl();});global.addEventListener('weigg:capabilities-ready',function(){syncFieldControls();syncDetailTabLabels();});global.addEventListener('weigg:route-state',syncDetailTabLabels);global.addEventListener('weigg:languagechange',function(){relabelDataGrid();syncRSSCopy();syncFieldControls();syncDetailTabLabels();});}
  W.UiSystem={init:init,fields:FIELDS,fitMobileRail:fitRail,enforceMobileHeight:enforceMobileHeight,applySort:applySort,installRSSControls:installRSSControls,syncDetailTabLabels:syncDetailTabLabels};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
