(function(global){
  'use strict';
  var W=global.WeiG,C=W&&W.Components,U=W&&W.util,R=W&&W.TorrentFieldRegistry;
  if(!W||!C||!U||!R||W.UiSystem)return;
  var initialized=false,rssQuery='',FIELDS=R.fields||[];
  function mobile(){return !!(global.matchMedia&&global.matchMedia('(max-width:820px)').matches);}
  function zh(){return !!(W.I18n&&W.I18n.getLocale&&W.I18n.getLocale()==='zh-CN');}
  function label(en,cn){return zh()?cn:en;}
  function fieldLabel(f){return R.label(f);}
  function mobileFields(){return R.effectiveMobileFields?R.effectiveMobileFields():R.mobileFields();}
  function saveMobileFields(fields){return R.saveEffectiveMobileFields?R.saveEffectiveMobileFields(fields):R.saveMobileFields(fields);}
  function availableFields(){return R.effectiveFields?R.effectiveFields():FIELDS;}
  function relabelDataGrid(){if(R.syncDataGrid)R.syncDataGrid();}

  function columnTemplate(columns){return W.DataGrid&&W.DataGrid.template?W.DataGrid.template(columns):(columns||[]).map(function(column){return Math.max(Number(column.min)||24,Number(column.width)||140)+'px';}).join(' ');}
  function installSharedColumnInteraction(){
    if(W.ColumnInteraction||!W.DataGrid)return;
    function attach(head,columns,onChange,options){
      options=options||{};var root=options.root||head.closest('.shared-table__viewport')||head.closest('.torrent-panel')||head.parentElement,cssVar=options.cssVar||((head.classList.contains('shared-table__head'))?'--weigg-detail-grid-template':'--weigg-grid-template'),rowSelector=options.rowSelector||(head.classList.contains('shared-table__head')?'.shared-table__row':'.torrent-row'),viewport=options.viewport||((head.parentElement&&head.parentElement.scrollWidth>head.parentElement.clientWidth)?head.parentElement:root);
      function setTemplate(){var template=columnTemplate(columns);if(root)root.style.setProperty(cssVar,template);head.style.gridTemplateColumns='var('+cssVar+')';return template;}
      function bindRows(){if(!root)return;Array.from(root.querySelectorAll(rowSelector)).forEach(function(row){row.style.gridTemplateColumns='var('+cssVar+')';});}
      function notify(reason){W.DataGrid._suppressVirtualRender=true;try{if(onChange)onChange(columns,true,reason);}finally{W.DataGrid._suppressVirtualRender=false;}}
      function clearDrop(){Array.from(head.querySelectorAll('.grid-head-cell')).forEach(function(cell){cell.style.boxShadow='';cell.style.opacity='';cell.classList.remove('is-column-dragging');});}
      function reorderRows(oldKeys){if(!root)return;Array.from(root.querySelectorAll(rowSelector)).forEach(function(row){var children=Array.from(row.children),byKey={};oldKeys.forEach(function(key,index){if(children[index])byKey[key]=children[index];});columns.forEach(function(column){if(byKey[column.key])row.appendChild(byKey[column.key]);});});}
      function commitReorder(sourceKey,targetKey,before){var oldKeys=columns.map(function(column){return column.key;}),si=columns.findIndex(function(column){return column.key===sourceKey;}),ti=columns.findIndex(function(column){return column.key===targetKey;});if(si<0||ti<0||si===ti)return false;var moved=columns.splice(si,1)[0];ti=columns.findIndex(function(column){return column.key===targetKey;});columns.splice(before?ti:ti+1,0,moved);columns.forEach(function(column){var node=Array.from(head.querySelectorAll('.grid-head-cell')).find(function(cell){return cell.dataset.key===column.key;});if(node)head.appendChild(node);});reorderRows(oldKeys);setTemplate();notify('reorder');return true;}
      function autoScroll(pointerX){if(!viewport||viewport.scrollWidth<=viewport.clientWidth)return;var rect=viewport.getBoundingClientRect(),edge=Math.min(48,Math.max(26,rect.width*.08));if(pointerX<rect.left+edge)viewport.scrollLeft=Math.max(0,viewport.scrollLeft-18);else if(pointerX>rect.right-edge)viewport.scrollLeft=Math.min(viewport.scrollWidth-viewport.clientWidth,viewport.scrollLeft+18);}
      setTemplate();bindRows();
      Array.from(head.querySelectorAll('.grid-head-cell')).forEach(function(cell){
        var handle=document.createElement('span');handle.className='col-resize';handle.setAttribute('aria-hidden','true');cell.appendChild(handle);
        handle.addEventListener('pointerdown',function(e){e.preventDefault();e.stopPropagation();var key=cell.dataset.key,current=columns.find(function(column){return column.key===key;}),startX=e.clientX,startW=current&&current.width||100,pointerId=e.pointerId;bindRows();if(handle.setPointerCapture)try{handle.setPointerCapture(pointerId);}catch(_e){}function move(ev){if(ev.pointerId!==pointerId)return;var active=columns.find(function(column){return column.key===key;});if(!active)return;active.width=Math.max(active.min||24,startW+(ev.clientX-startX));setTemplate();}function up(ev){if(ev.pointerId!==pointerId)return;if(handle.hasPointerCapture&&handle.hasPointerCapture(pointerId))try{handle.releasePointerCapture(pointerId);}catch(_e){}global.removeEventListener('pointermove',move,true);global.removeEventListener('pointerup',up,true);global.removeEventListener('pointercancel',up,true);notify('resize');}global.addEventListener('pointermove',move,true);global.addEventListener('pointerup',up,true);global.addEventListener('pointercancel',up,true);});
        var drag=null,longPress=0;
        cell.addEventListener('click',function(e){if(cell.__weiggSuppressSort){cell.__weiggSuppressSort=false;e.preventDefault();e.stopImmediatePropagation();}},true);
        cell.addEventListener('pointerdown',function(e){if((e.pointerType!=='touch'&&e.button!==0)||e.target.closest('.col-resize'))return;drag={id:e.pointerId,key:cell.dataset.key,startX:e.clientX,startY:e.clientY,active:false,armed:e.pointerType!=='touch',target:null,before:true};if(drag.armed&&cell.setPointerCapture)cell.setPointerCapture(e.pointerId);if(e.pointerType==='touch'){clearTimeout(longPress);longPress=setTimeout(function(){if(!drag||drag.id!==e.pointerId)return;drag.armed=true;drag.active=true;cell.classList.add('is-column-dragging');if(cell.setPointerCapture)try{cell.setPointerCapture(e.pointerId);}catch(_e){}},280);}});
        cell.addEventListener('pointermove',function(e){if(!drag||drag.id!==e.pointerId)return;var distance=Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY);if(!drag.armed){if(distance>8){clearTimeout(longPress);drag=null;}return;}if(!drag.active){if(distance<7)return;drag.active=true;cell.classList.add('is-column-dragging');}e.preventDefault();autoScroll(e.clientX);clearDrop();cell.style.opacity='.56';cell.classList.add('is-column-dragging');var hit=document.elementFromPoint(e.clientX,e.clientY),target=hit&&hit.closest&&hit.closest('.grid-head-cell');if(!target||target.parentElement!==head||target===cell){drag.target=null;return;}drag.target=target.dataset.key;drag.before=e.clientX<target.getBoundingClientRect().left+target.getBoundingClientRect().width/2;target.style.boxShadow=drag.before?'inset 2px 0 var(--accent-primary)':'inset -2px 0 var(--accent-primary)';});
        function finish(e){clearTimeout(longPress);if(!drag||drag.id!==e.pointerId)return;var state=drag;drag=null;if(cell.hasPointerCapture&&cell.hasPointerCapture(e.pointerId))cell.releasePointerCapture(e.pointerId);clearDrop();if(state.active){cell.__weiggSuppressSort=true;if(state.target)commitReorder(state.key,state.target,state.before);}}
        cell.addEventListener('pointerup',finish);cell.addEventListener('pointercancel',finish);
      });
      return columns;
    }
    W.ColumnInteraction={attach:attach};
    W.DataGrid.addResizeHandles=function(head,columns,onChange,options){return attach(head,columns,onChange,options);};
  }
  installSharedColumnInteraction();

  var sharedColumnDialog=null,sharedColumnContext=null;
  function ensureSharedColumnDialog(){
    if(sharedColumnDialog)return sharedColumnDialog;var dialog=document.createElement('dialog');dialog.id='shared-column-dialog';dialog.className='dialog surface surface--modal shared-column-dialog';dialog.innerHTML='<div class="dialog__head"><div><div class="eyebrow">TABLE</div><h2 class="shared-column-dialog__title"></h2></div><button type="button" class="icon-btn shared-column-dialog__close">×</button></div><div class="dialog__body"><div class="shared-column-settings"></div></div><div class="dialog__actions"><button type="button" class="btn btn--ghost shared-column-dialog__reset"></button><button type="button" class="btn btn--primary shared-column-dialog__done"></button></div>';dialog.querySelector('.shared-column-dialog__close').onclick=dialog.querySelector('.shared-column-dialog__done').onclick=function(){dialog.close();};dialog.querySelector('.shared-column-dialog__reset').onclick=function(){if(!sharedColumnContext)return;W.SharedColumns.reset(sharedColumnContext.tableId);sharedColumnContext.resolved=W.SharedColumns.resolve(sharedColumnContext.tableId,sharedColumnContext.source);sharedColumnContext.apply(true);renderSharedColumnDialog();};document.body.appendChild(dialog);sharedColumnDialog=dialog;return dialog;
  }
  function renderSharedColumnDialog(){var dialog=ensureSharedColumnDialog(),ctx=sharedColumnContext;if(!ctx)return;dialog.querySelector('.shared-column-dialog__title').textContent=label('Columns','列设置');dialog.querySelector('.shared-column-dialog__reset').textContent=label('Reset','恢复默认');dialog.querySelector('.shared-column-dialog__done').textContent=label('Done','完成');var root=dialog.querySelector('.shared-column-settings');root.textContent='';ctx.resolved.forEach(function(column,index){var row=document.createElement('div');row.className='shared-column-settings__row';var check=document.createElement('input');check.type='checkbox';check.checked=column.visible!==false;check.setAttribute('aria-label',column.label||column.caption||column.key);var text=document.createElement('span');text.textContent=column.label||column.caption||column.key;var controls=document.createElement('span');controls.className='shared-column-settings__order';var up=document.createElement('button');up.type='button';up.className='btn btn--ghost';up.textContent='↑';up.disabled=index===0;var down=document.createElement('button');down.type='button';down.className='btn btn--ghost';down.textContent='↓';down.disabled=index===ctx.resolved.length-1;check.onchange=function(){column.visible=check.checked;W.SharedColumns.commit(ctx.tableId,ctx.source,ctx.resolved);ctx.apply(true);renderSharedColumnDialog();};function move(delta){var at=ctx.resolved.indexOf(column),next=Math.max(0,Math.min(ctx.resolved.length-1,at+delta));if(at===next)return;ctx.resolved.splice(at,1);ctx.resolved.splice(next,0,column);W.SharedColumns.commit(ctx.tableId,ctx.source,ctx.resolved);ctx.apply(true);renderSharedColumnDialog();}up.onclick=function(){move(-1);};down.onclick=function(){move(1);};controls.append(up,down);row.append(check,text,controls);root.appendChild(row);});}
  function openSharedColumnDialog(ctx){sharedColumnContext=ctx;renderSharedColumnDialog();var dialog=ensureSharedColumnDialog();if(!dialog.open)dialog.showModal();}
  W.SharedColumnSettings={open:openSharedColumnDialog};

  function detailSurface(tab){tab=String(tab||'');return['files','trackers','peers','webseeds'].indexOf(tab)>=0?tab:'';}
  function detailWidth(column){var key=String(column&&column.key||'').toLowerCase();if(/name|path|url|client|message|host/.test(key))return 240;if(/ip|country|connection/.test(key))return 170;if(/status|flags|priority/.test(key))return 125;if(/progress|speed|size|download|upload|peer|seed|leech|port/.test(key))return 110;return 135;}
  function sourceColumnKeys(column){return Array.isArray(column&&column.dataProperties)?column.dataProperties.map(String):[];}
  function detailValueSource(surface,column){var key=String(column&&column.key||''),keys=sourceColumnKeys(column);if(surface==='files'&&(key==='checked'||key==='remaining'))return'derived';if(key&&keys.indexOf(key)>=0)return'response';var scalar=keys.filter(function(name){return name!=='endpoints';});return scalar.length===1?'projection':'derived';}
  function detailSourceColumns(surface){var columns=W.QbUiEvidence&&W.QbUiEvidence.detailColumns?W.QbUiEvidence.detailColumns(surface):[];return columns.map(function(column){var out=Object.assign({},column);out.min=24;out.defaultWidth=Number(out.defaultWidth)||detailWidth(out);out.defaultVisible=out.defaultVisible!==false;out.valueSource=out.valueSource||detailValueSource(surface,out);return out;});}
  function owns(item,key){return !!(item&&Object.prototype.hasOwnProperty.call(item,key));}
  function derivedDetailValue(surface,item,column){var key=String(column&&column.key||''),keys=sourceColumnKeys(column);if(surface==='files'&&key==='checked'&&keys.length===1&&keys[0]==='priority'&&owns(item,'priority')){var priority=Number(item.priority);return{key:key,value:Number.isFinite(priority)?priority!==0:null,format:'checkbox'};}if(surface==='files'&&key==='remaining'&&keys.indexOf('size')>=0&&keys.indexOf('progress')>=0&&owns(item,'size')&&owns(item,'progress')){var size=Number(item.size),progress=Number(item.progress),priorityValue=(keys.indexOf('priority')>=0&&owns(item,'priority'))?Number(item.priority):null;if(Number.isFinite(size)&&Number.isFinite(progress)){var ratio=progress>1?progress/100:progress;ratio=Math.max(0,Math.min(1,ratio));return{key:key,value:(priorityValue===0)?0:Math.max(0,size*(1-ratio)),format:'bytes'};}}return{key:key,value:null,derived:true};}
  function projectedDetailValue(item,column){var key=String(column&&column.key||''),keys=sourceColumnKeys(column).filter(function(name){return name!=='endpoints';}),owned=keys.filter(function(name){return owns(item,name);});if(owned.length!==1)return{key:key,value:null,projected:true};return{key:key,sourceKey:owned[0],value:item[owned[0]],projected:true};}
  function propertyValue(surface,item,column){var key=String(column&&column.key||''),keys=sourceColumnKeys(column),valueSource=column&&column.valueSource||detailValueSource(surface,column);if(valueSource==='derived')return derivedDetailValue(surface,item,column);if(valueSource==='projection')return projectedDetailValue(item,column);if(keys.indexOf(key)<0||!owns(item,key))return{key:key,value:null};return{key:key,value:item[key]};}
  function formatDetailValue(surface,item,column){var found=propertyValue(surface,item,column),key=String(column&&column.key||found.key||'').toLowerCase(),value=found.value;if(value===undefined||value===null||value==='')return'—';if(found.format==='bytes')return U.formatBytes(Number(value));if(typeof value==='boolean')return value?label('Yes','是'):label('No','否');if(Array.isArray(value))return value.join(', ');if(surface==='trackers'){if(/^(?:peers|seeds|leeches|downloaded)$/.test(key)&&Number.isFinite(Number(value)))return Number(value)<0?'N/A':String(Number(value));if(/^(?:nextannounce|minannounce)$/.test(key)&&Number.isFinite(Number(value)))return U.formatEta(Number(value));return String(value);}if(/progress|availability/.test(key)&&Number.isFinite(Number(value))){var n=Number(value);return U.percent(n<=1?n:n/100)+'%';}if(/(?:^|_)(?:dl|up)_?speed$|speed/.test(key)&&Number.isFinite(Number(value)))return U.formatSpeed(Number(value));if(/size|remaining|downloaded|uploaded|amount_left|piece_size|completed/.test(key)&&Number.isFinite(Number(value)))return U.formatBytes(Number(value));if(/(?:^|_)(?:added_on|completion_on|addition_date|completion_date|last_activity|seen_complete)$/.test(key)&&Number(value)>0)return new Date(Number(value)*1000).toLocaleString();if(typeof value==='number'&&!Number.isFinite(value))return'—';return String(value);}
  function detailContextItems(surface,item,ctx){if(!ctx||typeof ctx.contextItems!=='function')return[];var items=ctx.contextItems(item,surface);return Array.isArray(items)?items.filter(function(action){return action&&String(action.label||'').trim()&&typeof action.onSelect==='function';}):[];}
  function attachDetailContextMenu(row,surface,item,ctx){if(!C.openContextMenu)return;var items=detailContextItems(surface,item,ctx);if(!items.length)return;row.dataset.contextMenu='true';row.addEventListener('contextmenu',function(e){e.preventDefault();e.stopPropagation();C.openContextMenu({x:e.clientX,y:e.clientY,items:items});});}
  function mergeVisibleOrder(all,visible){var queue=visible.slice();return all.map(function(column){return column.visible===false?column:queue.shift();}).filter(Boolean);}
  function detailRow(item,index,ctx){var row=document.createElement('div');row.className='shared-table__row';row.style.gridTemplateColumns='var(--weigg-detail-grid-template)';ctx.visible.forEach(function(column){var cell=document.createElement('span');cell.dataset.columnKey=column.key;var found=propertyValue(ctx.surface,item,column),handled=false,isUrl=found.key==='url'||column.key==='url';if(typeof ctx.cellRenderer==='function'){try{handled=ctx.cellRenderer({cell:cell,item:item,index:index,column:column,found:found,surface:ctx.surface})===true;}catch(error){console.error('[WeiG detail cell]',error);}}if(!handled){if(ctx.surface==='files'&&column.key==='checked'&&found.format==='checkbox'){if(found.value===null){cell.textContent='—';}else{var checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=!!found.value;checkbox.tabIndex=-1;checkbox.style.pointerEvents='none';checkbox.setAttribute('aria-hidden','true');cell.appendChild(checkbox);}}else{cell.textContent=formatDetailValue(ctx.surface,item,column);cell.title=cell.textContent;if(isUrl){cell.style.whiteSpace='nowrap';cell.style.overflow='hidden';cell.style.textOverflow='ellipsis';}}}
      if(ctx.surface==='peers'&&column.key==='country'){var keys=sourceColumnKeys(column),codeKey=keys.find(function(name){return name==='country_code';}),flag=codeKey&&owns(item,codeKey)&&U.countryFlag?U.countryFlag(item[codeKey]):'';if(flag)cell.textContent=flag+(cell.textContent&&cell.textContent!=='—'?' '+cell.textContent:'');}
      row.appendChild(cell);});attachDetailContextMenu(row,ctx.surface,item,ctx);return row;}
  function ensureDetailToolbar(ctx){var root=ctx.container.parentElement;if(!root)return;var toolbar=root.querySelector(':scope > .inline-form')||root.querySelector(':scope > .shared-table__toolbar');if(toolbar)toolbar.classList.add('shared-table__toolbar');else{toolbar=document.createElement('div');toolbar.className='shared-table__toolbar';root.insertBefore(toolbar,root.firstChild||ctx.container);}toolbar.dataset.detailSurface=ctx.surface;var note=root.querySelector(':scope > .section-note');if(note&&note.parentElement===root){note.classList.add('shared-table__toolbar-note');toolbar.appendChild(note);}var button=toolbar.querySelector('[data-detail-columns]');if(!button){button=document.createElement('button');button.type='button';button.className='btn btn--ghost shared-table__columns-button';button.dataset.detailColumns=ctx.surface;button.textContent=label('Columns','列设置');button.onclick=function(){openSharedColumnDialog(ctx);};toolbar.appendChild(button);}else button.onclick=function(){openSharedColumnDialog(ctx);};ctx.toolbar=toolbar;}
  function applyDetailColumns(ctx,rebuild){ctx.visible=ctx.resolved.filter(function(column){return column.visible!==false;});if(!ctx.visible.length&&ctx.resolved.length){ctx.resolved[0].visible=true;ctx.visible=[ctx.resolved[0]];}ctx.head.textContent='';ctx.visible.forEach(function(column){var cell=document.createElement('span');cell.className='grid-head-cell';cell.dataset.key=column.key;cell.textContent=column.label||column.caption||column.key;ctx.head.appendChild(cell);});ctx.container.style.setProperty('--weigg-detail-grid-template',columnTemplate(ctx.visible));W.DataGrid.addResizeHandles(ctx.head,ctx.visible,function(visible,_save,reason){if(reason==='reorder')ctx.resolved=mergeVisibleOrder(ctx.resolved,visible);W.SharedColumns.commit(ctx.tableId,ctx.source,ctx.resolved);},{root:ctx.container,viewport:ctx.container,rowSelector:'.shared-table__row',cssVar:'--weigg-detail-grid-template'});if(rebuild&&ctx.instance){ctx.instance._lastRange='';ctx.instance.render(true);}}
  function prepareDetailVirtual(container,options){var app=W.AppState,surface=app&&detailSurface(app.detailTab);if(!surface||!container||!container.closest||!container.closest('#detail-content')||!W.QbUiEvidence||!W.SharedColumns)return null;var source=detailSourceColumns(surface);if(!source.length)return null;var tableId='torrent-detail-'+surface,resolved=W.SharedColumns.resolve(tableId,source),head=document.createElement('div'),ctx={surface:surface,tableId:tableId,source:source,resolved:resolved,visible:[],head:head,container:container,instance:null,contextItems:options&&options.detailContextItems,cellRenderer:options&&options.detailCellRenderer};ctx.apply=function(rebuild){applyDetailColumns(ctx,rebuild);};head.className='shared-table__head';container.classList.add('shared-table__viewport');var next=Object.assign({},options||{});next.staticHead=head;next.renderRow=function(item,index){return detailRow(item,index,ctx);};applyDetailColumns(ctx,false);return{ctx:ctx,options:next};}
  function installDetailVirtualAdapter(){var Base=W.VirtualList;if(!Base||Base.__weiggSharedDetailAdapter)return;function SharedVirtualList(container,options){var prepared=prepareDetailVirtual(container,options),instance=new Base(container,prepared?prepared.options:options);if(prepared){prepared.ctx.instance=instance;ensureDetailToolbar(prepared.ctx);applyDetailColumns(prepared.ctx,false);instance.__weiggSharedDetail=prepared.ctx;}return instance;}SharedVirtualList.prototype=Base.prototype;Object.keys(Base).forEach(function(key){SharedVirtualList[key]=Base[key];});SharedVirtualList.__weiggSharedDetailAdapter=true;W.VirtualList=SharedVirtualList;}
  installDetailVirtualAdapter();

  function detailTabKeys(){var ui=W.QbUiEvidence&&W.QbUiEvidence.detailUi&&W.QbUiEvidence.detailUi(),tabs=ui&&ui.tabs||{},raw=Array.isArray(ui&&ui.tabOrder)?ui.tabOrder:Object.keys(tabs);return raw.map(String).filter(function(key,index,list){return tabs[key]&&list.indexOf(key)===index;});}
  function syncDetailTabLabels(){if(!W.QbUiEvidence||!W.QbUiEvidence.detailUi||!W.QbUiEvidence.detailUi())return;var host=document.getElementById('detail-tabs')||document.querySelector('.detail-tabs'),keys=detailTabKeys();if(host&&keys.length){var route=W.Router&&W.Router.route?W.Router.route():{},active=route.name==='torrent'?(route.tab||keys[0]):(W.AppState&&W.AppState.detailTab)||keys[0];if(route.name==='torrent'&&route.tab&&keys.indexOf(route.tab)<0){var hash=W.AppState&&W.AppState.detailHash||decodeURIComponent(route.id||'');if(hash&&W.Router&&W.Router.detail){W.Router.detail(hash,keys[0]);return;}}host.textContent='';keys.forEach(function(key){var tab=document.createElement('button'),value=W.QbUiEvidence.detailTab(key);tab.type='button';tab.className='tab';tab.dataset.tab=key;tab.setAttribute('role','tab');tab.setAttribute('aria-selected',active===key?'true':'false');tab.classList.toggle('is-active',active===key);tab.textContent=value&&value!==key?value:key;tab.onclick=function(){var hash=W.AppState&&W.AppState.detailHash||decodeURIComponent(route.id||'');if(hash&&W.Router&&W.Router.detail)W.Router.detail(hash,key);};host.appendChild(tab);});}if(sharedColumnDialog&&sharedColumnDialog.open)renderSharedColumnDialog();}

  function fitRail(row){if(!row||!row.isConnected)return;var rail=row.querySelector('.mobile-card-meta--rail');if(!rail)return;var metricHost=rail.querySelector('.mobile-card-metrics'),metrics=Array.from(rail.querySelectorAll('.mobile-metric')),more=rail.querySelector('.mobile-metric-more');if(!metricHost||!more)return;metrics.forEach(function(x){x.hidden=false;});more.hidden=true;more.textContent='';var hidden=0;for(var i=metrics.length-1;i>=0&&metricHost.scrollWidth>metricHost.clientWidth;i--){metrics[i].hidden=true;hidden++;more.hidden=false;more.textContent='+'+hidden;}while(hidden&&metricHost.scrollWidth>metricHost.clientWidth){var visible=metrics.filter(function(x){return !x.hidden;});if(visible.length<=1)break;visible[visible.length-1].hidden=true;hidden++;more.textContent='+'+hidden;}row.dataset.hiddenMetrics=String(hidden);}
  function enforceMobileHeight(){if(!mobile())return;Array.from(document.querySelectorAll('.torrent-mobile-card--two-line')).forEach(fitRail);}

  function destructive(dialog){if(!dialog)return false;if(dialog.dataset.destructive==='true'||dialog.id==='delete-dialog')return true;return !!dialog.querySelector('.btn--danger');}
  function installDismissPolicy(){if(document.documentElement.dataset.weiggDismiss==='1')return;document.documentElement.dataset.weiggDismiss='1';document.addEventListener('dblclick',function(e){var d=e.target&&e.target.closest&&e.target.closest('dialog[open]');if(!d||e.target!==d||destructive(d))return;d.close();},{capture:true});}

  function applyRSSQuery(root){root=root||document.getElementById('rss-content');if(!root)return;var q=rssQuery.trim().toLocaleLowerCase();Array.from(root.querySelectorAll('.tool-row')).forEach(function(row){row.hidden=!!q&&String(row.textContent||'').toLocaleLowerCase().indexOf(q)<0;});}
  function setRSSQuery(value){rssQuery=String(value||'');applyRSSQuery();}
  function clearRSSQuery(){if(!rssQuery)return;rssQuery='';applyRSSQuery();var input=document.getElementById('search-input');if(input&&W.Router&&W.Router.route&&W.Router.route().name==='rss')input.value='';}
  W.RSS={setQuery:setRSSQuery,query:function(){return rssQuery;},apply:applyRSSQuery};

  var columnDialog=null,columnButton=null,sortControl=null,rssDialog=null,rssOpenButton=null;
  function refreshList(){var app=W.AppState;if(app&&app.virtual&&app.virtual.render)app.virtual.render();setTimeout(enforceMobileHeight,30);}
  function columnSummary(){return mobileFields().length;}
  function ensureColumnDialog(){if(columnDialog)return columnDialog;columnDialog=document.createElement('dialog');columnDialog.id='mobile-columns-dialog';columnDialog.className='dialog surface surface--modal mobile-field-dialog';columnDialog.innerHTML='<div class="dialog__head"><div><div class="eyebrow">MOBILE VIEW</div><h2>'+label('Visible fields','显示字段')+'</h2></div><button type="button" class="icon-btn mobile-fields-close">×</button></div><div class="dialog__body"><div class="mobile-field-list"></div></div><div class="dialog__actions"><button type="button" class="btn btn--ghost mobile-fields-reset">'+label('Defaults','默认')+'</button><button type="button" class="btn btn--primary mobile-fields-done">'+label('Done','完成')+'</button></div>';columnDialog.querySelector('.mobile-fields-close').onclick=columnDialog.querySelector('.mobile-fields-done').onclick=function(){columnDialog.close();};columnDialog.querySelector('.mobile-fields-reset').onclick=function(){saveMobileFields(['state','progress','size','dlspeed','upspeed','eta']);renderColumnDialog();refreshList();};document.body.appendChild(columnDialog);return columnDialog;}
  function renderColumnDialog(){var d=ensureColumnDialog(),root=d.querySelector('.mobile-field-list'),active=mobileFields();root.textContent='';availableFields().filter(function(f){return f.key!=='name';}).forEach(function(f){var row=document.createElement('div');row.className='mobile-field-row';var ck=document.createElement('input');ck.type='checkbox';ck.checked=active.indexOf(f.key)>=0;var text=document.createElement('span');text.textContent=fieldLabel(f);var controls=document.createElement('span');controls.className='mobile-field-order';var up=document.createElement('button');up.type='button';up.className='btn btn--ghost';up.textContent='↑';var down=document.createElement('button');down.type='button';down.className='btn btn--ghost';down.textContent='↓';function save(next){saveMobileFields(next);if(columnButton)columnButton.textContent=label('Columns ','列 ')+columnSummary();refreshList();renderColumnDialog();}ck.onchange=function(){var next=mobileFields(),i=next.indexOf(f.key);if(ck.checked&&i<0)next.push(f.key);if(!ck.checked&&i>=0)next.splice(i,1);save(next);};function move(dir){var next=mobileFields(),i=next.indexOf(f.key);if(i<0)return;var j=Math.max(0,Math.min(next.length-1,i+dir));if(i===j)return;var tmp=next[i];next[i]=next[j];next[j]=tmp;save(next);}up.onclick=function(){move(-1);};down.onclick=function(){move(1);};controls.append(up,down);row.append(ck,text,controls);root.appendChild(row);});}
  function sortOptions(){var out=[{value:'',label:label('Sort','排序')}];availableFields().forEach(function(f){out.push({value:f.key+':asc',label:fieldLabel(f)+' ↑'},{value:f.key+':desc',label:fieldLabel(f)+' ↓'});});return out;}
  function currentSortValue(){var state=W.LibraryController&&W.LibraryController.state?W.LibraryController.state():null;if(!state||!state.sort)return'';return state.sort+':' + (state.reverse?'desc':'asc');}
  function applySort(value){var parts=String(value||'').split(':'),key=parts[0],dir=parts[1]||'asc',f=R.get(key);if(!f||!R.isAvailable(f.key)||!W.LibraryController||!W.LibraryController.setSort)return Promise.resolve(false);return Promise.resolve(W.LibraryController.setSort(f.sort||f.key,dir));}
  function syncSortControl(){if(!sortControl)return;sortControl.setOptions(sortOptions());sortControl.setValue(currentSortValue());}
  function syncFieldControls(){if(columnButton)columnButton.textContent=label('Columns ','列 ')+columnSummary();syncSortControl();if(columnDialog&&columnDialog.open)renderColumnDialog();refreshList();}

  function syncRSSCopy(){var url=document.getElementById('rss-url'),add=document.getElementById('rss-add-btn'),title=rssDialog&&rssDialog.querySelector('.rss-add-dialog__title'),field=rssDialog&&rssDialog.querySelector('.rss-add-dialog__field-label'),cancel=rssDialog&&rssDialog.querySelector('.rss-add-dialog__cancel'),close=rssDialog&&rssDialog.querySelector('.rss-add-dialog__close');if(rssOpenButton)rssOpenButton.textContent=label('Add Feed','添加 Feed');if(add)add.textContent=label('Add','添加');if(title)title.textContent=label('Add RSS Feed','添加 RSS Feed');if(field)field.textContent=label('RSS Feed URL','RSS Feed URL');if(cancel)cancel.textContent=label('Cancel','取消');if(close)close.setAttribute('aria-label',label('Close','关闭'));if(url){url.placeholder=label('RSS Feed URL','RSS Feed URL');url.setAttribute('aria-label',label('RSS Feed URL','RSS Feed URL'));}}
  function installRSSControls(){if(document.getElementById('rss-add-open-btn'))return;var view=document.getElementById('rss-view'),header=view&&view.querySelector('.workspace__header'),form=view&&view.querySelector('.inline-form'),url=document.getElementById('rss-url'),add=document.getElementById('rss-add-btn'),refresh=document.getElementById('rss-refresh-btn');if(!view||!header||!form||!url||!add||!refresh)return;
    var actions=document.createElement('div');actions.className='rss-header-actions';rssOpenButton=document.createElement('button');rssOpenButton.id='rss-add-open-btn';rssOpenButton.type='button';rssOpenButton.className='btn btn--primary';rssOpenButton.addEventListener('click',function(){if(!rssDialog)return;if(!rssDialog.open)rssDialog.showModal();setTimeout(function(){url.focus();},20);});refresh.addEventListener('click',clearRSSQuery);actions.append(rssOpenButton,refresh);header.appendChild(actions);
    rssDialog=document.createElement('dialog');rssDialog.id='rss-add-dialog';rssDialog.className='dialog surface surface--modal rss-add-dialog';rssDialog.setAttribute('aria-labelledby','rss-add-dialog-title');var head=document.createElement('div');head.className='dialog__head';var headCopy=document.createElement('div');var eyebrow=document.createElement('div');eyebrow.className='eyebrow';eyebrow.textContent='RSS';var title=document.createElement('h2');title.id='rss-add-dialog-title';title.className='rss-add-dialog__title';headCopy.append(eyebrow,title);var close=document.createElement('button');close.type='button';close.className='icon-btn rss-add-dialog__close';close.textContent='×';close.onclick=function(){rssDialog.close();};head.append(headCopy,close);var body=document.createElement('div');body.className='dialog__body';var field=document.createElement('label');field.className='field rss-add-dialog__field';var fieldLabel=document.createElement('span');fieldLabel.className='rss-add-dialog__field-label';url.type='url';url.autocomplete='url';field.append(fieldLabel,url);body.appendChild(field);var dialogActions=document.createElement('div');dialogActions.className='dialog__actions';var cancel=document.createElement('button');cancel.type='button';cancel.className='btn btn--ghost rss-add-dialog__cancel';cancel.onclick=function(){rssDialog.close();};add.type='button';add.addEventListener('click',function(){if(url.value.trim()){clearRSSQuery();rssDialog.close();}});dialogActions.append(cancel,add);rssDialog.append(head,body,dialogActions);document.body.appendChild(rssDialog);form.remove();syncRSSCopy();}

  function installMobileControls(){if(document.getElementById('mobile-view-controls'))return;var host=document.querySelector('#list-view .grid-toolbar>div:first-child');if(!host)return;var wrap=document.createElement('span');wrap.id='mobile-view-controls';wrap.className='mobile-view-controls';columnButton=document.createElement('button');columnButton.type='button';columnButton.className='btn btn--ghost mobile-columns-button';columnButton.textContent=label('Columns ','列 ')+columnSummary();columnButton.onclick=function(){renderColumnDialog();ensureColumnDialog().showModal();};sortControl=C.selectControl({value:'',options:sortOptions(),className:'mobile-sort-control',ariaLabel:label('Torrent sort','种子排序'),searchable:true,searchThreshold:20,onChange:function(value){if(value)applySort(value).catch(function(e){console.error('[WeiG mobile sort]',e);});}});wrap.append(columnButton,sortControl);var pageHost=document.getElementById('page-size-control');if(pageHost&&pageHost.nextSibling)host.insertBefore(wrap,pageHost.nextSibling);else host.appendChild(wrap);syncSortControl();}

  function init(){if(initialized)return;initialized=true;installDismissPolicy();installRSSControls();installMobileControls();setTimeout(function(){installRSSControls();installMobileControls();syncDetailTabLabels();if(mobile()){refreshList();enforceMobileHeight();}syncSortControl();},650);global.addEventListener('resize',U.debounce(function(){enforceMobileHeight();},80));global.addEventListener('weigg:library-state',function(){enforceMobileHeight();syncSortControl();});global.addEventListener('weigg:capabilities-ready',function(){syncFieldControls();syncDetailTabLabels();});global.addEventListener('weigg:route-state',syncDetailTabLabels);global.addEventListener('weigg:release-profile',syncDetailTabLabels);global.addEventListener('weigg:languagechange',function(){relabelDataGrid();syncRSSCopy();syncFieldControls();syncDetailTabLabels();});}
  W.UiSystem={init:init,fields:FIELDS,fitMobileRail:fitRail,enforceMobileHeight:enforceMobileHeight,applySort:applySort,installRSSControls:installRSSControls,syncDetailTabLabels:syncDetailTabLabels};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
