(function(global){
  'use strict';
  var W=global.WeiG,C=W&&W.Components,U=W&&W.util;
  if(!W||!C||!U||W.UiSystem)return;
  var initialized=false,rssQuery='';
  function mobile(){return !!(global.matchMedia&&global.matchMedia('(max-width:820px)').matches);}
  function zh(){return !!(W.I18n&&W.I18n.getLocale&&W.I18n.getLocale()==='zh-CN');}
  function label(en,cn){return zh()?cn:en;}

  var FIELDS=[
    {key:'name',sort:'name',en:'Name',zh:'名称',short:'Name',width:420,min:220},
    {key:'size',sort:'size',en:'Size',zh:'大小',short:'Size',width:105,min:80,format:function(t){return U.formatBytes(t.size);}},
    {key:'progress',sort:'progress',en:'Progress',zh:'进度',short:'%',width:220,min:145,format:function(t){return U.percent(t.progress)+'%';}},
    {key:'dlspeed',sort:'dlspeed',en:'Download',zh:'下载',short:'↓',width:110,min:86,legacy:'dl',format:function(t){return '↓ '+U.formatSpeed(t.dlspeed);}},
    {key:'upspeed',sort:'upspeed',en:'Upload',zh:'上传',short:'↑',width:110,min:86,legacy:'up',format:function(t){return '↑ '+U.formatSpeed(t.upspeed);}},
    {key:'eta',sort:'eta',en:'ETA',zh:'ETA',short:'ETA',width:90,min:70,format:function(t){return 'ETA '+U.formatEta(t.eta);}},
    {key:'state',sort:'state',en:'Status',zh:'状态',short:'State',width:125,min:96,legacy:'status',format:function(t){var s=C.state(t.state);return s[0];}},
    {key:'ratio',sort:'ratio',en:'Ratio',zh:'Ratio',short:'R',width:90,min:70,format:function(t){return 'R '+U.formatRatio(t.ratio);}},
    {key:'tracker',sort:'tracker',en:'Tracker',zh:'Tracker',short:'Tracker',width:165,min:110,format:function(t){return U.trackerLabel(t.tracker);}},
    {key:'category',sort:'category',en:'Category',zh:'分类',short:'Cat',width:130,min:90,format:function(t){return t.category||'—';}},
    {key:'tags',sort:'tags',en:'Tags',zh:'标签',short:'Tags',width:150,min:100,format:function(t){return t.tags||'—';}},
    {key:'num_seeds',sort:'num_seeds',en:'Seeds',zh:'做种数',short:'S',width:90,min:68,format:function(t){return 'S '+(Number.isFinite(Number(t.num_seeds))?Number(t.num_seeds):0);}},
    {key:'num_leechs',sort:'num_leechs',en:'Peers',zh:'下载数',short:'P',width:90,min:68,format:function(t){return 'P '+(Number.isFinite(Number(t.num_leechs))?Number(t.num_leechs):0);}},
    {key:'save_path',sort:'save_path',en:'Save path',zh:'保存路径',short:'Path',width:220,min:130,format:function(t){return t.save_path||'—';}},
    {key:'added_on',sort:'added_on',en:'Added',zh:'添加时间',short:'Added',width:160,min:115,format:function(t){return formatTime(t.added_on);}},
    {key:'completion_on',sort:'completion_on',en:'Completed',zh:'完成时间',short:'Done',width:160,min:115,format:function(t){return formatTime(t.completion_on);}},
    {key:'priority',sort:'priority',en:'Priority',zh:'优先级',short:'Prio',width:92,min:70,format:function(t){var n=Number(t.priority);return Number.isFinite(n)?String(n):'—';}}
  ];
  var FIELD_MAP={};FIELDS.forEach(function(f){FIELD_MAP[f.key]=f;if(f.legacy)FIELD_MAP[f.legacy]=f;});
  function formatTime(value){var n=Number(value);if(!Number.isFinite(n)||n<=0)return'—';var ms=n<1e12?n*1000:n;try{return W.Time&&W.Time.format?W.Time.format(ms,{dateStyle:'short',timeStyle:'short'}):new Date(ms).toLocaleString();}catch(_e){return new Date(ms).toLocaleString();}}
  function fieldLabel(f){return label(f.en,f.zh);}
  function canonical(key){var f=FIELD_MAP[String(key||'')];return f&&f.key;}
  function mobileFields(){var cfg=W.Config.load(),raw=Array.isArray(cfg.mobileFields)?cfg.mobileFields:[];var out=[];raw.forEach(function(k){var c=canonical(k);if(c&&c!=='name'&&out.indexOf(c)<0)out.push(c);});if(!out.length)out=['state','progress','size','dlspeed','upspeed','eta'];return out;}
  function saveMobileFields(fields){var cfg=W.Config.load();cfg.mobileFields=fields.slice();W.Config.save(cfg);}
  W.TorrentFieldRegistry={fields:FIELDS,get:function(key){return FIELD_MAP[key]||null;},canonical:canonical,mobileFields:mobileFields,saveMobileFields:saveMobileFields};

  function extendDataGrid(){var defaults=W.DataGrid&&W.DataGrid.defaults;if(!defaults)return;FIELDS.forEach(function(f){var current=defaults.find(function(x){return x.key===f.key;});if(current){current.sort=f.sort;return;}defaults.push({key:f.key,label:fieldLabel(f),width:f.width,min:f.min,sort:f.sort});});}
  function relabelDataGrid(){var defaults=W.DataGrid&&W.DataGrid.defaults;if(!defaults)return;FIELDS.forEach(function(f){var current=defaults.find(function(x){return x.key===f.key;});if(current)current.label=fieldLabel(f);});}

  function fitRail(row){if(!row||!row.isConnected)return;var rail=row.querySelector('.mobile-card-meta--rail');if(!rail)return;var metrics=Array.from(rail.querySelectorAll('.mobile-metric')),more=rail.querySelector('.mobile-metric-more');metrics.forEach(function(x){x.hidden=false;});more.hidden=true;more.textContent='';var hidden=0;for(var i=metrics.length-1;i>=0&&rail.scrollWidth>rail.clientWidth;i--){metrics[i].hidden=true;hidden++;more.hidden=false;more.textContent='+'+hidden;}while(hidden&&rail.scrollWidth>rail.clientWidth){var visible=metrics.filter(function(x){return !x.hidden;});if(visible.length<=1)break;visible[visible.length-1].hidden=true;hidden++;more.textContent='+'+hidden;}row.dataset.hiddenMetrics=String(hidden);}
  function enforceMobileHeight(){if(!mobile())return;Array.from(document.querySelectorAll('.torrent-mobile-card--two-line')).forEach(fitRail);}

  function destructive(dialog){if(!dialog)return false;if(dialog.dataset.destructive==='true'||dialog.id==='delete-dialog')return true;return !!dialog.querySelector('.btn--danger');}
  function installDismissPolicy(){if(document.documentElement.dataset.weiggDismiss==='1')return;document.documentElement.dataset.weiggDismiss='1';document.addEventListener('dblclick',function(e){var d=e.target&&e.target.closest&&e.target.closest('dialog[open]');if(!d||e.target!==d||destructive(d))return;d.close();},{capture:true});}

  function applyRSSQuery(root){root=root||document.getElementById('rss-content');if(!root)return;var q=rssQuery.trim().toLocaleLowerCase();Array.from(root.querySelectorAll('.tool-row')).forEach(function(row){row.hidden=!!q&&String(row.textContent||'').toLocaleLowerCase().indexOf(q)<0;});}
  function setRSSQuery(value){rssQuery=String(value||'');applyRSSQuery();}
  function clearRSSQuery(){if(!rssQuery)return;rssQuery='';applyRSSQuery();var input=document.getElementById('search-input');if(input&&W.Router&&W.Router.route&&W.Router.route().name==='rss')input.value='';}
  W.RSS={setQuery:setRSSQuery,query:function(){return rssQuery;},apply:applyRSSQuery};

  var columnDialog=null,columnButton=null,sortControl=null,rssDialog=null,rssOpenButton=null;
  function refreshList(){var app=W.AppState;if(app&&app.virtual&&app.virtual.render)app.virtual.render();setTimeout(enforceMobileHeight,30);}
  function columnSummary(){return mobileFields().length;}
  function ensureColumnDialog(){if(columnDialog)return columnDialog;columnDialog=document.createElement('dialog');columnDialog.id='mobile-columns-dialog';columnDialog.className='dialog surface surface--modal mobile-field-dialog';columnDialog.innerHTML='<div class="dialog__head"><div><div class="eyebrow">MOBILE VIEW</div><h2>'+label('Visible fields','显示字段')+'</h2></div><button type="button" class="icon-btn mobile-fields-close">×</button></div><div class="dialog__body"><div class="mobile-field-list"></div></div><div class="dialog__actions"><button type="button" class="btn btn--ghost mobile-fields-reset">'+label('Defaults','默认')+'</button><button type="button" class="btn btn--primary mobile-fields-done">'+label('Done','完成')+'</button></div>';columnDialog.querySelector('.mobile-fields-close').onclick=columnDialog.querySelector('.mobile-fields-done').onclick=function(){columnDialog.close();};columnDialog.querySelector('.mobile-fields-reset').onclick=function(){saveMobileFields(['state','progress','size','dlspeed','upspeed','eta']);renderColumnDialog();refreshList();};document.body.appendChild(columnDialog);return columnDialog;}
  function renderColumnDialog(){var d=ensureColumnDialog(),root=d.querySelector('.mobile-field-list'),active=mobileFields();root.textContent='';FIELDS.filter(function(f){return f.key!=='name';}).forEach(function(f){var row=document.createElement('div');row.className='mobile-field-row';var ck=document.createElement('input');ck.type='checkbox';ck.checked=active.indexOf(f.key)>=0;var text=document.createElement('span');text.textContent=fieldLabel(f);var controls=document.createElement('span');controls.className='mobile-field-order';var up=document.createElement('button');up.type='button';up.className='btn btn--ghost';up.textContent='↑';var down=document.createElement('button');down.type='button';down.className='btn btn--ghost';down.textContent='↓';function save(next){saveMobileFields(next);if(columnButton)columnButton.textContent=label('Columns ','列 ')+columnSummary();refreshList();renderColumnDialog();}ck.onchange=function(){var next=mobileFields(),i=next.indexOf(f.key);if(ck.checked&&i<0)next.push(f.key);if(!ck.checked&&i>=0)next.splice(i,1);save(next);};function move(dir){var next=mobileFields(),i=next.indexOf(f.key);if(i<0)return;var j=Math.max(0,Math.min(next.length-1,i+dir));if(i===j)return;var tmp=next[i];next[i]=next[j];next[j]=tmp;save(next);}up.onclick=function(){move(-1);};down.onclick=function(){move(1);};controls.append(up,down);row.append(ck,text,controls);root.appendChild(row);});}
  function sortOptions(){var out=[{value:'',label:label('Sort','排序')}];FIELDS.forEach(function(f){out.push({value:f.key+':asc',label:fieldLabel(f)+' ↑'},{value:f.key+':desc',label:fieldLabel(f)+' ↓'});});return out;}
  function currentSortValue(){var state=W.LibraryController&&W.LibraryController.state?W.LibraryController.state():null;if(!state||!state.sort)return'';return state.sort+':' + (state.reverse?'desc':'asc');}
  function applySort(value){var parts=String(value||'').split(':'),key=parts[0],dir=parts[1]||'asc',f=FIELD_MAP[key];if(!f||!W.LibraryController||!W.LibraryController.setSort)return Promise.resolve(false);return Promise.resolve(W.LibraryController.setSort(f.sort||f.key,dir));}
  function syncSortControl(){if(!sortControl)return;sortControl.setOptions(sortOptions());sortControl.setValue(currentSortValue());}

  function syncRSSCopy(){var url=document.getElementById('rss-url'),add=document.getElementById('rss-add-btn'),title=rssDialog&&rssDialog.querySelector('.rss-add-dialog__title'),field=rssDialog&&rssDialog.querySelector('.rss-add-dialog__field-label'),cancel=rssDialog&&rssDialog.querySelector('.rss-add-dialog__cancel'),close=rssDialog&&rssDialog.querySelector('.rss-add-dialog__close');if(rssOpenButton)rssOpenButton.textContent=label('Add Feed','添加 Feed');if(add)add.textContent=label('Add','添加');if(title)title.textContent=label('Add RSS Feed','添加 RSS Feed');if(field)field.textContent=label('RSS Feed URL','RSS Feed URL');if(cancel)cancel.textContent=label('Cancel','取消');if(close)close.setAttribute('aria-label',label('Close','关闭'));if(url){url.placeholder=label('RSS Feed URL','RSS Feed URL');url.setAttribute('aria-label',label('RSS Feed URL','RSS Feed URL'));}}
  function installRSSControls(){if(document.getElementById('rss-add-open-btn'))return;var view=document.getElementById('rss-view'),header=view&&view.querySelector('.workspace__header'),form=view&&view.querySelector('.inline-form'),url=document.getElementById('rss-url'),add=document.getElementById('rss-add-btn'),refresh=document.getElementById('rss-refresh-btn');if(!view||!header||!form||!url||!add||!refresh)return;
    var actions=document.createElement('div');actions.className='rss-header-actions';rssOpenButton=document.createElement('button');rssOpenButton.id='rss-add-open-btn';rssOpenButton.type='button';rssOpenButton.className='btn btn--primary';rssOpenButton.addEventListener('click',function(){if(!rssDialog)return;if(!rssDialog.open)rssDialog.showModal();setTimeout(function(){url.focus();},20);});refresh.addEventListener('click',clearRSSQuery);actions.append(rssOpenButton,refresh);header.appendChild(actions);
    rssDialog=document.createElement('dialog');rssDialog.id='rss-add-dialog';rssDialog.className='dialog surface surface--modal rss-add-dialog';rssDialog.setAttribute('aria-labelledby','rss-add-dialog-title');var head=document.createElement('div');head.className='dialog__head';var headCopy=document.createElement('div');var eyebrow=document.createElement('div');eyebrow.className='eyebrow';eyebrow.textContent='RSS';var title=document.createElement('h2');title.id='rss-add-dialog-title';title.className='rss-add-dialog__title';headCopy.append(eyebrow,title);var close=document.createElement('button');close.type='button';close.className='icon-btn rss-add-dialog__close';close.textContent='×';close.onclick=function(){rssDialog.close();};head.append(headCopy,close);var body=document.createElement('div');body.className='dialog__body';var field=document.createElement('label');field.className='field rss-add-dialog__field';var fieldLabel=document.createElement('span');fieldLabel.className='rss-add-dialog__field-label';url.type='url';url.autocomplete='url';field.append(fieldLabel,url);body.appendChild(field);var dialogActions=document.createElement('div');dialogActions.className='dialog__actions';var cancel=document.createElement('button');cancel.type='button';cancel.className='btn btn--ghost rss-add-dialog__cancel';cancel.onclick=function(){rssDialog.close();};add.type='button';add.addEventListener('click',function(){if(url.value.trim()){clearRSSQuery();rssDialog.close();}});dialogActions.append(cancel,add);rssDialog.append(head,body,dialogActions);document.body.appendChild(rssDialog);form.remove();syncRSSCopy();}

  function installMobileControls(){if(document.getElementById('mobile-view-controls'))return;var host=document.querySelector('#list-view .grid-toolbar>div:first-child');if(!host)return;var wrap=document.createElement('span');wrap.id='mobile-view-controls';wrap.className='mobile-view-controls';columnButton=document.createElement('button');columnButton.type='button';columnButton.className='btn btn--ghost mobile-columns-button';columnButton.textContent=label('Columns ','列 ')+columnSummary();columnButton.onclick=function(){renderColumnDialog();ensureColumnDialog().showModal();};sortControl=C.selectControl({value:'',options:sortOptions(),className:'mobile-sort-control',ariaLabel:label('Torrent sort','种子排序'),searchable:true,searchThreshold:20,onChange:function(value){if(value)applySort(value).catch(function(e){console.error('[WeiG mobile sort]',e);});}});wrap.append(columnButton,sortControl);var pageHost=document.getElementById('page-size-control');if(pageHost&&pageHost.nextSibling)host.insertBefore(wrap,pageHost.nextSibling);else host.appendChild(wrap);syncSortControl();}

  function init(){if(initialized)return;initialized=true;extendDataGrid();installDismissPolicy();installRSSControls();installMobileControls();setTimeout(function(){installRSSControls();installMobileControls();if(mobile()){refreshList();enforceMobileHeight();}syncSortControl();},650);global.addEventListener('resize',U.debounce(function(){enforceMobileHeight();},80));global.addEventListener('weigg:library-state',function(){enforceMobileHeight();syncSortControl();});global.addEventListener('weigg:languagechange',function(){relabelDataGrid();syncRSSCopy();if(columnButton)columnButton.textContent=label('Columns ','列 ')+columnSummary();syncSortControl();});}
  W.UiSystem={init:init,fields:FIELDS,fitMobileRail:fitRail,enforceMobileHeight:enforceMobileHeight,applySort:applySort,installRSSControls:installRSSControls};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
