(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{};
  if(W.UpdateCheck)return;
  var RELEASE_API='https://api.github.com/repos/weigefenxiang/WeiG-qB-WebUI/releases/latest';
  var DEV_META='https://weigefenxiang.github.io/WeiG-qB-WebUI/metadata/dev.json';
  var RELEASES='https://github.com/weigefenxiang/WeiG-qB-WebUI/releases/latest';
  var INSTALL_SH='https://weigefenxiang.github.io/WeiG-qB-WebUI/downloads/dev/install.sh';
  var INSTALL_PS1='https://weigefenxiang.github.io/WeiG-qB-WebUI/downloads/dev/install.ps1';
  function tr(key,fallback){var value=W.t?W.t(key):'';return value&&value!==key?value:String(fallback||key);}
  function cleanVersion(value){return String(value||'').trim().replace(/^v/i,'');}
  function validSha(value){return /^[0-9a-f]{40}$/i.test(String(value||'').trim());}
  function normalizeIdentity(current,meta){current=current||{};meta=meta||{};var version=cleanVersion(current.version||meta.version||''),rawSha=String(current.gitSha||meta.gitSha||'').trim(),gitSha=validSha(rawSha)?rawSha.toLowerCase():'',rawChannel=String(meta.channel||'').trim().toLowerCase(),channel;if(meta.simulator===true)channel='virtual';else if(rawChannel==='dev')channel='dev';else if(rawChannel==='main'||rawChannel==='release'||rawChannel==='stable')channel='stable';else channel='source';return{version:version,gitSha:gitSha,channel:channel,materialized:!!gitSha,installer:String(meta.installer||'')};}
  function shortSha(value){return validSha(value)?String(value).toLowerCase().slice(0,7):'';}
  function identityValue(identity){identity=identity||{};var version=identity.version||'—',sha=shortSha(identity.gitSha);return sha?version+' ('+sha+')':version;}
  function identityState(identity){identity=identity||{};if(identity.channel==='dev')return tr('settings.update.channelDev','Dev');if(identity.channel==='stable')return tr('settings.update.channelStable','Stable');if(identity.channel==='virtual')return tr('settings.update.channelVirtual','Virtual');return tr('settings.update.sourceInstallNoSha','Source install · no build SHA');}
  function identityText(identity){var value=identityValue(identity),state=identityState(identity);return state?value+' · '+state:value;}
  function compare(a,b){var C=W.CapabilityRegistry;if(C&&typeof C.compareVersions==='function')return C.compareVersions(cleanVersion(a),cleanVersion(b));var aa=cleanVersion(a).split('.').map(Number),bb=cleanVersion(b).split('.').map(Number);for(var i=0;i<3;i++){var d=(aa[i]||0)-(bb[i]||0);if(d)return d>0?1:-1;}return 0;}
  async function json(url){var response=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'}});if(!response.ok)throw new Error('HTTP '+response.status);return response.json();}
  async function installMeta(){try{return await json('weig-install.json');}catch(_e){return null;}}
  function button(label,className,handler){var node=document.createElement('button');node.type='button';node.className=className||'btn btn--ghost';node.textContent=label;node.addEventListener('click',handler);return node;}
  function line(label,value,state,labelAccessory){var row=document.createElement('div'),labelWrap=document.createElement('span'),a=document.createElement('strong'),b=document.createElement('span'),c=document.createElement('span');row.className='update-check__row';labelWrap.className='update-check__label';a.textContent=label;labelWrap.appendChild(a);if(labelAccessory)labelWrap.appendChild(labelAccessory);b.className='update-check__value';b.textContent=value||'—';c.className='update-check__state';if(state)c.appendChild(document.createTextNode(state));row.append(labelWrap,b,c);return row;}
  async function copyCommand(value,buttonNode){if(!W.Clipboard||typeof W.Clipboard.copyText!=='function')throw new Error(tr('common.clipboardUnavailable','Clipboard access is unavailable in this browser context.'));var result=await W.Clipboard.copyText(value,{title:tr('settings.update.copy','Copy')});if(result&&result.copied){buttonNode.textContent=tr('settings.update.copied','Copied');setTimeout(function(){if(buttonNode.isConnected)buttonNode.textContent=tr('settings.update.copy','Copy');},1200);}return result;}
  function commandPanel(title,commands){var wrap=document.createElement('section');wrap.className='update-check__commands';var heading=document.createElement('strong');heading.textContent=title;wrap.appendChild(heading);commands.forEach(function(item){var row=document.createElement('div'),label=document.createElement('span'),code=document.createElement('code'),copy=button(tr('settings.update.copy','Copy'),'btn btn--ghost',function(){copyCommand(item.command,copy).catch(function(error){if(W.toast)W.toast(String(error&&error.message||error),'error',{title:tr('common.copyFailedTitle','Copy failed')});});});row.className='update-check__command';label.textContent=item.label;code.textContent=item.command;row.append(label,code,copy);wrap.appendChild(row);});return wrap;}
  function devWarningPanel(){var wrap=document.createElement('section'),title=document.createElement('strong'),copy=document.createElement('p');wrap.className='update-check__commands';title.textContent=tr('settings.update.devWarningTitle','Development build');copy.className='text-description update-check__note';copy.textContent=tr('settings.update.devWarning','Development builds contain the latest changes and may include undiscovered bugs or unstable behavior. Use Stable when long-term reliability is more important than the newest changes.');wrap.append(title,copy);return wrap;}
  function devInfoButton(details){var info=button('?','icon-btn update-check__info',function(){setPanel(details,devWarningPanel());});info.setAttribute('aria-label',tr('settings.update.devWarningTitle','Development build'));info.title=tr('settings.update.devWarningTitle','Development build');return info;}
  function devCommands(){return[
    {label:'Linux / NAS',command:'curl -fsSL '+INSTALL_SH+' -o install.sh && sh install.sh -dev'},
    {label:'Windows',command:'Invoke-WebRequest '+INSTALL_PS1+' -OutFile .\\install.ps1; powershell -ExecutionPolicy Bypass -File .\\install.ps1 -dev'}
  ];}
  function rollbackCommands(){return[
    {label:'Linux / NAS',command:'sh install.sh -rollback'},
    {label:'Windows',command:'powershell -ExecutionPolicy Bypass -File .\\install.ps1 -rollback'}
  ];}
  function setPanel(host,node){host.textContent='';if(node)host.appendChild(node);}
  function stableState(current,latest){if(!latest)return tr('settings.update.unavailable','Unavailable');if(!current)return tr('settings.update.available','Available');var cmp=compare(current,latest);return cmp<0?tr('settings.update.newVersion','New version'):cmp===0?tr('settings.update.current','Current'):tr('settings.update.ahead','Ahead');}
  function devState(current,devSha){if(!validSha(devSha))return tr('settings.update.unavailable','Unavailable');if(current&&current.channel==='dev'&&current.gitSha&&current.gitSha===String(devSha).toLowerCase())return tr('settings.update.current','Current');return tr('settings.update.available','Available');}
  async function open(current){current=current||{};if(!W.DialogRuntime)return null;var dialog=W.DialogRuntime.create({className:'dialog surface surface--modal update-check-dialog',removeOnClose:true,backdropClose:true,escapeClose:true}),surface=document.createElement('div'),head=document.createElement('header'),title=document.createElement('h2'),body=document.createElement('div'),summary=document.createElement('div'),details=document.createElement('div'),footer=document.createElement('div');surface.className='update-check__surface';head.className='dialog__head';title.textContent=tr('settings.update.title','Check for updates');head.appendChild(title);body.className='update-check__body';summary.className='update-check__summary';details.className='update-check__details';footer.className='update-check__footer';summary.appendChild(line(tr('settings.update.currentInstall','Current'),identityValue(normalizeIdentity(current,{})),tr('settings.update.checking','Checking…')));body.append(summary,details);surface.append(head,body,footer);dialog.appendChild(surface);
    var releaseButton=button(tr('settings.update.openRelease','Open Release'),'btn btn--ghost',function(){global.open(RELEASES,'_blank','noopener,noreferrer');}),devButton=button(tr('settings.update.devInstall','Dev install'),'btn btn--ghost',function(){setPanel(details,commandPanel(tr('settings.update.devInstall','Dev install'),devCommands()));}),rollbackButton=button(tr('settings.update.rollbackMethod','Rollback method'),'btn btn--ghost',function(){setPanel(details,commandPanel(tr('settings.update.rollbackTitle','Rollback method (return to the previous version)'),rollbackCommands()));}),closeButton=button(tr('app.close','Close'),'btn btn--primary',function(){W.DialogRuntime.close(dialog,'close');});releaseButton.disabled=true;footer.append(releaseButton,devButton,rollbackButton,closeButton);W.DialogRuntime.open(dialog,{draggable:true,backdropClose:true,escapeClose:true,removeOnClose:true,focus:closeButton});
    var metaTask=installMeta(),stableTask=json(RELEASE_API),devTask=json(DEV_META),results=await Promise.allSettled([metaTask,stableTask,devTask]);if(!dialog.isConnected)return dialog;var meta=results[0].status==='fulfilled'?results[0].value:null,stable=results[1].status==='fulfilled'?results[1].value:null,dev=results[2].status==='fulfilled'?results[2].value:null,currentIdentity=normalizeIdentity(current,meta),stableVersion=cleanVersion(stable&&stable.tag_name||''),devVersion=cleanVersion(dev&&dev.productVersion||''),devSha=validSha(dev&&dev.exactSha)?String(dev.exactSha).toLowerCase():'',stableIdentity=normalizeIdentity({version:stableVersion},{channel:'stable'}),devIdentity=normalizeIdentity({version:devVersion,gitSha:devSha},{channel:'dev'});summary.textContent='';summary.appendChild(line(tr('settings.update.currentInstall','Current'),identityValue(currentIdentity),identityState(currentIdentity)));summary.appendChild(line('Stable',identityValue(stableIdentity),stableState(currentIdentity.version,stableVersion)));summary.appendChild(line('Dev',identityValue(devIdentity),devState(currentIdentity,devSha),devInfoButton(details)));releaseButton.disabled=!stable;if(!stable||!dev){var note=document.createElement('p');note.className='text-description update-check__note';note.textContent=tr('settings.update.partial','Some update sources could not be reached. You can retry later.');details.appendChild(note);}return dialog;
  }
  W.UpdateCheck={open:open,compareVersions:compare,releaseApi:RELEASE_API,devMetadata:DEV_META,normalizeIdentity:normalizeIdentity,identityValue:identityValue,identityState:identityState,identityText:identityText,isValidSha:validSha};
})(window);
