(function(global){
  'use strict';
  var W=global.WeiG=global.WeiG||{};
  if(W.UpdateCheck)return;
  var RELEASE_API='https://api.github.com/repos/weigefenxiang/WeiG-qB-WebUI/releases/latest';
  var DEV_META='https://weigefenxiang.github.io/WeiG-qB-WebUI/metadata/dev.json';
  var RELEASES='https://github.com/weigefenxiang/WeiG-qB-WebUI/releases/latest';
  var INSTALL_SH='https://weigefenxiang.github.io/WeiG-qB-WebUI/downloads/dev/install.sh';
  var INSTALL_PS1='https://weigefenxiang.github.io/WeiG-qB-WebUI/downloads/dev/install.ps1';
  function tr(key,fallback){var value=W.t?W.t(key):'';return value&&value!==key?value:String(fallback||key);}
  function cleanVersion(value){return String(value||'').trim().replace(/^v/i,'');}
  function compare(a,b){var C=W.CapabilityRegistry;if(C&&typeof C.compareVersions==='function')return C.compareVersions(cleanVersion(a),cleanVersion(b));var aa=cleanVersion(a).split('.').map(Number),bb=cleanVersion(b).split('.').map(Number);for(var i=0;i<3;i++){var d=(aa[i]||0)-(bb[i]||0);if(d)return d>0?1:-1;}return 0;}
  async function json(url){var response=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'}});if(!response.ok)throw new Error('HTTP '+response.status);return response.json();}
  async function installMeta(){try{return await json('weig-install.json');}catch(_e){return null;}}
  function button(label,className,handler){var node=document.createElement('button');node.type='button';node.className=className||'btn btn--ghost';node.textContent=label;node.addEventListener('click',handler);return node;}
  function line(label,value,state){var row=document.createElement('div');row.className='update-check__row';var a=document.createElement('strong'),b=document.createElement('span'),c=document.createElement('span');a.textContent=label;b.textContent=value||'—';c.className='update-check__state';c.textContent=state||'';row.append(a,b,c);return row;}
  function commandPanel(title,commands){var wrap=document.createElement('section');wrap.className='update-check__commands';var heading=document.createElement('strong');heading.textContent=title;wrap.appendChild(heading);commands.forEach(function(item){var row=document.createElement('div'),label=document.createElement('span'),code=document.createElement('code'),copy=button(tr('settings.update.copy','Copy'),'btn btn--ghost',function(){copyText(item.command,copy);});row.className='update-check__command';label.textContent=item.label;code.textContent=item.command;row.append(label,code,copy);wrap.appendChild(row);});return wrap;}
  async function copyText(value,buttonNode){try{await navigator.clipboard.writeText(value);buttonNode.textContent=tr('settings.update.copied','Copied');setTimeout(function(){if(buttonNode.isConnected)buttonNode.textContent=tr('settings.update.copy','Copy');},1200);}catch(_e){var area=document.createElement('textarea');area.value=value;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();try{document.execCommand('copy');}catch(_ignore){}area.remove();}}
  function devCommands(){return[
    {label:'Linux / NAS',command:'curl -fsSL '+INSTALL_SH+' -o weig_qb-webui_install.sh && sh weig_qb-webui_install.sh -dev'},
    {label:'Windows',command:'Invoke-WebRequest '+INSTALL_PS1+' -OutFile .\\weig_qb-webui_install.ps1; powershell -ExecutionPolicy Bypass -File .\\weig_qb-webui_install.ps1 -dev'}
  ];}
  function rollbackCommands(){return[
    {label:'Linux / NAS',command:'sh weig_qb-webui_install.sh -rollback'},
    {label:'Windows',command:'powershell -ExecutionPolicy Bypass -File .\\weig_qb-webui_install.ps1 -rollback'}
  ];}
  function setPanel(host,node){host.textContent='';if(node)host.appendChild(node);}
  function stableState(current,latest){if(!latest)return tr('settings.update.unavailable','Unavailable');if(!current)return tr('settings.update.available','Available');var cmp=compare(current,latest);return cmp<0?tr('settings.update.newVersion','New version'):cmp===0?tr('settings.update.current','Current'):tr('settings.update.ahead','Ahead');}
  function devState(currentSha,devSha){if(!devSha)return tr('settings.update.unavailable','Unavailable');if(currentSha&&currentSha.toLowerCase()===devSha.toLowerCase())return tr('settings.update.current','Current');return tr('settings.update.available','Available');}
  async function open(current){current=current||{};if(!W.DialogRuntime)return null;var dialog=W.DialogRuntime.create({className:'dialog surface surface--modal update-check-dialog',removeOnClose:true,backdropClose:true,escapeClose:true}),surface=document.createElement('div'),head=document.createElement('header'),title=document.createElement('h2'),body=document.createElement('div'),summary=document.createElement('div'),details=document.createElement('div'),footer=document.createElement('div');surface.className='update-check__surface';head.className='dialog__head';title.textContent=tr('settings.update.title','Check for updates');head.appendChild(title);body.className='update-check__body';summary.className='update-check__summary';details.className='update-check__details';footer.className='update-check__footer';summary.appendChild(line(tr('settings.update.currentInstall','Current'),(current.version||'—')+(current.gitSha?' · '+String(current.gitSha).slice(0,8):''),tr('settings.update.checking','Checking…')));body.append(summary,details);surface.append(head,body,footer);dialog.appendChild(surface);
    var releaseButton=button(tr('settings.update.openRelease','Open Release'),'btn btn--ghost',function(){global.open(RELEASES,'_blank','noopener,noreferrer');}),devButton=button(tr('settings.update.devInstall','Dev install'),'btn btn--ghost',function(){setPanel(details,commandPanel(tr('settings.update.devInstall','Dev install'),devCommands()));}),rollbackButton=button(tr('settings.update.rollback','Rollback…'),'btn btn--ghost',function(){setPanel(details,commandPanel(tr('settings.update.rollback','Rollback…'),rollbackCommands()));}),closeButton=button(tr('app.close','Close'),'btn btn--primary',function(){W.DialogRuntime.close(dialog,'close');});releaseButton.disabled=true;footer.append(releaseButton,devButton,rollbackButton,closeButton);W.DialogRuntime.open(dialog,{draggable:false,backdropClose:true,escapeClose:true,removeOnClose:true,focus:closeButton});
    var metaTask=installMeta(),stableTask=json(RELEASE_API),devTask=json(DEV_META),results=await Promise.allSettled([metaTask,stableTask,devTask]);if(!dialog.isConnected)return dialog;var meta=results[0].status==='fulfilled'?results[0].value:null,stable=results[1].status==='fulfilled'?results[1].value:null,dev=results[2].status==='fulfilled'?results[2].value:null,currentVersion=cleanVersion(current.version||meta&&meta.version||''),currentSha=String(current.gitSha||meta&&meta.gitSha||''),stableVersion=cleanVersion(stable&&stable.tag_name||''),devVersion=cleanVersion(dev&&dev.productVersion||''),devSha=String(dev&&dev.exactSha||'');summary.textContent='';var channel=String(meta&&meta.channel||'source');summary.appendChild(line(tr('settings.update.currentInstall','Current'),(currentVersion||'—')+(currentSha?' · '+currentSha.slice(0,8):'')+' · '+channel,''));summary.appendChild(line('Stable',stableVersion||tr('settings.update.unavailable','Unavailable'),stableState(currentVersion,stableVersion)));summary.appendChild(line('Dev',(devVersion||'—')+(devSha?' · '+devSha.slice(0,8):''),devState(currentSha,devSha)));releaseButton.disabled=!stable;if(!stable||!dev){var note=document.createElement('p');note.className='text-description update-check__note';note.textContent=tr('settings.update.partial','Some update sources could not be reached. You can retry later.');details.appendChild(note);}return dialog;
  }
  W.UpdateCheck={open:open,compareVersions:compare,releaseApi:RELEASE_API,devMetadata:DEV_META};
})(window);
