(function(global){
  'use strict';
  var W=global.WeiG,U=W.util,I=W.I18n,T=W.t;
  if(!W||!U||!I)return;
  var filterKeys={all:'filter.all',downloading:'filter.downloading',seeding:'filter.seeding',completed:'filter.completed',paused:'filter.paused',active:'filter.active',stalled:'filter.stalled',errored:'filter.error',private:'filter.private'};
  var columnKeys={name:'torrent.name',size:'torrent.size',progress:'torrent.progress',dlspeed:'torrent.download',upspeed:'torrent.upload',eta:'torrent.eta',state:'torrent.status',ratio:'torrent.ratio',tracker:'torrent.tracker',category:'torrent.categoryColumn'};
  var routeSearch={home:'search.torrents',torrent:'search.torrents',settings:'search.settings',search:'search.engine',rss:'search.rss',logs:'search.logs'};
  var legacyExact={'全部种子':'library.all','全部 Tracker':'tracker.all','全部路径':'path.all','全部分类':'category.all','全部标签':'tag.all','种子详情':'detail.title','正在加载…':'app.loading','已刷新':'library.refreshed','命令已发送':'torrent.commandSent','文件优先级已更新':'file.updated','Peer 已封禁':'peer.banned','添加 Tracker':'tracker.add','删除':'torrent.delete','编辑':'tracker.edit','查看详情':'torrent.details','设置':'settings.title','搜索引擎':'search.title','日志':'logs.title','下载':'settings.downloads','连接':'settings.connection','速度':'settings.speed','高级':'settings.advanced','全部高级设置':'settings.advanced','界面':'settings.interface','性能':'settings.performance','保存 qB 设置':'settings.save','没有需要保存的 qB 设置':'settings.noChanges','qBittorrent 设置已保存':'settings.saved','当前版本没有返回这一组设置。':'settings.none','只显示当前 qBittorrent 实际返回的 Preferences。':'settings.currentOnly','所有字体、密度、分页和视觉行为都由统一 Token 控制。':'settings.interfaceDesc','开发/诊断信息从主界面移到这里。':'settings.performanceDesc','主题':'settings.theme','字体大小':'settings.fontSize','界面密度':'settings.density','星空':'settings.starfield','动画':'settings.motion','每页 Torrent':'settings.pageSize','刷新频率':'settings.refresh','4.x PT Tracker 规则':'settings.ptRules','跟随系统':'settings.theme.system','深色':'settings.theme.dark','浅色':'settings.theme.light','标准':'settings.size.standard','大（+2px）':'settings.size.large','特大（+3px）':'settings.size.xlarge','紧凑':'settings.density.compact','宽松':'settings.density.comfortable','关闭':'settings.off','柔和':'settings.subtle','完整':'settings.full','减少':'settings.reduced','统一全局设置':'settings.global','恢复默认':'columns.reset','完成':'columns.done','取消':'app.cancel','确认':'app.confirm','添加种子':'library.add','更多操作':'torrent.actions','开始':'torrent.start','暂停':'torrent.pause','强制开始':'torrent.forceStart','重新校验':'torrent.recheck','重新汇报':'torrent.reannounce','顺序下载':'torrent.sequential','首尾块优先':'torrent.firstLast','自动管理':'torrent.autoTmm','队列置顶':'torrent.top','队列置底':'torrent.bottom','重命名':'torrent.rename','移动位置':'torrent.location','设置分类':'torrent.category','添加 Tags':'torrent.addTags','设置下载限速 KiB/s':'torrent.downloadLimit','设置上传限速 KiB/s':'torrent.uploadLimit'};
  function routeName(){var r=W.Router.route();return r.name||'home';}
  function bindRoutes(){U.$$('#app-nav [data-route],#mobile-bottom-nav [data-route]').forEach(function(btn){if(btn.__weiggRouteBound)return;btn.__weiggRouteBound=true;btn.addEventListener('click',function(){var path=btn.dataset.route||'';if(path)W.Router.go(path);else W.Router.home();});});}
  function syncRouteUI(){var name=routeName(),active=name==='home'||name==='torrent'?'':name;U.$$('#app-nav [data-route],#mobile-bottom-nav [data-route]').forEach(function(btn){btn.classList.toggle('is-active',(btn.dataset.route||'')===active);});var input=U.$('search-input');if(input){input.dataset.i18nPlaceholder=routeSearch[name]||'search.torrents';input.placeholder=T(input.dataset.i18nPlaceholder);if(name!=='home'&&name!=='torrent')input.value='';}if(name==='settings')setTimeout(syncSettingsSearch,0);setTimeout(syncCapabilities,100);}
  function syncCapabilities(){['search','rss','logs'].forEach(function(cap){var nodes=U.$$('[data-capability="'+cap+'"]');if(!nodes.length)return;var hidden=nodes.some(function(n){return n.hidden;});nodes.forEach(function(n){n.hidden=hidden;});});}
  function translateGrid(){U.$$('#torrent-table-head .grid-head-cell').forEach(function(cell){var key=columnKeys[cell.dataset.key];if(!key)return;var arrow=/[↓↑]/.test(cell.textContent)?' '+(cell.textContent.indexOf('↓')>=0?'↓':'↑'):'';if(cell.firstChild)cell.firstChild.nodeValue=T(key)+arrow;});}
  function translateFilterTitle(){var active=document.querySelector('#filter-nav .nav-item.is-active'),title=U.$('page-title');if(active&&title&&filterKeys[active.dataset.filter])title.textContent=T(filterKeys[active.dataset.filter]);}
  function countSuffix(text){var m=String(text||'').match(/\s·\s(\d+)$/);return m?' · '+m[1]:'';}
  function translateDynamicNav(){var a=document.querySelector('#tracker-nav [data-tracker=""]');if(a)a.textContent=T('tracker.all')+countSuffix(a.textContent);var p=document.querySelector('#savepath-nav [data-savepath=""]');if(p)p.textContent=T('path.all')+countSuffix(p.textContent);var c=document.querySelector('#category-nav [data-category=""]');if(c)c.textContent=T('category.all');var g=document.querySelector('#tag-nav [data-tag=""]');if(g)g.textContent=T('tag.all');}
  function updateLibraryCopy(){var n=U.$('torrent-count'),copy=U.$('library-count-copy');if(!n||!copy)return;var value=n.textContent.trim();copy.textContent=/^\d+$/.test(value)?T('library.count',{count:value}):T('library.count',{count:'…'});}
  function translateLegacyNode(node){if(!node||node.nodeType!==3)return;var raw=node.nodeValue,trim=raw.trim();if(!trim)return;var key=legacyExact[trim];if(key){var next=T(key);if(next!==trim)node.nodeValue=raw.replace(trim,next);return;}var m=trim.match(/^第\s*(\d+)\s*\/\s*([^\s]+)\s*页\s*·\s*每页\s*(\d+)$/);if(m){node.nodeValue=T('library.page',{page:m[1],pages:m[2],size:m[3]});return;}m=trim.match(/^将删除\s*(\d+)\s*个选中的种子。$/);if(m){node.nodeValue=T('torrent.deleteSelected',{count:m[1]});return;}m=trim.match(/^读取种子失败：(.*)$/);if(m){node.nodeValue=T('library.readFailed',{error:m[1]});return;}m=trim.match(/^操作失败：(.*)$/);if(m){node.nodeValue=T('torrent.actionFailed',{error:m[1]});return;}m=trim.match(/^添加失败：(.*)$/);if(m){node.nodeValue=T('torrent.addFailed',{error:m[1]});return;}}
  function translateLegacy(root){if(I.getLocale()==='zh-CN')return;var walker=document.createTreeWalker(root||document.body,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(translateLegacyNode);}
  function syncSettingsSearch(){var input=U.$('settings-search-input');if(!input||input.__weiggBound)return;input.__weiggBound=true;input.addEventListener('input',function(){filterSettings(input.value);});}
  function filterSettings(query){var q=String(query||'').trim().toLocaleLowerCase();U.$$('#settings-content .setting-row').forEach(function(row){var value=(row.dataset.settingSearch||row.textContent||'').toLocaleLowerCase();row.hidden=!!q&&value.indexOf(q)<0;});}
  function translateConnection(){var status=U.$('connection-status'),dock=U.$('status-connection');if(status){var raw=status.textContent.trim().toLowerCase(),key=raw==='firewalled'?'stats.firewalled':raw==='connected'?'stats.connected':raw==='disconnected'?'stats.disconnected':'';if(key)status.textContent=T(key);}if(dock){var raw2=dock.textContent.replace(/^●\s*/,'').trim().toLowerCase(),k=raw2==='firewalled'?'stats.firewalled':raw2==='connected'?'stats.connected':raw2==='disconnected'?'stats.disconnected':'';if(k)dock.textContent='● '+T(k);}}
  function handleContextQuery(q){var name=routeName();if(name==='settings'){var s=U.$('settings-search-input');if(s){s.value=q;filterSettings(q);}}else if(name==='logs'||name==='rss'){var view=U.$(name+'-view');U.$$('.tool-row',view).forEach(function(row){row.hidden=!!q&&row.textContent.toLocaleLowerCase().indexOf(q.toLocaleLowerCase())<0;});}else if(name==='search'){var e=U.$('engine-query');if(e)e.value=q;}}
  function contextualSearch(){var input=U.$('search-input');if(!input||input.__weiggContext)return;input.__weiggContext=true;input.addEventListener('input',function(e){var name=routeName();if(name==='home'||name==='torrent')return;handleContextQuery(input.value);e.stopImmediatePropagation();},true);}
  function refreshTranslations(){I.apply(document);translateFilterTitle();translateDynamicNav();translateGrid();translateConnection();updateLibraryCopy();translateLegacy(document.body);}
  function observe(){var pending=false,obs=new MutationObserver(function(){if(pending)return;pending=true;requestAnimationFrame(function(){pending=false;translateFilterTitle();translateDynamicNav();translateGrid();translateConnection();updateLibraryCopy();if(routeName()==='settings')filterSettings(U.$('settings-search-input')?U.$('settings-search-input').value:'');translateLegacy(document.body);});});obs.observe(document.body,{childList:true,subtree:true,characterData:true});}
  function init(){I.apply(document);bindRoutes();contextualSearch();syncSettingsSearch();syncRouteUI();refreshTranslations();observe();global.addEventListener('hashchange',function(){syncRouteUI();refreshTranslations();});global.addEventListener('weigg:languagechange',refreshTranslations);setTimeout(function(){syncCapabilities();refreshTranslations();},800);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})(window);
