(function(global){
  'use strict';
  var W=global.WeiG,U=W.util,I=W.I18n,T=W.t;
  if(!W||!U||!I)return;
  var columnKeys={name:'torrent.name',size:'torrent.size',progress:'torrent.progress',dlspeed:'torrent.download',upspeed:'torrent.upload',eta:'torrent.eta',state:'torrent.status',ratio:'torrent.ratio',tracker:'torrent.tracker',category:'torrent.categoryColumn'};
  var routeSearch={home:'search.torrents',torrent:'search.torrents',settings:'search.settings',search:'search.engine',rss:'search.rss',logs:'search.logs'};
  var legacyExact={'全部种子':'library.all','全部 Tracker':'tracker.all','全部路径':'path.all','全部分类':'category.all','全部标签':'tag.all','种子详情':'detail.title','正在加载…':'app.loading','命令已发送':'torrent.commandSent','文件优先级已更新':'file.updated','Peer 已封禁':'peer.banned','添加 Tracker':'tracker.add','删除':'torrent.delete','编辑':'tracker.edit','查看详情':'torrent.details','搜索引擎':'search.title','日志':'logs.title','恢复默认':'columns.reset','完成':'columns.done','取消':'app.cancel','确认':'app.confirm','添加种子':'library.add','更多操作':'torrent.actions','开始':'torrent.start','暂停':'torrent.pause','强制开始':'torrent.forceStart','重新校验':'torrent.recheck','重新汇报':'torrent.reannounce','顺序下载':'torrent.sequential','首尾块优先':'torrent.firstLast','自动管理':'torrent.autoTmm','队列置顶':'torrent.top','队列置底':'torrent.bottom','重命名':'torrent.rename','移动位置':'torrent.location','设置分类':'torrent.category','添加 Tags':'torrent.addTags','设置下载限速 KiB/s':'torrent.downloadLimit','设置上传限速 KiB/s':'torrent.uploadLimit'};
  function routeName(){var r=W.Router.route();return r.name||'home';}
  function syncRouteText(){var name=routeName(),input=U.$('search-input');if(input){input.dataset.i18nPlaceholder=routeSearch[name]||'search.torrents';input.placeholder=T(input.dataset.i18nPlaceholder);if(name!=='home'&&name!=='torrent')input.value='';}if(name==='settings')syncSettingsSearch();syncCapabilities();}
  function syncCapabilities(){['search','rss','logs'].forEach(function(cap){var nodes=U.$$('[data-capability="'+cap+'"]');if(!nodes.length)return;var hidden=nodes.some(function(n){return n.hidden;});nodes.forEach(function(n){n.hidden=hidden;});});}
  function translateGrid(){U.$$('#torrent-table-head .grid-head-cell').forEach(function(cell){var key=columnKeys[cell.dataset.key];if(!key)return;var arrow=/[↓↑]/.test(cell.textContent)?' '+(cell.textContent.indexOf('↓')>=0?'↓':'↑'):'';if(cell.firstChild)cell.firstChild.nodeValue=T(key)+arrow;});}
  function settingsOwnedNode(node){var el=node&&node.parentElement;return !!(el&&el.closest&&el.closest('#settings-view'));}
  function translateLegacyNode(node){if(!node||node.nodeType!==3||settingsOwnedNode(node))return;var raw=node.nodeValue,trim=raw.trim();if(!trim)return;var key=legacyExact[trim];if(key){var next=T(key);if(next!==trim)node.nodeValue=raw.replace(trim,next);return;}var m=trim.match(/^第\s*(\d+)\s*\/\s*([^\s]+)\s*页\s*·\s*每页\s*(\d+)$/);if(m){node.nodeValue=T('library.page',{page:m[1],pages:m[2],size:m[3]});return;}m=trim.match(/^将删除\s*(\d+)\s*个选中的种子。$/);if(m){node.nodeValue=T('torrent.deleteSelected',{count:m[1]});return;}m=trim.match(/^读取种子失败：(.*)$/);if(m){node.nodeValue=T('library.readFailed',{error:m[1]});return;}m=trim.match(/^操作失败：(.*)$/);if(m){node.nodeValue=T('torrent.actionFailed',{error:m[1]});return;}m=trim.match(/^添加失败：(.*)$/);if(m){node.nodeValue=T('torrent.addFailed',{error:m[1]});return;}}
  function translateLegacy(root){if(I.getLocale()==='zh-CN')return;var walker=document.createTreeWalker(root||document.body,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(translateLegacyNode);}
  function syncSettingsSearch(){var input=U.$('settings-search-input');if(!input||input.__weigBound)return;input.__weigBound=true;input.addEventListener('input',function(){filterSettings(input.value);});}
  function filterSettings(query){var q=String(query||'').trim().toLocaleLowerCase();U.$$('#settings-content .setting-row').forEach(function(row){var value=(row.dataset.settingSearch||row.textContent||'').toLocaleLowerCase();row.hidden=!!q&&value.indexOf(q)<0;});}
  function handleContextQuery(q){var name=routeName();if(name==='settings'){var s=U.$('settings-search-input');if(s){s.value=q;filterSettings(q);}}else if(name==='logs'||name==='rss'){var view=U.$(name+'-view');U.$$('.tool-row',view).forEach(function(row){row.hidden=!!q&&row.textContent.toLocaleLowerCase().indexOf(q.toLocaleLowerCase())<0;});}else if(name==='search'){var e=U.$('engine-query');if(e)e.value=q;}}
  function contextualSearch(){var input=U.$('search-input');if(!input||input.__weigContext)return;input.__weigContext=true;input.addEventListener('input',function(e){var name=routeName();if(name==='home'||name==='torrent')return;handleContextQuery(input.value);e.stopImmediatePropagation();},true);}
  function refreshTranslations(root){I.apply(root||document);translateGrid();translateLegacy(root||document.body);if(routeName()==='settings')filterSettings(U.$('settings-search-input')?U.$('settings-search-input').value:'');if(W.SpatialRuntime&&W.SpatialRuntime.syncFacets)W.SpatialRuntime.syncFacets();}
  function refreshDynamic(){refreshTranslations(document.body);}
  function init(){I.apply(document);contextualSearch();syncSettingsSearch();syncRouteText();refreshTranslations(document.body);global.addEventListener('hashchange',function(){syncRouteText();refreshDynamic();});global.addEventListener('weig:route-state',function(){syncRouteText();refreshDynamic();});global.addEventListener('weig:library-state',refreshDynamic);global.addEventListener('weig:settings-render',function(){syncSettingsSearch();refreshDynamic();});global.addEventListener('weig:languagechange',function(){syncRouteText();refreshDynamic();});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})(window);
